This is a python plotting test

In [1]:
import pandas as pd
import numpy as np
from StockObj import StockObj
import matplotlib.pyplot as plt
print("Hello")

Hello

Update American Market

In [2]:
with open('../tks/USAtks') as f:
    lines = f.read().splitlines()

for line in lines:
    abc = StockObj("abc", str(line) + "")
    # conn = abc.create_connection("/Users/chenyanyang/tst.db")
    conn = abc.create_connection("D:\\stks\\tst.db")
    abc.update()

No record
0
AAPLneeds update
[]
[]
15
[]
[]
0
Apr 08, 2019
['2019-04-08', '196.42', '200.22', '196.34', '200.10', '200.10', '25,881,697']
1
196.42
2
200.22
3
196.34
4
200.10
5
200.10
6
25,881,697
7
Apr 08, 2019
['2019-04-08', '196.42', '200.23', '196.34', '200.10', '200.10', '25,849,800']
8
196.42
9
200.23
10
196.34
11
200.10
12
200.10
13
25,849,800
14
2
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
BACneeds update
[]
[]
15
[]
[]
0
Apr 08, 2019
['2019-04-08', '28.89', '29.20', '28.87', '29.17', '29.17', '35,272,847']
1
28.89
2
29.20
3
28.87
4
29.17
5
29.17
6
35,272,847
7
Apr 08, 2019
['2019-04-08', '28.89', '29.20', '28.87', '29.17', '29.17', '35,267,200']
8
28.89
9
29.20
10
28.87
11
29.17
12
29.17
13
35,267,200
14
2
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
AMZNneeds update
[]
[]
15
[]
[]
0
Apr 08, 2019
['2019-04-08', '1,833.23', '1,850.20', '1,825.13', '1,849.86', '1,849.86', '3,744,185']
1
1,833.23
2
1,850.20
3
1,825.13
4
1,849.86
5
1,849.86
6
3,744,185
7
Apr 08, 2019
['2019-04-08', '1,833.23', '1,850.20', '1,825.11', '1,849.86', '1,849.86', '3,747,200']
8
1,833.23
9
1,850.20
10
1,825.11
11
1,849.86
12
1,849.86
13
3,747,200
14
2
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
Tneeds update
[]
[]
15
[]
[]
0
Apr 08, 2019
['2019-04-08', '32.45', '32.51', '32.19', '32.39', '32.39', '37,251,965']
1
32.45
2
32.51
3
32.19
4
32.39
5
32.39
6
37,251,965
7
Apr 08, 2019
['2019-04-08', '32.45', '32.52', '32.19', '32.39', '32.39', '37,225,800']
8
32.45
9
32.52
10
32.19
11
32.39
12
32.39
13
37,225,800
14
2
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
GOOGneeds update
[]
[]
15
[]
[]
0
Apr 08, 2019
['2019-04-08', '1,207.89', '1,208.69', '1,199.86', '1,203.84', '1,203.84', '860,363']
1
1,207.89
2
1,208.69
3
1,199.86
4
1,203.84
5
1,203.84
6
860,363
7
Apr 08, 2019
['2019-04-08', '1,207.89', '1,208.69', '1,199.86', '1,203.84', '1,203.84', '860,200']
8
1,207.89
9
1,208.69
10
1,199.86
11
1,203.84
12
1,203.84
13
860,200
14
2
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
MOneeds update
[]
[]
15
[]
[]
0
Apr 08, 2019
['2019-04-08', '54.77', '55.39', '54.60', '55.28', '55.28', '5,595,411']
1
54.77
2
55.39
3
54.60
4
55.28
5
55.28
6
5,595,411
7
Apr 08, 2019
['2019-04-08', '54.77', '55.39', '54.60', '55.28', '55.28', '5,607,100']
8
54.77
9
55.39
10
54.60
11
55.28
12
55.28
13
5,607,100
14
2
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
DALneeds update
[]
[]
15
[]
[]
0
Apr 08, 2019
['2019-04-08', '57.50', '57.90', '56.91', '57.71', '57.71', '7,902,065']
1
57.50
2
57.90
3
56.91
4
57.71
5
57.71
6
7,902,065
7
Apr 08, 2019
['2019-04-08', '57.50', '57.90', '56.91', '57.71', '57.71', '7,906,600']
8
57.50
9
57.90
10
56.91
11
57.71
12
57.71
13
7,906,600
14
2
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
AAneeds update
[]
[]
15
[]
[]
0
Apr 08, 2019
['2019-04-08', '29.55', '29.73', '29.32', '29.66', '29.66', '2,375,490']
1
29.55
2
29.73
3
29.32
4
29.66
5
29.66
6
2,375,490
7
Apr 08, 2019
['2019-04-08', '29.55', '29.73', '29.32', '29.66', '29.66', '2,375,100']
8
29.55
9
29.73
10
29.32
11
29.66
12
29.66
13
2,375,100
14
2
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
AXPneeds update

KeyboardInterrupt:

Update China Market

In [2]:
with open('../tks/HKtks') as f:
    lines = f.read().splitlines()

for line in lines:
    abc = StockObj("abc", str(line))
    # conn = abc.create_connection("/Users/chenyanyang/tst.db")
    conn = abc.create_connection("D:\\stks\\tst.db")
    abc.manual_update("2019-04-01", "2019-04-11")

0
2718.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.980', '3.150', '2.860', '3.010', '3.010', '36,251,441']
1
2.980
2
3.150
3
2.860
4
3.010
5
3.010
6
36,251,441
7
1
duplicate data
2. Query all tasks
0
6185.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '42.800', '43.200', '40.950', '41.450', '41.450', '940,600']
1
42.800
2
43.200
3
40.950
4
41.450
5
41.450
6
940,600
7
1
duplicate data
2. Query all tasks
0
1797.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '10.500', '10.800', '10.500', '10.600', '10.600', '5,381,500']
1
10.500
2
10.800
3
10.500
4
10.600
5
10.600
6
5,381,500
7
1
duplicate data
2. Query all tasks
0
8537.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.010', '1.070', '1.010', '1.020', '1.020', '3,666,000']
1
1.010
2
1.070
3
1.010
4
1.020
5
1.020
6
3,666,000
7
Apr 10, 2019
['2019-04-10', '1.010', '1.080', '0.980', '1.040', '1.040', '6,790,000']
8
1.010
9
1.080
10
0.980
11
1.040
12
1.040
13
6,790,000
14
Apr 09, 2019
['2019-04-09', '0.980', '1.110', '0.940', '1.010', '1.010', '15,938,500']
15
0.980
16
1.110
17
0.940
18
1.010
19
1.010
20
15,938,500
21
Apr 08, 2019
['2019-04-08', '0.920', '0.970', '0.880', '0.960', '0.960', '5,390,000']
22
0.920
23
0.970
24
0.880
25
0.960
26
0.960
27
5,390,000
28
Apr 04, 2019
['2019-04-04', '0.940', '1.020', '0.870', '0.900', '0.900', '16,068,500']
29
0.940
30
1.020
31
0.870
32
0.900
33
0.900
34
16,068,500
35
Apr 03, 2019
['2019-04-03', '0.730', '0.960', '0.720', '0.930', '0.930', '20,204,500']
36
0.730
37
0.960
38
0.720
39
0.930
40
0.930
41
20,204,500
42
Apr 02, 2019
['2019-04-02', '0.710', '0.750', '0.640', '0.730', '0.730', '6,940,000']
43
0.710
44
0.750
45
0.640
46
0.730
47
0.730
48
6,940,000
49
Apr 01, 2019
['2019-04-01', '0.780', '0.860', '0.710', '0.720', '0.720', '14,330,000']
50
0.780
51
0.860
52
0.710
53
0.720
54
0.720
55
14,330,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6819.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '5.490', '5.570', '5.410', '5.550', '5.550', '94,000']
1
5.490
2
5.570
3
5.410
4
5.550
5
5.550
6
94,000
7
1
duplicate data
2. Query all tasks
0
1865.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.690', '0.690', '0.660', '0.670', '0.670', '9,592,000']
1
0.690
2
0.690
3
0.660
4
0.670
5
0.670
6
9,592,000
7
1
duplicate data
2. Query all tasks
0
1854.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.290', '0.290', '0.290', '0.290', '0.290', '1,300,000']
1
0.290
2
0.290
3
0.290
4
0.290
5
0.290
6
1,300,000
7
Apr 10, 2019
['2019-04-10', '0.290', '0.295', '0.290', '0.295', '0.295', '120,000']
8
0.290
9
0.295
10
0.290
11
0.295
12
0.295
13
120,000
14
Apr 09, 2019
['2019-04-09', '0.285', '0.285', '0.285', '0.285', '0.285', '150,000']
15
0.285
16
0.285
17
0.285
18
0.285
19
0.285
20
150,000
21
Apr 08, 2019
['2019-04-08', '0.300', '0.300', '0.295', '0.295', '0.295', '400,000']
22
0.300
23
0.300
24
0.295
25
0.295
26
0.295
27
400,000
28
Apr 04, 2019
['2019-04-04', '0.300', '0.305', '0.300', '0.305', '0.305', '280,000']
29
0.300
30
0.305
31
0.300
32
0.305
33
0.305
34
280,000
35
Apr 03, 2019
['2019-04-03', '0.300', '0.300', '0.300', '0.300', '0.300', '790,000']
36
0.300
37
0.300
38
0.300
39
0.300
40
0.300
41
790,000
42
Apr 02, 2019
['2019-04-02', '0.290', '0.300', '0.290', '0.300', '0.300', '630,000']
43
0.290
44
0.300
45
0.290
46
0.300
47
0.300
48
630,000
49
Apr 01, 2019
['2019-04-01', '0.300', '0.300', '0.300', '0.300', '0.300', '410,000']
50
0.300
51
0.300
52
0.300
53
0.300
54
0.300
55
410,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1897.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.750', '0.760', '0.750', '0.750', '0.750', '784,947']
1
0.750
2
0.760
3
0.750
4
0.750
5
0.750
6
784,947
7
1
duplicate data
2. Query all tasks
0
3662.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.600', '4.630', '4.510', '4.600', '4.600', '3,313,959']
1
4.600
2
4.630
3
4.510
4
4.600
5
4.600
6
3,313,959
7
1
duplicate data
2. Query all tasks
0
2682.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.300', '0.310', '0.285', '0.300', '0.300', '10,380,000']
1
0.300
2
0.310
3
0.285
4
0.300
5
0.300
6
10,380,000
7
Apr 10, 2019
['2019-04-10', '0.260', '0.310', '0.260', '0.305', '0.305', '37,052,000']
8
0.260
9
0.310
10
0.260
11
0.305
12
0.305
13
37,052,000
14
Apr 09, 2019
['2019-04-09', '0.260', '0.265', '0.260', '0.265', '0.265', '3,772,000']
15
0.260
16
0.265
17
0.260
18
0.265
19
0.265
20
3,772,000
21
Apr 08, 2019
['2019-04-08', '0.270', '0.275', '0.260', '0.265', '0.265', '6,948,000']
22
0.270
23
0.275
24
0.260
25
0.265
26
0.265
27
6,948,000
28
Apr 04, 2019
['2019-04-04', '0.275', '0.280', '0.270', '0.270', '0.270', '2,384,000']
29
0.275
30
0.280
31
0.270
32
0.270
33
0.270
34
2,384,000
35
Apr 03, 2019
['2019-04-03', '0.280', '0.280', '0.275', '0.275', '0.275', '4,024,000']
36
0.280
37
0.280
38
0.275
39
0.275
40
0.275
41
4,024,000
42
Apr 02, 2019
['2019-04-02', '0.280', '0.285', '0.275', '0.275', '0.275', '3,404,000']
43
0.280
44
0.285
45
0.275
46
0.275
47
0.275
48
3,404,000
49
Apr 01, 2019
['2019-04-01', '0.275', '0.295', '0.275', '0.280', '0.280', '8,848,000']
50
0.275
51
0.295
52
0.275
53
0.280
54
0.280
55
8,848,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3316.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '6.980', '7.010', '6.880', '6.980', '6.980', '277,500']
1
6.980
2
7.010
3
6.880
4
6.980
5
6.980
6
277,500
7
1
duplicate data
2. Query all tasks
No record
0
1907.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.960', '3.040', '2.900', '2.980', '2.980', '2,214,000']
1
2.960
2
3.040
3
2.900
4
2.980
5
2.980
6
2,214,000
7
1
duplicate data
2. Query all tasks
0
1563.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.870', '0.890', '0.860', '0.870', '0.870', '9,264,000']
1
0.870
2
0.890
3
0.860
4
0.870
5
0.870
6
9,264,000
7
1
duplicate data
2. Query all tasks
0
1891.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.325', '0.340', '0.305', '0.325', '0.325', '15,632,000']
1
0.325
2
0.340
3
0.305
4
0.325
5
0.325
6
15,632,000
7
1
duplicate data
2. Query all tasks
0
1917.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.740', '0.780', '0.670', '0.680', '0.680', '92,010,000']
1
0.740
2
0.780
3
0.670
4
0.680
5
0.680
6
92,010,000
7
1
duplicate data
2. Query all tasks
0
1158.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '15.980', '16.000', '15.700', '15.860', '15.860', '154,200']
1
15.980
2
16.000
3
15.700
4
15.860
5
15.860
6
154,200
7
1
duplicate data
2. Query all tasks
0
0150.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.850', '0.860', '0.830', '0.840', '0.840', '910,000']
1
0.850
2
0.860
3
0.830
4
0.840
5
0.840
6
910,000
7
Apr 10, 2019
['2019-04-10', '0.850', '0.850', '0.820', '0.850', '0.850', '1,640,000']
8
0.850
9
0.850
10
0.820
11
0.850
12
0.850
13
1,640,000
14
Apr 09, 2019
['2019-04-09', '0.830', '0.850', '0.820', '0.850', '0.850', '1,400,000']
15
0.830
16
0.850
17
0.820
18
0.850
19
0.850
20
1,400,000
21
Apr 08, 2019
['2019-04-08', '0.850', '0.900', '0.810', '0.830', '0.830', '9,280,000']
22
0.850
23
0.900
24
0.810
25
0.830
26
0.830
27
9,280,000
28
Apr 04, 2019
['2019-04-04', '0.830', '0.860', '0.820', '0.850', '0.850', '2,950,000']
29
0.830
30
0.860
31
0.820
32
0.850
33
0.850
34
2,950,000
35
Apr 03, 2019
['2019-04-03', '0.790', '0.830', '0.770', '0.820', '0.820', '2,020,000']
36
0.790
37
0.830
38
0.770
39
0.820
40
0.820
41
2,020,000
42
Apr 02, 2019
['2019-04-02', '0.790', '0.790', '0.790', '0.790', '0.790', '140,000']
43
0.790
44
0.790
45
0.790
46
0.790
47
0.790
48
140,000
49
Apr 01, 2019
['2019-04-01', '0.780', '0.810', '0.780', '0.800', '0.800', '1,080,000']
50
0.780
51
0.810
52
0.780
53
0.800
54
0.800
55
1,080,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2108.HKneeds update

[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.425', '0.440', '0.405', '0.410', '0.410', '10,108,000']
1
0.425
2
0.440
3
0.405
4
0.410
5
0.410
6
10,108,000
7
1
duplicate data
2. Query all tasks
0
1902.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.370', '2.370', '2.340', '2.350', '2.350', '240,000']
1
2.370
2
2.370
3
2.340
4
2.350
5
2.350
6
240,000
7
1
duplicate data
2. Query all tasks
0
1872.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.800', '1.800', '1.580', '1.710', '1.710', '1,450,000']
1
1.800
2
1.800
3
1.580
4
1.710
5
1.710
6
1,450,000
7
1
duplicate data
2. Query all tasks
0
1025.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.480', '3.760', '3.480', '3.620', '3.620', '580,000']
1
3.480
2
3.760
3
3.480
4
3.620
5
3.620
6
580,000
7
1
duplicate data
2. Query all tasks
0
1793.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.510', '0.520', '0.480', '0.480', '0.480', '3,668,000']
1
0.510
2
0.520
3
0.480
4
0.480
5
0.480
6
3,668,000
7
1
duplicate data
2. Query all tasks
0
8607.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.480', '0.485', '0.470', '0.480', '0.480', '935,000']
1
0.480
2
0.485
3
0.470
4
0.480
5
0.480
6
935,000
7
1
duplicate data
2. Query all tasks
0
2616.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '16.460', '16.460', '15.740', '15.860', '15.860', '259,500']
1
16.460
2
16.460
3
15.740
4
15.860
5
15.860
6
259,500
7
Apr 10, 2019
['2019-04-10', '16.500', '16.500', '16.100', '16.280', '16.280', '498,000']
8
16.500
9
16.500
10
16.100
11
16.280
12
16.280
13
498,000
14
Apr 09, 2019
['2019-04-09', '16.300', '16.440', '16.020', '16.400', '16.400', '671,000']
15
16.300
16
16.440
17
16.020
18
16.400
19
16.400
20
671,000
21
Apr 08, 2019
['2019-04-08', '16.060', '16.460', '15.900', '16.380', '16.380', '640,500']
22
16.060
23
16.460
24
15.900
25
16.380
26
16.380
27
640,500
28
Apr 04, 2019
['2019-04-04', '16.000', '16.200', '15.700', '16.040', '16.040', '379,500']
29
16.000
30
16.200
31
15.700
32
16.040
33
16.040
34
379,500
35
Apr 03, 2019
['2019-04-03', '16.400', '16.660', '15.960', '16.000', '16.000', '894,192']
36
16.400
37
16.660
38
15.960
39
16.000
40
16.000
41
894,192
42
Apr 02, 2019
['2019-04-02', '16.000', '16.900', '16.000', '16.340', '16.340', '2,421,000']
43
16.000
44
16.900
45
16.000
46
16.340
47
16.340
48
2,421,000
49
Apr 01, 2019
['2019-04-01', '16.000', '16.000', '15.680', '15.860', '15.860', '244,500']
50
16.000
51
16.000
52
15.680
53
15.860
54
15.860
55
244,500
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2019.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.900', '3.040', '2.880', '2.900', '2.900', '3,914,000']
1
2.900
2
3.040
3
2.880
4
2.900
5
2.900
6
3,914,000
7
1
duplicate data
2. Query all tasks
0
8036.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.214', '0.214', '0.208', '0.208', '0.208', '710,000']
1
0.214
2
0.214
3
0.208
4
0.208
5
0.208
6
710,000
7
Apr 10, 2019
['2019-04-10', '0.210', '0.218', '0.205', '0.211', '0.211', '3,310,000']
8
0.210
9
0.218
10
0.205
11
0.211
12
0.211
13
3,310,000
14
Apr 09, 2019
['2019-04-09', '0.202', '0.218', '0.201', '0.209', '0.209', '3,264,100']
15
0.202
16
0.218
17
0.201
18
0.209
19
0.209
20
3,264,100
21
Apr 08, 2019
['2019-04-08', '0.205', '0.209', '0.201', '0.204', '0.204', '1,280,000']
22
0.205
23
0.209
24
0.201
25
0.204
26
0.204
27
1,280,000
28
Apr 04, 2019
['2019-04-04', '0.214', '0.214', '0.201', '0.208', '0.208', '1,120,000']
29
0.214
30
0.214
31
0.201
32
0.208
33
0.208
34
1,120,000
35
Apr 03, 2019
['2019-04-03', '0.204', '0.222', '0.200', '0.210', '0.210', '4,730,000']
36
0.204
37
0.222
38
0.200
39
0.210
40
0.210
41
4,730,000
42
Apr 02, 2019
['2019-04-02', '0.204', '0.209', '0.203', '0.204', '0.204', '1,860,000']
43
0.204
44
0.209
45
0.203
46
0.204
47
0.204
48
1,860,000
49
Apr 01, 2019
['2019-04-01', '0.205', '0.205', '0.201', '0.201', '0.201', '1,650,000']
50
0.205
51
0.205
52
0.201
53
0.201
54
0.201
55
1,650,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1827.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.530', '1.530', '1.490', '1.520', '1.520', '100,000']
1
1.530
2
1.530
3
1.490
4
1.520
5
1.520
6
100,000
7
Apr 10, 2019
['2019-04-10', '1.440', '1.540', '1.440', '1.530', '1.530', '360,000']
8
1.440
9
1.540
10
1.440
11
1.530
12
1.530
13
360,000
14
Apr 09, 2019
['2019-04-09', '1.450', '1.480', '1.420', '1.440', '1.440', '140,000']
15
1.450
16
1.480
17
1.420
18
1.440
19
1.440
20
140,000
21
Apr 08, 2019
['2019-04-08', '1.410', '1.420', '1.410', '1.420', '1.420', '70,000']
22
1.410
23
1.420
24
1.410
25
1.420
26
1.420
27
70,000
28
Apr 04, 2019
['2019-04-04', '1.450', '1.450', '1.450', '1.450', '1.450', '-']
29
1.450
30
1.450
31
1.450
32
1.450
33
1.450
34
-
35
Apr 03, 2019
['2019-04-03', '1.450', '1.450', '1.450', '1.450', '1.450', '-']
36
1.450
37
1.450
38
1.450
39
1.450
40
1.450
41
-
42
Apr 02, 2019
['2019-04-02', '1.490', '1.490', '1.450', '1.450', '1.450', '110,000']
43
1.490
44
1.490
45
1.450
46
1.450
47
1.450
48
110,000
49
Apr 01, 2019
['2019-04-01', '1.450', '1.450', '1.450', '1.450', '1.450', '-']
50
1.450
51
1.450
52
1.450
53
1.450
54
1.450
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1703.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.510', '0.510', '0.500', '0.500', '0.500', '3,840,000']
1
0.510
2
0.510
3
0.500
4
0.500
5
0.500
6
3,840,000
7
1
duplicate data
2. Query all tasks
0
1850.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.365', '0.370', '0.365', '0.370', '0.370', '90,000']
1
0.365
2
0.370
3
0.365
4
0.370
5
0.370
6
90,000
7
Apr 10, 2019
['2019-04-10', '0.360', '0.385', '0.360', '0.380', '0.380', '180,000']
8
0.360
9
0.385
10
0.360
11
0.380
12
0.380
13
180,000
14
Apr 09, 2019
['2019-04-09', '0.385', '0.385', '0.385', '0.385', '0.385', '-']
15
0.385
16
0.385
17
0.385
18
0.385
19
0.385
20
-
21
Apr 08, 2019
['2019-04-08', '0.385', '0.385', '0.385', '0.385', '0.385', '100,000']
22
0.385
23
0.385
24
0.385
25
0.385
26
0.385
27
100,000
28
Apr 04, 2019
['2019-04-04', '0.385', '0.395', '0.385', '0.390', '0.390', '260,000']
29
0.385
30
0.395
31
0.385
32
0.390
33
0.390
34
260,000
35
Apr 03, 2019
['2019-04-03', '0.380', '0.380', '0.380', '0.380', '0.380', '10,000']
36
0.380
37
0.380
38
0.380
39
0.380
40
0.380
41
10,000
42
Apr 02, 2019
['2019-04-02', '0.390', '0.390', '0.390', '0.390', '0.390', '110,000']
43
0.390
44
0.390
45
0.390
46
0.390
47
0.390
48
110,000
49
Apr 01, 2019
['2019-04-01', '0.385', '0.405', '0.380', '0.390', '0.390', '390,000']
50
0.385
51
0.405
52
0.380
53
0.390
54
0.390
55
390,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1896.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '16.760', '16.760', '16.000', '16.200', '16.200', '340,800']
1
16.760
2
16.760
3
16.000
4
16.200
5
16.200
6
340,800
7
1
duplicate data
2. Query all tasks
0
1890.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.660', '3.770', '3.510', '3.520', '3.520', '2,696,000']
1
3.660
2
3.770
3
3.510
4
3.520
5
3.520
6
2,696,000
7
1
duplicate data
2. Query all tasks
0
1851.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.180', '2.220', '2.170', '2.190', '2.190', '208,000']
1
2.180
2
2.220
3
2.170
4
2.190
5
2.190
6
208,000
7
1
duplicate data
2. Query all tasks
0
6162.HKneeds update

[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.156', '0.156', '0.151', '0.153', '0.153', '1,160,000']
1
0.156
2
0.156
3
0.151
4
0.153
5
0.153
6
1,160,000
7
1
duplicate data
2. Query all tasks
0
2013.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '5.710', '6.040', '5.500', '5.600', '5.600', '16,312,150']
1
5.710
2
6.040
3
5.500
4
5.600
5
5.600
6
16,312,150
7
1
duplicate data
2. Query all tasks
0
1785.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.220', '2.300', '2.200', '2.210', '2.210', '76,000']
1
2.220
2
2.300
3
2.200
4
2.210
5
2.210
6
76,000
7
1
duplicate data
2. Query all tasks
0
1767.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.760', '0.770', '0.760', '0.760', '0.760', '940,000']
1
0.760
2
0.770
3
0.760
4
0.760
5
0.760
6
940,000
7
1
duplicate data
2. Query all tasks
0
2885.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.580', '0.580', '0.560', '0.580', '0.580', '1,388,000']
1
0.580
2
0.580
3
0.560
4
0.580
5
0.580
6
1,388,000
7
1
duplicate data
2. Query all tasks
0
2360.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.920', '3.920', '3.850', '3.920', '3.920', '1,146,000']
1
3.920
2
3.920
3
3.850
4
3.920
5
3.920
6
1,146,000
7
1
duplicate data
2. Query all tasks
0
1841.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.930', '0.950', '0.920', '0.950', '0.950', '270,000']
1
0.930
2
0.950
3
0.920
4
0.950
5
0.950
6
270,000
7
Apr 10, 2019
['2019-04-10', '0.940', '0.960', '0.940', '0.950', '0.950', '140,000']
8
0.940
9
0.960
10
0.940
11
0.950
12
0.950
13
140,000
14
Apr 09, 2019
['2019-04-09', '0.960', '0.960', '0.960', '0.960', '0.960', '20,000']
15
0.960
16
0.960
17
0.960
18
0.960
19
0.960
20
20,000
21
Apr 08, 2019
['2019-04-08', '0.960', '0.990', '0.950', '0.980', '0.980', '540,000']
22
0.960
23
0.990
24
0.950
25
0.980
26
0.980
27
540,000
28
Apr 04, 2019
['2019-04-04', '0.960', '0.960', '0.950', '0.950', '0.950', '220,000']
29
0.960
30
0.960
31
0.950
32
0.950
33
0.950
34
220,000
35
Apr 03, 2019
['2019-04-03', '0.950', '0.950', '0.920', '0.940', '0.940', '160,000']
36
0.950
37
0.950
38
0.920
39
0.940
40
0.940
41
160,000
42
Apr 02, 2019
['2019-04-02', '0.920', '0.950', '0.920', '0.950', '0.950', '210,000']
43
0.920
44
0.950
45
0.920
46
0.950
47
0.950
48
210,000
49
Apr 01, 2019
['2019-04-01', '0.900', '0.920', '0.900', '0.920', '0.920', '300,000']
50
0.900
51
0.920
52
0.900
53
0.920
54
0.920
55
300,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8631.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.380', '0.390', '0.380', '0.385', '0.385', '830,000']
1
0.380
2
0.390
3
0.380
4
0.385
5
0.385
6
830,000
7
1
duplicate data
2. Query all tasks
0
1743.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '16.880', '17.000', '16.840', '16.840', '16.840', '38,400']
1
16.880
2
17.000
3
16.840
4
16.840
5
16.840
6
38,400
7
Apr 10, 2019
['2019-04-10', '16.980', '17.100', '16.700', '16.880', '16.880', '38,800']
8
16.980
9
17.100
10
16.700
11
16.880
12
16.880
13
38,800
14
Apr 09, 2019
['2019-04-09', '16.620', '17.180', '16.620', '16.980', '16.980', '91,400']
15
16.620
16
17.180
17
16.620
18
16.980
19
16.980
20
91,400
21
Apr 08, 2019
['2019-04-08', '16.140', '17.400', '16.140', '16.620', '16.620', '79,800']
22
16.140
23
17.400
24
16.140
25
16.620
26
16.620
27
79,800
28
Apr 04, 2019
['2019-04-04', '15.800', '16.200', '15.760', '16.140', '16.140', '58,800']
29
15.800
30
16.200
31
15.760
32
16.140
33
16.140
34
58,800
35
Apr 03, 2019
['2019-04-03', '15.240', '15.820', '15.220', '15.800', '15.800', '44,400']
36
15.240
37
15.820
38
15.220
39
15.800
40
15.800
41
44,400
42
Apr 02, 2019
['2019-04-02', '15.100', '15.260', '15.100', '15.200', '15.200', '39,000']
43
15.100
44
15.260
45
15.100
46
15.200
47
15.200
48
39,000
49
Apr 01, 2019
['2019-04-01', '14.980', '15.120', '14.960', '15.100', '15.100', '37,800']
50
14.980
51
15.120
52
14.960
53
15.100
54
15.100
55
37,800
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6058.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.710', '0.710', '0.710', '0.710', '0.710', '-']
1
0.710
2
0.710
3
0.710
4
0.710
5
0.710
6
-
7
Apr 10, 2019
['2019-04-10', '0.770', '0.770', '0.770', '0.770', '0.770', '-']
8
0.770
9
0.770
10
0.770
11
0.770
12
0.770
13
-
14
Apr 09, 2019
['2019-04-09', '0.760', '0.760', '0.760', '0.750', '0.750', '76,000']
15
0.760
16
0.760
17
0.760
18
0.750
19
0.750
20
76,000
21
Apr 08, 2019
['2019-04-08', '0.720', '0.740', '0.720', '0.740', '0.740', '106,000']
22
0.720
23
0.740
24
0.720
25
0.740
26
0.740
27
106,000
28
Apr 04, 2019
['2019-04-04', '0.730', '0.730', '0.730', '0.730', '0.730', '-']
29
0.730
30
0.730
31
0.730
32
0.730
33
0.730
34
-
35
Apr 03, 2019
['2019-04-03', '0.730', '0.730', '0.730', '0.730', '0.730', '188,000']
36
0.730
37
0.730
38
0.730
39
0.730
40
0.730
41
188,000
42
Apr 02, 2019
['2019-04-02', '0.740', '0.740', '0.740', '0.740', '0.740', '-']
43
0.740
44
0.740
45
0.740
46
0.740
47
0.740
48
-
49
Apr 01, 2019
['2019-04-01', '0.720', '0.720', '0.720', '0.720', '0.720', '-']
50
0.720
51
0.720
52
0.720
53
0.720
54
0.720
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1845.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.970', '0.990', '0.960', '0.970', '0.970', '1,515,000']
1
0.970
2
0.990
3
0.960
4
0.970
5
0.970
6
1,515,000
7
1
duplicate data
2. Query all tasks
0
1796.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.100', '1.100', '1.080', '1.090', '1.090', '212,000']
1
1.100
2
1.100
3
1.080
4
1.090
5
1.090
6
212,000
7
Apr 10, 2019
['2019-04-10', '1.070', '1.090', '1.060', '1.060', '1.060', '80,000']
8
1.070
9
1.090
10
1.060
11
1.060
12
1.060
13
80,000
14
Apr 09, 2019
['2019-04-09', '1.100', '1.100', '1.070', '1.070', '1.070', '102,000']
15
1.100
16
1.100
17
1.070
18
1.070
19
1.070
20
102,000
21
Apr 08, 2019
['2019-04-08', '1.100', '1.100', '1.100', '1.100', '1.100', '-']
22
1.100
23
1.100
24
1.100
25
1.100
26
1.100
27
-
28
Apr 04, 2019
['2019-04-04', '1.090', '1.100', '1.080', '1.090', '1.090', '234,000']
29
1.090
30
1.100
31
1.080
32
1.090
33
1.090
34
234,000
35
Apr 03, 2019
['2019-04-03', '1.090', '1.150', '1.090', '1.100', '1.100', '766,000']
36
1.090
37
1.150
38
1.090
39
1.100
40
1.100
41
766,000
42
Apr 02, 2019
['2019-04-02', '1.050', '1.190', '1.050', '1.070', '1.070', '2,516,000']
43
1.050
44
1.190
45
1.050
46
1.070
47
1.070
48
2,516,000
49
Apr 01, 2019
['2019-04-01', '1.030', '1.030', '1.030', '1.030', '1.030', '2,000']
50
1.030
51
1.030
52
1.030
53
1.030
54
1.030
55
2,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1759.HKneeds update
[]
[]
8
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.120', '3.120', '3.090', '3.090', '3.090', '31,000']
1
3.120
2
3.120
3
3.090
4
3.090
5
3.090
6
31,000
7
1
duplicate data
2. Query all tasks
0
1713.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.470', '2.690', '2.470', '2.580', '2.580', '566,000']
1
2.470
2
2.690
3
2.470
4
2.580
5
2.580
6
566,000
7
Apr 10, 2019
['2019-04-10', '2.090', '2.380', '2.090', '2.370', '2.370', '412,000']
8
2.090
9
2.380
10
2.090
11
2.370
12
2.370
13
412,000
14
Apr 09, 2019
['2019-04-09', '1.960', '2.080', '1.960', '2.070', '2.070', '20,000']
15
1.960
16
2.080
17
1.960
18
2.070
19
2.070
20
20,000
21
Apr 08, 2019
['2019-04-08', '2.120', '2.120', '1.940', '1.940', '1.940', '80,000']
22
2.120
23
2.120
24
1.940
25
1.940
26
1.940
27
80,000
28
Apr 04, 2019
['2019-04-04', '2.120', '2.120', '2.080', '2.080', '2.080', '56,000']
29
2.120
30
2.120
31
2.080
32
2.080
33
2.080
34
56,000
35
Apr 03, 2019
['2019-04-03', '2.170', '2.200', '2.110', '2.110', '2.110', '106,000']
36
2.170
37
2.200
38
2.110
39
2.110
40
2.110
41
106,000
42
Apr 02, 2019
['2019-04-02', '2.050', '2.220', '2.050', '2.170', '2.170', '88,000']
43
2.050
44
2.220
45
2.050
46
2.170
47
2.170
48
88,000
49
Apr 01, 2019
['2019-04-01', '2.010', '2.070', '2.010', '2.050', '2.050', '166,000']
50
2.010
51
2.070
52
2.010
53
2.050
54
2.050
55
166,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3978.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.640', '3.640', '3.640', '3.640', '3.640', '-']
1
3.640
2
3.640
3
3.640
4
3.640
5
3.640
6
-
7
Apr 10, 2019
['2019-04-10', '3.630', '3.670', '3.630', '3.640', '3.640', '443,311']
8
3.630
9
3.670
10
3.630
11
3.640
12
3.640
13
443,311
14
Apr 09, 2019
['2019-04-09', '3.520', '3.650', '3.520', '3.640', '3.640', '115,000']
15
3.520
16
3.650
17
3.520
18
3.640
19
3.640
20
115,000
21
Apr 08, 2019
['2019-04-08', '3.560', '3.560', '3.520', '3.520', '3.520', '21,000']
22
3.560
23
3.560
24
3.520
25
3.520
26
3.520
27
21,000
28
Apr 04, 2019
['2019-04-04', '3.570', '3.570', '3.550', '3.550', '3.550', '186,000']
29
3.570
30
3.570
31
3.550
32
3.550
33
3.550
34
186,000
35
Apr 03, 2019
['2019-04-03', '3.630', '3.650', '3.560', '3.650', '3.650', '234,000']
36
3.630
37
3.650
38
3.560
39
3.650
40
3.650
41
234,000
42
Apr 02, 2019
['2019-04-02', '3.590', '3.630', '3.590', '3.630', '3.630', '212,000']
43
3.590
44
3.630
45
3.590
46
3.630
47
3.630
48
212,000
49
Apr 01, 2019
['2019-04-01', '3.540', '3.690', '3.540', '3.590', '3.590', '237,000']
50
3.540
51
3.690
52
3.540
53
3.590
54
3.590
55
237,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1877.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '31.800', '32.000', '30.800', '31.050', '31.050', '617,000']
1
31.800
2
32.000
3
30.800
4
31.050
5
31.050
6
617,000
7
Apr 10, 2019
['2019-04-10', '31.900', '32.250', '31.500', '31.900', '31.900', '428,000']
8
31.900
9
32.250
10
31.500
11
31.900
12
31.900
13
428,000
14
Apr 09, 2019
['2019-04-09', '30.700', '31.750', '30.650', '31.750', '31.750', '508,000']
15
30.700
16
31.750
17
30.650
18
31.750
19
31.750
20
508,000
21
Apr 08, 2019
['2019-04-08', '31.150', '31.150', '30.450', '30.750', '30.750', '526,000']
22
31.150
23
31.150
24
30.450
25
30.750
26
30.750
27
526,000
28
Apr 04, 2019
['2019-04-04', '31.950', '32.550', '30.200', '30.800', '30.800', '716,000']
29
31.950
30
32.550
31
30.200
32
30.800
33
30.800
34
716,000
35
Apr 03, 2019
['2019-04-03', '31.500', '31.650', '30.000', '30.950', '30.950', '429,000']
36
31.500
37
31.650
38
30.000
39
30.950
40
30.950
41
429,000
42
Apr 02, 2019
['2019-04-02', '30.700', '32.250', '30.700', '31.500', '31.500', '215,000']
43
30.700
44
32.250
45
30.700
46
31.500
47
31.500
48
215,000
49
Apr 01, 2019
['2019-04-01', '29.850', '30.700', '29.850', '30.450', '30.450', '209,532']
50
29.850
51
30.700
52
29.850
53
30.450
54
30.450
55
209,532
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1820.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.330', '4.360', '4.330', '4.360', '4.360', '40,000']
1
4.330
2
4.360
3
4.330
4
4.360
5
4.360
6
40,000
7
Apr 10, 2019
['2019-04-10', '4.390', '4.400', '4.280', '4.360', '4.360', '72,000']
8
4.390
9
4.400
10
4.280
11
4.360
12
4.360
13
72,000
14
Apr 09, 2019
['2019-04-09', '4.400', '4.400', '4.300', '4.390', '4.390', '57,000']
15
4.400
16
4.400
17
4.300
18
4.390
19
4.390
20
57,000
21
Apr 08, 2019
['2019-04-08', '4.590', '4.590', '4.420', '4.420', '4.420', '19,000']
22
4.590
23
4.590
24
4.420
25
4.420
26
4.420
27
19,000
28
Apr 04, 2019
['2019-04-04', '4.400', '4.510', '4.210', '4.490', '4.490', '40,000']
29
4.400
30
4.510
31
4.210
32
4.490
33
4.490
34
40,000
35
Apr 03, 2019
['2019-04-03', '4.710', '4.710', '4.500', '4.700', '4.700', '111,000']
36
4.710
37
4.710
38
4.500
39
4.700
40
4.700
41
111,000
42
Apr 02, 2019
['2019-04-02', '4.700', '4.700', '4.700', '4.700', '4.700', '-']
43
4.700
44
4.700
45
4.700
46
4.700
47
4.700
48
-
49
Apr 01, 2019
['2019-04-01', '4.550', '4.550', '4.550', '4.550', '4.550', '48,000']
50
4.550
51
4.550
52
4.550
53
4.550
54
4.550
55
48,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1762.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.790', '4.800', '4.550', '4.620', '4.620', '463,000']
1
4.790
2
4.800
3
4.550
4
4.620
5
4.620
6
463,000
7
Apr 10, 2019
['2019-04-10', '4.750', '4.790', '4.620', '4.740', '4.740', '494,000']
8
4.750
9
4.790
10
4.620
11
4.740
12
4.740
13
494,000
14
Apr 09, 2019
['2019-04-09', '4.820', '4.870', '4.730', '4.750', '4.750', '531,000']
15
4.820
16
4.870
17
4.730
18
4.750
19
4.750
20
531,000
21
Apr 08, 2019
['2019-04-08', '4.660', '4.870', '4.620', '4.820', '4.820', '1,121,000']
22
4.660
23
4.870
24
4.620
25
4.820
26
4.820
27
1,121,000
28
Apr 04, 2019
['2019-04-04', '4.730', '4.730', '4.400', '4.610', '4.610', '2,099,000']
29
4.730
30
4.730
31
4.400
32
4.610
33
4.610
34
2,099,000
35
Apr 03, 2019
['2019-04-03', '4.870', '4.920', '4.650', '4.730', '4.730', '3,066,000']
36
4.870
37
4.920
38
4.650
39
4.730
40
4.730
41
3,066,000
42
Apr 02, 2019
['2019-04-02', '4.810', '4.880', '4.720', '4.820', '4.820', '1,215,000']
43
4.810
44
4.880
45
4.720
46
4.820
47
4.820
48
1,215,000
49
Apr 01, 2019
['2019-04-01', '5.060', '5.150', '4.750', '4.820', '4.820', '1,969,000']
50
5.060
51
5.150
52
4.750
53
4.820
54
4.820
55
1,969,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2892.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.390', '1.390', '1.390', '1.390', '1.390', '-']
1
1.390
2
1.390
3
1.390
4
1.390
5
1.390
6
-
7
Apr 10, 2019
['2019-04-10', '1.360', '1.360', '1.360', '1.360', '1.360', '-']
8
1.360
9
1.360
10
1.360
11
1.360
12
1.360
13
-
14
Apr 09, 2019
['2019-04-09', '1.360', '1.360', '1.360', '1.360', '1.360', '-']
15
1.360
16
1.360
17
1.360
18
1.360
19
1.360
20
-
21
Apr 08, 2019
['2019-04-08', '1.350', '1.360', '1.350', '1.360', '1.360', '4,000']
22
1.350
23
1.360
24
1.350
25
1.360
26
1.360
27
4,000
28
Apr 04, 2019
['2019-04-04', '1.350', '1.350', '1.350', '1.350', '1.350', '-']
29
1.350
30
1.350
31
1.350
32
1.350
33
1.350
34
-
35
Apr 03, 2019
['2019-04-03', '1.380', '1.380', '1.380', '1.380', '1.380', '22,000']
36
1.380
37
1.380
38
1.380
39
1.380
40
1.380
41
22,000
42
Apr 02, 2019
['2019-04-02', '1.310', '1.350', '1.310', '1.370', '1.370', '68,000']
43
1.310
44
1.350
45
1.310
46
1.370
47
1.370
48
68,000
49
Apr 01, 2019
['2019-04-01', '1.300', '1.350', '1.300', '1.320', '1.320', '84,000']
50
1.300
51
1.350
52
1.300
53
1.320
54
1.320
55
84,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1675.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '9.500', '9.500', '9.400', '9.400', '9.400', '19,200']
1
9.500
2
9.500
3
9.400
4
9.400
5
9.400
6
19,200
7
Apr 10, 2019
['2019-04-10', '9.070', '9.330', '9.070', '9.330', '9.330', '15,200']
8
9.070
9
9.330
10
9.070
11
9.330
12
9.330
13
15,200
14
Apr 09, 2019
['2019-04-09', '9.240', '9.300', '9.230', '9.230', '9.230', '18,800']
15
9.240
16
9.300
17
9.230
18
9.230
19
9.230
20
18,800
21
Apr 08, 2019
['2019-04-08', '9.300', '9.300', '9.250', '9.250', '9.250', '10,800']
22
9.300
23
9.300
24
9.250
25
9.250
26
9.250
27
10,800
28
Apr 04, 2019
['2019-04-04', '9.410', '9.410', '9.250', '9.250', '9.250', '37,600']
29
9.410
30
9.410
31
9.250
32
9.250
33
9.250
34
37,600
35
Apr 03, 2019
['2019-04-03', '9.230', '9.230', '9.230', '9.230', '9.230', '-']
36
9.230
37
9.230
38
9.230
39
9.230
40
9.230
41
-
42
Apr 02, 2019
['2019-04-02', '9.500', '9.520', '9.110', '9.110', '9.110', '53,200']
43
9.500
44
9.520
45
9.110
46
9.110
47
9.110
48
53,200
49
Apr 01, 2019
['2019-04-01', '9.000', '9.530', '9.000', '9.500', '9.500', '132,240']
50
9.000
51
9.530
52
9.000
53
9.500
54
9.500
55
132,240
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1995.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.150', '3.190', '3.120', '3.150', '3.150', '1,960,000']
1
3.150
2
3.190
3
3.120
4
3.150
5
3.150
6
1,960,000
7
Apr 10, 2019
['2019-04-10', '3.200', '3.250', '3.160', '3.200', '3.200', '1,542,000']
8
3.200
9
3.250
10
3.160
11
3.200
12
3.200
13
1,542,000
14
Apr 09, 2019
['2019-04-09', '3.080', '3.280', '3.060', '3.230', '3.230', '2,594,000']
15
3.080
16
3.280
17
3.060
18
3.230
19
3.230
20
2,594,000
21
Apr 08, 2019
['2019-04-08', '3.120', '3.230', '3.100', '3.130', '3.130', '2,262,000']
22
3.120
23
3.230
24
3.100
25
3.130
26
3.130
27
2,262,000
28
Apr 04, 2019
['2019-04-04', '3.280', '3.280', '3.120', '3.190', '3.190', '5,058,000']
29
3.280
30
3.280
31
3.120
32
3.190
33
3.190
34
5,058,000
35
Apr 03, 2019
['2019-04-03', '3.290', '3.340', '3.230', '3.260', '3.260', '5,198,000']
36
3.290
37
3.340
38
3.230
39
3.260
40
3.260
41
5,198,000
42
Apr 02, 2019
['2019-04-02', '3.450', '3.480', '3.110', '3.380', '3.380', '6,992,000']
43
3.450
44
3.480
45
3.110
46
3.380
47
3.380
48
6,992,000
49
Apr 01, 2019
['2019-04-01', '3.320', '3.650', '3.270', '3.380', '3.380', '30,416,000']
50
3.320
51
3.650
52
3.270
53
3.380
54
3.380
55
30,416,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1983.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.040', '3.090', '3.040', '3.090', '3.090', '5,000']
1
3.040
2
3.090
3
3.040
4
3.090
5
3.090
6
5,000
7
Apr 10, 2019
['2019-04-10', '3.030', '3.030', '3.030', '3.030', '3.030', '-']
8
3.030
9
3.030
10
3.030
11
3.030
12
3.030
13
-
14
Apr 09, 2019
['2019-04-09', '3.050', '3.050', '3.030', '3.030', '3.030', '13,000']
15
3.050
16
3.050
17
3.030
18
3.030
19
3.030
20
13,000
21
Apr 08, 2019
['2019-04-08', '3.060', '3.060', '3.060', '3.060', '3.060', '-']
22
3.060
23
3.060
24
3.060
25
3.060
26
3.060
27
-
28
Apr 04, 2019
['2019-04-04', '3.070', '3.070', '3.070', '3.070', '3.070', '-']
29
3.070
30
3.070
31
3.070
32
3.070
33
3.070
34
-
35
Apr 03, 2019
['2019-04-03', '3.070', '3.070', '3.070', '3.070', '3.070', '-']
36
3.070
37
3.070
38
3.070
39
3.070
40
3.070
41
-
42
Apr 02, 2019
['2019-04-02', '2.870', '2.870', '2.870', '2.880', '2.880', '1,000']
43
2.870
44
2.870
45
2.870
46
2.880
47
2.880
48
1,000
49
Apr 01, 2019
['2019-04-01', '2.880', '2.880', '2.840', '2.840', '2.840', '10,000']
50
2.880
51
2.880
52
2.840
53
2.840
54
2.840
55
10,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1992.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '14.880', '14.880', '14.700', '14.800', '14.800', '16,000']
1
14.880
2
14.880
3
14.700
4
14.800
5
14.800
6
16,000
7
Apr 10, 2019
['2019-04-10', '14.700', '15.040', '14.700', '14.880', '14.880', '66,000']
8
14.700
9
15.040
10
14.700
11
14.880
12
14.880
13
66,000
14
Apr 09, 2019
['2019-04-09', '14.880', '14.880', '14.200', '14.520', '14.520', '130,225']
15
14.880
16
14.880
17
14.200
18
14.520
19
14.520
20
130,225
21
Apr 08, 2019
['2019-04-08', '15.060', '15.180', '14.880', '14.880', '14.880', '55,850']
22
15.060
23
15.180
24
14.880
25
14.880
26
14.880
27
55,850
28
Apr 04, 2019
['2019-04-04', '15.140', '15.180', '15.140', '15.140', '15.140', '256,400']
29
15.140
30
15.180
31
15.140
32
15.140
33
15.140
34
256,400
35
Apr 03, 2019
['2019-04-03', '15.120', '15.180', '15.080', '15.140', '15.140', '24,252']
36
15.120
37
15.180
38
15.080
39
15.140
40
15.140
41
24,252
42
Apr 02, 2019
['2019-04-02', '15.100', '15.240', '15.060', '15.120', '15.120', '15,473']
43
15.100
44
15.240
45
15.060
46
15.120
47
15.120
48
15,473
49
Apr 01, 2019
['2019-04-01', '15.280', '15.300', '15.080', '15.080', '15.080', '36,200']
50
15.280
51
15.300
52
15.080
53
15.080
54
15.080
55
36,200
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8622.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.290', '0.300', '0.290', '0.295', '0.295', '752,000']
1
0.290
2
0.300
3
0.290
4
0.295
5
0.295
6
752,000
7
Apr 10, 2019
['2019-04-10', '0.290', '0.300', '0.290', '0.300', '0.300', '264,000']
8
0.290
9
0.300
10
0.290
11
0.300
12
0.300
13
264,000
14
Apr 09, 2019
['2019-04-09', '0.290', '0.300', '0.290', '0.295', '0.295', '992,000']
15
0.290
16
0.300
17
0.290
18
0.295
19
0.295
20
992,000
21
Apr 08, 2019
['2019-04-08', '0.310', '0.310', '0.295', '0.300', '0.300', '1,824,000']
22
0.310
23
0.310
24
0.295
25
0.300
26
0.300
27
1,824,000
28
Apr 04, 2019
['2019-04-04', '0.310', '0.315', '0.305', '0.315', '0.315', '592,000']
29
0.310
30
0.315
31
0.305
32
0.315
33
0.315
34
592,000
35
Apr 03, 2019
['2019-04-03', '0.305', '0.315', '0.310', '0.310', '0.310', '216,000']
36
0.305
37
0.315
38
0.310
39
0.310
40
0.310
41
216,000
42
Apr 02, 2019
['2019-04-02', '0.305', '0.310', '0.300', '0.305', '0.305', '912,000']
43
0.305
44
0.310
45
0.300
46
0.305
47
0.305
48
912,000
49
Apr 01, 2019
['2019-04-01', '0.310', '0.310', '0.305', '0.310', '0.310', '472,000']
50
0.310
51
0.310
52
0.305
53
0.310
54
0.310
55
472,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2359.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '104.100', '104.100', '100.200', '101.400', '101.400', '302,765']
1
104.100
2
104.100
3
100.200
4
101.400
5
101.400
6
302,765
7
Apr 10, 2019
['2019-04-10', '100.500', '104.000', '98.500', '103.300', '103.300', '541,446']
8
100.500
9
104.000
10
98.500
11
103.300
12
103.300
13
541,446
14
Apr 09, 2019
['2019-04-09', '97.600', '101.100', '97.600', '100.000', '100.000', '683,120']
15
97.600
16
101.100
17
97.600
18
100.000
19
100.000
20
683,120
21
Apr 08, 2019
['2019-04-08', '98.000', '99.000', '97.900', '98.000', '98.000', '561,816']
22
98.000
23
99.000
24
97.900
25
98.000
26
98.000
27
561,816
28
Apr 04, 2019
['2019-04-04', '101.000', '101.000', '97.650', '97.850', '97.850', '366,200']
29
101.000
30
101.000
31
97.650
32
97.850
33
97.850
34
366,200
35
Apr 03, 2019
['2019-04-03', '98.000', '101.100', '97.850', '99.000', '99.000', '490,035']
36
98.000
37
101.100
38
97.850
39
99.000
40
99.000
41
490,035
42
Apr 02, 2019
['2019-04-02', '99.800', '105.000', '97.800', '97.900', '97.900', '914,300']
43
99.800
44
105.000
45
97.800
46
97.900
47
97.900
48
914,300
49
Apr 01, 2019
['2019-04-01', '96.400', '99.500', '95.550', '99.500', '99.500', '842,500']
50
96.400
51
99.500
52
95.550
53
99.500
54
99.500
55
842,500
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2798.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.820', '0.820', '0.810', '0.810', '0.810', '2,165,000']
1
0.820
2
0.820
3
0.810
4
0.810
5
0.810
6
2,165,000
7
Apr 10, 2019
['2019-04-10', '0.840', '0.840', '0.840', '0.840', '0.840', '80,000']
8
0.840
9
0.840
10
0.840
11
0.840
12
0.840
13
80,000
14
Apr 09, 2019
['2019-04-09', '0.850', '0.850', '0.840', '0.840', '0.840', '130,000']
15
0.850
16
0.850
17
0.840
18
0.840
19
0.840
20
130,000
21
Apr 08, 2019
['2019-04-08', '0.850', '0.850', '0.840', '0.840', '0.840', '125,000']
22
0.850
23
0.850
24
0.840
25
0.840
26
0.840
27
125,000
28
Apr 04, 2019
['2019-04-04', '0.820', '0.840', '0.820', '0.840', '0.840', '300,000']
29
0.820
30
0.840
31
0.820
32
0.840
33
0.840
34
300,000
35
Apr 03, 2019
['2019-04-03', '0.850', '0.850', '0.830', '0.830', '0.830', '240,000']
36
0.850
37
0.850
38
0.830
39
0.830
40
0.830
41
240,000
42
Apr 02, 2019
['2019-04-02', '0.870', '0.870', '0.860', '0.860', '0.860', '320,000']
43
0.870
44
0.870
45
0.860
46
0.860
47
0.860
48
320,000
49
Apr 01, 2019
['2019-04-01', '0.900', '0.930', '0.870', '0.870', '0.870', '265,000']
50
0.900
51
0.930
52
0.870
53
0.870
54
0.870
55
265,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8621.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.410', '0.425', '0.405', '0.410', '0.410', '912,000']
1
0.410
2
0.425
3
0.405
4
0.410
5
0.410
6
912,000
7
Apr 10, 2019
['2019-04-10', '0.405', '0.470', '0.395', '0.405', '0.405', '8,752,000']
8
0.405
9
0.470
10
0.395
11
0.405
12
0.405
13
8,752,000
14
Apr 09, 2019
['2019-04-09', '0.400', '0.400', '0.395', '0.395', '0.395', '944,000']
15
0.400
16
0.400
17
0.395
18
0.395
19
0.395
20
944,000
21
Apr 08, 2019
['2019-04-08', '0.400', '0.405', '0.395', '0.400', '0.400', '512,000']
22
0.400
23
0.405
24
0.395
25
0.400
26
0.400
27
512,000
28
Apr 04, 2019
['2019-04-04', '0.415', '0.415', '0.395', '0.400', '0.400', '2,576,000']
29
0.415
30
0.415
31
0.395
32
0.400
33
0.400
34
2,576,000
35
Apr 03, 2019
['2019-04-03', '0.400', '0.400', '0.400', '0.400', '0.400', '1,072,000']
36
0.400
37
0.400
38
0.400
39
0.400
40
0.400
41
1,072,000
42
Apr 02, 2019
['2019-04-02', '0.400', '0.400', '0.395', '0.400', '0.400', '1,864,000']
43
0.400
44
0.400
45
0.395
46
0.400
47
0.400
48
1,864,000
49
Apr 01, 2019
['2019-04-01', '0.400', '0.405', '0.395', '0.400', '0.400', '2,568,000']
50
0.400
51
0.405
52
0.395
53
0.400
54
0.400
55
2,568,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1837.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.630', '1.650', '1.600', '1.620', '1.620', '4,362,000']
1
1.630
2
1.650
3
1.600
4
1.620
5
1.620
6
4,362,000
7
Apr 10, 2019
['2019-04-10', '1.640', '1.670', '1.590', '1.650', '1.650', '4,888,000']
8
1.640
9
1.670
10
1.590
11
1.650
12
1.650
13
4,888,000
14
Apr 09, 2019
['2019-04-09', '1.710', '1.750', '1.650', '1.650', '1.650', '6,218,200']
15
1.710
16
1.750
17
1.650
18
1.650
19
1.650
20
6,218,200
21
Apr 08, 2019
['2019-04-08', '1.680', '1.750', '1.660', '1.710', '1.710', '6,756,000']
22
1.680
23
1.750
24
1.660
25
1.710
26
1.710
27
6,756,000
28
Apr 04, 2019
['2019-04-04', '1.680', '1.680', '1.650', '1.660', '1.660', '646,000']
29
1.680
30
1.680
31
1.650
32
1.660
33
1.660
34
646,000
35
Apr 03, 2019
['2019-04-03', '1.720', '1.730', '1.680', '1.680', '1.680', '3,108,000']
36
1.720
37
1.730
38
1.680
39
1.680
40
1.680
41
3,108,000
42
Apr 02, 2019
['2019-04-02', '1.660', '1.730', '1.640', '1.700', '1.700', '2,816,000']
43
1.660
44
1.730
45
1.640
46
1.700
47
1.700
48
2,816,000
49
Apr 01, 2019
['2019-04-01', '1.690', '1.700', '1.630', '1.650', '1.650', '2,176,000']
50
1.690
51
1.700
52
1.630
53
1.650
54
1.650
55
2,176,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1860.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.600', '4.600', '4.270', '4.300', '4.300', '2,276,000']
1
4.600
2
4.600
3
4.270
4
4.300
5
4.300
6
2,276,000
7
Apr 10, 2019
['2019-04-10', '4.080', '4.540', '4.080', '4.540', '4.540', '2,636,000']
8
4.080
9
4.540
10
4.080
11
4.540
12
4.540
13
2,636,000
14
Apr 09, 2019
['2019-04-09', '4.320', '4.320', '4.160', '4.180', '4.180', '1,226,000']
15
4.320
16
4.320
17
4.160
18
4.180
19
4.180
20
1,226,000
21
Apr 08, 2019
['2019-04-08', '4.410', '4.470', '4.170', '4.230', '4.230', '2,488,050']
22
4.410
23
4.470
24
4.170
25
4.230
26
4.230
27
2,488,050
28
Apr 04, 2019
['2019-04-04', '4.160', '4.440', '4.160', '4.400', '4.400', '2,741,000']
29
4.160
30
4.440
31
4.160
32
4.400
33
4.400
34
2,741,000
35
Apr 03, 2019
['2019-04-03', '4.340', '4.500', '4.190', '4.220', '4.220', '2,547,000']
36
4.340
37
4.500
38
4.190
39
4.220
40
4.220
41
2,547,000
42
Apr 02, 2019
['2019-04-02', '4.490', '4.540', '4.370', '4.380', '4.380', '2,145,000']
43
4.490
44
4.540
45
4.370
46
4.380
47
4.380
48
2,145,000
49
Apr 01, 2019
['2019-04-01', '4.520', '4.660', '4.310', '4.490', '4.490', '3,724,000']
50
4.520
51
4.660
52
4.310
53
4.490
54
4.490
55
3,724,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3992.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.120', '1.280', '1.100', '1.100', '1.100', '5,214,000']
1
1.120
2
1.280
3
1.100
4
1.100
5
1.100
6
5,214,000
7
Apr 10, 2019
['2019-04-10', '0.980', '1.160', '0.980', '1.130', '1.130', '3,594,000']
8
0.980
9
1.160
10
0.980
11
1.130
12
1.130
13
3,594,000
14
Apr 09, 2019
['2019-04-09', '0.930', '0.990', '0.930', '0.980', '0.980', '1,594,000']
15
0.930
16
0.990
17
0.930
18
0.980
19
0.980
20
1,594,000
21
Apr 08, 2019
['2019-04-08', '0.950', '0.970', '0.950', '0.950', '0.950', '472,000']
22
0.950
23
0.970
24
0.950
25
0.950
26
0.950
27
472,000
28
Apr 04, 2019
['2019-04-04', '0.960', '0.970', '0.940', '0.950', '0.950', '2,696,000']
29
0.960
30
0.970
31
0.940
32
0.950
33
0.950
34
2,696,000
35
Apr 03, 2019
['2019-04-03', '0.940', '1.000', '0.940', '0.970', '0.970', '914,000']
36
0.940
37
1.000
38
0.940
39
0.970
40
0.970
41
914,000
42
Apr 02, 2019
['2019-04-02', '0.940', '0.950', '0.940', '0.940', '0.940', '330,000']
43
0.940
44
0.950
45
0.940
46
0.940
47
0.940
48
330,000
49
Apr 01, 2019
['2019-04-01', '0.960', '0.960', '0.920', '0.920', '0.920', '244,000']
50
0.960
51
0.960
52
0.920
53
0.920
54
0.920
55
244,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3668.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '20.100', '20.100', '20.100', '20.100', '20.100', '-']
1
20.100
2
20.100
3
20.100
4
20.100
5
20.100
6
-
7
Apr 10, 2019
['2019-04-10', '19.620', '20.400', '19.300', '20.250', '20.250', '3,400']
8
19.620
9
20.400
10
19.300
11
20.250
12
20.250
13
3,400
14
Apr 09, 2019
['2019-04-09', '19.380', '19.380', '19.380', '19.460', '19.460', '300']
15
19.380
16
19.380
17
19.380
18
19.460
19
19.460
20
300
21
Apr 08, 2019
['2019-04-08', '19.820', '19.860', '19.400', '19.400', '19.400', '8,500']
22
19.820
23
19.860
24
19.400
25
19.400
26
19.400
27
8,500
28
Apr 04, 2019
['2019-04-04', '19.720', '19.720', '19.680', '19.680', '19.680', '500']
29
19.720
30
19.720
31
19.680
32
19.680
33
19.680
34
500
35
Apr 03, 2019
['2019-04-03', '20.000', '20.000', '19.420', '19.420', '19.420', '2,400']
36
20.000
37
20.000
38
19.420
39
19.420
40
19.420
41
2,400
42
Apr 02, 2019
['2019-04-02', '19.600', '20.050', '19.600', '20.000', '20.000', '3,000']
43
19.600
44
20.050
45
19.600
46
20.000
47
20.000
48
3,000
49
Apr 01, 2019
['2019-04-01', '19.400', '19.400', '19.400', '19.400', '19.400', '100']
50
19.400
51
19.400
52
19.400
53
19.400
54
19.400
55
100
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2168.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '9.600', '9.600', '9.310', '9.400', '9.400', '117,000']
1
9.600
2
9.600
3
9.310
4
9.400
5
9.400
6
117,000
7
Apr 10, 2019
['2019-04-10', '9.670', '9.670', '9.420', '9.570', '9.570', '115,250']
8
9.670
9
9.670
10
9.420
11
9.570
12
9.570
13
115,250
14
Apr 09, 2019
['2019-04-09', '9.680', '9.730', '9.550', '9.640', '9.640', '535,334']
15
9.680
16
9.730
17
9.550
18
9.640
19
9.640
20
535,334
21
Apr 08, 2019
['2019-04-08', '9.650', '9.770', '9.500', '9.680', '9.680', '413,250']
22
9.650
23
9.770
24
9.500
25
9.680
26
9.680
27
413,250
28
Apr 04, 2019
['2019-04-04', '9.490', '9.650', '9.300', '9.650', '9.650', '449,018']
29
9.490
30
9.650
31
9.300
32
9.650
33
9.650
34
449,018
35
Apr 03, 2019
['2019-04-03', '9.640', '9.730', '9.580', '9.680', '9.680', '742,660']
36
9.640
37
9.730
38
9.580
39
9.680
40
9.680
41
742,660
42
Apr 02, 2019
['2019-04-02', '9.400', '9.940', '9.370', '9.640', '9.640', '1,661,298']
43
9.400
44
9.940
45
9.370
46
9.640
47
9.640
48
1,661,298
49
Apr 01, 2019
['2019-04-01', '8.820', '9.330', '8.780', '9.330', '9.330', '736,000']
50
8.820
51
9.330
52
8.780
53
9.330
54
9.330
55
736,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1119.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '8.890', '9.700', '8.820', '8.920', '8.920', '16,802,800']
1
8.890
2
9.700
3
8.820
4
8.920
5
8.920
6
16,802,800
7
Apr 10, 2019
['2019-04-10', '7.680', '8.960', '7.540', '8.850', '8.850', '8,485,900']
8
7.680
9
8.960
10
7.540
11
8.850
12
8.850
13
8,485,900
14
Apr 09, 2019
['2019-04-09', '7.450', '7.820', '7.400', '7.640', '7.640', '2,779,600']
15
7.450
16
7.820
17
7.400
18
7.640
19
7.640
20
2,779,600
21
Apr 08, 2019
['2019-04-08', '7.930', '8.220', '7.220', '7.450', '7.450', '6,437,200']
22
7.930
23
8.220
24
7.220
25
7.450
26
7.450
27
6,437,200
28
Apr 04, 2019
['2019-04-04', '6.810', '8.090', '6.810', '7.880', '7.880', '11,762,000']
29
6.810
30
8.090
31
6.810
32
7.880
33
7.880
34
11,762,000
35
Apr 03, 2019
['2019-04-03', '6.500', '6.770', '6.450', '6.760', '6.760', '6,498,000']
36
6.500
37
6.770
38
6.450
39
6.760
40
6.760
41
6,498,000
42
Apr 02, 2019
['2019-04-02', '5.980', '6.390', '5.980', '6.350', '6.350', '3,636,600']
43
5.980
44
6.390
45
5.980
46
6.350
47
6.350
48
3,636,600
49
Apr 01, 2019
['2019-04-01', '5.910', '5.920', '5.830', '5.920', '5.920', '930,800']
50
5.910
51
5.920
52
5.830
53
5.920
54
5.920
55
930,800
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1790.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.750', '0.750', '0.720', '0.720', '0.720', '1,130,000']
1
0.750
2
0.750
3
0.720
4
0.720
5
0.720
6
1,130,000
7
Apr 10, 2019
['2019-04-10', '0.770', '0.780', '0.730', '0.750', '0.750', '575,000']
8
0.770
9
0.780
10
0.730
11
0.750
12
0.750
13
575,000
14
Apr 09, 2019
['2019-04-09', '0.750', '0.770', '0.740', '0.770', '0.770', '955,000']
15
0.750
16
0.770
17
0.740
18
0.770
19
0.770
20
955,000
21
Apr 08, 2019
['2019-04-08', '0.780', '0.780', '0.720', '0.740', '0.740', '1,720,000']
22
0.780
23
0.780
24
0.720
25
0.740
26
0.740
27
1,720,000
28
Apr 04, 2019
['2019-04-04', '0.730', '0.810', '0.720', '0.720', '0.720', '3,475,000']
29
0.730
30
0.810
31
0.720
32
0.720
33
0.720
34
3,475,000
35
Apr 03, 2019
['2019-04-03', '0.730', '0.740', '0.660', '0.710', '0.710', '2,805,000']
36
0.730
37
0.740
38
0.660
39
0.710
40
0.710
41
2,805,000
42
Apr 02, 2019
['2019-04-02', '0.740', '0.860', '0.720', '0.730', '0.730', '8,990,000']
43
0.740
44
0.860
45
0.720
46
0.730
47
0.730
48
8,990,000
49
Apr 01, 2019
['2019-04-01', '0.620', '0.780', '0.620', '0.730', '0.730', '5,720,000']
50
0.620
51
0.780
52
0.620
53
0.730
54
0.730
55
5,720,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1782.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.040', '1.050', '1.010', '1.020', '1.020', '295,000']
1
1.040
2
1.050
3
1.010
4
1.020
5
1.020
6
295,000
7
Apr 10, 2019
['2019-04-10', '1.010', '1.060', '1.000', '1.040', '1.040', '300,000']
8
1.010
9
1.060
10
1.000
11
1.040
12
1.040
13
300,000
14
Apr 09, 2019
['2019-04-09', '1.020', '1.070', '0.980', '1.040', '1.040', '610,000']
15
1.020
16
1.070
17
0.980
18
1.040
19
1.040
20
610,000
21
Apr 08, 2019
['2019-04-08', '1.080', '1.080', '1.020', '1.030', '1.030', '740,000']
22
1.080
23
1.080
24
1.020
25
1.030
26
1.030
27
740,000
28
Apr 04, 2019
['2019-04-04', '1.070', '1.080', '1.040', '1.080', '1.080', '285,000']
29
1.070
30
1.080
31
1.040
32
1.080
33
1.080
34
285,000
35
Apr 03, 2019
['2019-04-03', '1.130', '1.150', '1.090', '1.100', '1.100', '935,000']
36
1.130
37
1.150
38
1.090
39
1.100
40
1.100
41
935,000
42
Apr 02, 2019
['2019-04-02', '1.040', '1.100', '1.010', '1.090', '1.090', '305,000']
43
1.040
44
1.100
45
1.010
46
1.090
47
1.090
48
305,000
49
Apr 01, 2019
['2019-04-01', '1.050', '1.080', '0.990', '1.040', '1.040', '490,000']
50
1.050
51
1.080
52
0.990
53
1.040
54
1.040
55
490,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1761.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '6.450', '6.450', '6.130', '6.300', '6.300', '1,594,000']
1
6.450
2
6.450
3
6.130
4
6.300
5
6.300
6
1,594,000
7
Apr 10, 2019
['2019-04-10', '6.450', '6.450', '6.360', '6.400', '6.400', '2,022,000']
8
6.450
9
6.450
10
6.360
11
6.400
12
6.400
13
2,022,000
14
Apr 09, 2019
['2019-04-09', '6.300', '6.450', '6.300', '6.450', '6.450', '493,000']
15
6.300
16
6.450
17
6.300
18
6.450
19
6.450
20
493,000
21
Apr 08, 2019
['2019-04-08', '6.670', '6.750', '6.290', '6.380', '6.380', '2,529,000']
22
6.670
23
6.750
24
6.290
25
6.380
26
6.380
27
2,529,000
28
Apr 04, 2019
['2019-04-04', '6.700', '6.700', '6.600', '6.670', '6.670', '513,000']
29
6.700
30
6.700
31
6.600
32
6.670
33
6.670
34
513,000
35
Apr 03, 2019
['2019-04-03', '6.690', '6.740', '6.500', '6.650', '6.650', '1,037,000']
36
6.690
37
6.740
38
6.500
39
6.650
40
6.650
41
1,037,000
42
Apr 02, 2019
['2019-04-02', '6.620', '6.800', '6.600', '6.670', '6.670', '794,000']
43
6.620
44
6.800
45
6.600
46
6.670
47
6.670
48
794,000
49
Apr 01, 2019
['2019-04-01', '6.090', '6.870', '6.090', '6.550', '6.550', '1,465,500']
50
6.090
51
6.870
52
6.090
53
6.550
54
6.550
55
1,465,500
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0780.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '19.400', '19.720', '18.700', '19.020', '19.020', '1,802,000']
1
19.400
2
19.720
3
18.700
4
19.020
5
19.020
6
1,802,000
7
Apr 10, 2019
['2019-04-10', '18.860', '19.580', '18.720', '19.420', '19.420', '2,313,200']
8
18.860
9
19.580
10
18.720
11
19.420
12
19.420
13
2,313,200
14
Apr 09, 2019
['2019-04-09', '19.000', '19.000', '18.500', '19.000', '19.000', '1,513,400']
15
19.000
16
19.000
17
18.500
18
19.000
19
19.000
20
1,513,400
21
Apr 08, 2019
['2019-04-08', '18.700', '19.100', '18.500', '19.000', '19.000', '5,627,920']
22
18.700
23
19.100
24
18.500
25
19.000
26
19.000
27
5,627,920
28
Apr 04, 2019
['2019-04-04', '18.600', '18.880', '18.200', '18.700', '18.700', '3,277,600']
29
18.600
30
18.880
31
18.200
32
18.700
33
18.700
34
3,277,600
35
Apr 03, 2019
['2019-04-03', '17.600', '18.600', '17.300', '18.560', '18.560', '6,160,400']
36
17.600
37
18.600
38
17.300
39
18.560
40
18.560
41
6,160,400
42
Apr 02, 2019
['2019-04-02', '17.600', '17.600', '17.200', '17.380', '17.380', '1,034,200']
43
17.600
44
17.600
45
17.200
46
17.380
47
17.380
48
1,034,200
49
Apr 01, 2019
['2019-04-01', '17.420', '17.640', '16.880', '17.600', '17.600', '2,019,200']
50
17.420
51
17.640
52
16.880
53
17.600
54
17.600
55
2,019,200
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6890.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.170', '1.170', '1.120', '1.150', '1.150', '342,000']
1
1.170
2
1.170
3
1.120
4
1.150
5
1.150
6
342,000
7
Apr 10, 2019
['2019-04-10', '1.150', '1.200', '1.120', '1.190', '1.190', '622,000']
8
1.150
9
1.200
10
1.120
11
1.190
12
1.190
13
622,000
14
Apr 09, 2019
['2019-04-09', '1.180', '1.180', '1.140', '1.170', '1.170', '376,000']
15
1.180
16
1.180
17
1.140
18
1.170
19
1.170
20
376,000
21
Apr 08, 2019
['2019-04-08', '1.240', '1.240', '1.160', '1.200', '1.200', '344,000']
22
1.240
23
1.240
24
1.160
25
1.200
26
1.200
27
344,000
28
Apr 04, 2019
['2019-04-04', '1.200', '1.240', '1.150', '1.220', '1.220', '242,000']
29
1.200
30
1.240
31
1.150
32
1.220
33
1.220
34
242,000
35
Apr 03, 2019
['2019-04-03', '1.210', '1.210', '1.150', '1.210', '1.210', '182,000']
36
1.210
37
1.210
38
1.150
39
1.210
40
1.210
41
182,000
42
Apr 02, 2019
['2019-04-02', '1.120', '1.190', '1.120', '1.190', '1.190', '530,000']
43
1.120
44
1.190
45
1.120
46
1.190
47
1.190
48
530,000
49
Apr 01, 2019
['2019-04-01', '1.260', '1.260', '1.100', '1.170', '1.170', '1,768,000']
50
1.260
51
1.260
52
1.100
53
1.170
54
1.170
55
1,768,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2258.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.510', '1.510', '1.430', '1.440', '1.440', '904,000']
1
1.510
2
1.510
3
1.430
4
1.440
5
1.440
6
904,000
7
Apr 10, 2019
['2019-04-10', '1.490', '1.530', '1.440', '1.510', '1.510', '1,032,000']
8
1.490
9
1.530
10
1.440
11
1.510
12
1.510
13
1,032,000
14
Apr 09, 2019
['2019-04-09', '1.510', '1.510', '1.440', '1.490', '1.490', '932,000']
15
1.510
16
1.510
17
1.440
18
1.490
19
1.490
20
932,000
21
Apr 08, 2019
['2019-04-08', '1.580', '1.640', '1.480', '1.510', '1.510', '2,186,000']
22
1.580
23
1.640
24
1.480
25
1.510
26
1.510
27
2,186,000
28
Apr 04, 2019
['2019-04-04', '1.410', '1.620', '1.330', '1.540', '1.540', '5,744,000']
29
1.410
30
1.620
31
1.330
32
1.540
33
1.540
34
5,744,000
35
Apr 03, 2019
['2019-04-03', '1.620', '1.620', '1.400', '1.450', '1.450', '6,472,000']
36
1.620
37
1.620
38
1.400
39
1.450
40
1.450
41
6,472,000
42
Apr 02, 2019
['2019-04-02', '1.700', '1.710', '1.600', '1.620', '1.620', '2,200,000']
43
1.700
44
1.710
45
1.600
46
1.620
47
1.620
48
2,200,000
49
Apr 01, 2019
['2019-04-01', '1.800', '1.800', '1.530', '1.660', '1.660', '3,940,000']
50
1.800
51
1.800
52
1.530
53
1.660
54
1.660
55
3,940,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1835.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '5.000', '5.000', '5.000', '5.000', '5.000', '800']
1
5.000
2
5.000
3
5.000
4
5.000
5
5.000
6
800
7
Apr 10, 2019
['2019-04-10', '5.000', '5.000', '5.000', '5.000', '5.000', '-']
8
5.000
9
5.000
10
5.000
11
5.000
12
5.000
13
-
14
Apr 09, 2019
['2019-04-09', '5.000', '5.000', '5.000', '5.000', '5.000', '9,200']
15
5.000
16
5.000
17
5.000
18
5.000
19
5.000
20
9,200
21
Apr 08, 2019
['2019-04-08', '5.000', '5.000', '5.000', '5.000', '5.000', '11,600']
22
5.000
23
5.000
24
5.000
25
5.000
26
5.000
27
11,600
28
Apr 04, 2019
['2019-04-04', '5.010', '5.010', '5.010', '5.010', '5.010', '-']
29
5.010
30
5.010
31
5.010
32
5.010
33
5.010
34
-
35
Apr 03, 2019
['2019-04-03', '5.000', '5.010', '5.000', '5.010', '5.010', '3,600']
36
5.000
37
5.010
38
5.000
39
5.010
40
5.010
41
3,600
42
Apr 02, 2019
['2019-04-02', '5.000', '5.000', '5.000', '5.000', '5.000', '200,000']
43
5.000
44
5.000
45
5.000
46
5.000
47
5.000
48
200,000
49
Apr 01, 2019
['2019-04-01', '5.080', '5.080', '5.000', '5.000', '5.000', '1,200']
50
5.080
51
5.080
52
5.000
53
5.000
54
5.000
55
1,200
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3616.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.060', '1.090', '1.030', '1.050', '1.050', '200,000']
1
1.060
2
1.090
3
1.030
4
1.050
5
1.050
6
200,000
7
Apr 10, 2019
['2019-04-10', '1.070', '1.070', '1.030', '1.060', '1.060', '388,000']
8
1.070
9
1.070
10
1.030
11
1.060
12
1.060
13
388,000
14
Apr 09, 2019
['2019-04-09', '1.090', '1.090', '1.050', '1.070', '1.070', '526,000']
15
1.090
16
1.090
17
1.050
18
1.070
19
1.070
20
526,000
21
Apr 08, 2019
['2019-04-08', '1.070', '1.120', '1.050', '1.070', '1.070', '706,000']
22
1.070
23
1.120
24
1.050
25
1.070
26
1.070
27
706,000
28
Apr 04, 2019
['2019-04-04', '1.050', '1.080', '1.030', '1.070', '1.070', '880,000']
29
1.050
30
1.080
31
1.030
32
1.070
33
1.070
34
880,000
35
Apr 03, 2019
['2019-04-03', '1.080', '1.080', '1.020', '1.050', '1.050', '468,000']
36
1.080
37
1.080
38
1.020
39
1.050
40
1.050
41
468,000
42
Apr 02, 2019
['2019-04-02', '1.060', '1.080', '0.990', '1.050', '1.050', '132,000']
43
1.060
44
1.080
45
0.990
46
1.050
47
1.050
48
132,000
49
Apr 01, 2019
['2019-04-01', '1.070', '1.100', '1.010', '1.050', '1.050', '216,000']
50
1.070
51
1.100
52
1.010
53
1.050
54
1.050
55
216,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8259.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.110', '1.140', '1.060', '1.080', '1.080', '1,252,000']
1
1.110
2
1.140
3
1.060
4
1.080
5
1.080
6
1,252,000
7
Apr 10, 2019
['2019-04-10', '1.120', '1.120', '1.050', '1.100', '1.100', '1,152,000']
8
1.120
9
1.120
10
1.050
11
1.100
12
1.100
13
1,152,000
14
Apr 09, 2019
['2019-04-09', '1.140', '1.140', '1.030', '1.080', '1.080', '1,572,000']
15
1.140
16
1.140
17
1.030
18
1.080
19
1.080
20
1,572,000
21
Apr 08, 2019
['2019-04-08', '1.050', '1.120', '1.000', '1.060', '1.060', '1,196,000']
22
1.050
23
1.120
24
1.000
25
1.060
26
1.060
27
1,196,000
28
Apr 04, 2019
['2019-04-04', '1.170', '1.200', '1.000', '1.060', '1.060', '1,852,000']
29
1.170
30
1.200
31
1.000
32
1.060
33
1.060
34
1,852,000
35
Apr 03, 2019
['2019-04-03', '1.180', '1.190', '1.120', '1.150', '1.150', '1,076,000']
36
1.180
37
1.190
38
1.120
39
1.150
40
1.150
41
1,076,000
42
Apr 02, 2019
['2019-04-02', '1.240', '1.260', '1.180', '1.200', '1.200', '1,116,000']
43
1.240
44
1.260
45
1.180
46
1.200
47
1.200
48
1,116,000
49
Apr 01, 2019
['2019-04-01', '1.320', '1.320', '1.200', '1.240', '1.240', '1,484,000']
50
1.320
51
1.320
52
1.200
53
1.240
54
1.240
55
1,484,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1755.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '7.300', '7.470', '7.300', '7.410', '7.410', '1,386,000']
1
7.300
2
7.470
3
7.300
4
7.410
5
7.410
6
1,386,000
7
Apr 10, 2019
['2019-04-10', '7.380', '7.530', '7.200', '7.310', '7.310', '1,565,000']
8
7.380
9
7.530
10
7.200
11
7.310
12
7.310
13
1,565,000
14
Apr 09, 2019
['2019-04-09', '7.430', '7.600', '7.200', '7.480', '7.480', '4,060,000']
15
7.430
16
7.600
17
7.200
18
7.480
19
7.480
20
4,060,000
21
Apr 08, 2019
['2019-04-08', '7.560', '7.610', '7.190', '7.380', '7.380', '3,488,000']
22
7.560
23
7.610
24
7.190
25
7.380
26
7.380
27
3,488,000
28
Apr 04, 2019
['2019-04-04', '7.760', '8.090', '7.500', '7.620', '7.620', '3,520,000']
29
7.760
30
8.090
31
7.500
32
7.620
33
7.620
34
3,520,000
35
Apr 03, 2019
['2019-04-03', '7.850', '7.850', '7.490', '7.720', '7.720', '8,321,000']
36
7.850
37
7.850
38
7.490
39
7.720
40
7.720
41
8,321,000
42
Apr 02, 2019
['2019-04-02', '8.160', '8.330', '7.650', '7.960', '7.960', '3,053,000']
43
8.160
44
8.330
45
7.650
46
7.960
47
7.960
48
3,053,000
49
Apr 01, 2019
['2019-04-01', '8.200', '8.490', '8.100', '8.240', '8.240', '5,145,000']
50
8.200
51
8.490
52
8.100
53
8.240
54
8.240
55
5,145,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
No record
0
1801.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '30.000', '30.000', '28.700', '28.700', '28.700', '362,700']
1
30.000
2
30.000
3
28.700
4
28.700
5
28.700
6
362,700
7
Apr 10, 2019
['2019-04-10', '29.550', '30.100', '28.950', '29.750', '29.750', '456,500']
8
29.550
9
30.100
10
28.950
11
29.750
12
29.750
13
456,500
14
Apr 09, 2019
['2019-04-09', '29.900', '30.150', '29.450', '29.950', '29.950', '1,054,863']
15
29.900
16
30.150
17
29.450
18
29.950
19
29.950
20
1,054,863
21
Apr 08, 2019
['2019-04-08', '29.050', '30.400', '28.800', '29.900', '29.900', '385,584']
22
29.050
23
30.400
24
28.800
25
29.900
26
29.900
27
385,584
28
Apr 04, 2019
['2019-04-04', '28.800', '29.800', '28.750', '29.200', '29.200', '1,651,500']
29
28.800
30
29.800
31
28.750
32
29.200
33
29.200
34
1,651,500
35
Apr 03, 2019
['2019-04-03', '29.900', '30.000', '28.650', '28.800', '28.800', '999,000']
36
29.900
37
30.000
38
28.650
39
28.800
40
28.800
41
999,000
42
Apr 02, 2019
['2019-04-02', '30.500', '30.900', '29.900', '30.050', '30.050', '725,025']
43
30.500
44
30.900
45
29.900
46
30.050
47
30.050
48
725,025
49
Apr 01, 2019
['2019-04-01', '29.100', '30.250', '29.050', '30.100', '30.100', '1,187,056']
50
29.100
51
30.250
52
29.050
53
30.100
54
30.100
55
1,187,056
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1034.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.280', '2.520', '2.220', '2.510', '2.510', '5,528,000']
1
2.280
2
2.520
3
2.220
4
2.510
5
2.510
6
5,528,000
7
Apr 10, 2019
['2019-04-10', '2.060', '2.280', '2.010', '2.280', '2.280', '5,304,000']
8
2.060
9
2.280
10
2.010
11
2.280
12
2.280
13
5,304,000
14
Apr 09, 2019
['2019-04-09', '2.080', '2.080', '1.990', '2.040', '2.040', '5,424,000']
15
2.080
16
2.080
17
1.990
18
2.040
19
2.040
20
5,424,000
21
Apr 08, 2019
['2019-04-08', '2.100', '2.100', '1.960', '2.040', '2.040', '5,216,000']
22
2.100
23
2.100
24
1.960
25
2.040
26
2.040
27
5,216,000
28
Apr 04, 2019
['2019-04-04', '1.870', '2.050', '1.800', '2.040', '2.040', '6,456,000']
29
1.870
30
2.050
31
1.800
32
2.040
33
2.040
34
6,456,000
35
Apr 03, 2019
['2019-04-03', '1.700', '1.840', '1.590', '1.840', '1.840', '8,544,000']
36
1.700
37
1.840
38
1.590
39
1.840
40
1.840
41
8,544,000
42
Apr 02, 2019
['2019-04-02', '1.490', '1.670', '1.420', '1.670', '1.670', '7,579,005']
43
1.490
44
1.670
45
1.420
46
1.670
47
1.670
48
7,579,005
49
Apr 01, 2019
['2019-04-01', '1.350', '1.510', '1.270', '1.390', '1.390', '11,083,005']
50
1.350
51
1.510
52
1.270
53
1.390
54
1.390
55
11,083,005
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8611.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.270', '0.290', '0.270', '0.275', '0.275', '700,000']
1
0.270
2
0.290
3
0.270
4
0.275
5
0.275
6
700,000
7
Apr 10, 2019
['2019-04-10', '0.270', '0.285', '0.260', '0.280', '0.280', '1,650,000']
8
0.270
9
0.285
10
0.260
11
0.280
12
0.280
13
1,650,000
14
Apr 09, 2019
['2019-04-09', '0.235', '0.275', '0.235', '0.260', '0.260', '1,605,000']
15
0.235
16
0.275
17
0.235
18
0.260
19
0.260
20
1,605,000
21
Apr 08, 2019
['2019-04-08', '0.244', '0.244', '0.231', '0.235', '0.235', '785,000']
22
0.244
23
0.244
24
0.231
25
0.235
26
0.235
27
785,000
28
Apr 04, 2019
['2019-04-04', '0.246', '0.249', '0.246', '0.247', '0.247', '70,000']
29
0.246
30
0.249
31
0.246
32
0.247
33
0.247
34
70,000
35
Apr 03, 2019
['2019-04-03', '0.244', '0.250', '0.244', '0.246', '0.246', '175,000']
36
0.244
37
0.250
38
0.244
39
0.246
40
0.246
41
175,000
42
Apr 02, 2019
['2019-04-02', '0.250', '0.250', '0.246', '0.250', '0.250', '375,000']
43
0.250
44
0.250
45
0.246
46
0.250
47
0.250
48
375,000
49
Apr 01, 2019
['2019-04-01', '0.255', '0.255', '0.245', '0.247', '0.247', '605,000']
50
0.255
51
0.255
52
0.245
53
0.247
54
0.247
55
605,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1825.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.205', '0.205', '0.200', '0.202', '0.202', '1,450,000']
1
0.205
2
0.205
3
0.200
4
0.202
5
0.202
6
1,450,000
7
Apr 10, 2019
['2019-04-10', '0.200', '0.210', '0.200', '0.208', '0.208', '880,000']
8
0.200
9
0.210
10
0.200
11
0.208
12
0.208
13
880,000
14
Apr 09, 2019
['2019-04-09', '0.204', '0.204', '0.204', '0.204', '0.204', '10,000']
15
0.204
16
0.204
17
0.204
18
0.204
19
0.204
20
10,000
21
Apr 08, 2019
['2019-04-08', '0.204', '0.206', '0.198', '0.204', '0.204', '1,660,000']
22
0.204
23
0.206
24
0.198
25
0.204
26
0.204
27
1,660,000
28
Apr 04, 2019
['2019-04-04', '0.207', '0.208', '0.204', '0.208', '0.208', '1,550,000']
29
0.207
30
0.208
31
0.204
32
0.208
33
0.208
34
1,550,000
35
Apr 03, 2019
['2019-04-03', '0.209', '0.220', '0.206', '0.212', '0.212', '3,040,000']
36
0.209
37
0.220
38
0.206
39
0.212
40
0.212
41
3,040,000
42
Apr 02, 2019
['2019-04-02', '0.208', '0.208', '0.204', '0.207', '0.207', '1,840,000']
43
0.208
44
0.208
45
0.204
46
0.207
47
0.207
48
1,840,000
49
Apr 01, 2019
['2019-04-01', '0.205', '0.206', '0.204', '0.205', '0.205', '940,000']
50
0.205
51
0.206
52
0.204
53
0.205
54
0.205
55
940,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1653.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.127', '0.127', '0.123', '0.123', '0.123', '10,380,000']
1
0.127
2
0.127
3
0.123
4
0.123
5
0.123
6
10,380,000
7
Apr 10, 2019
['2019-04-10', '0.128', '0.128', '0.125', '0.126', '0.126', '9,620,000']
8
0.128
9
0.128
10
0.125
11
0.126
12
0.126
13
9,620,000
14
Apr 09, 2019
['2019-04-09', '0.128', '0.128', '0.126', '0.126', '0.126', '8,900,000']
15
0.128
16
0.128
17
0.126
18
0.126
19
0.126
20
8,900,000
21
Apr 08, 2019
['2019-04-08', '0.129', '0.130', '0.126', '0.129', '0.129', '11,000,000']
22
0.129
23
0.130
24
0.126
25
0.129
26
0.129
27
11,000,000
28
Apr 04, 2019
['2019-04-04', '0.128', '0.129', '0.125', '0.128', '0.128', '12,940,000']
29
0.128
30
0.129
31
0.125
32
0.128
33
0.128
34
12,940,000
35
Apr 03, 2019
['2019-04-03', '0.129', '0.132', '0.123', '0.126', '0.126', '13,560,000']
36
0.129
37
0.132
38
0.123
39
0.126
40
0.126
41
13,560,000
42
Apr 02, 2019
['2019-04-02', '0.123', '0.129', '0.123', '0.125', '0.125', '12,680,000']
43
0.123
44
0.129
45
0.123
46
0.125
47
0.125
48
12,680,000
49
Apr 01, 2019
['2019-04-01', '0.123', '0.128', '0.123', '0.124', '0.124', '12,080,000']
50
0.123
51
0.128
52
0.123
53
0.124
54
0.124
55
12,080,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8613.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.197', '0.204', '0.192', '0.198', '0.198', '2,131,789']
1
0.197
2
0.204
3
0.192
4
0.198
5
0.198
6
2,131,789
7
Apr 10, 2019
['2019-04-10', '0.191', '0.193', '0.189', '0.193', '0.193', '720,000']
8
0.191
9
0.193
10
0.189
11
0.193
12
0.193
13
720,000
14
Apr 09, 2019
['2019-04-09', '0.195', '0.198', '0.193', '0.193', '0.193', '1,120,000']
15
0.195
16
0.198
17
0.193
18
0.193
19
0.193
20
1,120,000
21
Apr 08, 2019
['2019-04-08', '0.192', '0.197', '0.185', '0.195', '0.195', '1,390,000']
22
0.192
23
0.197
24
0.185
25
0.195
26
0.195
27
1,390,000
28
Apr 04, 2019
['2019-04-04', '0.186', '0.193', '0.186', '0.193', '0.193', '1,540,000']
29
0.186
30
0.193
31
0.186
32
0.193
33
0.193
34
1,540,000
35
Apr 03, 2019
['2019-04-03', '0.193', '0.193', '0.186', '0.193', '0.193', '970,000']
36
0.193
37
0.193
38
0.186
39
0.193
40
0.193
41
970,000
42
Apr 02, 2019
['2019-04-02', '0.196', '0.196', '0.192', '0.192', '0.192', '650,000']
43
0.196
44
0.196
45
0.192
46
0.192
47
0.192
48
650,000
49
Apr 01, 2019
['2019-04-01', '0.200', '0.203', '0.192', '0.192', '0.192', '1,610,000']
50
0.200
51
0.203
52
0.192
53
0.192
54
0.192
55
1,610,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1741.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.760', '1.900', '1.760', '1.850', '1.850', '4,144,000']
1
1.760
2
1.900
3
1.760
4
1.850
5
1.850
6
4,144,000
7
Apr 10, 2019
['2019-04-10', '1.780', '1.940', '1.770', '1.930', '1.930', '152,000']
8
1.780
9
1.940
10
1.770
11
1.930
12
1.930
13
152,000
14
Apr 09, 2019
['2019-04-09', '2.100', '2.100', '1.880', '1.970', '1.970', '240,000']
15
2.100
16
2.100
17
1.880
18
1.970
19
1.970
20
240,000
21
Apr 08, 2019
['2019-04-08', '1.920', '2.080', '1.910', '2.080', '2.080', '836,000']
22
1.920
23
2.080
24
1.910
25
2.080
26
2.080
27
836,000
28
Apr 04, 2019
['2019-04-04', '1.800', '1.880', '1.750', '1.880', '1.880', '428,000']
29
1.800
30
1.880
31
1.750
32
1.880
33
1.880
34
428,000
35
Apr 03, 2019
['2019-04-03', '1.790', '1.840', '1.420', '1.700', '1.700', '916,000']
36
1.790
37
1.840
38
1.420
39
1.700
40
1.700
41
916,000
42
Apr 02, 2019
['2019-04-02', '1.540', '1.780', '1.540', '1.700', '1.700', '196,000']
43
1.540
44
1.780
45
1.540
46
1.700
47
1.700
48
196,000
49
Apr 01, 2019
['2019-04-01', '1.500', '1.550', '1.500', '1.550', '1.550', '148,000']
50
1.500
51
1.550
52
1.500
53
1.550
54
1.550
55
148,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8603.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.570', '0.570', '0.570', '0.570', '0.570', '-']
1
0.570
2
0.570
3
0.570
4
0.570
5
0.570
6
-
7
Apr 10, 2019
['2019-04-10', '0.570', '0.570', '0.570', '0.570', '0.570', '-']
8
0.570
9
0.570
10
0.570
11
0.570
12
0.570
13
-
14
Apr 09, 2019
['2019-04-09', '0.570', '0.570', '0.570', '0.570', '0.570', '-']
15
0.570
16
0.570
17
0.570
18
0.570
19
0.570
20
-
21
Apr 08, 2019
['2019-04-08', '0.530', '0.570', '0.530', '0.570', '0.570', '450,000']
22
0.530
23
0.570
24
0.530
25
0.570
26
0.570
27
450,000
28
Apr 04, 2019
['2019-04-04', '0.550', '0.550', '0.550', '0.550', '0.550', '-']
29
0.550
30
0.550
31
0.550
32
0.550
33
0.550
34
-
35
Apr 03, 2019
['2019-04-03', '0.540', '0.540', '0.540', '0.540', '0.540', '-']
36
0.540
37
0.540
38
0.540
39
0.540
40
0.540
41
-
42
Apr 02, 2019
['2019-04-02', '0.560', '0.560', '0.520', '0.550', '0.550', '140,000']
43
0.560
44
0.560
45
0.520
46
0.550
47
0.550
48
140,000
49
Apr 01, 2019
['2019-04-01', '0.550', '0.550', '0.550', '0.550', '0.550', '-']
50
0.550
51
0.550
52
0.550
53
0.550
54
0.550
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8516.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.060', '2.100', '2.020', '2.100', '2.100', '40,000']
1
2.060
2
2.100
3
2.020
4
2.100
5
2.100
6
40,000
7
Apr 10, 2019
['2019-04-10', '2.080', '2.190', '1.910', '2.050', '2.050', '90,000']
8
2.080
9
2.190
10
1.910
11
2.050
12
2.050
13
90,000
14
Apr 09, 2019
['2019-04-09', '2.160', '2.280', '2.160', '2.200', '2.200', '29,000']
15
2.160
16
2.280
17
2.160
18
2.200
19
2.200
20
29,000
21
Apr 08, 2019
['2019-04-08', '2.290', '2.290', '2.290', '2.290', '2.290', '-']
22
2.290
23
2.290
24
2.290
25
2.290
26
2.290
27
-
28
Apr 04, 2019
['2019-04-04', '2.330', '2.330', '2.250', '2.310', '2.310', '2,285,000']
29
2.330
30
2.330
31
2.250
32
2.310
33
2.310
34
2,285,000
35
Apr 03, 2019
['2019-04-03', '2.120', '2.260', '2.120', '2.260', '2.260', '155,000']
36
2.120
37
2.260
38
2.120
39
2.260
40
2.260
41
155,000
42
Apr 02, 2019
['2019-04-02', '1.860', '2.160', '1.860', '2.160', '2.160', '2,165,000']
43
1.860
44
2.160
45
1.860
46
2.160
47
2.160
48
2,165,000
49
Apr 01, 2019
['2019-04-01', '1.910', '2.250', '1.910', '2.120', '2.120', '7,070,000']
50
1.910
51
2.250
52
1.910
53
2.120
54
2.120
55
7,070,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8042.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.520', '0.850', '0.520', '0.640', '0.640', '43,811,500']
1
0.520
2
0.850
3
0.520
4
0.640
5
0.640
6
43,811,500
7
Apr 10, 2019
['2019-04-10', '0.580', '0.610', '0.450', '0.540', '0.540', '38,220,000']
8
0.580
9
0.610
10
0.450
11
0.540
12
0.540
13
38,220,000
14
Apr 09, 2019
['2019-04-09', '0.580', '0.640', '0.570', '0.580', '0.580', '19,450,000']
15
0.580
16
0.640
17
0.570
18
0.580
19
0.580
20
19,450,000
21
Apr 08, 2019
['2019-04-08', '0.580', '0.690', '0.460', '0.580', '0.580', '41,970,000']
22
0.580
23
0.690
24
0.460
25
0.580
26
0.580
27
41,970,000
28
Apr 04, 2019
['2019-04-04', '0.335', '0.610', '0.335', '0.600', '0.600', '66,870,000']
29
0.335
30
0.610
31
0.335
32
0.600
33
0.600
34
66,870,000
35
Apr 03, 2019
['2019-04-03', '0.320', '0.350', '0.315', '0.335', '0.335', '7,430,000']
36
0.320
37
0.350
38
0.315
39
0.335
40
0.335
41
7,430,000
42
Apr 02, 2019
['2019-04-02', '0.310', '0.320', '0.310', '0.320', '0.320', '5,100,000']
43
0.310
44
0.320
45
0.310
46
0.320
47
0.320
48
5,100,000
49
Apr 01, 2019
['2019-04-01', '0.315', '0.320', '0.305', '0.320', '0.320', '1,270,000']
50
0.315
51
0.320
52
0.305
53
0.320
54
0.320
55
1,270,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1894.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.090', '3.130', '2.950', '2.980', '2.980', '2,180,000']
1
3.090
2
3.130
3
2.950
4
2.980
5
2.980
6
2,180,000
7
Apr 10, 2019
['2019-04-10', '3.120', '3.180', '3.080', '3.090', '3.090', '1,830,000']
8
3.120
9
3.180
10
3.080
11
3.090
12
3.090
13
1,830,000
14
Apr 09, 2019
['2019-04-09', '3.080', '3.120', '3.070', '3.080', '3.080', '1,825,000']
15
3.080
16
3.120
17
3.070
18
3.080
19
3.080
20
1,825,000
21
Apr 08, 2019
['2019-04-08', '3.280', '3.310', '3.100', '3.100', '3.100', '1,770,000']
22
3.280
23
3.310
24
3.100
25
3.100
26
3.100
27
1,770,000
28
Apr 04, 2019
['2019-04-04', '3.260', '3.280', '3.220', '3.270', '3.270', '2,045,000']
29
3.260
30
3.280
31
3.220
32
3.270
33
3.270
34
2,045,000
35
Apr 03, 2019
['2019-04-03', '3.080', '3.280', '3.080', '3.260', '3.260', '1,695,000']
36
3.080
37
3.280
38
3.080
39
3.260
40
3.260
41
1,695,000
42
Apr 02, 2019
['2019-04-02', '2.980', '3.200', '2.970', '3.190', '3.190', '2,135,000']
43
2.980
44
3.200
45
2.970
46
3.190
47
3.190
48
2,135,000
49
Apr 01, 2019
['2019-04-01', '3.000', '3.100', '2.840', '2.940', '2.940', '2,355,000']
50
3.000
51
3.100
52
2.840
53
2.940
54
2.940
55
2,355,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3990.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '23.100', '23.800', '22.100', '22.200', '22.200', '4,388,200']
1
23.100
2
23.800
3
22.100
4
22.200
5
22.200
6
4,388,200
7
Apr 10, 2019
['2019-04-10', '22.400', '23.800', '22.400', '23.050', '23.050', '8,485,600']
8
22.400
9
23.800
10
22.400
11
23.050
12
23.050
13
8,485,600
14
Apr 09, 2019
['2019-04-09', '21.500', '21.800', '21.400', '21.600', '21.600', '2,353,400']
15
21.500
16
21.800
17
21.400
18
21.600
19
21.600
20
2,353,400
21
Apr 08, 2019
['2019-04-08', '22.600', '23.400', '21.300', '21.450', '21.450', '3,183,200']
22
22.600
23
23.400
24
21.300
25
21.450
26
21.450
27
3,183,200
28
Apr 04, 2019
['2019-04-04', '21.400', '22.450', '21.300', '22.200', '22.200', '3,024,800']
29
21.400
30
22.450
31
21.300
32
22.200
33
22.200
34
3,024,800
35
Apr 03, 2019
['2019-04-03', '20.250', '21.200', '20.050', '20.900', '20.900', '3,710,400']
36
20.250
37
21.200
38
20.050
39
20.900
40
20.900
41
3,710,400
42
Apr 02, 2019
['2019-04-02', '20.850', '20.850', '20.000', '20.100', '20.100', '1,195,250']
43
20.850
44
20.850
45
20.000
46
20.100
47
20.100
48
1,195,250
49
Apr 01, 2019
['2019-04-01', '21.000', '21.400', '20.250', '20.450', '20.450', '6,504,000']
50
21.000
51
21.400
52
20.250
53
20.450
54
20.450
55
6,504,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6111.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '5.700', '5.880', '5.700', '5.830', '5.830', '414,000']
1
5.700
2
5.880
3
5.700
4
5.830
5
5.830
6
414,000
7
Apr 10, 2019
['2019-04-10', '5.400', '5.800', '5.350', '5.710', '5.710', '761,000']
8
5.400
9
5.800
10
5.350
11
5.710
12
5.710
13
761,000
14
Apr 09, 2019
['2019-04-09', '5.060', '5.390', '5.060', '5.390', '5.390', '496,000']
15
5.060
16
5.390
17
5.060
18
5.390
19
5.390
20
496,000
21
Apr 08, 2019
['2019-04-08', '5.230', '5.240', '5.110', '5.130', '5.130', '520,000']
22
5.230
23
5.240
24
5.110
25
5.130
26
5.130
27
520,000
28
Apr 04, 2019
['2019-04-04', '5.270', '5.370', '5.200', '5.200', '5.200', '785,000']
29
5.270
30
5.370
31
5.200
32
5.200
33
5.200
34
785,000
35
Apr 03, 2019
['2019-04-03', '5.250', '5.330', '5.170', '5.300', '5.300', '650,000']
36
5.250
37
5.330
38
5.170
39
5.300
40
5.300
41
650,000
42
Apr 02, 2019
['2019-04-02', '5.200', '5.500', '5.200', '5.280', '5.280', '1,463,000']
43
5.200
44
5.500
45
5.200
46
5.280
47
5.280
48
1,463,000
49
Apr 01, 2019
['2019-04-01', '5.220', '5.650', '5.200', '5.630', '5.630', '697,000']
50
5.220
51
5.650
52
5.200
53
5.630
54
5.630
55
697,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1772.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '14.480', '15.000', '14.300', '14.300', '14.300', '911,000']
1
14.480
2
15.000
3
14.300
4
14.300
5
14.300
6
911,000
7
Apr 10, 2019
['2019-04-10', '14.600', '14.600', '14.200', '14.420', '14.420', '464,000']
8
14.600
9
14.600
10
14.200
11
14.420
12
14.420
13
464,000
14
Apr 09, 2019
['2019-04-09', '14.840', '14.940', '14.480', '14.500', '14.500', '863,200']
15
14.840
16
14.940
17
14.480
18
14.500
19
14.500
20
863,200
21
Apr 08, 2019
['2019-04-08', '14.780', '15.220', '14.380', '14.760', '14.760', '2,564,400']
22
14.780
23
15.220
24
14.380
25
14.760
26
14.760
27
2,564,400
28
Apr 04, 2019
['2019-04-04', '14.380', '14.560', '13.780', '13.860', '13.860', '883,200']
29
14.380
30
14.560
31
13.780
32
13.860
33
13.860
34
883,200
35
Apr 03, 2019
['2019-04-03', '14.260', '14.340', '14.020', '14.200', '14.200', '716,999']
36
14.260
37
14.340
38
14.020
39
14.200
40
14.200
41
716,999
42
Apr 02, 2019
['2019-04-02', '13.500', '14.260', '13.500', '14.200', '14.200', '1,590,100']
43
13.500
44
14.260
45
13.500
46
14.200
47
14.200
48
1,590,100
49
Apr 01, 2019
['2019-04-01', '13.100', '13.620', '13.100', '13.500', '13.500', '1,497,400']
50
13.100
51
13.620
52
13.100
53
13.500
54
13.500
55
1,497,400
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1939.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.250', '1.250', '1.250', '1.250', '1.250', '-']
1
1.250
2
1.250
3
1.250
4
1.250
5
1.250
6
-
7
Apr 10, 2019
['2019-04-10', '1.250', '1.250', '1.250', '1.250', '1.250', '-']
8
1.250
9
1.250
10
1.250
11
1.250
12
1.250
13
-
14
Apr 09, 2019
['2019-04-09', '1.280', '1.280', '1.230', '1.250', '1.250', '78,000']
15
1.280
16
1.280
17
1.230
18
1.250
19
1.250
20
78,000
21
Apr 08, 2019
['2019-04-08', '1.250', '1.290', '1.250', '1.290', '1.290', '122,000']
22
1.250
23
1.290
24
1.250
25
1.290
26
1.290
27
122,000
28
Apr 04, 2019
['2019-04-04', '1.290', '1.360', '1.280', '1.360', '1.360', '52,000']
29
1.290
30
1.360
31
1.280
32
1.360
33
1.360
34
52,000
35
Apr 03, 2019
['2019-04-03', '1.250', '1.290', '1.250', '1.290', '1.290', '28,000']
36
1.250
37
1.290
38
1.250
39
1.290
40
1.290
41
28,000
42
Apr 02, 2019
['2019-04-02', '1.390', '1.390', '1.230', '1.280', '1.280', '90,000']
43
1.390
44
1.390
45
1.230
46
1.280
47
1.280
48
90,000
49
Apr 01, 2019
['2019-04-01', '1.340', '1.340', '1.340', '1.340', '1.340', '-']
50
1.340
51
1.340
52
1.340
53
1.340
54
1.340
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1809.HKneeds update
[50]
[50]
59
50
length in loop59
50poped
[]
[]
0
Apr 11, 2019
['2019-04-11', '6.930', '7.000', '6.930', '7.000', '7.000', '332,500']
1
6.930
2
7.000
3
6.930
4
7.000
5
7.000
6
332,500
7
Apr 10, 2019
['2019-04-10', '6.960', '6.970', '6.770', '6.920', '6.920', '210,500']
8
6.960
9
6.970
10
6.770
11
6.920
12
6.920
13
210,500
14
Apr 09, 2019
['2019-04-09', '7.070', '7.070', '6.890', '7.010', '7.010', '320,500']
15
7.070
16
7.070
17
6.890
18
7.010
19
7.010
20
320,500
21
Apr 08, 2019
['2019-04-08', '7.140', '7.150', '7.000', '7.100', '7.100', '355,000']
22
7.140
23
7.150
24
7.000
25
7.100
26
7.100
27
355,000
28
Apr 04, 2019
['2019-04-04', '7.230', '7.230', '7.020', '7.130', '7.130', '354,000']
29
7.230
30
7.230
31
7.020
32
7.130
33
7.130
34
354,000
35
Apr 03, 2019
['2019-04-03', '7.810', '7.820', '7.170', '7.240', '7.240', '315,000']
36
7.810
37
7.820
38
7.170
39
7.240
40
7.240
41
315,000
42
Apr 02, 2019
['2019-04-02', '7.700', '7.800', '7.440', '7.800', '7.800', '400,500']
43
7.700
44
7.800
45
7.440
46
7.800
47
7.800
48
400,500
49
Apr 01, 2019
['2019-04-01', '8.170', '8.500', '7.670', '7.740', '7.502', '389,500']
50
8.170
51
8.500
52
7.670
53
7.740
54
7.502
55
389,500
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1736.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.310', '0.310', '0.300', '0.300', '0.300', '790,000']
1
0.310
2
0.310
3
0.300
4
0.300
5
0.300
6
790,000
7
Apr 10, 2019
['2019-04-10', '0.320', '0.320', '0.305', '0.310', '0.310', '1,490,000']
8
0.320
9
0.320
10
0.305
11
0.310
12
0.310
13
1,490,000
14
Apr 09, 2019
['2019-04-09', '0.310', '0.320', '0.310', '0.320', '0.320', '112,000']
15
0.310
16
0.320
17
0.310
18
0.320
19
0.320
20
112,000
21
Apr 08, 2019
['2019-04-08', '0.310', '0.320', '0.310', '0.310', '0.310', '522,000']
22
0.310
23
0.320
24
0.310
25
0.310
26
0.310
27
522,000
28
Apr 04, 2019
['2019-04-04', '0.300', '0.315', '0.300', '0.310', '0.310', '548,000']
29
0.300
30
0.315
31
0.300
32
0.310
33
0.310
34
548,000
35
Apr 03, 2019
['2019-04-03', '0.300', '0.315', '0.300', '0.310', '0.310', '306,000']
36
0.300
37
0.315
38
0.300
39
0.310
40
0.310
41
306,000
42
Apr 02, 2019
['2019-04-02', '0.295', '0.315', '0.295', '0.305', '0.305', '626,000']
43
0.295
44
0.315
45
0.295
46
0.305
47
0.305
48
626,000
49
Apr 01, 2019
['2019-04-01', '0.320', '0.320', '0.290', '0.305', '0.305', '1,924,000']
50
0.320
51
0.320
52
0.290
53
0.305
54
0.305
55
1,924,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1540.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.860', '0.860', '0.850', '0.850', '0.850', '300,000']
1
0.860
2
0.860
3
0.850
4
0.850
5
0.850
6
300,000
7
Apr 10, 2019
['2019-04-10', '0.850', '0.860', '0.850', '0.860', '0.860', '177,000']
8
0.850
9
0.860
10
0.850
11
0.860
12
0.860
13
177,000
14
Apr 09, 2019
['2019-04-09', '0.840', '0.840', '0.840', '0.840', '0.840', '222,000']
15
0.840
16
0.840
17
0.840
18
0.840
19
0.840
20
222,000
21
Apr 08, 2019
['2019-04-08', '0.850', '0.850', '0.840', '0.840', '0.840', '180,000']
22
0.850
23
0.850
24
0.840
25
0.840
26
0.840
27
180,000
28
Apr 04, 2019
['2019-04-04', '0.860', '0.860', '0.860', '0.860', '0.860', '-']
29
0.860
30
0.860
31
0.860
32
0.860
33
0.860
34
-
35
Apr 03, 2019
['2019-04-03', '0.860', '0.860', '0.860', '0.860', '0.860', '-']
36
0.860
37
0.860
38
0.860
39
0.860
40
0.860
41
-
42
Apr 02, 2019
['2019-04-02', '0.840', '0.840', '0.840', '0.840', '0.840', '234,000']
43
0.840
44
0.840
45
0.840
46
0.840
47
0.840
48
234,000
49
Apr 01, 2019
['2019-04-01', '0.850', '0.850', '0.840', '0.840', '0.840', '96,000']
50
0.850
51
0.850
52
0.840
53
0.840
54
0.840
55
96,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1781.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.270', '1.380', '1.180', '1.190', '1.190', '9,038,000']
1
1.270
2
1.380
3
1.180
4
1.190
5
1.190
6
9,038,000
7
Apr 10, 2019
['2019-04-10', '1.350', '1.350', '1.270', '1.270', '1.270', '7,398,000']
8
1.350
9
1.350
10
1.270
11
1.270
12
1.270
13
7,398,000
14
Apr 09, 2019
['2019-04-09', '1.340', '1.390', '1.300', '1.330', '1.330', '4,340,000']
15
1.340
16
1.390
17
1.300
18
1.330
19
1.330
20
4,340,000
21
Apr 08, 2019
['2019-04-08', '1.190', '1.350', '1.180', '1.260', '1.260', '4,642,000']
22
1.190
23
1.350
24
1.180
25
1.260
26
1.260
27
4,642,000
28
Apr 04, 2019
['2019-04-04', '1.160', '1.190', '1.160', '1.190', '1.190', '3,098,000']
29
1.160
30
1.190
31
1.160
32
1.190
33
1.190
34
3,098,000
35
Apr 03, 2019
['2019-04-03', '1.160', '1.190', '1.150', '1.180', '1.180', '3,094,000']
36
1.160
37
1.190
38
1.150
39
1.180
40
1.180
41
3,094,000
42
Apr 02, 2019
['2019-04-02', '1.230', '1.230', '1.180', '1.180', '1.180', '3,016,000']
43
1.230
44
1.230
45
1.180
46
1.180
47
1.180
48
3,016,000
49
Apr 01, 2019
['2019-04-01', '1.300', '1.330', '1.200', '1.260', '1.260', '3,858,000']
50
1.300
51
1.330
52
1.200
53
1.260
54
1.260
55
3,858,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8017.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.570', '0.570', '0.570', '0.570', '0.570', '-']
1
0.570
2
0.570
3
0.570
4
0.570
5
0.570
6
-
7
Apr 10, 2019
['2019-04-10', '0.590', '0.590', '0.570', '0.570', '0.570', '340,000']
8
0.590
9
0.590
10
0.570
11
0.570
12
0.570
13
340,000
14
Apr 09, 2019
['2019-04-09', '0.610', '0.620', '0.580', '0.600', '0.600', '1,424,000']
15
0.610
16
0.620
17
0.580
18
0.600
19
0.600
20
1,424,000
21
Apr 08, 2019
['2019-04-08', '0.670', '0.670', '0.620', '0.620', '0.620', '1,200,000']
22
0.670
23
0.670
24
0.620
25
0.620
26
0.620
27
1,200,000
28
Apr 04, 2019
['2019-04-04', '0.680', '0.680', '0.640', '0.660', '0.660', '372,000']
29
0.680
30
0.680
31
0.640
32
0.660
33
0.660
34
372,000
35
Apr 03, 2019
['2019-04-03', '0.640', '0.690', '0.640', '0.650', '0.650', '1,020,000']
36
0.640
37
0.690
38
0.640
39
0.650
40
0.650
41
1,020,000
42
Apr 02, 2019
['2019-04-02', '0.640', '0.640', '0.620', '0.640', '0.640', '400,000']
43
0.640
44
0.640
45
0.620
46
0.640
47
0.640
48
400,000
49
Apr 01, 2019
['2019-04-01', '0.640', '0.640', '0.600', '0.630', '0.630', '808,000']
50
0.640
51
0.640
52
0.600
53
0.630
54
0.630
55
808,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1787.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '19.000', '19.060', '18.680', '18.740', '18.740', '1,084,250']
1
19.000
2
19.060
3
18.680
4
18.740
5
18.740
6
1,084,250
7
Apr 10, 2019
['2019-04-10', '18.780', '19.160', '18.660', '18.840', '18.840', '1,273,750']
8
18.780
9
19.160
10
18.660
11
18.840
12
18.840
13
1,273,750
14
Apr 09, 2019
['2019-04-09', '18.620', '18.840', '18.520', '18.620', '18.620', '1,548,500']
15
18.620
16
18.840
17
18.520
18
18.620
19
18.620
20
1,548,500
21
Apr 08, 2019
['2019-04-08', '18.620', '18.880', '18.460', '18.700', '18.700', '1,241,750']
22
18.620
23
18.880
24
18.460
25
18.700
26
18.700
27
1,241,750
28
Apr 04, 2019
['2019-04-04', '18.700', '18.840', '18.500', '18.680', '18.680', '1,352,250']
29
18.700
30
18.840
31
18.500
32
18.680
33
18.680
34
1,352,250
35
Apr 03, 2019
['2019-04-03', '18.960', '19.000', '18.620', '18.620', '18.620', '1,866,000']
36
18.960
37
19.000
38
18.620
39
18.620
40
18.620
41
1,866,000
42
Apr 02, 2019
['2019-04-02', '18.520', '18.900', '18.420', '18.680', '18.680', '1,222,500']
43
18.520
44
18.900
45
18.420
46
18.680
47
18.680
48
1,222,500
49
Apr 01, 2019
['2019-04-01', '18.820', '18.940', '18.320', '18.400', '18.400', '3,011,750']
50
18.820
51
18.940
52
18.320
53
18.400
54
18.400
55
3,011,750
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1911.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '21.250', '21.250', '20.200', '20.650', '20.650', '152,465']
1
21.250
2
21.250
3
20.200
4
20.650
5
20.650
6
152,465
7
Apr 10, 2019
['2019-04-10', '21.650', '21.700', '20.500', '21.000', '21.000', '270,300']
8
21.650
9
21.700
10
20.500
11
21.000
12
21.000
13
270,300
14
Apr 09, 2019
['2019-04-09', '21.750', '21.750', '21.200', '21.500', '21.500', '207,000']
15
21.750
16
21.750
17
21.200
18
21.500
19
21.500
20
207,000
21
Apr 08, 2019
['2019-04-08', '21.600', '22.100', '20.950', '21.750', '21.750', '417,300']
22
21.600
23
22.100
24
20.950
25
21.750
26
21.750
27
417,300
28
Apr 04, 2019
['2019-04-04', '22.200', '22.300', '21.750', '21.750', '21.750', '349,900']
29
22.200
30
22.300
31
21.750
32
21.750
33
21.750
34
349,900
35
Apr 03, 2019
['2019-04-03', '21.000', '22.100', '21.000', '21.800', '21.800', '217,000']
36
21.000
37
22.100
38
21.000
39
21.800
40
21.800
41
217,000
42
Apr 02, 2019
['2019-04-02', '21.600', '21.600', '21.100', '21.300', '21.300', '101,100']
43
21.600
44
21.600
45
21.100
46
21.300
47
21.300
48
101,100
49
Apr 01, 2019
['2019-04-01', '21.350', '21.900', '21.200', '21.600', '21.600', '402,600']
50
21.350
51
21.900
52
21.200
53
21.600
54
21.600
55
402,600
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1723.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.800', '3.800', '3.340', '3.400', '3.400', '48,000']
1
3.800
2
3.800
3
3.340
4
3.400
5
3.400
6
48,000
7
Apr 10, 2019
['2019-04-10', '3.750', '3.800', '3.750', '3.800', '3.800', '6,000']
8
3.750
9
3.800
10
3.750
11
3.800
12
3.800
13
6,000
14
Apr 09, 2019
['2019-04-09', '3.810', '3.810', '3.750', '3.750', '3.750', '58,000']
15
3.810
16
3.810
17
3.750
18
3.750
19
3.750
20
58,000
21
Apr 08, 2019
['2019-04-08', '3.810', '3.810', '3.810', '3.810', '3.810', '-']
22
3.810
23
3.810
24
3.810
25
3.810
26
3.810
27
-
28
Apr 04, 2019
['2019-04-04', '3.820', '3.820', '3.820', '3.820', '3.820', '4,000']
29
3.820
30
3.820
31
3.820
32
3.820
33
3.820
34
4,000
35
Apr 03, 2019
['2019-04-03', '3.720', '3.860', '3.720', '3.800', '3.800', '170,000']
36
3.720
37
3.860
38
3.720
39
3.800
40
3.800
41
170,000
42
Apr 02, 2019
['2019-04-02', '3.720', '3.720', '3.720', '3.720', '3.720', '-']
43
3.720
44
3.720
45
3.720
46
3.720
47
3.720
48
-
49
Apr 01, 2019
['2019-04-01', '3.720', '3.730', '3.720', '3.720', '3.720', '24,000']
50
3.720
51
3.730
52
3.720
53
3.720
54
3.720
55
24,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6862.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '31.000', '32.400', '29.750', '29.800', '29.800', '7,412,468']
1
31.000
2
32.400
3
29.750
4
29.800
5
29.800
6
7,412,468
7
Apr 10, 2019
['2019-04-10', '30.100', '31.500', '29.550', '31.450', '31.450', '14,458,148']
8
30.100
9
31.500
10
29.550
11
31.450
12
31.450
13
14,458,148
14
Apr 09, 2019
['2019-04-09', '29.000', '30.150', '28.400', '30.000', '30.000', '7,960,300']
15
29.000
16
30.150
17
28.400
18
30.000
19
30.000
20
7,960,300
21
Apr 08, 2019
['2019-04-08', '28.400', '28.550', '28.000', '28.550', '28.550', '2,864,286']
22
28.400
23
28.550
24
28.000
25
28.550
26
28.550
27
2,864,286
28
Apr 04, 2019
['2019-04-04', '28.000', '29.050', '27.350', '27.700', '27.700', '5,272,548']
29
28.000
30
29.050
31
27.350
32
27.700
33
27.700
34
5,272,548
35
Apr 03, 2019
['2019-04-03', '28.200', '28.200', '27.450', '27.900', '27.900', '3,645,023']
36
28.200
37
28.200
38
27.450
39
27.900
40
27.900
41
3,645,023
42
Apr 02, 2019
['2019-04-02', '27.250', '28.400', '27.000', '27.950', '27.950', '7,362,979']
43
27.250
44
28.400
45
27.000
46
27.950
47
27.950
48
7,362,979
49
Apr 01, 2019
['2019-04-01', '25.500', '27.200', '25.100', '27.050', '27.050', '11,177,002']
50
25.500
51
27.200
52
25.100
53
27.050
54
27.050
55
11,177,002
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1748.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.470', '1.630', '1.470', '1.600', '1.600', '1,306,000']
1
1.470
2
1.630
3
1.470
4
1.600
5
1.600
6
1,306,000
7
Apr 10, 2019
['2019-04-10', '1.460', '1.490', '1.460', '1.490', '1.490', '254,000']
8
1.460
9
1.490
10
1.460
11
1.490
12
1.490
13
254,000
14
Apr 09, 2019
['2019-04-09', '1.440', '1.550', '1.440', '1.490', '1.490', '1,994,000']
15
1.440
16
1.550
17
1.440
18
1.490
19
1.490
20
1,994,000
21
Apr 08, 2019
['2019-04-08', '1.430', '1.440', '1.440', '1.440', '1.440', '482,000']
22
1.430
23
1.440
24
1.440
25
1.440
26
1.440
27
482,000
28
Apr 04, 2019
['2019-04-04', '1.410', '1.450', '1.370', '1.440', '1.440', '152,000']
29
1.410
30
1.450
31
1.370
32
1.440
33
1.440
34
152,000
35
Apr 03, 2019
['2019-04-03', '1.400', '1.400', '1.360', '1.360', '1.360', '290,000']
36
1.400
37
1.400
38
1.360
39
1.360
40
1.360
41
290,000
42
Apr 02, 2019
['2019-04-02', '1.450', '1.500', '1.390', '1.480', '1.480', '886,000']
43
1.450
44
1.500
45
1.390
46
1.480
47
1.480
48
886,000
49
Apr 01, 2019
['2019-04-01', '1.480', '1.490', '1.480', '1.500', '1.500', '52,000']
50
1.480
51
1.490
52
1.480
53
1.500
54
1.500
55
52,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3690.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '53.500', '53.850', '52.600', '53.050', '53.050', '10,453,999']
1
53.500
2
53.850
3
52.600
4
53.050
5
53.050
6
10,453,999
7
Apr 10, 2019
['2019-04-10', '53.000', '54.200', '51.850', '53.750', '53.750', '34,969,903']
8
53.000
9
54.200
10
51.850
11
53.750
12
53.750
13
34,969,903
14
Apr 09, 2019
['2019-04-09', '51.100', '53.300', '51.000', '53.150', '53.150', '31,836,998']
15
51.100
16
53.300
17
51.000
18
53.150
19
53.150
20
31,836,998
21
Apr 08, 2019
['2019-04-08', '50.900', '52.350', '50.200', '51.800', '51.800', '18,695,042']
22
50.900
23
52.350
24
50.200
25
51.800
26
51.800
27
18,695,042
28
Apr 04, 2019
['2019-04-04', '50.800', '52.000', '50.800', '51.250', '51.250', '14,565,369']
29
50.800
30
52.000
31
50.800
32
51.250
33
51.250
34
14,565,369
35
Apr 03, 2019
['2019-04-03', '50.800', '52.400', '50.800', '52.300', '52.300', '6,391,298']
36
50.800
37
52.400
38
50.800
39
52.300
40
52.300
41
6,391,298
42
Apr 02, 2019
['2019-04-02', '53.400', '53.400', '51.150', '51.750', '51.750', '9,451,381']
43
53.400
44
53.400
45
51.150
46
51.750
47
51.750
48
9,451,381
49
Apr 01, 2019
['2019-04-01', '53.600', '53.800', '52.000', '52.700', '52.700', '35,261,869']
50
53.600
51
53.800
52
52.000
53
52.700
54
52.700
55
35,261,869
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8619.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.100', '2.100', '2.080', '2.090', '2.090', '490,000']
1
2.100
2
2.100
3
2.080
4
2.090
5
2.090
6
490,000
7
Apr 10, 2019
['2019-04-10', '2.020', '2.090', '2.020', '2.090', '2.090', '360,000']
8
2.020
9
2.090
10
2.020
11
2.090
12
2.090
13
360,000
14
Apr 09, 2019
['2019-04-09', '2.130', '2.130', '2.020', '2.060', '2.060', '550,000']
15
2.130
16
2.130
17
2.020
18
2.060
19
2.060
20
550,000
21
Apr 08, 2019
['2019-04-08', '2.240', '2.240', '2.120', '2.120', '2.120', '570,000']
22
2.240
23
2.240
24
2.120
25
2.120
26
2.120
27
570,000
28
Apr 04, 2019
['2019-04-04', '2.280', '2.280', '2.200', '2.240', '2.240', '450,000']
29
2.280
30
2.280
31
2.200
32
2.240
33
2.240
34
450,000
35
Apr 03, 2019
['2019-04-03', '2.190', '2.330', '2.190', '2.280', '2.280', '1,570,000']
36
2.190
37
2.330
38
2.190
39
2.280
40
2.280
41
1,570,000
42
Apr 02, 2019
['2019-04-02', '2.270', '2.270', '2.150', '2.200', '2.200', '870,000']
43
2.270
44
2.270
45
2.150
46
2.200
47
2.200
48
870,000
49
Apr 01, 2019
['2019-04-01', '2.370', '2.480', '2.260', '2.340', '2.340', '780,000']
50
2.370
51
2.480
52
2.260
53
2.340
54
2.340
55
780,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2680.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.560', '1.560', '1.470', '1.530', '1.530', '2,132,000']
1
1.560
2
1.560
3
1.470
4
1.530
5
1.530
6
2,132,000
7
Apr 10, 2019
['2019-04-10', '1.560', '1.590', '1.530', '1.570', '1.570', '2,242,000']
8
1.560
9
1.590
10
1.530
11
1.570
12
1.570
13
2,242,000
14
Apr 09, 2019
['2019-04-09', '1.540', '1.620', '1.500', '1.560', '1.560', '2,848,000']
15
1.540
16
1.620
17
1.500
18
1.560
19
1.560
20
2,848,000
21
Apr 08, 2019
['2019-04-08', '1.500', '1.600', '1.500', '1.550', '1.550', '1,912,000']
22
1.500
23
1.600
24
1.500
25
1.550
26
1.550
27
1,912,000
28
Apr 04, 2019
['2019-04-04', '1.490', '1.500', '1.290', '1.500', '1.500', '1,502,000']
29
1.490
30
1.500
31
1.290
32
1.500
33
1.500
34
1,502,000
35
Apr 03, 2019
['2019-04-03', '1.520', '1.540', '1.490', '1.500', '1.500', '3,882,000']
36
1.520
37
1.540
38
1.490
39
1.500
40
1.500
41
3,882,000
42
Apr 02, 2019
['2019-04-02', '1.520', '1.600', '1.480', '1.520', '1.520', '5,868,000']
43
1.520
44
1.600
45
1.480
46
1.520
47
1.520
48
5,868,000
49
Apr 01, 2019
['2019-04-01', '1.530', '1.700', '1.460', '1.510', '1.510', '6,910,000']
50
1.530
51
1.700
52
1.460
53
1.510
54
1.510
55
6,910,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2552.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '7.400', '7.500', '7.360', '7.360', '7.360', '34,363']
1
7.400
2
7.500
3
7.360
4
7.360
5
7.360
6
34,363
7
Apr 10, 2019
['2019-04-10', '7.420', '7.500', '7.420', '7.500', '7.500', '7,500']
8
7.420
9
7.500
10
7.420
11
7.500
12
7.500
13
7,500
14
Apr 09, 2019
['2019-04-09', '7.500', '7.500', '7.420', '7.420', '7.420', '37,500']
15
7.500
16
7.500
17
7.420
18
7.420
19
7.420
20
37,500
21
Apr 08, 2019
['2019-04-08', '7.800', '7.800', '7.310', '7.370', '7.370', '110,500']
22
7.800
23
7.800
24
7.310
25
7.370
26
7.370
27
110,500
28
Apr 04, 2019
['2019-04-04', '7.800', '7.950', '7.800', '7.800', '7.800', '174,500']
29
7.800
30
7.950
31
7.800
32
7.800
33
7.800
34
174,500
35
Apr 03, 2019
['2019-04-03', '7.800', '7.900', '7.800', '7.800', '7.800', '15,000']
36
7.800
37
7.900
38
7.800
39
7.800
40
7.800
41
15,000
42
Apr 02, 2019
['2019-04-02', '7.800', '7.950', '7.760', '7.760', '7.760', '23,000']
43
7.800
44
7.950
45
7.760
46
7.760
47
7.760
48
23,000
49
Apr 01, 2019
['2019-04-01', '7.700', '7.920', '7.700', '7.800', '7.800', '83,000']
50
7.700
51
7.920
52
7.700
53
7.800
54
7.800
55
83,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8601.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.490', '0.490', '0.490', '0.490', '0.490', '40,000']
1
0.490
2
0.490
3
0.490
4
0.490
5
0.490
6
40,000
7
Apr 10, 2019
['2019-04-10', '0.475', '0.475', '0.475', '0.475', '0.475', '-']
8
0.475
9
0.475
10
0.475
11
0.475
12
0.475
13
-
14
Apr 09, 2019
['2019-04-09', '0.470', '0.470', '0.470', '0.470', '0.470', '-']
15
0.470
16
0.470
17
0.470
18
0.470
19
0.470
20
-
21
Apr 08, 2019
['2019-04-08', '0.500', '0.500', '0.500', '0.500', '0.500', '-']
22
0.500
23
0.500
24
0.500
25
0.500
26
0.500
27
-
28
Apr 04, 2019
['2019-04-04', '0.500', '0.500', '0.500', '0.500', '0.500', '-']
29
0.500
30
0.500
31
0.500
32
0.500
33
0.500
34
-
35
Apr 03, 2019
['2019-04-03', '0.500', '0.500', '0.500', '0.500', '0.500', '-']
36
0.500
37
0.500
38
0.500
39
0.500
40
0.500
41
-
42
Apr 02, 2019
['2019-04-02', '0.490', '0.500', '0.485', '0.500', '0.500', '170,000']
43
0.490
44
0.500
45
0.485
46
0.500
47
0.500
48
170,000
49
Apr 01, 2019
['2019-04-01', '0.485', '0.490', '0.485', '0.490', '0.490', '220,000']
50
0.485
51
0.490
52
0.485
53
0.490
54
0.490
55
220,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1969.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.520', '1.520', '1.500', '1.500', '1.500', '54,000']
1
1.520
2
1.520
3
1.500
4
1.500
5
1.500
6
54,000
7
Apr 10, 2019
['2019-04-10', '1.490', '1.510', '1.480', '1.500', '1.500', '288,000']
8
1.490
9
1.510
10
1.480
11
1.500
12
1.500
13
288,000
14
Apr 09, 2019
['2019-04-09', '1.520', '1.550', '1.510', '1.510', '1.510', '40,000']
15
1.520
16
1.550
17
1.510
18
1.510
19
1.510
20
40,000
21
Apr 08, 2019
['2019-04-08', '1.560', '1.560', '1.500', '1.520', '1.520', '320,000']
22
1.560
23
1.560
24
1.500
25
1.520
26
1.520
27
320,000
28
Apr 04, 2019
['2019-04-04', '1.500', '1.560', '1.490', '1.550', '1.550', '446,000']
29
1.500
30
1.560
31
1.490
32
1.550
33
1.550
34
446,000
35
Apr 03, 2019
['2019-04-03', '1.510', '1.510', '1.500', '1.500', '1.500', '171,000']
36
1.510
37
1.510
38
1.500
39
1.500
40
1.500
41
171,000
42
Apr 02, 2019
['2019-04-02', '1.510', '1.530', '1.460', '1.510', '1.510', '173,000']
43
1.510
44
1.530
45
1.460
46
1.510
47
1.510
48
173,000
49
Apr 01, 2019
['2019-04-01', '1.510', '1.510', '1.490', '1.490', '1.490', '85,000']
50
1.510
51
1.510
52
1.490
53
1.490
54
1.490
55
85,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1615.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.365', '0.370', '0.365', '0.370', '0.370', '335,000']
1
0.365
2
0.370
3
0.365
4
0.370
5
0.370
6
335,000
7
Apr 10, 2019
['2019-04-10', '0.370', '0.370', '0.365', '0.370', '0.370', '665,000']
8
0.370
9
0.370
10
0.365
11
0.370
12
0.370
13
665,000
14
Apr 09, 2019
['2019-04-09', '0.370', '0.385', '0.370', '0.370', '0.370', '755,000']
15
0.370
16
0.385
17
0.370
18
0.370
19
0.370
20
755,000
21
Apr 08, 2019
['2019-04-08', '0.375', '0.375', '0.370', '0.370', '0.370', '275,000']
22
0.375
23
0.375
24
0.370
25
0.370
26
0.370
27
275,000
28
Apr 04, 2019
['2019-04-04', '0.370', '0.375', '0.365', '0.375', '0.375', '900,000']
29
0.370
30
0.375
31
0.365
32
0.375
33
0.375
34
900,000
35
Apr 03, 2019
['2019-04-03', '0.365', '0.375', '0.365', '0.370', '0.370', '525,000']
36
0.365
37
0.375
38
0.365
39
0.370
40
0.370
41
525,000
42
Apr 02, 2019
['2019-04-02', '0.365', '0.385', '0.365', '0.365', '0.365', '1,705,000']
43
0.365
44
0.385
45
0.365
46
0.365
47
0.365
48
1,705,000
49
Apr 01, 2019
['2019-04-01', '0.365', '0.365', '0.360', '0.360', '0.360', '1,030,000']
50
0.365
51
0.365
52
0.360
53
0.360
54
0.360
55
1,030,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8609.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.222', '0.222', '0.211', '0.221', '0.221', '100,000']
1
0.222
2
0.222
3
0.211
4
0.221
5
0.221
6
100,000
7
Apr 10, 2019
['2019-04-10', '0.224', '0.224', '0.224', '0.224', '0.224', '-']
8
0.224
9
0.224
10
0.224
11
0.224
12
0.224
13
-
14
Apr 09, 2019
['2019-04-09', '0.212', '0.225', '0.212', '0.224', '0.224', '170,000']
15
0.212
16
0.225
17
0.212
18
0.224
19
0.224
20
170,000
21
Apr 08, 2019
['2019-04-08', '0.226', '0.226', '0.209', '0.226', '0.226', '180,000']
22
0.226
23
0.226
24
0.209
25
0.226
26
0.226
27
180,000
28
Apr 04, 2019
['2019-04-04', '0.213', '0.229', '0.213', '0.226', '0.226', '480,000']
29
0.213
30
0.229
31
0.213
32
0.226
33
0.226
34
480,000
35
Apr 03, 2019
['2019-04-03', '0.210', '0.226', '0.209', '0.219', '0.219', '280,000']
36
0.210
37
0.226
38
0.209
39
0.219
40
0.219
41
280,000
42
Apr 02, 2019
['2019-04-02', '0.228', '0.228', '0.228', '0.228', '0.228', '-']
43
0.228
44
0.228
45
0.228
46
0.228
47
0.228
48
-
49
Apr 01, 2019
['2019-04-01', '0.210', '0.228', '0.210', '0.228', '0.228', '70,000']
50
0.210
51
0.228
52
0.210
53
0.228
54
0.228
55
70,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8482.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.240', '0.249', '0.236', '0.249', '0.249', '1,160,000']
1
0.240
2
0.249
3
0.236
4
0.249
5
0.249
6
1,160,000
7
Apr 10, 2019
['2019-04-10', '0.245', '0.245', '0.240', '0.244', '0.244', '510,000']
8
0.245
9
0.245
10
0.240
11
0.244
12
0.244
13
510,000
14
Apr 09, 2019
['2019-04-09', '0.246', '0.250', '0.242', '0.250', '0.250', '450,000']
15
0.246
16
0.250
17
0.242
18
0.250
19
0.250
20
450,000
21
Apr 08, 2019
['2019-04-08', '0.250', '0.255', '0.241', '0.250', '0.250', '410,000']
22
0.250
23
0.255
24
0.241
25
0.250
26
0.250
27
410,000
28
Apr 04, 2019
['2019-04-04', '0.242', '0.247', '0.233', '0.247', '0.247', '330,000']
29
0.242
30
0.247
31
0.233
32
0.247
33
0.247
34
330,000
35
Apr 03, 2019
['2019-04-03', '0.222', '0.250', '0.220', '0.242', '0.242', '3,090,000']
36
0.222
37
0.250
38
0.220
39
0.242
40
0.242
41
3,090,000
42
Apr 02, 2019
['2019-04-02', '0.234', '0.234', '0.220', '0.230', '0.230', '550,000']
43
0.234
44
0.234
45
0.220
46
0.230
47
0.230
48
550,000
49
Apr 01, 2019
['2019-04-01', '0.240', '0.247', '0.237', '0.247', '0.247', '150,000']
50
0.240
51
0.247
52
0.237
53
0.247
54
0.247
55
150,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1869.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.310', '0.310', '0.310', '0.310', '0.310', '-']
1
0.310
2
0.310
3
0.310
4
0.310
5
0.310
6
-
7
Apr 10, 2019
['2019-04-10', '0.300', '0.315', '0.300', '0.310', '0.310', '1,370,000']
8
0.300
9
0.315
10
0.300
11
0.310
12
0.310
13
1,370,000
14
Apr 09, 2019
['2019-04-09', '0.300', '0.310', '0.300', '0.300', '0.300', '1,860,000']
15
0.300
16
0.310
17
0.300
18
0.300
19
0.300
20
1,860,000
21
Apr 08, 2019
['2019-04-08', '0.300', '0.305', '0.300', '0.305', '0.305', '1,180,000']
22
0.300
23
0.305
24
0.300
25
0.305
26
0.305
27
1,180,000
28
Apr 04, 2019
['2019-04-04', '0.305', '0.305', '0.300', '0.300', '0.300', '150,000']
29
0.305
30
0.305
31
0.300
32
0.300
33
0.300
34
150,000
35
Apr 03, 2019
['2019-04-03', '0.310', '0.310', '0.295', '0.305', '0.305', '1,560,040']
36
0.310
37
0.310
38
0.295
39
0.305
40
0.305
41
1,560,040
42
Apr 02, 2019
['2019-04-02', '0.300', '0.310', '0.300', '0.305', '0.305', '1,370,000']
43
0.300
44
0.310
45
0.300
46
0.305
47
0.305
48
1,370,000
49
Apr 01, 2019
['2019-04-01', '0.290', '0.300', '0.290', '0.300', '0.300', '370,000']
50
0.290
51
0.300
52
0.290
53
0.300
54
0.300
55
370,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8210.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.210', '0.210', '0.200', '0.201', '0.201', '1,900,000']
1
0.210
2
0.210
3
0.200
4
0.201
5
0.201
6
1,900,000
7
Apr 10, 2019
['2019-04-10', '0.210', '0.220', '0.210', '0.219', '0.219', '830,000']
8
0.210
9
0.220
10
0.210
11
0.219
12
0.219
13
830,000
14
Apr 09, 2019
['2019-04-09', '0.237', '0.237', '0.206', '0.210', '0.210', '5,430,000']
15
0.237
16
0.237
17
0.206
18
0.210
19
0.210
20
5,430,000
21
Apr 08, 2019
['2019-04-08', '0.209', '0.260', '0.209', '0.238', '0.238', '24,670,000']
22
0.209
23
0.260
24
0.209
25
0.238
26
0.238
27
24,670,000
28
Apr 04, 2019
['2019-04-04', '0.156', '0.210', '0.156', '0.209', '0.209', '3,950,000']
29
0.156
30
0.210
31
0.156
32
0.209
33
0.209
34
3,950,000
35
Apr 03, 2019
['2019-04-03', '0.164', '0.164', '0.155', '0.160', '0.160', '2,940,000']
36
0.164
37
0.164
38
0.155
39
0.160
40
0.160
41
2,940,000
42
Apr 02, 2019
['2019-04-02', '0.163', '0.163', '0.163', '0.158', '0.158', '190,000']
43
0.163
44
0.163
45
0.163
46
0.158
47
0.158
48
190,000
49
Apr 01, 2019
['2019-04-01', '0.153', '0.157', '0.153', '0.157', '0.157', '1,810,000']
50
0.153
51
0.157
52
0.153
53
0.157
54
0.157
55
1,810,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1783.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.270', '0.270', '0.265', '0.265', '0.265', '410,000']
1
0.270
2
0.270
3
0.265
4
0.265
5
0.265
6
410,000
7
Apr 10, 2019
['2019-04-10', '0.275', '0.275', '0.270', '0.270', '0.270', '570,000']
8
0.275
9
0.275
10
0.270
11
0.270
12
0.270
13
570,000
14
Apr 09, 2019
['2019-04-09', '0.275', '0.280', '0.275', '0.280', '0.280', '1,700,000']
15
0.275
16
0.280
17
0.275
18
0.280
19
0.280
20
1,700,000
21
Apr 08, 2019
['2019-04-08', '0.275', '0.275', '0.275', '0.275', '0.275', '120,000']
22
0.275
23
0.275
24
0.275
25
0.275
26
0.275
27
120,000
28
Apr 04, 2019
['2019-04-04', '0.275', '0.275', '0.270', '0.275', '0.275', '350,000']
29
0.275
30
0.275
31
0.270
32
0.275
33
0.275
34
350,000
35
Apr 03, 2019
['2019-04-03', '0.280', '0.285', '0.270', '0.275', '0.275', '1,110,000']
36
0.280
37
0.285
38
0.270
39
0.275
40
0.275
41
1,110,000
42
Apr 02, 2019
['2019-04-02', '0.275', '0.280', '0.270', '0.280', '0.280', '690,000']
43
0.275
44
0.280
45
0.270
46
0.280
47
0.280
48
690,000
49
Apr 01, 2019
['2019-04-01', '0.280', '0.285', '0.275', '0.280', '0.280', '3,600,000']
50
0.280
51
0.285
52
0.275
53
0.280
54
0.280
55
3,600,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1725.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.500', '1.500', '1.450', '1.490', '1.490', '195,000']
1
1.500
2
1.500
3
1.450
4
1.490
5
1.490
6
195,000
7
Apr 10, 2019
['2019-04-10', '1.490', '1.490', '1.490', '1.490', '1.490', '-']
8
1.490
9
1.490
10
1.490
11
1.490
12
1.490
13
-
14
Apr 09, 2019
['2019-04-09', '1.430', '1.500', '1.430', '1.490', '1.490', '180,000']
15
1.430
16
1.500
17
1.430
18
1.490
19
1.490
20
180,000
21
Apr 08, 2019
['2019-04-08', '1.540', '1.540', '1.540', '1.540', '1.540', '-']
22
1.540
23
1.540
24
1.540
25
1.540
26
1.540
27
-
28
Apr 04, 2019
['2019-04-04', '1.550', '1.580', '1.530', '1.540', '1.540', '635,000']
29
1.550
30
1.580
31
1.530
32
1.540
33
1.540
34
635,000
35
Apr 03, 2019
['2019-04-03', '1.520', '1.530', '1.520', '1.530', '1.530', '525,000']
36
1.520
37
1.530
38
1.520
39
1.530
40
1.530
41
525,000
42
Apr 02, 2019
['2019-04-02', '1.490', '1.520', '1.490', '1.520', '1.520', '1,180,000']
43
1.490
44
1.520
45
1.490
46
1.520
47
1.520
48
1,180,000
49
Apr 01, 2019
['2019-04-01', '1.460', '1.460', '1.450', '1.450', '1.450', '35,000']
50
1.460
51
1.460
52
1.450
53
1.450
54
1.450
55
35,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8475.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.202', '0.215', '0.202', '0.205', '0.205', '225,000']
1
0.202
2
0.215
3
0.202
4
0.205
5
0.205
6
225,000
7
Apr 10, 2019
['2019-04-10', '0.202', '0.209', '0.200', '0.202', '0.202', '110,000']
8
0.202
9
0.209
10
0.200
11
0.202
12
0.202
13
110,000
14
Apr 09, 2019
['2019-04-09', '0.202', '0.202', '0.202', '0.202', '0.202', '-']
15
0.202
16
0.202
17
0.202
18
0.202
19
0.202
20
-
21
Apr 08, 2019
['2019-04-08', '0.199', '0.202', '0.199', '0.202', '0.202', '30,000']
22
0.199
23
0.202
24
0.199
25
0.202
26
0.202
27
30,000
28
Apr 04, 2019
['2019-04-04', '0.192', '0.209', '0.192', '0.200', '0.200', '1,135,000']
29
0.192
30
0.209
31
0.192
32
0.200
33
0.200
34
1,135,000
35
Apr 03, 2019
['2019-04-03', '0.196', '0.197', '0.192', '0.197', '0.197', '225,000']
36
0.196
37
0.197
38
0.192
39
0.197
40
0.197
41
225,000
42
Apr 02, 2019
['2019-04-02', '0.199', '0.201', '0.191', '0.199', '0.199', '225,000']
43
0.199
44
0.201
45
0.191
46
0.199
47
0.199
48
225,000
49
Apr 01, 2019
['2019-04-01', '0.203', '0.203', '0.196', '0.200', '0.200', '330,000']
50
0.203
51
0.203
52
0.196
53
0.200
54
0.200
55
330,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6160.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '87.000', '88.000', '86.850', '87.200', '87.200', '14,700']
1
87.000
2
88.000
3
86.850
4
87.200
5
87.200
6
14,700
7
Apr 10, 2019
['2019-04-10', '87.050', '87.050', '85.650', '87.000', '87.000', '26,000']
8
87.050
9
87.050
10
85.650
11
87.000
12
87.000
13
26,000
14
Apr 09, 2019
['2019-04-09', '88.000', '88.100', '87.000', '87.700', '87.700', '85,600']
15
88.000
16
88.100
17
87.000
18
87.700
19
87.700
20
85,600
21
Apr 08, 2019
['2019-04-08', '88.000', '88.300', '87.150', '88.000', '88.000', '26,000']
22
88.000
23
88.300
24
87.150
25
88.000
26
88.000
27
26,000
28
Apr 04, 2019
['2019-04-04', '86.800', '87.600', '86.800', '87.150', '87.150', '26,200']
29
86.800
30
87.600
31
86.800
32
87.150
33
87.150
34
26,200
35
Apr 03, 2019
['2019-04-03', '86.000', '86.500', '84.950', '86.000', '86.000', '31,100']
36
86.000
37
86.500
38
84.950
39
86.000
40
86.000
41
31,100
42
Apr 02, 2019
['2019-04-02', '82.900', '83.500', '82.550', '83.500', '83.500', '62,400']
43
82.900
44
83.500
45
82.550
46
83.500
47
83.500
48
62,400
49
Apr 01, 2019
['2019-04-01', '78.900', '80.500', '78.900', '79.500', '79.500', '21,200']
50
78.900
51
80.500
52
78.900
53
79.500
54
79.500
55
21,200
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0788.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.130', '2.140', '2.010', '2.030', '2.030', '942,821,248']
1
2.130
2
2.140
3
2.010
4
2.030
5
2.030
6
942,821,248
7
Apr 10, 2019
['2019-04-10', '2.140', '2.150', '2.090', '2.120', '2.120', '989,131,094']
8
2.140
9
2.150
10
2.090
11
2.120
12
2.120
13
989,131,094
14
Apr 09, 2019
['2019-04-09', '2.030', '2.200', '2.030', '2.180', '2.180', '1,444,103,015']
15
2.030
16
2.200
17
2.030
18
2.180
19
2.180
20
1,444,103,015
21
Apr 08, 2019
['2019-04-08', '1.930', '2.030', '1.920', '2.020', '2.020', '1,063,182,582']
22
1.930
23
2.030
24
1.920
25
2.020
26
2.020
27
1,063,182,582
28
Apr 04, 2019
['2019-04-04', '1.950', '1.950', '1.890', '1.910', '1.910', '802,389,011']
29
1.950
30
1.950
31
1.890
32
1.910
33
1.910
34
802,389,011
35
Apr 03, 2019
['2019-04-03', '1.900', '1.960', '1.900', '1.940', '1.940', '908,873,194']
36
1.900
37
1.960
38
1.900
39
1.940
40
1.940
41
908,873,194
42
Apr 02, 2019
['2019-04-02', '1.850', '1.900', '1.850', '1.890', '1.890', '710,438,140']
43
1.850
44
1.900
45
1.850
46
1.890
47
1.890
48
710,438,140
49
Apr 01, 2019
['2019-04-01', '1.830', '1.860', '1.820', '1.850', '1.850', '448,135,017']
50
1.830
51
1.860
52
1.820
53
1.850
54
1.850
55
448,135,017
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1765.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.280', '1.300', '1.240', '1.250', '1.250', '6,997,376']
1
1.280
2
1.300
3
1.240
4
1.250
5
1.250
6
6,997,376
7
Apr 10, 2019
['2019-04-10', '1.290', '1.300', '1.260', '1.290', '1.290', '13,442,000']
8
1.290
9
1.300
10
1.260
11
1.290
12
1.290
13
13,442,000
14
Apr 09, 2019
['2019-04-09', '1.270', '1.310', '1.270', '1.300', '1.300', '15,608,652']
15
1.270
16
1.310
17
1.270
18
1.300
19
1.300
20
15,608,652
21
Apr 08, 2019
['2019-04-08', '1.250', '1.360', '1.210', '1.270', '1.270', '24,032,000']
22
1.250
23
1.360
24
1.210
25
1.270
26
1.270
27
24,032,000
28
Apr 04, 2019
['2019-04-04', '1.260', '1.310', '1.220', '1.230', '1.230', '20,758,000']
29
1.260
30
1.310
31
1.220
32
1.230
33
1.230
34
20,758,000
35
Apr 03, 2019
['2019-04-03', '1.200', '1.260', '1.190', '1.260', '1.260', '13,494,000']
36
1.200
37
1.260
38
1.190
39
1.260
40
1.260
41
13,494,000
42
Apr 02, 2019
['2019-04-02', '1.220', '1.220', '1.190', '1.190', '1.190', '5,502,000']
43
1.220
44
1.220
45
1.190
46
1.190
47
1.190
48
5,502,000
49
Apr 01, 2019
['2019-04-01', '1.200', '1.220', '1.200', '1.210', '1.210', '9,524,000']
50
1.200
51
1.220
52
1.200
53
1.210
54
1.210
55
9,524,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1672.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '7.160', '7.360', '6.990', '7.110', '7.110', '2,565,000']
1
7.160
2
7.360
3
6.990
4
7.110
5
7.110
6
2,565,000
7
Apr 10, 2019
['2019-04-10', '7.150', '7.450', '7.110', '7.380', '7.380', '1,956,000']
8
7.150
9
7.450
10
7.110
11
7.380
12
7.380
13
1,956,000
14
Apr 09, 2019
['2019-04-09', '6.900', '7.330', '6.770', '7.290', '7.290', '2,850,000']
15
6.900
16
7.330
17
6.770
18
7.290
19
7.290
20
2,850,000
21
Apr 08, 2019
['2019-04-08', '6.780', '6.900', '6.720', '6.760', '6.760', '1,329,000']
22
6.780
23
6.900
24
6.720
25
6.760
26
6.760
27
1,329,000
28
Apr 04, 2019
['2019-04-04', '6.810', '6.810', '6.620', '6.660', '6.660', '1,987,000']
29
6.810
30
6.810
31
6.620
32
6.660
33
6.660
34
1,987,000
35
Apr 03, 2019
['2019-04-03', '6.660', '6.860', '6.590', '6.810', '6.810', '2,639,000']
36
6.660
37
6.860
38
6.590
39
6.810
40
6.810
41
2,639,000
42
Apr 02, 2019
['2019-04-02', '6.600', '6.680', '6.430', '6.620', '6.620', '1,162,200']
43
6.600
44
6.680
45
6.430
46
6.620
47
6.620
48
1,162,200
49
Apr 01, 2019
['2019-04-01', '6.440', '6.580', '6.350', '6.530', '6.530', '1,193,154']
50
6.440
51
6.580
52
6.350
53
6.530
54
6.530
55
1,193,154
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1758.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.290', '1.300', '1.280', '1.290', '1.290', '604,000']
1
1.290
2
1.300
3
1.280
4
1.290
5
1.290
6
604,000
7
Apr 10, 2019
['2019-04-10', '1.250', '1.300', '1.250', '1.300', '1.300', '534,000']
8
1.250
9
1.300
10
1.250
11
1.300
12
1.300
13
534,000
14
Apr 09, 2019
['2019-04-09', '1.280', '1.280', '1.280', '1.280', '1.280', '-']
15
1.280
16
1.280
17
1.280
18
1.280
19
1.280
20
-
21
Apr 08, 2019
['2019-04-08', '1.320', '1.350', '1.300', '1.320', '1.320', '724,000']
22
1.320
23
1.350
24
1.300
25
1.320
26
1.320
27
724,000
28
Apr 04, 2019
['2019-04-04', '1.320', '1.360', '1.200', '1.320', '1.320', '1,344,000']
29
1.320
30
1.360
31
1.200
32
1.320
33
1.320
34
1,344,000
35
Apr 03, 2019
['2019-04-03', '1.370', '1.390', '1.300', '1.340', '1.340', '564,000']
36
1.370
37
1.390
38
1.300
39
1.340
40
1.340
41
564,000
42
Apr 02, 2019
['2019-04-02', '1.340', '1.380', '1.300', '1.350', '1.350', '1,060,000']
43
1.340
44
1.380
45
1.300
46
1.350
47
1.350
48
1,060,000
49
Apr 01, 2019
['2019-04-01', '1.290', '1.370', '1.290', '1.360', '1.360', '1,056,000']
50
1.290
51
1.370
52
1.290
53
1.360
54
1.360
55
1,056,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2048.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '11.360', '11.360', '10.940', '11.000', '11.000', '813,300']
1
11.360
2
11.360
3
10.940
4
11.000
5
11.000
6
813,300
7
Apr 10, 2019
['2019-04-10', '11.000', '11.500', '10.920', '11.080', '11.080', '2,681,100']
8
11.000
9
11.500
10
10.920
11
11.080
12
11.080
13
2,681,100
14
Apr 09, 2019
['2019-04-09', '11.360', '11.360', '11.020', '11.080', '11.080', '437,500']
15
11.360
16
11.360
17
11.020
18
11.080
19
11.080
20
437,500
21
Apr 08, 2019
['2019-04-08', '11.500', '11.620', '11.120', '11.340', '11.340', '694,200']
22
11.500
23
11.620
24
11.120
25
11.340
26
11.340
27
694,200
28
Apr 04, 2019
['2019-04-04', '12.000', '12.000', '11.500', '11.620', '11.620', '833,200']
29
12.000
30
12.000
31
11.500
32
11.620
33
11.620
34
833,200
35
Apr 03, 2019
['2019-04-03', '12.100', '12.120', '11.800', '11.980', '11.980', '1,010,600']
36
12.100
37
12.120
38
11.800
39
11.980
40
11.980
41
1,010,600
42
Apr 02, 2019
['2019-04-02', '12.300', '12.300', '11.880', '11.940', '11.940', '1,122,500']
43
12.300
44
12.300
45
11.880
46
11.940
47
11.940
48
1,122,500
49
Apr 01, 2019
['2019-04-01', '12.360', '12.380', '12.020', '12.300', '12.300', '2,862,400']
50
12.360
51
12.380
52
12.020
53
12.300
54
12.300
55
2,862,400
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8512.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.100', '0.102', '0.100', '0.100', '0.100', '80,000']
1
0.100
2
0.102
3
0.100
4
0.100
5
0.100
6
80,000
7
Apr 10, 2019
['2019-04-10', '0.103', '0.105', '0.101', '0.101', '0.101', '4,420,000']
8
0.103
9
0.105
10
0.101
11
0.101
12
0.101
13
4,420,000
14
Apr 09, 2019
['2019-04-09', '0.099', '0.104', '0.099', '0.100', '0.100', '390,000']
15
0.099
16
0.104
17
0.099
18
0.100
19
0.100
20
390,000
21
Apr 08, 2019
['2019-04-08', '0.103', '0.105', '0.099', '0.104', '0.104', '590,000']
22
0.103
23
0.105
24
0.099
25
0.104
26
0.104
27
590,000
28
Apr 04, 2019
['2019-04-04', '0.102', '0.118', '0.100', '0.103', '0.103', '2,040,000']
29
0.102
30
0.118
31
0.100
32
0.103
33
0.103
34
2,040,000
35
Apr 03, 2019
['2019-04-03', '0.100', '0.103', '0.100', '0.103', '0.103', '1,250,000']
36
0.100
37
0.103
38
0.100
39
0.103
40
0.103
41
1,250,000
42
Apr 02, 2019
['2019-04-02', '0.102', '0.104', '0.100', '0.104', '0.104', '530,000']
43
0.102
44
0.104
45
0.100
46
0.104
47
0.104
48
530,000
49
Apr 01, 2019
['2019-04-01', '0.100', '0.100', '0.100', '0.102', '0.102', '520,000']
50
0.100
51
0.100
52
0.100
53
0.102
54
0.102
55
520,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1576.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.900', '1.900', '1.890', '1.890', '1.890', '37,000']
1
1.900
2
1.900
3
1.890
4
1.890
5
1.890
6
37,000
7
Apr 10, 2019
['2019-04-10', '1.920', '1.940', '1.910', '1.910', '1.910', '226,000']
8
1.920
9
1.940
10
1.910
11
1.910
12
1.910
13
226,000
14
Apr 09, 2019
['2019-04-09', '1.900', '1.920', '1.900', '1.900', '1.900', '81,000']
15
1.900
16
1.920
17
1.900
18
1.900
19
1.900
20
81,000
21
Apr 08, 2019
['2019-04-08', '1.900', '1.930', '1.900', '1.900', '1.900', '340,000']
22
1.900
23
1.930
24
1.900
25
1.900
26
1.900
27
340,000
28
Apr 04, 2019
['2019-04-04', '1.910', '1.910', '1.850', '1.890', '1.890', '265,000']
29
1.910
30
1.910
31
1.850
32
1.890
33
1.890
34
265,000
35
Apr 03, 2019
['2019-04-03', '1.920', '1.920', '1.850', '1.850', '1.850', '695,000']
36
1.920
37
1.920
38
1.850
39
1.850
40
1.850
41
695,000
42
Apr 02, 2019
['2019-04-02', '1.910', '1.910', '1.870', '1.880', '1.880', '274,000']
43
1.910
44
1.910
45
1.870
46
1.880
47
1.880
48
274,000
49
Apr 01, 2019
['2019-04-01', '1.900', '1.900', '1.890', '1.900', '1.900', '234,000']
50
1.900
51
1.900
52
1.890
53
1.900
54
1.900
55
234,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8525.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.540', '0.540', '0.540', '0.540', '0.540', '182,000']
1
0.540
2
0.540
3
0.540
4
0.540
5
0.540
6
182,000
7
Apr 10, 2019
['2019-04-10', '0.560', '0.560', '0.530', '0.550', '0.550', '314,000']
8
0.560
9
0.560
10
0.530
11
0.550
12
0.550
13
314,000
14
Apr 09, 2019
['2019-04-09', '0.580', '0.580', '0.550', '0.580', '0.580', '446,000']
15
0.580
16
0.580
17
0.550
18
0.580
19
0.580
20
446,000
21
Apr 08, 2019
['2019-04-08', '0.580', '0.580', '0.580', '0.580', '0.580', '-']
22
0.580
23
0.580
24
0.580
25
0.580
26
0.580
27
-
28
Apr 04, 2019
['2019-04-04', '0.580', '0.580', '0.580', '0.580', '0.580', '-']
29
0.580
30
0.580
31
0.580
32
0.580
33
0.580
34
-
35
Apr 03, 2019
['2019-04-03', '0.560', '0.600', '0.560', '0.580', '0.580', '100,000']
36
0.560
37
0.600
38
0.560
39
0.580
40
0.580
41
100,000
42
Apr 02, 2019
['2019-04-02', '0.600', '0.600', '0.580', '0.580', '0.580', '126,000']
43
0.600
44
0.600
45
0.580
46
0.580
47
0.580
48
126,000
49
Apr 01, 2019
['2019-04-01', '0.590', '0.600', '0.590', '0.600', '0.600', '4,000']
50
0.590
51
0.600
52
0.590
53
0.600
54
0.600
55
4,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8547.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.207', '0.210', '0.204', '0.207', '0.207', '640,000']
1
0.207
2
0.210
3
0.204
4
0.207
5
0.207
6
640,000
7
Apr 10, 2019
['2019-04-10', '0.207', '0.215', '0.203', '0.207', '0.207', '1,170,000']
8
0.207
9
0.215
10
0.203
11
0.207
12
0.207
13
1,170,000
14
Apr 09, 2019
['2019-04-09', '0.207', '0.218', '0.207', '0.217', '0.217', '220,000']
15
0.207
16
0.218
17
0.207
18
0.217
19
0.217
20
220,000
21
Apr 08, 2019
['2019-04-08', '0.235', '0.235', '0.209', '0.219', '0.219', '2,520,000']
22
0.235
23
0.235
24
0.209
25
0.219
26
0.219
27
2,520,000
28
Apr 04, 2019
['2019-04-04', '0.224', '0.228', '0.222', '0.227', '0.227', '620,000']
29
0.224
30
0.228
31
0.222
32
0.227
33
0.227
34
620,000
35
Apr 03, 2019
['2019-04-03', '0.215', '0.229', '0.215', '0.229', '0.229', '3,170,000']
36
0.215
37
0.229
38
0.215
39
0.229
40
0.229
41
3,170,000
42
Apr 02, 2019
['2019-04-02', '0.226', '0.226', '0.222', '0.222', '0.222', '400,000']
43
0.226
44
0.226
45
0.222
46
0.222
47
0.222
48
400,000
49
Apr 01, 2019
['2019-04-01', '0.230', '0.232', '0.221', '0.224', '0.224', '780,000']
50
0.230
51
0.232
52
0.221
53
0.224
54
0.224
55
780,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0797.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.390', '1.400', '1.370', '1.400', '1.400', '142,000']
1
1.390
2
1.400
3
1.370
4
1.400
5
1.400
6
142,000
7
Apr 10, 2019
['2019-04-10', '1.400', '1.400', '1.400', '1.400', '1.400', '-']
8
1.400
9
1.400
10
1.400
11
1.400
12
1.400
13
-
14
Apr 09, 2019
['2019-04-09', '1.430', '1.440', '1.400', '1.410', '1.410', '1,188,000']
15
1.430
16
1.440
17
1.400
18
1.410
19
1.410
20
1,188,000
21
Apr 08, 2019
['2019-04-08', '1.430', '1.440', '1.400', '1.430', '1.430', '146,000']
22
1.430
23
1.440
24
1.400
25
1.430
26
1.430
27
146,000
28
Apr 04, 2019
['2019-04-04', '1.440', '1.440', '1.400', '1.440', '1.440', '702,000']
29
1.440
30
1.440
31
1.400
32
1.440
33
1.440
34
702,000
35
Apr 03, 2019
['2019-04-03', '1.410', '1.450', '1.380', '1.440', '1.440', '210,000']
36
1.410
37
1.450
38
1.380
39
1.440
40
1.440
41
210,000
42
Apr 02, 2019
['2019-04-02', '1.440', '1.480', '1.380', '1.400', '1.400', '454,000']
43
1.440
44
1.480
45
1.380
46
1.400
47
1.400
48
454,000
49
Apr 01, 2019
['2019-04-01', '1.420', '1.450', '1.390', '1.450', '1.450', '600,000']
50
1.420
51
1.450
52
1.390
53
1.450
54
1.450
55
600,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3302.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.830', '0.870', '0.810', '0.860', '0.860', '584,000']
1
0.830
2
0.870
3
0.810
4
0.860
5
0.860
6
584,000
7
Apr 10, 2019
['2019-04-10', '0.830', '0.840', '0.830', '0.840', '0.840', '602,000']
8
0.830
9
0.840
10
0.830
11
0.840
12
0.840
13
602,000
14
Apr 09, 2019
['2019-04-09', '0.850', '0.870', '0.830', '0.870', '0.870', '618,000']
15
0.850
16
0.870
17
0.830
18
0.870
19
0.870
20
618,000
21
Apr 08, 2019
['2019-04-08', '0.850', '0.860', '0.820', '0.860', '0.860', '568,000']
22
0.850
23
0.860
24
0.820
25
0.860
26
0.860
27
568,000
28
Apr 04, 2019
['2019-04-04', '0.860', '0.860', '0.850', '0.860', '0.860', '604,000']
29
0.860
30
0.860
31
0.850
32
0.860
33
0.860
34
604,000
35
Apr 03, 2019
['2019-04-03', '0.830', '0.870', '0.830', '0.870', '0.870', '634,000']
36
0.830
37
0.870
38
0.830
39
0.870
40
0.870
41
634,000
42
Apr 02, 2019
['2019-04-02', '0.820', '0.840', '0.820', '0.840', '0.840', '604,000']
43
0.820
44
0.840
45
0.820
46
0.840
47
0.840
48
604,000
49
Apr 01, 2019
['2019-04-01', '0.800', '0.830', '0.800', '0.830', '0.830', '4,864,000']
50
0.800
51
0.830
52
0.800
53
0.830
54
0.830
55
4,864,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8540.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.270', '1.270', '1.270', '1.270', '1.270', '-']
1
1.270
2
1.270
3
1.270
4
1.270
5
1.270
6
-
7
Apr 10, 2019
['2019-04-10', '1.260', '1.260', '1.260', '1.260', '1.260', '-']
8
1.260
9
1.260
10
1.260
11
1.260
12
1.260
13
-
14
Apr 09, 2019
['2019-04-09', '1.300', '1.300', '1.280', '1.300', '1.300', '90,000']
15
1.300
16
1.300
17
1.280
18
1.300
19
1.300
20
90,000
21
Apr 08, 2019
['2019-04-08', '1.320', '1.340', '1.320', '1.340', '1.340', '54,000']
22
1.320
23
1.340
24
1.320
25
1.340
26
1.340
27
54,000
28
Apr 04, 2019
['2019-04-04', '1.340', '1.340', '1.340', '1.340', '1.340', '-']
29
1.340
30
1.340
31
1.340
32
1.340
33
1.340
34
-
35
Apr 03, 2019
['2019-04-03', '1.360', '1.360', '1.360', '1.360', '1.360', '-']
36
1.360
37
1.360
38
1.360
39
1.360
40
1.360
41
-
42
Apr 02, 2019
['2019-04-02', '1.360', '1.360', '1.360', '1.360', '1.360', '-']
43
1.360
44
1.360
45
1.360
46
1.360
47
1.360
48
-
49
Apr 01, 2019
['2019-04-01', '1.370', '1.370', '1.370', '1.370', '1.370', '-']
50
1.370
51
1.370
52
1.370
53
1.370
54
1.370
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8606.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.245', '0.246', '0.239', '0.239', '0.239', '210,000']
1
0.245
2
0.246
3
0.239
4
0.239
5
0.239
6
210,000
7
Apr 10, 2019
['2019-04-10', '0.238', '0.245', '0.237', '0.245', '0.245', '670,000']
8
0.238
9
0.245
10
0.237
11
0.245
12
0.245
13
670,000
14
Apr 09, 2019
['2019-04-09', '0.239', '0.265', '0.239', '0.240', '0.240', '930,000']
15
0.239
16
0.265
17
0.239
18
0.240
19
0.240
20
930,000
21
Apr 08, 2019
['2019-04-08', '0.280', '0.285', '0.240', '0.240', '0.240', '1,170,000']
22
0.280
23
0.285
24
0.240
25
0.240
26
0.240
27
1,170,000
28
Apr 04, 2019
['2019-04-04', '0.260', '0.260', '0.245', '0.255', '0.255', '530,000']
29
0.260
30
0.260
31
0.245
32
0.255
33
0.255
34
530,000
35
Apr 03, 2019
['2019-04-03', '0.250', '0.255', '0.250', '0.255', '0.255', '130,000']
36
0.250
37
0.255
38
0.250
39
0.255
40
0.255
41
130,000
42
Apr 02, 2019
['2019-04-02', '0.255', '0.255', '0.255', '0.255', '0.255', '210,000']
43
0.255
44
0.255
45
0.255
46
0.255
47
0.255
48
210,000
49
Apr 01, 2019
['2019-04-01', '0.255', '0.255', '0.255', '0.255', '0.255', '-']
50
0.255
51
0.255
52
0.255
53
0.255
54
0.255
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1968.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.530', '0.540', '0.530', '0.540', '0.540', '1,620,000']
1
0.530
2
0.540
3
0.530
4
0.540
5
0.540
6
1,620,000
7
Apr 10, 2019
['2019-04-10', '0.540', '0.550', '0.540', '0.540', '0.540', '288,000']
8
0.540
9
0.550
10
0.540
11
0.540
12
0.540
13
288,000
14
Apr 09, 2019
['2019-04-09', '0.550', '0.550', '0.530', '0.540', '0.540', '3,380,000']
15
0.550
16
0.550
17
0.530
18
0.540
19
0.540
20
3,380,000
21
Apr 08, 2019
['2019-04-08', '0.560', '0.560', '0.540', '0.550', '0.550', '416,000']
22
0.560
23
0.560
24
0.540
25
0.550
26
0.550
27
416,000
28
Apr 04, 2019
['2019-04-04', '0.550', '0.560', '0.540', '0.550', '0.550', '200,000']
29
0.550
30
0.560
31
0.540
32
0.550
33
0.550
34
200,000
35
Apr 03, 2019
['2019-04-03', '0.550', '0.560', '0.530', '0.540', '0.540', '804,000']
36
0.550
37
0.560
38
0.530
39
0.540
40
0.540
41
804,000
42
Apr 02, 2019
['2019-04-02', '0.550', '0.550', '0.540', '0.550', '0.550', '280,000']
43
0.550
44
0.550
45
0.540
46
0.550
47
0.550
48
280,000
49
Apr 01, 2019
['2019-04-01', '0.560', '0.580', '0.540', '0.550', '0.550', '1,704,000']
50
0.560
51
0.580
52
0.540
53
0.550
54
0.550
55
1,704,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1715.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.405', '0.420', '0.405', '0.415', '0.415', '3,010,000']
1
0.405
2
0.420
3
0.405
4
0.415
5
0.415
6
3,010,000
7
Apr 10, 2019
['2019-04-10', '0.415', '0.415', '0.400', '0.410', '0.410', '2,550,000']
8
0.415
9
0.415
10
0.400
11
0.410
12
0.410
13
2,550,000
14
Apr 09, 2019
['2019-04-09', '0.430', '0.430', '0.405', '0.410', '0.410', '11,600,000']
15
0.430
16
0.430
17
0.405
18
0.410
19
0.410
20
11,600,000
21
Apr 08, 2019
['2019-04-08', '0.425', '0.480', '0.400', '0.435', '0.435', '44,160,000']
22
0.425
23
0.480
24
0.400
25
0.435
26
0.435
27
44,160,000
28
Apr 04, 2019
['2019-04-04', '0.410', '0.415', '0.395', '0.410', '0.410', '24,460,000']
29
0.410
30
0.415
31
0.395
32
0.410
33
0.410
34
24,460,000
35
Apr 03, 2019
['2019-04-03', '0.395', '0.410', '0.395', '0.405', '0.405', '19,270,000']
36
0.395
37
0.410
38
0.395
39
0.405
40
0.405
41
19,270,000
42
Apr 02, 2019
['2019-04-02', '0.400', '0.405', '0.395', '0.395', '0.395', '350,000']
43
0.400
44
0.405
45
0.395
46
0.395
47
0.395
48
350,000
49
Apr 01, 2019
['2019-04-01', '0.385', '0.425', '0.385', '0.400', '0.400', '1,460,000']
50
0.385
51
0.425
52
0.385
53
0.400
54
0.400
55
1,460,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1721.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.640', '0.640', '0.620', '0.630', '0.630', '375,000']
1
0.640
2
0.640
3
0.620
4
0.630
5
0.630
6
375,000
7
Apr 10, 2019
['2019-04-10', '0.620', '0.640', '0.610', '0.640', '0.640', '840,000']
8
0.620
9
0.640
10
0.610
11
0.640
12
0.640
13
840,000
14
Apr 09, 2019
['2019-04-09', '0.620', '0.630', '0.620', '0.630', '0.630', '285,000']
15
0.620
16
0.630
17
0.620
18
0.630
19
0.630
20
285,000
21
Apr 08, 2019
['2019-04-08', '0.640', '0.640', '0.610', '0.640', '0.640', '765,000']
22
0.640
23
0.640
24
0.610
25
0.640
26
0.640
27
765,000
28
Apr 04, 2019
['2019-04-04', '0.620', '0.650', '0.600', '0.640', '0.640', '2,415,000']
29
0.620
30
0.650
31
0.600
32
0.640
33
0.640
34
2,415,000
35
Apr 03, 2019
['2019-04-03', '0.610', '0.630', '0.600', '0.610', '0.610', '1,285,000']
36
0.610
37
0.630
38
0.600
39
0.610
40
0.610
41
1,285,000
42
Apr 02, 2019
['2019-04-02', '0.650', '0.700', '0.600', '0.600', '0.600', '159,240,000']
43
0.650
44
0.700
45
0.600
46
0.600
47
0.600
48
159,240,000
49
Apr 01, 2019
['2019-04-01', '0.570', '0.580', '0.570', '0.570', '0.570', '65,000']
50
0.570
51
0.580
52
0.570
53
0.570
54
0.570
55
65,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2051.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '5.680', '5.690', '5.230', '5.380', '5.380', '1,896,000']
1
5.680
2
5.690
3
5.230
4
5.380
5
5.380
6
1,896,000
7
Apr 10, 2019
['2019-04-10', '5.780', '5.780', '5.550', '5.590', '5.590', '1,541,500']
8
5.780
9
5.780
10
5.550
11
5.590
12
5.590
13
1,541,500
14
Apr 09, 2019
['2019-04-09', '5.950', '5.950', '5.680', '5.790', '5.790', '1,468,500']
15
5.950
16
5.950
17
5.680
18
5.790
19
5.790
20
1,468,500
21
Apr 08, 2019
['2019-04-08', '5.600', '5.780', '5.600', '5.700', '5.700', '1,060,500']
22
5.600
23
5.780
24
5.600
25
5.700
26
5.700
27
1,060,500
28
Apr 04, 2019
['2019-04-04', '5.750', '5.850', '5.660', '5.710', '5.710', '1,040,500']
29
5.750
30
5.850
31
5.660
32
5.710
33
5.710
34
1,040,500
35
Apr 03, 2019
['2019-04-03', '5.700', '5.880', '5.700', '5.780', '5.780', '1,242,000']
36
5.700
37
5.880
38
5.700
39
5.780
40
5.780
41
1,242,000
42
Apr 02, 2019
['2019-04-02', '5.700', '5.990', '5.630', '5.680', '5.680', '1,402,500']
43
5.700
44
5.990
45
5.630
46
5.680
47
5.680
48
1,402,500
49
Apr 01, 2019
['2019-04-01', '5.660', '5.700', '5.530', '5.590', '5.590', '1,223,000']
50
5.660
51
5.700
52
5.530
53
5.590
54
5.590
55
1,223,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1775.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.730', '0.730', '0.730', '0.730', '0.730', '-']
1
0.730
2
0.730
3
0.730
4
0.730
5
0.730
6
-
7
Apr 10, 2019
['2019-04-10', '0.710', '0.740', '0.710', '0.710', '0.710', '212,000']
8
0.710
9
0.740
10
0.710
11
0.710
12
0.710
13
212,000
14
Apr 09, 2019
['2019-04-09', '0.740', '0.750', '0.720', '0.740', '0.740', '224,000']
15
0.740
16
0.750
17
0.720
18
0.740
19
0.740
20
224,000
21
Apr 08, 2019
['2019-04-08', '0.700', '0.710', '0.700', '0.710', '0.710', '164,000']
22
0.700
23
0.710
24
0.700
25
0.710
26
0.710
27
164,000
28
Apr 04, 2019
['2019-04-04', '0.730', '0.780', '0.710', '0.720', '0.720', '324,000']
29
0.730
30
0.780
31
0.710
32
0.720
33
0.720
34
324,000
35
Apr 03, 2019
['2019-04-03', '0.690', '0.720', '0.680', '0.720', '0.720', '760,000']
36
0.690
37
0.720
38
0.680
39
0.720
40
0.720
41
760,000
42
Apr 02, 2019
['2019-04-02', '0.740', '0.740', '0.670', '0.680', '0.680', '1,968,000']
43
0.740
44
0.740
45
0.670
46
0.680
47
0.680
48
1,968,000
49
Apr 01, 2019
['2019-04-01', '0.740', '0.750', '0.700', '0.700', '0.700', '996,000']
50
0.740
51
0.750
52
0.700
53
0.700
54
0.700
55
996,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1731.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.130', '1.130', '1.090', '1.100', '1.100', '944,000']
1
1.130
2
1.130
3
1.090
4
1.100
5
1.100
6
944,000
7
Apr 10, 2019
['2019-04-10', '1.120', '1.140', '1.080', '1.090', '1.090', '1,076,000']
8
1.120
9
1.140
10
1.080
11
1.090
12
1.090
13
1,076,000
14
Apr 09, 2019
['2019-04-09', '1.140', '1.160', '1.130', '1.130', '1.130', '748,000']
15
1.140
16
1.160
17
1.130
18
1.130
19
1.130
20
748,000
21
Apr 08, 2019
['2019-04-08', '1.150', '1.170', '1.130', '1.130', '1.130', '916,000']
22
1.150
23
1.170
24
1.130
25
1.130
26
1.130
27
916,000
28
Apr 04, 2019
['2019-04-04', '1.160', '1.170', '1.150', '1.150', '1.150', '768,000']
29
1.160
30
1.170
31
1.150
32
1.150
33
1.150
34
768,000
35
Apr 03, 2019
['2019-04-03', '1.160', '1.160', '1.130', '1.150', '1.150', '1,212,000']
36
1.160
37
1.160
38
1.130
39
1.150
40
1.150
41
1,212,000
42
Apr 02, 2019
['2019-04-02', '1.180', '1.180', '1.170', '1.170', '1.170', '532,000']
43
1.180
44
1.180
45
1.170
46
1.170
47
1.170
48
532,000
49
Apr 01, 2019
['2019-04-01', '1.190', '1.190', '1.150', '1.170', '1.170', '948,000']
50
1.190
51
1.190
52
1.150
53
1.170
54
1.170
55
948,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6860.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.680', '1.730', '1.660', '1.660', '1.660', '603,000']
1
1.680
2
1.730
3
1.660
4
1.660
5
1.660
6
603,000
7
Apr 10, 2019
['2019-04-10', '1.670', '1.700', '1.640', '1.640', '1.640', '12,000']
8
1.670
9
1.700
10
1.640
11
1.640
12
1.640
13
12,000
14
Apr 09, 2019
['2019-04-09', '1.670', '1.710', '1.670', '1.710', '1.710', '52,000']
15
1.670
16
1.710
17
1.670
18
1.710
19
1.710
20
52,000
21
Apr 08, 2019
['2019-04-08', '1.710', '1.730', '1.660', '1.730', '1.730', '32,000']
22
1.710
23
1.730
24
1.660
25
1.730
26
1.730
27
32,000
28
Apr 04, 2019
['2019-04-04', '1.720', '1.750', '1.720', '1.750', '1.750', '154,000']
29
1.720
30
1.750
31
1.720
32
1.750
33
1.750
34
154,000
35
Apr 03, 2019
['2019-04-03', '1.710', '1.730', '1.700', '1.730', '1.730', '583,000']
36
1.710
37
1.730
38
1.700
39
1.730
40
1.730
41
583,000
42
Apr 02, 2019
['2019-04-02', '1.720', '1.720', '1.680', '1.710', '1.710', '89,000']
43
1.720
44
1.720
45
1.680
46
1.710
47
1.710
48
89,000
49
Apr 01, 2019
['2019-04-01', '1.670', '1.710', '1.650', '1.710', '1.710', '2,093,000']
50
1.670
51
1.710
52
1.650
53
1.710
54
1.710
55
2,093,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3700.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.110', '2.130', '1.980', '2.000', '2.000', '20,555,191']
1
2.110
2
2.130
3
1.980
4
2.000
5
2.000
6
20,555,191
7
Apr 10, 2019
['2019-04-10', '2.210', '2.210', '2.100', '2.140', '2.140', '15,957,000']
8
2.210
9
2.210
10
2.100
11
2.140
12
2.140
13
15,957,000
14
Apr 09, 2019
['2019-04-09', '2.170', '2.280', '2.130', '2.230', '2.230', '13,618,700']
15
2.170
16
2.280
17
2.130
18
2.230
19
2.230
20
13,618,700
21
Apr 08, 2019
['2019-04-08', '2.280', '2.280', '2.160', '2.180', '2.180', '13,420,869']
22
2.280
23
2.280
24
2.160
25
2.180
26
2.180
27
13,420,869
28
Apr 04, 2019
['2019-04-04', '2.320', '2.350', '2.230', '2.260', '2.260', '15,500,000']
29
2.320
30
2.350
31
2.230
32
2.260
33
2.260
34
15,500,000
35
Apr 03, 2019
['2019-04-03', '2.280', '2.370', '2.220', '2.320', '2.320', '19,554,000']
36
2.280
37
2.370
38
2.220
39
2.320
40
2.320
41
19,554,000
42
Apr 02, 2019
['2019-04-02', '2.310', '2.450', '2.220', '2.300', '2.300', '41,350,652']
43
2.310
44
2.450
45
2.220
46
2.300
47
2.300
48
41,350,652
49
Apr 01, 2019
['2019-04-01', '1.950', '2.330', '1.930', '2.310', '2.310', '98,799,712']
50
1.950
51
2.330
52
1.930
53
2.310
54
2.310
55
98,799,712
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8219.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.119', '0.119', '0.106', '0.114', '0.114', '1,890,000']
1
0.119
2
0.119
3
0.106
4
0.114
5
0.114
6
1,890,000
7
Apr 10, 2019
['2019-04-10', '0.101', '0.137', '0.101', '0.120', '0.120', '830,000']
8
0.101
9
0.137
10
0.101
11
0.120
12
0.120
13
830,000
14
Apr 09, 2019
['2019-04-09', '0.127', '0.130', '0.126', '0.128', '0.128', '420,000']
15
0.127
16
0.130
17
0.126
18
0.128
19
0.128
20
420,000
21
Apr 08, 2019
['2019-04-08', '0.131', '0.131', '0.128', '0.128', '0.128', '110,000']
22
0.131
23
0.131
24
0.128
25
0.128
26
0.128
27
110,000
28
Apr 04, 2019
['2019-04-04', '0.127', '0.127', '0.120', '0.127', '0.127', '1,550,000']
29
0.127
30
0.127
31
0.120
32
0.127
33
0.127
34
1,550,000
35
Apr 03, 2019
['2019-04-03', '0.142', '0.142', '0.123', '0.131', '0.131', '2,310,000']
36
0.142
37
0.142
38
0.123
39
0.131
40
0.131
41
2,310,000
42
Apr 02, 2019
['2019-04-02', '0.144', '0.144', '0.144', '0.144', '0.144', '-']
43
0.144
44
0.144
45
0.144
46
0.144
47
0.144
48
-
49
Apr 01, 2019
['2019-04-01', '0.142', '0.154', '0.138', '0.139', '0.139', '1,570,000']
50
0.142
51
0.154
52
0.138
53
0.139
54
0.139
55
1,570,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8140.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.980', '0.990', '0.930', '0.990', '0.990', '1,310,000']
1
0.980
2
0.990
3
0.930
4
0.990
5
0.990
6
1,310,000
7
Apr 10, 2019
['2019-04-10', '1.040', '1.040', '0.980', '1.010', '1.010', '3,770,000']
8
1.040
9
1.040
10
0.980
11
1.010
12
1.010
13
3,770,000
14
Apr 09, 2019
['2019-04-09', '1.020', '1.020', '1.000', '1.000', '1.000', '130,000']
15
1.020
16
1.020
17
1.000
18
1.000
19
1.000
20
130,000
21
Apr 08, 2019
['2019-04-08', '0.990', '1.070', '0.990', '1.020', '1.020', '2,230,000']
22
0.990
23
1.070
24
0.990
25
1.020
26
1.020
27
2,230,000
28
Apr 04, 2019
['2019-04-04', '1.030', '1.030', '0.960', '0.970', '0.970', '240,000']
29
1.030
30
1.030
31
0.960
32
0.970
33
0.970
34
240,000
35
Apr 03, 2019
['2019-04-03', '1.000', '1.040', '1.000', '1.010', '1.010', '8,530,000']
36
1.000
37
1.040
38
1.000
39
1.010
40
1.010
41
8,530,000
42
Apr 02, 2019
['2019-04-02', '1.080', '1.160', '1.020', '1.050', '1.050', '1,170,000']
43
1.080
44
1.160
45
1.020
46
1.050
47
1.050
48
1,170,000
49
Apr 01, 2019
['2019-04-01', '1.000', '1.060', '1.000', '1.020', '1.020', '320,000']
50
1.000
51
1.060
52
1.000
53
1.020
54
1.020
55
320,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1760.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.710', '3.720', '3.590', '3.600', '3.600', '239,000']
1
3.710
2
3.720
3
3.590
4
3.600
5
3.600
6
239,000
7
Apr 10, 2019
['2019-04-10', '3.670', '3.720', '3.610', '3.650', '3.650', '410,000']
8
3.670
9
3.720
10
3.610
11
3.650
12
3.650
13
410,000
14
Apr 09, 2019
['2019-04-09', '3.630', '3.680', '3.600', '3.600', '3.600', '671,000']
15
3.630
16
3.680
17
3.600
18
3.600
19
3.600
20
671,000
21
Apr 08, 2019
['2019-04-08', '3.460', '3.620', '3.400', '3.600', '3.600', '453,000']
22
3.460
23
3.620
24
3.400
25
3.600
26
3.600
27
453,000
28
Apr 04, 2019
['2019-04-04', '3.570', '3.620', '3.570', '3.610', '3.610', '30,000']
29
3.570
30
3.620
31
3.570
32
3.610
33
3.610
34
30,000
35
Apr 03, 2019
['2019-04-03', '3.470', '3.620', '3.470', '3.580', '3.580', '22,000']
36
3.470
37
3.620
38
3.470
39
3.580
40
3.580
41
22,000
42
Apr 02, 2019
['2019-04-02', '3.490', '3.640', '3.490', '3.640', '3.640', '34,000']
43
3.490
44
3.640
45
3.490
46
3.640
47
3.640
48
34,000
49
Apr 01, 2019
['2019-04-01', '3.400', '3.490', '3.390', '3.490', '3.490', '398,000']
50
3.400
51
3.490
52
3.390
53
3.490
54
3.490
55
398,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1739.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.560', '3.560', '3.340', '3.400', '3.400', '626,500']
1
3.560
2
3.560
3
3.340
4
3.400
5
3.400
6
626,500
7
Apr 10, 2019
['2019-04-10', '3.490', '3.530', '3.460', '3.490', '3.490', '601,000']
8
3.490
9
3.530
10
3.460
11
3.490
12
3.490
13
601,000
14
Apr 09, 2019
['2019-04-09', '3.540', '3.550', '3.460', '3.510', '3.510', '577,500']
15
3.540
16
3.550
17
3.460
18
3.510
19
3.510
20
577,500
21
Apr 08, 2019
['2019-04-08', '3.500', '3.570', '3.470', '3.520', '3.520', '572,500']
22
3.500
23
3.570
24
3.470
25
3.520
26
3.520
27
572,500
28
Apr 04, 2019
['2019-04-04', '3.450', '3.500', '3.390', '3.490', '3.490', '581,000']
29
3.450
30
3.500
31
3.390
32
3.490
33
3.490
34
581,000
35
Apr 03, 2019
['2019-04-03', '3.580', '3.580', '3.410', '3.450', '3.450', '586,000']
36
3.580
37
3.580
38
3.410
39
3.450
40
3.450
41
586,000
42
Apr 02, 2019
['2019-04-02', '3.470', '3.520', '3.200', '3.500', '3.500', '1,135,000']
43
3.470
44
3.520
45
3.200
46
3.500
47
3.500
48
1,135,000
49
Apr 01, 2019
['2019-04-01', '3.750', '3.750', '3.490', '3.550', '3.550', '2,515,500']
50
3.750
51
3.750
52
3.490
53
3.550
54
3.550
55
2,515,500
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1996.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.810', '2.810', '2.760', '2.800', '2.800', '2,128,000']
1
2.810
2
2.810
3
2.760
4
2.800
5
2.800
6
2,128,000
7
Apr 10, 2019
['2019-04-10', '2.790', '2.810', '2.760', '2.800', '2.800', '2,866,000']
8
2.790
9
2.810
10
2.760
11
2.800
12
2.800
13
2,866,000
14
Apr 09, 2019
['2019-04-09', '2.810', '2.820', '2.740', '2.800', '2.800', '2,410,000']
15
2.810
16
2.820
17
2.740
18
2.800
19
2.800
20
2,410,000
21
Apr 08, 2019
['2019-04-08', '2.810', '2.830', '2.750', '2.800', '2.800', '1,799,000']
22
2.810
23
2.830
24
2.750
25
2.800
26
2.800
27
1,799,000
28
Apr 04, 2019
['2019-04-04', '2.810', '2.830', '2.750', '2.780', '2.780', '2,082,000']
29
2.810
30
2.830
31
2.750
32
2.780
33
2.780
34
2,082,000
35
Apr 03, 2019
['2019-04-03', '2.820', '2.860', '2.790', '2.790', '2.790', '2,429,000']
36
2.820
37
2.860
38
2.790
39
2.790
40
2.790
41
2,429,000
42
Apr 02, 2019
['2019-04-02', '2.730', '2.820', '2.730', '2.780', '2.780', '3,825,000']
43
2.730
44
2.820
45
2.730
46
2.780
47
2.780
48
3,825,000
49
Apr 01, 2019
['2019-04-01', '2.710', '2.740', '2.680', '2.720', '2.720', '2,832,000']
50
2.710
51
2.740
52
2.680
53
2.720
54
2.720
55
2,832,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1773.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.410', '2.500', '2.350', '2.380', '2.380', '2,630,700']
1
2.410
2
2.500
3
2.350
4
2.380
5
2.380
6
2,630,700
7
Apr 10, 2019
['2019-04-10', '2.390', '2.450', '2.350', '2.410', '2.410', '2,566,000']
8
2.390
9
2.450
10
2.350
11
2.410
12
2.410
13
2,566,000
14
Apr 09, 2019
['2019-04-09', '2.400', '2.420', '2.350', '2.390', '2.390', '3,633,000']
15
2.400
16
2.420
17
2.350
18
2.390
19
2.390
20
3,633,000
21
Apr 08, 2019
['2019-04-08', '2.450', '2.500', '2.380', '2.410', '2.410', '4,163,000']
22
2.450
23
2.500
24
2.380
25
2.410
26
2.410
27
4,163,000
28
Apr 04, 2019
['2019-04-04', '2.450', '2.510', '2.400', '2.460', '2.460', '5,840,000']
29
2.450
30
2.510
31
2.400
32
2.460
33
2.460
34
5,840,000
35
Apr 03, 2019
['2019-04-03', '2.360', '2.440', '2.320', '2.400', '2.400', '4,420,000']
36
2.360
37
2.440
38
2.320
39
2.400
40
2.400
41
4,420,000
42
Apr 02, 2019
['2019-04-02', '2.260', '2.350', '2.230', '2.280', '2.280', '2,608,000']
43
2.260
44
2.350
45
2.230
46
2.280
47
2.280
48
2,608,000
49
Apr 01, 2019
['2019-04-01', '2.290', '2.370', '2.220', '2.260', '2.260', '6,661,000']
50
2.290
51
2.370
52
2.220
53
2.260
54
2.260
55
6,661,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1746.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.390', '0.400', '0.390', '0.395', '0.395', '336,000']
1
0.390
2
0.400
3
0.390
4
0.395
5
0.395
6
336,000
7
Apr 10, 2019
['2019-04-10', '0.390', '0.400', '0.385', '0.390', '0.390', '684,000']
8
0.390
9
0.400
10
0.385
11
0.390
12
0.390
13
684,000
14
Apr 09, 2019
['2019-04-09', '0.395', '0.395', '0.390', '0.395', '0.395', '376,000']
15
0.395
16
0.395
17
0.390
18
0.395
19
0.395
20
376,000
21
Apr 08, 2019
['2019-04-08', '0.395', '0.400', '0.395', '0.395', '0.395', '260,000']
22
0.395
23
0.400
24
0.395
25
0.395
26
0.395
27
260,000
28
Apr 04, 2019
['2019-04-04', '0.395', '0.400', '0.385', '0.385', '0.385', '1,744,000']
29
0.395
30
0.400
31
0.385
32
0.385
33
0.385
34
1,744,000
35
Apr 03, 2019
['2019-04-03', '0.395', '0.405', '0.395', '0.400', '0.400', '3,860,000']
36
0.395
37
0.405
38
0.395
39
0.400
40
0.400
41
3,860,000
42
Apr 02, 2019
['2019-04-02', '0.385', '0.400', '0.380', '0.395', '0.395', '17,796,000']
43
0.385
44
0.400
45
0.380
46
0.395
47
0.395
48
17,796,000
49
Apr 01, 2019
['2019-04-01', '0.380', '0.395', '0.380', '0.380', '0.380', '20,024,000']
50
0.380
51
0.395
52
0.380
53
0.380
54
0.380
55
20,024,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1652.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '5.290', '5.510', '5.120', '5.310', '5.310', '83,000']
1
5.290
2
5.510
3
5.120
4
5.310
5
5.310
6
83,000
7
Apr 10, 2019
['2019-04-10', '5.110', '5.480', '5.050', '5.250', '5.250', '269,000']
8
5.110
9
5.480
10
5.050
11
5.250
12
5.250
13
269,000
14
Apr 09, 2019
['2019-04-09', '4.280', '5.400', '4.280', '5.040', '5.040', '3,412,850']
15
4.280
16
5.400
17
4.280
18
5.040
19
5.040
20
3,412,850
21
Apr 08, 2019
['2019-04-08', '4.270', '4.500', '4.260', '4.390', '4.390', '74,000']
22
4.270
23
4.500
24
4.260
25
4.390
26
4.390
27
74,000
28
Apr 04, 2019
['2019-04-04', '4.600', '4.690', '4.560', '4.560', '4.560', '37,000']
29
4.600
30
4.690
31
4.560
32
4.560
33
4.560
34
37,000
35
Apr 03, 2019
['2019-04-03', '4.500', '4.700', '4.230', '4.600', '4.600', '159,000']
36
4.500
37
4.700
38
4.230
39
4.600
40
4.600
41
159,000
42
Apr 02, 2019
['2019-04-02', '4.100', '4.650', '4.100', '4.500', '4.500', '533,000']
43
4.100
44
4.650
45
4.100
46
4.500
47
4.500
48
533,000
49
Apr 01, 2019
['2019-04-01', '3.800', '4.080', '3.800', '3.920', '3.920', '247,000']
50
3.800
51
4.080
52
3.800
53
3.920
54
3.920
55
247,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8502.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.270', '0.270', '0.270', '0.270', '0.270', '552,000']
1
0.270
2
0.270
3
0.270
4
0.270
5
0.270
6
552,000
7
Apr 10, 2019
['2019-04-10', '0.270', '0.270', '0.270', '0.270', '0.270', '200,000']
8
0.270
9
0.270
10
0.270
11
0.270
12
0.270
13
200,000
14
Apr 09, 2019
['2019-04-09', '0.275', '0.275', '0.270', '0.270', '0.270', '232,000']
15
0.275
16
0.275
17
0.270
18
0.270
19
0.270
20
232,000
21
Apr 08, 2019
['2019-04-08', '0.270', '0.280', '0.270', '0.275', '0.275', '344,000']
22
0.270
23
0.280
24
0.270
25
0.275
26
0.275
27
344,000
28
Apr 04, 2019
['2019-04-04', '0.265', '0.270', '0.265', '0.265', '0.265', '368,000']
29
0.265
30
0.270
31
0.265
32
0.265
33
0.265
34
368,000
35
Apr 03, 2019
['2019-04-03', '0.260', '0.275', '0.260', '0.270', '0.270', '768,000']
36
0.260
37
0.275
38
0.260
39
0.270
40
0.270
41
768,000
42
Apr 02, 2019
['2019-04-02', '0.265', '0.270', '0.265', '0.265', '0.265', '936,000']
43
0.265
44
0.270
45
0.265
46
0.265
47
0.265
48
936,000
49
Apr 01, 2019
['2019-04-01', '0.265', '0.270', '0.265', '0.265', '0.265', '472,000']
50
0.265
51
0.270
52
0.265
53
0.265
54
0.265
55
472,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6190.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '10.600', '10.600', '10.600', '10.600', '10.600', '20,000,600']
1
10.600
2
10.600
3
10.600
4
10.600
5
10.600
6
20,000,600
7
Apr 10, 2019
['2019-04-10', '10.600', '10.600', '10.600', '10.600', '10.600', '200']
8
10.600
9
10.600
10
10.600
11
10.600
12
10.600
13
200
14
Apr 09, 2019
['2019-04-09', '10.620', '10.620', '10.460', '10.600', '10.600', '2,800']
15
10.620
16
10.620
17
10.460
18
10.600
19
10.600
20
2,800
21
Apr 08, 2019
['2019-04-08', '10.500', '10.500', '10.500', '10.600', '10.600', '1,000']
22
10.500
23
10.500
24
10.500
25
10.600
26
10.600
27
1,000
28
Apr 04, 2019
['2019-04-04', '10.600', '10.600', '10.500', '10.600', '10.600', '1,800']
29
10.600
30
10.600
31
10.500
32
10.600
33
10.600
34
1,800
35
Apr 03, 2019
['2019-04-03', '10.600', '10.600', '10.600', '10.600', '10.600', '200']
36
10.600
37
10.600
38
10.600
39
10.600
40
10.600
41
200
42
Apr 02, 2019
['2019-04-02', '10.600', '10.600', '10.600', '10.600', '10.600', '400']
43
10.600
44
10.600
45
10.600
46
10.600
47
10.600
48
400
49
Apr 01, 2019
['2019-04-01', '10.880', '10.880', '10.880', '10.800', '10.800', '200']
50
10.880
51
10.880
52
10.880
53
10.800
54
10.800
55
200
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8223.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.960', '0.990', '0.960', '0.990', '0.990', '116,000']
1
0.960
2
0.990
3
0.960
4
0.990
5
0.990
6
116,000
7
Apr 10, 2019
['2019-04-10', '0.990', '0.990', '0.960', '0.990', '0.990', '76,000']
8
0.990
9
0.990
10
0.960
11
0.990
12
0.990
13
76,000
14
Apr 09, 2019
['2019-04-09', '0.990', '0.990', '0.990', '0.990', '0.990', '168,000']
15
0.990
16
0.990
17
0.990
18
0.990
19
0.990
20
168,000
21
Apr 08, 2019
['2019-04-08', '0.990', '0.990', '0.980', '0.980', '0.980', '340,000']
22
0.990
23
0.990
24
0.980
25
0.980
26
0.980
27
340,000
28
Apr 04, 2019
['2019-04-04', '0.960', '0.990', '0.960', '0.990', '0.990', '8,000']
29
0.960
30
0.990
31
0.960
32
0.990
33
0.990
34
8,000
35
Apr 03, 2019
['2019-04-03', '0.960', '0.990', '0.930', '0.990', '0.990', '340,000']
36
0.960
37
0.990
38
0.930
39
0.990
40
0.990
41
340,000
42
Apr 02, 2019
['2019-04-02', '0.950', '0.990', '0.950', '0.960', '0.960', '44,000']
43
0.950
44
0.990
45
0.950
46
0.960
47
0.960
48
44,000
49
Apr 01, 2019
['2019-04-01', '1.000', '1.000', '1.000', '1.000', '1.000', '8,000']
50
1.000
51
1.000
52
1.000
53
1.000
54
1.000
55
8,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1810.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '11.780', '11.840', '11.520', '11.540', '11.540', '42,504,774']
1
11.780
2
11.840
3
11.520
4
11.540
5
11.540
6
42,504,774
7
Apr 10, 2019
['2019-04-10', '11.600', '11.900', '11.420', '11.840', '11.840', '58,170,697']
8
11.600
9
11.900
10
11.420
11
11.840
12
11.840
13
58,170,697
14
Apr 09, 2019
['2019-04-09', '11.720', '11.800', '11.500', '11.720', '11.720', '46,794,828']
15
11.720
16
11.800
17
11.500
18
11.720
19
11.720
20
46,794,828
21
Apr 08, 2019
['2019-04-08', '11.900', '11.960', '11.500', '11.760', '11.760', '52,740,551']
22
11.900
23
11.960
24
11.500
25
11.760
26
11.760
27
52,740,551
28
Apr 04, 2019
['2019-04-04', '11.860', '11.900', '11.660', '11.840', '11.840', '67,047,248']
29
11.860
30
11.900
31
11.660
32
11.840
33
11.840
34
67,047,248
35
Apr 03, 2019
['2019-04-03', '11.400', '11.940', '11.200', '11.920', '11.920', '114,684,905']
36
11.400
37
11.940
38
11.200
39
11.920
40
11.920
41
114,684,905
42
Apr 02, 2019
['2019-04-02', '11.400', '11.460', '11.200', '11.240', '11.240', '35,804,625']
43
11.400
44
11.460
45
11.200
46
11.240
47
11.240
48
35,804,625
49
Apr 01, 2019
['2019-04-01', '11.500', '11.500', '11.320', '11.360', '11.360', '50,751,587']
50
11.500
51
11.500
52
11.320
53
11.360
54
11.360
55
50,751,587
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1763.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '22.000', '22.000', '21.550', '21.800', '21.800', '465,200']
1
22.000
2
22.000
3
21.550
4
21.800
5
21.800
6
465,200
7
Apr 10, 2019
['2019-04-10', '22.150', '22.150', '21.500', '21.800', '21.800', '149,245']
8
22.150
9
22.150
10
21.500
11
21.800
12
21.800
13
149,245
14
Apr 09, 2019
['2019-04-09', '21.500', '22.150', '21.450', '22.150', '22.150', '572,400']
15
21.500
16
22.150
17
21.450
18
22.150
19
22.150
20
572,400
21
Apr 08, 2019
['2019-04-08', '21.000', '21.350', '20.350', '21.350', '21.350', '141,400']
22
21.000
23
21.350
24
20.350
25
21.350
26
21.350
27
141,400
28
Apr 04, 2019
['2019-04-04', '21.400', '22.000', '20.350', '20.900', '20.900', '787,200']
29
21.400
30
22.000
31
20.350
32
20.900
33
20.900
34
787,200
35
Apr 03, 2019
['2019-04-03', '21.600', '21.700', '20.900', '20.900', '20.900', '280,703']
36
21.600
37
21.700
38
20.900
39
20.900
40
20.900
41
280,703
42
Apr 02, 2019
['2019-04-02', '20.400', '21.600', '20.300', '21.600', '21.600', '486,800']
43
20.400
44
21.600
45
20.300
46
21.600
47
21.600
48
486,800
49
Apr 01, 2019
['2019-04-01', '19.980', '20.850', '19.980', '20.200', '20.200', '276,600']
50
19.980
51
20.850
52
19.980
53
20.200
54
20.200
55
276,600
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2262.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.820', '0.840', '0.800', '0.830', '0.830', '2,604,000']
1
0.820
2
0.840
3
0.800
4
0.830
5
0.830
6
2,604,000
7
Apr 10, 2019
['2019-04-10', '0.830', '0.830', '0.810', '0.820', '0.820', '1,368,000']
8
0.830
9
0.830
10
0.810
11
0.820
12
0.820
13
1,368,000
14
Apr 09, 2019
['2019-04-09', '0.860', '0.870', '0.830', '0.830', '0.830', '1,317,000']
15
0.860
16
0.870
17
0.830
18
0.830
19
0.830
20
1,317,000
21
Apr 08, 2019
['2019-04-08', '0.840', '0.850', '0.820', '0.840', '0.840', '1,272,000']
22
0.840
23
0.850
24
0.820
25
0.840
26
0.840
27
1,272,000
28
Apr 04, 2019
['2019-04-04', '0.840', '0.870', '0.820', '0.830', '0.830', '15,625,000']
29
0.840
30
0.870
31
0.820
32
0.830
33
0.830
34
15,625,000
35
Apr 03, 2019
['2019-04-03', '0.820', '0.840', '0.810', '0.830', '0.830', '1,986,000']
36
0.820
37
0.840
38
0.810
39
0.830
40
0.830
41
1,986,000
42
Apr 02, 2019
['2019-04-02', '0.860', '0.860', '0.810', '0.810', '0.810', '2,010,000']
43
0.860
44
0.860
45
0.810
46
0.810
47
0.810
48
2,010,000
49
Apr 01, 2019
['2019-04-01', '0.840', '0.850', '0.830', '0.850', '0.850', '1,299,000']
50
0.840
51
0.850
52
0.830
53
0.850
54
0.850
55
1,299,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8305.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.117', '0.120', '0.116', '0.116', '0.116', '2,160,000']
1
0.117
2
0.120
3
0.116
4
0.116
5
0.116
6
2,160,000
7
Apr 10, 2019
['2019-04-10', '0.119', '0.119', '0.115', '0.116', '0.116', '970,000']
8
0.119
9
0.119
10
0.115
11
0.116
12
0.116
13
970,000
14
Apr 09, 2019
['2019-04-09', '0.121', '0.121', '0.120', '0.120', '0.120', '430,000']
15
0.121
16
0.121
17
0.120
18
0.120
19
0.120
20
430,000
21
Apr 08, 2019
['2019-04-08', '0.120', '0.122', '0.119', '0.120', '0.120', '780,000']
22
0.120
23
0.122
24
0.119
25
0.120
26
0.120
27
780,000
28
Apr 04, 2019
['2019-04-04', '0.122', '0.122', '0.118', '0.122', '0.122', '190,000']
29
0.122
30
0.122
31
0.118
32
0.122
33
0.122
34
190,000
35
Apr 03, 2019
['2019-04-03', '0.121', '0.123', '0.121', '0.123', '0.123', '240,000']
36
0.121
37
0.123
38
0.121
39
0.123
40
0.123
41
240,000
42
Apr 02, 2019
['2019-04-02', '0.120', '0.120', '0.120', '0.120', '0.120', '-']
43
0.120
44
0.120
45
0.120
46
0.120
47
0.120
48
-
49
Apr 01, 2019
['2019-04-01', '0.117', '0.120', '0.117', '0.120', '0.120', '310,000']
50
0.117
51
0.120
52
0.117
53
0.120
54
0.120
55
310,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1592.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.190', '0.196', '0.189', '0.195', '0.195', '285,000']
1
0.190
2
0.196
3
0.189
4
0.195
5
0.195
6
285,000
7
Apr 10, 2019
['2019-04-10', '0.189', '0.200', '0.189', '0.195', '0.195', '425,000']
8
0.189
9
0.200
10
0.189
11
0.195
12
0.195
13
425,000
14
Apr 09, 2019
['2019-04-09', '0.186', '0.190', '0.186', '0.188', '0.188', '65,000']
15
0.186
16
0.190
17
0.186
18
0.188
19
0.188
20
65,000
21
Apr 08, 2019
['2019-04-08', '0.177', '0.193', '0.177', '0.187', '0.187', '570,000']
22
0.177
23
0.193
24
0.177
25
0.187
26
0.187
27
570,000
28
Apr 04, 2019
['2019-04-04', '0.179', '0.191', '0.170', '0.185', '0.185', '1,340,000']
29
0.179
30
0.191
31
0.170
32
0.185
33
0.185
34
1,340,000
35
Apr 03, 2019
['2019-04-03', '0.195', '0.195', '0.182', '0.189', '0.189', '620,000']
36
0.195
37
0.195
38
0.182
39
0.189
40
0.189
41
620,000
42
Apr 02, 2019
['2019-04-02', '0.196', '0.196', '0.196', '0.196', '0.196', '-']
43
0.196
44
0.196
45
0.196
46
0.196
47
0.196
48
-
49
Apr 01, 2019
['2019-04-01', '0.196', '0.197', '0.196', '0.197', '0.197', '115,000']
50
0.196
51
0.197
52
0.196
53
0.197
54
0.197
55
115,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6100.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '20.250', '20.450', '19.940', '19.980', '19.980', '160,400']
1
20.250
2
20.450
3
19.940
4
19.980
5
19.980
6
160,400
7
Apr 10, 2019
['2019-04-10', '20.100', '20.500', '19.920', '20.100', '20.100', '1,060,600']
8
20.100
9
20.500
10
19.920
11
20.100
12
20.100
13
1,060,600
14
Apr 09, 2019
['2019-04-09', '19.960', '20.000', '19.700', '19.900', '19.900', '433,400']
15
19.960
16
20.000
17
19.700
18
19.900
19
19.900
20
433,400
21
Apr 08, 2019
['2019-04-08', '19.740', '20.000', '19.720', '19.780', '19.780', '468,224']
22
19.740
23
20.000
24
19.720
25
19.780
26
19.780
27
468,224
28
Apr 04, 2019
['2019-04-04', '20.000', '20.500', '19.640', '19.740', '19.740', '2,869,200']
29
20.000
30
20.500
31
19.640
32
19.740
33
19.740
34
2,869,200
35
Apr 03, 2019
['2019-04-03', '22.000', '22.150', '19.880', '19.960', '19.960', '16,246,600']
36
22.000
37
22.150
38
19.880
39
19.960
40
19.960
41
16,246,600
42
Apr 02, 2019
['2019-04-02', '22.700', '22.800', '22.500', '22.500', '22.500', '583,204']
43
22.700
44
22.800
45
22.500
46
22.500
47
22.500
48
583,204
49
Apr 01, 2019
['2019-04-01', '23.200', '24.600', '22.650', '22.700', '22.700', '698,900']
50
23.200
51
24.600
52
22.650
53
22.700
54
22.700
55
698,900
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1620.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.250', '0.250', '0.250', '0.250', '0.250', '-']
1
0.250
2
0.250
3
0.250
4
0.250
5
0.250
6
-
7
Apr 10, 2019
['2019-04-10', '0.250', '0.250', '0.250', '0.250', '0.250', '-']
8
0.250
9
0.250
10
0.250
11
0.250
12
0.250
13
-
14
Apr 09, 2019
['2019-04-09', '0.255', '0.255', '0.248', '0.250', '0.250', '630,000']
15
0.255
16
0.255
17
0.248
18
0.250
19
0.250
20
630,000
21
Apr 08, 2019
['2019-04-08', '0.265', '0.265', '0.255', '0.255', '0.255', '230,000']
22
0.265
23
0.265
24
0.255
25
0.255
26
0.255
27
230,000
28
Apr 04, 2019
['2019-04-04', '0.249', '0.265', '0.249', '0.265', '0.265', '490,000']
29
0.249
30
0.265
31
0.249
32
0.265
33
0.265
34
490,000
35
Apr 03, 2019
['2019-04-03', '0.249', '0.249', '0.249', '0.249', '0.249', '260,000']
36
0.249
37
0.249
38
0.249
39
0.249
40
0.249
41
260,000
42
Apr 02, 2019
['2019-04-02', '0.250', '0.250', '0.250', '0.250', '0.250', '60,000']
43
0.250
44
0.250
45
0.250
46
0.250
47
0.250
48
60,000
49
Apr 01, 2019
['2019-04-01', '0.246', '0.250', '0.246', '0.250', '0.250', '30,000']
50
0.246
51
0.250
52
0.246
53
0.250
54
0.250
55
30,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8146.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.270', '0.275', '0.270', '0.270', '0.270', '360,000']
1
0.270
2
0.275
3
0.270
4
0.270
5
0.270
6
360,000
7
Apr 10, 2019
['2019-04-10', '0.270', '0.270', '0.270', '0.270', '0.270', '200,000']
8
0.270
9
0.270
10
0.270
11
0.270
12
0.270
13
200,000
14
Apr 09, 2019
['2019-04-09', '0.275', '0.275', '0.270', '0.270', '0.270', '1,090,000']
15
0.275
16
0.275
17
0.270
18
0.270
19
0.270
20
1,090,000
21
Apr 08, 2019
['2019-04-08', '0.270', '0.275', '0.270', '0.270', '0.270', '330,000']
22
0.270
23
0.275
24
0.270
25
0.270
26
0.270
27
330,000
28
Apr 04, 2019
['2019-04-04', '0.275', '0.280', '0.270', '0.270', '0.270', '850,000']
29
0.275
30
0.280
31
0.270
32
0.270
33
0.270
34
850,000
35
Apr 03, 2019
['2019-04-03', '0.275', '0.280', '0.275', '0.275', '0.275', '630,000']
36
0.275
37
0.280
38
0.275
39
0.275
40
0.275
41
630,000
42
Apr 02, 2019
['2019-04-02', '0.280', '0.285', '0.275', '0.275', '0.275', '280,000']
43
0.280
44
0.285
45
0.275
46
0.275
47
0.275
48
280,000
49
Apr 01, 2019
['2019-04-01', '0.280', '0.280', '0.275', '0.280', '0.280', '1,100,000']
50
0.280
51
0.280
52
0.275
53
0.280
54
0.280
55
1,100,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1749.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.520', '1.520', '1.490', '1.500', '1.500', '80,000']
1
1.520
2
1.520
3
1.490
4
1.500
5
1.500
6
80,000
7
Apr 10, 2019
['2019-04-10', '1.500', '1.530', '1.470', '1.530', '1.530', '185,000']
8
1.500
9
1.530
10
1.470
11
1.530
12
1.530
13
185,000
14
Apr 09, 2019
['2019-04-09', '1.490', '1.490', '1.470', '1.480', '1.480', '173,000']
15
1.490
16
1.490
17
1.470
18
1.480
19
1.480
20
173,000
21
Apr 08, 2019
['2019-04-08', '1.500', '1.510', '1.450', '1.490', '1.490', '229,000']
22
1.500
23
1.510
24
1.450
25
1.490
26
1.490
27
229,000
28
Apr 04, 2019
['2019-04-04', '1.500', '1.520', '1.490', '1.490', '1.490', '73,000']
29
1.500
30
1.520
31
1.490
32
1.490
33
1.490
34
73,000
35
Apr 03, 2019
['2019-04-03', '1.500', '1.500', '1.490', '1.490', '1.490', '78,000']
36
1.500
37
1.500
38
1.490
39
1.490
40
1.490
41
78,000
42
Apr 02, 2019
['2019-04-02', '1.470', '1.500', '1.460', '1.500', '1.500', '118,000']
43
1.470
44
1.500
45
1.460
46
1.500
47
1.500
48
118,000
49
Apr 01, 2019
['2019-04-01', '1.480', '1.500', '1.460', '1.480', '1.480', '142,000']
50
1.480
51
1.500
52
1.460
53
1.480
54
1.480
55
142,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1587.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.460', '0.460', '0.445', '0.460', '0.460', '84,000']
1
0.460
2
0.460
3
0.445
4
0.460
5
0.460
6
84,000
7
Apr 10, 2019
['2019-04-10', '0.450', '0.465', '0.440', '0.465', '0.465', '176,000']
8
0.450
9
0.465
10
0.440
11
0.465
12
0.465
13
176,000
14
Apr 09, 2019
['2019-04-09', '0.460', '0.460', '0.445', '0.455', '0.455', '604,000']
15
0.460
16
0.460
17
0.445
18
0.455
19
0.455
20
604,000
21
Apr 08, 2019
['2019-04-08', '0.460', '0.465', '0.455', '0.465', '0.465', '72,000']
22
0.460
23
0.465
24
0.455
25
0.465
26
0.465
27
72,000
28
Apr 04, 2019
['2019-04-04', '0.470', '0.470', '0.470', '0.470', '0.470', '8,000']
29
0.470
30
0.470
31
0.470
32
0.470
33
0.470
34
8,000
35
Apr 03, 2019
['2019-04-03', '0.480', '0.480', '0.465', '0.475', '0.475', '260,000']
36
0.480
37
0.480
38
0.465
39
0.475
40
0.475
41
260,000
42
Apr 02, 2019
['2019-04-02', '0.465', '0.495', '0.465', '0.495', '0.495', '1,820,000']
43
0.465
44
0.495
45
0.465
46
0.495
47
0.495
48
1,820,000
49
Apr 01, 2019
['2019-04-01', '0.470', '0.475', '0.470', '0.475', '0.475', '28,000']
50
0.470
51
0.475
52
0.470
53
0.475
54
0.475
55
28,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1916.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '6.370', '6.400', '6.350', '6.370', '6.370', '1,058,000']
1
6.370
2
6.400
3
6.350
4
6.370
5
6.370
6
1,058,000
7
Apr 10, 2019
['2019-04-10', '6.380', '6.420', '6.350', '6.370', '6.370', '1,198,000']
8
6.380
9
6.420
10
6.350
11
6.370
12
6.370
13
1,198,000
14
Apr 09, 2019
['2019-04-09', '6.300', '6.550', '6.300', '6.380', '6.380', '1,164,500']
15
6.300
16
6.550
17
6.300
18
6.380
19
6.380
20
1,164,500
21
Apr 08, 2019
['2019-04-08', '6.380', '6.550', '6.350', '6.390', '6.390', '975,000']
22
6.380
23
6.550
24
6.350
25
6.390
26
6.390
27
975,000
28
Apr 04, 2019
['2019-04-04', '6.400', '6.400', '6.390', '6.390', '6.390', '27,000']
29
6.400
30
6.400
31
6.390
32
6.390
33
6.390
34
27,000
35
Apr 03, 2019
['2019-04-03', '6.350', '6.490', '6.300', '6.360', '6.360', '227,000']
36
6.350
37
6.490
38
6.300
39
6.360
40
6.360
41
227,000
42
Apr 02, 2019
['2019-04-02', '6.380', '6.520', '6.380', '6.380', '6.380', '15,000']
43
6.380
44
6.520
45
6.380
46
6.380
47
6.380
48
15,000
49
Apr 01, 2019
['2019-04-01', '6.450', '6.660', '6.200', '6.380', '6.380', '753,500']
50
6.450
51
6.660
52
6.200
53
6.380
54
6.380
55
753,500
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2003.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '9.030', '9.080', '8.930', '9.050', '9.050', '578,600']
1
9.030
2
9.080
3
8.930
4
9.050
5
9.050
6
578,600
7
Apr 10, 2019
['2019-04-10', '9.040', '9.050', '8.890', '9.010', '9.010', '588,400']
8
9.040
9
9.050
10
8.890
11
9.010
12
9.010
13
588,400
14
Apr 09, 2019
['2019-04-09', '9.060', '9.080', '8.900', '8.990', '8.990', '384,000']
15
9.060
16
9.080
17
8.900
18
8.990
19
8.990
20
384,000
21
Apr 08, 2019
['2019-04-08', '9.230', '9.230', '8.800', '9.070', '9.070', '628,000']
22
9.230
23
9.230
24
8.800
25
9.070
26
9.070
27
628,000
28
Apr 04, 2019
['2019-04-04', '9.300', '9.310', '8.700', '9.020', '9.020', '707,800']
29
9.300
30
9.310
31
8.700
32
9.020
33
9.020
34
707,800
35
Apr 03, 2019
['2019-04-03', '9.390', '9.410', '9.180', '9.180', '9.180', '603,200']
36
9.390
37
9.410
38
9.180
39
9.180
40
9.180
41
603,200
42
Apr 02, 2019
['2019-04-02', '9.730', '9.730', '9.330', '9.520', '9.520', '711,800']
43
9.730
44
9.730
45
9.330
46
9.520
47
9.520
48
711,800
49
Apr 01, 2019
['2019-04-01', '9.900', '10.420', '9.530', '9.740', '9.740', '673,400']
50
9.900
51
10.420
52
9.530
53
9.740
54
9.740
55
673,400
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6098.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '14.400', '14.500', '14.040', '14.160', '14.160', '8,919,033']
1
14.400
2
14.500
3
14.040
4
14.160
5
14.160
6
8,919,033
7
Apr 10, 2019
['2019-04-10', '14.580', '14.680', '14.400', '14.500', '14.500', '10,075,890']
8
14.580
9
14.680
10
14.400
11
14.500
12
14.500
13
10,075,890
14
Apr 09, 2019
['2019-04-09', '14.520', '14.840', '14.380', '14.600', '14.600', '8,773,487']
15
14.520
16
14.840
17
14.380
18
14.600
19
14.600
20
8,773,487
21
Apr 08, 2019
['2019-04-08', '14.640', '14.680', '14.360', '14.500', '14.500', '6,170,375']
22
14.640
23
14.680
24
14.360
25
14.500
26
14.500
27
6,170,375
28
Apr 04, 2019
['2019-04-04', '14.500', '14.660', '14.360', '14.500', '14.500', '4,154,185']
29
14.500
30
14.660
31
14.360
32
14.500
33
14.500
34
4,154,185
35
Apr 03, 2019
['2019-04-03', '14.600', '14.680', '14.340', '14.460', '14.460', '4,811,236']
36
14.600
37
14.680
38
14.340
39
14.460
40
14.460
41
4,811,236
42
Apr 02, 2019
['2019-04-02', '14.700', '14.880', '14.300', '14.500', '14.500', '7,170,598']
43
14.700
44
14.880
45
14.300
46
14.500
47
14.500
48
7,170,598
49
Apr 01, 2019
['2019-04-01', '14.660', '15.000', '14.440', '14.600', '14.600', '6,246,342']
50
14.660
51
15.000
52
14.440
53
14.600
54
14.600
55
6,246,342
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8357.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.740', '0.750', '0.710', '0.740', '0.740', '455,000']
1
0.740
2
0.750
3
0.710
4
0.740
5
0.740
6
455,000
7
Apr 10, 2019
['2019-04-10', '0.760', '0.760', '0.730', '0.740', '0.740', '190,000']
8
0.760
9
0.760
10
0.730
11
0.740
12
0.740
13
190,000
14
Apr 09, 2019
['2019-04-09', '0.730', '0.740', '0.720', '0.740', '0.740', '280,000']
15
0.730
16
0.740
17
0.720
18
0.740
19
0.740
20
280,000
21
Apr 08, 2019
['2019-04-08', '0.730', '0.750', '0.730', '0.740', '0.740', '390,000']
22
0.730
23
0.750
24
0.730
25
0.740
26
0.740
27
390,000
28
Apr 04, 2019
['2019-04-04', '0.720', '0.730', '0.720', '0.730', '0.730', '175,000']
29
0.720
30
0.730
31
0.720
32
0.730
33
0.730
34
175,000
35
Apr 03, 2019
['2019-04-03', '0.710', '0.740', '0.710', '0.730', '0.730', '410,000']
36
0.710
37
0.740
38
0.710
39
0.730
40
0.730
41
410,000
42
Apr 02, 2019
['2019-04-02', '0.720', '0.740', '0.710', '0.740', '0.740', '400,000']
43
0.720
44
0.740
45
0.710
46
0.740
47
0.740
48
400,000
49
Apr 01, 2019
['2019-04-01', '0.740', '0.760', '0.720', '0.730', '0.730', '1,580,000']
50
0.740
51
0.760
52
0.720
53
0.730
54
0.730
55
1,580,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1806.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.410', '4.740', '4.320', '4.690', '4.690', '3,343,600']
1
4.410
2
4.740
3
4.320
4
4.690
5
4.690
6
3,343,600
7
Apr 10, 2019
['2019-04-10', '4.220', '4.420', '4.210', '4.400', '4.400', '2,694,800']
8
4.220
9
4.420
10
4.210
11
4.400
12
4.400
13
2,694,800
14
Apr 09, 2019
['2019-04-09', '4.340', '4.400', '4.160', '4.300', '4.300', '1,629,348']
15
4.340
16
4.400
17
4.160
18
4.300
19
4.300
20
1,629,348
21
Apr 08, 2019
['2019-04-08', '4.350', '4.410', '4.130', '4.300', '4.300', '1,132,400']
22
4.350
23
4.410
24
4.130
25
4.300
26
4.300
27
1,132,400
28
Apr 04, 2019
['2019-04-04', '4.340', '4.400', '4.220', '4.300', '4.300', '1,230,622']
29
4.340
30
4.400
31
4.220
32
4.300
33
4.300
34
1,230,622
35
Apr 03, 2019
['2019-04-03', '4.470', '4.470', '4.200', '4.340', '4.340', '933,600']
36
4.470
37
4.470
38
4.200
39
4.340
40
4.340
41
933,600
42
Apr 02, 2019
['2019-04-02', '4.300', '4.460', '4.220', '4.410', '4.410', '2,346,948']
43
4.300
44
4.460
45
4.220
46
4.410
47
4.410
48
2,346,948
49
Apr 01, 2019
['2019-04-01', '3.970', '4.320', '3.960', '4.300', '4.300', '2,807,411']
50
3.970
51
4.320
52
3.960
53
4.300
54
4.300
55
2,807,411
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8403.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.063', '0.075', '0.061', '0.064', '0.064', '2,760,000']
1
0.063
2
0.075
3
0.061
4
0.064
5
0.064
6
2,760,000
7
Apr 10, 2019
['2019-04-10', '0.063', '0.065', '0.061', '0.061', '0.061', '3,760,000']
8
0.063
9
0.065
10
0.061
11
0.061
12
0.061
13
3,760,000
14
Apr 09, 2019
['2019-04-09', '0.065', '0.074', '0.060', '0.063', '0.063', '7,780,000']
15
0.065
16
0.074
17
0.060
18
0.063
19
0.063
20
7,780,000
21
Apr 08, 2019
['2019-04-08', '0.056', '0.065', '0.056', '0.065', '0.065', '14,520,000']
22
0.056
23
0.065
24
0.056
25
0.065
26
0.065
27
14,520,000
28
Apr 04, 2019
['2019-04-04', '0.054', '0.057', '0.054', '0.054', '0.054', '2,360,000']
29
0.054
30
0.057
31
0.054
32
0.054
33
0.054
34
2,360,000
35
Apr 03, 2019
['2019-04-03', '0.053', '0.054', '0.053', '0.054', '0.054', '600,000']
36
0.053
37
0.054
38
0.053
39
0.054
40
0.054
41
600,000
42
Apr 02, 2019
['2019-04-02', '0.052', '0.055', '0.050', '0.053', '0.053', '2,180,000']
43
0.052
44
0.055
45
0.050
46
0.053
47
0.053
48
2,180,000
49
Apr 01, 2019
['2019-04-01', '0.054', '0.054', '0.051', '0.051', '0.051', '740,000']
50
0.054
51
0.054
52
0.051
53
0.051
54
0.051
55
740,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1751.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.270', '0.270', '0.265', '0.275', '0.275', '140,000']
1
0.270
2
0.270
3
0.265
4
0.275
5
0.275
6
140,000
7
Apr 10, 2019
['2019-04-10', '0.280', '0.280', '0.280', '0.280', '0.280', '-']
8
0.280
9
0.280
10
0.280
11
0.280
12
0.280
13
-
14
Apr 09, 2019
['2019-04-09', '0.280', '0.280', '0.270', '0.275', '0.275', '70,000']
15
0.280
16
0.280
17
0.270
18
0.275
19
0.275
20
70,000
21
Apr 08, 2019
['2019-04-08', '0.270', '0.270', '0.270', '0.270', '0.270', '150,000']
22
0.270
23
0.270
24
0.270
25
0.270
26
0.270
27
150,000
28
Apr 04, 2019
['2019-04-04', '0.280', '0.280', '0.280', '0.280', '0.280', '-']
29
0.280
30
0.280
31
0.280
32
0.280
33
0.280
34
-
35
Apr 03, 2019
['2019-04-03', '0.275', '0.275', '0.275', '0.275', '0.275', '-']
36
0.275
37
0.275
38
0.275
39
0.275
40
0.275
41
-
42
Apr 02, 2019
['2019-04-02', '0.290', '0.290', '0.270', '0.270', '0.270', '30,000']
43
0.290
44
0.290
45
0.270
46
0.270
47
0.270
48
30,000
49
Apr 01, 2019
['2019-04-01', '0.285', '0.285', '0.280', '0.280', '0.280', '20,000']
50
0.285
51
0.285
52
0.280
53
0.280
54
0.280
55
20,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1757.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.227', '0.227', '0.227', '0.227', '0.227', '-']
1
0.227
2
0.227
3
0.227
4
0.227
5
0.227
6
-
7
Apr 10, 2019
['2019-04-10', '0.230', '0.230', '0.223', '0.224', '0.224', '170,000']
8
0.230
9
0.230
10
0.223
11
0.224
12
0.224
13
170,000
14
Apr 09, 2019
['2019-04-09', '0.229', '0.240', '0.225', '0.239', '0.239', '380,000']
15
0.229
16
0.240
17
0.225
18
0.239
19
0.239
20
380,000
21
Apr 08, 2019
['2019-04-08', '0.222', '0.225', '0.222', '0.225', '0.225', '140,000']
22
0.222
23
0.225
24
0.222
25
0.225
26
0.225
27
140,000
28
Apr 04, 2019
['2019-04-04', '0.239', '0.239', '0.239', '0.239', '0.239', '-']
29
0.239
30
0.239
31
0.239
32
0.239
33
0.239
34
-
35
Apr 03, 2019
['2019-04-03', '0.245', '0.245', '0.245', '0.245', '0.245', '50,000']
36
0.245
37
0.245
38
0.245
39
0.245
40
0.245
41
50,000
42
Apr 02, 2019
['2019-04-02', '0.231', '0.245', '0.231', '0.245', '0.245', '290,000']
43
0.231
44
0.245
45
0.231
46
0.245
47
0.245
48
290,000
49
Apr 01, 2019
['2019-04-01', '0.237', '0.237', '0.237', '0.237', '0.237', '-']
50
0.237
51
0.237
52
0.237
53
0.237
54
0.237
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6119.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.650', '0.650', '0.650', '0.650', '0.650', '6,000']
1
0.650
2
0.650
3
0.650
4
0.650
5
0.650
6
6,000
7
Apr 10, 2019
['2019-04-10', '0.650', '0.650', '0.650', '0.650', '0.650', '174,000']
8
0.650
9
0.650
10
0.650
11
0.650
12
0.650
13
174,000
14
Apr 09, 2019
['2019-04-09', '0.660', '0.690', '0.650', '0.660', '0.660', '291,000']
15
0.660
16
0.690
17
0.650
18
0.660
19
0.660
20
291,000
21
Apr 08, 2019
['2019-04-08', '0.650', '0.690', '0.650', '0.660', '0.660', '759,000']
22
0.650
23
0.690
24
0.650
25
0.660
26
0.660
27
759,000
28
Apr 04, 2019
['2019-04-04', '0.600', '0.600', '0.600', '0.600', '0.600', '-']
29
0.600
30
0.600
31
0.600
32
0.600
33
0.600
34
-
35
Apr 03, 2019
['2019-04-03', '0.610', '0.610', '0.600', '0.600', '0.600', '135,000']
36
0.610
37
0.610
38
0.600
39
0.600
40
0.600
41
135,000
42
Apr 02, 2019
['2019-04-02', '0.620', '0.620', '0.620', '0.620', '0.620', '-']
43
0.620
44
0.620
45
0.620
46
0.620
47
0.620
48
-
49
Apr 01, 2019
['2019-04-01', '0.640', '0.650', '0.620', '0.620', '0.620', '237,000']
50
0.640
51
0.650
52
0.620
53
0.620
54
0.620
55
237,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1451.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.830', '0.830', '0.820', '0.820', '0.820', '106,000']
1
0.830
2
0.830
3
0.820
4
0.820
5
0.820
6
106,000
7
Apr 10, 2019
['2019-04-10', '0.850', '0.850', '0.850', '0.850', '0.850', '50,000']
8
0.850
9
0.850
10
0.850
11
0.850
12
0.850
13
50,000
14
Apr 09, 2019
['2019-04-09', '0.860', '0.870', '0.850', '0.850', '0.850', '234,000']
15
0.860
16
0.870
17
0.850
18
0.850
19
0.850
20
234,000
21
Apr 08, 2019
['2019-04-08', '0.880', '0.880', '0.860', '0.860', '0.860', '56,000']
22
0.880
23
0.880
24
0.860
25
0.860
26
0.860
27
56,000
28
Apr 04, 2019
['2019-04-04', '0.880', '0.880', '0.880', '0.880', '0.880', '-']
29
0.880
30
0.880
31
0.880
32
0.880
33
0.880
34
-
35
Apr 03, 2019
['2019-04-03', '0.870', '0.880', '0.840', '0.880', '0.880', '330,000']
36
0.870
37
0.880
38
0.840
39
0.880
40
0.880
41
330,000
42
Apr 02, 2019
['2019-04-02', '0.830', '0.870', '0.830', '0.870', '0.870', '6,000']
43
0.830
44
0.870
45
0.830
46
0.870
47
0.870
48
6,000
49
Apr 01, 2019
['2019-04-01', '0.870', '0.870', '0.870', '0.870', '0.870', '-']
50
0.870
51
0.870
52
0.870
53
0.870
54
0.870
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8545.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.144', '0.144', '0.141', '0.143', '0.143', '48,000']
1
0.144
2
0.144
3
0.141
4
0.143
5
0.143
6
48,000
7
Apr 10, 2019
['2019-04-10', '0.141', '0.143', '0.139', '0.141', '0.141', '352,000']
8
0.141
9
0.143
10
0.139
11
0.141
12
0.141
13
352,000
14
Apr 09, 2019
['2019-04-09', '0.137', '0.144', '0.137', '0.141', '0.141', '1,056,000']
15
0.137
16
0.144
17
0.137
18
0.141
19
0.141
20
1,056,000
21
Apr 08, 2019
['2019-04-08', '0.140', '0.141', '0.138', '0.138', '0.138', '952,000']
22
0.140
23
0.141
24
0.138
25
0.138
26
0.138
27
952,000
28
Apr 04, 2019
['2019-04-04', '0.141', '0.146', '0.136', '0.139', '0.139', '2,288,000']
29
0.141
30
0.146
31
0.136
32
0.139
33
0.139
34
2,288,000
35
Apr 03, 2019
['2019-04-03', '0.141', '0.146', '0.141', '0.142', '0.142', '10,832,000']
36
0.141
37
0.146
38
0.141
39
0.142
40
0.142
41
10,832,000
42
Apr 02, 2019
['2019-04-02', '0.143', '0.147', '0.142', '0.142', '0.142', '1,832,000']
43
0.143
44
0.147
45
0.142
46
0.142
47
0.142
48
1,832,000
49
Apr 01, 2019
['2019-04-01', '0.140', '0.144', '0.138', '0.142', '0.142', '1,744,000']
50
0.140
51
0.144
52
0.138
53
0.142
54
0.142
55
1,744,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8490.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.415', '0.415', '0.410', '0.410', '0.410', '350,000']
1
0.415
2
0.415
3
0.410
4
0.410
5
0.410
6
350,000
7
Apr 10, 2019
['2019-04-10', '0.390', '0.425', '0.390', '0.425', '0.425', '690,000']
8
0.390
9
0.425
10
0.390
11
0.425
12
0.425
13
690,000
14
Apr 09, 2019
['2019-04-09', '0.395', '0.395', '0.385', '0.390', '0.390', '445,000']
15
0.395
16
0.395
17
0.385
18
0.390
19
0.390
20
445,000
21
Apr 08, 2019
['2019-04-08', '0.390', '0.390', '0.370', '0.385', '0.385', '525,000']
22
0.390
23
0.390
24
0.370
25
0.385
26
0.385
27
525,000
28
Apr 04, 2019
['2019-04-04', '0.410', '0.410', '0.380', '0.380', '0.380', '905,000']
29
0.410
30
0.410
31
0.380
32
0.380
33
0.380
34
905,000
35
Apr 03, 2019
['2019-04-03', '0.415', '0.425', '0.415', '0.415', '0.415', '635,000']
36
0.415
37
0.425
38
0.415
39
0.415
40
0.415
41
635,000
42
Apr 02, 2019
['2019-04-02', '0.415', '0.415', '0.405', '0.410', '0.410', '135,000']
43
0.415
44
0.415
45
0.405
46
0.410
47
0.410
48
135,000
49
Apr 01, 2019
['2019-04-01', '0.435', '0.440', '0.375', '0.430', '0.430', '595,000']
50
0.435
51
0.440
52
0.375
53
0.430
54
0.430
55
595,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1978.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.840', '0.860', '0.840', '0.850', '0.850', '812,000']
1
0.840
2
0.860
3
0.840
4
0.850
5
0.850
6
812,000
7
Apr 10, 2019
['2019-04-10', '0.860', '0.860', '0.840', '0.850', '0.850', '750,000']
8
0.860
9
0.860
10
0.840
11
0.850
12
0.850
13
750,000
14
Apr 09, 2019
['2019-04-09', '0.850', '0.880', '0.840', '0.860', '0.860', '1,038,000']
15
0.850
16
0.880
17
0.840
18
0.860
19
0.860
20
1,038,000
21
Apr 08, 2019
['2019-04-08', '0.880', '0.910', '0.860', '0.860', '0.860', '784,000']
22
0.880
23
0.910
24
0.860
25
0.860
26
0.860
27
784,000
28
Apr 04, 2019
['2019-04-04', '0.890', '0.900', '0.850', '0.880', '0.880', '1,514,000']
29
0.890
30
0.900
31
0.850
32
0.880
33
0.880
34
1,514,000
35
Apr 03, 2019
['2019-04-03', '0.870', '0.890', '0.860', '0.890', '0.890', '646,000']
36
0.870
37
0.890
38
0.860
39
0.890
40
0.890
41
646,000
42
Apr 02, 2019
['2019-04-02', '0.910', '0.910', '0.870', '0.870', '0.870', '1,012,000']
43
0.910
44
0.910
45
0.870
46
0.870
47
0.870
48
1,012,000
49
Apr 01, 2019
['2019-04-01', '0.920', '0.930', '0.830', '0.910', '0.910', '4,386,000']
50
0.920
51
0.930
52
0.830
53
0.910
54
0.910
55
4,386,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3613.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '15.140', '15.380', '15.060', '15.140', '15.140', '302,340']
1
15.140
2
15.380
3
15.060
4
15.140
5
15.140
6
302,340
7
Apr 10, 2019
['2019-04-10', '14.960', '15.320', '14.960', '15.140', '15.140', '548,000']
8
14.960
9
15.320
10
14.960
11
15.140
12
15.140
13
548,000
14
Apr 09, 2019
['2019-04-09', '15.180', '15.260', '14.740', '15.260', '15.260', '757,843']
15
15.180
16
15.260
17
14.740
18
15.260
19
15.260
20
757,843
21
Apr 08, 2019
['2019-04-08', '15.000', '15.060', '14.780', '14.780', '14.780', '379,000']
22
15.000
23
15.060
24
14.780
25
14.780
26
14.780
27
379,000
28
Apr 04, 2019
['2019-04-04', '15.000', '15.400', '15.000', '15.040', '15.040', '352,000']
29
15.000
30
15.400
31
15.000
32
15.040
33
15.040
34
352,000
35
Apr 03, 2019
['2019-04-03', '15.040', '15.480', '15.040', '15.420', '15.420', '680,000']
36
15.040
37
15.480
38
15.040
39
15.420
40
15.420
41
680,000
42
Apr 02, 2019
['2019-04-02', '14.880', '15.560', '14.680', '15.060', '15.060', '762,000']
43
14.880
44
15.560
45
14.680
46
15.060
47
15.060
48
762,000
49
Apr 01, 2019
['2019-04-01', '14.340', '14.860', '14.340', '14.600', '14.600', '403,000']
50
14.340
51
14.860
52
14.340
53
14.600
54
14.600
55
403,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1598.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.850', '0.860', '0.830', '0.840', '0.840', '681,000']
1
0.850
2
0.860
3
0.830
4
0.840
5
0.840
6
681,000
7
Apr 10, 2019
['2019-04-10', '0.840', '0.860', '0.840', '0.840', '0.840', '1,005,000']
8
0.840
9
0.860
10
0.840
11
0.840
12
0.840
13
1,005,000
14
Apr 09, 2019
['2019-04-09', '0.850', '0.860', '0.840', '0.860', '0.860', '831,000']
15
0.850
16
0.860
17
0.840
18
0.860
19
0.860
20
831,000
21
Apr 08, 2019
['2019-04-08', '0.850', '0.860', '0.850', '0.850', '0.850', '687,000']
22
0.850
23
0.860
24
0.850
25
0.850
26
0.850
27
687,000
28
Apr 04, 2019
['2019-04-04', '0.840', '0.860', '0.820', '0.850', '0.850', '1,557,000']
29
0.840
30
0.860
31
0.820
32
0.850
33
0.850
34
1,557,000
35
Apr 03, 2019
['2019-04-03', '0.840', '0.850', '0.820', '0.840', '0.840', '981,000']
36
0.840
37
0.850
38
0.820
39
0.840
40
0.840
41
981,000
42
Apr 02, 2019
['2019-04-02', '0.840', '0.850', '0.830', '0.850', '0.850', '147,000']
43
0.840
44
0.850
45
0.830
46
0.850
47
0.850
48
147,000
49
Apr 01, 2019
['2019-04-01', '0.850', '0.860', '0.820', '0.850', '0.850', '840,000']
50
0.850
51
0.860
52
0.820
53
0.850
54
0.850
55
840,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8536.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.600', '0.630', '0.600', '0.620', '0.620', '2,770,000']
1
0.600
2
0.630
3
0.600
4
0.620
5
0.620
6
2,770,000
7
Apr 10, 2019
['2019-04-10', '0.610', '0.610', '0.590', '0.590', '0.590', '2,280,000']
8
0.610
9
0.610
10
0.590
11
0.590
12
0.590
13
2,280,000
14
Apr 09, 2019
['2019-04-09', '0.570', '0.620', '0.560', '0.600', '0.600', '4,470,000']
15
0.570
16
0.620
17
0.560
18
0.600
19
0.600
20
4,470,000
21
Apr 08, 2019
['2019-04-08', '0.570', '0.580', '0.560', '0.570', '0.570', '2,710,000']
22
0.570
23
0.580
24
0.560
25
0.570
26
0.570
27
2,710,000
28
Apr 04, 2019
['2019-04-04', '0.560', '0.610', '0.550', '0.560', '0.560', '9,130,000']
29
0.560
30
0.610
31
0.550
32
0.560
33
0.560
34
9,130,000
35
Apr 03, 2019
['2019-04-03', '0.550', '0.570', '0.550', '0.560', '0.560', '1,180,000']
36
0.550
37
0.570
38
0.550
39
0.560
40
0.560
41
1,180,000
42
Apr 02, 2019
['2019-04-02', '0.550', '0.560', '0.540', '0.550', '0.550', '1,690,000']
43
0.550
44
0.560
45
0.540
46
0.550
47
0.550
48
1,690,000
49
Apr 01, 2019
['2019-04-01', '0.550', '0.560', '0.540', '0.550', '0.550', '1,490,000']
50
0.550
51
0.560
52
0.540
53
0.550
54
0.550
55
1,490,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8521.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.245', '0.255', '0.245', '0.255', '0.255', '340,000']
1
0.245
2
0.255
3
0.245
4
0.255
5
0.255
6
340,000
7
Apr 10, 2019
['2019-04-10', '0.250', '0.250', '0.250', '0.250', '0.250', '270,000']
8
0.250
9
0.250
10
0.250
11
0.250
12
0.250
13
270,000
14
Apr 09, 2019
['2019-04-09', '0.260', '0.260', '0.250', '0.250', '0.250', '780,000']
15
0.260
16
0.260
17
0.250
18
0.250
19
0.250
20
780,000
21
Apr 08, 2019
['2019-04-08', '0.255', '0.260', '0.255', '0.260', '0.260', '25,000']
22
0.255
23
0.260
24
0.255
25
0.260
26
0.260
27
25,000
28
Apr 04, 2019
['2019-04-04', '0.260', '0.260', '0.260', '0.260', '0.260', '-']
29
0.260
30
0.260
31
0.260
32
0.260
33
0.260
34
-
35
Apr 03, 2019
['2019-04-03', '0.260', '0.260', '0.260', '0.260', '0.260', '110,000']
36
0.260
37
0.260
38
0.260
39
0.260
40
0.260
41
110,000
42
Apr 02, 2019
['2019-04-02', '0.255', '0.260', '0.250', '0.260', '0.260', '2,010,000']
43
0.255
44
0.260
45
0.250
46
0.260
47
0.260
48
2,010,000
49
Apr 01, 2019
['2019-04-01', '0.260', '0.270', '0.255', '0.270', '0.270', '375,000']
50
0.260
51
0.270
52
0.255
53
0.270
54
0.270
55
375,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8105.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.630', '0.630', '0.600', '0.620', '0.620', '465,000']
1
0.630
2
0.630
3
0.600
4
0.620
5
0.620
6
465,000
7
Apr 10, 2019
['2019-04-10', '0.630', '0.630', '0.600', '0.620', '0.620', '595,000']
8
0.630
9
0.630
10
0.600
11
0.620
12
0.620
13
595,000
14
Apr 09, 2019
['2019-04-09', '0.630', '0.640', '0.610', '0.620', '0.620', '550,000']
15
0.630
16
0.640
17
0.610
18
0.620
19
0.620
20
550,000
21
Apr 08, 2019
['2019-04-08', '0.640', '0.670', '0.600', '0.620', '0.620', '5,450,000']
22
0.640
23
0.670
24
0.600
25
0.620
26
0.620
27
5,450,000
28
Apr 04, 2019
['2019-04-04', '0.630', '0.640', '0.600', '0.620', '0.620', '970,000']
29
0.630
30
0.640
31
0.600
32
0.620
33
0.620
34
970,000
35
Apr 03, 2019
['2019-04-03', '0.640', '0.640', '0.610', '0.640', '0.640', '1,165,000']
36
0.640
37
0.640
38
0.610
39
0.640
40
0.640
41
1,165,000
42
Apr 02, 2019
['2019-04-02', '0.580', '0.650', '0.540', '0.640', '0.640', '22,345,000']
43
0.580
44
0.650
45
0.540
46
0.640
47
0.640
48
22,345,000
49
Apr 01, 2019
['2019-04-01', '0.620', '0.680', '0.520', '0.600', '0.600', '5,110,000']
50
0.620
51
0.680
52
0.520
53
0.600
54
0.600
55
5,110,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2119.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.760', '1.890', '1.760', '1.830', '1.830', '9,620,000']
1
1.760
2
1.890
3
1.760
4
1.830
5
1.830
6
9,620,000
7
Apr 10, 2019
['2019-04-10', '1.720', '1.760', '1.710', '1.750', '1.750', '1,452,000']
8
1.720
9
1.760
10
1.710
11
1.750
12
1.750
13
1,452,000
14
Apr 09, 2019
['2019-04-09', '1.690', '1.770', '1.690', '1.730', '1.730', '3,346,000']
15
1.690
16
1.770
17
1.690
18
1.730
19
1.730
20
3,346,000
21
Apr 08, 2019
['2019-04-08', '1.680', '1.700', '1.660', '1.690', '1.690', '1,000,000']
22
1.680
23
1.700
24
1.660
25
1.690
26
1.690
27
1,000,000
28
Apr 04, 2019
['2019-04-04', '1.670', '1.690', '1.670', '1.680', '1.680', '882,000']
29
1.670
30
1.690
31
1.670
32
1.680
33
1.680
34
882,000
35
Apr 03, 2019
['2019-04-03', '1.690', '1.690', '1.640', '1.670', '1.670', '1,176,001']
36
1.690
37
1.690
38
1.640
39
1.670
40
1.670
41
1,176,001
42
Apr 02, 2019
['2019-04-02', '1.690', '1.690', '1.650', '1.680', '1.680', '1,124,000']
43
1.690
44
1.690
45
1.650
46
1.680
47
1.680
48
1,124,000
49
Apr 01, 2019
['2019-04-01', '1.680', '1.720', '1.650', '1.690', '1.690', '2,098,000']
50
1.680
51
1.720
52
1.650
53
1.690
54
1.690
55
2,098,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8391.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.171', '0.176', '0.171', '0.176', '0.176', '744,000']
1
0.171
2
0.176
3
0.171
4
0.176
5
0.176
6
744,000
7
Apr 10, 2019
['2019-04-10', '0.174', '0.177', '0.172', '0.177', '0.177', '896,000']
8
0.174
9
0.177
10
0.172
11
0.177
12
0.177
13
896,000
14
Apr 09, 2019
['2019-04-09', '0.180', '0.180', '0.165', '0.173', '0.173', '3,268,000']
15
0.180
16
0.180
17
0.165
18
0.173
19
0.173
20
3,268,000
21
Apr 08, 2019
['2019-04-08', '0.222', '0.222', '0.175', '0.181', '0.181', '5,700,000']
22
0.222
23
0.222
24
0.175
25
0.181
26
0.181
27
5,700,000
28
Apr 04, 2019
['2019-04-04', '0.151', '0.265', '0.151', '0.204', '0.204', '27,888,000']
29
0.151
30
0.265
31
0.151
32
0.204
33
0.204
34
27,888,000
35
Apr 03, 2019
['2019-04-03', '0.153', '0.158', '0.150', '0.153', '0.153', '2,728,000']
36
0.153
37
0.158
38
0.150
39
0.153
40
0.153
41
2,728,000
42
Apr 02, 2019
['2019-04-02', '0.155', '0.155', '0.153', '0.153', '0.153', '40,000']
43
0.155
44
0.155
45
0.153
46
0.153
47
0.153
48
40,000
49
Apr 01, 2019
['2019-04-01', '0.165', '0.173', '0.150', '0.154', '0.154', '996,000']
50
0.165
51
0.173
52
0.150
53
0.154
54
0.154
55
996,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1752.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.355', '0.355', '0.350', '0.350', '0.350', '1,900,000']
1
0.355
2
0.355
3
0.350
4
0.350
5
0.350
6
1,900,000
7
Apr 10, 2019
['2019-04-10', '0.360', '0.360', '0.355', '0.355', '0.355', '2,090,000']
8
0.360
9
0.360
10
0.355
11
0.355
12
0.355
13
2,090,000
14
Apr 09, 2019
['2019-04-09', '0.370', '0.370', '0.360', '0.365', '0.365', '1,220,000']
15
0.370
16
0.370
17
0.360
18
0.365
19
0.365
20
1,220,000
21
Apr 08, 2019
['2019-04-08', '0.380', '0.380', '0.370', '0.375', '0.375', '1,310,000']
22
0.380
23
0.380
24
0.370
25
0.375
26
0.375
27
1,310,000
28
Apr 04, 2019
['2019-04-04', '0.375', '0.380', '0.365', '0.375', '0.375', '2,790,000']
29
0.375
30
0.380
31
0.365
32
0.375
33
0.375
34
2,790,000
35
Apr 03, 2019
['2019-04-03', '0.370', '0.370', '0.360', '0.365', '0.365', '1,270,000']
36
0.370
37
0.370
38
0.360
39
0.365
40
0.365
41
1,270,000
42
Apr 02, 2019
['2019-04-02', '0.370', '0.370', '0.360', '0.365', '0.365', '1,630,000']
43
0.370
44
0.370
45
0.360
46
0.365
47
0.365
48
1,630,000
49
Apr 01, 2019
['2019-04-01', '0.355', '0.375', '0.355', '0.370', '0.370', '2,060,000']
50
0.355
51
0.375
52
0.355
53
0.370
54
0.370
55
2,060,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1742.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.216', '0.235', '0.216', '0.234', '0.234', '125,000']
1
0.216
2
0.235
3
0.216
4
0.234
5
0.234
6
125,000
7
Apr 10, 2019
['2019-04-10', '0.229', '0.235', '0.220', '0.224', '0.224', '940,000']
8
0.229
9
0.235
10
0.220
11
0.224
12
0.224
13
940,000
14
Apr 09, 2019
['2019-04-09', '0.230', '0.231', '0.222', '0.229', '0.229', '455,000']
15
0.230
16
0.231
17
0.222
18
0.229
19
0.229
20
455,000
21
Apr 08, 2019
['2019-04-08', '0.228', '0.228', '0.223', '0.230', '0.230', '1,030,000']
22
0.228
23
0.228
24
0.223
25
0.230
26
0.230
27
1,030,000
28
Apr 04, 2019
['2019-04-04', '0.231', '0.239', '0.228', '0.238', '0.238', '575,000']
29
0.231
30
0.239
31
0.228
32
0.238
33
0.238
34
575,000
35
Apr 03, 2019
['2019-04-03', '0.232', '0.235', '0.230', '0.234', '0.234', '380,000']
36
0.232
37
0.235
38
0.230
39
0.234
40
0.234
41
380,000
42
Apr 02, 2019
['2019-04-02', '0.231', '0.242', '0.231', '0.241', '0.241', '4,395,000']
43
0.231
44
0.242
45
0.231
46
0.241
47
0.241
48
4,395,000
49
Apr 01, 2019
['2019-04-01', '0.238', '0.238', '0.238', '0.245', '0.245', '10,000']
50
0.238
51
0.238
52
0.238
53
0.245
54
0.245
55
10,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1750.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.300', '0.305', '0.300', '0.305', '0.305', '4,420,000']
1
0.300
2
0.305
3
0.300
4
0.305
5
0.305
6
4,420,000
7
Apr 10, 2019
['2019-04-10', '0.305', '0.305', '0.295', '0.300', '0.300', '5,970,000']
8
0.305
9
0.305
10
0.295
11
0.300
12
0.300
13
5,970,000
14
Apr 09, 2019
['2019-04-09', '0.305', '0.315', '0.285', '0.305', '0.305', '6,570,000']
15
0.305
16
0.315
17
0.285
18
0.305
19
0.305
20
6,570,000
21
Apr 08, 2019
['2019-04-08', '0.315', '0.325', '0.300', '0.310', '0.310', '8,750,000']
22
0.315
23
0.325
24
0.300
25
0.310
26
0.310
27
8,750,000
28
Apr 04, 2019
['2019-04-04', '0.325', '0.330', '0.305', '0.315', '0.315', '11,250,000']
29
0.325
30
0.330
31
0.305
32
0.315
33
0.315
34
11,250,000
35
Apr 03, 2019
['2019-04-03', '0.290', '0.330', '0.290', '0.320', '0.320', '33,400,000']
36
0.290
37
0.330
38
0.290
39
0.320
40
0.320
41
33,400,000
42
Apr 02, 2019
['2019-04-02', '0.280', '0.290', '0.280', '0.285', '0.285', '6,200,000']
43
0.280
44
0.290
45
0.280
46
0.285
47
0.285
48
6,200,000
49
Apr 01, 2019
['2019-04-01', '0.290', '0.290', '0.265', '0.275', '0.275', '3,720,000']
50
0.290
51
0.290
52
0.265
53
0.275
54
0.275
55
3,720,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8527.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.310', '2.310', '2.310', '2.310', '2.310', '-']
1
2.310
2
2.310
3
2.310
4
2.310
5
2.310
6
-
7
Apr 10, 2019
['2019-04-10', '2.320', '2.320', '2.320', '2.320', '2.320', '-']
8
2.320
9
2.320
10
2.320
11
2.320
12
2.320
13
-
14
Apr 09, 2019
['2019-04-09', '2.320', '2.320', '2.320', '2.320', '2.320', '-']
15
2.320
16
2.320
17
2.320
18
2.320
19
2.320
20
-
21
Apr 08, 2019
['2019-04-08', '2.190', '2.300', '2.190', '2.290', '2.290', '100,000']
22
2.190
23
2.300
24
2.190
25
2.290
26
2.290
27
100,000
28
Apr 04, 2019
['2019-04-04', '2.120', '2.120', '2.120', '2.120', '2.120', '20,000']
29
2.120
30
2.120
31
2.120
32
2.120
33
2.120
34
20,000
35
Apr 03, 2019
['2019-04-03', '2.120', '2.180', '2.050', '2.070', '2.070', '2,465,000']
36
2.120
37
2.180
38
2.050
39
2.070
40
2.070
41
2,465,000
42
Apr 02, 2019
['2019-04-02', '2.180', '2.180', '2.180', '2.180', '2.180', '-']
43
2.180
44
2.180
45
2.180
46
2.180
47
2.180
48
-
49
Apr 01, 2019
['2019-04-01', '2.190', '2.200', '2.190', '2.200', '2.200', '25,000']
50
2.190
51
2.200
52
2.190
53
2.200
54
2.200
55
25,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8107.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.112', '0.112', '0.112', '0.112', '0.112', '-']
1
0.112
2
0.112
3
0.112
4
0.112
5
0.112
6
-
7
Apr 10, 2019
['2019-04-10', '0.112', '0.112', '0.112', '0.112', '0.112', '-']
8
0.112
9
0.112
10
0.112
11
0.112
12
0.112
13
-
14
Apr 09, 2019
['2019-04-09', '0.113', '0.113', '0.108', '0.112', '0.112', '200,000']
15
0.113
16
0.113
17
0.108
18
0.112
19
0.112
20
200,000
21
Apr 08, 2019
['2019-04-08', '0.111', '0.111', '0.110', '0.110', '0.110', '48,000']
22
0.111
23
0.111
24
0.110
25
0.110
26
0.110
27
48,000
28
Apr 04, 2019
['2019-04-04', '0.109', '0.116', '0.109', '0.116', '0.116', '60,000']
29
0.109
30
0.116
31
0.109
32
0.116
33
0.116
34
60,000
35
Apr 03, 2019
['2019-04-03', '0.110', '0.116', '0.110', '0.116', '0.116', '1,070,000']
36
0.110
37
0.116
38
0.110
39
0.116
40
0.116
41
1,070,000
42
Apr 02, 2019
['2019-04-02', '0.113', '0.113', '0.110', '0.112', '0.112', '610,000']
43
0.113
44
0.113
45
0.110
46
0.112
47
0.112
48
610,000
49
Apr 01, 2019
['2019-04-01', '0.109', '0.110', '0.109', '0.110', '0.110', '250,000']
50
0.109
51
0.110
52
0.109
53
0.110
54
0.110
55
250,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1833.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '45.400', '45.500', '42.750', '43.300', '43.300', '2,899,892']
1
45.400
2
45.500
3
42.750
4
43.300
5
43.300
6
2,899,892
7
Apr 10, 2019
['2019-04-10', '44.350', '45.250', '43.400', '44.950', '44.950', '2,547,353']
8
44.350
9
45.250
10
43.400
11
44.950
12
44.950
13
2,547,353
14
Apr 09, 2019
['2019-04-09', '42.700', '44.200', '42.500', '44.150', '44.150', '1,534,047']
15
42.700
16
44.200
17
42.500
18
44.150
19
44.150
20
1,534,047
21
Apr 08, 2019
['2019-04-08', '42.300', '42.800', '42.000', '42.500', '42.500', '593,400']
22
42.300
23
42.800
24
42.000
25
42.500
26
42.500
27
593,400
28
Apr 04, 2019
['2019-04-04', '43.250', '43.950', '41.800', '42.050', '42.050', '2,050,415']
29
43.250
30
43.950
31
41.800
32
42.050
33
42.050
34
2,050,415
35
Apr 03, 2019
['2019-04-03', '44.600', '44.600', '43.000', '43.000', '43.000', '1,519,718']
36
44.600
37
44.600
38
43.000
39
43.000
40
43.000
41
1,519,718
42
Apr 02, 2019
['2019-04-02', '45.550', '45.550', '43.800', '43.950', '43.950', '1,029,280']
43
45.550
44
45.550
45
43.800
46
43.950
47
43.950
48
1,029,280
49
Apr 01, 2019
['2019-04-01', '45.150', '45.450', '43.650', '43.900', '43.900', '2,028,300']
50
45.150
51
45.450
52
43.650
53
43.900
54
43.900
55
2,028,300
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1671.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.160', '3.340', '3.060', '3.210', '3.210', '10,206,000']
1
3.160
2
3.340
3
3.060
4
3.210
5
3.210
6
10,206,000
7
Apr 10, 2019
['2019-04-10', '2.890', '3.300', '2.800', '3.170', '3.170', '9,780,000']
8
2.890
9
3.300
10
2.800
11
3.170
12
3.170
13
9,780,000
14
Apr 09, 2019
['2019-04-09', '2.730', '2.920', '2.660', '2.890', '2.890', '3,190,000']
15
2.730
16
2.920
17
2.660
18
2.890
19
2.890
20
3,190,000
21
Apr 08, 2019
['2019-04-08', '2.440', '2.750', '2.390', '2.730', '2.730', '3,872,000']
22
2.440
23
2.750
24
2.390
25
2.730
26
2.730
27
3,872,000
28
Apr 04, 2019
['2019-04-04', '2.350', '2.450', '2.280', '2.420', '2.420', '2,944,000']
29
2.350
30
2.450
31
2.280
32
2.420
33
2.420
34
2,944,000
35
Apr 03, 2019
['2019-04-03', '2.260', '2.370', '2.210', '2.340', '2.340', '2,092,000']
36
2.260
37
2.370
38
2.210
39
2.340
40
2.340
41
2,092,000
42
Apr 02, 2019
['2019-04-02', '2.160', '2.350', '2.130', '2.260', '2.260', '2,798,000']
43
2.160
44
2.350
45
2.130
46
2.260
47
2.260
48
2,798,000
49
Apr 01, 2019
['2019-04-01', '2.200', '2.260', '2.100', '2.170', '2.170', '2,910,000']
50
2.200
51
2.260
52
2.100
53
2.170
54
2.170
55
2,910,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8151.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.181', '0.181', '0.181', '0.186', '0.186', '155,000']
1
0.181
2
0.181
3
0.181
4
0.186
5
0.186
6
155,000
7
Apr 10, 2019
['2019-04-10', '0.184', '0.184', '0.184', '0.184', '0.184', '-']
8
0.184
9
0.184
10
0.184
11
0.184
12
0.184
13
-
14
Apr 09, 2019
['2019-04-09', '0.186', '0.187', '0.185', '0.187', '0.187', '195,000']
15
0.186
16
0.187
17
0.185
18
0.187
19
0.187
20
195,000
21
Apr 08, 2019
['2019-04-08', '0.195', '0.196', '0.195', '0.196', '0.196', '110,000']
22
0.195
23
0.196
24
0.195
25
0.196
26
0.196
27
110,000
28
Apr 04, 2019
['2019-04-04', '0.193', '0.193', '0.193', '0.193', '0.193', '50,000']
29
0.193
30
0.193
31
0.193
32
0.193
33
0.193
34
50,000
35
Apr 03, 2019
['2019-04-03', '0.190', '0.190', '0.190', '0.190', '0.190', '40,000']
36
0.190
37
0.190
38
0.190
39
0.190
40
0.190
41
40,000
42
Apr 02, 2019
['2019-04-02', '0.185', '0.193', '0.185', '0.193', '0.193', '795,000']
43
0.185
44
0.193
45
0.185
46
0.193
47
0.193
48
795,000
49
Apr 01, 2019
['2019-04-01', '0.190', '0.190', '0.190', '0.190', '0.190', '35,000']
50
0.190
51
0.190
52
0.190
53
0.190
54
0.190
55
35,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8511.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.205', '0.205', '0.205', '0.205', '0.205', '-']
1
0.205
2
0.205
3
0.205
4
0.205
5
0.205
6
-
7
Apr 10, 2019
['2019-04-10', '0.183', '0.205', '0.190', '0.205', '0.205', '120,000']
8
0.183
9
0.205
10
0.190
11
0.205
12
0.205
13
120,000
14
Apr 09, 2019
['2019-04-09', '0.197', '0.204', '0.196', '0.201', '0.201', '400,000']
15
0.197
16
0.204
17
0.196
18
0.201
19
0.201
20
400,000
21
Apr 08, 2019
['2019-04-08', '0.198', '0.210', '0.198', '0.210', '0.210', '92,000']
22
0.198
23
0.210
24
0.198
25
0.210
26
0.210
27
92,000
28
Apr 04, 2019
['2019-04-04', '0.210', '0.210', '0.210', '0.210', '0.210', '-']
29
0.210
30
0.210
31
0.210
32
0.210
33
0.210
34
-
35
Apr 03, 2019
['2019-04-03', '0.210', '0.210', '0.210', '0.210', '0.210', '-']
36
0.210
37
0.210
38
0.210
39
0.210
40
0.210
41
-
42
Apr 02, 2019
['2019-04-02', '0.216', '0.216', '0.204', '0.210', '0.210', '24,000']
43
0.216
44
0.216
45
0.204
46
0.210
47
0.210
48
24,000
49
Apr 01, 2019
['2019-04-01', '0.206', '0.206', '0.206', '0.206', '0.206', '28,000']
50
0.206
51
0.206
52
0.206
53
0.206
54
0.206
55
28,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1726.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.330', '0.380', '0.320', '0.345', '0.345', '5,570,000']
1
0.330
2
0.380
3
0.320
4
0.345
5
0.345
6
5,570,000
7
Apr 10, 2019
['2019-04-10', '0.310', '0.325', '0.305', '0.320', '0.320', '3,145,000']
8
0.310
9
0.325
10
0.305
11
0.320
12
0.320
13
3,145,000
14
Apr 09, 2019
['2019-04-09', '0.310', '0.320', '0.310', '0.310', '0.310', '185,000']
15
0.310
16
0.320
17
0.310
18
0.310
19
0.310
20
185,000
21
Apr 08, 2019
['2019-04-08', '0.310', '0.320', '0.305', '0.320', '0.320', '375,000']
22
0.310
23
0.320
24
0.305
25
0.320
26
0.320
27
375,000
28
Apr 04, 2019
['2019-04-04', '0.320', '0.320', '0.310', '0.320', '0.320', '460,000']
29
0.320
30
0.320
31
0.310
32
0.320
33
0.320
34
460,000
35
Apr 03, 2019
['2019-04-03', '0.310', '0.320', '0.310', '0.315', '0.315', '1,240,000']
36
0.310
37
0.320
38
0.310
39
0.315
40
0.315
41
1,240,000
42
Apr 02, 2019
['2019-04-02', '0.315', '0.330', '0.315', '0.315', '0.315', '1,285,000']
43
0.315
44
0.330
45
0.315
46
0.315
47
0.315
48
1,285,000
49
Apr 01, 2019
['2019-04-01', '0.305', '0.320', '0.305', '0.315', '0.315', '320,000']
50
0.305
51
0.320
52
0.305
53
0.315
54
0.315
55
320,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8451.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.103', '0.103', '0.096', '0.097', '0.097', '120,000']
1
0.103
2
0.103
3
0.096
4
0.097
5
0.097
6
120,000
7
Apr 10, 2019
['2019-04-10', '0.103', '0.103', '0.103', '0.103', '0.103', '-']
8
0.103
9
0.103
10
0.103
11
0.103
12
0.103
13
-
14
Apr 09, 2019
['2019-04-09', '0.105', '0.111', '0.105', '0.106', '0.106', '330,000']
15
0.105
16
0.111
17
0.105
18
0.106
19
0.106
20
330,000
21
Apr 08, 2019
['2019-04-08', '0.105', '0.105', '0.105', '0.105', '0.105', '-']
22
0.105
23
0.105
24
0.105
25
0.105
26
0.105
27
-
28
Apr 04, 2019
['2019-04-04', '0.103', '0.106', '0.098', '0.106', '0.106', '450,000']
29
0.103
30
0.106
31
0.098
32
0.106
33
0.106
34
450,000
35
Apr 03, 2019
['2019-04-03', '0.108', '0.108', '0.108', '0.108', '0.108', '-']
36
0.108
37
0.108
38
0.108
39
0.108
40
0.108
41
-
42
Apr 02, 2019
['2019-04-02', '0.100', '0.109', '0.100', '0.108', '0.108', '1,590,000']
43
0.100
44
0.109
45
0.100
46
0.108
47
0.108
48
1,590,000
49
Apr 01, 2019
['2019-04-01', '0.109', '0.109', '0.109', '0.109', '0.109', '-']
50
0.109
51
0.109
52
0.109
53
0.109
54
0.109
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8507.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.170', '0.170', '0.165', '0.167', '0.167', '716,000']
1
0.170
2
0.170
3
0.165
4
0.167
5
0.167
6
716,000
7
Apr 10, 2019
['2019-04-10', '0.180', '0.180', '0.166', '0.170', '0.170', '740,000']
8
0.180
9
0.180
10
0.166
11
0.170
12
0.170
13
740,000
14
Apr 09, 2019
['2019-04-09', '0.172', '0.176', '0.165', '0.176', '0.176', '960,000']
15
0.172
16
0.176
17
0.165
18
0.176
19
0.176
20
960,000
21
Apr 08, 2019
['2019-04-08', '0.172', '0.172', '0.172', '0.172', '0.172', '4,000']
22
0.172
23
0.172
24
0.172
25
0.172
26
0.172
27
4,000
28
Apr 04, 2019
['2019-04-04', '0.180', '0.180', '0.172', '0.172', '0.172', '96,000']
29
0.180
30
0.180
31
0.172
32
0.172
33
0.172
34
96,000
35
Apr 03, 2019
['2019-04-03', '0.175', '0.183', '0.175', '0.182', '0.182', '432,000']
36
0.175
37
0.183
38
0.175
39
0.182
40
0.182
41
432,000
42
Apr 02, 2019
['2019-04-02', '0.175', '0.175', '0.175', '0.175', '0.175', '400,000']
43
0.175
44
0.175
45
0.175
46
0.175
47
0.175
48
400,000
49
Apr 01, 2019
['2019-04-01', '0.177', '0.177', '0.151', '0.175', '0.175', '564,000']
50
0.177
51
0.177
52
0.151
53
0.175
54
0.175
55
564,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8241.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.255', '0.255', '0.255', '0.255', '0.255', '90,000']
1
0.255
2
0.255
3
0.255
4
0.255
5
0.255
6
90,000
7
Apr 10, 2019
['2019-04-10', '0.244', '0.260', '0.244', '0.255', '0.255', '255,000']
8
0.244
9
0.260
10
0.244
11
0.255
12
0.255
13
255,000
14
Apr 09, 2019
['2019-04-09', '0.240', '0.247', '0.240', '0.247', '0.247', '10,000']
15
0.240
16
0.247
17
0.240
18
0.247
19
0.247
20
10,000
21
Apr 08, 2019
['2019-04-08', '0.240', '0.240', '0.240', '0.240', '0.240', '-']
22
0.240
23
0.240
24
0.240
25
0.240
26
0.240
27
-
28
Apr 04, 2019
['2019-04-04', '0.250', '0.250', '0.235', '0.240', '0.240', '135,000']
29
0.250
30
0.250
31
0.235
32
0.240
33
0.240
34
135,000
35
Apr 03, 2019
['2019-04-03', '0.244', '0.244', '0.244', '0.244', '0.244', '-']
36
0.244
37
0.244
38
0.244
39
0.244
40
0.244
41
-
42
Apr 02, 2019
['2019-04-02', '0.245', '0.255', '0.235', '0.255', '0.255', '175,000']
43
0.245
44
0.255
45
0.235
46
0.255
47
0.255
48
175,000
49
Apr 01, 2019
['2019-04-01', '0.233', '0.250', '0.233', '0.250', '0.250', '10,000']
50
0.233
51
0.250
52
0.233
53
0.250
54
0.250
55
10,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8447.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.099', '0.099', '0.099', '0.099', '0.099', '-']
1
0.099
2
0.099
3
0.099
4
0.099
5
0.099
6
-
7
Apr 10, 2019
['2019-04-10', '0.093', '0.098', '0.092', '0.098', '0.098', '340,000']
8
0.093
9
0.098
10
0.092
11
0.098
12
0.098
13
340,000
14
Apr 09, 2019
['2019-04-09', '0.103', '0.103', '0.103', '0.102', '0.102', '30,000']
15
0.103
16
0.103
17
0.103
18
0.102
19
0.102
20
30,000
21
Apr 08, 2019
['2019-04-08', '0.102', '0.103', '0.102', '0.103', '0.103', '70,000']
22
0.102
23
0.103
24
0.102
25
0.103
26
0.103
27
70,000
28
Apr 04, 2019
['2019-04-04', '0.099', '0.101', '0.099', '0.101', '0.101', '130,000']
29
0.099
30
0.101
31
0.099
32
0.101
33
0.101
34
130,000
35
Apr 03, 2019
['2019-04-03', '0.100', '0.100', '0.087', '0.097', '0.097', '1,580,000']
36
0.100
37
0.100
38
0.087
39
0.097
40
0.097
41
1,580,000
42
Apr 02, 2019
['2019-04-02', '0.112', '0.114', '0.091', '0.100', '0.100', '6,070,000']
43
0.112
44
0.114
45
0.091
46
0.100
47
0.100
48
6,070,000
49
Apr 01, 2019
['2019-04-01', '0.115', '0.115', '0.103', '0.115', '0.115', '340,000']
50
0.115
51
0.115
52
0.103
53
0.115
54
0.115
55
340,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8372.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.124', '0.124', '0.116', '0.116', '0.116', '460,000']
1
0.124
2
0.124
3
0.116
4
0.116
5
0.116
6
460,000
7
Apr 10, 2019
['2019-04-10', '0.123', '0.124', '0.123', '0.124', '0.124', '50,000']
8
0.123
9
0.124
10
0.123
11
0.124
12
0.124
13
50,000
14
Apr 09, 2019
['2019-04-09', '0.131', '0.135', '0.131', '0.131', '0.131', '200,000']
15
0.131
16
0.135
17
0.131
18
0.131
19
0.131
20
200,000
21
Apr 08, 2019
['2019-04-08', '0.131', '0.131', '0.131', '0.131', '0.131', '-']
22
0.131
23
0.131
24
0.131
25
0.131
26
0.131
27
-
28
Apr 04, 2019
['2019-04-04', '0.131', '0.131', '0.131', '0.131', '0.131', '-']
29
0.131
30
0.131
31
0.131
32
0.131
33
0.131
34
-
35
Apr 03, 2019
['2019-04-03', '0.118', '0.133', '0.118', '0.132', '0.132', '490,000']
36
0.118
37
0.133
38
0.118
39
0.132
40
0.132
41
490,000
42
Apr 02, 2019
['2019-04-02', '0.119', '0.119', '0.118', '0.118', '0.118', '103,000']
43
0.119
44
0.119
45
0.118
46
0.118
47
0.118
48
103,000
49
Apr 01, 2019
['2019-04-01', '0.118', '0.120', '0.116', '0.117', '0.117', '460,000']
50
0.118
51
0.120
52
0.116
53
0.117
54
0.117
55
460,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1735.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.980', '1.980', '1.960', '1.960', '1.960', '1,064,000']
1
1.980
2
1.980
3
1.960
4
1.960
5
1.960
6
1,064,000
7
Apr 10, 2019
['2019-04-10', '1.970', '1.970', '1.950', '1.990', '1.990', '4,006,000']
8
1.970
9
1.970
10
1.950
11
1.990
12
1.990
13
4,006,000
14
Apr 09, 2019
['2019-04-09', '2.010', '2.090', '1.950', '1.990', '1.990', '42,000']
15
2.010
16
2.090
17
1.950
18
1.990
19
1.990
20
42,000
21
Apr 08, 2019
['2019-04-08', '2.010', '2.010', '2.010', '2.010', '2.010', '2,000']
22
2.010
23
2.010
24
2.010
25
2.010
26
2.010
27
2,000
28
Apr 04, 2019
['2019-04-04', '2.080', '2.170', '1.970', '2.110', '2.110', '36,000']
29
2.080
30
2.170
31
1.970
32
2.110
33
2.110
34
36,000
35
Apr 03, 2019
['2019-04-03', '2.050', '2.120', '1.950', '2.100', '2.100', '98,000']
36
2.050
37
2.120
38
1.950
39
2.100
40
2.100
41
98,000
42
Apr 02, 2019
['2019-04-02', '2.150', '2.150', '1.960', '2.140', '2.140', '26,000']
43
2.150
44
2.150
45
1.960
46
2.140
47
2.140
48
26,000
49
Apr 01, 2019
['2019-04-01', '2.180', '2.180', '2.150', '2.150', '2.150', '22,000']
50
2.180
51
2.180
52
2.150
53
2.150
54
2.150
55
22,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8401.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.990', '0.990', '0.940', '0.970', '0.970', '30,000']
1
0.990
2
0.990
3
0.940
4
0.970
5
0.970
6
30,000
7
Apr 10, 2019
['2019-04-10', '0.970', '0.990', '0.950', '0.950', '0.950', '160,000']
8
0.970
9
0.990
10
0.950
11
0.950
12
0.950
13
160,000
14
Apr 09, 2019
['2019-04-09', '0.960', '1.000', '0.960', '0.990', '0.990', '378,000']
15
0.960
16
1.000
17
0.960
18
0.990
19
0.990
20
378,000
21
Apr 08, 2019
['2019-04-08', '0.990', '1.000', '0.970', '1.000', '1.000', '1,722,000']
22
0.990
23
1.000
24
0.970
25
1.000
26
1.000
27
1,722,000
28
Apr 04, 2019
['2019-04-04', '0.930', '0.990', '0.930', '0.990', '0.990', '1,556,000']
29
0.930
30
0.990
31
0.930
32
0.990
33
0.990
34
1,556,000
35
Apr 03, 2019
['2019-04-03', '0.930', '0.960', '0.930', '0.960', '0.960', '76,000']
36
0.930
37
0.960
38
0.930
39
0.960
40
0.960
41
76,000
42
Apr 02, 2019
['2019-04-02', '0.920', '0.960', '0.920', '0.960', '0.960', '230,000']
43
0.920
44
0.960
45
0.920
46
0.960
47
0.960
48
230,000
49
Apr 01, 2019
['2019-04-01', '0.930', '0.960', '0.910', '0.960', '0.960', '226,000']
50
0.930
51
0.960
52
0.910
53
0.960
54
0.960
55
226,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8448.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.073', '0.073', '0.073', '0.073', '0.073', '100,000']
1
0.073
2
0.073
3
0.073
4
0.073
5
0.073
6
100,000
7
Apr 10, 2019
['2019-04-10', '0.073', '0.073', '0.073', '0.073', '0.073', '120,000']
8
0.073
9
0.073
10
0.073
11
0.073
12
0.073
13
120,000
14
Apr 09, 2019
['2019-04-09', '0.072', '0.072', '0.072', '0.072', '0.072', '-']
15
0.072
16
0.072
17
0.072
18
0.072
19
0.072
20
-
21
Apr 08, 2019
['2019-04-08', '0.072', '0.072', '0.072', '0.072', '0.072', '-']
22
0.072
23
0.072
24
0.072
25
0.072
26
0.072
27
-
28
Apr 04, 2019
['2019-04-04', '0.078', '0.078', '0.074', '0.075', '0.075', '500,000']
29
0.078
30
0.078
31
0.074
32
0.075
33
0.075
34
500,000
35
Apr 03, 2019
['2019-04-03', '0.069', '0.080', '0.069', '0.078', '0.078', '5,240,000']
36
0.069
37
0.080
38
0.069
39
0.078
40
0.078
41
5,240,000
42
Apr 02, 2019
['2019-04-02', '0.071', '0.071', '0.071', '0.071', '0.071', '-']
43
0.071
44
0.071
45
0.071
46
0.071
47
0.071
48
-
49
Apr 01, 2019
['2019-04-01', '0.068', '0.071', '0.068', '0.071', '0.071', '1,340,000']
50
0.068
51
0.071
52
0.068
53
0.071
54
0.071
55
1,340,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1716.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.200', '1.240', '1.180', '1.190', '1.190', '440,000']
1
1.200
2
1.240
3
1.180
4
1.190
5
1.190
6
440,000
7
Apr 10, 2019
['2019-04-10', '1.170', '1.290', '1.170', '1.220', '1.220', '1,560,000']
8
1.170
9
1.290
10
1.170
11
1.220
12
1.220
13
1,560,000
14
Apr 09, 2019
['2019-04-09', '1.170', '1.200', '1.170', '1.180', '1.180', '106,000']
15
1.170
16
1.200
17
1.170
18
1.180
19
1.180
20
106,000
21
Apr 08, 2019
['2019-04-08', '1.170', '1.200', '1.170', '1.190', '1.190', '186,000']
22
1.170
23
1.200
24
1.170
25
1.190
26
1.190
27
186,000
28
Apr 04, 2019
['2019-04-04', '1.160', '1.180', '1.160', '1.170', '1.170', '134,000']
29
1.160
30
1.180
31
1.160
32
1.170
33
1.170
34
134,000
35
Apr 03, 2019
['2019-04-03', '1.190', '1.200', '1.170', '1.180', '1.180', '154,000']
36
1.190
37
1.200
38
1.170
39
1.180
40
1.180
41
154,000
42
Apr 02, 2019
['2019-04-02', '1.170', '1.190', '1.160', '1.180', '1.180', '38,000']
43
1.170
44
1.190
45
1.160
46
1.180
47
1.180
48
38,000
49
Apr 01, 2019
['2019-04-01', '1.190', '1.200', '1.160', '1.180', '1.180', '212,000']
50
1.190
51
1.200
52
1.160
53
1.180
54
1.180
55
212,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2116.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.485', '0.500', '0.485', '0.500', '0.500', '84,000']
1
0.485
2
0.500
3
0.485
4
0.500
5
0.500
6
84,000
7
Apr 10, 2019
['2019-04-10', '0.485', '0.500', '0.480', '0.500', '0.500', '180,000']
8
0.485
9
0.500
10
0.480
11
0.500
12
0.500
13
180,000
14
Apr 09, 2019
['2019-04-09', '0.500', '0.510', '0.490', '0.500', '0.500', '270,000']
15
0.500
16
0.510
17
0.490
18
0.500
19
0.500
20
270,000
21
Apr 08, 2019
['2019-04-08', '0.490', '0.510', '0.490', '0.510', '0.510', '392,000']
22
0.490
23
0.510
24
0.490
25
0.510
26
0.510
27
392,000
28
Apr 04, 2019
['2019-04-04', '0.495', '0.510', '0.480', '0.510', '0.510', '412,000']
29
0.495
30
0.510
31
0.480
32
0.510
33
0.510
34
412,000
35
Apr 03, 2019
['2019-04-03', '0.510', '0.520', '0.490', '0.510', '0.510', '456,000']
36
0.510
37
0.520
38
0.490
39
0.510
40
0.510
41
456,000
42
Apr 02, 2019
['2019-04-02', '0.495', '0.510', '0.495', '0.510', '0.510', '492,000']
43
0.495
44
0.510
45
0.495
46
0.510
47
0.510
48
492,000
49
Apr 01, 2019
['2019-04-01', '0.480', '0.540', '0.480', '0.520', '0.520', '1,038,000']
50
0.480
51
0.540
52
0.480
53
0.520
54
0.520
55
1,038,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3997.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.500', '2.500', '2.500', '2.500', '2.500', '-']
1
2.500
2
2.500
3
2.500
4
2.500
5
2.500
6
-
7
Apr 10, 2019
['2019-04-10', '2.500', '2.500', '2.500', '2.500', '2.500', '-']
8
2.500
9
2.500
10
2.500
11
2.500
12
2.500
13
-
14
Apr 09, 2019
['2019-04-09', '2.500', '2.500', '2.500', '2.500', '2.500', '-']
15
2.500
16
2.500
17
2.500
18
2.500
19
2.500
20
-
21
Apr 08, 2019
['2019-04-08', '2.500', '2.500', '2.500', '2.500', '2.500', '-']
22
2.500
23
2.500
24
2.500
25
2.500
26
2.500
27
-
28
Apr 04, 2019
['2019-04-04', '2.500', '2.500', '2.500', '2.500', '2.500', '-']
29
2.500
30
2.500
31
2.500
32
2.500
33
2.500
34
-
35
Apr 03, 2019
['2019-04-03', '2.500', '2.500', '2.500', '2.500', '2.500', '-']
36
2.500
37
2.500
38
2.500
39
2.500
40
2.500
41
-
42
Apr 02, 2019
['2019-04-02', '2.500', '2.500', '2.500', '2.500', '2.500', '-']
43
2.500
44
2.500
45
2.500
46
2.500
47
2.500
48
-
49
Apr 01, 2019
['2019-04-01', '2.500', '2.500', '2.500', '2.500', '2.500', '-']
50
2.500
51
2.500
52
2.500
53
2.500
54
2.500
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2779.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.710', '2.710', '2.630', '2.670', '2.670', '1,290,000']
1
2.710
2
2.710
3
2.630
4
2.670
5
2.670
6
1,290,000
7
Apr 10, 2019
['2019-04-10', '2.710', '2.720', '2.630', '2.710', '2.710', '2,006,000']
8
2.710
9
2.720
10
2.630
11
2.710
12
2.710
13
2,006,000
14
Apr 09, 2019
['2019-04-09', '2.760', '2.780', '2.700', '2.720', '2.720', '1,743,009']
15
2.760
16
2.780
17
2.700
18
2.720
19
2.720
20
1,743,009
21
Apr 08, 2019
['2019-04-08', '2.710', '2.810', '2.700', '2.760', '2.760', '3,725,000']
22
2.710
23
2.810
24
2.700
25
2.760
26
2.760
27
3,725,000
28
Apr 04, 2019
['2019-04-04', '2.630', '2.730', '2.630', '2.690', '2.690', '4,232,000']
29
2.630
30
2.730
31
2.630
32
2.690
33
2.690
34
4,232,000
35
Apr 03, 2019
['2019-04-03', '2.480', '2.710', '2.470', '2.610', '2.610', '4,086,000']
36
2.480
37
2.710
38
2.470
39
2.610
40
2.610
41
4,086,000
42
Apr 02, 2019
['2019-04-02', '2.530', '2.540', '2.440', '2.460', '2.460', '5,916,000']
43
2.530
44
2.540
45
2.440
46
2.460
47
2.460
48
5,916,000
49
Apr 01, 2019
['2019-04-01', '2.630', '2.650', '2.500', '2.530', '2.530', '4,529,000']
50
2.630
51
2.650
52
2.500
53
2.530
54
2.530
55
4,529,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0807.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.050', '2.060', '2.030', '2.030', '2.030', '347,000']
1
2.050
2
2.060
3
2.030
4
2.030
5
2.030
6
347,000
7
Apr 10, 2019
['2019-04-10', '2.060', '2.090', '2.020', '2.050', '2.050', '982,000']
8
2.060
9
2.090
10
2.020
11
2.050
12
2.050
13
982,000
14
Apr 09, 2019
['2019-04-09', '2.080', '2.150', '2.080', '2.100', '2.100', '3,362,000']
15
2.080
16
2.150
17
2.080
18
2.100
19
2.100
20
3,362,000
21
Apr 08, 2019
['2019-04-08', '2.100', '2.130', '2.080', '2.100', '2.100', '573,000']
22
2.100
23
2.130
24
2.080
25
2.100
26
2.100
27
573,000
28
Apr 04, 2019
['2019-04-04', '2.060', '2.100', '2.040', '2.060', '2.060', '510,000']
29
2.060
30
2.100
31
2.040
32
2.060
33
2.060
34
510,000
35
Apr 03, 2019
['2019-04-03', '2.080', '2.120', '2.040', '2.060', '2.060', '776,000']
36
2.080
37
2.120
38
2.040
39
2.060
40
2.060
41
776,000
42
Apr 02, 2019
['2019-04-02', '2.060', '2.140', '2.040', '2.070', '2.070', '1,317,000']
43
2.060
44
2.140
45
2.040
46
2.070
47
2.070
48
1,317,000
49
Apr 01, 2019
['2019-04-01', '2.030', '2.070', '2.030', '2.040', '2.040', '3,420,000']
50
2.030
51
2.070
52
2.030
53
2.040
54
2.040
55
3,420,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8168.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.105', '0.107', '0.105', '0.107', '0.107', '130,000']
1
0.105
2
0.107
3
0.105
4
0.107
5
0.107
6
130,000
7
Apr 10, 2019
['2019-04-10', '0.108', '0.108', '0.103', '0.106', '0.106', '310,000']
8
0.108
9
0.108
10
0.103
11
0.106
12
0.106
13
310,000
14
Apr 09, 2019
['2019-04-09', '0.107', '0.114', '0.107', '0.112', '0.112', '350,000']
15
0.107
16
0.114
17
0.107
18
0.112
19
0.112
20
350,000
21
Apr 08, 2019
['2019-04-08', '0.100', '0.112', '0.100', '0.110', '0.110', '2,710,000']
22
0.100
23
0.112
24
0.100
25
0.110
26
0.110
27
2,710,000
28
Apr 04, 2019
['2019-04-04', '0.111', '0.111', '0.097', '0.098', '0.098', '240,000']
29
0.111
30
0.111
31
0.097
32
0.098
33
0.098
34
240,000
35
Apr 03, 2019
['2019-04-03', '0.106', '0.114', '0.108', '0.112', '0.112', '220,000']
36
0.106
37
0.114
38
0.108
39
0.112
40
0.112
41
220,000
42
Apr 02, 2019
['2019-04-02', '0.110', '0.110', '0.110', '0.108', '0.108', '60,000']
43
0.110
44
0.110
45
0.110
46
0.108
47
0.108
48
60,000
49
Apr 01, 2019
['2019-04-01', '0.096', '0.107', '0.096', '0.107', '0.107', '540,000']
50
0.096
51
0.107
52
0.096
53
0.107
54
0.107
55
540,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6036.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.285', '0.300', '0.275', '0.300', '0.300', '5,905,000']
1
0.285
2
0.300
3
0.275
4
0.300
5
0.300
6
5,905,000
7
Apr 10, 2019
['2019-04-10', '0.285', '0.285', '0.280', '0.285', '0.285', '1,115,000']
8
0.285
9
0.285
10
0.280
11
0.285
12
0.285
13
1,115,000
14
Apr 09, 2019
['2019-04-09', '0.275', '0.280', '0.270', '0.275', '0.275', '2,215,000']
15
0.275
16
0.280
17
0.270
18
0.275
19
0.275
20
2,215,000
21
Apr 08, 2019
['2019-04-08', '0.270', '0.275', '0.270', '0.275', '0.275', '1,010,000']
22
0.270
23
0.275
24
0.270
25
0.275
26
0.275
27
1,010,000
28
Apr 04, 2019
['2019-04-04', '0.275', '0.275', '0.270', '0.270', '0.270', '245,000']
29
0.275
30
0.275
31
0.270
32
0.270
33
0.270
34
245,000
35
Apr 03, 2019
['2019-04-03', '0.270', '0.275', '0.270', '0.275', '0.275', '705,000']
36
0.270
37
0.275
38
0.270
39
0.275
40
0.275
41
705,000
42
Apr 02, 2019
['2019-04-02', '0.270', '0.275', '0.265', '0.275', '0.275', '1,015,000']
43
0.270
44
0.275
45
0.265
46
0.275
47
0.275
48
1,015,000
49
Apr 01, 2019
['2019-04-01', '0.265', '0.275', '0.265', '0.275', '0.275', '910,000']
50
0.265
51
0.275
52
0.265
53
0.275
54
0.275
55
910,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2377.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.610', '1.650', '1.610', '1.650', '1.650', '14,000']
1
1.610
2
1.650
3
1.610
4
1.650
5
1.650
6
14,000
7
Apr 10, 2019
['2019-04-10', '1.600', '1.660', '1.600', '1.640', '1.640', '186,000']
8
1.600
9
1.660
10
1.600
11
1.640
12
1.640
13
186,000
14
Apr 09, 2019
['2019-04-09', '1.650', '1.650', '1.600', '1.600', '1.600', '276,000']
15
1.650
16
1.650
17
1.600
18
1.600
19
1.600
20
276,000
21
Apr 08, 2019
['2019-04-08', '1.650', '1.680', '1.580', '1.640', '1.640', '745,000']
22
1.650
23
1.680
24
1.580
25
1.640
26
1.640
27
745,000
28
Apr 04, 2019
['2019-04-04', '1.650', '1.680', '1.640', '1.660', '1.660', '478,000']
29
1.650
30
1.680
31
1.640
32
1.660
33
1.660
34
478,000
35
Apr 03, 2019
['2019-04-03', '1.620', '1.660', '1.620', '1.660', '1.660', '18,000']
36
1.620
37
1.660
38
1.620
39
1.660
40
1.660
41
18,000
42
Apr 02, 2019
['2019-04-02', '1.630', '1.720', '1.620', '1.640', '1.640', '199,000']
43
1.630
44
1.720
45
1.620
46
1.640
47
1.640
48
199,000
49
Apr 01, 2019
['2019-04-01', '1.610', '1.680', '1.610', '1.630', '1.630', '25,000']
50
1.610
51
1.680
52
1.610
53
1.630
54
1.630
55
25,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2363.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.350', '1.350', '1.350', '1.340', '1.340', '8,753']
1
1.350
2
1.350
3
1.350
4
1.340
5
1.340
6
8,753
7
Apr 10, 2019
['2019-04-10', '1.310', '1.380', '1.310', '1.380', '1.380', '14,750']
8
1.310
9
1.380
10
1.310
11
1.380
12
1.380
13
14,750
14
Apr 09, 2019
['2019-04-09', '1.320', '1.380', '1.300', '1.360', '1.360', '85,000']
15
1.320
16
1.380
17
1.300
18
1.360
19
1.360
20
85,000
21
Apr 08, 2019
['2019-04-08', '1.230', '1.430', '1.230', '1.430', '1.430', '222,250']
22
1.230
23
1.430
24
1.230
25
1.430
26
1.430
27
222,250
28
Apr 04, 2019
['2019-04-04', '1.220', '1.250', '1.220', '1.250', '1.250', '7,250']
29
1.220
30
1.250
31
1.220
32
1.250
33
1.250
34
7,250
35
Apr 03, 2019
['2019-04-03', '1.220', '1.280', '1.210', '1.220', '1.220', '286,506']
36
1.220
37
1.280
38
1.210
39
1.220
40
1.220
41
286,506
42
Apr 02, 2019
['2019-04-02', '1.230', '1.230', '1.230', '1.230', '1.230', '13,250']
43
1.230
44
1.230
45
1.230
46
1.230
47
1.230
48
13,250
49
Apr 01, 2019
['2019-04-01', '1.240', '1.260', '1.240', '1.260', '1.260', '40,250']
50
1.240
51
1.260
52
1.240
53
1.260
54
1.260
55
40,250
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1737.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.180', '0.188', '0.177', '0.182', '0.182', '560,000']
1
0.180
2
0.188
3
0.177
4
0.182
5
0.182
6
560,000
7
Apr 10, 2019
['2019-04-10', '0.175', '0.180', '0.175', '0.180', '0.180', '180,000']
8
0.175
9
0.180
10
0.175
11
0.180
12
0.180
13
180,000
14
Apr 09, 2019
['2019-04-09', '0.181', '0.184', '0.181', '0.184', '0.184', '270,000']
15
0.181
16
0.184
17
0.181
18
0.184
19
0.184
20
270,000
21
Apr 08, 2019
['2019-04-08', '0.200', '0.200', '0.180', '0.187', '0.187', '510,000']
22
0.200
23
0.200
24
0.180
25
0.187
26
0.187
27
510,000
28
Apr 04, 2019
['2019-04-04', '0.176', '0.196', '0.176', '0.185', '0.185', '1,450,000']
29
0.176
30
0.196
31
0.176
32
0.185
33
0.185
34
1,450,000
35
Apr 03, 2019
['2019-04-03', '0.184', '0.185', '0.173', '0.176', '0.176', '3,340,000']
36
0.184
37
0.185
38
0.173
39
0.176
40
0.176
41
3,340,000
42
Apr 02, 2019
['2019-04-02', '0.180', '0.184', '0.178', '0.181', '0.181', '700,000']
43
0.180
44
0.184
45
0.178
46
0.181
47
0.181
48
700,000
49
Apr 01, 2019
['2019-04-01', '0.190', '0.192', '0.186', '0.190', '0.190', '580,000']
50
0.190
51
0.192
52
0.186
53
0.190
54
0.190
55
580,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1705.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.040', '1.040', '1.000', '1.000', '1.000', '292,000']
1
1.040
2
1.040
3
1.000
4
1.000
5
1.000
6
292,000
7
Apr 10, 2019
['2019-04-10', '0.980', '1.090', '0.980', '1.040', '1.040', '1,280,000']
8
0.980
9
1.090
10
0.980
11
1.040
12
1.040
13
1,280,000
14
Apr 09, 2019
['2019-04-09', '1.000', '1.020', '0.980', '0.980', '0.980', '196,000']
15
1.000
16
1.020
17
0.980
18
0.980
19
0.980
20
196,000
21
Apr 08, 2019
['2019-04-08', '1.000', '1.020', '0.980', '0.980', '0.980', '280,000']
22
1.000
23
1.020
24
0.980
25
0.980
26
0.980
27
280,000
28
Apr 04, 2019
['2019-04-04', '0.990', '1.000', '0.990', '0.990', '0.990', '124,000']
29
0.990
30
1.000
31
0.990
32
0.990
33
0.990
34
124,000
35
Apr 03, 2019
['2019-04-03', '0.980', '1.000', '0.980', '1.000', '1.000', '232,000']
36
0.980
37
1.000
38
0.980
39
1.000
40
1.000
41
232,000
42
Apr 02, 2019
['2019-04-02', '0.980', '1.000', '0.980', '0.980', '0.980', '80,000']
43
0.980
44
1.000
45
0.980
46
0.980
47
0.980
48
80,000
49
Apr 01, 2019
['2019-04-01', '0.980', '0.980', '0.950', '0.980', '0.980', '316,000']
50
0.980
51
0.980
52
0.950
53
0.980
54
0.980
55
316,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1815.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.020', '1.020', '0.980', '0.990', '0.990', '1,068,600']
1
1.020
2
1.020
3
0.980
4
0.990
5
0.990
6
1,068,600
7
Apr 10, 2019
['2019-04-10', '1.000', '1.020', '0.980', '1.020', '1.020', '1,128,466']
8
1.000
9
1.020
10
0.980
11
1.020
12
1.020
13
1,128,466
14
Apr 09, 2019
['2019-04-09', '1.000', '1.040', '0.990', '1.000', '1.000', '1,205,833']
15
1.000
16
1.040
17
0.990
18
1.000
19
1.000
20
1,205,833
21
Apr 08, 2019
['2019-04-08', '1.000', '1.080', '0.980', '0.990', '0.990', '2,801,000']
22
1.000
23
1.080
24
0.980
25
0.990
26
0.990
27
2,801,000
28
Apr 04, 2019
['2019-04-04', '1.060', '1.060', '0.980', '1.010', '1.010', '1,774,166']
29
1.060
30
1.060
31
0.980
32
1.010
33
1.010
34
1,774,166
35
Apr 03, 2019
['2019-04-03', '0.920', '1.070', '0.860', '1.060', '1.060', '3,078,000']
36
0.920
37
1.070
38
0.860
39
1.060
40
1.060
41
3,078,000
42
Apr 02, 2019
['2019-04-02', '0.970', '0.970', '0.910', '0.920', '0.920', '1,490,033']
43
0.970
44
0.970
45
0.910
46
0.920
47
0.920
48
1,490,033
49
Apr 01, 2019
['2019-04-01', '1.000', '1.000', '0.940', '0.970', '0.970', '1,061,000']
50
1.000
51
1.000
52
0.940
53
0.970
54
0.970
55
1,061,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2182.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.630', '0.630', '0.620', '0.630', '0.630', '620,000']
1
0.630
2
0.630
3
0.620
4
0.630
5
0.630
6
620,000
7
Apr 10, 2019
['2019-04-10', '0.630', '0.650', '0.620', '0.640', '0.640', '720,000']
8
0.630
9
0.650
10
0.620
11
0.640
12
0.640
13
720,000
14
Apr 09, 2019
['2019-04-09', '0.640', '0.650', '0.620', '0.630', '0.630', '2,484,000']
15
0.640
16
0.650
17
0.620
18
0.630
19
0.630
20
2,484,000
21
Apr 08, 2019
['2019-04-08', '0.660', '0.670', '0.640', '0.650', '0.650', '808,000']
22
0.660
23
0.670
24
0.640
25
0.650
26
0.650
27
808,000
28
Apr 04, 2019
['2019-04-04', '0.660', '0.670', '0.640', '0.650', '0.650', '1,752,000']
29
0.660
30
0.670
31
0.640
32
0.650
33
0.650
34
1,752,000
35
Apr 03, 2019
['2019-04-03', '0.680', '0.680', '0.650', '0.660', '0.660', '1,919,000']
36
0.680
37
0.680
38
0.650
39
0.660
40
0.660
41
1,919,000
42
Apr 02, 2019
['2019-04-02', '0.710', '0.710', '0.680', '0.680', '0.680', '1,396,000']
43
0.710
44
0.710
45
0.680
46
0.680
47
0.680
48
1,396,000
49
Apr 01, 2019
['2019-04-01', '0.670', '0.730', '0.670', '0.700', '0.700', '4,912,000']
50
0.670
51
0.730
52
0.670
53
0.700
54
0.700
55
4,912,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1621.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.195', '0.195', '0.190', '0.190', '0.190', '1,064,000']
1
0.195
2
0.195
3
0.190
4
0.190
5
0.190
6
1,064,000
7
Apr 10, 2019
['2019-04-10', '0.198', '0.198', '0.195', '0.195', '0.195', '120,000']
8
0.198
9
0.198
10
0.195
11
0.195
12
0.195
13
120,000
14
Apr 09, 2019
['2019-04-09', '0.198', '0.204', '0.193', '0.204', '0.204', '608,000']
15
0.198
16
0.204
17
0.193
18
0.204
19
0.204
20
608,000
21
Apr 08, 2019
['2019-04-08', '0.201', '0.211', '0.201', '0.208', '0.208', '32,000']
22
0.201
23
0.211
24
0.201
25
0.208
26
0.208
27
32,000
28
Apr 04, 2019
['2019-04-04', '0.204', '0.204', '0.199', '0.199', '0.199', '320,000']
29
0.204
30
0.204
31
0.199
32
0.199
33
0.199
34
320,000
35
Apr 03, 2019
['2019-04-03', '0.194', '0.201', '0.190', '0.201', '0.201', '1,368,000']
36
0.194
37
0.201
38
0.190
39
0.201
40
0.201
41
1,368,000
42
Apr 02, 2019
['2019-04-02', '0.196', '0.203', '0.196', '0.200', '0.200', '368,000']
43
0.196
44
0.203
45
0.196
46
0.200
47
0.200
48
368,000
49
Apr 01, 2019
['2019-04-01', '0.200', '0.200', '0.200', '0.200', '0.200', '632,000']
50
0.200
51
0.200
52
0.200
53
0.200
54
0.200
55
632,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1933.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.500', '0.500', '0.500', '0.500', '0.500', '-']
1
0.500
2
0.500
3
0.500
4
0.500
5
0.500
6
-
7
Apr 10, 2019
['2019-04-10', '0.510', '0.510', '0.500', '0.500', '0.500', '224,000']
8
0.510
9
0.510
10
0.500
11
0.500
12
0.500
13
224,000
14
Apr 09, 2019
['2019-04-09', '0.510', '0.510', '0.510', '0.510', '0.510', '-']
15
0.510
16
0.510
17
0.510
18
0.510
19
0.510
20
-
21
Apr 08, 2019
['2019-04-08', '0.500', '0.520', '0.500', '0.520', '0.520', '232,000']
22
0.500
23
0.520
24
0.500
25
0.520
26
0.520
27
232,000
28
Apr 04, 2019
['2019-04-04', '0.510', '0.510', '0.510', '0.510', '0.510', '-']
29
0.510
30
0.510
31
0.510
32
0.510
33
0.510
34
-
35
Apr 03, 2019
['2019-04-03', '0.520', '0.520', '0.520', '0.520', '0.520', '104,000']
36
0.520
37
0.520
38
0.520
39
0.520
40
0.520
41
104,000
42
Apr 02, 2019
['2019-04-02', '0.520', '0.520', '0.520', '0.520', '0.520', '-']
43
0.520
44
0.520
45
0.520
46
0.520
47
0.520
48
-
49
Apr 01, 2019
['2019-04-01', '0.500', '0.500', '0.500', '0.500', '0.500', '-']
50
0.500
51
0.500
52
0.500
53
0.500
54
0.500
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8483.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.105', '0.106', '0.103', '0.106', '0.106', '328,000']
1
0.105
2
0.106
3
0.103
4
0.106
5
0.106
6
328,000
7
Apr 10, 2019
['2019-04-10', '0.105', '0.105', '0.105', '0.105', '0.105', '200,000']
8
0.105
9
0.105
10
0.105
11
0.105
12
0.105
13
200,000
14
Apr 09, 2019
['2019-04-09', '0.111', '0.111', '0.108', '0.109', '0.109', '432,000']
15
0.111
16
0.111
17
0.108
18
0.109
19
0.109
20
432,000
21
Apr 08, 2019
['2019-04-08', '0.114', '0.114', '0.110', '0.110', '0.110', '472,000']
22
0.114
23
0.114
24
0.110
25
0.110
26
0.110
27
472,000
28
Apr 04, 2019
['2019-04-04', '0.111', '0.114', '0.110', '0.114', '0.114', '288,000']
29
0.111
30
0.114
31
0.110
32
0.114
33
0.114
34
288,000
35
Apr 03, 2019
['2019-04-03', '0.110', '0.110', '0.110', '0.110', '0.110', '32,000']
36
0.110
37
0.110
38
0.110
39
0.110
40
0.110
41
32,000
42
Apr 02, 2019
['2019-04-02', '0.111', '0.111', '0.111', '0.111', '0.111', '-']
43
0.111
44
0.111
45
0.111
46
0.111
47
0.111
48
-
49
Apr 01, 2019
['2019-04-01', '0.112', '0.112', '0.112', '0.112', '0.112', '-']
50
0.112
51
0.112
52
0.112
53
0.112
54
0.112
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8526.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.320', '0.330', '0.320', '0.330', '0.330', '320,000']
1
0.320
2
0.330
3
0.320
4
0.330
5
0.330
6
320,000
7
Apr 10, 2019
['2019-04-10', '0.315', '0.330', '0.315', '0.320', '0.320', '340,000']
8
0.315
9
0.330
10
0.315
11
0.320
12
0.320
13
340,000
14
Apr 09, 2019
['2019-04-09', '0.305', '0.305', '0.305', '0.305', '0.305', '270,000']
15
0.305
16
0.305
17
0.305
18
0.305
19
0.305
20
270,000
21
Apr 08, 2019
['2019-04-08', '0.310', '0.330', '0.305', '0.305', '0.305', '390,000']
22
0.310
23
0.330
24
0.305
25
0.305
26
0.305
27
390,000
28
Apr 04, 2019
['2019-04-04', '0.315', '0.315', '0.305', '0.305', '0.305', '450,000']
29
0.315
30
0.315
31
0.305
32
0.305
33
0.305
34
450,000
35
Apr 03, 2019
['2019-04-03', '0.310', '0.325', '0.310', '0.310', '0.310', '330,000']
36
0.310
37
0.325
38
0.310
39
0.310
40
0.310
41
330,000
42
Apr 02, 2019
['2019-04-02', '0.310', '0.310', '0.310', '0.310', '0.310', '50,000']
43
0.310
44
0.310
45
0.310
46
0.310
47
0.310
48
50,000
49
Apr 01, 2019
['2019-04-01', '0.330', '0.330', '0.310', '0.310', '0.310', '230,000']
50
0.330
51
0.330
52
0.310
53
0.310
54
0.310
55
230,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8367.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.085', '0.085', '0.085', '0.085', '0.085', '-']
1
0.085
2
0.085
3
0.085
4
0.085
5
0.085
6
-
7
Apr 10, 2019
['2019-04-10', '0.085', '0.085', '0.085', '0.085', '0.085', '160,000']
8
0.085
9
0.085
10
0.085
11
0.085
12
0.085
13
160,000
14
Apr 09, 2019
['2019-04-09', '0.081', '0.085', '0.081', '0.085', '0.085', '420,000']
15
0.081
16
0.085
17
0.081
18
0.085
19
0.085
20
420,000
21
Apr 08, 2019
['2019-04-08', '0.081', '0.081', '0.081', '0.081', '0.081', '-']
22
0.081
23
0.081
24
0.081
25
0.081
26
0.081
27
-
28
Apr 04, 2019
['2019-04-04', '0.081', '0.083', '0.080', '0.084', '0.084', '840,000']
29
0.081
30
0.083
31
0.080
32
0.084
33
0.084
34
840,000
35
Apr 03, 2019
['2019-04-03', '0.082', '0.086', '0.082', '0.086', '0.086', '730,000']
36
0.082
37
0.086
38
0.082
39
0.086
40
0.086
41
730,000
42
Apr 02, 2019
['2019-04-02', '0.083', '0.083', '0.082', '0.082', '0.082', '440,000']
43
0.083
44
0.083
45
0.082
46
0.082
47
0.082
48
440,000
49
Apr 01, 2019
['2019-04-01', '0.083', '0.083', '0.079', '0.081', '0.081', '2,300,000']
50
0.083
51
0.083
52
0.079
53
0.081
54
0.081
55
2,300,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8532.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.084', '0.087', '0.082', '0.086', '0.086', '176,000']
1
0.084
2
0.087
3
0.082
4
0.086
5
0.086
6
176,000
7
Apr 10, 2019
['2019-04-10', '0.084', '0.086', '0.080', '0.085', '0.085', '992,000']
8
0.084
9
0.086
10
0.080
11
0.085
12
0.085
13
992,000
14
Apr 09, 2019
['2019-04-09', '0.085', '0.087', '0.084', '0.087', '0.087', '176,000']
15
0.085
16
0.087
17
0.084
18
0.087
19
0.087
20
176,000
21
Apr 08, 2019
['2019-04-08', '0.090', '0.090', '0.090', '0.090', '0.090', '-']
22
0.090
23
0.090
24
0.090
25
0.090
26
0.090
27
-
28
Apr 04, 2019
['2019-04-04', '0.081', '0.088', '0.080', '0.088', '0.088', '3,240,000']
29
0.081
30
0.088
31
0.080
32
0.088
33
0.088
34
3,240,000
35
Apr 03, 2019
['2019-04-03', '0.090', '0.090', '0.090', '0.090', '0.090', '-']
36
0.090
37
0.090
38
0.090
39
0.090
40
0.090
41
-
42
Apr 02, 2019
['2019-04-02', '0.086', '0.090', '0.083', '0.090', '0.090', '888,000']
43
0.086
44
0.090
45
0.083
46
0.090
47
0.090
48
888,000
49
Apr 01, 2019
['2019-04-01', '0.088', '0.088', '0.088', '0.088', '0.088', '-']
50
0.088
51
0.088
52
0.088
53
0.088
54
0.088
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8379.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.092', '0.092', '0.088', '0.091', '0.091', '790,000']
1
0.092
2
0.092
3
0.088
4
0.091
5
0.091
6
790,000
7
Apr 10, 2019
['2019-04-10', '0.095', '0.095', '0.091', '0.095', '0.095', '220,000']
8
0.095
9
0.095
10
0.091
11
0.095
12
0.095
13
220,000
14
Apr 09, 2019
['2019-04-09', '0.098', '0.098', '0.097', '0.097', '0.097', '40,000']
15
0.098
16
0.098
17
0.097
18
0.097
19
0.097
20
40,000
21
Apr 08, 2019
['2019-04-08', '0.092', '0.093', '0.093', '0.093', '0.093', '360,000']
22
0.092
23
0.093
24
0.093
25
0.093
26
0.093
27
360,000
28
Apr 04, 2019
['2019-04-04', '0.092', '0.098', '0.091', '0.096', '0.096', '720,000']
29
0.092
30
0.098
31
0.091
32
0.096
33
0.096
34
720,000
35
Apr 03, 2019
['2019-04-03', '0.094', '0.100', '0.090', '0.091', '0.091', '1,250,000']
36
0.094
37
0.100
38
0.090
39
0.091
40
0.091
41
1,250,000
42
Apr 02, 2019
['2019-04-02', '0.097', '0.097', '0.094', '0.094', '0.094', '2,040,000']
43
0.097
44
0.097
45
0.094
46
0.094
47
0.094
48
2,040,000
49
Apr 01, 2019
['2019-04-01', '0.097', '0.097', '0.097', '0.097', '0.097', '-']
50
0.097
51
0.097
52
0.097
53
0.097
54
0.097
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8040.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.310', '0.310', '0.300', '0.310', '0.310', '795,000']
1
0.310
2
0.310
3
0.300
4
0.310
5
0.310
6
795,000
7
Apr 10, 2019
['2019-04-10', '0.305', '0.310', '0.305', '0.310', '0.310', '70,000']
8
0.305
9
0.310
10
0.305
11
0.310
12
0.310
13
70,000
14
Apr 09, 2019
['2019-04-09', '0.325', '0.325', '0.325', '0.325', '0.325', '-']
15
0.325
16
0.325
17
0.325
18
0.325
19
0.325
20
-
21
Apr 08, 2019
['2019-04-08', '0.325', '0.325', '0.325', '0.325', '0.325', '-']
22
0.325
23
0.325
24
0.325
25
0.325
26
0.325
27
-
28
Apr 04, 2019
['2019-04-04', '0.325', '0.325', '0.325', '0.325', '0.325', '-']
29
0.325
30
0.325
31
0.325
32
0.325
33
0.325
34
-
35
Apr 03, 2019
['2019-04-03', '0.310', '0.310', '0.310', '0.310', '0.310', '40,000']
36
0.310
37
0.310
38
0.310
39
0.310
40
0.310
41
40,000
42
Apr 02, 2019
['2019-04-02', '0.305', '0.335', '0.305', '0.320', '0.320', '20,000']
43
0.305
44
0.335
45
0.305
46
0.320
47
0.320
48
20,000
49
Apr 01, 2019
['2019-04-01', '0.310', '0.310', '0.310', '0.310', '0.310', '-']
50
0.310
51
0.310
52
0.310
53
0.310
54
0.310
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8510.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.148', '0.154', '0.146', '0.154', '0.154', '152,000']
1
0.148
2
0.154
3
0.146
4
0.154
5
0.154
6
152,000
7
Apr 10, 2019
['2019-04-10', '0.154', '0.154', '0.154', '0.154', '0.154', '-']
8
0.154
9
0.154
10
0.154
11
0.154
12
0.154
13
-
14
Apr 09, 2019
['2019-04-09', '0.154', '0.155', '0.150', '0.155', '0.155', '4,192,000']
15
0.154
16
0.155
17
0.150
18
0.155
19
0.155
20
4,192,000
21
Apr 08, 2019
['2019-04-08', '0.145', '0.155', '0.144', '0.155', '0.155', '344,000']
22
0.145
23
0.155
24
0.144
25
0.155
26
0.155
27
344,000
28
Apr 04, 2019
['2019-04-04', '0.151', '0.151', '0.144', '0.145', '0.145', '408,000']
29
0.151
30
0.151
31
0.144
32
0.145
33
0.145
34
408,000
35
Apr 03, 2019
['2019-04-03', '0.148', '0.152', '0.148', '0.152', '0.152', '56,000']
36
0.148
37
0.152
38
0.148
39
0.152
40
0.152
41
56,000
42
Apr 02, 2019
['2019-04-02', '0.150', '0.156', '0.145', '0.152', '0.152', '528,000']
43
0.150
44
0.156
45
0.145
46
0.152
47
0.152
48
528,000
49
Apr 01, 2019
['2019-04-01', '0.150', '0.150', '0.150', '0.150', '0.150', '-']
50
0.150
51
0.150
52
0.150
53
0.150
54
0.150
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8522.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.250', '1.270', '1.240', '1.240', '1.240', '1,060,000']
1
1.250
2
1.270
3
1.240
4
1.240
5
1.240
6
1,060,000
7
Apr 10, 2019
['2019-04-10', '1.270', '1.270', '1.250', '1.250', '1.250', '1,780,000']
8
1.270
9
1.270
10
1.250
11
1.250
12
1.250
13
1,780,000
14
Apr 09, 2019
['2019-04-09', '1.210', '1.270', '1.270', '1.270', '1.270', '32,000']
15
1.210
16
1.270
17
1.270
18
1.270
19
1.270
20
32,000
21
Apr 08, 2019
['2019-04-08', '1.260', '1.290', '1.250', '1.270', '1.270', '1,300,000']
22
1.260
23
1.290
24
1.250
25
1.270
26
1.270
27
1,300,000
28
Apr 04, 2019
['2019-04-04', '1.290', '1.290', '1.270', '1.290', '1.290', '620,000']
29
1.290
30
1.290
31
1.270
32
1.290
33
1.290
34
620,000
35
Apr 03, 2019
['2019-04-03', '1.240', '1.290', '1.240', '1.290', '1.290', '704,000']
36
1.240
37
1.290
38
1.240
39
1.290
40
1.290
41
704,000
42
Apr 02, 2019
['2019-04-02', '1.250', '1.280', '1.200', '1.270', '1.270', '764,000']
43
1.250
44
1.280
45
1.200
46
1.270
47
1.270
48
764,000
49
Apr 01, 2019
['2019-04-01', '1.260', '1.290', '1.250', '1.250', '1.250', '508,000']
50
1.260
51
1.290
52
1.250
53
1.250
54
1.250
55
508,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1183.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.260', '1.340', '1.240', '1.280', '1.280', '3,812,000']
1
1.260
2
1.340
3
1.240
4
1.280
5
1.280
6
3,812,000
7
Apr 10, 2019
['2019-04-10', '1.270', '1.270', '1.240', '1.260', '1.260', '1,418,000']
8
1.270
9
1.270
10
1.240
11
1.260
12
1.260
13
1,418,000
14
Apr 09, 2019
['2019-04-09', '1.260', '1.260', '1.230', '1.250', '1.250', '1,272,000']
15
1.260
16
1.260
17
1.230
18
1.250
19
1.250
20
1,272,000
21
Apr 08, 2019
['2019-04-08', '1.230', '1.260', '1.230', '1.250', '1.250', '2,234,000']
22
1.230
23
1.260
24
1.230
25
1.250
26
1.250
27
2,234,000
28
Apr 04, 2019
['2019-04-04', '1.210', '1.220', '1.180', '1.220', '1.220', '906,000']
29
1.210
30
1.220
31
1.180
32
1.220
33
1.220
34
906,000
35
Apr 03, 2019
['2019-04-03', '1.200', '1.260', '1.200', '1.210', '1.210', '4,166,000']
36
1.200
37
1.260
38
1.200
39
1.210
40
1.210
41
4,166,000
42
Apr 02, 2019
['2019-04-02', '1.120', '1.200', '1.080', '1.170', '1.170', '3,316,000']
43
1.120
44
1.200
45
1.080
46
1.170
47
1.170
48
3,316,000
49
Apr 01, 2019
['2019-04-01', '1.110', '1.120', '1.090', '1.120', '1.120', '562,000']
50
1.110
51
1.120
52
1.090
53
1.120
54
1.120
55
562,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1729.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.880', '0.920', '0.860', '0.880', '0.880', '23,664,000']
1
0.880
2
0.920
3
0.860
4
0.880
5
0.880
6
23,664,000
7
Apr 10, 2019
['2019-04-10', '0.850', '0.880', '0.840', '0.880', '0.880', '20,908,000']
8
0.850
9
0.880
10
0.840
11
0.880
12
0.880
13
20,908,000
14
Apr 09, 2019
['2019-04-09', '0.810', '0.840', '0.800', '0.830', '0.830', '9,608,000']
15
0.810
16
0.840
17
0.800
18
0.830
19
0.830
20
9,608,000
21
Apr 08, 2019
['2019-04-08', '0.800', '0.820', '0.790', '0.800', '0.800', '6,800,000']
22
0.800
23
0.820
24
0.790
25
0.800
26
0.800
27
6,800,000
28
Apr 04, 2019
['2019-04-04', '0.780', '0.810', '0.780', '0.800', '0.800', '3,660,400']
29
0.780
30
0.810
31
0.780
32
0.800
33
0.800
34
3,660,400
35
Apr 03, 2019
['2019-04-03', '0.790', '0.790', '0.770', '0.780', '0.780', '2,280,000']
36
0.790
37
0.790
38
0.770
39
0.780
40
0.780
41
2,280,000
42
Apr 02, 2019
['2019-04-02', '0.790', '0.800', '0.770', '0.790', '0.790', '9,512,000']
43
0.790
44
0.800
45
0.770
46
0.790
47
0.790
48
9,512,000
49
Apr 01, 2019
['2019-04-01', '0.800', '0.810', '0.790', '0.800', '0.800', '3,152,000']
50
0.800
51
0.810
52
0.790
53
0.800
54
0.800
55
3,152,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8523.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.610', '0.660', '0.610', '0.660', '0.660', '85,000']
1
0.610
2
0.660
3
0.610
4
0.660
5
0.660
6
85,000
7
Apr 10, 2019
['2019-04-10', '0.680', '0.680', '0.630', '0.670', '0.670', '35,000']
8
0.680
9
0.680
10
0.630
11
0.670
12
0.670
13
35,000
14
Apr 09, 2019
['2019-04-09', '0.600', '0.700', '0.600', '0.690', '0.690', '470,000']
15
0.600
16
0.700
17
0.600
18
0.690
19
0.690
20
470,000
21
Apr 08, 2019
['2019-04-08', '0.680', '0.680', '0.630', '0.660', '0.660', '960,000']
22
0.680
23
0.680
24
0.630
25
0.660
26
0.660
27
960,000
28
Apr 04, 2019
['2019-04-04', '0.740', '0.740', '0.680', '0.680', '0.680', '1,620,000']
29
0.740
30
0.740
31
0.680
32
0.680
33
0.680
34
1,620,000
35
Apr 03, 2019
['2019-04-03', '0.780', '0.780', '0.720', '0.740', '0.740', '1,025,000']
36
0.780
37
0.780
38
0.720
39
0.740
40
0.740
41
1,025,000
42
Apr 02, 2019
['2019-04-02', '0.780', '0.780', '0.760', '0.760', '0.760', '350,000']
43
0.780
44
0.780
45
0.760
46
0.760
47
0.760
48
350,000
49
Apr 01, 2019
['2019-04-01', '0.770', '0.790', '0.770', '0.790', '0.790', '415,000']
50
0.770
51
0.790
52
0.770
53
0.790
54
0.790
55
415,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8535.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.158', '0.164', '0.152', '0.164', '0.164', '1,560,000']
1
0.158
2
0.164
3
0.152
4
0.164
5
0.164
6
1,560,000
7
Apr 10, 2019
['2019-04-10', '0.160', '0.163', '0.159', '0.159', '0.159', '1,400,000']
8
0.160
9
0.163
10
0.159
11
0.159
12
0.159
13
1,400,000
14
Apr 09, 2019
['2019-04-09', '0.160', '0.163', '0.154', '0.161', '0.161', '1,960,000']
15
0.160
16
0.163
17
0.154
18
0.161
19
0.161
20
1,960,000
21
Apr 08, 2019
['2019-04-08', '0.161', '0.165', '0.161', '0.164', '0.164', '820,000']
22
0.161
23
0.165
24
0.161
25
0.164
26
0.164
27
820,000
28
Apr 04, 2019
['2019-04-04', '0.162', '0.166', '0.157', '0.165', '0.165', '300,000']
29
0.162
30
0.166
31
0.157
32
0.165
33
0.165
34
300,000
35
Apr 03, 2019
['2019-04-03', '0.160', '0.165', '0.160', '0.165', '0.165', '1,680,000']
36
0.160
37
0.165
38
0.160
39
0.165
40
0.165
41
1,680,000
42
Apr 02, 2019
['2019-04-02', '0.161', '0.163', '0.160', '0.162', '0.162', '1,280,000']
43
0.161
44
0.163
45
0.160
46
0.162
47
0.162
48
1,280,000
49
Apr 01, 2019
['2019-04-01', '0.158', '0.162', '0.153', '0.160', '0.160', '1,880,000']
50
0.158
51
0.162
52
0.153
53
0.160
54
0.160
55
1,880,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8473.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.340', '0.345', '0.325', '0.325', '0.325', '2,380,000']
1
0.340
2
0.345
3
0.325
4
0.325
5
0.325
6
2,380,000
7
Apr 10, 2019
['2019-04-10', '0.340', '0.350', '0.330', '0.330', '0.330', '3,050,000']
8
0.340
9
0.350
10
0.330
11
0.330
12
0.330
13
3,050,000
14
Apr 09, 2019
['2019-04-09', '0.320', '0.355', '0.320', '0.340', '0.340', '18,780,000']
15
0.320
16
0.355
17
0.320
18
0.340
19
0.340
20
18,780,000
21
Apr 08, 2019
['2019-04-08', '0.300', '0.325', '0.300', '0.320', '0.320', '6,860,000']
22
0.300
23
0.325
24
0.300
25
0.320
26
0.320
27
6,860,000
28
Apr 04, 2019
['2019-04-04', '0.300', '0.300', '0.290', '0.295', '0.295', '1,650,000']
29
0.300
30
0.300
31
0.290
32
0.295
33
0.295
34
1,650,000
35
Apr 03, 2019
['2019-04-03', '0.300', '0.300', '0.290', '0.300', '0.300', '1,620,000']
36
0.300
37
0.300
38
0.290
39
0.300
40
0.300
41
1,620,000
42
Apr 02, 2019
['2019-04-02', '0.295', '0.300', '0.290', '0.300', '0.300', '810,000']
43
0.295
44
0.300
45
0.290
46
0.300
47
0.300
48
810,000
49
Apr 01, 2019
['2019-04-01', '0.290', '0.300', '0.290', '0.295', '0.295', '1,110,000']
50
0.290
51
0.300
52
0.290
53
0.295
54
0.295
55
1,110,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1690.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.200', '0.200', '0.200', '0.200', '0.200', '-']
1
0.200
2
0.200
3
0.200
4
0.200
5
0.200
6
-
7
Apr 10, 2019
['2019-04-10', '0.200', '0.200', '0.200', '0.200', '0.200', '300,000']
8
0.200
9
0.200
10
0.200
11
0.200
12
0.200
13
300,000
14
Apr 09, 2019
['2019-04-09', '0.199', '0.199', '0.199', '0.199', '0.199', '-']
15
0.199
16
0.199
17
0.199
18
0.199
19
0.199
20
-
21
Apr 08, 2019
['2019-04-08', '0.199', '0.199', '0.199', '0.199', '0.199', '-']
22
0.199
23
0.199
24
0.199
25
0.199
26
0.199
27
-
28
Apr 04, 2019
['2019-04-04', '0.199', '0.199', '0.199', '0.199', '0.199', '-']
29
0.199
30
0.199
31
0.199
32
0.199
33
0.199
34
-
35
Apr 03, 2019
['2019-04-03', '0.200', '0.200', '0.200', '0.200', '0.200', '-']
36
0.200
37
0.200
38
0.200
39
0.200
40
0.200
41
-
42
Apr 02, 2019
['2019-04-02', '0.194', '0.195', '0.191', '0.195', '0.195', '110,000']
43
0.194
44
0.195
45
0.191
46
0.195
47
0.195
48
110,000
49
Apr 01, 2019
['2019-04-01', '0.198', '0.198', '0.180', '0.196', '0.196', '420,000']
50
0.198
51
0.198
52
0.180
53
0.196
54
0.196
55
420,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1990.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.920', '0.930', '0.920', '0.920', '0.920', '69,550']
1
0.920
2
0.930
3
0.920
4
0.920
5
0.920
6
69,550
7
Apr 10, 2019
['2019-04-10', '0.900', '0.910', '0.900', '0.910', '0.910', '3,700']
8
0.900
9
0.910
10
0.900
11
0.910
12
0.910
13
3,700
14
Apr 09, 2019
['2019-04-09', '0.920', '0.920', '0.920', '0.920', '0.920', '-']
15
0.920
16
0.920
17
0.920
18
0.920
19
0.920
20
-
21
Apr 08, 2019
['2019-04-08', '0.910', '0.910', '0.910', '0.910', '0.910', '-']
22
0.910
23
0.910
24
0.910
25
0.910
26
0.910
27
-
28
Apr 04, 2019
['2019-04-04', '0.950', '0.950', '0.910', '0.910', '0.910', '82,700']
29
0.950
30
0.950
31
0.910
32
0.910
33
0.910
34
82,700
35
Apr 03, 2019
['2019-04-03', '0.940', '0.940', '0.940', '0.940', '0.940', '-']
36
0.940
37
0.940
38
0.940
39
0.940
40
0.940
41
-
42
Apr 02, 2019
['2019-04-02', '0.900', '0.940', '0.900', '0.940', '0.940', '46,250']
43
0.900
44
0.940
45
0.900
46
0.940
47
0.940
48
46,250
49
Apr 01, 2019
['2019-04-01', '0.910', '0.940', '0.910', '0.910', '0.910', '139,000']
50
0.910
51
0.940
52
0.910
53
0.910
54
0.910
55
139,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3319.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '12.680', '12.760', '12.280', '12.300', '12.300', '3,298,890']
1
12.680
2
12.760
3
12.280
4
12.300
5
12.300
6
3,298,890
7
Apr 10, 2019
['2019-04-10', '12.920', '12.940', '12.600', '12.720', '12.720', '4,074,000']
8
12.920
9
12.940
10
12.600
11
12.720
12
12.720
13
4,074,000
14
Apr 09, 2019
['2019-04-09', '13.360', '13.360', '12.900', '12.940', '12.940', '4,554,415']
15
13.360
16
13.360
17
12.900
18
12.940
19
12.940
20
4,554,415
21
Apr 08, 2019
['2019-04-08', '13.180', '13.380', '13.120', '13.360', '13.360', '3,517,410']
22
13.180
23
13.380
24
13.120
25
13.360
26
13.360
27
3,517,410
28
Apr 04, 2019
['2019-04-04', '13.140', '13.180', '12.900', '13.100', '13.100', '2,264,250']
29
13.140
30
13.180
31
12.900
32
13.100
33
13.100
34
2,264,250
35
Apr 03, 2019
['2019-04-03', '13.000', '13.160', '12.720', '13.060', '13.060', '4,604,670']
36
13.000
37
13.160
38
12.720
39
13.060
40
13.060
41
4,604,670
42
Apr 02, 2019
['2019-04-02', '13.540', '13.640', '12.960', '13.000', '13.000', '4,646,027']
43
13.540
44
13.640
45
12.960
46
13.000
47
13.000
48
4,646,027
49
Apr 01, 2019
['2019-04-01', '13.640', '13.780', '13.220', '13.520', '13.520', '3,352,352']
50
13.640
51
13.780
52
13.220
53
13.520
54
13.520
55
3,352,352
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8519.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.110', '0.110', '0.110', '0.110', '0.110', '-']
1
0.110
2
0.110
3
0.110
4
0.110
5
0.110
6
-
7
Apr 10, 2019
['2019-04-10', '0.089', '0.112', '0.089', '0.112', '0.112', '60,000']
8
0.089
9
0.112
10
0.089
11
0.112
12
0.112
13
60,000
14
Apr 09, 2019
['2019-04-09', '0.113', '0.114', '0.113', '0.114', '0.114', '210,000']
15
0.113
16
0.114
17
0.113
18
0.114
19
0.114
20
210,000
21
Apr 08, 2019
['2019-04-08', '0.097', '0.114', '0.097', '0.114', '0.114', '80,000']
22
0.097
23
0.114
24
0.097
25
0.114
26
0.114
27
80,000
28
Apr 04, 2019
['2019-04-04', '0.108', '0.108', '0.106', '0.104', '0.104', '60,000']
29
0.108
30
0.108
31
0.106
32
0.104
33
0.104
34
60,000
35
Apr 03, 2019
['2019-04-03', '0.110', '0.110', '0.110', '0.110', '0.110', '-']
36
0.110
37
0.110
38
0.110
39
0.110
40
0.110
41
-
42
Apr 02, 2019
['2019-04-02', '0.110', '0.110', '0.110', '0.110', '0.110', '-']
43
0.110
44
0.110
45
0.110
46
0.110
47
0.110
48
-
49
Apr 01, 2019
['2019-04-01', '0.076', '0.110', '0.076', '0.110', '0.110', '90,000']
50
0.076
51
0.110
52
0.076
53
0.110
54
0.110
55
90,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6829.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.211', '0.211', '0.207', '0.208', '0.208', '290,000']
1
0.211
2
0.211
3
0.207
4
0.208
5
0.208
6
290,000
7
Apr 10, 2019
['2019-04-10', '0.210', '0.216', '0.209', '0.210', '0.210', '240,000']
8
0.210
9
0.216
10
0.209
11
0.210
12
0.210
13
240,000
14
Apr 09, 2019
['2019-04-09', '0.211', '0.221', '0.209', '0.209', '0.209', '2,550,000']
15
0.211
16
0.221
17
0.209
18
0.209
19
0.209
20
2,550,000
21
Apr 08, 2019
['2019-04-08', '0.210', '0.219', '0.202', '0.219', '0.219', '5,040,000']
22
0.210
23
0.219
24
0.202
25
0.219
26
0.219
27
5,040,000
28
Apr 04, 2019
['2019-04-04', '0.212', '0.225', '0.212', '0.214', '0.214', '2,410,000']
29
0.212
30
0.225
31
0.212
32
0.214
33
0.214
34
2,410,000
35
Apr 03, 2019
['2019-04-03', '0.212', '0.219', '0.207', '0.207', '0.207', '1,160,000']
36
0.212
37
0.219
38
0.207
39
0.207
40
0.207
41
1,160,000
42
Apr 02, 2019
['2019-04-02', '0.214', '0.223', '0.205', '0.212', '0.212', '3,540,000']
43
0.214
44
0.223
45
0.205
46
0.212
47
0.212
48
3,540,000
49
Apr 01, 2019
['2019-04-01', '0.218', '0.221', '0.212', '0.213', '0.213', '700,000']
50
0.218
51
0.221
52
0.212
53
0.213
54
0.213
55
700,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1659.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.135', '0.135', '0.135', '0.135', '0.135', '-']
1
0.135
2
0.135
3
0.135
4
0.135
5
0.135
6
-
7
Apr 10, 2019
['2019-04-10', '0.135', '0.135', '0.135', '0.135', '0.135', '-']
8
0.135
9
0.135
10
0.135
11
0.135
12
0.135
13
-
14
Apr 09, 2019
['2019-04-09', '0.135', '0.135', '0.135', '0.135', '0.135', '-']
15
0.135
16
0.135
17
0.135
18
0.135
19
0.135
20
-
21
Apr 08, 2019
['2019-04-08', '0.135', '0.135', '0.135', '0.135', '0.135', '-']
22
0.135
23
0.135
24
0.135
25
0.135
26
0.135
27
-
28
Apr 04, 2019
['2019-04-04', '0.135', '0.135', '0.135', '0.135', '0.135', '-']
29
0.135
30
0.135
31
0.135
32
0.135
33
0.135
34
-
35
Apr 03, 2019
['2019-04-03', '0.135', '0.135', '0.135', '0.135', '0.135', '-']
36
0.135
37
0.135
38
0.135
39
0.135
40
0.135
41
-
42
Apr 02, 2019
['2019-04-02', '0.135', '0.135', '0.135', '0.135', '0.135', '-']
43
0.135
44
0.135
45
0.135
46
0.135
47
0.135
48
-
49
Apr 01, 2019
['2019-04-01', '0.135', '0.135', '0.135', '0.135', '0.135', '-']
50
0.135
51
0.135
52
0.135
53
0.135
54
0.135
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8450.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.077', '0.077', '0.077', '0.079', '0.079', '250,000']
1
0.077
2
0.077
3
0.077
4
0.079
5
0.079
6
250,000
7
Apr 10, 2019
['2019-04-10', '0.082', '0.082', '0.080', '0.080', '0.080', '390,000']
8
0.082
9
0.082
10
0.080
11
0.080
12
0.080
13
390,000
14
Apr 09, 2019
['2019-04-09', '0.082', '0.082', '0.082', '0.082', '0.082', '-']
15
0.082
16
0.082
17
0.082
18
0.082
19
0.082
20
-
21
Apr 08, 2019
['2019-04-08', '0.082', '0.082', '0.082', '0.082', '0.082', '90,000']
22
0.082
23
0.082
24
0.082
25
0.082
26
0.082
27
90,000
28
Apr 04, 2019
['2019-04-04', '0.082', '0.082', '0.082', '0.082', '0.082', '40,000']
29
0.082
30
0.082
31
0.082
32
0.082
33
0.082
34
40,000
35
Apr 03, 2019
['2019-04-03', '0.075', '0.082', '0.075', '0.082', '0.082', '30,000']
36
0.075
37
0.082
38
0.075
39
0.082
40
0.082
41
30,000
42
Apr 02, 2019
['2019-04-02', '0.082', '0.081', '0.074', '0.079', '0.079', '2,170,000']
43
0.082
44
0.081
45
0.074
46
0.079
47
0.079
48
2,170,000
49
Apr 01, 2019
['2019-04-01', '0.082', '0.082', '0.082', '0.082', '0.082', '-']
50
0.082
51
0.082
52
0.082
53
0.082
54
0.082
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1719.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.000', '1.020', '1.000', '1.020', '1.020', '296,000']
1
1.000
2
1.020
3
1.000
4
1.020
5
1.020
6
296,000
7
Apr 10, 2019
['2019-04-10', '0.910', '1.090', '0.910', '1.010', '1.010', '1,952,000']
8
0.910
9
1.090
10
0.910
11
1.010
12
1.010
13
1,952,000
14
Apr 09, 2019
['2019-04-09', '1.000', '1.200', '1.000', '1.030', '1.030', '960,000']
15
1.000
16
1.200
17
1.000
18
1.030
19
1.030
20
960,000
21
Apr 08, 2019
['2019-04-08', '0.780', '0.950', '0.780', '0.950', '0.950', '192,000']
22
0.780
23
0.950
24
0.780
25
0.950
26
0.950
27
192,000
28
Apr 04, 2019
['2019-04-04', '0.900', '0.970', '0.900', '0.950', '0.950', '284,000']
29
0.900
30
0.970
31
0.900
32
0.950
33
0.950
34
284,000
35
Apr 03, 2019
['2019-04-03', '0.930', '0.970', '0.880', '0.900', '0.900', '824,000']
36
0.930
37
0.970
38
0.880
39
0.900
40
0.900
41
824,000
42
Apr 02, 2019
['2019-04-02', '0.890', '0.930', '0.890', '0.930', '0.930', '796,000']
43
0.890
44
0.930
45
0.890
46
0.930
47
0.930
48
796,000
49
Apr 01, 2019
['2019-04-01', '0.810', '0.900', '0.810', '0.890', '0.890', '548,000']
50
0.810
51
0.900
52
0.810
53
0.890
54
0.890
55
548,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1711.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.310', '0.320', '0.310', '0.315', '0.315', '790,000']
1
0.310
2
0.320
3
0.310
4
0.315
5
0.315
6
790,000
7
Apr 10, 2019
['2019-04-10', '0.315', '0.320', '0.310', '0.315', '0.315', '900,000']
8
0.315
9
0.320
10
0.310
11
0.315
12
0.315
13
900,000
14
Apr 09, 2019
['2019-04-09', '0.315', '0.330', '0.315', '0.315', '0.315', '450,000']
15
0.315
16
0.330
17
0.315
18
0.315
19
0.315
20
450,000
21
Apr 08, 2019
['2019-04-08', '0.320', '0.320', '0.315', '0.315', '0.315', '160,000']
22
0.320
23
0.320
24
0.315
25
0.315
26
0.315
27
160,000
28
Apr 04, 2019
['2019-04-04', '0.315', '0.330', '0.315', '0.320', '0.320', '1,330,000']
29
0.315
30
0.330
31
0.315
32
0.320
33
0.320
34
1,330,000
35
Apr 03, 2019
['2019-04-03', '0.310', '0.320', '0.310', '0.310', '0.310', '170,000']
36
0.310
37
0.320
38
0.310
39
0.310
40
0.310
41
170,000
42
Apr 02, 2019
['2019-04-02', '0.310', '0.320', '0.310', '0.315', '0.315', '750,000']
43
0.310
44
0.320
45
0.310
46
0.315
47
0.315
48
750,000
49
Apr 01, 2019
['2019-04-01', '0.310', '0.315', '0.310', '0.310', '0.310', '940,000']
50
0.310
51
0.315
52
0.310
53
0.310
54
0.310
55
940,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8456.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.239', '0.239', '0.239', '0.239', '0.239', '-']
1
0.239
2
0.239
3
0.239
4
0.239
5
0.239
6
-
7
Apr 10, 2019
['2019-04-10', '0.241', '0.241', '0.232', '0.239', '0.239', '84,000']
8
0.241
9
0.241
10
0.232
11
0.239
12
0.239
13
84,000
14
Apr 09, 2019
['2019-04-09', '0.233', '0.235', '0.233', '0.235', '0.235', '436,000']
15
0.233
16
0.235
17
0.233
18
0.235
19
0.235
20
436,000
21
Apr 08, 2019
['2019-04-08', '0.239', '0.239', '0.239', '0.239', '0.239', '-']
22
0.239
23
0.239
24
0.239
25
0.239
26
0.239
27
-
28
Apr 04, 2019
['2019-04-04', '0.242', '0.242', '0.242', '0.242', '0.242', '-']
29
0.242
30
0.242
31
0.242
32
0.242
33
0.242
34
-
35
Apr 03, 2019
['2019-04-03', '0.245', '0.245', '0.245', '0.245', '0.245', '-']
36
0.245
37
0.245
38
0.245
39
0.245
40
0.245
41
-
42
Apr 02, 2019
['2019-04-02', '0.235', '0.245', '0.235', '0.245', '0.245', '8,000']
43
0.235
44
0.245
45
0.235
46
0.245
47
0.245
48
8,000
49
Apr 01, 2019
['2019-04-01', '0.235', '0.235', '0.235', '0.235', '0.235', '-']
50
0.235
51
0.235
52
0.235
53
0.235
54
0.235
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8395.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.066', '0.066', '0.066', '0.066', '0.066', '-']
1
0.066
2
0.066
3
0.066
4
0.066
5
0.066
6
-
7
Apr 10, 2019
['2019-04-10', '0.076', '0.076', '0.069', '0.069', '0.069', '320,000']
8
0.076
9
0.076
10
0.069
11
0.069
12
0.069
13
320,000
14
Apr 09, 2019
['2019-04-09', '0.069', '0.069', '0.069', '0.069', '0.069', '440,000']
15
0.069
16
0.069
17
0.069
18
0.069
19
0.069
20
440,000
21
Apr 08, 2019
['2019-04-08', '0.063', '0.071', '0.063', '0.070', '0.070', '80,000']
22
0.063
23
0.071
24
0.063
25
0.070
26
0.070
27
80,000
28
Apr 04, 2019
['2019-04-04', '0.071', '0.071', '0.071', '0.071', '0.071', '-']
29
0.071
30
0.071
31
0.071
32
0.071
33
0.071
34
-
35
Apr 03, 2019
['2019-04-03', '0.071', '0.071', '0.071', '0.071', '0.071', '-']
36
0.071
37
0.071
38
0.071
39
0.071
40
0.071
41
-
42
Apr 02, 2019
['2019-04-02', '0.071', '0.071', '0.071', '0.071', '0.071', '-']
43
0.071
44
0.071
45
0.071
46
0.071
47
0.071
48
-
49
Apr 01, 2019
['2019-04-01', '0.070', '0.071', '0.070', '0.071', '0.071', '1,160,000']
50
0.070
51
0.071
52
0.070
53
0.071
54
0.071
55
1,160,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8136.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.135', '0.139', '0.135', '0.139', '0.139', '320,000']
1
0.135
2
0.139
3
0.135
4
0.139
5
0.139
6
320,000
7
Apr 10, 2019
['2019-04-10', '0.135', '0.139', '0.135', '0.139', '0.139', '440,000']
8
0.135
9
0.139
10
0.135
11
0.139
12
0.139
13
440,000
14
Apr 09, 2019
['2019-04-09', '0.135', '0.143', '0.133', '0.135', '0.135', '350,000']
15
0.135
16
0.143
17
0.133
18
0.135
19
0.135
20
350,000
21
Apr 08, 2019
['2019-04-08', '0.141', '0.142', '0.131', '0.131', '0.131', '470,000']
22
0.141
23
0.142
24
0.131
25
0.131
26
0.131
27
470,000
28
Apr 04, 2019
['2019-04-04', '0.142', '0.149', '0.139', '0.146', '0.146', '160,000']
29
0.142
30
0.149
31
0.139
32
0.146
33
0.146
34
160,000
35
Apr 03, 2019
['2019-04-03', '0.149', '0.149', '0.142', '0.148', '0.148', '200,000']
36
0.149
37
0.149
38
0.142
39
0.148
40
0.148
41
200,000
42
Apr 02, 2019
['2019-04-02', '0.147', '0.150', '0.147', '0.149', '0.149', '1,030,000']
43
0.147
44
0.150
45
0.147
46
0.149
47
0.149
48
1,030,000
49
Apr 01, 2019
['2019-04-01', '0.147', '0.147', '0.147', '0.147', '0.147', '160,000']
50
0.147
51
0.147
52
0.147
53
0.147
54
0.147
55
160,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2683.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.570', '0.570', '0.560', '0.570', '0.570', '2,000']
1
0.570
2
0.570
3
0.560
4
0.570
5
0.570
6
2,000
7
Apr 10, 2019
['2019-04-10', '0.560', '0.570', '0.560', '0.570', '0.570', '112,000']
8
0.560
9
0.570
10
0.560
11
0.570
12
0.570
13
112,000
14
Apr 09, 2019
['2019-04-09', '0.560', '0.570', '0.560', '0.560', '0.560', '206,000']
15
0.560
16
0.570
17
0.560
18
0.560
19
0.560
20
206,000
21
Apr 08, 2019
['2019-04-08', '0.570', '0.570', '0.560', '0.570', '0.570', '134,000']
22
0.570
23
0.570
24
0.560
25
0.570
26
0.570
27
134,000
28
Apr 04, 2019
['2019-04-04', '0.570', '0.580', '0.560', '0.560', '0.560', '246,000']
29
0.570
30
0.580
31
0.560
32
0.560
33
0.560
34
246,000
35
Apr 03, 2019
['2019-04-03', '0.560', '0.560', '0.560', '0.560', '0.560', '60,000']
36
0.560
37
0.560
38
0.560
39
0.560
40
0.560
41
60,000
42
Apr 02, 2019
['2019-04-02', '0.560', '0.570', '0.560', '0.570', '0.570', '262,000']
43
0.560
44
0.570
45
0.560
46
0.570
47
0.570
48
262,000
49
Apr 01, 2019
['2019-04-01', '0.560', '0.580', '0.560', '0.580', '0.580', '34,000']
50
0.560
51
0.580
52
0.560
53
0.580
54
0.580
55
34,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1686.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '6.950', '6.950', '6.720', '6.780', '6.780', '798,000']
1
6.950
2
6.950
3
6.720
4
6.780
5
6.780
6
798,000
7
Apr 10, 2019
['2019-04-10', '6.870', '6.970', '6.800', '6.920', '6.920', '717,060']
8
6.870
9
6.970
10
6.800
11
6.920
12
6.920
13
717,060
14
Apr 09, 2019
['2019-04-09', '6.920', '6.950', '6.800', '6.870', '6.870', '1,792,745']
15
6.920
16
6.950
17
6.800
18
6.870
19
6.870
20
1,792,745
21
Apr 08, 2019
['2019-04-08', '7.020', '7.020', '6.840', '6.880', '6.880', '960,908']
22
7.020
23
7.020
24
6.840
25
6.880
26
6.880
27
960,908
28
Apr 04, 2019
['2019-04-04', '6.790', '7.010', '6.780', '6.990', '6.990', '1,906,508']
29
6.790
30
7.010
31
6.780
32
6.990
33
6.990
34
1,906,508
35
Apr 03, 2019
['2019-04-03', '6.910', '7.030', '6.720', '6.780', '6.780', '3,828,952']
36
6.910
37
7.030
38
6.720
39
6.780
40
6.780
41
3,828,952
42
Apr 02, 2019
['2019-04-02', '6.850', '6.970', '6.800', '6.910', '6.910', '1,796,000']
43
6.850
44
6.970
45
6.800
46
6.910
47
6.910
48
1,796,000
49
Apr 01, 2019
['2019-04-01', '6.710', '6.900', '6.710', '6.860', '6.860', '1,545,102']
50
6.710
51
6.900
52
6.710
53
6.860
54
6.860
55
1,545,102
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8513.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.250', '0.250', '0.250', '0.250', '0.250', '-']
1
0.250
2
0.250
3
0.250
4
0.250
5
0.250
6
-
7
Apr 10, 2019
['2019-04-10', '0.250', '0.250', '0.250', '0.250', '0.250', '4,000']
8
0.250
9
0.250
10
0.250
11
0.250
12
0.250
13
4,000
14
Apr 09, 2019
['2019-04-09', '0.245', '0.265', '0.245', '0.250', '0.250', '36,000']
15
0.245
16
0.265
17
0.245
18
0.250
19
0.250
20
36,000
21
Apr 08, 2019
['2019-04-08', '0.260', '0.265', '0.245', '0.250', '0.250', '164,000']
22
0.260
23
0.265
24
0.245
25
0.250
26
0.250
27
164,000
28
Apr 04, 2019
['2019-04-04', '0.245', '0.245', '0.245', '0.245', '0.245', '108,000']
29
0.245
30
0.245
31
0.245
32
0.245
33
0.245
34
108,000
35
Apr 03, 2019
['2019-04-03', '0.245', '0.245', '0.245', '0.245', '0.245', '-']
36
0.245
37
0.245
38
0.245
39
0.245
40
0.245
41
-
42
Apr 02, 2019
['2019-04-02', '0.255', '0.255', '0.231', '0.245', '0.245', '192,000']
43
0.255
44
0.255
45
0.231
46
0.245
47
0.245
48
192,000
49
Apr 01, 2019
['2019-04-01', '0.255', '0.255', '0.255', '0.255', '0.255', '-']
50
0.255
51
0.255
52
0.255
53
0.255
54
0.255
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8043.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.215', '0.223', '0.215', '0.217', '0.217', '325,000']
1
0.215
2
0.223
3
0.215
4
0.217
5
0.217
6
325,000
7
Apr 10, 2019
['2019-04-10', '0.208', '0.215', '0.208', '0.212', '0.212', '350,000']
8
0.208
9
0.215
10
0.208
11
0.212
12
0.212
13
350,000
14
Apr 09, 2019
['2019-04-09', '0.207', '0.207', '0.206', '0.207', '0.207', '100,000']
15
0.207
16
0.207
17
0.206
18
0.207
19
0.207
20
100,000
21
Apr 08, 2019
['2019-04-08', '0.202', '0.206', '0.202', '0.206', '0.206', '240,000']
22
0.202
23
0.206
24
0.202
25
0.206
26
0.206
27
240,000
28
Apr 04, 2019
['2019-04-04', '0.196', '0.204', '0.195', '0.202', '0.202', '60,000']
29
0.196
30
0.204
31
0.195
32
0.202
33
0.202
34
60,000
35
Apr 03, 2019
['2019-04-03', '0.193', '0.194', '0.193', '0.193', '0.193', '105,000']
36
0.193
37
0.194
38
0.193
39
0.193
40
0.193
41
105,000
42
Apr 02, 2019
['2019-04-02', '0.189', '0.193', '0.189', '0.191', '0.191', '105,000']
43
0.189
44
0.193
45
0.189
46
0.191
47
0.191
48
105,000
49
Apr 01, 2019
['2019-04-01', '0.199', '0.204', '0.179', '0.185', '0.185', '2,245,000']
50
0.199
51
0.204
52
0.179
53
0.185
54
0.185
55
2,245,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1665.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.020', '1.030', '0.980', '1.000', '1.000', '1,880,000']
1
1.020
2
1.030
3
0.980
4
1.000
5
1.000
6
1,880,000
7
Apr 10, 2019
['2019-04-10', '1.020', '1.030', '1.000', '1.030', '1.030', '3,256,000']
8
1.020
9
1.030
10
1.000
11
1.030
12
1.030
13
3,256,000
14
Apr 09, 2019
['2019-04-09', '0.990', '1.020', '0.990', '1.010', '1.010', '3,044,000']
15
0.990
16
1.020
17
0.990
18
1.010
19
1.010
20
3,044,000
21
Apr 08, 2019
['2019-04-08', '0.950', '1.000', '0.940', '0.980', '0.980', '2,260,000']
22
0.950
23
1.000
24
0.940
25
0.980
26
0.980
27
2,260,000
28
Apr 04, 2019
['2019-04-04', '0.940', '0.960', '0.940', '0.940', '0.940', '492,000']
29
0.940
30
0.960
31
0.940
32
0.940
33
0.940
34
492,000
35
Apr 03, 2019
['2019-04-03', '0.930', '0.950', '0.930', '0.940', '0.940', '2,952,000']
36
0.930
37
0.950
38
0.930
39
0.940
40
0.940
41
2,952,000
42
Apr 02, 2019
['2019-04-02', '0.960', '0.960', '0.930', '0.930', '0.930', '1,936,000']
43
0.960
44
0.960
45
0.930
46
0.930
47
0.930
48
1,936,000
49
Apr 01, 2019
['2019-04-01', '0.930', '0.960', '0.930', '0.940', '0.940', '16,643,666']
50
0.930
51
0.960
52
0.930
53
0.940
54
0.940
55
16,643,666
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8287.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.201', '0.223', '0.201', '0.220', '0.220', '1,250,000']
1
0.201
2
0.223
3
0.201
4
0.220
5
0.220
6
1,250,000
7
Apr 10, 2019
['2019-04-10', '0.201', '0.205', '0.200', '0.200', '0.200', '460,000']
8
0.201
9
0.205
10
0.200
11
0.200
12
0.200
13
460,000
14
Apr 09, 2019
['2019-04-09', '0.200', '0.200', '0.200', '0.200', '0.200', '170,000']
15
0.200
16
0.200
17
0.200
18
0.200
19
0.200
20
170,000
21
Apr 08, 2019
['2019-04-08', '0.205', '0.205', '0.205', '0.205', '0.205', '70,000']
22
0.205
23
0.205
24
0.205
25
0.205
26
0.205
27
70,000
28
Apr 04, 2019
['2019-04-04', '0.211', '0.211', '0.211', '0.211', '0.211', '-']
29
0.211
30
0.211
31
0.211
32
0.211
33
0.211
34
-
35
Apr 03, 2019
['2019-04-03', '0.206', '0.213', '0.213', '0.213', '0.213', '70,000']
36
0.206
37
0.213
38
0.213
39
0.213
40
0.213
41
70,000
42
Apr 02, 2019
['2019-04-02', '0.204', '0.215', '0.204', '0.213', '0.213', '12,360,000']
43
0.204
44
0.215
45
0.204
46
0.213
47
0.213
48
12,360,000
49
Apr 01, 2019
['2019-04-01', '0.199', '0.220', '0.199', '0.205', '0.205', '12,910,000']
50
0.199
51
0.220
52
0.199
53
0.205
54
0.205
55
12,910,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2139.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.260', '2.260', '2.210', '2.210', '2.210', '9,000']
1
2.260
2
2.260
3
2.210
4
2.210
5
2.210
6
9,000
7
Apr 10, 2019
['2019-04-10', '2.200', '2.300', '2.200', '2.280', '2.280', '13,000']
8
2.200
9
2.300
10
2.200
11
2.280
12
2.280
13
13,000
14
Apr 09, 2019
['2019-04-09', '2.230', '2.230', '2.200', '2.210', '2.210', '239,000']
15
2.230
16
2.230
17
2.200
18
2.210
19
2.210
20
239,000
21
Apr 08, 2019
['2019-04-08', '2.260', '2.260', '2.240', '2.240', '2.240', '16,000']
22
2.260
23
2.260
24
2.240
25
2.240
26
2.240
27
16,000
28
Apr 04, 2019
['2019-04-04', '2.370', '2.370', '2.260', '2.260', '2.260', '112,000']
29
2.370
30
2.370
31
2.260
32
2.260
33
2.260
34
112,000
35
Apr 03, 2019
['2019-04-03', '2.400', '2.400', '2.250', '2.370', '2.370', '623,000']
36
2.400
37
2.400
38
2.250
39
2.370
40
2.370
41
623,000
42
Apr 02, 2019
['2019-04-02', '2.200', '2.460', '2.200', '2.450', '2.450', '603,000']
43
2.200
44
2.460
45
2.200
46
2.450
47
2.450
48
603,000
49
Apr 01, 2019
['2019-04-01', '2.270', '2.280', '2.200', '2.200', '2.200', '144,000']
50
2.270
51
2.280
52
2.200
53
2.200
54
2.200
55
144,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8479.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.315', '0.320', '0.315', '0.320', '0.320', '764,000']
1
0.315
2
0.320
3
0.315
4
0.320
5
0.320
6
764,000
7
Apr 10, 2019
['2019-04-10', '0.320', '0.320', '0.310', '0.315', '0.315', '3,288,000']
8
0.320
9
0.320
10
0.310
11
0.315
12
0.315
13
3,288,000
14
Apr 09, 2019
['2019-04-09', '0.320', '0.325', '0.315', '0.325', '0.325', '1,104,000']
15
0.320
16
0.325
17
0.315
18
0.325
19
0.325
20
1,104,000
21
Apr 08, 2019
['2019-04-08', '0.320', '0.325', '0.315', '0.315', '0.315', '1,608,000']
22
0.320
23
0.325
24
0.315
25
0.315
26
0.315
27
1,608,000
28
Apr 04, 2019
['2019-04-04', '0.335', '0.335', '0.310', '0.320', '0.320', '4,364,000']
29
0.335
30
0.335
31
0.310
32
0.320
33
0.320
34
4,364,000
35
Apr 03, 2019
['2019-04-03', '0.330', '0.345', '0.325', '0.340', '0.340', '324,000']
36
0.330
37
0.345
38
0.325
39
0.340
40
0.340
41
324,000
42
Apr 02, 2019
['2019-04-02', '0.330', '0.345', '0.330', '0.340', '0.340', '112,000']
43
0.330
44
0.345
45
0.330
46
0.340
47
0.340
48
112,000
49
Apr 01, 2019
['2019-04-01', '0.330', '0.345', '0.330', '0.345', '0.345', '820,000']
50
0.330
51
0.345
52
0.330
53
0.345
54
0.345
55
820,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8371.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.680', '0.710', '0.680', '0.710', '0.710', '20,000']
1
0.680
2
0.710
3
0.680
4
0.710
5
0.710
6
20,000
7
Apr 10, 2019
['2019-04-10', '0.700', '0.700', '0.700', '0.700', '0.700', '-']
8
0.700
9
0.700
10
0.700
11
0.700
12
0.700
13
-
14
Apr 09, 2019
['2019-04-09', '0.710', '0.710', '0.710', '0.710', '0.710', '-']
15
0.710
16
0.710
17
0.710
18
0.710
19
0.710
20
-
21
Apr 08, 2019
['2019-04-08', '0.710', '0.710', '0.710', '0.710', '0.710', '20,000']
22
0.710
23
0.710
24
0.710
25
0.710
26
0.710
27
20,000
28
Apr 04, 2019
['2019-04-04', '0.710', '0.710', '0.710', '0.710', '0.710', '24,000']
29
0.710
30
0.710
31
0.710
32
0.710
33
0.710
34
24,000
35
Apr 03, 2019
['2019-04-03', '0.700', '0.700', '0.700', '0.700', '0.700', '-']
36
0.700
37
0.700
38
0.700
39
0.700
40
0.700
41
-
42
Apr 02, 2019
['2019-04-02', '0.680', '0.710', '0.680', '0.700', '0.700', '124,000']
43
0.680
44
0.710
45
0.680
46
0.700
47
0.700
48
124,000
49
Apr 01, 2019
['2019-04-01', '0.710', '0.710', '0.710', '0.710', '0.710', '32,000']
50
0.710
51
0.710
52
0.710
53
0.710
54
0.710
55
32,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6182.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.480', '0.485', '0.465', '0.470', '0.470', '2,576,000']
1
0.480
2
0.485
3
0.465
4
0.470
5
0.470
6
2,576,000
7
Apr 10, 2019
['2019-04-10', '0.490', '0.490', '0.485', '0.485', '0.485', '1,096,000']
8
0.490
9
0.490
10
0.485
11
0.485
12
0.485
13
1,096,000
14
Apr 09, 2019
['2019-04-09', '0.485', '0.490', '0.480', '0.485', '0.485', '2,864,000']
15
0.485
16
0.490
17
0.480
18
0.485
19
0.485
20
2,864,000
21
Apr 08, 2019
['2019-04-08', '0.485', '0.490', '0.480', '0.490', '0.490', '3,552,000']
22
0.485
23
0.490
24
0.480
25
0.490
26
0.490
27
3,552,000
28
Apr 04, 2019
['2019-04-04', '0.485', '0.490', '0.480', '0.485', '0.485', '3,672,000']
29
0.485
30
0.490
31
0.480
32
0.485
33
0.485
34
3,672,000
35
Apr 03, 2019
['2019-04-03', '0.485', '0.490', '0.475', '0.480', '0.480', '2,840,000']
36
0.485
37
0.490
38
0.475
39
0.480
40
0.480
41
2,840,000
42
Apr 02, 2019
['2019-04-02', '0.490', '0.490', '0.480', '0.490', '0.490', '3,752,000']
43
0.490
44
0.490
45
0.480
46
0.490
47
0.490
48
3,752,000
49
Apr 01, 2019
['2019-04-01', '0.490', '0.495', '0.485', '0.490', '0.490', '2,896,000']
50
0.490
51
0.495
52
0.485
53
0.490
54
0.490
55
2,896,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8313.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.310', '0.315', '0.305', '0.310', '0.310', '6,570,000']
1
0.310
2
0.315
3
0.305
4
0.310
5
0.310
6
6,570,000
7
Apr 10, 2019
['2019-04-10', '0.305', '0.310', '0.305', '0.310', '0.310', '4,260,000']
8
0.305
9
0.310
10
0.305
11
0.310
12
0.310
13
4,260,000
14
Apr 09, 2019
['2019-04-09', '0.305', '0.315', '0.305', '0.310', '0.310', '4,420,000']
15
0.305
16
0.315
17
0.305
18
0.310
19
0.310
20
4,420,000
21
Apr 08, 2019
['2019-04-08', '0.315', '0.315', '0.305', '0.310', '0.310', '7,170,000']
22
0.315
23
0.315
24
0.305
25
0.310
26
0.310
27
7,170,000
28
Apr 04, 2019
['2019-04-04', '0.295', '0.335', '0.295', '0.315', '0.315', '7,720,000']
29
0.295
30
0.335
31
0.295
32
0.315
33
0.315
34
7,720,000
35
Apr 03, 2019
['2019-04-03', '0.300', '0.305', '0.295', '0.305', '0.305', '6,440,000']
36
0.300
37
0.305
38
0.295
39
0.305
40
0.305
41
6,440,000
42
Apr 02, 2019
['2019-04-02', '0.300', '0.305', '0.295', '0.305', '0.305', '6,190,000']
43
0.300
44
0.305
45
0.295
46
0.305
47
0.305
48
6,190,000
49
Apr 01, 2019
['2019-04-01', '0.295', '0.305', '0.295', '0.305', '0.305', '6,800,000']
50
0.295
51
0.305
52
0.295
53
0.305
54
0.305
55
6,800,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8285.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.120', '0.120', '0.120', '0.120', '0.120', '-']
1
0.120
2
0.120
3
0.120
4
0.120
5
0.120
6
-
7
Apr 10, 2019
['2019-04-10', '0.119', '0.120', '0.119', '0.120', '0.120', '160,000']
8
0.119
9
0.120
10
0.119
11
0.120
12
0.120
13
160,000
14
Apr 09, 2019
['2019-04-09', '0.121', '0.122', '0.121', '0.122', '0.122', '270,000']
15
0.121
16
0.122
17
0.121
18
0.122
19
0.122
20
270,000
21
Apr 08, 2019
['2019-04-08', '0.120', '0.123', '0.120', '0.123', '0.123', '125,000']
22
0.120
23
0.123
24
0.120
25
0.123
26
0.123
27
125,000
28
Apr 04, 2019
['2019-04-04', '0.117', '0.119', '0.117', '0.119', '0.119', '10,000']
29
0.117
30
0.119
31
0.117
32
0.119
33
0.119
34
10,000
35
Apr 03, 2019
['2019-04-03', '0.123', '0.123', '0.123', '0.123', '0.123', '-']
36
0.123
37
0.123
38
0.123
39
0.123
40
0.123
41
-
42
Apr 02, 2019
['2019-04-02', '0.123', '0.123', '0.123', '0.123', '0.123', '-']
43
0.123
44
0.123
45
0.123
46
0.123
47
0.123
48
-
49
Apr 01, 2019
['2019-04-01', '0.123', '0.123', '0.123', '0.123', '0.123', '-']
50
0.123
51
0.123
52
0.123
53
0.123
54
0.123
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8493.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.120', '0.120', '0.120', '0.120', '0.120', '-']
1
0.120
2
0.120
3
0.120
4
0.120
5
0.120
6
-
7
Apr 10, 2019
['2019-04-10', '0.120', '0.120', '0.120', '0.120', '0.120', '-']
8
0.120
9
0.120
10
0.120
11
0.120
12
0.120
13
-
14
Apr 09, 2019
['2019-04-09', '0.111', '0.120', '0.111', '0.120', '0.120', '60,000']
15
0.111
16
0.120
17
0.111
18
0.120
19
0.120
20
60,000
21
Apr 08, 2019
['2019-04-08', '0.128', '0.128', '0.128', '0.128', '0.128', '-']
22
0.128
23
0.128
24
0.128
25
0.128
26
0.128
27
-
28
Apr 04, 2019
['2019-04-04', '0.125', '0.125', '0.125', '0.128', '0.128', '12,000']
29
0.125
30
0.125
31
0.125
32
0.128
33
0.128
34
12,000
35
Apr 03, 2019
['2019-04-03', '0.133', '0.135', '0.133', '0.135', '0.135', '1,824,000']
36
0.133
37
0.135
38
0.133
39
0.135
40
0.135
41
1,824,000
42
Apr 02, 2019
['2019-04-02', '0.130', '0.130', '0.130', '0.130', '0.130', '-']
43
0.130
44
0.130
45
0.130
46
0.130
47
0.130
48
-
49
Apr 01, 2019
['2019-04-01', '0.130', '0.130', '0.130', '0.130', '0.130', '228,000']
50
0.130
51
0.130
52
0.130
53
0.130
54
0.130
55
228,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8487.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.040', '1.050', '0.970', '0.970', '0.970', '1,410,000']
1
1.040
2
1.050
3
0.970
4
0.970
5
0.970
6
1,410,000
7
Apr 10, 2019
['2019-04-10', '1.000', '1.080', '0.970', '1.080', '1.080', '910,000']
8
1.000
9
1.080
10
0.970
11
1.080
12
1.080
13
910,000
14
Apr 09, 2019
['2019-04-09', '1.010', '1.030', '0.990', '0.990', '0.990', '940,000']
15
1.010
16
1.030
17
0.990
18
0.990
19
0.990
20
940,000
21
Apr 08, 2019
['2019-04-08', '1.010', '1.010', '1.010', '1.010', '1.010', '-']
22
1.010
23
1.010
24
1.010
25
1.010
26
1.010
27
-
28
Apr 04, 2019
['2019-04-04', '1.050', '1.060', '1.030', '1.030', '1.030', '750,000']
29
1.050
30
1.060
31
1.030
32
1.030
33
1.030
34
750,000
35
Apr 03, 2019
['2019-04-03', '1.040', '1.100', '1.040', '1.070', '1.070', '1,150,000']
36
1.040
37
1.100
38
1.040
39
1.070
40
1.070
41
1,150,000
42
Apr 02, 2019
['2019-04-02', '1.070', '1.100', '1.040', '1.080', '1.080', '470,000']
43
1.070
44
1.100
45
1.040
46
1.080
47
1.080
48
470,000
49
Apr 01, 2019
['2019-04-01', '1.100', '1.100', '1.100', '1.100', '1.100', '-']
50
1.100
51
1.100
52
1.100
53
1.100
54
1.100
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2448.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.170', '1.170', '1.150', '1.150', '1.150', '37,500']
1
1.170
2
1.170
3
1.150
4
1.150
5
1.150
6
37,500
7
Apr 10, 2019
['2019-04-10', '1.190', '1.190', '1.060', '1.160', '1.160', '112,500']
8
1.190
9
1.190
10
1.060
11
1.160
12
1.160
13
112,500
14
Apr 09, 2019
['2019-04-09', '1.180', '1.190', '1.180', '1.190', '1.190', '10,000']
15
1.180
16
1.190
17
1.180
18
1.190
19
1.190
20
10,000
21
Apr 08, 2019
['2019-04-08', '1.210', '1.240', '1.200', '1.190', '1.190', '47,500']
22
1.210
23
1.240
24
1.200
25
1.190
26
1.190
27
47,500
28
Apr 04, 2019
['2019-04-04', '1.180', '1.220', '1.180', '1.190', '1.190', '105,000']
29
1.180
30
1.220
31
1.180
32
1.190
33
1.190
34
105,000
35
Apr 03, 2019
['2019-04-03', '1.180', '1.200', '1.150', '1.170', '1.170', '197,500']
36
1.180
37
1.200
38
1.150
39
1.170
40
1.170
41
197,500
42
Apr 02, 2019
['2019-04-02', '1.170', '1.240', '1.170', '1.200', '1.200', '425,000']
43
1.170
44
1.240
45
1.170
46
1.200
47
1.200
48
425,000
49
Apr 01, 2019
['2019-04-01', '1.170', '1.180', '1.140', '1.170', '1.170', '340,000']
50
1.170
51
1.180
52
1.140
53
1.170
54
1.170
55
340,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2292.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.220', '1.220', '1.210', '1.210', '1.210', '82,000']
1
1.220
2
1.220
3
1.210
4
1.210
5
1.210
6
82,000
7
Apr 10, 2019
['2019-04-10', '1.230', '1.270', '1.230', '1.230', '1.230', '38,000']
8
1.230
9
1.270
10
1.230
11
1.230
12
1.230
13
38,000
14
Apr 09, 2019
['2019-04-09', '1.270', '1.270', '1.230', '1.240', '1.240', '46,020']
15
1.270
16
1.270
17
1.230
18
1.240
19
1.240
20
46,020
21
Apr 08, 2019
['2019-04-08', '1.230', '1.270', '1.230', '1.270', '1.270', '54,000']
22
1.230
23
1.270
24
1.230
25
1.270
26
1.270
27
54,000
28
Apr 04, 2019
['2019-04-04', '1.230', '1.230', '1.230', '1.230', '1.230', '2,000']
29
1.230
30
1.230
31
1.230
32
1.230
33
1.230
34
2,000
35
Apr 03, 2019
['2019-04-03', '1.230', '1.230', '1.230', '1.230', '1.230', '-']
36
1.230
37
1.230
38
1.230
39
1.230
40
1.230
41
-
42
Apr 02, 2019
['2019-04-02', '1.230', '1.250', '1.220', '1.220', '1.220', '100,000']
43
1.230
44
1.250
45
1.220
46
1.220
47
1.220
48
100,000
49
Apr 01, 2019
['2019-04-01', '1.270', '1.270', '1.270', '1.270', '1.270', '-']
50
1.270
51
1.270
52
1.270
53
1.270
54
1.270
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6158.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '5.350', '5.390', '5.270', '5.280', '5.280', '5,703,000']
1
5.350
2
5.390
3
5.270
4
5.280
5
5.280
6
5,703,000
7
Apr 10, 2019
['2019-04-10', '5.380', '5.430', '5.280', '5.350', '5.350', '7,073,000']
8
5.380
9
5.430
10
5.280
11
5.350
12
5.350
13
7,073,000
14
Apr 09, 2019
['2019-04-09', '5.350', '5.390', '5.280', '5.340', '5.340', '5,687,000']
15
5.350
16
5.390
17
5.280
18
5.340
19
5.340
20
5,687,000
21
Apr 08, 2019
['2019-04-08', '5.390', '5.420', '5.300', '5.310', '5.310', '5,823,000']
22
5.390
23
5.420
24
5.300
25
5.310
26
5.310
27
5,823,000
28
Apr 04, 2019
['2019-04-04', '5.450', '5.480', '5.300', '5.350', '5.350', '5,007,000']
29
5.450
30
5.480
31
5.300
32
5.350
33
5.350
34
5,007,000
35
Apr 03, 2019
['2019-04-03', '5.500', '5.500', '5.370', '5.430', '5.430', '6,001,908']
36
5.500
37
5.500
38
5.370
39
5.430
40
5.430
41
6,001,908
42
Apr 02, 2019
['2019-04-02', '5.550', '5.550', '5.440', '5.470', '5.470', '5,510,000']
43
5.550
44
5.550
45
5.440
46
5.470
47
5.470
48
5,510,000
49
Apr 01, 2019
['2019-04-01', '5.460', '5.600', '5.450', '5.520', '5.520', '5,563,000']
50
5.460
51
5.600
52
5.450
53
5.520
54
5.520
55
5,563,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3699.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.870', '0.900', '0.840', '0.840', '0.840', '80,000']
1
0.870
2
0.900
3
0.840
4
0.840
5
0.840
6
80,000
7
Apr 10, 2019
['2019-04-10', '0.810', '0.830', '0.810', '0.830', '0.830', '66,000']
8
0.810
9
0.830
10
0.810
11
0.830
12
0.830
13
66,000
14
Apr 09, 2019
['2019-04-09', '0.830', '0.830', '0.830', '0.830', '0.830', '2,000']
15
0.830
16
0.830
17
0.830
18
0.830
19
0.830
20
2,000
21
Apr 08, 2019
['2019-04-08', '0.830', '0.830', '0.830', '0.830', '0.830', '-']
22
0.830
23
0.830
24
0.830
25
0.830
26
0.830
27
-
28
Apr 04, 2019
['2019-04-04', '0.830', '0.830', '0.830', '0.830', '0.830', '-']
29
0.830
30
0.830
31
0.830
32
0.830
33
0.830
34
-
35
Apr 03, 2019
['2019-04-03', '0.830', '0.850', '0.820', '0.820', '0.820', '66,000']
36
0.830
37
0.850
38
0.820
39
0.820
40
0.820
41
66,000
42
Apr 02, 2019
['2019-04-02', '0.820', '0.820', '0.820', '0.820', '0.820', '-']
43
0.820
44
0.820
45
0.820
46
0.820
47
0.820
48
-
49
Apr 01, 2019
['2019-04-01', '0.820', '0.820', '0.820', '0.820', '0.820', '2,000']
50
0.820
51
0.820
52
0.820
53
0.820
54
0.820
55
2,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3309.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.970', '4.990', '4.900', '4.920', '4.920', '1,026,000']
1
4.970
2
4.990
3
4.900
4
4.920
5
4.920
6
1,026,000
7
Apr 10, 2019
['2019-04-10', '4.930', '4.990', '4.900', '4.940', '4.940', '1,166,000']
8
4.930
9
4.990
10
4.900
11
4.940
12
4.940
13
1,166,000
14
Apr 09, 2019
['2019-04-09', '4.960', '4.960', '4.920', '4.930', '4.930', '1,260,000']
15
4.960
16
4.960
17
4.920
18
4.930
19
4.930
20
1,260,000
21
Apr 08, 2019
['2019-04-08', '4.960', '5.040', '4.940', '4.960', '4.960', '1,812,000']
22
4.960
23
5.040
24
4.940
25
4.960
26
4.960
27
1,812,000
28
Apr 04, 2019
['2019-04-04', '4.980', '5.020', '4.940', '4.950', '4.950', '872,000']
29
4.980
30
5.020
31
4.940
32
4.950
33
4.950
34
872,000
35
Apr 03, 2019
['2019-04-03', '4.980', '4.990', '4.940', '4.980', '4.980', '906,000']
36
4.980
37
4.990
38
4.940
39
4.980
40
4.980
41
906,000
42
Apr 02, 2019
['2019-04-02', '4.990', '5.020', '4.900', '4.930', '4.930', '1,454,000']
43
4.990
44
5.020
45
4.900
46
4.930
47
4.930
48
1,454,000
49
Apr 01, 2019
['2019-04-01', '5.010', '5.060', '4.950', '4.980', '4.980', '664,000']
50
5.010
51
5.060
52
4.950
53
4.980
54
4.980
55
664,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8509.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.580', '0.580', '0.580', '0.580', '0.580', '-']
1
0.580
2
0.580
3
0.580
4
0.580
5
0.580
6
-
7
Apr 10, 2019
['2019-04-10', '0.610', '0.610', '0.550', '0.580', '0.580', '40,000']
8
0.610
9
0.610
10
0.550
11
0.580
12
0.580
13
40,000
14
Apr 09, 2019
['2019-04-09', '0.620', '0.620', '0.550', '0.620', '0.620', '68,000']
15
0.620
16
0.620
17
0.550
18
0.620
19
0.620
20
68,000
21
Apr 08, 2019
['2019-04-08', '0.630', '0.630', '0.630', '0.630', '0.630', '-']
22
0.630
23
0.630
24
0.630
25
0.630
26
0.630
27
-
28
Apr 04, 2019
['2019-04-04', '0.630', '0.630', '0.630', '0.630', '0.630', '-']
29
0.630
30
0.630
31
0.630
32
0.630
33
0.630
34
-
35
Apr 03, 2019
['2019-04-03', '0.660', '0.660', '0.600', '0.640', '0.640', '72,000']
36
0.660
37
0.660
38
0.600
39
0.640
40
0.640
41
72,000
42
Apr 02, 2019
['2019-04-02', '0.690', '0.690', '0.680', '0.670', '0.670', '224,000']
43
0.690
44
0.690
45
0.680
46
0.670
47
0.670
48
224,000
49
Apr 01, 2019
['2019-04-01', '0.690', '0.760', '0.660', '0.680', '0.680', '1,856,000']
50
0.690
51
0.760
52
0.660
53
0.680
54
0.680
55
1,856,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8350.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.270', '0.270', '0.270', '0.270', '0.270', '-']
1
0.270
2
0.270
3
0.270
4
0.270
5
0.270
6
-
7
Apr 10, 2019
['2019-04-10', '0.270', '0.270', '0.270', '0.270', '0.270', '-']
8
0.270
9
0.270
10
0.270
11
0.270
12
0.270
13
-
14
Apr 09, 2019
['2019-04-09', '0.270', '0.270', '0.270', '0.270', '0.270', '-']
15
0.270
16
0.270
17
0.270
18
0.270
19
0.270
20
-
21
Apr 08, 2019
['2019-04-08', '0.260', '0.270', '0.260', '0.270', '0.270', '56,000']
22
0.260
23
0.270
24
0.260
25
0.270
26
0.270
27
56,000
28
Apr 04, 2019
['2019-04-04', '0.260', '0.260', '0.260', '0.260', '0.260', '-']
29
0.260
30
0.260
31
0.260
32
0.260
33
0.260
34
-
35
Apr 03, 2019
['2019-04-03', '0.255', '0.260', '0.255', '0.260', '0.260', '80,000']
36
0.255
37
0.260
38
0.255
39
0.260
40
0.260
41
80,000
42
Apr 02, 2019
['2019-04-02', '0.255', '0.260', '0.233', '0.260', '0.260', '432,000']
43
0.255
44
0.260
45
0.233
46
0.260
47
0.260
48
432,000
49
Apr 01, 2019
['2019-04-01', '0.260', '0.260', '0.260', '0.260', '0.260', '-']
50
0.260
51
0.260
52
0.260
53
0.260
54
0.260
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2025.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.710', '1.750', '1.710', '1.740', '1.740', '148,000']
1
1.710
2
1.750
3
1.710
4
1.740
5
1.740
6
148,000
7
Apr 10, 2019
['2019-04-10', '1.680', '1.720', '1.680', '1.720', '1.720', '60,000']
8
1.680
9
1.720
10
1.680
11
1.720
12
1.720
13
60,000
14
Apr 09, 2019
['2019-04-09', '1.680', '1.750', '1.680', '1.700', '1.700', '372,000']
15
1.680
16
1.750
17
1.680
18
1.700
19
1.700
20
372,000
21
Apr 08, 2019
['2019-04-08', '1.650', '1.700', '1.650', '1.670', '1.670', '662,000']
22
1.650
23
1.700
24
1.650
25
1.670
26
1.670
27
662,000
28
Apr 04, 2019
['2019-04-04', '1.590', '1.680', '1.590', '1.650', '1.650', '216,000']
29
1.590
30
1.680
31
1.590
32
1.650
33
1.650
34
216,000
35
Apr 03, 2019
['2019-04-03', '1.560', '1.590', '1.560', '1.590', '1.590', '48,000']
36
1.560
37
1.590
38
1.560
39
1.590
40
1.590
41
48,000
42
Apr 02, 2019
['2019-04-02', '1.520', '1.580', '1.520', '1.580', '1.580', '82,000']
43
1.520
44
1.580
45
1.520
46
1.580
47
1.580
48
82,000
49
Apr 01, 2019
['2019-04-01', '1.630', '1.630', '1.580', '1.580', '1.580', '466,000']
50
1.630
51
1.630
52
1.580
53
1.580
54
1.580
55
466,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8506.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.108', '0.113', '0.108', '0.109', '0.109', '228,000']
1
0.108
2
0.113
3
0.108
4
0.109
5
0.109
6
228,000
7
Apr 10, 2019
['2019-04-10', '0.106', '0.114', '0.106', '0.108', '0.108', '444,000']
8
0.106
9
0.114
10
0.106
11
0.108
12
0.108
13
444,000
14
Apr 09, 2019
['2019-04-09', '0.108', '0.110', '0.102', '0.108', '0.108', '528,000']
15
0.108
16
0.110
17
0.102
18
0.108
19
0.108
20
528,000
21
Apr 08, 2019
['2019-04-08', '0.108', '0.108', '0.108', '0.108', '0.108', '-']
22
0.108
23
0.108
24
0.108
25
0.108
26
0.108
27
-
28
Apr 04, 2019
['2019-04-04', '0.111', '0.111', '0.111', '0.111', '0.111', '-']
29
0.111
30
0.111
31
0.111
32
0.111
33
0.111
34
-
35
Apr 03, 2019
['2019-04-03', '0.111', '0.113', '0.112', '0.113', '0.113', '60,000']
36
0.111
37
0.113
38
0.112
39
0.113
40
0.113
41
60,000
42
Apr 02, 2019
['2019-04-02', '0.113', '0.116', '0.110', '0.110', '0.110', '684,000']
43
0.113
44
0.116
45
0.110
46
0.110
47
0.110
48
684,000
49
Apr 01, 2019
['2019-04-01', '0.115', '0.115', '0.112', '0.113', '0.113', '996,000']
50
0.115
51
0.115
52
0.112
53
0.113
54
0.113
55
996,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8501.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.350', '1.350', '1.350', '1.350', '1.350', '-']
1
1.350
2
1.350
3
1.350
4
1.350
5
1.350
6
-
7
Apr 10, 2019
['2019-04-10', '1.350', '1.350', '1.350', '1.350', '1.350', '14,000']
8
1.350
9
1.350
10
1.350
11
1.350
12
1.350
13
14,000
14
Apr 09, 2019
['2019-04-09', '1.350', '1.350', '1.350', '1.350', '1.350', '-']
15
1.350
16
1.350
17
1.350
18
1.350
19
1.350
20
-
21
Apr 08, 2019
['2019-04-08', '1.380', '1.380', '1.380', '1.370', '1.370', '20,000']
22
1.380
23
1.380
24
1.380
25
1.370
26
1.370
27
20,000
28
Apr 04, 2019
['2019-04-04', '1.390', '1.390', '1.390', '1.390', '1.390', '-']
29
1.390
30
1.390
31
1.390
32
1.390
33
1.390
34
-
35
Apr 03, 2019
['2019-04-03', '1.390', '1.390', '1.390', '1.390', '1.390', '-']
36
1.390
37
1.390
38
1.390
39
1.390
40
1.390
41
-
42
Apr 02, 2019
['2019-04-02', '1.400', '1.400', '1.400', '1.400', '1.400', '-']
43
1.400
44
1.400
45
1.400
46
1.400
47
1.400
48
-
49
Apr 01, 2019
['2019-04-01', '1.470', '1.470', '1.470', '1.470', '1.470', '-']
50
1.470
51
1.470
52
1.470
53
1.470
54
1.470
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3738.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.040', '3.100', '2.990', '3.090', '3.090', '2,069,000']
1
3.040
2
3.100
3
2.990
4
3.090
5
3.090
6
2,069,000
7
Apr 10, 2019
['2019-04-10', '3.090', '3.090', '3.000', '3.040', '3.040', '3,091,000']
8
3.090
9
3.090
10
3.000
11
3.040
12
3.040
13
3,091,000
14
Apr 09, 2019
['2019-04-09', '3.110', '3.110', '3.040', '3.100', '3.100', '2,194,856']
15
3.110
16
3.110
17
3.040
18
3.100
19
3.100
20
2,194,856
21
Apr 08, 2019
['2019-04-08', '3.100', '3.150', '3.050', '3.100', '3.100', '2,760,000']
22
3.100
23
3.150
24
3.050
25
3.100
26
3.100
27
2,760,000
28
Apr 04, 2019
['2019-04-04', '2.960', '3.100', '2.960', '3.100', '3.100', '4,041,000']
29
2.960
30
3.100
31
2.960
32
3.100
33
3.100
34
4,041,000
35
Apr 03, 2019
['2019-04-03', '3.160', '3.160', '3.000', '3.010', '3.010', '3,151,000']
36
3.160
37
3.160
38
3.000
39
3.010
40
3.010
41
3,151,000
42
Apr 02, 2019
['2019-04-02', '3.100', '3.130', '3.050', '3.130', '3.130', '1,390,000']
43
3.100
44
3.130
45
3.050
46
3.130
47
3.130
48
1,390,000
49
Apr 01, 2019
['2019-04-01', '3.080', '3.150', '2.950', '3.070', '3.070', '5,333,336']
50
3.080
51
3.150
52
2.950
53
3.070
54
3.070
55
5,333,336
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1730.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.930', '0.950', '0.930', '0.950', '0.950', '74,000']
1
0.930
2
0.950
3
0.930
4
0.950
5
0.950
6
74,000
7
Apr 10, 2019
['2019-04-10', '0.910', '0.940', '0.910', '0.940', '0.940', '12,000']
8
0.910
9
0.940
10
0.910
11
0.940
12
0.940
13
12,000
14
Apr 09, 2019
['2019-04-09', '0.910', '0.910', '0.910', '0.910', '0.910', '-']
15
0.910
16
0.910
17
0.910
18
0.910
19
0.910
20
-
21
Apr 08, 2019
['2019-04-08', '0.910', '0.930', '0.910', '0.910', '0.910', '30,000']
22
0.910
23
0.930
24
0.910
25
0.910
26
0.910
27
30,000
28
Apr 04, 2019
['2019-04-04', '0.900', '0.920', '0.900', '0.910', '0.910', '138,000']
29
0.900
30
0.920
31
0.900
32
0.910
33
0.910
34
138,000
35
Apr 03, 2019
['2019-04-03', '0.890', '0.910', '0.890', '0.910', '0.910', '86,000']
36
0.890
37
0.910
38
0.890
39
0.910
40
0.910
41
86,000
42
Apr 02, 2019
['2019-04-02', '0.880', '0.880', '0.880', '0.880', '0.880', '-']
43
0.880
44
0.880
45
0.880
46
0.880
47
0.880
48
-
49
Apr 01, 2019
['2019-04-01', '0.900', '0.900', '0.880', '0.880', '0.880', '40,000']
50
0.900
51
0.900
52
0.880
53
0.880
54
0.880
55
40,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8422.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.255', '0.335', '0.245', '0.246', '0.246', '3,480,000']
1
0.255
2
0.335
3
0.245
4
0.246
5
0.246
6
3,480,000
7
Apr 10, 2019
['2019-04-10', '0.237', '0.270', '0.237', '0.248', '0.248', '11,610,000']
8
0.237
9
0.270
10
0.237
11
0.248
12
0.248
13
11,610,000
14
Apr 09, 2019
['2019-04-09', '0.255', '0.260', '0.249', '0.250', '0.250', '8,900,000']
15
0.255
16
0.260
17
0.249
18
0.250
19
0.250
20
8,900,000
21
Apr 08, 2019
['2019-04-08', '0.231', '0.250', '0.231', '0.250', '0.250', '8,280,000']
22
0.231
23
0.250
24
0.231
25
0.250
26
0.250
27
8,280,000
28
Apr 04, 2019
['2019-04-04', '0.255', '0.255', '0.255', '0.255', '0.255', '-']
29
0.255
30
0.255
31
0.255
32
0.255
33
0.255
34
-
35
Apr 03, 2019
['2019-04-03', '0.255', '0.255', '0.255', '0.255', '0.255', '60,000']
36
0.255
37
0.255
38
0.255
39
0.255
40
0.255
41
60,000
42
Apr 02, 2019
['2019-04-02', '0.265', '0.275', '0.260', '0.265', '0.265', '630,000']
43
0.265
44
0.275
45
0.260
46
0.265
47
0.265
48
630,000
49
Apr 01, 2019
['2019-04-01', '0.229', '0.280', '0.229', '0.250', '0.250', '1,050,000']
50
0.229
51
0.280
52
0.229
53
0.250
54
0.250
55
1,050,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8485.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.094', '0.094', '0.094', '0.094', '0.094', '-']
1
0.094
2
0.094
3
0.094
4
0.094
5
0.094
6
-
7
Apr 10, 2019
['2019-04-10', '0.095', '0.095', '0.089', '0.094', '0.094', '600,000']
8
0.095
9
0.095
10
0.089
11
0.094
12
0.094
13
600,000
14
Apr 09, 2019
['2019-04-09', '0.093', '0.097', '0.092', '0.097', '0.097', '870,000']
15
0.093
16
0.097
17
0.092
18
0.097
19
0.097
20
870,000
21
Apr 08, 2019
['2019-04-08', '0.097', '0.099', '0.097', '0.099', '0.099', '60,000']
22
0.097
23
0.099
24
0.097
25
0.099
26
0.099
27
60,000
28
Apr 04, 2019
['2019-04-04', '0.094', '0.098', '0.094', '0.097', '0.097', '350,000']
29
0.094
30
0.098
31
0.094
32
0.097
33
0.097
34
350,000
35
Apr 03, 2019
['2019-04-03', '0.101', '0.108', '0.097', '0.097', '0.097', '3,440,000']
36
0.101
37
0.108
38
0.097
39
0.097
40
0.097
41
3,440,000
42
Apr 02, 2019
['2019-04-02', '0.098', '0.101', '0.098', '0.101', '0.101', '400,000']
43
0.098
44
0.101
45
0.098
46
0.101
47
0.101
48
400,000
49
Apr 01, 2019
['2019-04-01', '0.098', '0.102', '0.095', '0.102', '0.102', '640,000']
50
0.098
51
0.102
52
0.095
53
0.102
54
0.102
55
640,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0784.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.255', '0.300', '0.238', '0.280', '0.280', '2,410,000']
1
0.255
2
0.300
3
0.238
4
0.280
5
0.280
6
2,410,000
7
Apr 10, 2019
['2019-04-10', '0.270', '0.290', '0.250', '0.255', '0.255', '1,530,000']
8
0.270
9
0.290
10
0.250
11
0.255
12
0.255
13
1,530,000
14
Apr 09, 2019
['2019-04-09', '0.270', '0.270', '0.270', '0.270', '0.270', '-']
15
0.270
16
0.270
17
0.270
18
0.270
19
0.270
20
-
21
Apr 08, 2019
['2019-04-08', '0.270', '0.270', '0.270', '0.270', '0.270', '60,000']
22
0.270
23
0.270
24
0.270
25
0.270
26
0.270
27
60,000
28
Apr 04, 2019
['2019-04-04', '0.270', '0.270', '0.270', '0.270', '0.270', '80,000']
29
0.270
30
0.270
31
0.270
32
0.270
33
0.270
34
80,000
35
Apr 03, 2019
['2019-04-03', '0.265', '0.290', '0.265', '0.280', '0.280', '1,760,000']
36
0.265
37
0.290
38
0.265
39
0.280
40
0.280
41
1,760,000
42
Apr 02, 2019
['2019-04-02', '0.295', '0.295', '0.295', '0.295', '0.295', '-']
43
0.295
44
0.295
45
0.295
46
0.295
47
0.295
48
-
49
Apr 01, 2019
['2019-04-01', '0.295', '0.295', '0.295', '0.295', '0.295', '-']
50
0.295
51
0.295
52
0.295
53
0.295
54
0.295
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2708.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.830', '1.850', '1.750', '1.770', '1.770', '1,838,000']
1
1.830
2
1.850
3
1.750
4
1.770
5
1.770
6
1,838,000
7
Apr 10, 2019
['2019-04-10', '1.870', '1.880', '1.830', '1.850', '1.850', '1,502,000']
8
1.870
9
1.880
10
1.830
11
1.850
12
1.850
13
1,502,000
14
Apr 09, 2019
['2019-04-09', '1.900', '1.910', '1.830', '1.870', '1.870', '2,042,000']
15
1.900
16
1.910
17
1.830
18
1.870
19
1.870
20
2,042,000
21
Apr 08, 2019
['2019-04-08', '1.880', '1.900', '1.820', '1.900', '1.900', '1,508,000']
22
1.880
23
1.900
24
1.820
25
1.900
26
1.900
27
1,508,000
28
Apr 04, 2019
['2019-04-04', '1.930', '1.940', '1.810', '1.860', '1.860', '2,044,000']
29
1.930
30
1.940
31
1.810
32
1.860
33
1.860
34
2,044,000
35
Apr 03, 2019
['2019-04-03', '1.930', '1.960', '1.930', '1.930', '1.930', '1,924,000']
36
1.930
37
1.960
38
1.930
39
1.930
40
1.930
41
1,924,000
42
Apr 02, 2019
['2019-04-02', '1.970', '1.970', '1.910', '1.910', '1.910', '1,432,000']
43
1.970
44
1.970
45
1.910
46
1.910
47
1.910
48
1,432,000
49
Apr 01, 2019
['2019-04-01', '1.880', '1.960', '1.880', '1.950', '1.950', '2,306,000']
50
1.880
51
1.960
52
1.880
53
1.950
54
1.950
55
2,306,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3878.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.930', '1.930', '1.930', '1.930', '1.930', '-']
1
1.930
2
1.930
3
1.930
4
1.930
5
1.930
6
-
7
Apr 10, 2019
['2019-04-10', '1.930', '1.930', '1.930', '1.930', '1.930', '-']
8
1.930
9
1.930
10
1.930
11
1.930
12
1.930
13
-
14
Apr 09, 2019
['2019-04-09', '1.930', '1.950', '1.900', '1.940', '1.940', '20,000']
15
1.930
16
1.950
17
1.900
18
1.940
19
1.940
20
20,000
21
Apr 08, 2019
['2019-04-08', '1.900', '1.950', '1.900', '1.950', '1.950', '12,000']
22
1.900
23
1.950
24
1.900
25
1.950
26
1.950
27
12,000
28
Apr 04, 2019
['2019-04-04', '1.950', '1.950', '1.950', '1.950', '1.950', '-']
29
1.950
30
1.950
31
1.950
32
1.950
33
1.950
34
-
35
Apr 03, 2019
['2019-04-03', '1.950', '1.950', '1.950', '1.950', '1.950', '-']
36
1.950
37
1.950
38
1.950
39
1.950
40
1.950
41
-
42
Apr 02, 2019
['2019-04-02', '1.900', '1.900', '1.890', '1.890', '1.890', '30,000']
43
1.900
44
1.900
45
1.890
46
1.890
47
1.890
48
30,000
49
Apr 01, 2019
['2019-04-01', '1.890', '1.890', '1.890', '1.890', '1.890', '-']
50
1.890
51
1.890
52
1.890
53
1.890
54
1.890
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8419.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.320', '0.320', '0.315', '0.320', '0.320', '95,000']
1
0.320
2
0.320
3
0.315
4
0.320
5
0.320
6
95,000
7
Apr 10, 2019
['2019-04-10', '0.325', '0.325', '0.325', '0.325', '0.325', '115,000']
8
0.325
9
0.325
10
0.325
11
0.325
12
0.325
13
115,000
14
Apr 09, 2019
['2019-04-09', '0.320', '0.330', '0.315', '0.325', '0.325', '810,000']
15
0.320
16
0.330
17
0.315
18
0.325
19
0.325
20
810,000
21
Apr 08, 2019
['2019-04-08', '0.330', '0.330', '0.315', '0.325', '0.325', '1,320,000']
22
0.330
23
0.330
24
0.315
25
0.325
26
0.325
27
1,320,000
28
Apr 04, 2019
['2019-04-04', '0.325', '0.340', '0.325', '0.340', '0.340', '200,000']
29
0.325
30
0.340
31
0.325
32
0.340
33
0.340
34
200,000
35
Apr 03, 2019
['2019-04-03', '0.335', '0.340', '0.325', '0.330', '0.330', '775,000']
36
0.335
37
0.340
38
0.325
39
0.330
40
0.330
41
775,000
42
Apr 02, 2019
['2019-04-02', '0.350', '0.350', '0.335', '0.340', '0.340', '375,000']
43
0.350
44
0.350
45
0.335
46
0.340
47
0.340
48
375,000
49
Apr 01, 2019
['2019-04-01', '0.330', '0.355', '0.330', '0.350', '0.350', '1,385,000']
50
0.330
51
0.355
52
0.330
53
0.350
54
0.350
55
1,385,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1789.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.230', '4.230', '4.130', '4.170', '4.170', '3,602,028']
1
4.230
2
4.230
3
4.130
4
4.170
5
4.170
6
3,602,028
7
Apr 10, 2019
['2019-04-10', '4.250', '4.270', '4.190', '4.230', '4.230', '1,584,000']
8
4.250
9
4.270
10
4.190
11
4.230
12
4.230
13
1,584,000
14
Apr 09, 2019
['2019-04-09', '4.230', '4.280', '4.220', '4.270', '4.270', '1,652,169']
15
4.230
16
4.280
17
4.220
18
4.270
19
4.270
20
1,652,169
21
Apr 08, 2019
['2019-04-08', '4.250', '4.280', '4.190', '4.230', '4.230', '1,388,000']
22
4.250
23
4.280
24
4.190
25
4.230
26
4.230
27
1,388,000
28
Apr 04, 2019
['2019-04-04', '4.280', '4.280', '4.150', '4.190', '4.190', '2,281,055']
29
4.280
30
4.280
31
4.150
32
4.190
33
4.190
34
2,281,055
35
Apr 03, 2019
['2019-04-03', '4.210', '4.290', '4.170', '4.270', '4.270', '2,666,062']
36
4.210
37
4.290
38
4.170
39
4.270
40
4.270
41
2,666,062
42
Apr 02, 2019
['2019-04-02', '4.300', '4.300', '4.180', '4.210', '4.210', '2,552,106']
43
4.300
44
4.300
45
4.180
46
4.210
47
4.210
48
2,552,106
49
Apr 01, 2019
['2019-04-01', '4.340', '4.390', '4.290', '4.300', '4.300', '1,318,000']
50
4.340
51
4.390
52
4.290
53
4.300
54
4.300
55
1,318,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2022.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.285', '0.370', '0.285', '0.360', '0.360', '45,488,000']
1
0.285
2
0.370
3
0.285
4
0.360
5
0.360
6
45,488,000
7
Apr 10, 2019
['2019-04-10', '0.275', '0.295', '0.275', '0.285', '0.285', '1,888,000']
8
0.275
9
0.295
10
0.275
11
0.285
12
0.285
13
1,888,000
14
Apr 09, 2019
['2019-04-09', '0.290', '0.295', '0.280', '0.285', '0.285', '1,324,000']
15
0.290
16
0.295
17
0.280
18
0.285
19
0.285
20
1,324,000
21
Apr 08, 2019
['2019-04-08', '0.285', '0.290', '0.280', '0.285', '0.285', '264,000']
22
0.285
23
0.290
24
0.280
25
0.285
26
0.285
27
264,000
28
Apr 04, 2019
['2019-04-04', '0.275', '0.295', '0.275', '0.285', '0.285', '2,892,000']
29
0.275
30
0.295
31
0.275
32
0.285
33
0.285
34
2,892,000
35
Apr 03, 2019
['2019-04-03', '0.285', '0.295', '0.270', '0.280', '0.280', '4,932,000']
36
0.285
37
0.295
38
0.270
39
0.280
40
0.280
41
4,932,000
42
Apr 02, 2019
['2019-04-02', '0.280', '0.285', '0.280', '0.280', '0.280', '916,000']
43
0.280
44
0.285
45
0.280
46
0.280
47
0.280
48
916,000
49
Apr 01, 2019
['2019-04-01', '0.290', '0.300', '0.280', '0.285', '0.285', '4,632,000']
50
0.290
51
0.300
52
0.280
53
0.285
54
0.285
55
4,632,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6877.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.495', '0.495', '0.470', '0.475', '0.475', '80,000']
1
0.495
2
0.495
3
0.470
4
0.475
5
0.475
6
80,000
7
Apr 10, 2019
['2019-04-10', '0.425', '0.520', '0.425', '0.495', '0.495', '2,935,000']
8
0.425
9
0.520
10
0.425
11
0.495
12
0.495
13
2,935,000
14
Apr 09, 2019
['2019-04-09', '0.435', '0.435', '0.410', '0.425', '0.425', '490,000']
15
0.435
16
0.435
17
0.410
18
0.425
19
0.425
20
490,000
21
Apr 08, 2019
['2019-04-08', '0.455', '0.455', '0.410', '0.435', '0.435', '25,000']
22
0.455
23
0.455
24
0.410
25
0.435
26
0.435
27
25,000
28
Apr 04, 2019
['2019-04-04', '0.455', '0.455', '0.400', '0.450', '0.450', '400,000']
29
0.455
30
0.455
31
0.400
32
0.450
33
0.450
34
400,000
35
Apr 03, 2019
['2019-04-03', '0.465', '0.465', '0.430', '0.455', '0.455', '170,000']
36
0.465
37
0.465
38
0.430
39
0.455
40
0.455
41
170,000
42
Apr 02, 2019
['2019-04-02', '0.425', '0.470', '0.425', '0.460', '0.460', '125,000']
43
0.425
44
0.470
45
0.425
46
0.460
47
0.460
48
125,000
49
Apr 01, 2019
['2019-04-01', '0.450', '0.475', '0.450', '0.450', '0.450', '300,000']
50
0.450
51
0.475
52
0.450
53
0.450
54
0.450
55
300,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8377.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.185', '0.185', '0.170', '0.174', '0.174', '120,000']
1
0.185
2
0.185
3
0.170
4
0.174
5
0.174
6
120,000
7
Apr 10, 2019
['2019-04-10', '0.185', '0.185', '0.185', '0.185', '0.185', '-']
8
0.185
9
0.185
10
0.185
11
0.185
12
0.185
13
-
14
Apr 09, 2019
['2019-04-09', '0.174', '0.174', '0.174', '0.174', '0.174', '-']
15
0.174
16
0.174
17
0.174
18
0.174
19
0.174
20
-
21
Apr 08, 2019
['2019-04-08', '0.165', '0.183', '0.164', '0.179', '0.179', '340,000']
22
0.165
23
0.183
24
0.164
25
0.179
26
0.179
27
340,000
28
Apr 04, 2019
['2019-04-04', '0.165', '0.170', '0.165', '0.170', '0.170', '30,000']
29
0.165
30
0.170
31
0.165
32
0.170
33
0.170
34
30,000
35
Apr 03, 2019
['2019-04-03', '0.175', '0.175', '0.170', '0.170', '0.170', '80,000']
36
0.175
37
0.175
38
0.170
39
0.170
40
0.170
41
80,000
42
Apr 02, 2019
['2019-04-02', '0.180', '0.180', '0.180', '0.180', '0.180', '-']
43
0.180
44
0.180
45
0.180
46
0.180
47
0.180
48
-
49
Apr 01, 2019
['2019-04-01', '0.200', '0.200', '0.180', '0.180', '0.180', '250,000']
50
0.200
51
0.200
52
0.180
53
0.180
54
0.180
55
250,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0839.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '12.980', '13.120', '12.620', '12.620', '12.620', '6,546,800']
1
12.980
2
13.120
3
12.620
4
12.620
5
12.620
6
6,546,800
7
Apr 10, 2019
['2019-04-10', '12.460', '12.940', '12.240', '12.860', '12.860', '11,644,500']
8
12.460
9
12.940
10
12.240
11
12.860
12
12.860
13
11,644,500
14
Apr 09, 2019
['2019-04-09', '12.340', '12.600', '11.880', '12.520', '12.520', '10,126,000']
15
12.340
16
12.600
17
11.880
18
12.520
19
12.520
20
10,126,000
21
Apr 08, 2019
['2019-04-08', '11.980', '12.420', '11.980', '12.200', '12.200', '12,275,515']
22
11.980
23
12.420
24
11.980
25
12.200
26
12.200
27
12,275,515
28
Apr 04, 2019
['2019-04-04', '12.000', '12.180', '11.720', '11.920', '11.920', '5,017,000']
29
12.000
30
12.180
31
11.720
32
11.920
33
11.920
34
5,017,000
35
Apr 03, 2019
['2019-04-03', '11.740', '12.000', '11.720', '11.960', '11.960', '2,830,774']
36
11.740
37
12.000
38
11.720
39
11.960
40
11.960
41
2,830,774
42
Apr 02, 2019
['2019-04-02', '11.860', '12.160', '11.640', '11.720', '11.720', '10,411,673']
43
11.860
44
12.160
45
11.640
46
11.720
47
11.720
48
10,411,673
49
Apr 01, 2019
['2019-04-01', '11.920', '12.180', '11.660', '11.840', '11.840', '5,493,000']
50
11.920
51
12.180
52
11.660
53
11.840
54
11.840
55
5,493,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1722.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.400', '0.420', '0.400', '0.420', '0.420', '4,940,000']
1
0.400
2
0.420
3
0.400
4
0.420
5
0.420
6
4,940,000
7
Apr 10, 2019
['2019-04-10', '0.400', '0.400', '0.400', '0.400', '0.400', '10,000']
8
0.400
9
0.400
10
0.400
11
0.400
12
0.400
13
10,000
14
Apr 09, 2019
['2019-04-09', '0.405', '0.410', '0.395', '0.410', '0.410', '160,000']
15
0.405
16
0.410
17
0.395
18
0.410
19
0.410
20
160,000
21
Apr 08, 2019
['2019-04-08', '0.400', '0.440', '0.400', '0.410', '0.410', '310,000']
22
0.400
23
0.440
24
0.400
25
0.410
26
0.410
27
310,000
28
Apr 04, 2019
['2019-04-04', '0.405', '0.415', '0.405', '0.410', '0.410', '320,000']
29
0.405
30
0.415
31
0.405
32
0.410
33
0.410
34
320,000
35
Apr 03, 2019
['2019-04-03', '0.400', '0.400', '0.400', '0.400', '0.400', '90,000']
36
0.400
37
0.400
38
0.400
39
0.400
40
0.400
41
90,000
42
Apr 02, 2019
['2019-04-02', '0.390', '0.390', '0.390', '0.390', '0.390', '290,000']
43
0.390
44
0.390
45
0.390
46
0.390
47
0.390
48
290,000
49
Apr 01, 2019
['2019-04-01', '0.390', '0.390', '0.390', '0.390', '0.390', '80,000']
50
0.390
51
0.390
52
0.390
53
0.390
54
0.390
55
80,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1727.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '6.650', '6.710', '6.270', '6.310', '6.310', '6,691,000']
1
6.650
2
6.710
3
6.270
4
6.310
5
6.310
6
6,691,000
7
Apr 10, 2019
['2019-04-10', '6.800', '6.840', '6.520', '6.780', '6.780', '10,064,500']
8
6.800
9
6.840
10
6.520
11
6.780
12
6.780
13
10,064,500
14
Apr 09, 2019
['2019-04-09', '7.280', '7.310', '6.830', '6.900', '6.900', '8,234,500']
15
7.280
16
7.310
17
6.830
18
6.900
19
6.900
20
8,234,500
21
Apr 08, 2019
['2019-04-08', '7.500', '7.520', '7.200', '7.300', '7.300', '8,157,500']
22
7.500
23
7.520
24
7.200
25
7.300
26
7.300
27
8,157,500
28
Apr 04, 2019
['2019-04-04', '7.550', '7.550', '7.380', '7.460', '7.460', '43,949,000']
29
7.550
30
7.550
31
7.380
32
7.460
33
7.460
34
43,949,000
35
Apr 03, 2019
['2019-04-03', '7.410', '7.620', '7.390', '7.590', '7.590', '13,568,000']
36
7.410
37
7.620
38
7.390
39
7.590
40
7.590
41
13,568,000
42
Apr 02, 2019
['2019-04-02', '7.400', '7.470', '7.360', '7.410', '7.410', '13,194,000']
43
7.400
44
7.470
45
7.360
46
7.410
47
7.410
48
13,194,000
49
Apr 01, 2019
['2019-04-01', '7.180', '7.400', '7.110', '7.350', '7.350', '12,733,000']
50
7.180
51
7.400
52
7.110
53
7.350
54
7.350
55
12,733,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8385.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.193', '0.196', '0.193', '0.196', '0.196', '430,000']
1
0.193
2
0.196
3
0.193
4
0.196
5
0.196
6
430,000
7
Apr 10, 2019
['2019-04-10', '0.192', '0.195', '0.188', '0.188', '0.188', '510,000']
8
0.192
9
0.195
10
0.188
11
0.188
12
0.188
13
510,000
14
Apr 09, 2019
['2019-04-09', '0.202', '0.202', '0.188', '0.190', '0.190', '430,000']
15
0.202
16
0.202
17
0.188
18
0.190
19
0.190
20
430,000
21
Apr 08, 2019
['2019-04-08', '0.196', '0.196', '0.196', '0.196', '0.196', '-']
22
0.196
23
0.196
24
0.196
25
0.196
26
0.196
27
-
28
Apr 04, 2019
['2019-04-04', '0.199', '0.199', '0.191', '0.196', '0.196', '1,450,000']
29
0.199
30
0.199
31
0.191
32
0.196
33
0.196
34
1,450,000
35
Apr 03, 2019
['2019-04-03', '0.192', '0.202', '0.192', '0.199', '0.199', '970,000']
36
0.192
37
0.202
38
0.192
39
0.199
40
0.199
41
970,000
42
Apr 02, 2019
['2019-04-02', '0.208', '0.208', '0.201', '0.201', '0.201', '90,000']
43
0.208
44
0.208
45
0.201
46
0.201
47
0.201
48
90,000
49
Apr 01, 2019
['2019-04-01', '0.206', '0.210', '0.197', '0.197', '0.197', '690,000']
50
0.206
51
0.210
52
0.197
53
0.197
54
0.197
55
690,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6090.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.530', '2.530', '2.530', '2.530', '2.530', '-']
1
2.530
2
2.530
3
2.530
4
2.530
5
2.530
6
-
7
Apr 10, 2019
['2019-04-10', '2.530', '2.530', '2.530', '2.530', '2.530', '-']
8
2.530
9
2.530
10
2.530
11
2.530
12
2.530
13
-
14
Apr 09, 2019
['2019-04-09', '2.530', '2.530', '2.530', '2.530', '2.530', '-']
15
2.530
16
2.530
17
2.530
18
2.530
19
2.530
20
-
21
Apr 08, 2019
['2019-04-08', '2.430', '2.530', '2.430', '2.530', '2.530', '5,000']
22
2.430
23
2.530
24
2.430
25
2.530
26
2.530
27
5,000
28
Apr 04, 2019
['2019-04-04', '2.360', '2.530', '2.360', '2.530', '2.530', '11,000']
29
2.360
30
2.530
31
2.360
32
2.530
33
2.530
34
11,000
35
Apr 03, 2019
['2019-04-03', '2.410', '2.410', '2.410', '2.410', '2.410', '-']
36
2.410
37
2.410
38
2.410
39
2.410
40
2.410
41
-
42
Apr 02, 2019
['2019-04-02', '2.410', '2.410', '2.410', '2.410', '2.410', '-']
43
2.410
44
2.410
45
2.410
46
2.410
47
2.410
48
-
49
Apr 01, 2019
['2019-04-01', '2.360', '2.410', '2.360', '2.410', '2.410', '65,000']
50
2.360
51
2.410
52
2.360
53
2.410
54
2.410
55
65,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2227.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.620', '0.690', '0.620', '0.640', '0.640', '224,000']
1
0.620
2
0.690
3
0.620
4
0.640
5
0.640
6
224,000
7
Apr 10, 2019
['2019-04-10', '0.620', '0.640', '0.610', '0.640', '0.640', '13,360,000']
8
0.620
9
0.640
10
0.610
11
0.640
12
0.640
13
13,360,000
14
Apr 09, 2019
['2019-04-09', '0.620', '0.640', '0.600', '0.620', '0.620', '360,000']
15
0.620
16
0.640
17
0.600
18
0.620
19
0.620
20
360,000
21
Apr 08, 2019
['2019-04-08', '0.610', '0.610', '0.600', '0.600', '0.600', '752,000']
22
0.610
23
0.610
24
0.600
25
0.600
26
0.600
27
752,000
28
Apr 04, 2019
['2019-04-04', '0.600', '0.610', '0.590', '0.610', '0.610', '820,000']
29
0.600
30
0.610
31
0.590
32
0.610
33
0.610
34
820,000
35
Apr 03, 2019
['2019-04-03', '0.620', '0.620', '0.620', '0.620', '0.620', '-']
36
0.620
37
0.620
38
0.620
39
0.620
40
0.620
41
-
42
Apr 02, 2019
['2019-04-02', '0.630', '0.640', '0.630', '0.620', '0.620', '16,000']
43
0.630
44
0.640
45
0.630
46
0.620
47
0.620
48
16,000
49
Apr 01, 2019
['2019-04-01', '0.630', '0.640', '0.580', '0.600', '0.600', '320,000']
50
0.630
51
0.640
52
0.580
53
0.600
54
0.600
55
320,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1475.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.560', '4.600', '4.380', '4.450', '4.450', '1,303,000']
1
4.560
2
4.600
3
4.380
4
4.450
5
4.450
6
1,303,000
7
Apr 10, 2019
['2019-04-10', '4.550', '4.570', '4.510', '4.550', '4.550', '939,000']
8
4.550
9
4.570
10
4.510
11
4.550
12
4.550
13
939,000
14
Apr 09, 2019
['2019-04-09', '4.570', '4.600', '4.490', '4.510', '4.510', '1,188,000']
15
4.570
16
4.600
17
4.490
18
4.510
19
4.510
20
1,188,000
21
Apr 08, 2019
['2019-04-08', '4.670', '4.680', '4.440', '4.550', '4.550', '2,524,000']
22
4.670
23
4.680
24
4.440
25
4.550
26
4.550
27
2,524,000
28
Apr 04, 2019
['2019-04-04', '4.750', '4.760', '4.600', '4.650', '4.650', '2,016,000']
29
4.750
30
4.760
31
4.600
32
4.650
33
4.650
34
2,016,000
35
Apr 03, 2019
['2019-04-03', '4.630', '4.740', '4.620', '4.710', '4.710', '3,409,200']
36
4.630
37
4.740
38
4.620
39
4.710
40
4.710
41
3,409,200
42
Apr 02, 2019
['2019-04-02', '4.530', '4.710', '4.520', '4.630', '4.630', '3,398,000']
43
4.530
44
4.710
45
4.520
46
4.630
47
4.630
48
3,398,000
49
Apr 01, 2019
['2019-04-01', '4.500', '4.540', '4.450', '4.510', '4.510', '1,641,000']
50
4.500
51
4.540
52
4.450
53
4.510
54
4.510
55
1,641,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1417.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.120', '3.120', '3.070', '3.070', '3.070', '166,000']
1
3.120
2
3.120
3
3.070
4
3.070
5
3.070
6
166,000
7
Apr 10, 2019
['2019-04-10', '3.150', '3.150', '3.060', '3.120', '3.120', '170,000']
8
3.150
9
3.150
10
3.060
11
3.120
12
3.120
13
170,000
14
Apr 09, 2019
['2019-04-09', '3.110', '3.120', '3.100', '3.110', '3.110', '222,000']
15
3.110
16
3.120
17
3.100
18
3.110
19
3.110
20
222,000
21
Apr 08, 2019
['2019-04-08', '3.100', '3.120', '3.100', '3.110', '3.110', '162,000']
22
3.100
23
3.120
24
3.100
25
3.110
26
3.110
27
162,000
28
Apr 04, 2019
['2019-04-04', '3.200', '3.220', '3.100', '3.100', '3.100', '222,000']
29
3.200
30
3.220
31
3.100
32
3.100
33
3.100
34
222,000
35
Apr 03, 2019
['2019-04-03', '3.150', '3.390', '3.150', '3.200', '3.200', '220,000']
36
3.150
37
3.390
38
3.150
39
3.200
40
3.200
41
220,000
42
Apr 02, 2019
['2019-04-02', '3.130', '3.150', '3.120', '3.150', '3.150', '198,000']
43
3.130
44
3.150
45
3.120
46
3.150
47
3.150
48
198,000
49
Apr 01, 2019
['2019-04-01', '3.060', '3.130', '3.050', '3.130', '3.130', '196,000']
50
3.060
51
3.130
52
3.050
53
3.130
54
3.130
55
196,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8429.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.660', '0.660', '0.640', '0.660', '0.660', '1,065,000']
1
0.660
2
0.660
3
0.640
4
0.660
5
0.660
6
1,065,000
7
Apr 10, 2019
['2019-04-10', '0.680', '0.690', '0.650', '0.660', '0.660', '1,235,000']
8
0.680
9
0.690
10
0.650
11
0.660
12
0.660
13
1,235,000
14
Apr 09, 2019
['2019-04-09', '0.680', '0.690', '0.670', '0.680', '0.680', '500,000']
15
0.680
16
0.690
17
0.670
18
0.680
19
0.680
20
500,000
21
Apr 08, 2019
['2019-04-08', '0.690', '0.690', '0.670', '0.680', '0.680', '565,000']
22
0.690
23
0.690
24
0.670
25
0.680
26
0.680
27
565,000
28
Apr 04, 2019
['2019-04-04', '0.680', '0.720', '0.680', '0.680', '0.680', '1,505,000']
29
0.680
30
0.720
31
0.680
32
0.680
33
0.680
34
1,505,000
35
Apr 03, 2019
['2019-04-03', '0.670', '0.690', '0.670', '0.680', '0.680', '490,000']
36
0.670
37
0.690
38
0.670
39
0.680
40
0.680
41
490,000
42
Apr 02, 2019
['2019-04-02', '0.670', '0.670', '0.660', '0.670', '0.670', '735,000']
43
0.670
44
0.670
45
0.660
46
0.670
47
0.670
48
735,000
49
Apr 01, 2019
['2019-04-01', '0.680', '0.720', '0.650', '0.670', '0.670', '2,290,000']
50
0.680
51
0.720
52
0.650
53
0.670
54
0.670
55
2,290,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1697.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.300', '1.300', '1.270', '1.300', '1.300', '1,426,600']
1
1.300
2
1.300
3
1.270
4
1.300
5
1.300
6
1,426,600
7
Apr 10, 2019
['2019-04-10', '1.330', '1.330', '1.310', '1.310', '1.310', '259,200']
8
1.330
9
1.330
10
1.310
11
1.310
12
1.310
13
259,200
14
Apr 09, 2019
['2019-04-09', '1.320', '1.400', '1.310', '1.330', '1.330', '1,092,600']
15
1.320
16
1.400
17
1.310
18
1.330
19
1.330
20
1,092,600
21
Apr 08, 2019
['2019-04-08', '1.300', '1.320', '1.260', '1.280', '1.280', '370,800']
22
1.300
23
1.320
24
1.260
25
1.280
26
1.280
27
370,800
28
Apr 04, 2019
['2019-04-04', '1.280', '1.300', '1.270', '1.280', '1.280', '408,600']
29
1.280
30
1.300
31
1.270
32
1.280
33
1.280
34
408,600
35
Apr 03, 2019
['2019-04-03', '1.240', '1.290', '1.240', '1.270', '1.270', '257,400']
36
1.240
37
1.290
38
1.240
39
1.270
40
1.270
41
257,400
42
Apr 02, 2019
['2019-04-02', '1.270', '1.300', '1.240', '1.240', '1.240', '145,800']
43
1.270
44
1.300
45
1.240
46
1.240
47
1.240
48
145,800
49
Apr 01, 2019
['2019-04-01', '1.220', '1.270', '1.220', '1.270', '1.270', '261,000']
50
1.220
51
1.270
52
1.220
53
1.270
54
1.270
55
261,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
No record
0
8495.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.240', '0.240', '0.240', '0.240', '0.240', '-']
1
0.240
2
0.240
3
0.240
4
0.240
5
0.240
6
-
7
Apr 10, 2019
['2019-04-10', '0.240', '0.240', '0.240', '0.240', '0.240', '4,000']
8
0.240
9
0.240
10
0.240
11
0.240
12
0.240
13
4,000
14
Apr 09, 2019
['2019-04-09', '0.242', '0.250', '0.240', '0.240', '0.240', '184,000']
15
0.242
16
0.250
17
0.240
18
0.240
19
0.240
20
184,000
21
Apr 08, 2019
['2019-04-08', '0.242', '0.242', '0.242', '0.242', '0.242', '-']
22
0.242
23
0.242
24
0.242
25
0.242
26
0.242
27
-
28
Apr 04, 2019
['2019-04-04', '0.242', '0.242', '0.242', '0.242', '0.242', '4,000']
29
0.242
30
0.242
31
0.242
32
0.242
33
0.242
34
4,000
35
Apr 03, 2019
['2019-04-03', '0.248', '0.250', '0.240', '0.242', '0.242', '356,000']
36
0.248
37
0.250
38
0.240
39
0.242
40
0.242
41
356,000
42
Apr 02, 2019
['2019-04-02', '0.230', '0.240', '0.230', '0.240', '0.240', '260,000']
43
0.230
44
0.240
45
0.230
46
0.240
47
0.240
48
260,000
49
Apr 01, 2019
['2019-04-01', '0.230', '0.230', '0.230', '0.230', '0.230', '-']
50
0.230
51
0.230
52
0.230
53
0.230
54
0.230
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1997.HKneeds update
[50]
[50]
59
50
length in loop59
50poped
[]
[]
0
Apr 11, 2019
['2019-04-11', '58.800', '58.900', '57.200', '57.850', '57.850', '2,310,914']
1
58.800
2
58.900
3
57.200
4
57.850
5
57.850
6
2,310,914
7
Apr 10, 2019
['2019-04-10', '59.200', '59.200', '58.550', '58.850', '58.850', '1,916,585']
8
59.200
9
59.200
10
58.550
11
58.850
12
58.850
13
1,916,585
14
Apr 09, 2019
['2019-04-09', '58.550', '59.000', '58.150', '59.000', '59.000', '2,725,029']
15
58.550
16
59.000
17
58.150
18
59.000
19
59.000
20
2,725,029
21
Apr 08, 2019
['2019-04-08', '58.950', '59.250', '58.000', '58.850', '58.850', '4,157,286']
22
58.950
23
59.250
24
58.000
25
58.850
26
58.850
27
4,157,286
28
Apr 04, 2019
['2019-04-04', '59.400', '59.550', '58.250', '59.100', '59.100', '3,755,629']
29
59.400
30
59.550
31
58.250
32
59.100
33
59.100
34
3,755,629
35
Apr 03, 2019
['2019-04-03', '58.250', '59.400', '57.400', '59.400', '59.400', '2,768,864']
36
58.250
37
59.400
38
57.400
39
59.400
40
59.400
41
2,768,864
42
Apr 02, 2019
['2019-04-02', '58.050', '59.150', '58.050', '58.550', '58.550', '1,858,815']
43
58.050
44
59.150
45
58.050
46
58.550
47
58.550
48
1,858,815
49
Apr 01, 2019
['2019-04-01', '59.100', '59.600', '58.600', '59.600', '58.550', '2,554,755']
50
59.100
51
59.600
52
58.600
53
59.600
54
58.550
55
2,554,755
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1710.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.550', '0.560', '0.550', '0.560', '0.560', '542,941']
1
0.550
2
0.560
3
0.550
4
0.560
5
0.560
6
542,941
7
Apr 10, 2019
['2019-04-10', '0.540', '0.590', '0.530', '0.540', '0.540', '1,249,288']
8
0.540
9
0.590
10
0.530
11
0.540
12
0.540
13
1,249,288
14
Apr 09, 2019
['2019-04-09', '0.510', '0.540', '0.510', '0.530', '0.530', '456,455']
15
0.510
16
0.540
17
0.510
18
0.530
19
0.530
20
456,455
21
Apr 08, 2019
['2019-04-08', '0.510', '0.510', '0.490', '0.510', '0.510', '894,330']
22
0.510
23
0.510
24
0.490
25
0.510
26
0.510
27
894,330
28
Apr 04, 2019
['2019-04-04', '0.510', '0.530', '0.510', '0.520', '0.520', '304,000']
29
0.510
30
0.530
31
0.510
32
0.520
33
0.520
34
304,000
35
Apr 03, 2019
['2019-04-03', '0.530', '0.550', '0.530', '0.530', '0.530', '1,337,349']
36
0.530
37
0.550
38
0.530
39
0.530
40
0.530
41
1,337,349
42
Apr 02, 2019
['2019-04-02', '0.475', '0.550', '0.475', '0.510', '0.510', '3,864,497']
43
0.475
44
0.550
45
0.475
46
0.510
47
0.510
48
3,864,497
49
Apr 01, 2019
['2019-04-01', '0.465', '0.475', '0.445', '0.460', '0.460', '736,000']
50
0.465
51
0.475
52
0.445
53
0.460
54
0.460
55
736,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8402.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.410', '0.440', '0.410', '0.430', '0.430', '1,650,000']
1
0.410
2
0.440
3
0.410
4
0.430
5
0.430
6
1,650,000
7
Apr 10, 2019
['2019-04-10', '0.415', '0.430', '0.380', '0.425', '0.425', '3,130,000']
8
0.415
9
0.430
10
0.380
11
0.425
12
0.425
13
3,130,000
14
Apr 09, 2019
['2019-04-09', '0.425', '0.435', '0.415', '0.420', '0.420', '1,800,000']
15
0.425
16
0.435
17
0.415
18
0.420
19
0.420
20
1,800,000
21
Apr 08, 2019
['2019-04-08', '0.440', '0.440', '0.425', '0.435', '0.435', '785,000']
22
0.440
23
0.440
24
0.425
25
0.435
26
0.435
27
785,000
28
Apr 04, 2019
['2019-04-04', '0.425', '0.440', '0.420', '0.440', '0.440', '1,080,000']
29
0.425
30
0.440
31
0.420
32
0.440
33
0.440
34
1,080,000
35
Apr 03, 2019
['2019-04-03', '0.425', '0.430', '0.415', '0.425', '0.425', '1,740,000']
36
0.425
37
0.430
38
0.415
39
0.425
40
0.425
41
1,740,000
42
Apr 02, 2019
['2019-04-02', '0.415', '0.425', '0.410', '0.425', '0.425', '1,945,000']
43
0.415
44
0.425
45
0.410
46
0.425
47
0.425
48
1,945,000
49
Apr 01, 2019
['2019-04-01', '0.420', '0.430', '0.405', '0.420', '0.420', '1,595,000']
50
0.420
51
0.430
52
0.405
53
0.420
54
0.420
55
1,595,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8118.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.227', '0.234', '0.226', '0.231', '0.231', '680,000']
1
0.227
2
0.234
3
0.226
4
0.231
5
0.231
6
680,000
7
Apr 10, 2019
['2019-04-10', '0.232', '0.238', '0.232', '0.234', '0.234', '472,000']
8
0.232
9
0.238
10
0.232
11
0.234
12
0.234
13
472,000
14
Apr 09, 2019
['2019-04-09', '0.231', '0.242', '0.231', '0.241', '0.241', '424,000']
15
0.231
16
0.242
17
0.231
18
0.241
19
0.241
20
424,000
21
Apr 08, 2019
['2019-04-08', '0.230', '0.249', '0.230', '0.249', '0.249', '56,000']
22
0.230
23
0.249
24
0.230
25
0.249
26
0.249
27
56,000
28
Apr 04, 2019
['2019-04-04', '0.240', '0.255', '0.236', '0.248', '0.248', '520,000']
29
0.240
30
0.255
31
0.236
32
0.248
33
0.248
34
520,000
35
Apr 03, 2019
['2019-04-03', '0.240', '0.260', '0.240', '0.249', '0.249', '2,448,000']
36
0.240
37
0.260
38
0.240
39
0.249
40
0.249
41
2,448,000
42
Apr 02, 2019
['2019-04-02', '0.245', '0.245', '0.221', '0.239', '0.239', '848,000']
43
0.245
44
0.245
45
0.221
46
0.239
47
0.239
48
848,000
49
Apr 01, 2019
['2019-04-01', '0.228', '0.255', '0.225', '0.229', '0.229', '2,536,000']
50
0.228
51
0.255
52
0.225
53
0.229
54
0.229
55
2,536,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8373.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.395', '0.395', '0.385', '0.390', '0.390', '330,000']
1
0.395
2
0.395
3
0.385
4
0.390
5
0.390
6
330,000
7
Apr 10, 2019
['2019-04-10', '0.400', '0.400', '0.400', '0.400', '0.400', '-']
8
0.400
9
0.400
10
0.400
11
0.400
12
0.400
13
-
14
Apr 09, 2019
['2019-04-09', '0.395', '0.405', '0.395', '0.405', '0.405', '30,000']
15
0.395
16
0.405
17
0.395
18
0.405
19
0.405
20
30,000
21
Apr 08, 2019
['2019-04-08', '0.400', '0.405', '0.395', '0.395', '0.395', '45,000']
22
0.400
23
0.405
24
0.395
25
0.395
26
0.395
27
45,000
28
Apr 04, 2019
['2019-04-04', '0.410', '0.410', '0.410', '0.410', '0.410', '135,000']
29
0.410
30
0.410
31
0.410
32
0.410
33
0.410
34
135,000
35
Apr 03, 2019
['2019-04-03', '0.380', '0.410', '0.375', '0.410', '0.410', '925,000']
36
0.380
37
0.410
38
0.375
39
0.410
40
0.410
41
925,000
42
Apr 02, 2019
['2019-04-02', '0.390', '0.390', '0.350', '0.375', '0.375', '735,000']
43
0.390
44
0.390
45
0.350
46
0.375
47
0.375
48
735,000
49
Apr 01, 2019
['2019-04-01', '0.365', '0.390', '0.355', '0.390', '0.390', '430,000']
50
0.365
51
0.390
52
0.355
53
0.390
54
0.390
55
430,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3358.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.630', '3.760', '3.510', '3.600', '3.600', '1,859,500']
1
3.630
2
3.760
3
3.510
4
3.600
5
3.600
6
1,859,500
7
Apr 10, 2019
['2019-04-10', '3.600', '4.020', '3.600', '3.650', '3.650', '6,130,500']
8
3.600
9
4.020
10
3.600
11
3.650
12
3.650
13
6,130,500
14
Apr 09, 2019
['2019-04-09', '3.400', '3.560', '3.380', '3.530', '3.530', '2,018,000']
15
3.400
16
3.560
17
3.380
18
3.530
19
3.530
20
2,018,000
21
Apr 08, 2019
['2019-04-08', '3.400', '3.430', '3.350', '3.400', '3.400', '1,129,500']
22
3.400
23
3.430
24
3.350
25
3.400
26
3.400
27
1,129,500
28
Apr 04, 2019
['2019-04-04', '3.370', '3.400', '3.370', '3.400', '3.400', '365,500']
29
3.370
30
3.400
31
3.370
32
3.400
33
3.400
34
365,500
35
Apr 03, 2019
['2019-04-03', '3.400', '3.400', '3.370', '3.380', '3.380', '806,500']
36
3.400
37
3.400
38
3.370
39
3.380
40
3.380
41
806,500
42
Apr 02, 2019
['2019-04-02', '3.400', '3.420', '3.390', '3.400', '3.400', '810,500']
43
3.400
44
3.420
45
3.390
46
3.400
47
3.400
48
810,500
49
Apr 01, 2019
['2019-04-01', '3.400', '3.460', '3.390', '3.430', '3.430', '1,127,500']
50
3.400
51
3.460
52
3.390
53
3.430
54
3.430
55
1,127,500
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1975.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.590', '0.590', '0.570', '0.590', '0.590', '72,000']
1
0.590
2
0.590
3
0.570
4
0.590
5
0.590
6
72,000
7
Apr 10, 2019
['2019-04-10', '0.570', '0.600', '0.570', '0.600', '0.600', '12,000']
8
0.570
9
0.600
10
0.570
11
0.600
12
0.600
13
12,000
14
Apr 09, 2019
['2019-04-09', '0.570', '0.570', '0.570', '0.570', '0.570', '20,000']
15
0.570
16
0.570
17
0.570
18
0.570
19
0.570
20
20,000
21
Apr 08, 2019
['2019-04-08', '0.570', '0.580', '0.570', '0.580', '0.580', '252,000']
22
0.570
23
0.580
24
0.570
25
0.580
26
0.580
27
252,000
28
Apr 04, 2019
['2019-04-04', '0.580', '0.580', '0.580', '0.580', '0.580', '-']
29
0.580
30
0.580
31
0.580
32
0.580
33
0.580
34
-
35
Apr 03, 2019
['2019-04-03', '0.590', '0.600', '0.600', '0.600', '0.600', '168,000']
36
0.590
37
0.600
38
0.600
39
0.600
40
0.600
41
168,000
42
Apr 02, 2019
['2019-04-02', '0.600', '0.600', '0.600', '0.600', '0.600', '20,000']
43
0.600
44
0.600
45
0.600
46
0.600
47
0.600
48
20,000
49
Apr 01, 2019
['2019-04-01', '0.590', '0.600', '0.590', '0.600', '0.600', '84,000']
50
0.590
51
0.600
52
0.590
53
0.600
54
0.600
55
84,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2858.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.010', '2.020', '1.970', '1.980', '1.980', '3,565,500']
1
2.010
2
2.020
3
1.970
4
1.980
5
1.980
6
3,565,500
7
Apr 10, 2019
['2019-04-10', '2.010', '2.040', '1.970', '2.030', '2.030', '4,099,716']
8
2.010
9
2.040
10
1.970
11
2.030
12
2.030
13
4,099,716
14
Apr 09, 2019
['2019-04-09', '2.040', '2.050', '2.020', '2.030', '2.030', '2,220,500']
15
2.040
16
2.050
17
2.020
18
2.030
19
2.030
20
2,220,500
21
Apr 08, 2019
['2019-04-08', '2.030', '2.050', '2.020', '2.040', '2.040', '3,062,000']
22
2.030
23
2.050
24
2.020
25
2.040
26
2.040
27
3,062,000
28
Apr 04, 2019
['2019-04-04', '2.100', '2.100', '2.010', '2.030', '2.030', '4,221,500']
29
2.100
30
2.100
31
2.010
32
2.030
33
2.030
34
4,221,500
35
Apr 03, 2019
['2019-04-03', '2.050', '2.100', '2.050', '2.080', '2.080', '3,583,500']
36
2.050
37
2.100
38
2.050
39
2.080
40
2.080
41
3,583,500
42
Apr 02, 2019
['2019-04-02', '2.000', '2.100', '1.990', '2.060', '2.060', '5,960,000']
43
2.000
44
2.100
45
1.990
46
2.060
47
2.060
48
5,960,000
49
Apr 01, 2019
['2019-04-01', '1.910', '2.010', '1.910', '2.000', '2.000', '7,527,600']
50
1.910
51
2.010
52
1.910
53
2.000
54
2.000
55
7,527,600
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8376.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.410', '0.410', '0.410', '0.410', '0.410', '-']
1
0.410
2
0.410
3
0.410
4
0.410
5
0.410
6
-
7
Apr 10, 2019
['2019-04-10', '0.395', '0.420', '0.395', '0.420', '0.420', '184,000']
8
0.395
9
0.420
10
0.395
11
0.420
12
0.420
13
184,000
14
Apr 09, 2019
['2019-04-09', '0.415', '0.420', '0.390', '0.395', '0.395', '200,000']
15
0.415
16
0.420
17
0.390
18
0.395
19
0.395
20
200,000
21
Apr 08, 2019
['2019-04-08', '0.445', '0.450', '0.400', '0.415', '0.415', '472,000']
22
0.445
23
0.450
24
0.400
25
0.415
26
0.415
27
472,000
28
Apr 04, 2019
['2019-04-04', '0.390', '0.395', '0.390', '0.395', '0.395', '32,000']
29
0.390
30
0.395
31
0.390
32
0.395
33
0.395
34
32,000
35
Apr 03, 2019
['2019-04-03', '0.400', '0.435', '0.380', '0.425', '0.425', '1,140,000']
36
0.400
37
0.435
38
0.380
39
0.425
40
0.425
41
1,140,000
42
Apr 02, 2019
['2019-04-02', '0.310', '0.430', '0.310', '0.400', '0.400', '4,244,000']
43
0.310
44
0.430
45
0.310
46
0.400
47
0.400
48
4,244,000
49
Apr 01, 2019
['2019-04-01', '0.310', '0.310', '0.310', '0.310', '0.310', '12,000']
50
0.310
51
0.310
52
0.310
53
0.310
54
0.310
55
12,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8400.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.170', '0.170', '0.158', '0.158', '0.158', '1,090,000']
1
0.170
2
0.170
3
0.158
4
0.158
5
0.158
6
1,090,000
7
Apr 10, 2019
['2019-04-10', '0.176', '0.176', '0.176', '0.176', '0.176', '20,000']
8
0.176
9
0.176
10
0.176
11
0.176
12
0.176
13
20,000
14
Apr 09, 2019
['2019-04-09', '0.187', '0.187', '0.187', '0.187', '0.187', '-']
15
0.187
16
0.187
17
0.187
18
0.187
19
0.187
20
-
21
Apr 08, 2019
['2019-04-08', '0.182', '0.189', '0.182', '0.187', '0.187', '780,000']
22
0.182
23
0.189
24
0.182
25
0.187
26
0.187
27
780,000
28
Apr 04, 2019
['2019-04-04', '0.188', '0.188', '0.188', '0.188', '0.188', '-']
29
0.188
30
0.188
31
0.188
32
0.188
33
0.188
34
-
35
Apr 03, 2019
['2019-04-03', '0.174', '0.180', '0.174', '0.180', '0.180', '900,000']
36
0.174
37
0.180
38
0.174
39
0.180
40
0.180
41
900,000
42
Apr 02, 2019
['2019-04-02', '0.170', '0.170', '0.170', '0.170', '0.170', '20,000']
43
0.170
44
0.170
45
0.170
46
0.170
47
0.170
48
20,000
49
Apr 01, 2019
['2019-04-01', '0.187', '0.194', '0.170', '0.170', '0.170', '720,000']
50
0.187
51
0.194
52
0.170
53
0.170
54
0.170
55
720,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1706.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.246', '0.250', '0.239', '0.250', '0.250', '830,000']
1
0.246
2
0.250
3
0.239
4
0.250
5
0.250
6
830,000
7
Apr 10, 2019
['2019-04-10', '0.255', '0.255', '0.247', '0.250', '0.250', '2,590,000']
8
0.255
9
0.255
10
0.247
11
0.250
12
0.250
13
2,590,000
14
Apr 09, 2019
['2019-04-09', '0.260', '0.270', '0.247', '0.255', '0.255', '2,975,000']
15
0.260
16
0.270
17
0.247
18
0.255
19
0.255
20
2,975,000
21
Apr 08, 2019
['2019-04-08', '0.300', '0.315', '0.260', '0.265', '0.265', '7,515,000']
22
0.300
23
0.315
24
0.260
25
0.265
26
0.265
27
7,515,000
28
Apr 04, 2019
['2019-04-04', '0.220', '0.295', '0.220', '0.290', '0.290', '42,405,000']
29
0.220
30
0.295
31
0.220
32
0.290
33
0.290
34
42,405,000
35
Apr 03, 2019
['2019-04-03', '0.224', '0.230', '0.223', '0.230', '0.230', '65,000']
36
0.224
37
0.230
38
0.223
39
0.230
40
0.230
41
65,000
42
Apr 02, 2019
['2019-04-02', '0.226', '0.230', '0.226', '0.229', '0.229', '85,000']
43
0.226
44
0.230
45
0.226
46
0.229
47
0.229
48
85,000
49
Apr 01, 2019
['2019-04-01', '0.227', '0.231', '0.227', '0.230', '0.230', '595,000']
50
0.227
51
0.231
52
0.227
53
0.230
54
0.230
55
595,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6083.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.870', '0.870', '0.830', '0.840', '0.840', '424,000']
1
0.870
2
0.870
3
0.830
4
0.840
5
0.840
6
424,000
7
Apr 10, 2019
['2019-04-10', '0.880', '0.880', '0.850', '0.860', '0.860', '604,000']
8
0.880
9
0.880
10
0.850
11
0.860
12
0.860
13
604,000
14
Apr 09, 2019
['2019-04-09', '0.870', '0.870', '0.840', '0.860', '0.860', '1,664,000']
15
0.870
16
0.870
17
0.840
18
0.860
19
0.860
20
1,664,000
21
Apr 08, 2019
['2019-04-08', '0.870', '0.870', '0.830', '0.860', '0.860', '1,188,000']
22
0.870
23
0.870
24
0.830
25
0.860
26
0.860
27
1,188,000
28
Apr 04, 2019
['2019-04-04', '0.870', '0.880', '0.850', '0.850', '0.850', '960,000']
29
0.870
30
0.880
31
0.850
32
0.850
33
0.850
34
960,000
35
Apr 03, 2019
['2019-04-03', '0.860', '0.880', '0.850', '0.870', '0.870', '896,000']
36
0.860
37
0.880
38
0.850
39
0.870
40
0.870
41
896,000
42
Apr 02, 2019
['2019-04-02', '0.850', '0.870', '0.850', '0.860', '0.860', '1,568,000']
43
0.850
44
0.870
45
0.850
46
0.860
47
0.860
48
1,568,000
49
Apr 01, 2019
['2019-04-01', '0.850', '0.880', '0.850', '0.860', '0.860', '2,336,000']
50
0.850
51
0.880
52
0.850
53
0.860
54
0.860
55
2,336,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8375.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.120', '0.121', '0.117', '0.121', '0.121', '24,410,000']
1
0.120
2
0.121
3
0.117
4
0.121
5
0.121
6
24,410,000
7
Apr 10, 2019
['2019-04-10', '0.120', '0.120', '0.120', '0.120', '0.120', '-']
8
0.120
9
0.120
10
0.120
11
0.120
12
0.120
13
-
14
Apr 09, 2019
['2019-04-09', '0.119', '0.119', '0.119', '0.119', '0.119', '4,300,000']
15
0.119
16
0.119
17
0.119
18
0.119
19
0.119
20
4,300,000
21
Apr 08, 2019
['2019-04-08', '0.119', '0.119', '0.119', '0.119', '0.119', '-']
22
0.119
23
0.119
24
0.119
25
0.119
26
0.119
27
-
28
Apr 04, 2019
['2019-04-04', '0.131', '0.131', '0.116', '0.119', '0.119', '3,490,000']
29
0.131
30
0.131
31
0.116
32
0.119
33
0.119
34
3,490,000
35
Apr 03, 2019
['2019-04-03', '0.130', '0.131', '0.130', '0.131', '0.131', '220,000']
36
0.130
37
0.131
38
0.130
39
0.131
40
0.131
41
220,000
42
Apr 02, 2019
['2019-04-02', '0.130', '0.130', '0.130', '0.130', '0.130', '100,000']
43
0.130
44
0.130
45
0.130
46
0.130
47
0.130
48
100,000
49
Apr 01, 2019
['2019-04-01', '0.130', '0.130', '0.130', '0.130', '0.130', '100,000']
50
0.130
51
0.130
52
0.130
53
0.130
54
0.130
55
100,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1337.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.810', '1.880', '1.770', '1.840', '1.840', '40,868,983']
1
1.810
2
1.880
3
1.770
4
1.840
5
1.840
6
40,868,983
7
Apr 10, 2019
['2019-04-10', '1.750', '1.820', '1.750', '1.800', '1.800', '48,140,951']
8
1.750
9
1.820
10
1.750
11
1.800
12
1.800
13
48,140,951
14
Apr 09, 2019
['2019-04-09', '1.700', '1.730', '1.670', '1.720', '1.720', '31,188,863']
15
1.700
16
1.730
17
1.670
18
1.720
19
1.720
20
31,188,863
21
Apr 08, 2019
['2019-04-08', '1.700', '1.740', '1.670', '1.690', '1.690', '23,413,555']
22
1.700
23
1.740
24
1.670
25
1.690
26
1.690
27
23,413,555
28
Apr 04, 2019
['2019-04-04', '1.700', '1.710', '1.660', '1.700', '1.700', '11,664,944']
29
1.700
30
1.710
31
1.660
32
1.700
33
1.700
34
11,664,944
35
Apr 03, 2019
['2019-04-03', '1.720', '1.740', '1.660', '1.700', '1.700', '19,842,511']
36
1.720
37
1.740
38
1.660
39
1.700
40
1.700
41
19,842,511
42
Apr 02, 2019
['2019-04-02', '1.670', '1.760', '1.640', '1.720', '1.720', '29,484,822']
43
1.670
44
1.760
45
1.640
46
1.720
47
1.720
48
29,484,822
49
Apr 01, 2019
['2019-04-01', '1.650', '1.690', '1.650', '1.660', '1.660', '11,812,828']
50
1.650
51
1.690
52
1.650
53
1.660
54
1.660
55
11,812,828
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8426.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.171', '0.171', '0.171', '0.171', '0.171', '-']
1
0.171
2
0.171
3
0.171
4
0.171
5
0.171
6
-
7
Apr 10, 2019
['2019-04-10', '0.171', '0.171', '0.171', '0.171', '0.171', '-']
8
0.171
9
0.171
10
0.171
11
0.171
12
0.171
13
-
14
Apr 09, 2019
['2019-04-09', '0.173', '0.178', '0.164', '0.168', '0.168', '270,000']
15
0.173
16
0.178
17
0.164
18
0.168
19
0.168
20
270,000
21
Apr 08, 2019
['2019-04-08', '0.175', '0.180', '0.168', '0.178', '0.178', '150,000']
22
0.175
23
0.180
24
0.168
25
0.178
26
0.178
27
150,000
28
Apr 04, 2019
['2019-04-04', '0.173', '0.173', '0.173', '0.173', '0.173', '-']
29
0.173
30
0.173
31
0.173
32
0.173
33
0.173
34
-
35
Apr 03, 2019
['2019-04-03', '0.175', '0.175', '0.175', '0.175', '0.175', '20,000']
36
0.175
37
0.175
38
0.175
39
0.175
40
0.175
41
20,000
42
Apr 02, 2019
['2019-04-02', '0.170', '0.170', '0.170', '0.170', '0.170', '290,000']
43
0.170
44
0.170
45
0.170
46
0.170
47
0.170
48
290,000
49
Apr 01, 2019
['2019-04-01', '0.169', '0.175', '0.165', '0.175', '0.175', '1,230,000']
50
0.169
51
0.175
52
0.165
53
0.175
54
0.175
55
1,230,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3919.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.610', '0.610', '0.610', '0.610', '0.610', '2,000']
1
0.610
2
0.610
3
0.610
4
0.610
5
0.610
6
2,000
7
Apr 10, 2019
['2019-04-10', '0.620', '0.620', '0.590', '0.590', '0.590', '92,000']
8
0.620
9
0.620
10
0.590
11
0.590
12
0.590
13
92,000
14
Apr 09, 2019
['2019-04-09', '0.620', '0.620', '0.600', '0.620', '0.620', '34,000']
15
0.620
16
0.620
17
0.600
18
0.620
19
0.620
20
34,000
21
Apr 08, 2019
['2019-04-08', '0.620', '0.620', '0.620', '0.620', '0.620', '2,000']
22
0.620
23
0.620
24
0.620
25
0.620
26
0.620
27
2,000
28
Apr 04, 2019
['2019-04-04', '0.610', '0.610', '0.600', '0.600', '0.600', '65,000']
29
0.610
30
0.610
31
0.600
32
0.600
33
0.600
34
65,000
35
Apr 03, 2019
['2019-04-03', '0.600', '0.610', '0.600', '0.610', '0.610', '21,000']
36
0.600
37
0.610
38
0.600
39
0.610
40
0.610
41
21,000
42
Apr 02, 2019
['2019-04-02', '0.610', '0.630', '0.600', '0.630', '0.630', '68,000']
43
0.610
44
0.630
45
0.600
46
0.630
47
0.630
48
68,000
49
Apr 01, 2019
['2019-04-01', '0.630', '0.640', '0.620', '0.620', '0.620', '98,000']
50
0.630
51
0.640
52
0.620
53
0.620
54
0.620
55
98,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2122.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.395', '0.405', '0.390', '0.395', '0.395', '1,568,000']
1
0.395
2
0.405
3
0.390
4
0.395
5
0.395
6
1,568,000
7
Apr 10, 2019
['2019-04-10', '0.395', '0.410', '0.390', '0.405', '0.405', '1,472,000']
8
0.395
9
0.410
10
0.390
11
0.405
12
0.405
13
1,472,000
14
Apr 09, 2019
['2019-04-09', '0.405', '0.405', '0.395', '0.405', '0.405', '270,000']
15
0.405
16
0.405
17
0.395
18
0.405
19
0.405
20
270,000
21
Apr 08, 2019
['2019-04-08', '0.400', '0.410', '0.400', '0.410', '0.410', '370,000']
22
0.400
23
0.410
24
0.400
25
0.410
26
0.410
27
370,000
28
Apr 04, 2019
['2019-04-04', '0.405', '0.415', '0.380', '0.400', '0.400', '1,792,000']
29
0.405
30
0.415
31
0.380
32
0.400
33
0.400
34
1,792,000
35
Apr 03, 2019
['2019-04-03', '0.405', '0.415', '0.400', '0.415', '0.415', '1,472,000']
36
0.405
37
0.415
38
0.400
39
0.415
40
0.415
41
1,472,000
42
Apr 02, 2019
['2019-04-02', '0.440', '0.445', '0.410', '0.415', '0.415', '2,248,000']
43
0.440
44
0.445
45
0.410
46
0.415
47
0.415
48
2,248,000
49
Apr 01, 2019
['2019-04-01', '0.455', '0.455', '0.425', '0.440', '0.440', '4,114,000']
50
0.455
51
0.455
52
0.425
53
0.440
54
0.440
55
4,114,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1720.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.580', '2.560', '2.530', '2.560', '2.560', '208,000']
1
2.580
2
2.560
3
2.530
4
2.560
5
2.560
6
208,000
7
Apr 10, 2019
['2019-04-10', '2.560', '2.580', '2.500', '2.550', '2.550', '376,000']
8
2.560
9
2.580
10
2.500
11
2.550
12
2.550
13
376,000
14
Apr 09, 2019
['2019-04-09', '2.520', '2.620', '2.460', '2.620', '2.620', '1,004,000']
15
2.520
16
2.620
17
2.460
18
2.620
19
2.620
20
1,004,000
21
Apr 08, 2019
['2019-04-08', '2.590', '2.700', '2.580', '2.640', '2.640', '712,000']
22
2.590
23
2.700
24
2.580
25
2.640
26
2.640
27
712,000
28
Apr 04, 2019
['2019-04-04', '2.730', '2.740', '2.590', '2.590', '2.590', '2,420,000']
29
2.730
30
2.740
31
2.590
32
2.590
33
2.590
34
2,420,000
35
Apr 03, 2019
['2019-04-03', '2.790', '2.800', '2.710', '2.720', '2.720', '1,232,000']
36
2.790
37
2.800
38
2.710
39
2.720
40
2.720
41
1,232,000
42
Apr 02, 2019
['2019-04-02', '2.780', '2.820', '2.770', '2.790', '2.790', '264,000']
43
2.780
44
2.820
45
2.770
46
2.790
47
2.790
48
264,000
49
Apr 01, 2019
['2019-04-01', '2.920', '2.920', '2.680', '2.830', '2.830', '984,000']
50
2.920
51
2.920
52
2.680
53
2.830
54
2.830
55
984,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0772.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '39.200', '39.650', '37.850', '38.150', '38.150', '2,756,925']
1
39.200
2
39.650
3
37.850
4
38.150
5
38.150
6
2,756,925
7
Apr 10, 2019
['2019-04-10', '37.700', '39.400', '37.700', '39.200', '39.200', '2,899,013']
8
37.700
9
39.400
10
37.700
11
39.200
12
39.200
13
2,899,013
14
Apr 09, 2019
['2019-04-09', '37.050', '38.600', '37.050', '38.350', '38.350', '2,818,738']
15
37.050
16
38.600
17
37.050
18
38.350
19
38.350
20
2,818,738
21
Apr 08, 2019
['2019-04-08', '38.350', '38.500', '36.850', '37.200', '37.200', '2,539,975']
22
38.350
23
38.500
24
36.850
25
37.200
26
37.200
27
2,539,975
28
Apr 04, 2019
['2019-04-04', '37.550', '38.100', '37.300', '38.100', '38.100', '3,105,937']
29
37.550
30
38.100
31
37.300
32
38.100
33
38.100
34
3,105,937
35
Apr 03, 2019
['2019-04-03', '36.000', '37.800', '36.000', '37.800', '37.800', '7,275,712']
36
36.000
37
37.800
38
36.000
39
37.800
40
37.800
41
7,275,712
42
Apr 02, 2019
['2019-04-02', '37.100', '37.350', '35.900', '35.900', '35.900', '2,549,030']
43
37.100
44
37.350
45
35.900
46
35.900
47
35.900
48
2,549,030
49
Apr 01, 2019
['2019-04-01', '36.700', '37.600', '36.700', '37.000', '37.000', '1,739,301']
50
36.700
51
37.600
52
36.700
53
37.000
54
37.000
55
1,739,301
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2232.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.090', '4.100', '4.030', '4.090', '4.090', '401,000']
1
4.090
2
4.100
3
4.030
4
4.090
5
4.090
6
401,000
7
Apr 10, 2019
['2019-04-10', '4.150', '4.150', '4.030', '4.090', '4.090', '2,346,000']
8
4.150
9
4.150
10
4.030
11
4.090
12
4.090
13
2,346,000
14
Apr 09, 2019
['2019-04-09', '4.100', '4.170', '4.060', '4.100', '4.100', '1,073,215']
15
4.100
16
4.170
17
4.060
18
4.100
19
4.100
20
1,073,215
21
Apr 08, 2019
['2019-04-08', '4.080', '4.170', '4.080', '4.100', '4.100', '540,500']
22
4.080
23
4.170
24
4.080
25
4.100
26
4.100
27
540,500
28
Apr 04, 2019
['2019-04-04', '4.190', '4.190', '4.080', '4.180', '4.180', '467,500']
29
4.190
30
4.190
31
4.080
32
4.180
33
4.180
34
467,500
35
Apr 03, 2019
['2019-04-03', '4.040', '4.170', '3.980', '4.140', '4.140', '591,788']
36
4.040
37
4.170
38
3.980
39
4.140
40
4.140
41
591,788
42
Apr 02, 2019
['2019-04-02', '4.090', '4.120', '3.980', '3.980', '3.980', '14,381,000']
43
4.090
44
4.120
45
3.980
46
3.980
47
3.980
48
14,381,000
49
Apr 01, 2019
['2019-04-01', '4.150', '4.150', '4.090', '4.110', '4.110', '326,000']
50
4.150
51
4.150
52
4.090
53
4.110
54
4.110
55
326,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8436.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.840', '3.840', '3.730', '3.820', '3.820', '1,230,000']
1
3.840
2
3.840
3
3.730
4
3.820
5
3.820
6
1,230,000
7
Apr 10, 2019
['2019-04-10', '3.750', '3.870', '3.700', '3.830', '3.830', '535,000']
8
3.750
9
3.870
10
3.700
11
3.830
12
3.830
13
535,000
14
Apr 09, 2019
['2019-04-09', '3.830', '3.870', '3.660', '3.800', '3.800', '1,640,000']
15
3.830
16
3.870
17
3.660
18
3.800
19
3.800
20
1,640,000
21
Apr 08, 2019
['2019-04-08', '3.900', '3.950', '3.830', '3.880', '3.880', '1,190,000']
22
3.900
23
3.950
24
3.830
25
3.880
26
3.880
27
1,190,000
28
Apr 04, 2019
['2019-04-04', '4.120', '4.120', '3.840', '4.050', '4.050', '2,420,000']
29
4.120
30
4.120
31
3.840
32
4.050
33
4.050
34
2,420,000
35
Apr 03, 2019
['2019-04-03', '3.900', '4.130', '3.900', '4.120', '4.120', '3,550,000']
36
3.900
37
4.130
38
3.900
39
4.120
40
4.120
41
3,550,000
42
Apr 02, 2019
['2019-04-02', '3.870', '3.960', '3.850', '3.950', '3.950', '1,285,000']
43
3.870
44
3.960
45
3.850
46
3.950
47
3.950
48
1,285,000
49
Apr 01, 2019
['2019-04-01', '3.950', '3.950', '3.810', '3.900', '3.900', '370,000']
50
3.950
51
3.950
52
3.810
53
3.900
54
3.900
55
370,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1546.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.640', '0.660', '0.640', '0.660', '0.660', '1,744,000']
1
0.640
2
0.660
3
0.640
4
0.660
5
0.660
6
1,744,000
7
Apr 10, 2019
['2019-04-10', '0.640', '0.660', '0.620', '0.640', '0.640', '864,000']
8
0.640
9
0.660
10
0.620
11
0.640
12
0.640
13
864,000
14
Apr 09, 2019
['2019-04-09', '0.640', '0.650', '0.620', '0.630', '0.630', '1,072,000']
15
0.640
16
0.650
17
0.620
18
0.630
19
0.630
20
1,072,000
21
Apr 08, 2019
['2019-04-08', '0.640', '0.640', '0.640', '0.640', '0.640', '-']
22
0.640
23
0.640
24
0.640
25
0.640
26
0.640
27
-
28
Apr 04, 2019
['2019-04-04', '0.620', '0.680', '0.610', '0.640', '0.640', '1,876,000']
29
0.620
30
0.680
31
0.610
32
0.640
33
0.640
34
1,876,000
35
Apr 03, 2019
['2019-04-03', '0.610', '0.620', '0.610', '0.610', '0.610', '80,000']
36
0.610
37
0.620
38
0.610
39
0.610
40
0.610
41
80,000
42
Apr 02, 2019
['2019-04-02', '0.600', '0.620', '0.600', '0.610', '0.610', '720,000']
43
0.600
44
0.620
45
0.600
46
0.610
47
0.610
48
720,000
49
Apr 01, 2019
['2019-04-01', '0.600', '0.620', '0.600', '0.600', '0.600', '728,000']
50
0.600
51
0.620
52
0.600
53
0.600
54
0.600
55
728,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8470.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.275', '0.330', '0.270', '0.290', '0.290', '3,464,000']
1
0.275
2
0.330
3
0.270
4
0.290
5
0.290
6
3,464,000
7
Apr 10, 2019
['2019-04-10', '0.300', '0.300', '0.275', '0.275', '0.275', '1,752,000']
8
0.300
9
0.300
10
0.275
11
0.275
12
0.275
13
1,752,000
14
Apr 09, 2019
['2019-04-09', '0.300', '0.305', '0.290', '0.300', '0.300', '416,000']
15
0.300
16
0.305
17
0.290
18
0.300
19
0.300
20
416,000
21
Apr 08, 2019
['2019-04-08', '0.315', '0.320', '0.300', '0.300', '0.300', '512,000']
22
0.315
23
0.320
24
0.300
25
0.300
26
0.300
27
512,000
28
Apr 04, 2019
['2019-04-04', '0.310', '0.320', '0.305', '0.310', '0.310', '592,000']
29
0.310
30
0.320
31
0.305
32
0.310
33
0.310
34
592,000
35
Apr 03, 2019
['2019-04-03', '0.305', '0.325', '0.300', '0.310', '0.310', '1,600,000']
36
0.305
37
0.325
38
0.300
39
0.310
40
0.310
41
1,600,000
42
Apr 02, 2019
['2019-04-02', '0.300', '0.310', '0.300', '0.305', '0.305', '928,000']
43
0.300
44
0.310
45
0.300
46
0.305
47
0.305
48
928,000
49
Apr 01, 2019
['2019-04-01', '0.305', '0.315', '0.300', '0.305', '0.305', '1,136,000']
50
0.305
51
0.315
52
0.300
53
0.305
54
0.305
55
1,136,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2663.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.305', '0.305', '0.305', '0.305', '0.305', '-']
1
0.305
2
0.305
3
0.305
4
0.305
5
0.305
6
-
7
Apr 10, 2019
['2019-04-10', '0.305', '0.305', '0.305', '0.305', '0.305', '-']
8
0.305
9
0.305
10
0.305
11
0.305
12
0.305
13
-
14
Apr 09, 2019
['2019-04-09', '0.305', '0.320', '0.305', '0.305', '0.305', '370,000']
15
0.305
16
0.320
17
0.305
18
0.305
19
0.305
20
370,000
21
Apr 08, 2019
['2019-04-08', '0.310', '0.310', '0.310', '0.310', '0.310', '-']
22
0.310
23
0.310
24
0.310
25
0.310
26
0.310
27
-
28
Apr 04, 2019
['2019-04-04', '0.310', '0.310', '0.310', '0.310', '0.310', '-']
29
0.310
30
0.310
31
0.310
32
0.310
33
0.310
34
-
35
Apr 03, 2019
['2019-04-03', '0.305', '0.325', '0.305', '0.310', '0.310', '730,000']
36
0.305
37
0.325
38
0.305
39
0.310
40
0.310
41
730,000
42
Apr 02, 2019
['2019-04-02', '0.315', '0.315', '0.315', '0.315', '0.315', '-']
43
0.315
44
0.315
45
0.315
46
0.315
47
0.315
48
-
49
Apr 01, 2019
['2019-04-01', '0.315', '0.315', '0.315', '0.315', '0.315', '130,000']
50
0.315
51
0.315
52
0.315
53
0.315
54
0.315
55
130,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6080.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.580', '0.580', '0.580', '0.580', '0.580', '30,000']
1
0.580
2
0.580
3
0.580
4
0.580
5
0.580
6
30,000
7
Apr 10, 2019
['2019-04-10', '0.590', '0.600', '0.580', '0.580', '0.580', '198,000']
8
0.590
9
0.600
10
0.580
11
0.580
12
0.580
13
198,000
14
Apr 09, 2019
['2019-04-09', '0.570', '0.590', '0.570', '0.590', '0.590', '102,000']
15
0.570
16
0.590
17
0.570
18
0.590
19
0.590
20
102,000
21
Apr 08, 2019
['2019-04-08', '0.590', '0.590', '0.570', '0.570', '0.570', '1,002,000']
22
0.590
23
0.590
24
0.570
25
0.570
26
0.570
27
1,002,000
28
Apr 04, 2019
['2019-04-04', '0.590', '0.590', '0.590', '0.590', '0.590', '54,000']
29
0.590
30
0.590
31
0.590
32
0.590
33
0.590
34
54,000
35
Apr 03, 2019
['2019-04-03', '0.590', '0.600', '0.590', '0.590', '0.590', '150,000']
36
0.590
37
0.600
38
0.590
39
0.590
40
0.590
41
150,000
42
Apr 02, 2019
['2019-04-02', '0.590', '0.600', '0.580', '0.590', '0.590', '156,000']
43
0.590
44
0.600
45
0.580
46
0.590
47
0.590
48
156,000
49
Apr 01, 2019
['2019-04-01', '0.590', '0.590', '0.570', '0.590', '0.590', '156,000']
50
0.590
51
0.590
52
0.570
53
0.590
54
0.590
55
156,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8476.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.670', '0.680', '0.670', '0.680', '0.680', '8,000']
1
0.670
2
0.680
3
0.670
4
0.680
5
0.680
6
8,000
7
Apr 10, 2019
['2019-04-10', '0.690', '0.690', '0.690', '0.690', '0.690', '-']
8
0.690
9
0.690
10
0.690
11
0.690
12
0.690
13
-
14
Apr 09, 2019
['2019-04-09', '0.690', '0.690', '0.690', '0.690', '0.690', '-']
15
0.690
16
0.690
17
0.690
18
0.690
19
0.690
20
-
21
Apr 08, 2019
['2019-04-08', '0.680', '0.680', '0.680', '0.680', '0.680', '-']
22
0.680
23
0.680
24
0.680
25
0.680
26
0.680
27
-
28
Apr 04, 2019
['2019-04-04', '0.670', '0.680', '0.650', '0.680', '0.680', '50,000']
29
0.670
30
0.680
31
0.650
32
0.680
33
0.680
34
50,000
35
Apr 03, 2019
['2019-04-03', '0.670', '0.670', '0.670', '0.670', '0.670', '4,000']
36
0.670
37
0.670
38
0.670
39
0.670
40
0.670
41
4,000
42
Apr 02, 2019
['2019-04-02', '0.670', '0.670', '0.660', '0.670', '0.670', '16,000']
43
0.670
44
0.670
45
0.660
46
0.670
47
0.670
48
16,000
49
Apr 01, 2019
['2019-04-01', '0.650', '0.670', '0.650', '0.670', '0.670', '26,000']
50
0.650
51
0.670
52
0.650
53
0.670
54
0.670
55
26,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8457.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.215', '0.235', '0.212', '0.229', '0.229', '4,900,000']
1
0.215
2
0.235
3
0.212
4
0.229
5
0.229
6
4,900,000
7
Apr 10, 2019
['2019-04-10', '0.214', '0.225', '0.206', '0.214', '0.214', '2,480,000']
8
0.214
9
0.225
10
0.206
11
0.214
12
0.214
13
2,480,000
14
Apr 09, 2019
['2019-04-09', '0.210', '0.214', '0.205', '0.214', '0.214', '940,000']
15
0.210
16
0.214
17
0.205
18
0.214
19
0.214
20
940,000
21
Apr 08, 2019
['2019-04-08', '0.210', '0.210', '0.210', '0.210', '0.210', '850,000']
22
0.210
23
0.210
24
0.210
25
0.210
26
0.210
27
850,000
28
Apr 04, 2019
['2019-04-04', '0.203', '0.210', '0.203', '0.210', '0.210', '800,000']
29
0.203
30
0.210
31
0.203
32
0.210
33
0.210
34
800,000
35
Apr 03, 2019
['2019-04-03', '0.210', '0.210', '0.210', '0.210', '0.210', '-']
36
0.210
37
0.210
38
0.210
39
0.210
40
0.210
41
-
42
Apr 02, 2019
['2019-04-02', '0.202', '0.210', '0.201', '0.210', '0.210', '670,000']
43
0.202
44
0.210
45
0.201
46
0.210
47
0.210
48
670,000
49
Apr 01, 2019
['2019-04-01', '0.212', '0.212', '0.206', '0.206', '0.206', '790,000']
50
0.212
51
0.212
52
0.206
53
0.206
54
0.206
55
790,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8430.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.141', '0.145', '0.139', '0.144', '0.144', '2,700,000']
1
0.141
2
0.145
3
0.139
4
0.144
5
0.144
6
2,700,000
7
Apr 10, 2019
['2019-04-10', '0.141', '0.144', '0.138', '0.142', '0.142', '2,265,000']
8
0.141
9
0.144
10
0.138
11
0.142
12
0.142
13
2,265,000
14
Apr 09, 2019
['2019-04-09', '0.143', '0.146', '0.140', '0.141', '0.141', '1,235,000']
15
0.143
16
0.146
17
0.140
18
0.141
19
0.141
20
1,235,000
21
Apr 08, 2019
['2019-04-08', '0.143', '0.147', '0.143', '0.143', '0.143', '765,000']
22
0.143
23
0.147
24
0.143
25
0.143
26
0.143
27
765,000
28
Apr 04, 2019
['2019-04-04', '0.141', '0.146', '0.140', '0.143', '0.143', '455,000']
29
0.141
30
0.146
31
0.140
32
0.143
33
0.143
34
455,000
35
Apr 03, 2019
['2019-04-03', '0.143', '0.150', '0.138', '0.142', '0.142', '4,785,000']
36
0.143
37
0.150
38
0.138
39
0.142
40
0.142
41
4,785,000
42
Apr 02, 2019
['2019-04-02', '0.138', '0.148', '0.141', '0.145', '0.145', '1,925,000']
43
0.138
44
0.148
45
0.141
46
0.145
47
0.145
48
1,925,000
49
Apr 01, 2019
['2019-04-01', '0.146', '0.150', '0.135', '0.144', '0.144', '2,950,000']
50
0.146
51
0.150
52
0.135
53
0.144
54
0.144
55
2,950,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2225.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.900', '1.900', '1.900', '1.900', '1.900', '10,000']
1
1.900
2
1.900
3
1.900
4
1.900
5
1.900
6
10,000
7
Apr 10, 2019
['2019-04-10', '1.950', '1.950', '1.950', '1.950', '1.950', '120,000']
8
1.950
9
1.950
10
1.950
11
1.950
12
1.950
13
120,000
14
Apr 09, 2019
['2019-04-09', '1.950', '1.950', '1.930', '1.950', '1.950', '120,000']
15
1.950
16
1.950
17
1.930
18
1.950
19
1.950
20
120,000
21
Apr 08, 2019
['2019-04-08', '1.970', '1.960', '1.950', '1.950', '1.950', '245,000']
22
1.970
23
1.960
24
1.950
25
1.950
26
1.950
27
245,000
28
Apr 04, 2019
['2019-04-04', '1.970', '1.990', '1.960', '1.990', '1.990', '715,000']
29
1.970
30
1.990
31
1.960
32
1.990
33
1.990
34
715,000
35
Apr 03, 2019
['2019-04-03', '1.920', '1.920', '1.920', '1.920', '1.920', '-']
36
1.920
37
1.920
38
1.920
39
1.920
40
1.920
41
-
42
Apr 02, 2019
['2019-04-02', '1.990', '1.990', '1.870', '1.900', '1.900', '720,000']
43
1.990
44
1.990
45
1.870
46
1.900
47
1.900
48
720,000
49
Apr 01, 2019
['2019-04-01', '1.960', '1.960', '1.960', '1.960', '1.960', '-']
50
1.960
51
1.960
52
1.960
53
1.960
54
1.960
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8392.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.215', '0.217', '0.215', '0.217', '0.217', '100,000']
1
0.215
2
0.217
3
0.215
4
0.217
5
0.217
6
100,000
7
Apr 10, 2019
['2019-04-10', '0.212', '0.222', '0.212', '0.215', '0.215', '1,200,000']
8
0.212
9
0.222
10
0.212
11
0.215
12
0.215
13
1,200,000
14
Apr 09, 2019
['2019-04-09', '0.230', '0.230', '0.230', '0.230', '0.230', '-']
15
0.230
16
0.230
17
0.230
18
0.230
19
0.230
20
-
21
Apr 08, 2019
['2019-04-08', '0.228', '0.230', '0.227', '0.230', '0.230', '130,000']
22
0.228
23
0.230
24
0.227
25
0.230
26
0.230
27
130,000
28
Apr 04, 2019
['2019-04-04', '0.231', '0.231', '0.231', '0.231', '0.231', '-']
29
0.231
30
0.231
31
0.231
32
0.231
33
0.231
34
-
35
Apr 03, 2019
['2019-04-03', '0.247', '0.247', '0.229', '0.233', '0.233', '660,000']
36
0.247
37
0.247
38
0.229
39
0.233
40
0.233
41
660,000
42
Apr 02, 2019
['2019-04-02', '0.214', '0.217', '0.205', '0.210', '0.210', '150,000']
43
0.214
44
0.217
45
0.205
46
0.210
47
0.210
48
150,000
49
Apr 01, 2019
['2019-04-01', '0.218', '0.218', '0.218', '0.218', '0.218', '-']
50
0.218
51
0.218
52
0.218
53
0.218
54
0.218
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8480.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.980', '3.000', '2.960', '2.980', '2.980', '76,000']
1
2.980
2
3.000
3
2.960
4
2.980
5
2.980
6
76,000
7
Apr 10, 2019
['2019-04-10', '2.970', '2.980', '2.970', '2.980', '2.980', '20,000']
8
2.970
9
2.980
10
2.970
11
2.980
12
2.980
13
20,000
14
Apr 09, 2019
['2019-04-09', '2.990', '2.990', '2.950', '2.970', '2.970', '60,000']
15
2.990
16
2.990
17
2.950
18
2.970
19
2.970
20
60,000
21
Apr 08, 2019
['2019-04-08', '2.920', '3.030', '2.920', '2.990', '2.990', '256,000']
22
2.920
23
3.030
24
2.920
25
2.990
26
2.990
27
256,000
28
Apr 04, 2019
['2019-04-04', '2.920', '2.920', '2.810', '2.920', '2.920', '216,000']
29
2.920
30
2.920
31
2.810
32
2.920
33
2.920
34
216,000
35
Apr 03, 2019
['2019-04-03', '2.850', '2.920', '2.850', '2.920', '2.920', '240,000']
36
2.850
37
2.920
38
2.850
39
2.920
40
2.920
41
240,000
42
Apr 02, 2019
['2019-04-02', '2.840', '2.930', '2.810', '2.850', '2.850', '3,036,000']
43
2.840
44
2.930
45
2.810
46
2.850
47
2.850
48
3,036,000
49
Apr 01, 2019
['2019-04-01', '2.800', '2.890', '2.790', '2.840', '2.840', '172,000']
50
2.800
51
2.890
52
2.790
53
2.840
54
2.840
55
172,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8275.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.117', '0.129', '0.117', '0.122', '0.122', '560,000']
1
0.117
2
0.129
3
0.117
4
0.122
5
0.122
6
560,000
7
Apr 10, 2019
['2019-04-10', '0.120', '0.120', '0.119', '0.119', '0.119', '280,000']
8
0.120
9
0.120
10
0.119
11
0.119
12
0.119
13
280,000
14
Apr 09, 2019
['2019-04-09', '0.118', '0.125', '0.118', '0.122', '0.122', '380,000']
15
0.118
16
0.125
17
0.118
18
0.122
19
0.122
20
380,000
21
Apr 08, 2019
['2019-04-08', '0.117', '0.117', '0.117', '0.118', '0.118', '10,000']
22
0.117
23
0.117
24
0.117
25
0.118
26
0.118
27
10,000
28
Apr 04, 2019
['2019-04-04', '0.116', '0.116', '0.116', '0.116', '0.116', '240,000']
29
0.116
30
0.116
31
0.116
32
0.116
33
0.116
34
240,000
35
Apr 03, 2019
['2019-04-03', '0.121', '0.121', '0.116', '0.119', '0.119', '810,000']
36
0.121
37
0.121
38
0.116
39
0.119
40
0.119
41
810,000
42
Apr 02, 2019
['2019-04-02', '0.119', '0.126', '0.115', '0.124', '0.124', '340,000']
43
0.119
44
0.126
45
0.115
46
0.124
47
0.124
48
340,000
49
Apr 01, 2019
['2019-04-01', '0.121', '0.121', '0.119', '0.119', '0.119', '230,000']
50
0.121
51
0.121
52
0.119
53
0.119
54
0.119
55
230,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2337.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.990', '5.020', '4.980', '5.010', '5.010', '332,000']
1
4.990
2
5.020
3
4.980
4
5.010
5
5.010
6
332,000
7
Apr 10, 2019
['2019-04-10', '5.020', '5.040', '4.900', '5.010', '5.010', '390,000']
8
5.020
9
5.040
10
4.900
11
5.010
12
5.010
13
390,000
14
Apr 09, 2019
['2019-04-09', '5.090', '5.130', '5.000', '5.070', '5.070', '357,000']
15
5.090
16
5.130
17
5.000
18
5.070
19
5.070
20
357,000
21
Apr 08, 2019
['2019-04-08', '5.160', '5.160', '5.100', '5.110', '5.110', '355,000']
22
5.160
23
5.160
24
5.100
25
5.110
26
5.110
27
355,000
28
Apr 04, 2019
['2019-04-04', '5.130', '5.180', '5.090', '5.130', '5.130', '338,000']
29
5.130
30
5.180
31
5.090
32
5.130
33
5.130
34
338,000
35
Apr 03, 2019
['2019-04-03', '5.200', '5.270', '5.130', '5.150', '5.150', '230,000']
36
5.200
37
5.270
38
5.130
39
5.150
40
5.150
41
230,000
42
Apr 02, 2019
['2019-04-02', '5.260', '5.300', '5.210', '5.250', '5.250', '241,000']
43
5.260
44
5.300
45
5.210
46
5.250
47
5.250
48
241,000
49
Apr 01, 2019
['2019-04-01', '5.420', '5.490', '5.290', '5.350', '5.350', '234,000']
50
5.420
51
5.490
52
5.290
53
5.350
54
5.350
55
234,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8065.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.290', '0.300', '0.290', '0.300', '0.300', '80,000']
1
0.290
2
0.300
3
0.290
4
0.300
5
0.300
6
80,000
7
Apr 10, 2019
['2019-04-10', '0.290', '0.290', '0.290', '0.290', '0.290', '-']
8
0.290
9
0.290
10
0.290
11
0.290
12
0.290
13
-
14
Apr 09, 2019
['2019-04-09', '0.290', '0.290', '0.290', '0.290', '0.290', '15,000']
15
0.290
16
0.290
17
0.290
18
0.290
19
0.290
20
15,000
21
Apr 08, 2019
['2019-04-08', '0.300', '0.300', '0.290', '0.290', '0.290', '70,000']
22
0.300
23
0.300
24
0.290
25
0.290
26
0.290
27
70,000
28
Apr 04, 2019
['2019-04-04', '0.300', '0.310', '0.300', '0.305', '0.305', '170,000']
29
0.300
30
0.310
31
0.300
32
0.305
33
0.305
34
170,000
35
Apr 03, 2019
['2019-04-03', '0.295', '0.295', '0.295', '0.295', '0.295', '-']
36
0.295
37
0.295
38
0.295
39
0.295
40
0.295
41
-
42
Apr 02, 2019
['2019-04-02', '0.300', '0.300', '0.290', '0.295', '0.295', '165,000']
43
0.300
44
0.300
45
0.290
46
0.295
47
0.295
48
165,000
49
Apr 01, 2019
['2019-04-01', '0.285', '0.300', '0.285', '0.300', '0.300', '400,000']
50
0.285
51
0.300
52
0.285
53
0.300
54
0.300
55
400,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8437.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.270', '0.270', '0.270', '0.270', '0.270', '-']
1
0.270
2
0.270
3
0.270
4
0.270
5
0.270
6
-
7
Apr 10, 2019
['2019-04-10', '0.270', '0.270', '0.270', '0.270', '0.270', '16,000']
8
0.270
9
0.270
10
0.270
11
0.270
12
0.270
13
16,000
14
Apr 09, 2019
['2019-04-09', '0.265', '0.270', '0.265', '0.270', '0.270', '24,000']
15
0.265
16
0.270
17
0.265
18
0.270
19
0.270
20
24,000
21
Apr 08, 2019
['2019-04-08', '0.270', '0.275', '0.260', '0.265', '0.265', '288,000']
22
0.270
23
0.275
24
0.260
25
0.265
26
0.265
27
288,000
28
Apr 04, 2019
['2019-04-04', '0.270', '0.275', '0.270', '0.275', '0.275', '384,000']
29
0.270
30
0.275
31
0.270
32
0.275
33
0.275
34
384,000
35
Apr 03, 2019
['2019-04-03', '0.265', '0.270', '0.260', '0.265', '0.265', '696,000']
36
0.265
37
0.270
38
0.260
39
0.265
40
0.265
41
696,000
42
Apr 02, 2019
['2019-04-02', '0.270', '0.270', '0.270', '0.270', '0.270', '80,000']
43
0.270
44
0.270
45
0.270
46
0.270
47
0.270
48
80,000
49
Apr 01, 2019
['2019-04-01', '0.275', '0.275', '0.275', '0.275', '0.275', '40,000']
50
0.275
51
0.275
52
0.275
53
0.275
54
0.275
55
40,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1707.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.475', '0.520', '0.465', '0.475', '0.475', '8,952,000']
1
0.475
2
0.520
3
0.465
4
0.475
5
0.475
6
8,952,000
7
Apr 10, 2019
['2019-04-10', '0.465', '0.495', '0.465', '0.470', '0.470', '2,104,000']
8
0.465
9
0.495
10
0.465
11
0.470
12
0.470
13
2,104,000
14
Apr 09, 2019
['2019-04-09', '0.465', '0.495', '0.460', '0.470', '0.470', '2,712,000']
15
0.465
16
0.495
17
0.460
18
0.470
19
0.470
20
2,712,000
21
Apr 08, 2019
['2019-04-08', '0.495', '0.520', '0.460', '0.460', '0.460', '8,536,000']
22
0.495
23
0.520
24
0.460
25
0.460
26
0.460
27
8,536,000
28
Apr 04, 2019
['2019-04-04', '0.500', '0.530', '0.470', '0.490', '0.490', '5,008,000']
29
0.500
30
0.530
31
0.470
32
0.490
33
0.490
34
5,008,000
35
Apr 03, 2019
['2019-04-03', '0.500', '0.580', '0.485', '0.510', '0.510', '5,216,000']
36
0.500
37
0.580
38
0.485
39
0.510
40
0.510
41
5,216,000
42
Apr 02, 2019
['2019-04-02', '0.520', '0.520', '0.500', '0.500', '0.500', '736,000']
43
0.520
44
0.520
45
0.500
46
0.500
47
0.500
48
736,000
49
Apr 01, 2019
['2019-04-01', '0.530', '0.530', '0.520', '0.520', '0.520', '184,000']
50
0.530
51
0.530
52
0.520
53
0.520
54
0.520
55
184,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6885.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.750', '4.800', '4.700', '4.790', '4.790', '347,000']
1
4.750
2
4.800
3
4.700
4
4.790
5
4.790
6
347,000
7
Apr 10, 2019
['2019-04-10', '4.810', '4.850', '4.780', '4.810', '4.810', '224,000']
8
4.810
9
4.850
10
4.780
11
4.810
12
4.810
13
224,000
14
Apr 09, 2019
['2019-04-09', '4.800', '4.850', '4.780', '4.810', '4.810', '873,000']
15
4.800
16
4.850
17
4.780
18
4.810
19
4.810
20
873,000
21
Apr 08, 2019
['2019-04-08', '4.750', '4.860', '4.750', '4.800', '4.800', '1,579,000']
22
4.750
23
4.860
24
4.750
25
4.800
26
4.800
27
1,579,000
28
Apr 04, 2019
['2019-04-04', '4.730', '4.820', '4.730', '4.740', '4.740', '366,000']
29
4.730
30
4.820
31
4.730
32
4.740
33
4.740
34
366,000
35
Apr 03, 2019
['2019-04-03', '4.780', '4.900', '4.720', '4.800', '4.800', '708,000']
36
4.780
37
4.900
38
4.720
39
4.800
40
4.800
41
708,000
42
Apr 02, 2019
['2019-04-02', '4.730', '4.800', '4.710', '4.780', '4.780', '296,000']
43
4.730
44
4.800
45
4.710
46
4.780
47
4.780
48
296,000
49
Apr 01, 2019
['2019-04-01', '4.740', '4.840', '4.600', '4.740', '4.740', '802,000']
50
4.740
51
4.840
52
4.600
53
4.740
54
4.740
55
802,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8445.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.365', '0.455', '0.360', '0.420', '0.420', '6,940,000']
1
0.365
2
0.455
3
0.360
4
0.420
5
0.420
6
6,940,000
7
Apr 10, 2019
['2019-04-10', '0.370', '0.380', '0.360', '0.370', '0.370', '2,210,000']
8
0.370
9
0.380
10
0.360
11
0.370
12
0.370
13
2,210,000
14
Apr 09, 2019
['2019-04-09', '0.430', '0.430', '0.310', '0.370', '0.370', '9,620,000']
15
0.430
16
0.430
17
0.310
18
0.370
19
0.370
20
9,620,000
21
Apr 08, 2019
['2019-04-08', '0.490', '0.490', '0.420', '0.430', '0.430', '5,620,000']
22
0.490
23
0.490
24
0.420
25
0.430
26
0.430
27
5,620,000
28
Apr 04, 2019
['2019-04-04', '0.500', '0.510', '0.440', '0.490', '0.490', '6,880,000']
29
0.500
30
0.510
31
0.440
32
0.490
33
0.490
34
6,880,000
35
Apr 03, 2019
['2019-04-03', '0.500', '0.530', '0.500', '0.510', '0.510', '2,620,000']
36
0.500
37
0.530
38
0.500
39
0.510
40
0.510
41
2,620,000
42
Apr 02, 2019
['2019-04-02', '0.510', '0.540', '0.510', '0.520', '0.520', '9,130,000']
43
0.510
44
0.540
45
0.510
46
0.520
47
0.520
48
9,130,000
49
Apr 01, 2019
['2019-04-01', '0.560', '0.560', '0.510', '0.510', '0.510', '2,230,000']
50
0.560
51
0.560
52
0.510
53
0.510
54
0.510
55
2,230,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
6060.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '30.600', '30.800', '28.900', '29.600', '29.600', '3,636,897']
1
30.600
2
30.800
3
28.900
4
29.600
5
29.600
6
3,636,897
7
Apr 10, 2019
['2019-04-10', '31.400', '31.400', '30.200', '30.500', '30.500', '4,097,900']
8
31.400
9
31.400
10
30.200
11
30.500
12
30.500
13
4,097,900
14
Apr 09, 2019
['2019-04-09', '29.650', '31.650', '29.650', '31.650', '31.650', '5,576,750']
15
29.650
16
31.650
17
29.650
18
31.650
19
31.650
20
5,576,750
21
Apr 08, 2019
['2019-04-08', '29.800', '30.050', '29.400', '29.650', '29.650', '1,639,066']
22
29.800
23
30.050
24
29.400
25
29.650
26
29.650
27
1,639,066
28
Apr 04, 2019
['2019-04-04', '30.100', '30.100', '29.300', '29.800', '29.800', '2,172,700']
29
30.100
30
30.100
31
29.300
32
29.800
33
29.800
34
2,172,700
35
Apr 03, 2019
['2019-04-03', '27.900', '30.250', '27.900', '30.100', '30.100', '5,293,400']
36
27.900
37
30.250
38
27.900
39
30.100
40
30.100
41
5,293,400
42
Apr 02, 2019
['2019-04-02', '28.100', '28.450', '27.900', '28.100', '28.100', '1,240,700']
43
28.100
44
28.450
45
27.900
46
28.100
47
28.100
48
1,240,700
49
Apr 01, 2019
['2019-04-01', '28.200', '28.500', '27.600', '27.800', '27.800', '1,681,139']
50
28.200
51
28.500
52
27.600
53
27.800
54
27.800
55
1,681,139
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8199.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.240', '0.246', '0.240', '0.246', '0.246', '160,000']
1
0.240
2
0.246
3
0.240
4
0.246
5
0.246
6
160,000
7
Apr 10, 2019
['2019-04-10', '0.234', '0.239', '0.233', '0.239', '0.239', '320,000']
8
0.234
9
0.239
10
0.233
11
0.239
12
0.239
13
320,000
14
Apr 09, 2019
['2019-04-09', '0.228', '0.240', '0.228', '0.233', '0.233', '1,150,000']
15
0.228
16
0.240
17
0.228
18
0.233
19
0.233
20
1,150,000
21
Apr 08, 2019
['2019-04-08', '0.230', '0.230', '0.225', '0.230', '0.230', '1,680,000']
22
0.230
23
0.230
24
0.225
25
0.230
26
0.230
27
1,680,000
28
Apr 04, 2019
['2019-04-04', '0.230', '0.231', '0.230', '0.230', '0.230', '420,000']
29
0.230
30
0.231
31
0.230
32
0.230
33
0.230
34
420,000
35
Apr 03, 2019
['2019-04-03', '0.240', '0.240', '0.229', '0.230', '0.230', '2,650,000']
36
0.240
37
0.240
38
0.229
39
0.230
40
0.230
41
2,650,000
42
Apr 02, 2019
['2019-04-02', '0.240', '0.240', '0.240', '0.240', '0.240', '-']
43
0.240
44
0.240
45
0.240
46
0.240
47
0.240
48
-
49
Apr 01, 2019
['2019-04-01', '0.240', '0.240', '0.229', '0.240', '0.240', '1,340,000']
50
0.240
51
0.240
52
0.229
53
0.240
54
0.240
55
1,340,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1709.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.510', '0.540', '0.495', '0.510', '0.510', '1,657,000']
1
0.510
2
0.540
3
0.495
4
0.510
5
0.510
6
1,657,000
7
Apr 10, 2019
['2019-04-10', '0.510', '0.550', '0.500', '0.510', '0.510', '5,148,000']
8
0.510
9
0.550
10
0.500
11
0.510
12
0.510
13
5,148,000
14
Apr 09, 2019
['2019-04-09', '0.520', '0.520', '0.500', '0.510', '0.510', '503,000']
15
0.520
16
0.520
17
0.500
18
0.510
19
0.510
20
503,000
21
Apr 08, 2019
['2019-04-08', '0.510', '0.520', '0.500', '0.520', '0.520', '28,000']
22
0.510
23
0.520
24
0.500
25
0.520
26
0.520
27
28,000
28
Apr 04, 2019
['2019-04-04', '0.510', '0.520', '0.500', '0.520', '0.520', '1,038,000']
29
0.510
30
0.520
31
0.500
32
0.520
33
0.520
34
1,038,000
35
Apr 03, 2019
['2019-04-03', '0.530', '0.530', '0.510', '0.530', '0.530', '105,000']
36
0.530
37
0.530
38
0.510
39
0.530
40
0.530
41
105,000
42
Apr 02, 2019
['2019-04-02', '0.540', '0.540', '0.510', '0.530', '0.530', '243,000']
43
0.540
44
0.540
45
0.510
46
0.530
47
0.530
48
243,000
49
Apr 01, 2019
['2019-04-01', '0.540', '0.580', '0.520', '0.540', '0.540', '7,716,000']
50
0.540
51
0.580
52
0.520
53
0.540
54
0.540
55
7,716,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1651.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '8.880', '8.880', '8.880', '8.880', '8.880', '-']
1
8.880
2
8.880
3
8.880
4
8.880
5
8.880
6
-
7
Apr 10, 2019
['2019-04-10', '9.000', '9.010', '8.800', '8.900', '8.900', '154,000']
8
9.000
9
9.010
10
8.800
11
8.900
12
8.900
13
154,000
14
Apr 09, 2019
['2019-04-09', '9.000', '9.120', '9.000', '9.040', '9.040', '69,000']
15
9.000
16
9.120
17
9.000
18
9.040
19
9.040
20
69,000
21
Apr 08, 2019
['2019-04-08', '8.910', '9.020', '8.900', '9.010', '9.010', '22,000']
22
8.910
23
9.020
24
8.900
25
9.010
26
9.010
27
22,000
28
Apr 04, 2019
['2019-04-04', '9.020', '9.020', '8.900', '9.020', '9.020', '17,000']
29
9.020
30
9.020
31
8.900
32
9.020
33
9.020
34
17,000
35
Apr 03, 2019
['2019-04-03', '9.110', '9.150', '9.020', '9.020', '9.020', '159,000']
36
9.110
37
9.150
38
9.020
39
9.020
40
9.020
41
159,000
42
Apr 02, 2019
['2019-04-02', '9.160', '9.200', '9.110', '9.110', '9.110', '62,000']
43
9.160
44
9.200
45
9.110
46
9.110
47
9.110
48
62,000
49
Apr 01, 2019
['2019-04-01', '9.030', '9.200', '9.030', '9.160', '9.160', '244,000']
50
9.030
51
9.200
52
9.030
53
9.160
54
9.160
55
244,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8491.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.460', '1.460', '1.390', '1.390', '1.390', '260,000']
1
1.460
2
1.460
3
1.390
4
1.390
5
1.390
6
260,000
7
Apr 10, 2019
['2019-04-10', '1.510', '1.510', '1.450', '1.450', '1.450', '35,000']
8
1.510
9
1.510
10
1.450
11
1.450
12
1.450
13
35,000
14
Apr 09, 2019
['2019-04-09', '1.450', '1.490', '1.450', '1.490', '1.490', '340,000']
15
1.450
16
1.490
17
1.450
18
1.490
19
1.490
20
340,000
21
Apr 08, 2019
['2019-04-08', '1.460', '1.470', '1.450', '1.450', '1.450', '415,000']
22
1.460
23
1.470
24
1.450
25
1.450
26
1.450
27
415,000
28
Apr 04, 2019
['2019-04-04', '1.490', '1.490', '1.390', '1.460', '1.460', '10,880,000']
29
1.490
30
1.490
31
1.390
32
1.460
33
1.460
34
10,880,000
35
Apr 03, 2019
['2019-04-03', '1.490', '1.490', '1.490', '1.490', '1.490', '35,000']
36
1.490
37
1.490
38
1.490
39
1.490
40
1.490
41
35,000
42
Apr 02, 2019
['2019-04-02', '1.510', '1.510', '1.500', '1.510', '1.510', '20,000']
43
1.510
44
1.510
45
1.500
46
1.510
47
1.510
48
20,000
49
Apr 01, 2019
['2019-04-01', '1.500', '1.510', '1.460', '1.490', '1.490', '625,000']
50
1.500
51
1.510
52
1.460
53
1.490
54
1.490
55
625,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3830.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.186', '0.190', '0.185', '0.190', '0.190', '335,000']
1
0.186
2
0.190
3
0.185
4
0.190
5
0.190
6
335,000
7
Apr 10, 2019
['2019-04-10', '0.186', '0.186', '0.186', '0.186', '0.186', '5,000']
8
0.186
9
0.186
10
0.186
11
0.186
12
0.186
13
5,000
14
Apr 09, 2019
['2019-04-09', '0.190', '0.192', '0.185', '0.186', '0.186', '215,000']
15
0.190
16
0.192
17
0.185
18
0.186
19
0.186
20
215,000
21
Apr 08, 2019
['2019-04-08', '0.190', '0.190', '0.190', '0.190', '0.190', '-']
22
0.190
23
0.190
24
0.190
25
0.190
26
0.190
27
-
28
Apr 04, 2019
['2019-04-04', '0.197', '0.197', '0.197', '0.197', '0.197', '-']
29
0.197
30
0.197
31
0.197
32
0.197
33
0.197
34
-
35
Apr 03, 2019
['2019-04-03', '0.197', '0.197', '0.197', '0.197', '0.197', '5,000']
36
0.197
37
0.197
38
0.197
39
0.197
40
0.197
41
5,000
42
Apr 02, 2019
['2019-04-02', '0.196', '0.196', '0.196', '0.197', '0.197', '90,000']
43
0.196
44
0.196
45
0.196
46
0.197
47
0.197
48
90,000
49
Apr 01, 2019
['2019-04-01', '0.193', '0.195', '0.193', '0.195', '0.195', '20,000']
50
0.193
51
0.195
52
0.193
53
0.195
54
0.195
55
20,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1696.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '5.090', '5.180', '5.060', '5.090', '5.090', '189,200']
1
5.090
2
5.180
3
5.060
4
5.090
5
5.090
6
189,200
7
Apr 10, 2019
['2019-04-10', '5.080', '5.170', '5.080', '5.090', '5.090', '230,400']
8
5.080
9
5.170
10
5.080
11
5.090
12
5.090
13
230,400
14
Apr 09, 2019
['2019-04-09', '4.980', '5.130', '4.980', '5.090', '5.090', '318,800']
15
4.980
16
5.130
17
4.980
18
5.090
19
5.090
20
318,800
21
Apr 08, 2019
['2019-04-08', '5.000', '5.050', '4.950', '4.980', '4.980', '522,171']
22
5.000
23
5.050
24
4.950
25
4.980
26
4.980
27
522,171
28
Apr 04, 2019
['2019-04-04', '4.950', '4.990', '4.880', '4.920', '4.920', '473,200']
29
4.950
30
4.990
31
4.880
32
4.920
33
4.920
34
473,200
35
Apr 03, 2019
['2019-04-03', '4.900', '4.980', '4.850', '4.980', '4.980', '296,400']
36
4.900
37
4.980
38
4.850
39
4.980
40
4.980
41
296,400
42
Apr 02, 2019
['2019-04-02', '4.800', '4.970', '4.800', '4.900', '4.900', '267,220']
43
4.800
44
4.970
45
4.800
46
4.900
47
4.900
48
267,220
49
Apr 01, 2019
['2019-04-01', '4.790', '4.920', '4.790', '4.840', '4.840', '332,908']
50
4.790
51
4.920
52
4.790
53
4.840
54
4.840
55
332,908
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3728.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.230', '0.230', '0.230', '0.230', '0.230', '-']
1
0.230
2
0.230
3
0.230
4
0.230
5
0.230
6
-
7
Apr 10, 2019
['2019-04-10', '0.230', '0.230', '0.230', '0.230', '0.230', '-']
8
0.230
9
0.230
10
0.230
11
0.230
12
0.230
13
-
14
Apr 09, 2019
['2019-04-09', '0.230', '0.230', '0.230', '0.230', '0.230', '40,000']
15
0.230
16
0.230
17
0.230
18
0.230
19
0.230
20
40,000
21
Apr 08, 2019
['2019-04-08', '0.235', '0.235', '0.235', '0.215', '0.215', '20,000']
22
0.235
23
0.235
24
0.235
25
0.215
26
0.215
27
20,000
28
Apr 04, 2019
['2019-04-04', '0.196', '0.215', '0.195', '0.215', '0.215', '80,000']
29
0.196
30
0.215
31
0.195
32
0.215
33
0.215
34
80,000
35
Apr 03, 2019
['2019-04-03', '0.209', '0.216', '0.201', '0.215', '0.215', '300,000']
36
0.209
37
0.216
38
0.201
39
0.215
40
0.215
41
300,000
42
Apr 02, 2019
['2019-04-02', '0.208', '0.220', '0.208', '0.214', '0.214', '220,000']
43
0.208
44
0.220
45
0.208
46
0.214
47
0.214
48
220,000
49
Apr 01, 2019
['2019-04-01', '0.225', '0.225', '0.220', '0.220', '0.220', '300,000']
50
0.225
51
0.225
52
0.220
53
0.220
54
0.220
55
300,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8383.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.200', '0.200', '0.200', '0.200', '0.200', '-']
1
0.200
2
0.200
3
0.200
4
0.200
5
0.200
6
-
7
Apr 10, 2019
['2019-04-10', '0.200', '0.200', '0.200', '0.200', '0.200', '448,000']
8
0.200
9
0.200
10
0.200
11
0.200
12
0.200
13
448,000
14
Apr 09, 2019
['2019-04-09', '0.209', '0.209', '0.208', '0.208', '0.208', '128,000']
15
0.209
16
0.209
17
0.208
18
0.208
19
0.208
20
128,000
21
Apr 08, 2019
['2019-04-08', '0.211', '0.211', '0.208', '0.208', '0.208', '568,000']
22
0.211
23
0.211
24
0.208
25
0.208
26
0.208
27
568,000
28
Apr 04, 2019
['2019-04-04', '0.215', '0.215', '0.205', '0.208', '0.208', '648,000']
29
0.215
30
0.215
31
0.205
32
0.208
33
0.208
34
648,000
35
Apr 03, 2019
['2019-04-03', '0.220', '0.250', '0.215', '0.225', '0.225', '4,888,000']
36
0.220
37
0.250
38
0.215
39
0.225
40
0.225
41
4,888,000
42
Apr 02, 2019
['2019-04-02', '0.191', '0.223', '0.191', '0.223', '0.223', '400,000']
43
0.191
44
0.223
45
0.191
46
0.223
47
0.223
48
400,000
49
Apr 01, 2019
['2019-04-01', '0.230', '0.235', '0.230', '0.234', '0.234', '560,000']
50
0.230
51
0.235
52
0.230
53
0.234
54
0.234
55
560,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1552.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.320', '0.320', '0.320', '0.320', '0.320', '-']
1
0.320
2
0.320
3
0.320
4
0.320
5
0.320
6
-
7
Apr 10, 2019
['2019-04-10', '0.315', '0.325', '0.315', '0.320', '0.320', '790,000']
8
0.315
9
0.325
10
0.315
11
0.320
12
0.320
13
790,000
14
Apr 09, 2019
['2019-04-09', '0.330', '0.335', '0.320', '0.320', '0.320', '330,000']
15
0.330
16
0.335
17
0.320
18
0.320
19
0.320
20
330,000
21
Apr 08, 2019
['2019-04-08', '0.335', '0.335', '0.335', '0.335', '0.335', '-']
22
0.335
23
0.335
24
0.335
25
0.335
26
0.335
27
-
28
Apr 04, 2019
['2019-04-04', '0.335', '0.335', '0.335', '0.335', '0.335', '-']
29
0.335
30
0.335
31
0.335
32
0.335
33
0.335
34
-
35
Apr 03, 2019
['2019-04-03', '0.330', '0.335', '0.330', '0.335', '0.335', '205,000']
36
0.330
37
0.335
38
0.330
39
0.335
40
0.335
41
205,000
42
Apr 02, 2019
['2019-04-02', '0.335', '0.335', '0.330', '0.335', '0.335', '720,000']
43
0.335
44
0.335
45
0.330
46
0.335
47
0.335
48
720,000
49
Apr 01, 2019
['2019-04-01', '0.340', '0.340', '0.325', '0.335', '0.335', '655,000']
50
0.340
51
0.340
52
0.325
53
0.335
54
0.335
55
655,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2863.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.520', '0.520', '0.520', '0.520', '0.520', '159,000']
1
0.520
2
0.520
3
0.520
4
0.520
5
0.520
6
159,000
7
Apr 10, 2019
['2019-04-10', '0.520', '0.520', '0.485', '0.520', '0.520', '300,000']
8
0.520
9
0.520
10
0.485
11
0.520
12
0.520
13
300,000
14
Apr 09, 2019
['2019-04-09', '0.520', '0.520', '0.520', '0.520', '0.520', '-']
15
0.520
16
0.520
17
0.520
18
0.520
19
0.520
20
-
21
Apr 08, 2019
['2019-04-08', '0.520', '0.520', '0.520', '0.520', '0.520', '-']
22
0.520
23
0.520
24
0.520
25
0.520
26
0.520
27
-
28
Apr 04, 2019
['2019-04-04', '0.520', '0.520', '0.520', '0.520', '0.520', '-']
29
0.520
30
0.520
31
0.520
32
0.520
33
0.520
34
-
35
Apr 03, 2019
['2019-04-03', '0.520', '0.520', '0.520', '0.520', '0.520', '63,000']
36
0.520
37
0.520
38
0.520
39
0.520
40
0.520
41
63,000
42
Apr 02, 2019
['2019-04-02', '0.520', '0.520', '0.520', '0.520', '0.520', '483,000']
43
0.520
44
0.520
45
0.520
46
0.520
47
0.520
48
483,000
49
Apr 01, 2019
['2019-04-01', '0.500', '0.510', '0.500', '0.510', '0.510', '414,000']
50
0.500
51
0.510
52
0.500
53
0.510
54
0.510
55
414,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
1693.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.187', '0.207', '0.187', '0.200', '0.200', '120,000']
1
0.187
2
0.207
3
0.187
4
0.200
5
0.200
6
120,000
7
Apr 10, 2019
['2019-04-10', '0.180', '0.189', '0.180', '0.187', '0.187', '136,000']
8
0.180
9
0.189
10
0.180
11
0.187
12
0.187
13
136,000
14
Apr 09, 2019
['2019-04-09', '0.185', '0.188', '0.185', '0.188', '0.188', '96,000']
15
0.185
16
0.188
17
0.185
18
0.188
19
0.188
20
96,000
21
Apr 08, 2019
['2019-04-08', '0.198', '0.198', '0.198', '0.198', '0.198', '-']
22
0.198
23
0.198
24
0.198
25
0.198
26
0.198
27
-
28
Apr 04, 2019
['2019-04-04', '0.197', '0.198', '0.194', '0.198', '0.198', '16,000']
29
0.197
30
0.198
31
0.194
32
0.198
33
0.198
34
16,000
35
Apr 03, 2019
['2019-04-03', '0.186', '0.198', '0.185', '0.189', '0.189', '768,000']
36
0.186
37
0.198
38
0.185
39
0.189
40
0.189
41
768,000
42
Apr 02, 2019
['2019-04-02', '0.199', '0.199', '0.199', '0.199', '0.199', '-']
43
0.199
44
0.199
45
0.199
46
0.199
47
0.199
48
-
49
Apr 01, 2019
['2019-04-01', '0.185', '0.199', '0.173', '0.199', '0.199', '168,000']
50
0.185
51
0.199
52
0.173
53
0.199
54
0.199
55
168,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8142.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.265', '0.265', '0.265', '0.265', '0.265', '170,000']
1
0.265
2
0.265
3
0.265
4
0.265
5
0.265
6
170,000
7
Apr 10, 2019
['2019-04-10', '0.265', '0.265', '0.265', '0.265', '0.265', '30,000']
8
0.265
9
0.265
10
0.265
11
0.265
12
0.265
13
30,000
14
Apr 09, 2019
['2019-04-09', '0.265', '0.265', '0.265', '0.265', '0.265', '-']
15
0.265
16
0.265
17
0.265
18
0.265
19
0.265
20
-
21
Apr 08, 2019
['2019-04-08', '0.265', '0.265', '0.265', '0.265', '0.265', '-']
22
0.265
23
0.265
24
0.265
25
0.265
26
0.265
27
-
28
Apr 04, 2019
['2019-04-04', '0.265', '0.265', '0.265', '0.265', '0.265', '-']
29
0.265
30
0.265
31
0.265
32
0.265
33
0.265
34
-
35
Apr 03, 2019
['2019-04-03', '0.260', '0.260', '0.260', '0.260', '0.260', '110,000']
36
0.260
37
0.260
38
0.260
39
0.260
40
0.260
41
110,000
42
Apr 02, 2019
['2019-04-02', '0.255', '0.260', '0.255', '0.260', '0.260', '30,000']
43
0.255
44
0.260
45
0.255
46
0.260
47
0.260
48
30,000
49
Apr 01, 2019
['2019-04-01', '0.265', '0.265', '0.265', '0.265', '0.265', '-']
50
0.265
51
0.265
52
0.265
53
0.265
54
0.265
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8152.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.099', '0.099', '0.099', '0.099', '0.099', '-']
1
0.099
2
0.099
3
0.099
4
0.099
5
0.099
6
-
7
Apr 10, 2019
['2019-04-10', '0.097', '0.108', '0.097', '0.105', '0.105', '340,000']
8
0.097
9
0.108
10
0.097
11
0.105
12
0.105
13
340,000
14
Apr 09, 2019
['2019-04-09', '0.097', '0.104', '0.097', '0.101', '0.101', '490,000']
15
0.097
16
0.104
17
0.097
18
0.101
19
0.101
20
490,000
21
Apr 08, 2019
['2019-04-08', '0.112', '0.112', '0.100', '0.100', '0.100', '310,000']
22
0.112
23
0.112
24
0.100
25
0.100
26
0.100
27
310,000
28
Apr 04, 2019
['2019-04-04', '0.106', '0.108', '0.105', '0.104', '0.104', '260,000']
29
0.106
30
0.108
31
0.105
32
0.104
33
0.104
34
260,000
35
Apr 03, 2019
['2019-04-03', '0.091', '0.096', '0.091', '0.096', '0.096', '330,000']
36
0.091
37
0.096
38
0.091
39
0.096
40
0.096
41
330,000
42
Apr 02, 2019
['2019-04-02', '0.095', '0.095', '0.095', '0.096', '0.096', '400,000']
43
0.095
44
0.095
45
0.095
46
0.096
47
0.096
48
400,000
49
Apr 01, 2019
['2019-04-01', '0.096', '0.096', '0.096', '0.096', '0.096', '-']
50
0.096
51
0.096
52
0.096
53
0.096
54
0.096
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8471.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.650', '0.670', '0.650', '0.680', '0.680', '240,000']
1
0.650
2
0.670
3
0.650
4
0.680
5
0.680
6
240,000
7
Apr 10, 2019
['2019-04-10', '0.790', '0.760', '0.630', '0.660', '0.660', '580,000']
8
0.790
9
0.760
10
0.630
11
0.660
12
0.660
13
580,000
14
Apr 09, 2019
['2019-04-09', '0.770', '0.770', '0.690', '0.720', '0.720', '510,000']
15
0.770
16
0.770
17
0.690
18
0.720
19
0.720
20
510,000
21
Apr 08, 2019
['2019-04-08', '0.780', '0.780', '0.750', '0.770', '0.770', '180,000']
22
0.780
23
0.780
24
0.750
25
0.770
26
0.770
27
180,000
28
Apr 04, 2019
['2019-04-04', '0.740', '0.810', '0.740', '0.770', '0.770', '630,000']
29
0.740
30
0.810
31
0.740
32
0.770
33
0.770
34
630,000
35
Apr 03, 2019
['2019-04-03', '0.760', '0.820', '0.700', '0.780', '0.780', '940,000']
36
0.760
37
0.820
38
0.700
39
0.780
40
0.780
41
940,000
42
Apr 02, 2019
['2019-04-02', '0.780', '0.950', '0.740', '0.750', '0.750', '3,210,000']
43
0.780
44
0.950
45
0.740
46
0.750
47
0.750
48
3,210,000
49
Apr 01, 2019
['2019-04-01', '0.570', '0.880', '0.570', '0.770', '0.770', '10,630,000']
50
0.570
51
0.880
52
0.570
53
0.770
54
0.770
55
10,630,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8073.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.610', '0.630', '0.610', '0.630', '0.630', '86,000']
1
0.610
2
0.630
3
0.610
4
0.630
5
0.630
6
86,000
7
Apr 10, 2019
['2019-04-10', '0.630', '0.640', '0.630', '0.610', '0.610', '32,000']
8
0.630
9
0.640
10
0.630
11
0.610
12
0.610
13
32,000
14
Apr 09, 2019
['2019-04-09', '0.600', '0.630', '0.600', '0.600', '0.600', '364,000']
15
0.600
16
0.630
17
0.600
18
0.600
19
0.600
20
364,000
21
Apr 08, 2019
['2019-04-08', '0.600', '0.610', '0.590', '0.600', '0.600', '128,435']
22
0.600
23
0.610
24
0.590
25
0.600
26
0.600
27
128,435
28
Apr 04, 2019
['2019-04-04', '0.620', '0.640', '0.600', '0.630', '0.630', '356,000']
29
0.620
30
0.640
31
0.600
32
0.630
33
0.630
34
356,000
35
Apr 03, 2019
['2019-04-03', '0.590', '0.630', '0.580', '0.620', '0.620', '488,000']
36
0.590
37
0.630
38
0.580
39
0.620
40
0.620
41
488,000
42
Apr 02, 2019
['2019-04-02', '0.600', '0.620', '0.600', '0.620', '0.620', '440,020']
43
0.600
44
0.620
45
0.600
46
0.620
47
0.620
48
440,020
49
Apr 01, 2019
['2019-04-01', '0.540', '0.590', '0.540', '0.580', '0.580', '1,148,000']
50
0.540
51
0.590
52
0.540
53
0.580
54
0.580
55
1,148,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
2203.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.810', '0.860', '0.800', '0.860', '0.860', '520,000']
1
0.810
2
0.860
3
0.800
4
0.860
5
0.860
6
520,000
7
Apr 10, 2019
['2019-04-10', '0.830', '0.860', '0.830', '0.840', '0.840', '230,000']
8
0.830
9
0.860
10
0.830
11
0.840
12
0.840
13
230,000
14
Apr 09, 2019
['2019-04-09', '0.890', '0.890', '0.830', '0.870', '0.870', '760,000']
15
0.890
16
0.890
17
0.830
18
0.870
19
0.870
20
760,000
21
Apr 08, 2019
['2019-04-08', '0.890', '0.900', '0.870', '0.870', '0.870', '950,000']
22
0.890
23
0.900
24
0.870
25
0.870
26
0.870
27
950,000
28
Apr 04, 2019
['2019-04-04', '0.930', '0.940', '0.900', '0.900', '0.900', '2,500,000']
29
0.930
30
0.940
31
0.900
32
0.900
33
0.900
34
2,500,000
35
Apr 03, 2019
['2019-04-03', '0.940', '0.960', '0.940', '0.950', '0.950', '770,000']
36
0.940
37
0.960
38
0.940
39
0.950
40
0.950
41
770,000
42
Apr 02, 2019
['2019-04-02', '0.900', '0.990', '0.900', '0.950', '0.950', '1,780,000']
43
0.900
44
0.990
45
0.900
46
0.950
47
0.950
48
1,780,000
49
Apr 01, 2019
['2019-04-01', '0.920', '0.930', '0.900', '0.900', '0.900', '90,000']
50
0.920
51
0.930
52
0.900
53
0.900
54
0.900
55
90,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
3848.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '7.600', '7.990', '7.250', '7.300', '7.300', '76,000']
1
7.600
2
7.990
3
7.250
4
7.300
5
7.300
6
76,000
7
Apr 10, 2019
['2019-04-10', '7.800', '7.820', '7.540', '7.550', '7.550', '69,000']
8
7.800
9
7.820
10
7.540
11
7.550
12
7.550
13
69,000
14
Apr 09, 2019
['2019-04-09', '7.850', '7.990', '7.700', '7.710', '7.710', '58,000']
15
7.850
16
7.990
17
7.700
18
7.710
19
7.710
20
58,000
21
Apr 08, 2019
['2019-04-08', '8.170', '8.180', '7.820', '7.850', '7.850', '63,000']
22
8.170
23
8.180
24
7.820
25
7.850
26
7.850
27
63,000
28
Apr 04, 2019
['2019-04-04', '8.020', '8.180', '7.800', '8.090', '8.090', '63,000']
29
8.020
30
8.180
31
7.800
32
8.090
33
8.090
34
63,000
35
Apr 03, 2019
['2019-04-03', '8.090', '8.090', '7.900', '7.900', '7.900', '68,000']
36
8.090
37
8.090
38
7.900
39
7.900
40
7.900
41
68,000
42
Apr 02, 2019
['2019-04-02', '8.110', '8.120', '8.000', '8.060', '8.060', '65,000']
43
8.110
44
8.120
45
8.000
46
8.060
47
8.060
48
65,000
49
Apr 01, 2019
['2019-04-01', '8.180', '8.180', '8.100', '8.120', '8.120', '64,000']
50
8.180
51
8.180
52
8.100
53
8.120
54
8.120
55
64,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8465.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.390', '1.390', '1.030', '1.290', '1.290', '56,000']
1
1.390
2
1.390
3
1.030
4
1.290
5
1.290
6
56,000
7
Apr 10, 2019
['2019-04-10', '1.300', '1.300', '1.300', '1.300', '1.300', '-']
8
1.300
9
1.300
10
1.300
11
1.300
12
1.300
13
-
14
Apr 09, 2019
['2019-04-09', '1.300', '1.320', '1.300', '1.300', '1.300', '22,000']
15
1.300
16
1.320
17
1.300
18
1.300
19
1.300
20
22,000
21
Apr 08, 2019
['2019-04-08', '1.390', '1.390', '1.320', '1.320', '1.320', '20,000']
22
1.390
23
1.390
24
1.320
25
1.320
26
1.320
27
20,000
28
Apr 04, 2019
['2019-04-04', '1.380', '1.380', '1.380', '1.380', '1.380', '-']
29
1.380
30
1.380
31
1.380
32
1.380
33
1.380
34
-
35
Apr 03, 2019
['2019-04-03', '1.360', '1.400', '1.360', '1.400', '1.400', '36,000']
36
1.360
37
1.400
38
1.360
39
1.400
40
1.400
41
36,000
42
Apr 02, 2019
['2019-04-02', '1.350', '1.410', '1.350', '1.350', '1.350', '24,000']
43
1.350
44
1.410
45
1.350
46
1.350
47
1.350
48
24,000
49
Apr 01, 2019
['2019-04-01', '1.430', '1.440', '1.320', '1.360', '1.360', '228,000']
50
1.430
51
1.440
52
1.320
53
1.360
54
1.360
55
228,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
8427.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.295', '0.310', '0.290', '0.290', '0.290', '360,000']
1
0.295
2
0.310
3
0.290
4
0.290
5
0.290
6
360,000
7
Apr 10, 2019
['2019-04-10', '0.305', '0.305', '0.305', '0.305', '0.305', '-']
8
0.305
9
0.305
10
0.305
11
0.305
12
0.305
13
-
14
Apr 09, 2019
['2019-04-09', '0.310', '0.310', '0.310', '0.310', '0.310', '-']
15
0.310
16
0.310
17
0.310
18
0.310
19
0.310
20
-
21
Apr 08, 2019
['2019-04-08', '0.310', '0.310', '0.310', '0.310', '0.310', '-']
22
0.310
23
0.310
24
0.310
25
0.310
26
0.310
27
-
28
Apr 04, 2019
['2019-04-04', '0.310', '0.310', '0.310', '0.310', '0.310', '-']
29
0.310
30
0.310
31
0.310
32
0.310
33
0.310
34
-
35
Apr 03, 2019
['2019-04-03', '0.310', '0.310', '0.310', '0.310', '0.310', '-']
36
0.310
37
0.310
38
0.310
39
0.310
40
0.310
41
-
42
Apr 02, 2019
['2019-04-02', '0.310', '0.310', '0.310', '0.310', '0.310', '-']
43
0.310
44
0.310
45
0.310
46
0.310
47
0.310
48
-
49
Apr 01, 2019
['2019-04-01', '0.295', '0.310', '0.290', '0.310', '0.310', '224,000']
50
0.295
51
0.310
52
0.290
53
0.310
54
0.310
55
224,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
No record
No record
No record
No record
0
0735.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '5.320', '5.380', '5.320', '5.330', '5.330', '3,265,000']
1
5.320
2
5.380
3
5.320
4
5.330
5
5.330
6
3,265,000
7
Apr 10, 2019
['2019-04-10', '5.340', '5.360', '5.320', '5.340', '5.340', '3,376,000']
8
5.340
9
5.360
10
5.320
11
5.340
12
5.340
13
3,376,000
14
Apr 09, 2019
['2019-04-09', '5.310', '5.350', '5.300', '5.330', '5.330', '7,119,000']
15
5.310
16
5.350
17
5.300
18
5.330
19
5.330
20
7,119,000
21
Apr 08, 2019
['2019-04-08', '5.280', '5.310', '5.280', '5.300', '5.300', '8,765,500']
22
5.280
23
5.310
24
5.280
25
5.300
26
5.300
27
8,765,500
28
Apr 04, 2019
['2019-04-04', '5.270', '5.320', '5.260', '5.280', '5.280', '6,432,500']
29
5.270
30
5.320
31
5.260
32
5.280
33
5.280
34
6,432,500
35
Apr 03, 2019
['2019-04-03', '5.250', '5.300', '5.250', '5.260', '5.260', '3,681,460']
36
5.250
37
5.300
38
5.250
39
5.260
40
5.260
41
3,681,460
42
Apr 02, 2019
['2019-04-02', '5.240', '5.290', '5.230', '5.250', '5.250', '6,233,500']
43
5.240
44
5.290
45
5.230
46
5.250
47
5.250
48
6,233,500
49
Apr 01, 2019
['2019-04-01', '5.230', '5.260', '5.200', '5.230', '5.230', '22,323,500']
50
5.230
51
5.260
52
5.200
53
5.230
54
5.230
55
22,323,500
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
No record
0
0001.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '84.650', '85.400', '83.600', '84.300', '84.300', '5,766,180']
1
84.650
2
85.400
3
83.600
4
84.300
5
84.300
6
5,766,180
7
Apr 10, 2019
['2019-04-10', '85.100', '85.800', '84.500', '85.350', '85.350', '5,840,791']
8
85.100
9
85.800
10
84.500
11
85.350
12
85.350
13
5,840,791
14
Apr 09, 2019
['2019-04-09', '85.600', '86.450', '85.500', '86.200', '86.200', '5,913,309']
15
85.600
16
86.450
17
85.500
18
86.200
19
86.200
20
5,913,309
21
Apr 08, 2019
['2019-04-08', '85.900', '86.300', '85.600', '86.000', '86.000', '6,741,262']
22
85.900
23
86.300
24
85.600
25
86.000
26
86.000
27
6,741,262
28
Apr 04, 2019
['2019-04-04', '85.850', '85.900', '85.050', '85.600', '85.600', '5,064,829']
29
85.850
30
85.900
31
85.050
32
85.600
33
85.600
34
5,064,829
35
Apr 03, 2019
['2019-04-03', '85.000', '86.300', '84.850', '85.950', '85.950', '7,568,400']
36
85.000
37
86.300
38
84.850
39
85.950
40
85.950
41
7,568,400
42
Apr 02, 2019
['2019-04-02', '84.050', '85.300', '83.550', '85.000', '85.000', '6,339,089']
43
84.050
44
85.300
45
83.550
46
85.000
47
85.000
48
6,339,089
49
Apr 01, 2019
['2019-04-01', '83.050', '84.150', '82.600', '84.100', '84.100', '7,299,974']
50
83.050
51
84.150
52
82.600
53
84.100
54
84.100
55
7,299,974
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0003.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '18.960', '19.100', '18.800', '18.800', '18.800', '14,637,984']
1
18.960
2
19.100
3
18.800
4
18.800
5
18.800
6
14,637,984
7
Apr 10, 2019
['2019-04-10', '19.080', '19.080', '18.840', '18.880', '18.880', '16,088,980']
8
19.080
9
19.080
10
18.840
11
18.880
12
18.880
13
16,088,980
14
Apr 09, 2019
['2019-04-09', '19.100', '19.120', '18.960', '18.980', '18.980', '13,607,371']
15
19.100
16
19.120
17
18.960
18
18.980
19
18.980
20
13,607,371
21
Apr 08, 2019
['2019-04-08', '19.240', '19.280', '18.960', '18.980', '18.980', '23,777,542']
22
19.240
23
19.280
24
18.960
25
18.980
26
18.980
27
23,777,542
28
Apr 04, 2019
['2019-04-04', '19.200', '19.280', '19.000', '19.100', '19.100', '16,449,019']
29
19.200
30
19.280
31
19.000
32
19.100
33
19.100
34
16,449,019
35
Apr 03, 2019
['2019-04-03', '19.100', '19.280', '19.040', '19.260', '19.260', '15,143,579']
36
19.100
37
19.280
38
19.040
39
19.260
40
19.260
41
15,143,579
42
Apr 02, 2019
['2019-04-02', '19.100', '19.300', '18.900', '19.140', '19.140', '13,533,117']
43
19.100
44
19.300
45
18.900
46
19.140
47
19.140
48
13,533,117
49
Apr 01, 2019
['2019-04-01', '18.820', '19.140', '18.820', '19.120', '19.120', '23,114,343']
50
18.820
51
19.140
52
18.820
53
19.120
54
19.120
55
23,114,343
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0004.HKneeds update
[43, 52]
[43, 52]
61
52
length in loop61
52poped
43
length in loop59
43poped
[]
[]
0
Apr 11, 2019
['2019-04-11', '23.650', '23.750', '23.350', '23.500', '23.500', '4,914,494']
1
23.650
2
23.750
3
23.350
4
23.500
5
23.500
6
4,914,494
7
Apr 10, 2019
['2019-04-10', '23.550', '23.650', '23.100', '23.450', '23.450', '5,624,570']
8
23.550
9
23.650
10
23.100
11
23.450
12
23.450
13
5,624,570
14
Apr 09, 2019
['2019-04-09', '23.550', '23.550', '23.050', '23.450', '23.450', '4,710,362']
15
23.550
16
23.550
17
23.050
18
23.450
19
23.450
20
4,710,362
21
Apr 08, 2019
['2019-04-08', '23.800', '23.950', '23.200', '23.400', '23.400', '4,460,994']
22
23.800
23
23.950
24
23.200
25
23.400
26
23.400
27
4,460,994
28
Apr 04, 2019
['2019-04-04', '23.900', '24.000', '23.750', '24.000', '24.000', '2,489,138']
29
23.900
30
24.000
31
23.750
32
24.000
33
24.000
34
2,489,138
35
Apr 03, 2019
['2019-04-03', '23.550', '24.000', '23.550', '24.000', '24.000', '3,572,896']
36
23.550
37
24.000
38
23.550
39
24.000
40
24.000
41
3,572,896
42
Apr 02, 2019
['2019-04-02', '23.900', '23.950', '23.450', '23.850', '23.450', '5,195,175']
43
23.900
44
23.950
45
23.450
46
23.850
47
23.450
48
5,195,175
49
Apr 01, 2019
['2019-04-01', '23.850', '24.250', '23.600', '24.150', '23.352', '5,104,939']
50
23.850
51
24.250
52
23.600
53
24.150
54
23.352
55
5,104,939
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0005.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '66.900', '66.950', '66.300', '66.600', '66.600', '15,217,993']
1
66.900
2
66.950
3
66.300
4
66.600
5
66.600
6
15,217,993
7
Apr 10, 2019
['2019-04-10', '66.800', '66.950', '66.500', '66.950', '66.950', '13,952,939']
8
66.800
9
66.950
10
66.500
11
66.950
12
66.950
13
13,952,939
14
Apr 09, 2019
['2019-04-09', '67.000', '67.000', '66.600', '67.000', '67.000', '19,765,001']
15
67.000
16
67.000
17
66.600
18
67.000
19
67.000
20
19,765,001
21
Apr 08, 2019
['2019-04-08', '66.550', '67.000', '66.450', '66.700', '66.700', '17,767,223']
22
66.550
23
67.000
24
66.450
25
66.700
26
66.700
27
17,767,223
28
Apr 04, 2019
['2019-04-04', '66.700', '66.950', '66.200', '66.500', '66.500', '28,689,527']
29
66.700
30
66.950
31
66.200
32
66.500
33
66.500
34
28,689,527
35
Apr 03, 2019
['2019-04-03', '66.150', '66.600', '66.000', '66.400', '66.400', '43,821,179']
36
66.150
37
66.600
38
66.000
39
66.400
40
66.400
41
43,821,179
42
Apr 02, 2019
['2019-04-02', '65.050', '65.500', '65.050', '65.450', '65.450', '29,102,893']
43
65.050
44
65.500
45
65.050
46
65.450
47
65.450
48
29,102,893
49
Apr 01, 2019
['2019-04-01', '64.150', '64.800', '64.100', '64.750', '64.750', '20,610,944']
50
64.150
51
64.800
52
64.100
53
64.750
54
64.750
55
20,610,944
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0006.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '54.400', '54.400', '54.050', '54.200', '54.200', '3,290,762']
1
54.400
2
54.400
3
54.050
4
54.200
5
54.200
6
3,290,762
7
Apr 10, 2019
['2019-04-10', '54.050', '54.400', '54.050', '54.200', '54.200', '2,974,581']
8
54.050
9
54.400
10
54.050
11
54.200
12
54.200
13
2,974,581
14
Apr 09, 2019
['2019-04-09', '54.750', '54.750', '54.000', '54.300', '54.300', '3,588,507']
15
54.750
16
54.750
17
54.000
18
54.300
19
54.300
20
3,588,507
21
Apr 08, 2019
['2019-04-08', '54.600', '54.650', '54.150', '54.400', '54.400', '4,879,173']
22
54.600
23
54.650
24
54.150
25
54.400
26
54.400
27
4,879,173
28
Apr 04, 2019
['2019-04-04', '54.500', '54.650', '54.300', '54.400', '54.400', '4,082,318']
29
54.500
30
54.650
31
54.300
32
54.400
33
54.400
34
4,082,318
35
Apr 03, 2019
['2019-04-03', '54.000', '54.500', '54.000', '54.500', '54.500', '2,644,169']
36
54.000
37
54.500
38
54.000
39
54.500
40
54.500
41
2,644,169
42
Apr 02, 2019
['2019-04-02', '54.600', '54.650', '54.100', '54.300', '54.300', '6,104,563']
43
54.600
44
54.650
45
54.100
46
54.300
47
54.300
48
6,104,563
49
Apr 01, 2019
['2019-04-01', '54.750', '54.800', '54.250', '54.600', '54.600', '5,502,394']
50
54.750
51
54.800
52
54.250
53
54.600
54
54.600
55
5,502,394
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0007.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.930', '0.940', '0.900', '0.910', '0.910', '9,314,000']
1
0.930
2
0.940
3
0.900
4
0.910
5
0.910
6
9,314,000
7
Apr 10, 2019
['2019-04-10', '0.910', '0.950', '0.900', '0.920', '0.920', '17,518,000']
8
0.910
9
0.950
10
0.900
11
0.920
12
0.920
13
17,518,000
14
Apr 09, 2019
['2019-04-09', '0.930', '0.950', '0.890', '0.910', '0.910', '26,400,000']
15
0.930
16
0.950
17
0.890
18
0.910
19
0.910
20
26,400,000
21
Apr 08, 2019
['2019-04-08', '0.910', '0.980', '0.910', '0.940', '0.940', '49,476,000']
22
0.910
23
0.980
24
0.910
25
0.940
26
0.940
27
49,476,000
28
Apr 04, 2019
['2019-04-04', '0.910', '0.910', '0.910', '0.910', '0.910', '-']
29
0.910
30
0.910
31
0.910
32
0.910
33
0.910
34
-
35
Apr 03, 2019
['2019-04-03', '0.910', '0.910', '0.910', '0.910', '0.910', '-']
36
0.910
37
0.910
38
0.910
39
0.910
40
0.910
41
-
42
Apr 02, 2019
['2019-04-02', '0.910', '0.910', '0.910', '0.910', '0.910', '-']
43
0.910
44
0.910
45
0.910
46
0.910
47
0.910
48
-
49
Apr 01, 2019
['2019-04-01', '0.910', '0.910', '0.910', '0.910', '0.910', '-']
50
0.910
51
0.910
52
0.910
53
0.910
54
0.910
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0008.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.710', '4.740', '4.700', '4.740', '4.740', '11,750,728']
1
4.710
2
4.740
3
4.700
4
4.740
5
4.740
6
11,750,728
7
Apr 10, 2019
['2019-04-10', '4.720', '4.750', '4.710', '4.710', '4.710', '9,057,984']
8
4.720
9
4.750
10
4.710
11
4.710
12
4.710
13
9,057,984
14
Apr 09, 2019
['2019-04-09', '4.750', '4.760', '4.700', '4.730', '4.730', '13,984,367']
15
4.750
16
4.760
17
4.700
18
4.730
19
4.730
20
13,984,367
21
Apr 08, 2019
['2019-04-08', '4.800', '4.830', '4.740', '4.740', '4.740', '12,059,749']
22
4.800
23
4.830
24
4.740
25
4.740
26
4.740
27
12,059,749
28
Apr 04, 2019
['2019-04-04', '4.890', '4.890', '4.790', '4.800', '4.800', '12,605,930']
29
4.890
30
4.890
31
4.790
32
4.800
33
4.800
34
12,605,930
35
Apr 03, 2019
['2019-04-03', '4.920', '4.920', '4.850', '4.860', '4.860', '8,955,760']
36
4.920
37
4.920
38
4.850
39
4.860
40
4.860
41
8,955,760
42
Apr 02, 2019
['2019-04-02', '4.890', '4.920', '4.850', '4.900', '4.900', '8,224,884']
43
4.890
44
4.920
45
4.850
46
4.900
47
4.900
48
8,224,884
49
Apr 01, 2019
['2019-04-01', '4.880', '4.920', '4.840', '4.860', '4.860', '9,759,607']
50
4.880
51
4.920
52
4.840
53
4.860
54
4.860
55
9,759,607
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0009.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.217', '0.217', '0.203', '0.208', '0.208', '1,494,000']
1
0.217
2
0.217
3
0.203
4
0.208
5
0.208
6
1,494,000
7
Apr 10, 2019
['2019-04-10', '0.211', '0.214', '0.208', '0.213', '0.213', '498,000']
8
0.211
9
0.214
10
0.208
11
0.213
12
0.213
13
498,000
14
Apr 09, 2019
['2019-04-09', '0.213', '0.213', '0.211', '0.211', '0.211', '780,000']
15
0.213
16
0.213
17
0.211
18
0.211
19
0.211
20
780,000
21
Apr 08, 2019
['2019-04-08', '0.214', '0.214', '0.213', '0.214', '0.214', '660,400']
22
0.214
23
0.214
24
0.213
25
0.214
26
0.214
27
660,400
28
Apr 04, 2019
['2019-04-04', '0.220', '0.222', '0.215', '0.217', '0.217', '516,000']
29
0.220
30
0.222
31
0.215
32
0.217
33
0.217
34
516,000
35
Apr 03, 2019
['2019-04-03', '0.222', '0.224', '0.222', '0.222', '0.222', '162,165']
36
0.222
37
0.224
38
0.222
39
0.222
40
0.222
41
162,165
42
Apr 02, 2019
['2019-04-02', '0.235', '0.235', '0.218', '0.219', '0.219', '696,000']
43
0.235
44
0.235
45
0.218
46
0.219
47
0.219
48
696,000
49
Apr 01, 2019
['2019-04-01', '0.222', '0.227', '0.220', '0.226', '0.226', '864,000']
50
0.222
51
0.227
52
0.220
53
0.226
54
0.226
55
864,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0011.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '198.100', '198.600', '196.500', '198.100', '198.100', '1,480,681']
1
198.100
2
198.600
3
196.500
4
198.100
5
198.100
6
1,480,681
7
Apr 10, 2019
['2019-04-10', '197.800', '198.500', '197.000', '198.000', '198.000', '1,279,208']
8
197.800
9
198.500
10
197.000
11
198.000
12
198.000
13
1,279,208
14
Apr 09, 2019
['2019-04-09', '197.300', '197.900', '196.300', '197.800', '197.800', '1,150,399']
15
197.300
16
197.900
17
196.300
18
197.800
19
197.800
20
1,150,399
21
Apr 08, 2019
['2019-04-08', '199.000', '199.700', '195.400', '195.700', '195.700', '4,011,630']
22
199.000
23
199.700
24
195.400
25
195.700
26
195.700
27
4,011,630
28
Apr 04, 2019
['2019-04-04', '197.000', '198.500', '195.600', '198.400', '198.400', '1,431,011']
29
197.000
30
198.500
31
195.600
32
198.400
33
198.400
34
1,431,011
35
Apr 03, 2019
['2019-04-03', '196.000', '196.800', '194.500', '196.700', '196.700', '1,046,982']
36
196.000
37
196.800
38
194.500
39
196.700
40
196.700
41
1,046,982
42
Apr 02, 2019
['2019-04-02', '194.500', '197.000', '194.500', '196.600', '196.600', '1,695,839']
43
194.500
44
197.000
45
194.500
46
196.600
47
196.600
48
1,695,839
49
Apr 01, 2019
['2019-04-01', '194.000', '195.700', '194.000', '195.700', '195.700', '1,643,102']
50
194.000
51
195.700
52
194.000
53
195.700
54
195.700
55
1,643,102
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0012.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '50.800', '50.900', '49.800', '49.950', '49.950', '7,059,669']
1
50.800
2
50.900
3
49.800
4
49.950
5
49.950
6
7,059,669
7
Apr 10, 2019
['2019-04-10', '50.400', '51.050', '50.000', '50.850', '50.850', '5,099,591']
8
50.400
9
51.050
10
50.000
11
50.850
12
50.850
13
5,099,591
14
Apr 09, 2019
['2019-04-09', '50.600', '50.600', '50.050', '50.200', '50.200', '3,213,039']
15
50.600
16
50.600
17
50.050
18
50.200
19
50.200
20
3,213,039
21
Apr 08, 2019
['2019-04-08', '50.500', '50.750', '50.050', '50.300', '50.300', '5,493,750']
22
50.500
23
50.750
24
50.050
25
50.300
26
50.300
27
5,493,750
28
Apr 04, 2019
['2019-04-04', '49.900', '50.200', '49.500', '50.050', '50.050', '3,679,180']
29
49.900
30
50.200
31
49.500
32
50.050
33
50.050
34
3,679,180
35
Apr 03, 2019
['2019-04-03', '49.600', '50.000', '49.500', '49.950', '49.950', '4,184,819']
36
49.600
37
50.000
38
49.500
39
49.950
40
49.950
41
4,184,819
42
Apr 02, 2019
['2019-04-02', '50.050', '50.150', '49.450', '49.900', '49.900', '6,004,494']
43
50.050
44
50.150
45
49.450
46
49.900
47
49.900
48
6,004,494
49
Apr 01, 2019
['2019-04-01', '50.300', '50.500', '49.950', '50.050', '50.050', '10,259,142']
50
50.300
51
50.500
52
49.950
53
50.050
54
50.050
55
10,259,142
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0015.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.720', '0.720', '0.720', '0.720', '0.720', '-']
1
0.720
2
0.720
3
0.720
4
0.720
5
0.720
6
-
7
Apr 10, 2019
['2019-04-10', '0.720', '0.720', '0.720', '0.720', '0.720', '-']
8
0.720
9
0.720
10
0.720
11
0.720
12
0.720
13
-
14
Apr 09, 2019
['2019-04-09', '0.710', '0.740', '0.710', '0.720', '0.720', '180,000']
15
0.710
16
0.740
17
0.710
18
0.720
19
0.720
20
180,000
21
Apr 08, 2019
['2019-04-08', '0.710', '0.710', '0.710', '0.710', '0.710', '-']
22
0.710
23
0.710
24
0.710
25
0.710
26
0.710
27
-
28
Apr 04, 2019
['2019-04-04', '0.700', '0.730', '0.700', '0.710', '0.710', '30,000']
29
0.700
30
0.730
31
0.700
32
0.710
33
0.710
34
30,000
35
Apr 03, 2019
['2019-04-03', '0.720', '0.720', '0.700', '0.720', '0.720', '422,000']
36
0.720
37
0.720
38
0.700
39
0.720
40
0.720
41
422,000
42
Apr 02, 2019
['2019-04-02', '0.730', '0.750', '0.730', '0.730', '0.730', '34,000']
43
0.730
44
0.750
45
0.730
46
0.730
47
0.730
48
34,000
49
Apr 01, 2019
['2019-04-01', '0.720', '0.720', '0.720', '0.720', '0.720', '18,000']
50
0.720
51
0.720
52
0.720
53
0.720
54
0.720
55
18,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0016.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '139.000', '139.600', '136.000', '136.800', '136.800', '5,889,189']
1
139.000
2
139.600
3
136.000
4
136.800
5
136.800
6
5,889,189
7
Apr 10, 2019
['2019-04-10', '140.000', '140.500', '139.100', '139.600', '139.600', '4,394,386']
8
140.000
9
140.500
10
139.100
11
139.600
12
139.600
13
4,394,386
14
Apr 09, 2019
['2019-04-09', '140.600', '141.100', '140.000', '140.700', '140.700', '4,931,314']
15
140.600
16
141.100
17
140.000
18
140.700
19
140.700
20
4,931,314
21
Apr 08, 2019
['2019-04-08', '142.000', '142.000', '140.100', '141.300', '141.300', '3,746,364']
22
142.000
23
142.000
24
140.100
25
141.300
26
141.300
27
3,746,364
28
Apr 04, 2019
['2019-04-04', '141.000', '142.000', '140.200', '141.500', '141.500', '3,358,765']
29
141.000
30
142.000
31
140.200
32
141.500
33
141.500
34
3,358,765
35
Apr 03, 2019
['2019-04-03', '140.100', '141.800', '140.000', '141.600', '141.600', '3,744,902']
36
140.100
37
141.800
38
140.000
39
141.600
40
141.600
41
3,744,902
42
Apr 02, 2019
['2019-04-02', '140.000', '141.900', '139.200', '141.300', '141.300', '5,341,280']
43
140.000
44
141.900
45
139.200
46
141.300
47
141.300
48
5,341,280
49
Apr 01, 2019
['2019-04-01', '136.000', '141.700', '135.400', '141.400', '141.400', '9,921,308']
50
136.000
51
141.700
52
135.400
53
141.400
54
141.400
55
9,921,308
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0017.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '13.420', '13.580', '13.260', '13.300', '13.300', '14,029,332']
1
13.420
2
13.580
3
13.260
4
13.300
5
13.300
6
14,029,332
7
Apr 10, 2019
['2019-04-10', '13.600', '13.680', '13.440', '13.520', '13.520', '14,233,841']
8
13.600
9
13.680
10
13.440
11
13.520
12
13.520
13
14,233,841
14
Apr 09, 2019
['2019-04-09', '13.600', '13.680', '13.500', '13.600', '13.600', '15,994,654']
15
13.600
16
13.680
17
13.500
18
13.600
19
13.600
20
15,994,654
21
Apr 08, 2019
['2019-04-08', '13.860', '13.860', '13.620', '13.700', '13.700', '14,466,870']
22
13.860
23
13.860
24
13.620
25
13.700
26
13.700
27
14,466,870
28
Apr 04, 2019
['2019-04-04', '13.800', '13.860', '13.620', '13.760', '13.760', '16,802,528']
29
13.800
30
13.860
31
13.620
32
13.760
33
13.760
34
16,802,528
35
Apr 03, 2019
['2019-04-03', '13.800', '13.880', '13.680', '13.880', '13.880', '19,351,792']
36
13.800
37
13.880
38
13.680
39
13.880
40
13.880
41
19,351,792
42
Apr 02, 2019
['2019-04-02', '13.440', '13.860', '13.440', '13.840', '13.840', '27,464,375']
43
13.440
44
13.860
45
13.440
46
13.840
47
13.840
48
27,464,375
49
Apr 01, 2019
['2019-04-01', '13.280', '13.700', '13.240', '13.700', '13.700', '41,021,565']
50
13.280
51
13.700
52
13.240
53
13.700
54
13.700
55
41,021,565
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0019.HKneeds update
[15]
[15]
59
15
length in loop59
15poped
[]
[]
0
Apr 11, 2019
['2019-04-11', '100.400', '100.400', '97.500', '98.800', '98.800', '1,926,905']
1
100.400
2
100.400
3
97.500
4
98.800
5
98.800
6
1,926,905
7
Apr 10, 2019
['2019-04-10', '99.750', '100.700', '98.350', '98.600', '98.600', '1,644,405']
8
99.750
9
100.700
10
98.350
11
98.600
12
98.600
13
1,644,405
14
Apr 09, 2019
['2019-04-09', '101.400', '101.600', '99.900', '100.900', '99.100', '1,448,549']
15
101.400
16
101.600
17
99.900
18
100.900
19
99.100
20
1,448,549
21
Apr 08, 2019
['2019-04-08', '102.500', '102.500', '99.900', '100.200', '98.412', '2,602,069']
22
102.500
23
102.500
24
99.900
25
100.200
26
98.412
27
2,602,069
28
Apr 04, 2019
['2019-04-04', '103.800', '103.800', '101.800', '102.300', '100.475', '1,587,675']
29
103.800
30
103.800
31
101.800
32
102.300
33
100.475
34
1,587,675
35
Apr 03, 2019
['2019-04-03', '102.200', '102.500', '101.200', '102.300', '100.475', '1,363,066']
36
102.200
37
102.500
38
101.200
39
102.300
40
100.475
41
1,363,066
42
Apr 02, 2019
['2019-04-02', '101.000', '101.600', '100.300', '101.200', '99.395', '1,560,179']
43
101.000
44
101.600
45
100.300
46
101.200
47
99.395
48
1,560,179
49
Apr 01, 2019
['2019-04-01', '101.500', '102.400', '100.400', '102.200', '100.377', '2,205,730']
50
101.500
51
102.400
52
100.400
53
102.200
54
100.377
55
2,205,730
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0020.HKneeds update
[15]
[15]
59
15
length in loop59
15poped
[]
[]
0
Apr 11, 2019
['2019-04-11', '57.800', '57.800', '56.000', '56.250', '56.250', '1,332,725']
1
57.800
2
57.800
3
56.000
4
56.250
5
56.250
6
1,332,725
7
Apr 10, 2019
['2019-04-10', '57.500', '57.700', '56.750', '56.950', '56.950', '1,829,000']
8
57.500
9
57.700
10
56.750
11
56.950
12
56.950
13
1,829,000
14
Apr 09, 2019
['2019-04-09', '59.300', '59.300', '58.000', '58.450', '57.400', '1,692,085']
15
59.300
16
59.300
17
58.000
18
58.450
19
57.400
20
1,692,085
21
Apr 08, 2019
['2019-04-08', '59.500', '59.500', '58.450', '58.650', '57.596', '1,544,829']
22
59.500
23
59.500
24
58.450
25
58.650
26
57.596
27
1,544,829
28
Apr 04, 2019
['2019-04-04', '59.350', '59.350', '58.500', '58.850', '57.793', '1,167,700']
29
59.350
30
59.350
31
58.500
32
58.850
33
57.793
34
1,167,700
35
Apr 03, 2019
['2019-04-03', '59.400', '59.400', '58.500', '59.000', '57.940', '1,749,859']
36
59.400
37
59.400
38
58.500
39
59.000
40
57.940
41
1,749,859
42
Apr 02, 2019
['2019-04-02', '58.850', '59.250', '58.100', '59.200', '58.137', '3,636,818']
43
58.850
44
59.250
45
58.100
46
59.200
47
58.137
48
3,636,818
49
Apr 01, 2019
['2019-04-01', '57.800', '58.100', '57.650', '58.050', '57.007', '1,527,100']
50
57.800
51
58.100
52
57.650
53
58.050
54
57.007
55
1,527,100
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0021.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.174', '0.174', '0.155', '0.161', '0.161', '390,000']
1
0.174
2
0.174
3
0.155
4
0.161
5
0.161
6
390,000
7
Apr 10, 2019
['2019-04-10', '0.169', '0.169', '0.169', '0.169', '0.169', '-']
8
0.169
9
0.169
10
0.169
11
0.169
12
0.169
13
-
14
Apr 09, 2019
['2019-04-09', '0.163', '0.170', '0.156', '0.169', '0.169', '215,000']
15
0.163
16
0.170
17
0.156
18
0.169
19
0.169
20
215,000
21
Apr 08, 2019
['2019-04-08', '0.170', '0.170', '0.170', '0.170', '0.170', '-']
22
0.170
23
0.170
24
0.170
25
0.170
26
0.170
27
-
28
Apr 04, 2019
['2019-04-04', '0.170', '0.170', '0.170', '0.170', '0.170', '-']
29
0.170
30
0.170
31
0.170
32
0.170
33
0.170
34
-
35
Apr 03, 2019
['2019-04-03', '0.170', '0.170', '0.170', '0.170', '0.170', '-']
36
0.170
37
0.170
38
0.170
39
0.170
40
0.170
41
-
42
Apr 02, 2019
['2019-04-02', '0.170', '0.170', '0.170', '0.170', '0.170', '-']
43
0.170
44
0.170
45
0.170
46
0.170
47
0.170
48
-
49
Apr 01, 2019
['2019-04-01', '0.170', '0.170', '0.170', '0.170', '0.170', '-']
50
0.170
51
0.170
52
0.170
53
0.170
54
0.170
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0022.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.222', '0.222', '0.222', '0.222', '0.222', '-']
1
0.222
2
0.222
3
0.222
4
0.222
5
0.222
6
-
7
Apr 10, 2019
['2019-04-10', '0.222', '0.222', '0.222', '0.222', '0.222', '80,000']
8
0.222
9
0.222
10
0.222
11
0.222
12
0.222
13
80,000
14
Apr 09, 2019
['2019-04-09', '0.218', '0.218', '0.218', '0.218', '0.218', '-']
15
0.218
16
0.218
17
0.218
18
0.218
19
0.218
20
-
21
Apr 08, 2019
['2019-04-08', '0.217', '0.225', '0.217', '0.218', '0.218', '360,000']
22
0.217
23
0.225
24
0.217
25
0.218
26
0.218
27
360,000
28
Apr 04, 2019
['2019-04-04', '0.221', '0.223', '0.221', '0.223', '0.223', '460,000']
29
0.221
30
0.223
31
0.221
32
0.223
33
0.223
34
460,000
35
Apr 03, 2019
['2019-04-03', '0.217', '0.222', '0.217', '0.217', '0.217', '480,000']
36
0.217
37
0.222
38
0.217
39
0.217
40
0.217
41
480,000
42
Apr 02, 2019
['2019-04-02', '0.221', '0.221', '0.212', '0.217', '0.217', '1,880,000']
43
0.221
44
0.221
45
0.212
46
0.217
47
0.217
48
1,880,000
49
Apr 01, 2019
['2019-04-01', '0.229', '0.229', '0.229', '0.229', '0.229', '-']
50
0.229
51
0.229
52
0.229
53
0.229
54
0.229
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0023.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '25.800', '25.800', '25.350', '25.350', '25.350', '785,223']
1
25.800
2
25.800
3
25.350
4
25.350
5
25.350
6
785,223
7
Apr 10, 2019
['2019-04-10', '25.550', '25.750', '25.450', '25.700', '25.700', '582,650']
8
25.550
9
25.750
10
25.450
11
25.700
12
25.700
13
582,650
14
Apr 09, 2019
['2019-04-09', '25.400', '25.700', '25.400', '25.650', '25.650', '768,130']
15
25.400
16
25.700
17
25.400
18
25.650
19
25.650
20
768,130
21
Apr 08, 2019
['2019-04-08', '26.000', '26.000', '25.350', '25.450', '25.450', '1,339,600']
22
26.000
23
26.000
24
25.350
25
25.450
26
25.450
27
1,339,600
28
Apr 04, 2019
['2019-04-04', '26.050', '26.050', '25.650', '25.750', '25.750', '1,282,865']
29
26.050
30
26.050
31
25.650
32
25.750
33
25.750
34
1,282,865
35
Apr 03, 2019
['2019-04-03', '25.650', '26.200', '25.500', '26.100', '26.100', '1,253,349']
36
25.650
37
26.200
38
25.500
39
26.100
40
26.100
41
1,253,349
42
Apr 02, 2019
['2019-04-02', '25.750', '25.850', '25.450', '25.800', '25.800', '802,779']
43
25.750
44
25.850
45
25.450
46
25.800
47
25.800
48
802,779
49
Apr 01, 2019
['2019-04-01', '25.500', '25.900', '25.400', '25.800', '25.800', '1,296,861']
50
25.500
51
25.900
52
25.400
53
25.800
54
25.800
55
1,296,861
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0024.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.138', '0.140', '0.135', '0.138', '0.138', '5,158,000']
1
0.138
2
0.140
3
0.135
4
0.138
5
0.138
6
5,158,000
7
Apr 10, 2019
['2019-04-10', '0.138', '0.142', '0.137', '0.138', '0.138', '2,903,420']
8
0.138
9
0.142
10
0.137
11
0.138
12
0.138
13
2,903,420
14
Apr 09, 2019
['2019-04-09', '0.141', '0.143', '0.135', '0.139', '0.139', '7,136,000']
15
0.141
16
0.143
17
0.135
18
0.139
19
0.139
20
7,136,000
21
Apr 08, 2019
['2019-04-08', '0.139', '0.141', '0.136', '0.141', '0.141', '1,709,000']
22
0.139
23
0.141
24
0.136
25
0.141
26
0.141
27
1,709,000
28
Apr 04, 2019
['2019-04-04', '0.138', '0.140', '0.137', '0.139', '0.139', '4,526,000']
29
0.138
30
0.140
31
0.137
32
0.139
33
0.139
34
4,526,000
35
Apr 03, 2019
['2019-04-03', '0.140', '0.143', '0.131', '0.135', '0.135', '15,506,000']
36
0.140
37
0.143
38
0.131
39
0.135
40
0.135
41
15,506,000
42
Apr 02, 2019
['2019-04-02', '0.141', '0.143', '0.137', '0.138', '0.138', '12,278,000']
43
0.141
44
0.143
45
0.137
46
0.138
47
0.138
48
12,278,000
49
Apr 01, 2019
['2019-04-01', '0.159', '0.159', '0.140', '0.144', '0.144', '26,654,000']
50
0.159
51
0.159
52
0.140
53
0.144
54
0.144
55
26,654,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0025.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '12.000', '12.000', '12.000', '12.000', '12.000', '-']
1
12.000
2
12.000
3
12.000
4
12.000
5
12.000
6
-
7
Apr 10, 2019
['2019-04-10', '11.960', '12.000', '11.960', '12.000', '12.000', '4,000']
8
11.960
9
12.000
10
11.960
11
12.000
12
12.000
13
4,000
14
Apr 09, 2019
['2019-04-09', '11.980', '12.000', '11.980', '12.000', '12.000', '12,000']
15
11.980
16
12.000
17
11.980
18
12.000
19
12.000
20
12,000
21
Apr 08, 2019
['2019-04-08', '11.980', '11.980', '11.980', '11.980', '11.980', '6,000']
22
11.980
23
11.980
24
11.980
25
11.980
26
11.980
27
6,000
28
Apr 04, 2019
['2019-04-04', '11.800', '11.980', '11.800', '11.980', '11.980', '26,000']
29
11.800
30
11.980
31
11.800
32
11.980
33
11.980
34
26,000
35
Apr 03, 2019
['2019-04-03', '11.720', '12.000', '11.700', '11.960', '11.960', '34,000']
36
11.720
37
12.000
38
11.700
39
11.960
40
11.960
41
34,000
42
Apr 02, 2019
['2019-04-02', '11.840', '11.880', '11.800', '11.880', '11.880', '14,000']
43
11.840
44
11.880
45
11.800
46
11.880
47
11.880
48
14,000
49
Apr 01, 2019
['2019-04-01', '11.860', '11.960', '11.680', '11.840', '11.840', '44,372']
50
11.860
51
11.960
52
11.680
53
11.840
54
11.840
55
44,372
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0027.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '60.700', '60.700', '58.000', '58.050', '58.050', '17,277,755']
1
60.700
2
60.700
3
58.000
4
58.050
5
58.050
6
17,277,755
7
Apr 10, 2019
['2019-04-10', '59.800', '60.750', '58.700', '60.400', '60.400', '11,417,119']
8
59.800
9
60.750
10
58.700
11
60.400
12
60.400
13
11,417,119
14
Apr 09, 2019
['2019-04-09', '59.800', '60.850', '59.100', '59.700', '59.700', '10,514,553']
15
59.800
16
60.850
17
59.100
18
59.700
19
59.700
20
10,514,553
21
Apr 08, 2019
['2019-04-08', '61.800', '62.000', '59.350', '59.850', '59.850', '12,493,062']
22
61.800
23
62.000
24
59.350
25
59.850
26
59.850
27
12,493,062
28
Apr 04, 2019
['2019-04-04', '60.500', '62.100', '60.050', '61.300', '61.300', '14,839,726']
29
60.500
30
62.100
31
60.050
32
61.300
33
61.300
34
14,839,726
35
Apr 03, 2019
['2019-04-03', '59.100', '61.150', '58.900', '60.750', '60.750', '21,138,694']
36
59.100
37
61.150
38
58.900
39
60.750
40
60.750
41
21,138,694
42
Apr 02, 2019
['2019-04-02', '57.200', '59.450', '56.700', '58.950', '58.950', '31,781,810']
43
57.200
44
59.450
45
56.700
46
58.950
47
58.950
48
31,781,810
49
Apr 01, 2019
['2019-04-01', '54.000', '56.850', '53.600', '56.650', '56.650', '29,306,111']
50
54.000
51
56.850
52
53.600
53
56.650
54
56.650
55
29,306,111
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0028.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.340', '4.340', '4.290', '4.290', '4.290', '16,000']
1
4.340
2
4.340
3
4.290
4
4.290
5
4.290
6
16,000
7
Apr 10, 2019
['2019-04-10', '4.340', '4.340', '4.250', '4.270', '4.270', '72,000']
8
4.340
9
4.340
10
4.250
11
4.270
12
4.270
13
72,000
14
Apr 09, 2019
['2019-04-09', '4.330', '4.390', '4.330', '4.340', '4.340', '979,400']
15
4.330
16
4.390
17
4.330
18
4.340
19
4.340
20
979,400
21
Apr 08, 2019
['2019-04-08', '4.360', '4.360', '4.360', '4.360', '4.360', '-']
22
4.360
23
4.360
24
4.360
25
4.360
26
4.360
27
-
28
Apr 04, 2019
['2019-04-04', '4.360', '4.370', '4.290', '4.360', '4.360', '690,000']
29
4.360
30
4.370
31
4.290
32
4.360
33
4.360
34
690,000
35
Apr 03, 2019
['2019-04-03', '4.260', '4.400', '4.300', '4.390', '4.390', '26,000']
36
4.260
37
4.400
38
4.300
39
4.390
40
4.390
41
26,000
42
Apr 02, 2019
['2019-04-02', '4.270', '4.300', '4.270', '4.300', '4.300', '78,000']
43
4.270
44
4.300
45
4.270
46
4.300
47
4.300
48
78,000
49
Apr 01, 2019
['2019-04-01', '4.230', '4.300', '4.230', '4.290', '4.290', '79,000']
50
4.230
51
4.300
52
4.230
53
4.290
54
4.290
55
79,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0029.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '7.870', '7.870', '7.770', '7.770', '7.770', '172,000']
1
7.870
2
7.870
3
7.770
4
7.770
5
7.770
6
172,000
7
Apr 10, 2019
['2019-04-10', '7.790', '7.950', '7.670', '7.810', '7.810', '239,000']
8
7.790
9
7.950
10
7.670
11
7.810
12
7.810
13
239,000
14
Apr 09, 2019
['2019-04-09', '7.580', '7.720', '7.550', '7.600', '7.600', '118,000']
15
7.580
16
7.720
17
7.550
18
7.600
19
7.600
20
118,000
21
Apr 08, 2019
['2019-04-08', '7.600', '7.700', '7.560', '7.670', '7.670', '88,000']
22
7.600
23
7.700
24
7.560
25
7.670
26
7.670
27
88,000
28
Apr 04, 2019
['2019-04-04', '7.480', '7.690', '7.480', '7.670', '7.670', '11,000']
29
7.480
30
7.690
31
7.480
32
7.670
33
7.670
34
11,000
35
Apr 03, 2019
['2019-04-03', '7.550', '7.580', '7.550', '7.580', '7.580', '21,200']
36
7.550
37
7.580
38
7.550
39
7.580
40
7.580
41
21,200
42
Apr 02, 2019
['2019-04-02', '7.550', '7.580', '7.550', '7.580', '7.580', '6,000']
43
7.550
44
7.580
45
7.550
46
7.580
47
7.580
48
6,000
49
Apr 01, 2019
['2019-04-01', '7.610', '7.610', '7.550', '7.550', '7.550', '150,000']
50
7.610
51
7.610
52
7.550
53
7.550
54
7.550
55
150,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0030.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.305', '0.310', '0.300', '0.305', '0.305', '3,596,000']
1
0.305
2
0.310
3
0.300
4
0.305
5
0.305
6
3,596,000
7
Apr 10, 2019
['2019-04-10', '0.295', '0.310', '0.290', '0.310', '0.310', '5,266,000']
8
0.295
9
0.310
10
0.290
11
0.310
12
0.310
13
5,266,000
14
Apr 09, 2019
['2019-04-09', '0.285', '0.300', '0.285', '0.295', '0.295', '1,068,000']
15
0.285
16
0.300
17
0.285
18
0.295
19
0.295
20
1,068,000
21
Apr 08, 2019
['2019-04-08', '0.290', '0.300', '0.285', '0.285', '0.285', '2,764,000']
22
0.290
23
0.300
24
0.285
25
0.285
26
0.285
27
2,764,000
28
Apr 04, 2019
['2019-04-04', '0.290', '0.290', '0.270', '0.285', '0.285', '5,842,000']
29
0.290
30
0.290
31
0.270
32
0.285
33
0.285
34
5,842,000
35
Apr 03, 2019
['2019-04-03', '0.300', '0.305', '0.295', '0.295', '0.295', '13,200,000']
36
0.300
37
0.305
38
0.295
39
0.295
40
0.295
41
13,200,000
42
Apr 02, 2019
['2019-04-02', '0.305', '0.310', '0.295', '0.305', '0.305', '27,722,000']
43
0.305
44
0.310
45
0.295
46
0.305
47
0.305
48
27,722,000
49
Apr 01, 2019
['2019-04-01', '0.310', '0.310', '0.300', '0.310', '0.310', '36,930,000']
50
0.310
51
0.310
52
0.300
53
0.310
54
0.310
55
36,930,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0033.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.052', '0.055', '0.051', '0.055', '0.055', '8,880,000']
1
0.052
2
0.055
3
0.051
4
0.055
5
0.055
6
8,880,000
7
Apr 10, 2019
['2019-04-10', '0.053', '0.053', '0.050', '0.052', '0.052', '13,640,000']
8
0.053
9
0.053
10
0.050
11
0.052
12
0.052
13
13,640,000
14
Apr 09, 2019
['2019-04-09', '0.052', '0.056', '0.051', '0.053', '0.053', '18,286,000']
15
0.052
16
0.056
17
0.051
18
0.053
19
0.053
20
18,286,000
21
Apr 08, 2019
['2019-04-08', '0.060', '0.060', '0.051', '0.054', '0.054', '65,784,000']
22
0.060
23
0.060
24
0.051
25
0.054
26
0.054
27
65,784,000
28
Apr 04, 2019
['2019-04-04', '0.062', '0.066', '0.061', '0.064', '0.064', '12,846,000']
29
0.062
30
0.066
31
0.061
32
0.064
33
0.064
34
12,846,000
35
Apr 03, 2019
['2019-04-03', '0.062', '0.066', '0.060', '0.062', '0.062', '8,574,000']
36
0.062
37
0.066
38
0.060
39
0.062
40
0.062
41
8,574,000
42
Apr 02, 2019
['2019-04-02', '0.067', '0.067', '0.058', '0.062', '0.062', '56,796,000']
43
0.067
44
0.067
45
0.058
46
0.062
47
0.062
48
56,796,000
49
Apr 01, 2019
['2019-04-01', '0.072', '0.074', '0.067', '0.069', '0.069', '22,142,000']
50
0.072
51
0.074
52
0.067
53
0.069
54
0.069
55
22,142,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0035.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '3.880', '3.910', '3.860', '3.870', '3.870', '300,000']
1
3.880
2
3.910
3
3.860
4
3.870
5
3.870
6
300,000
7
Apr 10, 2019
['2019-04-10', '3.900', '3.920', '3.850', '3.870', '3.870', '631,481']
8
3.900
9
3.920
10
3.850
11
3.870
12
3.870
13
631,481
14
Apr 09, 2019
['2019-04-09', '3.870', '3.900', '3.850', '3.900', '3.900', '678,106']
15
3.870
16
3.900
17
3.850
18
3.900
19
3.900
20
678,106
21
Apr 08, 2019
['2019-04-08', '3.880', '3.900', '3.850', '3.900', '3.900', '850,231']
22
3.880
23
3.900
24
3.850
25
3.900
26
3.900
27
850,231
28
Apr 04, 2019
['2019-04-04', '3.850', '3.900', '3.850', '3.880', '3.880', '222,526']
29
3.850
30
3.900
31
3.850
32
3.880
33
3.880
34
222,526
35
Apr 03, 2019
['2019-04-03', '3.890', '3.950', '3.860', '3.890', '3.890', '1,358,926']
36
3.890
37
3.950
38
3.860
39
3.890
40
3.890
41
1,358,926
42
Apr 02, 2019
['2019-04-02', '3.800', '3.890', '3.780', '3.890', '3.890', '836,873']
43
3.800
44
3.890
45
3.780
46
3.890
47
3.890
48
836,873
49
Apr 01, 2019
['2019-04-01', '3.800', '3.800', '3.740', '3.770', '3.770', '1,174,914']
50
3.800
51
3.800
52
3.740
53
3.770
54
3.770
55
1,174,914
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0038.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.190', '2.240', '2.120', '2.160', '2.160', '2,564,000']
1
2.190
2
2.240
3
2.120
4
2.160
5
2.160
6
2,564,000
7
Apr 10, 2019
['2019-04-10', '2.170', '2.170', '2.130', '2.160', '2.160', '934,000']
8
2.170
9
2.170
10
2.130
11
2.160
12
2.160
13
934,000
14
Apr 09, 2019
['2019-04-09', '2.100', '2.170', '2.090', '2.150', '2.150', '1,774,000']
15
2.100
16
2.170
17
2.090
18
2.150
19
2.150
20
1,774,000
21
Apr 08, 2019
['2019-04-08', '2.130', '2.130', '2.080', '2.100', '2.100', '286,000']
22
2.130
23
2.130
24
2.080
25
2.100
26
2.100
27
286,000
28
Apr 04, 2019
['2019-04-04', '2.120', '2.120', '2.080', '2.100', '2.100', '506,000']
29
2.120
30
2.120
31
2.080
32
2.100
33
2.100
34
506,000
35
Apr 03, 2019
['2019-04-03', '2.100', '2.120', '2.070', '2.110', '2.110', '938,000']
36
2.100
37
2.120
38
2.070
39
2.110
40
2.110
41
938,000
42
Apr 02, 2019
['2019-04-02', '2.100', '2.110', '2.070', '2.070', '2.070', '650,000']
43
2.100
44
2.110
45
2.070
46
2.070
47
2.070
48
650,000
49
Apr 01, 2019
['2019-04-01', '2.040', '2.110', '2.000', '2.070', '2.070', '928,000']
50
2.040
51
2.110
52
2.000
53
2.070
54
2.070
55
928,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0039.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.265', '0.265', '0.243', '0.247', '0.247', '5,114,000']
1
0.265
2
0.265
3
0.243
4
0.247
5
0.247
6
5,114,000
7
Apr 10, 2019
['2019-04-10', '0.275', '0.275', '0.260', '0.265', '0.265', '1,712,000']
8
0.275
9
0.275
10
0.260
11
0.265
12
0.265
13
1,712,000
14
Apr 09, 2019
['2019-04-09', '0.280', '0.285', '0.270', '0.275', '0.275', '8,080,000']
15
0.280
16
0.285
17
0.270
18
0.275
19
0.275
20
8,080,000
21
Apr 08, 2019
['2019-04-08', '0.290', '0.290', '0.275', '0.280', '0.280', '1,600,000']
22
0.290
23
0.290
24
0.275
25
0.280
26
0.280
27
1,600,000
28
Apr 04, 2019
['2019-04-04', '0.265', '0.280', '0.265', '0.280', '0.280', '8,588,000']
29
0.265
30
0.280
31
0.265
32
0.280
33
0.280
34
8,588,000
35
Apr 03, 2019
['2019-04-03', '0.265', '0.285', '0.265', '0.270', '0.270', '4,826,000']
36
0.265
37
0.285
38
0.265
39
0.270
40
0.270
41
4,826,000
42
Apr 02, 2019
['2019-04-02', '0.260', '0.270', '0.260', '0.265', '0.265', '3,726,000']
43
0.260
44
0.270
45
0.260
46
0.265
47
0.265
48
3,726,000
49
Apr 01, 2019
['2019-04-01', '0.242', '0.265', '0.241', '0.260', '0.260', '10,780,000']
50
0.242
51
0.265
52
0.241
53
0.260
54
0.260
55
10,780,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0041.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '37.600', '37.950', '37.500', '37.700', '37.700', '309,000']
1
37.600
2
37.950
3
37.500
4
37.700
5
37.700
6
309,000
7
Apr 10, 2019
['2019-04-10', '38.100', '38.100', '37.500', '37.550', '37.550', '315,009']
8
38.100
9
38.100
10
37.500
11
37.550
12
37.550
13
315,009
14
Apr 09, 2019
['2019-04-09', '38.800', '39.450', '38.050', '38.200', '38.200', '187,769']
15
38.800
16
39.450
17
38.050
18
38.200
19
38.200
20
187,769
21
Apr 08, 2019
['2019-04-08', '39.000', '39.050', '38.850', '38.950', '38.950', '49,022']
22
39.000
23
39.050
24
38.850
25
38.950
26
38.950
27
49,022
28
Apr 04, 2019
['2019-04-04', '39.150', '39.500', '38.950', '39.150', '39.150', '42,000']
29
39.150
30
39.500
31
38.950
32
39.150
33
39.150
34
42,000
35
Apr 03, 2019
['2019-04-03', '39.250', '39.500', '39.150', '39.400', '39.400', '43,963']
36
39.250
37
39.500
38
39.150
39
39.400
40
39.400
41
43,963
42
Apr 02, 2019
['2019-04-02', '39.600', '39.600', '39.250', '39.250', '39.250', '38,000']
43
39.600
44
39.600
45
39.250
46
39.250
47
39.250
48
38,000
49
Apr 01, 2019
['2019-04-01', '40.000', '40.050', '39.250', '39.650', '39.650', '168,710']
50
40.000
51
40.050
52
39.250
53
39.650
54
39.650
55
168,710
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0042.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.900', '0.900', '0.870', '0.870', '0.870', '164,000']
1
0.900
2
0.900
3
0.870
4
0.870
5
0.870
6
164,000
7
Apr 10, 2019
['2019-04-10', '0.900', '0.900', '0.880', '0.890', '0.890', '226,000']
8
0.900
9
0.900
10
0.880
11
0.890
12
0.890
13
226,000
14
Apr 09, 2019
['2019-04-09', '0.900', '0.920', '0.900', '0.900', '0.900', '110,000']
15
0.900
16
0.920
17
0.900
18
0.900
19
0.900
20
110,000
21
Apr 08, 2019
['2019-04-08', '0.900', '0.900', '0.880', '0.890', '0.890', '112,000']
22
0.900
23
0.900
24
0.880
25
0.890
26
0.890
27
112,000
28
Apr 04, 2019
['2019-04-04', '0.900', '0.900', '0.870', '0.900', '0.900', '32,000']
29
0.900
30
0.900
31
0.870
32
0.900
33
0.900
34
32,000
35
Apr 03, 2019
['2019-04-03', '0.900', '0.910', '0.900', '0.900', '0.900', '396,000']
36
0.900
37
0.910
38
0.900
39
0.900
40
0.900
41
396,000
42
Apr 02, 2019
['2019-04-02', '0.880', '0.900', '0.870', '0.880', '0.880', '140,000']
43
0.880
44
0.900
45
0.870
46
0.880
47
0.880
48
140,000
49
Apr 01, 2019
['2019-04-01', '0.870', '0.910', '0.870', '0.880', '0.880', '114,000']
50
0.870
51
0.910
52
0.870
53
0.880
54
0.880
55
114,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0043.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.680', '0.690', '0.670', '0.680', '0.680', '2,298,000']
1
0.680
2
0.690
3
0.670
4
0.680
5
0.680
6
2,298,000
7
Apr 10, 2019
['2019-04-10', '0.680', '0.690', '0.670', '0.690', '0.690', '4,848,000']
8
0.680
9
0.690
10
0.670
11
0.690
12
0.690
13
4,848,000
14
Apr 09, 2019
['2019-04-09', '0.670', '0.680', '0.670', '0.680', '0.680', '4,278,000']
15
0.670
16
0.680
17
0.670
18
0.680
19
0.680
20
4,278,000
21
Apr 08, 2019
['2019-04-08', '0.690', '0.690', '0.670', '0.680', '0.680', '10,362,000']
22
0.690
23
0.690
24
0.670
25
0.680
26
0.680
27
10,362,000
28
Apr 04, 2019
['2019-04-04', '0.690', '0.690', '0.680', '0.690', '0.690', '3,590,000']
29
0.690
30
0.690
31
0.680
32
0.690
33
0.690
34
3,590,000
35
Apr 03, 2019
['2019-04-03', '0.700', '0.700', '0.680', '0.690', '0.690', '9,161,989']
36
0.700
37
0.700
38
0.680
39
0.690
40
0.690
41
9,161,989
42
Apr 02, 2019
['2019-04-02', '0.700', '0.700', '0.680', '0.700', '0.700', '5,624,000']
43
0.700
44
0.700
45
0.680
46
0.700
47
0.700
48
5,624,000
49
Apr 01, 2019
['2019-04-01', '0.710', '0.710', '0.690', '0.700', '0.700', '3,648,000']
50
0.710
51
0.710
52
0.690
53
0.700
54
0.700
55
3,648,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0045.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '11.620', '11.740', '11.620', '11.720', '11.720', '257,500']
1
11.620
2
11.740
3
11.620
4
11.720
5
11.720
6
257,500
7
Apr 10, 2019
['2019-04-10', '11.700', '11.800', '11.620', '11.740', '11.740', '92,357']
8
11.700
9
11.800
10
11.620
11
11.740
12
11.740
13
92,357
14
Apr 09, 2019
['2019-04-09', '11.720', '11.820', '11.700', '11.800', '11.800', '470,075']
15
11.720
16
11.820
17
11.700
18
11.800
19
11.800
20
470,075
21
Apr 08, 2019
['2019-04-08', '11.700', '11.780', '11.700', '11.740', '11.740', '27,104']
22
11.700
23
11.780
24
11.700
25
11.740
26
11.740
27
27,104
28
Apr 04, 2019
['2019-04-04', '11.640', '11.780', '11.620', '11.720', '11.720', '633,500']
29
11.640
30
11.780
31
11.620
32
11.720
33
11.720
34
633,500
35
Apr 03, 2019
['2019-04-03', '11.700', '11.740', '11.580', '11.740', '11.740', '356,428']
36
11.700
37
11.740
38
11.580
39
11.740
40
11.740
41
356,428
42
Apr 02, 2019
['2019-04-02', '11.460', '11.620', '11.400', '11.620', '11.620', '241,308']
43
11.460
44
11.620
45
11.400
46
11.620
47
11.620
48
241,308
49
Apr 01, 2019
['2019-04-01', '11.320', '11.540', '11.320', '11.460', '11.460', '305,000']
50
11.320
51
11.540
52
11.320
53
11.460
54
11.460
55
305,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0046.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.150', '4.150', '4.030', '4.050', '4.050', '190,000']
1
4.150
2
4.150
3
4.030
4
4.050
5
4.050
6
190,000
7
Apr 10, 2019
['2019-04-10', '3.830', '4.150', '3.800', '4.090', '4.090', '986,000']
8
3.830
9
4.150
10
3.800
11
4.090
12
4.090
13
986,000
14
Apr 09, 2019
['2019-04-09', '3.800', '3.850', '3.800', '3.830', '3.830', '112,000']
15
3.800
16
3.850
17
3.800
18
3.830
19
3.830
20
112,000
21
Apr 08, 2019
['2019-04-08', '3.770', '3.800', '3.770', '3.800', '3.800', '126,839']
22
3.770
23
3.800
24
3.770
25
3.800
26
3.800
27
126,839
28
Apr 04, 2019
['2019-04-04', '3.780', '3.790', '3.770', '3.770', '3.770', '50,000']
29
3.780
30
3.790
31
3.770
32
3.770
33
3.770
34
50,000
35
Apr 03, 2019
['2019-04-03', '3.770', '3.790', '3.750', '3.770', '3.770', '74,000']
36
3.770
37
3.790
38
3.750
39
3.770
40
3.770
41
74,000
42
Apr 02, 2019
['2019-04-02', '3.790', '3.800', '3.680', '3.760', '3.760', '380,000']
43
3.790
44
3.800
45
3.680
46
3.760
47
3.760
48
380,000
49
Apr 01, 2019
['2019-04-01', '3.720', '3.800', '3.650', '3.770', '3.770', '996,000']
50
3.720
51
3.800
52
3.650
53
3.770
54
3.770
55
996,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0047.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.146', '0.148', '0.145', '0.145', '0.145', '732,000']
1
0.146
2
0.148
3
0.145
4
0.145
5
0.145
6
732,000
7
Apr 10, 2019
['2019-04-10', '0.148', '0.148', '0.147', '0.147', '0.147', '228,000']
8
0.148
9
0.148
10
0.147
11
0.147
12
0.147
13
228,000
14
Apr 09, 2019
['2019-04-09', '0.149', '0.149', '0.148', '0.149', '0.149', '536,000']
15
0.149
16
0.149
17
0.148
18
0.149
19
0.149
20
536,000
21
Apr 08, 2019
['2019-04-08', '0.148', '0.150', '0.146', '0.147', '0.147', '1,824,000']
22
0.148
23
0.150
24
0.146
25
0.147
26
0.147
27
1,824,000
28
Apr 04, 2019
['2019-04-04', '0.142', '0.152', '0.141', '0.150', '0.150', '2,388,000']
29
0.142
30
0.152
31
0.141
32
0.150
33
0.150
34
2,388,000
35
Apr 03, 2019
['2019-04-03', '0.142', '0.142', '0.142', '0.142', '0.142', '416,000']
36
0.142
37
0.142
38
0.142
39
0.142
40
0.142
41
416,000
42
Apr 02, 2019
['2019-04-02', '0.143', '0.143', '0.138', '0.140', '0.140', '8,686,015']
43
0.143
44
0.143
45
0.138
46
0.140
47
0.140
48
8,686,015
49
Apr 01, 2019
['2019-04-01', '0.141', '0.143', '0.136', '0.143', '0.143', '2,556,000']
50
0.141
51
0.143
52
0.136
53
0.143
54
0.143
55
2,556,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0052.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '27.700', '27.700', '27.400', '27.450', '27.450', '60,500']
1
27.700
2
27.700
3
27.400
4
27.450
5
27.450
6
60,500
7
Apr 10, 2019
['2019-04-10', '27.350', '27.600', '27.350', '27.500', '27.500', '88,388']
8
27.350
9
27.600
10
27.350
11
27.500
12
27.500
13
88,388
14
Apr 09, 2019
['2019-04-09', '27.300', '27.350', '27.250', '27.300', '27.300', '59,500']
15
27.300
16
27.350
17
27.250
18
27.300
19
27.300
20
59,500
21
Apr 08, 2019
['2019-04-08', '27.300', '27.600', '27.300', '27.400', '27.400', '66,406']
22
27.300
23
27.600
24
27.300
25
27.400
26
27.400
27
66,406
28
Apr 04, 2019
['2019-04-04', '27.300', '27.500', '27.300', '27.400', '27.400', '32,500']
29
27.300
30
27.500
31
27.300
32
27.400
33
27.400
34
32,500
35
Apr 03, 2019
['2019-04-03', '27.600', '27.600', '27.250', '27.400', '27.400', '72,000']
36
27.600
37
27.600
38
27.250
39
27.400
40
27.400
41
72,000
42
Apr 02, 2019
['2019-04-02', '27.600', '27.600', '27.200', '27.600', '27.600', '145,500']
43
27.600
44
27.600
45
27.200
46
27.600
47
27.600
48
145,500
49
Apr 01, 2019
['2019-04-01', '27.700', '27.800', '27.550', '27.550', '27.550', '79,000']
50
27.700
51
27.800
52
27.550
53
27.550
54
27.550
55
79,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0053.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '111.000', '112.000', '110.500', '112.000', '112.000', '10,000']
1
111.000
2
112.000
3
110.500
4
112.000
5
112.000
6
10,000
7
Apr 10, 2019
['2019-04-10', '111.300', '111.500', '111.100', '111.100', '111.100', '7,000']
8
111.300
9
111.500
10
111.100
11
111.100
12
111.100
13
7,000
14
Apr 09, 2019
['2019-04-09', '112.000', '112.000', '111.300', '111.500', '111.500', '33,000']
15
112.000
16
112.000
17
111.300
18
111.500
19
111.500
20
33,000
21
Apr 08, 2019
['2019-04-08', '112.500', '112.500', '111.600', '112.100', '112.100', '10,600']
22
112.500
23
112.500
24
111.600
25
112.100
26
112.100
27
10,600
28
Apr 04, 2019
['2019-04-04', '113.600', '113.700', '111.600', '112.500', '112.500', '17,000']
29
113.600
30
113.700
31
111.600
32
112.500
33
112.500
34
17,000
35
Apr 03, 2019
['2019-04-03', '113.000', '113.400', '113.000', '113.400', '113.400', '2,000']
36
113.000
37
113.400
38
113.000
39
113.400
40
113.400
41
2,000
42
Apr 02, 2019
['2019-04-02', '114.000', '114.700', '113.000', '113.000', '113.000', '15,775']
43
114.000
44
114.700
45
113.000
46
113.000
47
113.000
48
15,775
49
Apr 01, 2019
['2019-04-01', '115.000', '115.000', '112.500', '112.500', '112.500', '12,686']
50
115.000
51
115.000
52
112.500
53
112.500
54
112.500
55
12,686
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0055.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.365', '0.365', '0.360', '0.360', '0.360', '130,000']
1
0.365
2
0.365
3
0.360
4
0.360
5
0.360
6
130,000
7
Apr 10, 2019
['2019-04-10', '0.390', '0.390', '0.355', '0.375', '0.375', '60,000']
8
0.390
9
0.390
10
0.355
11
0.375
12
0.375
13
60,000
14
Apr 09, 2019
['2019-04-09', '0.360', '0.365', '0.360', '0.365', '0.365', '40,000']
15
0.360
16
0.365
17
0.360
18
0.365
19
0.365
20
40,000
21
Apr 08, 2019
['2019-04-08', '0.380', '0.380', '0.380', '0.380', '0.380', '-']
22
0.380
23
0.380
24
0.380
25
0.380
26
0.380
27
-
28
Apr 04, 2019
['2019-04-04', '0.385', '0.385', '0.380', '0.380', '0.380', '120,000']
29
0.385
30
0.385
31
0.380
32
0.380
33
0.380
34
120,000
35
Apr 03, 2019
['2019-04-03', '0.370', '0.380', '0.370', '0.370', '0.370', '60,000']
36
0.370
37
0.380
38
0.370
39
0.370
40
0.370
41
60,000
42
Apr 02, 2019
['2019-04-02', '0.340', '0.365', '0.340', '0.365', '0.365', '90,000']
43
0.340
44
0.365
45
0.340
46
0.365
47
0.365
48
90,000
49
Apr 01, 2019
['2019-04-01', '0.335', '0.355', '0.335', '0.335', '0.335', '182,000']
50
0.335
51
0.355
52
0.335
53
0.335
54
0.335
55
182,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0057.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.850', '2.850', '2.820', '2.820', '2.820', '20,000']
1
2.850
2
2.850
3
2.820
4
2.820
5
2.820
6
20,000
7
Apr 10, 2019
['2019-04-10', '2.850', '2.850', '2.850', '2.850', '2.850', '-']
8
2.850
9
2.850
10
2.850
11
2.850
12
2.850
13
-
14
Apr 09, 2019
['2019-04-09', '2.830', '2.870', '2.800', '2.830', '2.830', '178,000']
15
2.830
16
2.870
17
2.800
18
2.830
19
2.830
20
178,000
21
Apr 08, 2019
['2019-04-08', '2.830', '2.860', '2.830', '2.830', '2.830', '106,000']
22
2.830
23
2.860
24
2.830
25
2.830
26
2.830
27
106,000
28
Apr 04, 2019
['2019-04-04', '2.820', '2.820', '2.820', '2.820', '2.820', '-']
29
2.820
30
2.820
31
2.820
32
2.820
33
2.820
34
-
35
Apr 03, 2019
['2019-04-03', '2.890', '2.890', '2.820', '2.820', '2.820', '116,000']
36
2.890
37
2.890
38
2.820
39
2.820
40
2.820
41
116,000
42
Apr 02, 2019
['2019-04-02', '2.820', '2.870', '2.820', '2.870', '2.870', '16,000']
43
2.820
44
2.870
45
2.820
46
2.870
47
2.870
48
16,000
49
Apr 01, 2019
['2019-04-01', '2.820', '2.820', '2.800', '2.820', '2.820', '164,000']
50
2.820
51
2.820
52
2.800
53
2.820
54
2.820
55
164,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0058.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.172', '0.172', '0.170', '0.172', '0.172', '262,000']
1
0.172
2
0.172
3
0.170
4
0.172
5
0.172
6
262,000
7
Apr 10, 2019
['2019-04-10', '0.176', '0.176', '0.176', '0.176', '0.176', '-']
8
0.176
9
0.176
10
0.176
11
0.176
12
0.176
13
-
14
Apr 09, 2019
['2019-04-09', '0.172', '0.178', '0.171', '0.173', '0.173', '614,000']
15
0.172
16
0.178
17
0.171
18
0.173
19
0.173
20
614,000
21
Apr 08, 2019
['2019-04-08', '0.169', '0.171', '0.169', '0.170', '0.170', '662,000']
22
0.169
23
0.171
24
0.169
25
0.170
26
0.170
27
662,000
28
Apr 04, 2019
['2019-04-04', '0.171', '0.171', '0.170', '0.171', '0.171', '120,000']
29
0.171
30
0.171
31
0.170
32
0.171
33
0.171
34
120,000
35
Apr 03, 2019
['2019-04-03', '0.171', '0.180', '0.171', '0.180', '0.180', '536,000']
36
0.171
37
0.180
38
0.171
39
0.180
40
0.180
41
536,000
42
Apr 02, 2019
['2019-04-02', '0.173', '0.173', '0.173', '0.173', '0.173', '-']
43
0.173
44
0.173
45
0.173
46
0.173
47
0.173
48
-
49
Apr 01, 2019
['2019-04-01', '0.170', '0.173', '0.170', '0.173', '0.173', '1,430,000']
50
0.170
51
0.173
52
0.170
53
0.173
54
0.173
55
1,430,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0059.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.150', '1.220', '1.150', '1.200', '1.200', '7,862,000']
1
1.150
2
1.220
3
1.150
4
1.200
5
1.200
6
7,862,000
7
Apr 10, 2019
['2019-04-10', '1.150', '1.150', '1.130', '1.150', '1.150', '4,746,018']
8
1.150
9
1.150
10
1.130
11
1.150
12
1.150
13
4,746,018
14
Apr 09, 2019
['2019-04-09', '1.140', '1.170', '1.140', '1.150', '1.150', '4,414,000']
15
1.140
16
1.170
17
1.140
18
1.150
19
1.150
20
4,414,000
21
Apr 08, 2019
['2019-04-08', '1.140', '1.150', '1.130', '1.150', '1.150', '4,506,000']
22
1.140
23
1.150
24
1.130
25
1.150
26
1.150
27
4,506,000
28
Apr 04, 2019
['2019-04-04', '1.140', '1.160', '1.130', '1.130', '1.130', '4,452,000']
29
1.140
30
1.160
31
1.130
32
1.130
33
1.130
34
4,452,000
35
Apr 03, 2019
['2019-04-03', '1.120', '1.150', '1.120', '1.140', '1.140', '5,920,000']
36
1.120
37
1.150
38
1.120
39
1.140
40
1.140
41
5,920,000
42
Apr 02, 2019
['2019-04-02', '1.120', '1.130', '1.110', '1.120', '1.120', '8,380,096']
43
1.120
44
1.130
45
1.110
46
1.120
47
1.120
48
8,380,096
49
Apr 01, 2019
['2019-04-01', '1.130', '1.150', '1.120', '1.120', '1.120', '5,208,000']
50
1.130
51
1.150
52
1.120
53
1.120
54
1.120
55
5,208,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0061.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.043', '0.043', '0.042', '0.042', '0.042', '4,220,000']
1
0.043
2
0.043
3
0.042
4
0.042
5
0.042
6
4,220,000
7
Apr 10, 2019
['2019-04-10', '0.044', '0.044', '0.042', '0.043', '0.043', '1,460,000']
8
0.044
9
0.044
10
0.042
11
0.043
12
0.043
13
1,460,000
14
Apr 09, 2019
['2019-04-09', '0.043', '0.044', '0.042', '0.043', '0.043', '3,550,000']
15
0.043
16
0.044
17
0.042
18
0.043
19
0.043
20
3,550,000
21
Apr 08, 2019
['2019-04-08', '0.043', '0.043', '0.041', '0.043', '0.043', '2,365,000']
22
0.043
23
0.043
24
0.041
25
0.043
26
0.043
27
2,365,000
28
Apr 04, 2019
['2019-04-04', '0.043', '0.043', '0.040', '0.043', '0.043', '560,000']
29
0.043
30
0.043
31
0.040
32
0.043
33
0.043
34
560,000
35
Apr 03, 2019
['2019-04-03', '0.044', '0.044', '0.041', '0.043', '0.043', '1,556,500']
36
0.044
37
0.044
38
0.041
39
0.043
40
0.043
41
1,556,500
42
Apr 02, 2019
['2019-04-02', '0.041', '0.042', '0.040', '0.040', '0.040', '7,826,500']
43
0.041
44
0.042
45
0.040
46
0.040
47
0.040
48
7,826,500
49
Apr 01, 2019
['2019-04-01', '0.040', '0.042', '0.040', '0.041', '0.041', '5,940,000']
50
0.040
51
0.042
52
0.040
53
0.041
54
0.041
55
5,940,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0062.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '23.850', '24.100', '23.850', '24.000', '24.000', '256,800']
1
23.850
2
24.100
3
23.850
4
24.000
5
24.000
6
256,800
7
Apr 10, 2019
['2019-04-10', '23.850', '23.850', '23.750', '23.750', '23.750', '35,833']
8
23.850
9
23.850
10
23.750
11
23.750
12
23.750
13
35,833
14
Apr 09, 2019
['2019-04-09', '23.850', '23.950', '23.650', '23.850', '23.850', '88,955']
15
23.850
16
23.950
17
23.650
18
23.850
19
23.850
20
88,955
21
Apr 08, 2019
['2019-04-08', '23.700', '23.800', '23.600', '23.700', '23.700', '38,400']
22
23.700
23
23.800
24
23.600
25
23.700
26
23.700
27
38,400
28
Apr 04, 2019
['2019-04-04', '23.800', '23.800', '23.600', '23.650', '23.650', '64,400']
29
23.800
30
23.800
31
23.600
32
23.650
33
23.650
34
64,400
35
Apr 03, 2019
['2019-04-03', '23.600', '23.800', '23.600', '23.800', '23.800', '66,800']
36
23.600
37
23.800
38
23.600
39
23.800
40
23.800
41
66,800
42
Apr 02, 2019
['2019-04-02', '23.700', '23.700', '23.550', '23.650', '23.650', '93,200']
43
23.700
44
23.700
45
23.550
46
23.650
47
23.650
48
93,200
49
Apr 01, 2019
['2019-04-01', '23.650', '23.950', '23.550', '23.750', '23.750', '121,611']
50
23.650
51
23.950
52
23.550
53
23.750
54
23.750
55
121,611
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0063.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.208', '0.220', '0.208', '0.220', '0.220', '51,000']
1
0.208
2
0.220
3
0.208
4
0.220
5
0.220
6
51,000
7
Apr 10, 2019
['2019-04-10', '0.210', '0.214', '0.209', '0.210', '0.210', '598,000']
8
0.210
9
0.214
10
0.209
11
0.210
12
0.210
13
598,000
14
Apr 09, 2019
['2019-04-09', '0.218', '0.230', '0.217', '0.230', '0.230', '775,000']
15
0.218
16
0.230
17
0.217
18
0.230
19
0.230
20
775,000
21
Apr 08, 2019
['2019-04-08', '0.218', '0.218', '0.218', '0.218', '0.218', '-']
22
0.218
23
0.218
24
0.218
25
0.218
26
0.218
27
-
28
Apr 04, 2019
['2019-04-04', '0.218', '0.218', '0.218', '0.218', '0.218', '-']
29
0.218
30
0.218
31
0.218
32
0.218
33
0.218
34
-
35
Apr 03, 2019
['2019-04-03', '0.218', '0.218', '0.218', '0.218', '0.218', '-']
36
0.218
37
0.218
38
0.218
39
0.218
40
0.218
41
-
42
Apr 02, 2019
['2019-04-02', '0.218', '0.218', '0.218', '0.218', '0.218', '-']
43
0.218
44
0.218
45
0.218
46
0.218
47
0.218
48
-
49
Apr 01, 2019
['2019-04-01', '0.212', '0.220', '0.212', '0.218', '0.218', '439,000']
50
0.212
51
0.220
52
0.212
53
0.218
54
0.218
55
439,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0065.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.460', '0.460', '0.460', '0.460', '0.460', '198,400']
1
0.460
2
0.460
3
0.460
4
0.460
5
0.460
6
198,400
7
Apr 10, 2019
['2019-04-10', '0.470', '0.470', '0.470', '0.470', '0.470', '-']
8
0.470
9
0.470
10
0.470
11
0.470
12
0.470
13
-
14
Apr 09, 2019
['2019-04-09', '0.465', '0.465', '0.460', '0.460', '0.460', '167,553']
15
0.465
16
0.465
17
0.460
18
0.460
19
0.460
20
167,553
21
Apr 08, 2019
['2019-04-08', '0.470', '0.470', '0.465', '0.465', '0.465', '119,177']
22
0.470
23
0.470
24
0.465
25
0.465
26
0.465
27
119,177
28
Apr 04, 2019
['2019-04-04', '0.460', '0.475', '0.460', '0.475', '0.475', '23,924']
29
0.460
30
0.475
31
0.460
32
0.475
33
0.475
34
23,924
35
Apr 03, 2019
['2019-04-03', '0.465', '0.465', '0.460', '0.465', '0.465', '174,400']
36
0.465
37
0.465
38
0.460
39
0.465
40
0.465
41
174,400
42
Apr 02, 2019
['2019-04-02', '0.480', '0.480', '0.480', '0.480', '0.480', '-']
43
0.480
44
0.480
45
0.480
46
0.480
47
0.480
48
-
49
Apr 01, 2019
['2019-04-01', '0.480', '0.485', '0.480', '0.480', '0.480', '220,000']
50
0.480
51
0.485
52
0.480
53
0.480
54
0.480
55
220,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0069.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '11.480', '11.620', '11.140', '11.200', '11.200', '6,879,648']
1
11.480
2
11.620
3
11.140
4
11.200
5
11.200
6
6,879,648
7
Apr 10, 2019
['2019-04-10', '11.640', '11.780', '11.380', '11.440', '11.440', '4,122,000']
8
11.640
9
11.780
10
11.380
11
11.440
12
11.440
13
4,122,000
14
Apr 09, 2019
['2019-04-09', '11.860', '11.960', '11.680', '11.780', '11.780', '1,785,018']
15
11.860
16
11.960
17
11.680
18
11.780
19
11.780
20
1,785,018
21
Apr 08, 2019
['2019-04-08', '12.000', '12.120', '11.820', '11.860', '11.860', '4,308,000']
22
12.000
23
12.120
24
11.820
25
11.860
26
11.860
27
4,308,000
28
Apr 04, 2019
['2019-04-04', '11.860', '11.860', '11.660', '11.840', '11.840', '4,154,000']
29
11.860
30
11.860
31
11.660
32
11.840
33
11.840
34
4,154,000
35
Apr 03, 2019
['2019-04-03', '11.800', '11.840', '11.680', '11.840', '11.840', '2,389,857']
36
11.800
37
11.840
38
11.680
39
11.840
40
11.840
41
2,389,857
42
Apr 02, 2019
['2019-04-02', '11.500', '11.900', '11.460', '11.800', '11.800', '5,744,817']
43
11.500
44
11.900
45
11.460
46
11.800
47
11.800
48
5,744,817
49
Apr 01, 2019
['2019-04-01', '11.280', '11.680', '11.160', '11.560', '11.560', '6,033,810']
50
11.280
51
11.680
52
11.160
53
11.560
54
11.560
55
6,033,810
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0071.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '17.100', '17.120', '16.800', '16.800', '16.800', '79,960']
1
17.100
2
17.120
3
16.800
4
16.800
5
16.800
6
79,960
7
Apr 10, 2019
['2019-04-10', '17.000', '17.100', '16.900', '17.080', '17.080', '49,000']
8
17.000
9
17.100
10
16.900
11
17.080
12
17.080
13
49,000
14
Apr 09, 2019
['2019-04-09', '16.940', '17.020', '16.940', '16.980', '16.980', '28,800']
15
16.940
16
17.020
17
16.940
18
16.980
19
16.980
20
28,800
21
Apr 08, 2019
['2019-04-08', '17.020', '17.040', '16.940', '16.940', '16.940', '83,000']
22
17.020
23
17.040
24
16.940
25
16.940
26
16.940
27
83,000
28
Apr 04, 2019
['2019-04-04', '17.040', '17.160', '16.960', '17.080', '17.080', '122,000']
29
17.040
30
17.160
31
16.960
32
17.080
33
17.080
34
122,000
35
Apr 03, 2019
['2019-04-03', '17.000', '17.000', '16.920', '16.980', '16.980', '26,000']
36
17.000
37
17.000
38
16.920
39
16.980
40
16.980
41
26,000
42
Apr 02, 2019
['2019-04-02', '17.080', '17.080', '16.960', '17.000', '17.000', '110,000']
43
17.080
44
17.080
45
16.960
46
17.000
47
17.000
48
110,000
49
Apr 01, 2019
['2019-04-01', '16.960', '17.060', '16.900', '17.040', '17.040', '202,000']
50
16.960
51
17.060
52
16.900
53
17.040
54
17.040
55
202,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0072.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.365', '0.365', '0.365', '0.365', '0.365', '62,000']
1
0.365
2
0.365
3
0.365
4
0.365
5
0.365
6
62,000
7
Apr 10, 2019
['2019-04-10', '0.370', '0.370', '0.370', '0.370', '0.370', '34,000']
8
0.370
9
0.370
10
0.370
11
0.370
12
0.370
13
34,000
14
Apr 09, 2019
['2019-04-09', '0.375', '0.375', '0.350', '0.350', '0.350', '50,000']
15
0.375
16
0.375
17
0.350
18
0.350
19
0.350
20
50,000
21
Apr 08, 2019
['2019-04-08', '0.370', '0.370', '0.370', '0.370', '0.370', '10,000']
22
0.370
23
0.370
24
0.370
25
0.370
26
0.370
27
10,000
28
Apr 04, 2019
['2019-04-04', '0.370', '0.375', '0.370', '0.375', '0.375', '10,000']
29
0.370
30
0.375
31
0.370
32
0.375
33
0.375
34
10,000
35
Apr 03, 2019
['2019-04-03', '0.375', '0.375', '0.375', '0.375', '0.375', '-']
36
0.375
37
0.375
38
0.375
39
0.375
40
0.375
41
-
42
Apr 02, 2019
['2019-04-02', '0.375', '0.375', '0.375', '0.375', '0.375', '-']
43
0.375
44
0.375
45
0.375
46
0.375
47
0.375
48
-
49
Apr 01, 2019
['2019-04-01', '0.375', '0.375', '0.375', '0.375', '0.375', '-']
50
0.375
51
0.375
52
0.375
53
0.375
54
0.375
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
No record
0
0075.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.370', '2.370', '2.360', '2.360', '2.360', '27,532']
1
2.370
2
2.370
3
2.360
4
2.360
5
2.360
6
27,532
7
Apr 10, 2019
['2019-04-10', '2.360', '2.370', '2.360', '2.360', '2.360', '195,546']
8
2.360
9
2.370
10
2.360
11
2.360
12
2.360
13
195,546
14
Apr 09, 2019
['2019-04-09', '2.370', '2.500', '2.360', '2.360', '2.360', '216,350']
15
2.370
16
2.500
17
2.360
18
2.360
19
2.360
20
216,350
21
Apr 08, 2019
['2019-04-08', '2.340', '2.370', '2.340', '2.370', '2.370', '81,977']
22
2.340
23
2.370
24
2.340
25
2.370
26
2.370
27
81,977
28
Apr 04, 2019
['2019-04-04', '2.360', '2.360', '2.360', '2.360', '2.360', '46,302']
29
2.360
30
2.360
31
2.360
32
2.360
33
2.360
34
46,302
35
Apr 03, 2019
['2019-04-03', '2.360', '2.450', '2.360', '2.360', '2.360', '96,317']
36
2.360
37
2.450
38
2.360
39
2.360
40
2.360
41
96,317
42
Apr 02, 2019
['2019-04-02', '2.360', '2.360', '2.360', '2.360', '2.360', '122,851']
43
2.360
44
2.360
45
2.360
46
2.360
47
2.360
48
122,851
49
Apr 01, 2019
['2019-04-01', '2.360', '2.370', '2.360', '2.360', '2.360', '292,478']
50
2.360
51
2.370
52
2.360
53
2.360
54
2.360
55
292,478
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0078.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.940', '4.970', '4.880', '4.950', '4.950', '242,000']
1
4.940
2
4.970
3
4.880
4
4.950
5
4.950
6
242,000
7
Apr 10, 2019
['2019-04-10', '4.970', '4.970', '4.930', '4.970', '4.970', '178,000']
8
4.970
9
4.970
10
4.930
11
4.970
12
4.970
13
178,000
14
Apr 09, 2019
['2019-04-09', '4.930', '4.960', '4.910', '4.940', '4.940', '390,000']
15
4.930
16
4.960
17
4.910
18
4.940
19
4.940
20
390,000
21
Apr 08, 2019
['2019-04-08', '4.940', '5.040', '4.900', '4.960', '4.960', '484,400']
22
4.940
23
5.040
24
4.900
25
4.960
26
4.960
27
484,400
28
Apr 04, 2019
['2019-04-04', '4.950', '4.990', '4.940', '4.960', '4.960', '268,000']
29
4.950
30
4.990
31
4.940
32
4.960
33
4.960
34
268,000
35
Apr 03, 2019
['2019-04-03', '4.970', '5.000', '4.950', '4.960', '4.960', '211,000']
36
4.970
37
5.000
38
4.950
39
4.960
40
4.960
41
211,000
42
Apr 02, 2019
['2019-04-02', '4.930', '5.090', '4.930', '5.000', '5.000', '328,759']
43
4.930
44
5.090
45
4.930
46
5.000
47
5.000
48
328,759
49
Apr 01, 2019
['2019-04-01', '4.940', '5.040', '4.930', '4.950', '4.950', '259,000']
50
4.940
51
5.040
52
4.930
53
4.950
54
4.950
55
259,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0079.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.385', '0.385', '0.385', '0.385', '0.385', '-']
1
0.385
2
0.385
3
0.385
4
0.385
5
0.385
6
-
7
Apr 10, 2019
['2019-04-10', '0.385', '0.385', '0.385', '0.385', '0.385', '-']
8
0.385
9
0.385
10
0.385
11
0.385
12
0.385
13
-
14
Apr 09, 2019
['2019-04-09', '0.385', '0.385', '0.385', '0.385', '0.385', '56,000']
15
0.385
16
0.385
17
0.385
18
0.385
19
0.385
20
56,000
21
Apr 08, 2019
['2019-04-08', '0.400', '0.400', '0.400', '0.400', '0.400', '-']
22
0.400
23
0.400
24
0.400
25
0.400
26
0.400
27
-
28
Apr 04, 2019
['2019-04-04', '0.385', '0.385', '0.385', '0.400', '0.400', '7,000']
29
0.385
30
0.385
31
0.385
32
0.400
33
0.400
34
7,000
35
Apr 03, 2019
['2019-04-03', '0.385', '0.385', '0.385', '0.385', '0.385', '-']
36
0.385
37
0.385
38
0.385
39
0.385
40
0.385
41
-
42
Apr 02, 2019
['2019-04-02', '0.385', '0.385', '0.385', '0.385', '0.385', '-']
43
0.385
44
0.385
45
0.385
46
0.385
47
0.385
48
-
49
Apr 01, 2019
['2019-04-01', '0.385', '0.385', '0.385', '0.385', '0.385', '-']
50
0.385
51
0.385
52
0.385
53
0.385
54
0.385
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0080.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.100', '0.100', '0.095', '0.095', '0.095', '26,780,000']
1
0.100
2
0.100
3
0.095
4
0.095
5
0.095
6
26,780,000
7
Apr 10, 2019
['2019-04-10', '0.100', '0.100', '0.100', '0.100', '0.100', '93,980,000']
8
0.100
9
0.100
10
0.100
11
0.100
12
0.100
13
93,980,000
14
Apr 09, 2019
['2019-04-09', '0.099', '0.099', '0.099', '0.099', '0.099', '-']
15
0.099
16
0.099
17
0.099
18
0.099
19
0.099
20
-
21
Apr 08, 2019
['2019-04-08', '0.100', '0.100', '0.100', '0.100', '0.100', '1,000,000']
22
0.100
23
0.100
24
0.100
25
0.100
26
0.100
27
1,000,000
28
Apr 04, 2019
['2019-04-04', '0.085', '0.100', '0.080', '0.100', '0.100', '1,200,000']
29
0.085
30
0.100
31
0.080
32
0.100
33
0.100
34
1,200,000
35
Apr 03, 2019
['2019-04-03', '0.091', '0.091', '0.090', '0.091', '0.091', '1,200,000']
36
0.091
37
0.091
38
0.090
39
0.091
40
0.091
41
1,200,000
42
Apr 02, 2019
['2019-04-02', '0.086', '0.094', '0.086', '0.094', '0.094', '80,000']
43
0.086
44
0.094
45
0.086
46
0.094
47
0.094
48
80,000
49
Apr 01, 2019
['2019-04-01', '0.098', '0.099', '0.098', '0.099', '0.099', '100,000']
50
0.098
51
0.099
52
0.098
53
0.099
54
0.099
55
100,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0081.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.480', '4.520', '4.370', '4.470', '4.470', '6,788,542']
1
4.480
2
4.520
3
4.370
4
4.470
5
4.470
6
6,788,542
7
Apr 10, 2019
['2019-04-10', '4.500', '4.600', '4.450', '4.470', '4.470', '7,325,753']
8
4.500
9
4.600
10
4.450
11
4.470
12
4.470
13
7,325,753
14
Apr 09, 2019
['2019-04-09', '4.400', '4.600', '4.400', '4.560', '4.560', '10,536,230']
15
4.400
16
4.600
17
4.400
18
4.560
19
4.560
20
10,536,230
21
Apr 08, 2019
['2019-04-08', '4.450', '4.480', '4.310', '4.420', '4.420', '9,376,441']
22
4.450
23
4.480
24
4.310
25
4.420
26
4.420
27
9,376,441
28
Apr 04, 2019
['2019-04-04', '4.560', '4.620', '4.350', '4.410', '4.410', '21,318,422']
29
4.560
30
4.620
31
4.350
32
4.410
33
4.410
34
21,318,422
35
Apr 03, 2019
['2019-04-03', '4.450', '4.680', '4.440', '4.570', '4.570', '16,624,231']
36
4.450
37
4.680
38
4.440
39
4.570
40
4.570
41
16,624,231
42
Apr 02, 2019
['2019-04-02', '4.400', '4.470', '4.340', '4.440', '4.440', '19,302,264']
43
4.400
44
4.470
45
4.340
46
4.440
47
4.440
48
19,302,264
49
Apr 01, 2019
['2019-04-01', '4.280', '4.360', '4.260', '4.340', '4.340', '17,942,500']
50
4.280
51
4.360
52
4.260
53
4.340
54
4.340
55
17,942,500
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
No record
0
0083.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '14.620', '14.660', '14.400', '14.440', '14.440', '4,002,932']
1
14.620
2
14.660
3
14.400
4
14.440
5
14.440
6
4,002,932
7
Apr 10, 2019
['2019-04-10', '14.660', '14.840', '14.500', '14.580', '14.580', '6,030,023']
8
14.660
9
14.840
10
14.500
11
14.580
12
14.580
13
6,030,023
14
Apr 09, 2019
['2019-04-09', '14.620', '14.760', '14.520', '14.620', '14.620', '4,099,726']
15
14.620
16
14.760
17
14.520
18
14.620
19
14.620
20
4,099,726
21
Apr 08, 2019
['2019-04-08', '15.020', '15.040', '14.540', '14.660', '14.660', '5,425,658']
22
15.020
23
15.040
24
14.540
25
14.660
26
14.660
27
5,425,658
28
Apr 04, 2019
['2019-04-04', '15.040', '15.060', '14.680', '14.920', '14.920', '4,834,930']
29
15.040
30
15.060
31
14.680
32
14.920
33
14.920
34
4,834,930
35
Apr 03, 2019
['2019-04-03', '15.120', '15.240', '14.920', '15.000', '15.000', '7,296,911']
36
15.120
37
15.240
38
14.920
39
15.000
40
15.000
41
7,296,911
42
Apr 02, 2019
['2019-04-02', '15.180', '15.360', '15.040', '15.220', '15.220', '6,484,263']
43
15.180
44
15.360
45
15.040
46
15.220
47
15.220
48
6,484,263
49
Apr 01, 2019
['2019-04-01', '15.180', '15.480', '15.020', '15.480', '15.480', '6,523,531']
50
15.180
51
15.480
52
15.020
53
15.480
54
15.480
55
6,523,531
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0084.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.233', '0.249', '0.233', '0.236', '0.236', '282,000']
1
0.233
2
0.249
3
0.233
4
0.236
5
0.236
6
282,000
7
Apr 10, 2019
['2019-04-10', '0.236', '0.244', '0.232', '0.232', '0.232', '2,223,126']
8
0.236
9
0.244
10
0.232
11
0.232
12
0.232
13
2,223,126
14
Apr 09, 2019
['2019-04-09', '0.245', '0.247', '0.234', '0.236', '0.236', '3,753,000']
15
0.245
16
0.247
17
0.234
18
0.236
19
0.236
20
3,753,000
21
Apr 08, 2019
['2019-04-08', '0.245', '0.250', '0.245', '0.250', '0.250', '82,000']
22
0.245
23
0.250
24
0.245
25
0.250
26
0.250
27
82,000
28
Apr 04, 2019
['2019-04-04', '0.243', '0.255', '0.243', '0.245', '0.245', '377,000']
29
0.243
30
0.255
31
0.243
32
0.245
33
0.245
34
377,000
35
Apr 03, 2019
['2019-04-03', '0.250', '0.250', '0.244', '0.250', '0.250', '1,400,000']
36
0.250
37
0.250
38
0.244
39
0.250
40
0.250
41
1,400,000
42
Apr 02, 2019
['2019-04-02', '0.250', '0.250', '0.245', '0.250', '0.250', '1,516,000']
43
0.250
44
0.250
45
0.245
46
0.250
47
0.250
48
1,516,000
49
Apr 01, 2019
['2019-04-01', '0.250', '0.250', '0.250', '0.250', '0.250', '55,000']
50
0.250
51
0.250
52
0.250
53
0.250
54
0.250
55
55,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0085.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.800', '0.820', '0.790', '0.800', '0.800', '536,000']
1
0.800
2
0.820
3
0.790
4
0.800
5
0.800
6
536,000
7
Apr 10, 2019
['2019-04-10', '0.790', '0.810', '0.790', '0.810', '0.810', '2,058,000']
8
0.790
9
0.810
10
0.790
11
0.810
12
0.810
13
2,058,000
14
Apr 09, 2019
['2019-04-09', '0.800', '0.820', '0.790', '0.800', '0.800', '1,698,000']
15
0.800
16
0.820
17
0.790
18
0.800
19
0.800
20
1,698,000
21
Apr 08, 2019
['2019-04-08', '0.800', '0.800', '0.790', '0.800', '0.800', '686,000']
22
0.800
23
0.800
24
0.790
25
0.800
26
0.800
27
686,000
28
Apr 04, 2019
['2019-04-04', '0.800', '0.820', '0.790', '0.790', '0.790', '1,018,000']
29
0.800
30
0.820
31
0.790
32
0.790
33
0.790
34
1,018,000
35
Apr 03, 2019
['2019-04-03', '0.800', '0.820', '0.790', '0.810', '0.810', '1,303,750']
36
0.800
37
0.820
38
0.790
39
0.810
40
0.810
41
1,303,750
42
Apr 02, 2019
['2019-04-02', '0.770', '0.790', '0.770', '0.780', '0.780', '408,000']
43
0.770
44
0.790
45
0.770
46
0.780
47
0.780
48
408,000
49
Apr 01, 2019
['2019-04-01', '0.780', '0.780', '0.760', '0.760', '0.760', '1,402,000']
50
0.780
51
0.780
52
0.760
53
0.760
54
0.760
55
1,402,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0086.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.020', '4.020', '3.940', '3.950', '3.950', '430,004']
1
4.020
2
4.020
3
3.940
4
3.950
5
3.950
6
430,004
7
Apr 10, 2019
['2019-04-10', '3.980', '4.000', '3.950', '4.000', '4.000', '777,000']
8
3.980
9
4.000
10
3.950
11
4.000
12
4.000
13
777,000
14
Apr 09, 2019
['2019-04-09', '3.950', '3.970', '3.930', '3.950', '3.950', '936,842']
15
3.950
16
3.970
17
3.930
18
3.950
19
3.950
20
936,842
21
Apr 08, 2019
['2019-04-08', '4.020', '4.020', '3.960', '3.960', '3.960', '1,180,253']
22
4.020
23
4.020
24
3.960
25
3.960
26
3.960
27
1,180,253
28
Apr 04, 2019
['2019-04-04', '4.030', '4.050', '3.980', '4.020', '4.020', '741,000']
29
4.030
30
4.050
31
3.980
32
4.020
33
4.020
34
741,000
35
Apr 03, 2019
['2019-04-03', '3.980', '4.040', '3.980', '4.030', '4.030', '1,959,176']
36
3.980
37
4.040
38
3.980
39
4.030
40
4.030
41
1,959,176
42
Apr 02, 2019
['2019-04-02', '3.940', '3.990', '3.940', '3.980', '3.980', '694,000']
43
3.940
44
3.990
45
3.940
46
3.980
47
3.980
48
694,000
49
Apr 01, 2019
['2019-04-01', '3.950', '3.980', '3.910', '3.940', '3.940', '809,000']
50
3.950
51
3.980
52
3.910
53
3.940
54
3.940
55
809,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0088.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '8.630', '8.670', '8.630', '8.660', '8.660', '18,000']
1
8.630
2
8.670
3
8.630
4
8.660
5
8.660
6
18,000
7
Apr 10, 2019
['2019-04-10', '8.630', '8.740', '8.630', '8.720', '8.720', '52,944']
8
8.630
9
8.740
10
8.630
11
8.720
12
8.720
13
52,944
14
Apr 09, 2019
['2019-04-09', '8.690', '8.730', '8.690', '8.730', '8.730', '85,000']
15
8.690
16
8.730
17
8.690
18
8.730
19
8.730
20
85,000
21
Apr 08, 2019
['2019-04-08', '8.700', '8.700', '8.500', '8.670', '8.670', '121,000']
22
8.700
23
8.700
24
8.500
25
8.670
26
8.670
27
121,000
28
Apr 04, 2019
['2019-04-04', '8.620', '8.720', '8.600', '8.720', '8.720', '21,000']
29
8.620
30
8.720
31
8.600
32
8.720
33
8.720
34
21,000
35
Apr 03, 2019
['2019-04-03', '8.600', '8.700', '8.600', '8.710', '8.710', '155,000']
36
8.600
37
8.700
38
8.600
39
8.710
40
8.710
41
155,000
42
Apr 02, 2019
['2019-04-02', '8.620', '8.700', '8.620', '8.630', '8.630', '8,000']
43
8.620
44
8.700
45
8.620
46
8.630
47
8.630
48
8,000
49
Apr 01, 2019
['2019-04-01', '8.750', '8.750', '8.640', '8.700', '8.700', '65,000']
50
8.750
51
8.750
52
8.640
53
8.700
54
8.700
55
65,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0092.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.234', '0.239', '0.229', '0.236', '0.236', '606,040']
1
0.234
2
0.239
3
0.229
4
0.236
5
0.236
6
606,040
7
Apr 10, 2019
['2019-04-10', '0.240', '0.240', '0.240', '0.240', '0.240', '-']
8
0.240
9
0.240
10
0.240
11
0.240
12
0.240
13
-
14
Apr 09, 2019
['2019-04-09', '0.240', '0.240', '0.240', '0.240', '0.240', '-']
15
0.240
16
0.240
17
0.240
18
0.240
19
0.240
20
-
21
Apr 08, 2019
['2019-04-08', '0.236', '0.242', '0.236', '0.240', '0.240', '1,998,000']
22
0.236
23
0.242
24
0.236
25
0.240
26
0.240
27
1,998,000
28
Apr 04, 2019
['2019-04-04', '0.238', '0.238', '0.236', '0.236', '0.236', '63,111']
29
0.238
30
0.238
31
0.236
32
0.236
33
0.236
34
63,111
35
Apr 03, 2019
['2019-04-03', '0.234', '0.240', '0.234', '0.240', '0.240', '136,359']
36
0.234
37
0.240
38
0.234
39
0.240
40
0.240
41
136,359
42
Apr 02, 2019
['2019-04-02', '0.240', '0.240', '0.240', '0.240', '0.240', '30,000']
43
0.240
44
0.240
45
0.240
46
0.240
47
0.240
48
30,000
49
Apr 01, 2019
['2019-04-01', '0.238', '0.240', '0.231', '0.240', '0.240', '337,625']
50
0.238
51
0.240
52
0.231
53
0.240
54
0.240
55
337,625
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0093.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.420', '0.420', '0.400', '0.430', '0.430', '102,000']
1
0.420
2
0.420
3
0.400
4
0.430
5
0.430
6
102,000
7
Apr 10, 2019
['2019-04-10', '0.400', '0.420', '0.380', '0.420', '0.420', '108,000']
8
0.400
9
0.420
10
0.380
11
0.420
12
0.420
13
108,000
14
Apr 09, 2019
['2019-04-09', '0.425', '0.425', '0.425', '0.425', '0.425', '-']
15
0.425
16
0.425
17
0.425
18
0.425
19
0.425
20
-
21
Apr 08, 2019
['2019-04-08', '0.410', '0.460', '0.410', '0.425', '0.425', '168,000']
22
0.410
23
0.460
24
0.410
25
0.425
26
0.425
27
168,000
28
Apr 04, 2019
['2019-04-04', '0.400', '0.405', '0.390', '0.405', '0.405', '42,000']
29
0.400
30
0.405
31
0.390
32
0.405
33
0.405
34
42,000
35
Apr 03, 2019
['2019-04-03', '0.410', '0.410', '0.410', '0.410', '0.410', '-']
36
0.410
37
0.410
38
0.410
39
0.410
40
0.410
41
-
42
Apr 02, 2019
['2019-04-02', '0.405', '0.415', '0.395', '0.395', '0.395', '518,000']
43
0.405
44
0.415
45
0.395
46
0.395
47
0.395
48
518,000
49
Apr 01, 2019
['2019-04-01', '0.390', '0.410', '0.385', '0.395', '0.395', '198,000']
50
0.390
51
0.410
52
0.385
53
0.395
54
0.395
55
198,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0096.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.800', '1.800', '1.800', '1.800', '1.800', '-']
1
1.800
2
1.800
3
1.800
4
1.800
5
1.800
6
-
7
Apr 10, 2019
['2019-04-10', '1.800', '1.800', '1.800', '1.800', '1.800', '-']
8
1.800
9
1.800
10
1.800
11
1.800
12
1.800
13
-
14
Apr 09, 2019
['2019-04-09', '1.800', '1.800', '1.800', '1.800', '1.800', '-']
15
1.800
16
1.800
17
1.800
18
1.800
19
1.800
20
-
21
Apr 08, 2019
['2019-04-08', '1.800', '1.800', '1.800', '1.800', '1.800', '-']
22
1.800
23
1.800
24
1.800
25
1.800
26
1.800
27
-
28
Apr 04, 2019
['2019-04-04', '1.800', '1.800', '1.800', '1.800', '1.800', '-']
29
1.800
30
1.800
31
1.800
32
1.800
33
1.800
34
-
35
Apr 03, 2019
['2019-04-03', '1.800', '1.800', '1.800', '1.800', '1.800', '12,000']
36
1.800
37
1.800
38
1.800
39
1.800
40
1.800
41
12,000
42
Apr 02, 2019
['2019-04-02', '1.800', '1.800', '1.800', '1.800', '1.800', '-']
43
1.800
44
1.800
45
1.800
46
1.800
47
1.800
48
-
49
Apr 01, 2019
['2019-04-01', '1.800', '1.800', '1.800', '1.800', '1.800', '-']
50
1.800
51
1.800
52
1.800
53
1.800
54
1.800
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0098.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '6.070', '6.070', '5.900', '5.900', '5.900', '148,000']
1
6.070
2
6.070
3
5.900
4
5.900
5
5.900
6
148,000
7
Apr 10, 2019
['2019-04-10', '6.200', '6.200', '6.030', '6.040', '6.040', '161,000']
8
6.200
9
6.200
10
6.030
11
6.040
12
6.040
13
161,000
14
Apr 09, 2019
['2019-04-09', '6.290', '6.300', '6.200', '6.200', '6.200', '146,000']
15
6.290
16
6.300
17
6.200
18
6.200
19
6.200
20
146,000
21
Apr 08, 2019
['2019-04-08', '5.790', '6.210', '5.790', '6.210', '6.210', '340,000']
22
5.790
23
6.210
24
5.790
25
6.210
26
6.210
27
340,000
28
Apr 04, 2019
['2019-04-04', '5.620', '5.790', '5.620', '5.790', '5.790', '44,000']
29
5.620
30
5.790
31
5.620
32
5.790
33
5.790
34
44,000
35
Apr 03, 2019
['2019-04-03', '5.670', '5.670', '5.600', '5.670', '5.670', '321,000']
36
5.670
37
5.670
38
5.600
39
5.670
40
5.670
41
321,000
42
Apr 02, 2019
['2019-04-02', '5.690', '5.790', '5.650', '5.660', '5.660', '122,000']
43
5.690
44
5.790
45
5.650
46
5.660
47
5.660
48
122,000
49
Apr 01, 2019
['2019-04-01', '5.650', '5.650', '5.550', '5.650', '5.650', '267,000']
50
5.650
51
5.650
52
5.550
53
5.650
54
5.650
55
267,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
No record
0
0101.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '19.440', '19.460', '18.900', '18.980', '18.980', '2,585,444']
1
19.440
2
19.460
3
18.900
4
18.980
5
18.980
6
2,585,444
7
Apr 10, 2019
['2019-04-10', '19.460', '19.460', '19.200', '19.400', '19.400', '3,591,977']
8
19.460
9
19.460
10
19.200
11
19.400
12
19.400
13
3,591,977
14
Apr 09, 2019
['2019-04-09', '19.640', '19.640', '19.200', '19.440', '19.440', '3,622,257']
15
19.640
16
19.640
17
19.200
18
19.440
19
19.440
20
3,622,257
21
Apr 08, 2019
['2019-04-08', '19.720', '19.720', '19.340', '19.440', '19.440', '3,559,918']
22
19.720
23
19.720
24
19.340
25
19.440
26
19.440
27
3,559,918
28
Apr 04, 2019
['2019-04-04', '19.540', '19.660', '19.380', '19.580', '19.580', '6,634,211']
29
19.540
30
19.660
31
19.380
32
19.580
33
19.580
34
6,634,211
35
Apr 03, 2019
['2019-04-03', '19.560', '19.740', '19.380', '19.740', '19.740', '5,686,577']
36
19.560
37
19.740
38
19.380
39
19.740
40
19.740
41
5,686,577
42
Apr 02, 2019
['2019-04-02', '19.620', '19.880', '19.620', '19.800', '19.800', '17,352,255']
43
19.620
44
19.880
45
19.620
46
19.800
47
19.800
48
17,352,255
49
Apr 01, 2019
['2019-04-01', '19.240', '20.000', '19.120', '19.920', '19.920', '9,712,352']
50
19.240
51
20.000
52
19.120
53
19.920
54
19.920
55
9,712,352
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0102.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.690', '1.690', '1.500', '1.530', '1.530', '19,998,000']
1
1.690
2
1.690
3
1.500
4
1.530
5
1.530
6
19,998,000
7
Apr 10, 2019
['2019-04-10', '1.500', '1.700', '1.480', '1.690', '1.690', '33,236,000']
8
1.500
9
1.700
10
1.480
11
1.690
12
1.690
13
33,236,000
14
Apr 09, 2019
['2019-04-09', '1.510', '1.520', '1.470', '1.500', '1.500', '16,258,000']
15
1.510
16
1.520
17
1.470
18
1.500
19
1.500
20
16,258,000
21
Apr 08, 2019
['2019-04-08', '1.400', '1.500', '1.400', '1.480', '1.480', '15,069,632']
22
1.400
23
1.500
24
1.400
25
1.480
26
1.480
27
15,069,632
28
Apr 04, 2019
['2019-04-04', '1.430', '1.440', '1.360', '1.430', '1.430', '18,160,000']
29
1.430
30
1.440
31
1.360
32
1.430
33
1.430
34
18,160,000
35
Apr 03, 2019
['2019-04-03', '1.320', '1.430', '1.270', '1.410', '1.410', '42,664,000']
36
1.320
37
1.430
38
1.270
39
1.410
40
1.410
41
42,664,000
42
Apr 02, 2019
['2019-04-02', '1.170', '1.330', '1.150', '1.320', '1.320', '34,306,000']
43
1.170
44
1.330
45
1.150
46
1.320
47
1.320
48
34,306,000
49
Apr 01, 2019
['2019-04-01', '1.040', '1.220', '1.040', '1.140', '1.140', '23,892,000']
50
1.040
51
1.220
52
1.040
53
1.140
54
1.140
55
23,892,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0104.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.630', '0.650', '0.620', '0.630', '0.630', '210,000']
1
0.630
2
0.650
3
0.620
4
0.630
5
0.630
6
210,000
7
Apr 10, 2019
['2019-04-10', '0.610', '0.700', '0.610', '0.640', '0.640', '3,925,750']
8
0.610
9
0.700
10
0.610
11
0.640
12
0.640
13
3,925,750
14
Apr 09, 2019
['2019-04-09', '0.610', '0.610', '0.610', '0.610', '0.610', '-']
15
0.610
16
0.610
17
0.610
18
0.610
19
0.610
20
-
21
Apr 08, 2019
['2019-04-08', '0.620', '0.620', '0.620', '0.620', '0.620', '-']
22
0.620
23
0.620
24
0.620
25
0.620
26
0.620
27
-
28
Apr 04, 2019
['2019-04-04', '0.600', '0.610', '0.600', '0.610', '0.610', '42,000']
29
0.600
30
0.610
31
0.600
32
0.610
33
0.610
34
42,000
35
Apr 03, 2019
['2019-04-03', '0.600', '0.600', '0.600', '0.600', '0.600', '-']
36
0.600
37
0.600
38
0.600
39
0.600
40
0.600
41
-
42
Apr 02, 2019
['2019-04-02', '0.610', '0.610', '0.610', '0.610', '0.610', '-']
43
0.610
44
0.610
45
0.610
46
0.610
47
0.610
48
-
49
Apr 01, 2019
['2019-04-01', '0.600', '0.610', '0.580', '0.610', '0.610', '129,140']
50
0.600
51
0.610
52
0.580
53
0.610
54
0.610
55
129,140
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0105.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '23.000', '23.000', '23.000', '23.000', '23.000', '-']
1
23.000
2
23.000
3
23.000
4
23.000
5
23.000
6
-
7
Apr 10, 2019
['2019-04-10', '23.000', '23.000', '23.000', '23.000', '23.000', '26,000']
8
23.000
9
23.000
10
23.000
11
23.000
12
23.000
13
26,000
14
Apr 09, 2019
['2019-04-09', '23.000', '23.000', '23.000', '23.000', '23.000', '-']
15
23.000
16
23.000
17
23.000
18
23.000
19
23.000
20
-
21
Apr 08, 2019
['2019-04-08', '22.800', '22.800', '22.800', '22.800', '22.800', '-']
22
22.800
23
22.800
24
22.800
25
22.800
26
22.800
27
-
28
Apr 04, 2019
['2019-04-04', '23.000', '23.000', '23.000', '23.000', '23.000', '-']
29
23.000
30
23.000
31
23.000
32
23.000
33
23.000
34
-
35
Apr 03, 2019
['2019-04-03', '23.050', '23.050', '23.050', '23.050', '23.050', '-']
36
23.050
37
23.050
38
23.050
39
23.050
40
23.050
41
-
42
Apr 02, 2019
['2019-04-02', '23.000', '23.000', '23.000', '23.050', '23.050', '10,000']
43
23.000
44
23.000
45
23.000
46
23.050
47
23.050
48
10,000
49
Apr 01, 2019
['2019-04-01', '23.000', '23.000', '23.000', '23.000', '23.000', '-']
50
23.000
51
23.000
52
23.000
53
23.000
54
23.000
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0106.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.010', '1.010', '1.000', '1.010', '1.010', '772,000']
1
1.010
2
1.010
3
1.000
4
1.010
5
1.010
6
772,000
7
Apr 10, 2019
['2019-04-10', '1.020', '1.020', '1.000', '1.010', '1.010', '1,696,000']
8
1.020
9
1.020
10
1.000
11
1.010
12
1.010
13
1,696,000
14
Apr 09, 2019
['2019-04-09', '1.030', '1.030', '1.000', '1.030', '1.030', '1,884,000']
15
1.030
16
1.030
17
1.000
18
1.030
19
1.030
20
1,884,000
21
Apr 08, 2019
['2019-04-08', '1.040', '1.040', '1.020', '1.030', '1.030', '1,449,000']
22
1.040
23
1.040
24
1.020
25
1.030
26
1.030
27
1,449,000
28
Apr 04, 2019
['2019-04-04', '1.040', '1.050', '1.020', '1.040', '1.040', '780,000']
29
1.040
30
1.050
31
1.020
32
1.040
33
1.040
34
780,000
35
Apr 03, 2019
['2019-04-03', '1.050', '1.050', '1.020', '1.040', '1.040', '1,640,000']
36
1.050
37
1.050
38
1.020
39
1.040
40
1.040
41
1,640,000
42
Apr 02, 2019
['2019-04-02', '1.040', '1.050', '1.030', '1.050', '1.050', '1,191,200']
43
1.040
44
1.050
45
1.030
46
1.050
47
1.050
48
1,191,200
49
Apr 01, 2019
['2019-04-01', '1.040', '1.060', '1.040', '1.040', '1.040', '2,844,000']
50
1.040
51
1.060
52
1.040
53
1.040
54
1.040
55
2,844,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0107.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.670', '2.680', '2.640', '2.650', '2.650', '1,244,000']
1
2.670
2
2.680
3
2.640
4
2.650
5
2.650
6
1,244,000
7
Apr 10, 2019
['2019-04-10', '2.650', '2.700', '2.630', '2.670', '2.670', '4,978,000']
8
2.650
9
2.700
10
2.630
11
2.670
12
2.670
13
4,978,000
14
Apr 09, 2019
['2019-04-09', '2.630', '2.650', '2.620', '2.650', '2.650', '1,690,000']
15
2.630
16
2.650
17
2.620
18
2.650
19
2.650
20
1,690,000
21
Apr 08, 2019
['2019-04-08', '2.620', '2.640', '2.600', '2.630', '2.630', '3,202,000']
22
2.620
23
2.640
24
2.600
25
2.630
26
2.630
27
3,202,000
28
Apr 04, 2019
['2019-04-04', '2.590', '2.630', '2.580', '2.590', '2.590', '2,130,000']
29
2.590
30
2.630
31
2.580
32
2.590
33
2.590
34
2,130,000
35
Apr 03, 2019
['2019-04-03', '2.590', '2.610', '2.580', '2.600', '2.600', '2,388,000']
36
2.590
37
2.610
38
2.580
39
2.600
40
2.600
41
2,388,000
42
Apr 02, 2019
['2019-04-02', '2.600', '2.620', '2.600', '2.610', '2.610', '1,072,000']
43
2.600
44
2.620
45
2.600
46
2.610
47
2.610
48
1,072,000
49
Apr 01, 2019
['2019-04-01', '2.600', '2.610', '2.580', '2.600', '2.600', '2,596,000']
50
2.600
51
2.610
52
2.580
53
2.600
54
2.600
55
2,596,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0109.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.182', '0.182', '0.182', '0.182', '0.182', '-']
1
0.182
2
0.182
3
0.182
4
0.182
5
0.182
6
-
7
Apr 10, 2019
['2019-04-10', '0.179', '0.179', '0.178', '0.178', '0.178', '345,705']
8
0.179
9
0.179
10
0.178
11
0.178
12
0.178
13
345,705
14
Apr 09, 2019
['2019-04-09', '0.180', '0.182', '0.179', '0.182', '0.182', '1,236,014']
15
0.180
16
0.182
17
0.179
18
0.182
19
0.182
20
1,236,014
21
Apr 08, 2019
['2019-04-08', '0.180', '0.183', '0.179', '0.179', '0.179', '875,705']
22
0.180
23
0.183
24
0.179
25
0.179
26
0.179
27
875,705
28
Apr 04, 2019
['2019-04-04', '0.181', '0.183', '0.180', '0.180', '0.180', '605,705']
29
0.181
30
0.183
31
0.180
32
0.180
33
0.180
34
605,705
35
Apr 03, 2019
['2019-04-03', '0.180', '0.182', '0.179', '0.179', '0.179', '535,705']
36
0.180
37
0.182
38
0.179
39
0.179
40
0.179
41
535,705
42
Apr 02, 2019
['2019-04-02', '0.180', '0.180', '0.180', '0.180', '0.180', '525,775']
43
0.180
44
0.180
45
0.180
46
0.180
47
0.180
48
525,775
49
Apr 01, 2019
['2019-04-01', '0.181', '0.186', '0.179', '0.183', '0.183', '1,085,705']
50
0.181
51
0.186
52
0.179
53
0.183
54
0.183
55
1,085,705
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0110.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.162', '0.162', '0.162', '0.162', '0.162', '-']
1
0.162
2
0.162
3
0.162
4
0.162
5
0.162
6
-
7
Apr 10, 2019
['2019-04-10', '0.162', '0.162', '0.162', '0.162', '0.162', '-']
8
0.162
9
0.162
10
0.162
11
0.162
12
0.162
13
-
14
Apr 09, 2019
['2019-04-09', '0.156', '0.162', '0.156', '0.162', '0.162', '202,000']
15
0.156
16
0.162
17
0.156
18
0.162
19
0.162
20
202,000
21
Apr 08, 2019
['2019-04-08', '0.150', '0.168', '0.150', '0.168', '0.168', '10,000']
22
0.150
23
0.168
24
0.150
25
0.168
26
0.168
27
10,000
28
Apr 04, 2019
['2019-04-04', '0.168', '0.168', '0.168', '0.168', '0.168', '-']
29
0.168
30
0.168
31
0.168
32
0.168
33
0.168
34
-
35
Apr 03, 2019
['2019-04-03', '0.169', '0.169', '0.169', '0.169', '0.169', '-']
36
0.169
37
0.169
38
0.169
39
0.169
40
0.169
41
-
42
Apr 02, 2019
['2019-04-02', '0.161', '0.173', '0.160', '0.173', '0.173', '122,000']
43
0.161
44
0.173
45
0.160
46
0.173
47
0.173
48
122,000
49
Apr 01, 2019
['2019-04-01', '0.151', '0.160', '0.151', '0.160', '0.160', '330,000']
50
0.151
51
0.160
52
0.151
53
0.160
54
0.160
55
330,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0113.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.200', '4.200', '4.160', '4.190', '4.190', '51,000']
1
4.200
2
4.200
3
4.160
4
4.190
5
4.190
6
51,000
7
Apr 10, 2019
['2019-04-10', '4.200', '4.200', '4.100', '4.200', '4.200', '151,000']
8
4.200
9
4.200
10
4.100
11
4.200
12
4.200
13
151,000
14
Apr 09, 2019
['2019-04-09', '4.180', '4.180', '4.180', '4.180', '4.180', '-']
15
4.180
16
4.180
17
4.180
18
4.180
19
4.180
20
-
21
Apr 08, 2019
['2019-04-08', '4.170', '4.180', '4.150', '4.170', '4.170', '325,800']
22
4.170
23
4.180
24
4.150
25
4.170
26
4.170
27
325,800
28
Apr 04, 2019
['2019-04-04', '4.100', '4.180', '4.100', '4.180', '4.180', '105,500']
29
4.100
30
4.180
31
4.100
32
4.180
33
4.180
34
105,500
35
Apr 03, 2019
['2019-04-03', '4.170', '4.170', '4.090', '4.160', '4.160', '147,000']
36
4.170
37
4.170
38
4.090
39
4.160
40
4.160
41
147,000
42
Apr 02, 2019
['2019-04-02', '4.150', '4.180', '4.130', '4.170', '4.170', '209,500']
43
4.150
44
4.180
45
4.130
46
4.170
47
4.170
48
209,500
49
Apr 01, 2019
['2019-04-01', '4.090', '4.150', '4.090', '4.150', '4.150', '127,500']
50
4.090
51
4.150
52
4.090
53
4.150
54
4.150
55
127,500
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0114.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.770', '0.770', '0.770', '0.770', '0.770', '-']
1
0.770
2
0.770
3
0.770
4
0.770
5
0.770
6
-
7
Apr 10, 2019
['2019-04-10', '0.770', '0.770', '0.770', '0.770', '0.770', '-']
8
0.770
9
0.770
10
0.770
11
0.770
12
0.770
13
-
14
Apr 09, 2019
['2019-04-09', '0.850', '0.850', '0.850', '0.850', '0.850', '-']
15
0.850
16
0.850
17
0.850
18
0.850
19
0.850
20
-
21
Apr 08, 2019
['2019-04-08', '0.850', '0.850', '0.850', '0.850', '0.850', '-']
22
0.850
23
0.850
24
0.850
25
0.850
26
0.850
27
-
28
Apr 04, 2019
['2019-04-04', '0.850', '0.850', '0.850', '0.850', '0.850', '-']
29
0.850
30
0.850
31
0.850
32
0.850
33
0.850
34
-
35
Apr 03, 2019
['2019-04-03', '0.860', '0.860', '0.860', '0.860', '0.860', '-']
36
0.860
37
0.860
38
0.860
39
0.860
40
0.860
41
-
42
Apr 02, 2019
['2019-04-02', '0.840', '0.860', '0.840', '0.860', '0.860', '70,000']
43
0.840
44
0.860
45
0.840
46
0.860
47
0.860
48
70,000
49
Apr 01, 2019
['2019-04-01', '0.760', '0.760', '0.760', '0.760', '0.760', '-']
50
0.760
51
0.760
52
0.760
53
0.760
54
0.760
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0116.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '13.600', '13.720', '13.280', '13.400', '13.400', '938,594']
1
13.600
2
13.720
3
13.280
4
13.400
5
13.400
6
938,594
7
Apr 10, 2019
['2019-04-10', '13.520', '13.880', '13.360', '13.800', '13.800', '1,290,000']
8
13.520
9
13.880
10
13.360
11
13.800
12
13.800
13
1,290,000
14
Apr 09, 2019
['2019-04-09', '13.340', '13.840', '13.240', '13.680', '13.680', '950,045']
15
13.340
16
13.840
17
13.240
18
13.680
19
13.680
20
950,045
21
Apr 08, 2019
['2019-04-08', '12.940', '13.500', '12.920', '13.340', '13.340', '1,709,522']
22
12.940
23
13.500
24
12.920
25
13.340
26
13.340
27
1,709,522
28
Apr 04, 2019
['2019-04-04', '13.000', '13.020', '12.620', '12.780', '12.780', '858,000']
29
13.000
30
13.020
31
12.620
32
12.780
33
12.780
34
858,000
35
Apr 03, 2019
['2019-04-03', '12.500', '13.100', '12.460', '12.960', '12.960', '2,007,000']
36
12.500
37
13.100
38
12.460
39
12.960
40
12.960
41
2,007,000
42
Apr 02, 2019
['2019-04-02', '12.360', '12.680', '12.300', '12.600', '12.600', '1,871,000']
43
12.360
44
12.680
45
12.300
46
12.600
47
12.600
48
1,871,000
49
Apr 01, 2019
['2019-04-01', '12.400', '12.400', '12.160', '12.320', '12.320', '1,832,300']
50
12.400
51
12.400
52
12.160
53
12.320
54
12.320
55
1,832,300
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0117.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.980', '0.980', '0.910', '0.940', '0.940', '826,000']
1
0.980
2
0.980
3
0.910
4
0.940
5
0.940
6
826,000
7
Apr 10, 2019
['2019-04-10', '0.930', '0.940', '0.920', '0.940', '0.940', '1,218,000']
8
0.930
9
0.940
10
0.920
11
0.940
12
0.940
13
1,218,000
14
Apr 09, 2019
['2019-04-09', '0.900', '0.940', '0.880', '0.930', '0.930', '2,788,000']
15
0.900
16
0.940
17
0.880
18
0.930
19
0.930
20
2,788,000
21
Apr 08, 2019
['2019-04-08', '0.890', '0.900', '0.870', '0.880', '0.880', '432,000']
22
0.890
23
0.900
24
0.870
25
0.880
26
0.880
27
432,000
28
Apr 04, 2019
['2019-04-04', '0.890', '0.930', '0.830', '0.880', '0.880', '1,700,000']
29
0.890
30
0.930
31
0.830
32
0.880
33
0.880
34
1,700,000
35
Apr 03, 2019
['2019-04-03', '0.890', '0.900', '0.820', '0.880', '0.880', '1,188,000']
36
0.890
37
0.900
38
0.820
39
0.880
40
0.880
41
1,188,000
42
Apr 02, 2019
['2019-04-02', '0.880', '0.930', '0.870', '0.930', '0.930', '550,000']
43
0.880
44
0.930
45
0.870
46
0.930
47
0.930
48
550,000
49
Apr 01, 2019
['2019-04-01', '0.900', '0.900', '0.880', '0.890', '0.890', '898,000']
50
0.900
51
0.900
52
0.880
53
0.890
54
0.890
55
898,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0120.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.430', '1.460', '1.430', '1.440', '1.440', '644,000']
1
1.430
2
1.460
3
1.430
4
1.440
5
1.440
6
644,000
7
Apr 10, 2019
['2019-04-10', '1.470', '1.480', '1.430', '1.460', '1.460', '600,000']
8
1.470
9
1.480
10
1.430
11
1.460
12
1.460
13
600,000
14
Apr 09, 2019
['2019-04-09', '1.480', '1.550', '1.440', '1.470', '1.470', '710,000']
15
1.480
16
1.550
17
1.440
18
1.470
19
1.470
20
710,000
21
Apr 08, 2019
['2019-04-08', '1.490', '1.490', '1.440', '1.450', '1.450', '626,000']
22
1.490
23
1.490
24
1.440
25
1.450
26
1.450
27
626,000
28
Apr 04, 2019
['2019-04-04', '1.520', '1.520', '1.440', '1.490', '1.490', '652,000']
29
1.520
30
1.520
31
1.440
32
1.490
33
1.490
34
652,000
35
Apr 03, 2019
['2019-04-03', '1.460', '1.520', '1.460', '1.500', '1.500', '582,000']
36
1.460
37
1.520
38
1.460
39
1.500
40
1.500
41
582,000
42
Apr 02, 2019
['2019-04-02', '1.480', '1.500', '1.460', '1.470', '1.470', '586,000']
43
1.480
44
1.500
45
1.460
46
1.470
47
1.470
48
586,000
49
Apr 01, 2019
['2019-04-01', '1.480', '1.540', '1.450', '1.480', '1.480', '600,000']
50
1.480
51
1.540
52
1.450
53
1.480
54
1.480
55
600,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0121.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.080', '0.085', '0.080', '0.083', '0.083', '220,000']
1
0.080
2
0.085
3
0.080
4
0.083
5
0.083
6
220,000
7
Apr 10, 2019
['2019-04-10', '0.081', '0.085', '0.081', '0.082', '0.082', '100,000']
8
0.081
9
0.085
10
0.081
11
0.082
12
0.082
13
100,000
14
Apr 09, 2019
['2019-04-09', '0.086', '0.086', '0.086', '0.086', '0.086', '-']
15
0.086
16
0.086
17
0.086
18
0.086
19
0.086
20
-
21
Apr 08, 2019
['2019-04-08', '0.081', '0.086', '0.079', '0.086', '0.086', '130,000']
22
0.081
23
0.086
24
0.079
25
0.086
26
0.086
27
130,000
28
Apr 04, 2019
['2019-04-04', '0.082', '0.085', '0.082', '0.085', '0.085', '360,000']
29
0.082
30
0.085
31
0.082
32
0.085
33
0.085
34
360,000
35
Apr 03, 2019
['2019-04-03', '0.088', '0.088', '0.088', '0.088', '0.088', '-']
36
0.088
37
0.088
38
0.088
39
0.088
40
0.088
41
-
42
Apr 02, 2019
['2019-04-02', '0.088', '0.088', '0.088', '0.088', '0.088', '-']
43
0.088
44
0.088
45
0.088
46
0.088
47
0.088
48
-
49
Apr 01, 2019
['2019-04-01', '0.088', '0.088', '0.088', '0.088', '0.088', '-']
50
0.088
51
0.088
52
0.088
53
0.088
54
0.088
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0123.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.920', '1.930', '1.880', '1.890', '1.890', '27,305,853']
1
1.920
2
1.930
3
1.880
4
1.890
5
1.890
6
27,305,853
7
Apr 10, 2019
['2019-04-10', '1.920', '1.930', '1.890', '1.920', '1.920', '33,345,313']
8
1.920
9
1.930
10
1.890
11
1.920
12
1.920
13
33,345,313
14
Apr 09, 2019
['2019-04-09', '1.910', '1.950', '1.890', '1.920', '1.920', '47,482,937']
15
1.910
16
1.950
17
1.890
18
1.920
19
1.920
20
47,482,937
21
Apr 08, 2019
['2019-04-08', '1.930', '1.940', '1.890', '1.910', '1.910', '28,881,020']
22
1.930
23
1.940
24
1.890
25
1.910
26
1.910
27
28,881,020
28
Apr 04, 2019
['2019-04-04', '1.930', '1.940', '1.900', '1.920', '1.920', '27,831,942']
29
1.930
30
1.940
31
1.900
32
1.920
33
1.920
34
27,831,942
35
Apr 03, 2019
['2019-04-03', '1.930', '1.940', '1.920', '1.940', '1.940', '37,632,707']
36
1.930
37
1.940
38
1.920
39
1.940
40
1.940
41
37,632,707
42
Apr 02, 2019
['2019-04-02', '1.930', '1.930', '1.910', '1.930', '1.930', '26,866,966']
43
1.930
44
1.930
45
1.910
46
1.930
47
1.930
48
26,866,966
49
Apr 01, 2019
['2019-04-01', '1.910', '1.950', '1.900', '1.910', '1.910', '49,871,124']
50
1.910
51
1.950
52
1.900
53
1.910
54
1.910
55
49,871,124
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0125.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.870', '2.870', '2.870', '2.870', '2.870', '-']
1
2.870
2
2.870
3
2.870
4
2.870
5
2.870
6
-
7
Apr 10, 2019
['2019-04-10', '2.810', '2.880', '2.810', '2.880', '2.880', '12,000']
8
2.810
9
2.880
10
2.810
11
2.880
12
2.880
13
12,000
14
Apr 09, 2019
['2019-04-09', '2.860', '2.860', '2.800', '2.800', '2.800', '22,000']
15
2.860
16
2.860
17
2.800
18
2.800
19
2.800
20
22,000
21
Apr 08, 2019
['2019-04-08', '2.890', '2.890', '2.890', '2.890', '2.890', '-']
22
2.890
23
2.890
24
2.890
25
2.890
26
2.890
27
-
28
Apr 04, 2019
['2019-04-04', '2.810', '2.810', '2.800', '2.800', '2.800', '56,000']
29
2.810
30
2.810
31
2.800
32
2.800
33
2.800
34
56,000
35
Apr 03, 2019
['2019-04-03', '2.890', '2.890', '2.720', '2.770', '2.770', '60,000']
36
2.890
37
2.890
38
2.720
39
2.770
40
2.770
41
60,000
42
Apr 02, 2019
['2019-04-02', '2.900', '2.900', '2.900', '2.900', '2.900', '-']
43
2.900
44
2.900
45
2.900
46
2.900
47
2.900
48
-
49
Apr 01, 2019
['2019-04-01', '2.880', '2.880', '2.880', '2.880', '2.880', '4,000']
50
2.880
51
2.880
52
2.880
53
2.880
54
2.880
55
4,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0126.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.930', '0.930', '0.930', '0.930', '0.930', '220,000']
1
0.930
2
0.930
3
0.930
4
0.930
5
0.930
6
220,000
7
Apr 10, 2019
['2019-04-10', '0.930', '0.940', '0.920', '0.940', '0.940', '588,000']
8
0.930
9
0.940
10
0.920
11
0.940
12
0.940
13
588,000
14
Apr 09, 2019
['2019-04-09', '0.930', '0.940', '0.930', '0.940', '0.940', '42,000']
15
0.930
16
0.940
17
0.930
18
0.940
19
0.940
20
42,000
21
Apr 08, 2019
['2019-04-08', '0.930', '0.940', '0.920', '0.940', '0.940', '550,000']
22
0.930
23
0.940
24
0.920
25
0.940
26
0.940
27
550,000
28
Apr 04, 2019
['2019-04-04', '0.930', '0.940', '0.910', '0.910', '0.910', '84,000']
29
0.930
30
0.940
31
0.910
32
0.910
33
0.910
34
84,000
35
Apr 03, 2019
['2019-04-03', '0.920', '0.930', '0.910', '0.920', '0.920', '518,000']
36
0.920
37
0.930
38
0.910
39
0.920
40
0.920
41
518,000
42
Apr 02, 2019
['2019-04-02', '0.920', '0.940', '0.910', '0.920', '0.920', '1,336,000']
43
0.920
44
0.940
45
0.910
46
0.920
47
0.920
48
1,336,000
49
Apr 01, 2019
['2019-04-01', '0.910', '0.920', '0.910', '0.920', '0.920', '1,828,000']
50
0.910
51
0.920
52
0.910
53
0.920
54
0.920
55
1,828,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0127.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '8.830', '8.850', '8.700', '8.730', '8.730', '412,500']
1
8.830
2
8.850
3
8.700
4
8.730
5
8.730
6
412,500
7
Apr 10, 2019
['2019-04-10', '8.920', '8.920', '8.800', '8.850', '8.850', '448,000']
8
8.920
9
8.920
10
8.800
11
8.850
12
8.850
13
448,000
14
Apr 09, 2019
['2019-04-09', '8.870', '8.950', '8.800', '8.920', '8.920', '466,353']
15
8.870
16
8.950
17
8.800
18
8.920
19
8.920
20
466,353
21
Apr 08, 2019
['2019-04-08', '8.800', '8.920', '8.800', '8.850', '8.850', '439,000']
22
8.800
23
8.920
24
8.800
25
8.850
26
8.850
27
439,000
28
Apr 04, 2019
['2019-04-04', '8.910', '8.910', '8.820', '8.880', '8.880', '237,500']
29
8.910
30
8.910
31
8.820
32
8.880
33
8.880
34
237,500
35
Apr 03, 2019
['2019-04-03', '8.990', '9.050', '8.850', '8.910', '8.910', '607,316']
36
8.990
37
9.050
38
8.850
39
8.910
40
8.910
41
607,316
42
Apr 02, 2019
['2019-04-02', '9.060', '9.080', '8.900', '8.970', '8.970', '316,500']
43
9.060
44
9.080
45
8.900
46
8.970
47
8.970
48
316,500
49
Apr 01, 2019
['2019-04-01', '9.220', '9.220', '9.010', '9.020', '9.020', '357,000']
50
9.220
51
9.220
52
9.010
53
9.020
54
9.020
55
357,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0129.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.630', '1.640', '1.630', '1.630', '1.630', '386,000']
1
1.630
2
1.640
3
1.630
4
1.630
5
1.630
6
386,000
7
Apr 10, 2019
['2019-04-10', '1.630', '1.650', '1.630', '1.630', '1.630', '122,071']
8
1.630
9
1.650
10
1.630
11
1.630
12
1.630
13
122,071
14
Apr 09, 2019
['2019-04-09', '1.620', '1.650', '1.620', '1.620', '1.620', '862,312']
15
1.620
16
1.650
17
1.620
18
1.620
19
1.620
20
862,312
21
Apr 08, 2019
['2019-04-08', '1.620', '1.620', '1.610', '1.620', '1.620', '67,136']
22
1.620
23
1.620
24
1.610
25
1.620
26
1.620
27
67,136
28
Apr 04, 2019
['2019-04-04', '1.640', '1.640', '1.610', '1.630', '1.630', '138,000']
29
1.640
30
1.640
31
1.610
32
1.630
33
1.630
34
138,000
35
Apr 03, 2019
['2019-04-03', '1.620', '1.630', '1.620', '1.620', '1.620', '594,000']
36
1.620
37
1.630
38
1.620
39
1.620
40
1.620
41
594,000
42
Apr 02, 2019
['2019-04-02', '1.610', '1.620', '1.610', '1.610', '1.610', '152,883']
43
1.610
44
1.620
45
1.610
46
1.610
47
1.610
48
152,883
49
Apr 01, 2019
['2019-04-01', '1.620', '1.630', '1.600', '1.620', '1.620', '186,000']
50
1.620
51
1.630
52
1.600
53
1.620
54
1.620
55
186,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0130.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.680', '0.730', '0.660', '0.730', '0.730', '165,000']
1
0.680
2
0.730
3
0.660
4
0.730
5
0.730
6
165,000
7
Apr 10, 2019
['2019-04-10', '0.690', '0.690', '0.690', '0.690', '0.690', '-']
8
0.690
9
0.690
10
0.690
11
0.690
12
0.690
13
-
14
Apr 09, 2019
['2019-04-09', '0.690', '0.690', '0.690', '0.690', '0.690', '-']
15
0.690
16
0.690
17
0.690
18
0.690
19
0.690
20
-
21
Apr 08, 2019
['2019-04-08', '0.690', '0.690', '0.690', '0.690', '0.690', '2,000']
22
0.690
23
0.690
24
0.690
25
0.690
26
0.690
27
2,000
28
Apr 04, 2019
['2019-04-04', '0.700', '0.760', '0.680', '0.730', '0.730', '346,000']
29
0.700
30
0.760
31
0.680
32
0.730
33
0.730
34
346,000
35
Apr 03, 2019
['2019-04-03', '0.630', '0.700', '0.630', '0.700', '0.700', '196,000']
36
0.630
37
0.700
38
0.630
39
0.700
40
0.700
41
196,000
42
Apr 02, 2019
['2019-04-02', '0.700', '0.700', '0.700', '0.700', '0.700', '-']
43
0.700
44
0.700
45
0.700
46
0.700
47
0.700
48
-
49
Apr 01, 2019
['2019-04-01', '0.700', '0.700', '0.700', '0.700', '0.700', '-']
50
0.700
51
0.700
52
0.700
53
0.700
54
0.700
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0131.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.160', '4.270', '4.160', '4.270', '4.270', '45,000']
1
4.160
2
4.270
3
4.160
4
4.270
5
4.270
6
45,000
7
Apr 10, 2019
['2019-04-10', '4.300', '4.430', '4.260', '4.260', '4.260', '59,000']
8
4.300
9
4.430
10
4.260
11
4.260
12
4.260
13
59,000
14
Apr 09, 2019
['2019-04-09', '4.420', '4.420', '4.420', '4.400', '4.400', '13,000']
15
4.420
16
4.420
17
4.420
18
4.400
19
4.400
20
13,000
21
Apr 08, 2019
['2019-04-08', '4.390', '4.480', '4.390', '4.480', '4.480', '48,000']
22
4.390
23
4.480
24
4.390
25
4.480
26
4.480
27
48,000
28
Apr 04, 2019
['2019-04-04', '4.350', '4.390', '4.350', '4.390', '4.390', '37,889']
29
4.350
30
4.390
31
4.350
32
4.390
33
4.390
34
37,889
35
Apr 03, 2019
['2019-04-03', '4.370', '4.400', '4.370', '4.390', '4.390', '62,000']
36
4.370
37
4.400
38
4.370
39
4.390
40
4.390
41
62,000
42
Apr 02, 2019
['2019-04-02', '4.320', '4.370', '4.130', '4.370', '4.370', '91,899']
43
4.320
44
4.370
45
4.130
46
4.370
47
4.370
48
91,899
49
Apr 01, 2019
['2019-04-01', '4.370', '4.370', '4.370', '4.370', '4.370', '-']
50
4.370
51
4.370
52
4.370
53
4.370
54
4.370
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0132.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.400', '0.400', '0.400', '0.400', '0.400', '-']
1
0.400
2
0.400
3
0.400
4
0.400
5
0.400
6
-
7
Apr 10, 2019
['2019-04-10', '0.350', '0.420', '0.350', '0.400', '0.400', '121,000']
8
0.350
9
0.420
10
0.350
11
0.400
12
0.400
13
121,000
14
Apr 09, 2019
['2019-04-09', '0.390', '0.390', '0.390', '0.390', '0.390', '-']
15
0.390
16
0.390
17
0.390
18
0.390
19
0.390
20
-
21
Apr 08, 2019
['2019-04-08', '0.410', '0.410', '0.410', '0.410', '0.410', '-']
22
0.410
23
0.410
24
0.410
25
0.410
26
0.410
27
-
28
Apr 04, 2019
['2019-04-04', '0.380', '0.410', '0.380', '0.410', '0.410', '100,866']
29
0.380
30
0.410
31
0.380
32
0.410
33
0.410
34
100,866
35
Apr 03, 2019
['2019-04-03', '0.400', '0.400', '0.400', '0.400', '0.400', '-']
36
0.400
37
0.400
38
0.400
39
0.400
40
0.400
41
-
42
Apr 02, 2019
['2019-04-02', '0.405', '0.405', '0.400', '0.400', '0.400', '5,000']
43
0.405
44
0.405
45
0.400
46
0.400
47
0.400
48
5,000
49
Apr 01, 2019
['2019-04-01', '0.450', '0.450', '0.410', '0.410', '0.410', '382,000']
50
0.450
51
0.450
52
0.410
53
0.410
54
0.410
55
382,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0135.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '8.590', '8.790', '8.530', '8.770', '8.770', '30,039,255']
1
8.590
2
8.790
3
8.530
4
8.770
5
8.770
6
30,039,255
7
Apr 10, 2019
['2019-04-10', '8.400', '8.520', '8.350', '8.450', '8.450', '22,879,819']
8
8.400
9
8.520
10
8.350
11
8.450
12
8.450
13
22,879,819
14
Apr 09, 2019
['2019-04-09', '8.380', '8.430', '8.300', '8.350', '8.350', '12,830,703']
15
8.380
16
8.430
17
8.300
18
8.350
19
8.350
20
12,830,703
21
Apr 08, 2019
['2019-04-08', '8.440', '8.520', '8.310', '8.380', '8.380', '23,454,582']
22
8.440
23
8.520
24
8.310
25
8.380
26
8.380
27
23,454,582
28
Apr 04, 2019
['2019-04-04', '8.400', '8.450', '8.340', '8.400', '8.400', '19,792,339']
29
8.400
30
8.450
31
8.340
32
8.400
33
8.400
34
19,792,339
35
Apr 03, 2019
['2019-04-03', '8.140', '8.410', '8.100', '8.400', '8.400', '24,318,176']
36
8.140
37
8.410
38
8.100
39
8.400
40
8.400
41
24,318,176
42
Apr 02, 2019
['2019-04-02', '8.200', '8.410', '8.080', '8.110', '8.110', '33,801,684']
43
8.200
44
8.410
45
8.080
46
8.110
47
8.110
48
33,801,684
49
Apr 01, 2019
['2019-04-01', '8.200', '8.250', '8.060', '8.140', '8.140', '24,472,434']
50
8.200
51
8.250
52
8.060
53
8.140
54
8.140
55
24,472,434
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0136.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.238', '0.239', '0.234', '0.235', '0.235', '77,496,000']
1
0.238
2
0.239
3
0.234
4
0.235
5
0.235
6
77,496,000
7
Apr 10, 2019
['2019-04-10', '0.238', '0.239', '0.235', '0.238', '0.238', '101,721,562']
8
0.238
9
0.239
10
0.235
11
0.238
12
0.238
13
101,721,562
14
Apr 09, 2019
['2019-04-09', '0.242', '0.244', '0.238', '0.238', '0.238', '116,426,000']
15
0.242
16
0.244
17
0.238
18
0.238
19
0.238
20
116,426,000
21
Apr 08, 2019
['2019-04-08', '0.247', '0.247', '0.240', '0.242', '0.242', '90,962,000']
22
0.247
23
0.247
24
0.240
25
0.242
26
0.242
27
90,962,000
28
Apr 04, 2019
['2019-04-04', '0.255', '0.255', '0.245', '0.247', '0.247', '107,346,000']
29
0.255
30
0.255
31
0.245
32
0.247
33
0.247
34
107,346,000
35
Apr 03, 2019
['2019-04-03', '0.255', '0.260', '0.245', '0.250', '0.250', '159,544,000']
36
0.255
37
0.260
38
0.245
39
0.250
40
0.250
41
159,544,000
42
Apr 02, 2019
['2019-04-02', '0.239', '0.255', '0.237', '0.255', '0.255', '151,819,375']
43
0.239
44
0.255
45
0.237
46
0.255
47
0.255
48
151,819,375
49
Apr 01, 2019
['2019-04-01', '0.238', '0.242', '0.235', '0.237', '0.237', '128,956,821']
50
0.238
51
0.242
52
0.235
53
0.237
54
0.237
55
128,956,821
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0137.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.890', '0.890', '0.890', '0.890', '0.890', '-']
1
0.890
2
0.890
3
0.890
4
0.890
5
0.890
6
-
7
Apr 10, 2019
['2019-04-10', '0.920', '0.920', '0.890', '0.890', '0.890', '62,000']
8
0.920
9
0.920
10
0.890
11
0.890
12
0.890
13
62,000
14
Apr 09, 2019
['2019-04-09', '0.850', '0.930', '0.850', '0.920', '0.920', '393,000']
15
0.850
16
0.930
17
0.850
18
0.920
19
0.920
20
393,000
21
Apr 08, 2019
['2019-04-08', '0.880', '0.880', '0.880', '0.880', '0.880', '-']
22
0.880
23
0.880
24
0.880
25
0.880
26
0.880
27
-
28
Apr 04, 2019
['2019-04-04', '0.880', '0.880', '0.880', '0.880', '0.880', '-']
29
0.880
30
0.880
31
0.880
32
0.880
33
0.880
34
-
35
Apr 03, 2019
['2019-04-03', '0.880', '0.880', '0.880', '0.880', '0.880', '47,000']
36
0.880
37
0.880
38
0.880
39
0.880
40
0.880
41
47,000
42
Apr 02, 2019
['2019-04-02', '0.880', '0.880', '0.880', '0.880', '0.880', '51,000']
43
0.880
44
0.880
45
0.880
46
0.880
47
0.880
48
51,000
49
Apr 01, 2019
['2019-04-01', '0.880', '0.900', '0.880', '0.880', '0.880', '34,000']
50
0.880
51
0.900
52
0.880
53
0.880
54
0.880
55
34,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0138.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.750', '0.750', '0.730', '0.740', '0.740', '396,000']
1
0.750
2
0.750
3
0.730
4
0.740
5
0.740
6
396,000
7
Apr 10, 2019
['2019-04-10', '0.750', '0.750', '0.740', '0.750', '0.750', '135,000']
8
0.750
9
0.750
10
0.740
11
0.750
12
0.750
13
135,000
14
Apr 09, 2019
['2019-04-09', '0.750', '0.750', '0.740', '0.750', '0.750', '42,000']
15
0.750
16
0.750
17
0.740
18
0.750
19
0.750
20
42,000
21
Apr 08, 2019
['2019-04-08', '0.750', '0.760', '0.740', '0.750', '0.750', '268,600']
22
0.750
23
0.760
24
0.740
25
0.750
26
0.750
27
268,600
28
Apr 04, 2019
['2019-04-04', '0.730', '0.750', '0.730', '0.750', '0.750', '994,750']
29
0.730
30
0.750
31
0.730
32
0.750
33
0.750
34
994,750
35
Apr 03, 2019
['2019-04-03', '0.740', '0.750', '0.730', '0.730', '0.730', '1,631,000']
36
0.740
37
0.750
38
0.730
39
0.730
40
0.730
41
1,631,000
42
Apr 02, 2019
['2019-04-02', '0.770', '0.770', '0.730', '0.750', '0.750', '1,826,545']
43
0.770
44
0.770
45
0.730
46
0.750
47
0.750
48
1,826,545
49
Apr 01, 2019
['2019-04-01', '0.760', '0.780', '0.700', '0.780', '0.780', '4,220,385']
50
0.760
51
0.780
52
0.700
53
0.780
54
0.780
55
4,220,385
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0139.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.059', '0.059', '0.055', '0.057', '0.057', '15,541,549']
1
0.059
2
0.059
3
0.055
4
0.057
5
0.057
6
15,541,549
7
Apr 10, 2019
['2019-04-10', '0.059', '0.059', '0.056', '0.058', '0.058', '28,952,452']
8
0.059
9
0.059
10
0.056
11
0.058
12
0.058
13
28,952,452
14
Apr 09, 2019
['2019-04-09', '0.053', '0.059', '0.053', '0.058', '0.058', '44,780,829']
15
0.053
16
0.059
17
0.053
18
0.058
19
0.058
20
44,780,829
21
Apr 08, 2019
['2019-04-08', '0.058', '0.058', '0.054', '0.055', '0.055', '38,747,229']
22
0.058
23
0.058
24
0.054
25
0.055
26
0.055
27
38,747,229
28
Apr 04, 2019
['2019-04-04', '0.054', '0.058', '0.054', '0.057', '0.057', '33,560,001']
29
0.054
30
0.058
31
0.054
32
0.057
33
0.057
34
33,560,001
35
Apr 03, 2019
['2019-04-03', '0.058', '0.058', '0.053', '0.055', '0.055', '46,471,017']
36
0.058
37
0.058
38
0.053
39
0.055
40
0.055
41
46,471,017
42
Apr 02, 2019
['2019-04-02', '0.062', '0.064', '0.055', '0.057', '0.057', '51,240,020']
43
0.062
44
0.064
45
0.055
46
0.057
47
0.057
48
51,240,020
49
Apr 01, 2019
['2019-04-01', '0.061', '0.064', '0.061', '0.062', '0.062', '19,760,492']
50
0.061
51
0.064
52
0.061
53
0.062
54
0.062
55
19,760,492
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0142.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.860', '2.870', '2.800', '2.800', '2.800', '10,380,200']
1
2.860
2
2.870
3
2.800
4
2.800
5
2.800
6
10,380,200
7
Apr 10, 2019
['2019-04-10', '2.860', '2.900', '2.840', '2.860', '2.860', '7,522,132']
8
2.860
9
2.900
10
2.840
11
2.860
12
2.860
13
7,522,132
14
Apr 09, 2019
['2019-04-09', '2.860', '2.930', '2.860', '2.890', '2.890', '28,083,241']
15
2.860
16
2.930
17
2.860
18
2.890
19
2.890
20
28,083,241
21
Apr 08, 2019
['2019-04-08', '2.870', '2.910', '2.850', '2.860', '2.860', '6,815,500']
22
2.870
23
2.910
24
2.850
25
2.860
26
2.860
27
6,815,500
28
Apr 04, 2019
['2019-04-04', '2.900', '2.910', '2.850', '2.870', '2.870', '2,947,704']
29
2.900
30
2.910
31
2.850
32
2.870
33
2.870
34
2,947,704
35
Apr 03, 2019
['2019-04-03', '2.880', '2.910', '2.860', '2.880', '2.880', '5,232,000']
36
2.880
37
2.910
38
2.860
39
2.880
40
2.880
41
5,232,000
42
Apr 02, 2019
['2019-04-02', '2.850', '2.880', '2.830', '2.880', '2.880', '4,503,231']
43
2.850
44
2.880
45
2.830
46
2.880
47
2.880
48
4,503,231
49
Apr 01, 2019
['2019-04-01', '2.880', '2.880', '2.840', '2.860', '2.860', '7,307,000']
50
2.880
51
2.880
52
2.840
53
2.860
54
2.860
55
7,307,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0143.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.125', '0.125', '0.118', '0.121', '0.121', '168,000']
1
0.125
2
0.125
3
0.118
4
0.121
5
0.121
6
168,000
7
Apr 10, 2019
['2019-04-10', '0.118', '0.121', '0.118', '0.121', '0.121', '1,214,000']
8
0.118
9
0.121
10
0.118
11
0.121
12
0.121
13
1,214,000
14
Apr 09, 2019
['2019-04-09', '0.124', '0.124', '0.117', '0.122', '0.122', '384,000']
15
0.124
16
0.124
17
0.117
18
0.122
19
0.122
20
384,000
21
Apr 08, 2019
['2019-04-08', '0.126', '0.126', '0.117', '0.123', '0.123', '18,000']
22
0.126
23
0.126
24
0.117
25
0.123
26
0.123
27
18,000
28
Apr 04, 2019
['2019-04-04', '0.119', '0.120', '0.118', '0.120', '0.120', '462,000']
29
0.119
30
0.120
31
0.118
32
0.120
33
0.120
34
462,000
35
Apr 03, 2019
['2019-04-03', '0.118', '0.124', '0.118', '0.120', '0.120', '562,000']
36
0.118
37
0.124
38
0.118
39
0.120
40
0.120
41
562,000
42
Apr 02, 2019
['2019-04-02', '0.117', '0.119', '0.117', '0.118', '0.118', '662,000']
43
0.117
44
0.119
45
0.117
46
0.118
47
0.118
48
662,000
49
Apr 01, 2019
['2019-04-01', '0.120', '0.120', '0.118', '0.119', '0.119', '204,000']
50
0.120
51
0.120
52
0.118
53
0.119
54
0.119
55
204,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0144.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '16.520', '16.520', '16.360', '16.420', '16.420', '3,365,150']
1
16.520
2
16.520
3
16.360
4
16.420
5
16.420
6
3,365,150
7
Apr 10, 2019
['2019-04-10', '16.520', '16.540', '16.240', '16.460', '16.460', '6,015,470']
8
16.520
9
16.540
10
16.240
11
16.460
12
16.460
13
6,015,470
14
Apr 09, 2019
['2019-04-09', '16.760', '16.800', '16.460', '16.640', '16.640', '3,797,547']
15
16.760
16
16.800
17
16.460
18
16.640
19
16.640
20
3,797,547
21
Apr 08, 2019
['2019-04-08', '16.880', '16.940', '16.760', '16.800', '16.800', '3,291,365']
22
16.880
23
16.940
24
16.760
25
16.800
26
16.800
27
3,291,365
28
Apr 04, 2019
['2019-04-04', '17.140', '17.140', '16.760', '16.880', '16.880', '2,478,950']
29
17.140
30
17.140
31
16.760
32
16.880
33
16.880
34
2,478,950
35
Apr 03, 2019
['2019-04-03', '16.940', '17.060', '16.860', '16.960', '16.960', '3,389,213']
36
16.940
37
17.060
38
16.860
39
16.960
40
16.960
41
3,389,213
42
Apr 02, 2019
['2019-04-02', '16.860', '16.980', '16.600', '16.960', '16.960', '5,255,651']
43
16.860
44
16.980
45
16.600
46
16.960
47
16.960
48
5,255,651
49
Apr 01, 2019
['2019-04-01', '16.720', '16.820', '16.520', '16.660', '16.660', '3,535,146']
50
16.720
51
16.820
52
16.520
53
16.660
54
16.660
55
3,535,146
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0146.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '1.520', '1.520', '1.520', '1.520', '1.520', '-']
1
1.520
2
1.520
3
1.520
4
1.520
5
1.520
6
-
7
Apr 10, 2019
['2019-04-10', '1.520', '1.520', '1.520', '1.520', '1.520', '-']
8
1.520
9
1.520
10
1.520
11
1.520
12
1.520
13
-
14
Apr 09, 2019
['2019-04-09', '1.560', '1.560', '1.560', '1.560', '1.560', '-']
15
1.560
16
1.560
17
1.560
18
1.560
19
1.560
20
-
21
Apr 08, 2019
['2019-04-08', '1.560', '1.560', '1.560', '1.560', '1.560', '-']
22
1.560
23
1.560
24
1.560
25
1.560
26
1.560
27
-
28
Apr 04, 2019
['2019-04-04', '1.560', '1.560', '1.560', '1.560', '1.560', '-']
29
1.560
30
1.560
31
1.560
32
1.560
33
1.560
34
-
35
Apr 03, 2019
['2019-04-03', '1.520', '1.560', '1.520', '1.560', '1.560', '17,000']
36
1.520
37
1.560
38
1.520
39
1.560
40
1.560
41
17,000
42
Apr 02, 2019
['2019-04-02', '1.530', '1.530', '1.530', '1.530', '1.530', '-']
43
1.530
44
1.530
45
1.530
46
1.530
47
1.530
48
-
49
Apr 01, 2019
['2019-04-01', '1.520', '1.520', '1.520', '1.520', '1.520', '-']
50
1.520
51
1.520
52
1.520
53
1.520
54
1.520
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0147.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.139', '0.139', '0.132', '0.135', '0.135', '100,000']
1
0.139
2
0.139
3
0.132
4
0.135
5
0.135
6
100,000
7
Apr 10, 2019
['2019-04-10', '0.140', '0.140', '0.140', '0.140', '0.140', '25,000']
8
0.140
9
0.140
10
0.140
11
0.140
12
0.140
13
25,000
14
Apr 09, 2019
['2019-04-09', '0.140', '0.140', '0.140', '0.140', '0.140', '600,000']
15
0.140
16
0.140
17
0.140
18
0.140
19
0.140
20
600,000
21
Apr 08, 2019
['2019-04-08', '0.145', '0.145', '0.145', '0.145', '0.145', '-']
22
0.145
23
0.145
24
0.145
25
0.145
26
0.145
27
-
28
Apr 04, 2019
['2019-04-04', '0.145', '0.145', '0.145', '0.145', '0.145', '-']
29
0.145
30
0.145
31
0.145
32
0.145
33
0.145
34
-
35
Apr 03, 2019
['2019-04-03', '0.145', '0.145', '0.145', '0.145', '0.145', '100,000']
36
0.145
37
0.145
38
0.145
39
0.145
40
0.145
41
100,000
42
Apr 02, 2019
['2019-04-02', '0.147', '0.147', '0.145', '0.145', '0.145', '10,000']
43
0.147
44
0.147
45
0.145
46
0.145
47
0.145
48
10,000
49
Apr 01, 2019
['2019-04-01', '0.140', '0.140', '0.140', '0.140', '0.140', '-']
50
0.140
51
0.140
52
0.140
53
0.140
54
0.140
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0148.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '28.750', '29.000', '28.500', '28.550', '28.550', '2,324,005']
1
28.750
2
29.000
3
28.500
4
28.550
5
28.550
6
2,324,005
7
Apr 10, 2019
['2019-04-10', '28.800', '28.900', '28.300', '28.600', '28.600', '3,079,415']
8
28.800
9
28.900
10
28.300
11
28.600
12
28.600
13
3,079,415
14
Apr 09, 2019
['2019-04-09', '28.500', '28.850', '27.950', '28.850', '28.850', '2,879,000']
15
28.500
16
28.850
17
27.950
18
28.850
19
28.850
20
2,879,000
21
Apr 08, 2019
['2019-04-08', '28.400', '28.800', '28.150', '28.400', '28.400', '5,847,650']
22
28.400
23
28.800
24
28.150
25
28.400
26
28.400
27
5,847,650
28
Apr 04, 2019
['2019-04-04', '28.200', '28.400', '27.900', '28.200', '28.200', '1,540,500']
29
28.200
30
28.400
31
27.900
32
28.200
33
28.200
34
1,540,500
35
Apr 03, 2019
['2019-04-03', '28.000', '28.200', '27.900', '28.050', '28.050', '1,532,900']
36
28.000
37
28.200
38
27.900
39
28.050
40
28.050
41
1,532,900
42
Apr 02, 2019
['2019-04-02', '28.350', '28.450', '27.950', '28.150', '28.150', '1,877,350']
43
28.350
44
28.450
45
27.950
46
28.150
47
28.150
48
1,877,350
49
Apr 01, 2019
['2019-04-01', '27.900', '28.350', '27.550', '28.200', '28.200', '2,326,497']
50
27.900
51
28.350
52
27.550
53
28.200
54
28.200
55
2,326,497
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0149.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.044', '0.044', '0.043', '0.044', '0.044', '1,927,531']
1
0.044
2
0.044
3
0.043
4
0.044
5
0.044
6
1,927,531
7
Apr 10, 2019
['2019-04-10', '0.043', '0.044', '0.043', '0.044', '0.044', '1,947,000']
8
0.043
9
0.044
10
0.043
11
0.044
12
0.044
13
1,947,000
14
Apr 09, 2019
['2019-04-09', '0.044', '0.045', '0.043', '0.044', '0.044', '8,560,000']
15
0.044
16
0.045
17
0.043
18
0.044
19
0.044
20
8,560,000
21
Apr 08, 2019
['2019-04-08', '0.044', '0.045', '0.043', '0.045', '0.045', '2,830,000']
22
0.044
23
0.045
24
0.043
25
0.045
26
0.045
27
2,830,000
28
Apr 04, 2019
['2019-04-04', '0.043', '0.044', '0.043', '0.044', '0.044', '3,926,000']
29
0.043
30
0.044
31
0.043
32
0.044
33
0.044
34
3,926,000
35
Apr 03, 2019
['2019-04-03', '0.044', '0.047', '0.043', '0.044', '0.044', '8,944,700']
36
0.044
37
0.047
38
0.043
39
0.044
40
0.044
41
8,944,700
42
Apr 02, 2019
['2019-04-02', '0.042', '0.044', '0.042', '0.043', '0.043', '1,536,000']
43
0.042
44
0.044
45
0.042
46
0.043
47
0.043
48
1,536,000
49
Apr 01, 2019
['2019-04-01', '0.042', '0.044', '0.041', '0.043', '0.043', '41,965,000']
50
0.042
51
0.044
52
0.041
53
0.043
54
0.043
55
41,965,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0151.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '6.500', '6.530', '6.460', '6.490', '6.490', '8,988,060']
1
6.500
2
6.530
3
6.460
4
6.490
5
6.490
6
8,988,060
7
Apr 10, 2019
['2019-04-10', '6.700', '6.700', '6.460', '6.550', '6.550', '8,673,100']
8
6.700
9
6.700
10
6.460
11
6.550
12
6.550
13
8,673,100
14
Apr 09, 2019
['2019-04-09', '6.630', '6.690', '6.560', '6.640', '6.640', '9,160,388']
15
6.630
16
6.690
17
6.560
18
6.640
19
6.640
20
9,160,388
21
Apr 08, 2019
['2019-04-08', '6.680', '6.790', '6.590', '6.640', '6.640', '11,227,641']
22
6.680
23
6.790
24
6.590
25
6.640
26
6.640
27
11,227,641
28
Apr 04, 2019
['2019-04-04', '6.720', '6.720', '6.600', '6.640', '6.640', '7,444,415']
29
6.720
30
6.720
31
6.600
32
6.640
33
6.640
34
7,444,415
35
Apr 03, 2019
['2019-04-03', '6.560', '6.720', '6.520', '6.710', '6.710', '11,930,688']
36
6.560
37
6.720
38
6.520
39
6.710
40
6.710
41
11,930,688
42
Apr 02, 2019
['2019-04-02', '6.570', '6.570', '6.480', '6.510', '6.510', '6,374,728']
43
6.570
44
6.570
45
6.480
46
6.510
47
6.510
48
6,374,728
49
Apr 01, 2019
['2019-04-01', '6.540', '6.620', '6.500', '6.530', '6.530', '10,570,920']
50
6.540
51
6.620
52
6.500
53
6.530
54
6.530
55
10,570,920
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0152.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '17.680', '17.800', '17.460', '17.560', '17.560', '4,517,533']
1
17.680
2
17.800
3
17.460
4
17.560
5
17.560
6
4,517,533
7
Apr 10, 2019
['2019-04-10', '17.500', '17.520', '17.380', '17.520', '17.520', '2,823,438']
8
17.500
9
17.520
10
17.380
11
17.520
12
17.520
13
2,823,438
14
Apr 09, 2019
['2019-04-09', '17.400', '17.500', '17.120', '17.500', '17.500', '3,025,114']
15
17.400
16
17.500
17
17.120
18
17.500
19
17.500
20
3,025,114
21
Apr 08, 2019
['2019-04-08', '17.460', '17.460', '17.000', '17.280', '17.280', '3,362,807']
22
17.460
23
17.460
24
17.000
25
17.280
26
17.280
27
3,362,807
28
Apr 04, 2019
['2019-04-04', '16.920', '17.360', '16.820', '17.180', '17.180', '4,529,419']
29
16.920
30
17.360
31
16.820
32
17.180
33
17.180
34
4,529,419
35
Apr 03, 2019
['2019-04-03', '17.000', '17.000', '16.620', '16.860', '16.860', '2,256,398']
36
17.000
37
17.000
38
16.620
39
16.860
40
16.860
41
2,256,398
42
Apr 02, 2019
['2019-04-02', '16.880', '17.020', '16.780', '16.940', '16.940', '2,728,680']
43
16.880
44
17.020
45
16.780
46
16.940
47
16.940
48
2,728,680
49
Apr 01, 2019
['2019-04-01', '16.920', '16.940', '16.620', '16.700', '16.700', '3,284,071']
50
16.920
51
16.940
52
16.620
53
16.700
54
16.700
55
3,284,071
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0153.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.370', '0.370', '0.360', '0.370', '0.370', '250,000']
1
0.370
2
0.370
3
0.360
4
0.370
5
0.370
6
250,000
7
Apr 10, 2019
['2019-04-10', '0.365', '0.370', '0.360', '0.370', '0.370', '420,000']
8
0.365
9
0.370
10
0.360
11
0.370
12
0.370
13
420,000
14
Apr 09, 2019
['2019-04-09', '0.365', '0.370', '0.355', '0.370', '0.370', '3,522,000']
15
0.365
16
0.370
17
0.355
18
0.370
19
0.370
20
3,522,000
21
Apr 08, 2019
['2019-04-08', '0.380', '0.380', '0.355', '0.370', '0.370', '5,156,000']
22
0.380
23
0.380
24
0.355
25
0.370
26
0.370
27
5,156,000
28
Apr 04, 2019
['2019-04-04', '0.375', '0.380', '0.370', '0.375', '0.375', '486,000']
29
0.375
30
0.380
31
0.370
32
0.375
33
0.375
34
486,000
35
Apr 03, 2019
['2019-04-03', '0.370', '0.375', '0.365', '0.375', '0.375', '2,334,000']
36
0.370
37
0.375
38
0.365
39
0.375
40
0.375
41
2,334,000
42
Apr 02, 2019
['2019-04-02', '0.370', '0.375', '0.365', '0.375', '0.375', '3,052,000']
43
0.370
44
0.375
45
0.365
46
0.375
47
0.375
48
3,052,000
49
Apr 01, 2019
['2019-04-01', '0.380', '0.380', '0.370', '0.375', '0.375', '3,008,000']
50
0.380
51
0.380
52
0.370
53
0.375
54
0.375
55
3,008,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
No record
0
0157.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.640', '0.640', '0.640', '0.640', '0.640', '20,000']
1
0.640
2
0.640
3
0.640
4
0.640
5
0.640
6
20,000
7
Apr 10, 2019
['2019-04-10', '0.650', '0.650', '0.650', '0.650', '0.650', '-']
8
0.650
9
0.650
10
0.650
11
0.650
12
0.650
13
-
14
Apr 09, 2019
['2019-04-09', '0.650', '0.650', '0.630', '0.650', '0.650', '240,000']
15
0.650
16
0.650
17
0.630
18
0.650
19
0.650
20
240,000
21
Apr 08, 2019
['2019-04-08', '0.640', '0.640', '0.640', '0.640', '0.640', '130,000']
22
0.640
23
0.640
24
0.640
25
0.640
26
0.640
27
130,000
28
Apr 04, 2019
['2019-04-04', '0.670', '0.670', '0.640', '0.670', '0.670', '220,000']
29
0.670
30
0.670
31
0.640
32
0.670
33
0.670
34
220,000
35
Apr 03, 2019
['2019-04-03', '0.700', '0.700', '0.680', '0.680', '0.680', '60,000']
36
0.700
37
0.700
38
0.680
39
0.680
40
0.680
41
60,000
42
Apr 02, 2019
['2019-04-02', '0.730', '0.730', '0.700', '0.700', '0.700', '170,000']
43
0.730
44
0.730
45
0.700
46
0.700
47
0.700
48
170,000
49
Apr 01, 2019
['2019-04-01', '0.750', '0.750', '0.750', '0.750', '0.750', '-']
50
0.750
51
0.750
52
0.750
53
0.750
54
0.750
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0159.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.166', '0.166', '0.166', '0.166', '0.166', '-']
1
0.166
2
0.166
3
0.166
4
0.166
5
0.166
6
-
7
Apr 10, 2019
['2019-04-10', '0.170', '0.170', '0.170', '0.170', '0.170', '-']
8
0.170
9
0.170
10
0.170
11
0.170
12
0.170
13
-
14
Apr 09, 2019
['2019-04-09', '0.170', '0.170', '0.170', '0.170', '0.170', '-']
15
0.170
16
0.170
17
0.170
18
0.170
19
0.170
20
-
21
Apr 08, 2019
['2019-04-08', '0.170', '0.170', '0.170', '0.170', '0.170', '-']
22
0.170
23
0.170
24
0.170
25
0.170
26
0.170
27
-
28
Apr 04, 2019
['2019-04-04', '0.170', '0.170', '0.170', '0.170', '0.170', '-']
29
0.170
30
0.170
31
0.170
32
0.170
33
0.170
34
-
35
Apr 03, 2019
['2019-04-03', '0.170', '0.170', '0.170', '0.170', '0.170', '-']
36
0.170
37
0.170
38
0.170
39
0.170
40
0.170
41
-
42
Apr 02, 2019
['2019-04-02', '0.170', '0.170', '0.170', '0.170', '0.170', '-']
43
0.170
44
0.170
45
0.170
46
0.170
47
0.170
48
-
49
Apr 01, 2019
['2019-04-01', '0.176', '0.176', '0.176', '0.176', '0.176', '-']
50
0.176
51
0.176
52
0.176
53
0.176
54
0.176
55
-
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0161.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '4.960', '4.990', '4.870', '4.870', '4.870', '408,000']
1
4.960
2
4.990
3
4.870
4
4.870
5
4.870
6
408,000
7
Apr 10, 2019
['2019-04-10', '4.980', '4.990', '4.910', '4.980', '4.980', '424,000']
8
4.980
9
4.990
10
4.910
11
4.980
12
4.980
13
424,000
14
Apr 09, 2019
['2019-04-09', '5.000', '5.080', '4.930', '5.000', '5.000', '528,000']
15
5.000
16
5.080
17
4.930
18
5.000
19
5.000
20
528,000
21
Apr 08, 2019
['2019-04-08', '5.110', '5.170', '4.880', '4.980', '4.980', '846,036']
22
5.110
23
5.170
24
4.880
25
4.980
26
4.980
27
846,036
28
Apr 04, 2019
['2019-04-04', '5.200', '5.240', '5.040', '5.090', '5.090', '826,000']
29
5.200
30
5.240
31
5.040
32
5.090
33
5.090
34
826,000
35
Apr 03, 2019
['2019-04-03', '5.180', '5.220', '5.100', '5.170', '5.170', '1,926,000']
36
5.180
37
5.220
38
5.100
39
5.170
40
5.170
41
1,926,000
42
Apr 02, 2019
['2019-04-02', '4.930', '5.250', '4.910', '5.200', '5.200', '2,146,000']
43
4.930
44
5.250
45
4.910
46
5.200
47
5.200
48
2,146,000
49
Apr 01, 2019
['2019-04-01', '4.860', '5.030', '4.850', '4.980', '4.980', '672,000']
50
4.860
51
5.030
52
4.850
53
4.980
54
4.980
55
672,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0162.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.275', '0.280', '0.275', '0.280', '0.280', '3,116,000']
1
0.275
2
0.280
3
0.275
4
0.280
5
0.280
6
3,116,000
7
Apr 10, 2019
['2019-04-10', '0.265', '0.275', '0.265', '0.270', '0.270', '92,000']
8
0.265
9
0.275
10
0.265
11
0.270
12
0.270
13
92,000
14
Apr 09, 2019
['2019-04-09', '0.280', '0.280', '0.265', '0.280', '0.280', '387,000']
15
0.280
16
0.280
17
0.265
18
0.280
19
0.280
20
387,000
21
Apr 08, 2019
['2019-04-08', '0.270', '0.285', '0.270', '0.285', '0.285', '1,102,000']
22
0.270
23
0.285
24
0.270
25
0.285
26
0.285
27
1,102,000
28
Apr 04, 2019
['2019-04-04', '0.280', '0.280', '0.270', '0.275', '0.275', '384,000']
29
0.280
30
0.280
31
0.270
32
0.275
33
0.275
34
384,000
35
Apr 03, 2019
['2019-04-03', '0.290', '0.290', '0.280', '0.285', '0.285', '262,000']
36
0.290
37
0.290
38
0.280
39
0.285
40
0.285
41
262,000
42
Apr 02, 2019
['2019-04-02', '0.280', '0.295', '0.280', '0.290', '0.290', '40,000']
43
0.280
44
0.295
45
0.280
46
0.290
47
0.290
48
40,000
49
Apr 01, 2019
['2019-04-01', '0.285', '0.295', '0.280', '0.290', '0.290', '731,500']
50
0.285
51
0.295
52
0.280
53
0.290
54
0.290
55
731,500
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0163.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '2.440', '2.440', '2.350', '2.400', '2.400', '622,000']
1
2.440
2
2.440
3
2.350
4
2.400
5
2.400
6
622,000
7
Apr 10, 2019
['2019-04-10', '2.420', '2.440', '2.400', '2.410', '2.410', '280,003']
8
2.420
9
2.440
10
2.400
11
2.410
12
2.410
13
280,003
14
Apr 09, 2019
['2019-04-09', '2.410', '2.450', '2.410', '2.430', '2.430', '718,000']
15
2.410
16
2.450
17
2.410
18
2.430
19
2.430
20
718,000
21
Apr 08, 2019
['2019-04-08', '2.440', '2.460', '2.420', '2.440', '2.440', '773,000']
22
2.440
23
2.460
24
2.420
25
2.440
26
2.440
27
773,000
28
Apr 04, 2019
['2019-04-04', '2.440', '2.450', '2.400', '2.420', '2.420', '712,000']
29
2.440
30
2.450
31
2.400
32
2.420
33
2.420
34
712,000
35
Apr 03, 2019
['2019-04-03', '2.420', '2.450', '2.410', '2.430', '2.430', '306,000']
36
2.420
37
2.450
38
2.410
39
2.430
40
2.430
41
306,000
42
Apr 02, 2019
['2019-04-02', '2.470', '2.470', '2.430', '2.440', '2.440', '566,000']
43
2.470
44
2.470
45
2.430
46
2.440
47
2.440
48
566,000
49
Apr 01, 2019
['2019-04-01', '2.450', '2.460', '2.360', '2.440', '2.440', '502,333']
50
2.450
51
2.460
52
2.360
53
2.440
54
2.440
55
502,333
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0164.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.220', '0.228', '0.213', '0.217', '0.217', '270,000']
1
0.220
2
0.228
3
0.213
4
0.217
5
0.217
6
270,000
7
Apr 10, 2019
['2019-04-10', '0.212', '0.215', '0.210', '0.213', '0.213', '625,000']
8
0.212
9
0.215
10
0.210
11
0.213
12
0.213
13
625,000
14
Apr 09, 2019
['2019-04-09', '0.219', '0.219', '0.213', '0.213', '0.213', '410,000']
15
0.219
16
0.219
17
0.213
18
0.213
19
0.213
20
410,000
21
Apr 08, 2019
['2019-04-08', '0.225', '0.225', '0.213', '0.219', '0.219', '1,390,000']
22
0.225
23
0.225
24
0.213
25
0.219
26
0.219
27
1,390,000
28
Apr 04, 2019
['2019-04-04', '0.211', '0.220', '0.210', '0.220', '0.220', '2,375,000']
29
0.211
30
0.220
31
0.210
32
0.220
33
0.220
34
2,375,000
35
Apr 03, 2019
['2019-04-03', '0.212', '0.218', '0.210', '0.217', '0.217', '925,000']
36
0.212
37
0.218
38
0.210
39
0.217
40
0.217
41
925,000
42
Apr 02, 2019
['2019-04-02', '0.226', '0.226', '0.212', '0.221', '0.221', '1,910,000']
43
0.226
44
0.226
45
0.212
46
0.221
47
0.221
48
1,910,000
49
Apr 01, 2019
['2019-04-01', '0.213', '0.250', '0.213', '0.226', '0.226', '2,524,500']
50
0.213
51
0.250
52
0.213
53
0.226
54
0.226
55
2,524,500
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0166.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.103', '0.107', '0.102', '0.105', '0.105', '733,900']
1
0.103
2
0.107
3
0.102
4
0.105
5
0.105
6
733,900
7
Apr 10, 2019
['2019-04-10', '0.100', '0.110', '0.100', '0.107', '0.107', '2,042,200']
8
0.100
9
0.110
10
0.100
11
0.107
12
0.107
13
2,042,200
14
Apr 09, 2019
['2019-04-09', '0.104', '0.105', '0.099', '0.103', '0.103', '1,237,100']
15
0.104
16
0.105
17
0.099
18
0.103
19
0.103
20
1,237,100
21
Apr 08, 2019
['2019-04-08', '0.103', '0.108', '0.103', '0.107', '0.107', '81,000']
22
0.103
23
0.108
24
0.103
25
0.107
26
0.107
27
81,000
28
Apr 04, 2019
['2019-04-04', '0.105', '0.113', '0.103', '0.107', '0.107', '3,904,000']
29
0.105
30
0.113
31
0.103
32
0.107
33
0.107
34
3,904,000
35
Apr 03, 2019
['2019-04-03', '0.104', '0.106', '0.104', '0.105', '0.105', '252,000']
36
0.104
37
0.106
38
0.104
39
0.105
40
0.105
41
252,000
42
Apr 02, 2019
['2019-04-02', '0.105', '0.106', '0.105', '0.105', '0.105', '166,000']
43
0.105
44
0.106
45
0.105
46
0.105
47
0.105
48
166,000
49
Apr 01, 2019
['2019-04-01', '0.102', '0.112', '0.101', '0.105', '0.105', '2,168,500']
50
0.102
51
0.112
52
0.101
53
0.105
54
0.105
55
2,168,500
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0167.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.079', '0.079', '0.079', '0.079', '0.079', '372,000']
1
0.079
2
0.079
3
0.079
4
0.079
5
0.079
6
372,000
7
Apr 10, 2019
['2019-04-10', '0.079', '0.083', '0.079', '0.082', '0.082', '480,000']
8
0.079
9
0.083
10
0.079
11
0.082
12
0.082
13
480,000
14
Apr 09, 2019
['2019-04-09', '0.083', '0.083', '0.083', '0.083', '0.083', '-']
15
0.083
16
0.083
17
0.083
18
0.083
19
0.083
20
-
21
Apr 08, 2019
['2019-04-08', '0.083', '0.083', '0.083', '0.083', '0.083', '422,000']
22
0.083
23
0.083
24
0.083
25
0.083
26
0.083
27
422,000
28
Apr 04, 2019
['2019-04-04', '0.082', '0.084', '0.082', '0.084', '0.084', '346,000']
29
0.082
30
0.084
31
0.082
32
0.084
33
0.084
34
346,000
35
Apr 03, 2019
['2019-04-03', '0.083', '0.083', '0.080', '0.081', '0.081', '1,714,000']
36
0.083
37
0.083
38
0.080
39
0.081
40
0.081
41
1,714,000
42
Apr 02, 2019
['2019-04-02', '0.084', '0.087', '0.080', '0.083', '0.083', '1,548,000']
43
0.084
44
0.087
45
0.080
46
0.083
47
0.083
48
1,548,000
49
Apr 01, 2019
['2019-04-01', '0.090', '0.091', '0.084', '0.089', '0.089', '1,364,000']
50
0.090
51
0.091
52
0.084
53
0.089
54
0.089
55
1,364,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0168.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '43.000', '43.900', '42.000', '42.700', '42.700', '3,192,345']
1
43.000
2
43.900
3
42.000
4
42.700
5
42.700
6
3,192,345
7
Apr 10, 2019
['2019-04-10', '41.850', '42.950', '41.750', '42.900', '42.900', '1,850,332']
8
41.850
9
42.950
10
41.750
11
42.900
12
42.900
13
1,850,332
14
Apr 09, 2019
['2019-04-09', '42.200', '42.450', '41.450', '42.200', '42.200', '1,878,921']
15
42.200
16
42.450
17
41.450
18
42.200
19
42.200
20
1,878,921
21
Apr 08, 2019
['2019-04-08', '41.600', '42.800', '41.600', '42.200', '42.200', '3,234,232']
22
41.600
23
42.800
24
41.600
25
42.200
26
42.200
27
3,234,232
28
Apr 04, 2019
['2019-04-04', '41.550', '42.000', '40.600', '41.600', '41.600', '3,188,000']
29
41.550
30
42.000
31
40.600
32
41.600
33
41.600
34
3,188,000
35
Apr 03, 2019
['2019-04-03', '39.200', '42.000', '39.200', '41.650', '41.650', '7,127,945']
36
39.200
37
42.000
38
39.200
39
41.650
40
41.650
41
7,127,945
42
Apr 02, 2019
['2019-04-02', '39.000', '39.500', '38.600', '39.400', '39.400', '3,660,251']
43
39.000
44
39.500
45
38.600
46
39.400
47
39.400
48
3,660,251
49
Apr 01, 2019
['2019-04-01', '37.600', '39.350', '37.050', '39.350', '39.350', '6,919,060']
50
37.600
51
39.350
52
37.050
53
39.350
54
39.350
55
6,919,060
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0169.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.890', '0.910', '0.850', '0.860', '0.860', '5,501,000']
1
0.890
2
0.910
3
0.850
4
0.860
5
0.860
6
5,501,000
7
Apr 10, 2019
['2019-04-10', '0.830', '0.940', '0.830', '0.890', '0.890', '23,507,000']
8
0.830
9
0.940
10
0.830
11
0.890
12
0.890
13
23,507,000
14
Apr 09, 2019
['2019-04-09', '0.820', '0.850', '0.810', '0.830', '0.830', '2,822,000']
15
0.820
16
0.850
17
0.810
18
0.830
19
0.830
20
2,822,000
21
Apr 08, 2019
['2019-04-08', '0.800', '0.840', '0.800', '0.820', '0.820', '2,897,600']
22
0.800
23
0.840
24
0.800
25
0.820
26
0.820
27
2,897,600
28
Apr 04, 2019
['2019-04-04', '0.800', '0.830', '0.780', '0.800', '0.800', '2,524,000']
29
0.800
30
0.830
31
0.780
32
0.800
33
0.800
34
2,524,000
35
Apr 03, 2019
['2019-04-03', '0.760', '0.840', '0.760', '0.810', '0.810', '5,532,000']
36
0.760
37
0.840
38
0.760
39
0.810
40
0.810
41
5,532,000
42
Apr 02, 2019
['2019-04-02', '0.780', '0.780', '0.760', '0.780', '0.780', '575,000']
43
0.780
44
0.780
45
0.760
46
0.780
47
0.780
48
575,000
49
Apr 01, 2019
['2019-04-01', '0.770', '0.780', '0.750', '0.780', '0.780', '1,093,200']
50
0.770
51
0.780
52
0.750
53
0.780
54
0.780
55
1,093,200
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0173.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '5.060', '5.060', '4.890', '4.920', '4.920', '4,680,175']
1
5.060
2
5.060
3
4.890
4
4.920
5
4.920
6
4,680,175
7
Apr 10, 2019
['2019-04-10', '4.940', '5.070', '4.930', '5.060', '5.060', '5,886,683']
8
4.940
9
5.070
10
4.930
11
5.060
12
5.060
13
5,886,683
14
Apr 09, 2019
['2019-04-09', '4.870', '4.970', '4.860', '4.970', '4.970', '3,903,091']
15
4.870
16
4.970
17
4.860
18
4.970
19
4.970
20
3,903,091
21
Apr 08, 2019
['2019-04-08', '4.870', '4.950', '4.850', '4.900', '4.900', '2,915,724']
22
4.870
23
4.950
24
4.850
25
4.900
26
4.900
27
2,915,724
28
Apr 04, 2019
['2019-04-04', '4.960', '4.960', '4.840', '4.870', '4.870', '4,293,728']
29
4.960
30
4.960
31
4.840
32
4.870
33
4.870
34
4,293,728
35
Apr 03, 2019
['2019-04-03', '4.950', '4.970', '4.880', '4.940', '4.940', '7,763,572']
36
4.950
37
4.970
38
4.880
39
4.940
40
4.940
41
7,763,572
42
Apr 02, 2019
['2019-04-02', '4.930', '4.950', '4.870', '4.890', '4.890', '5,206,303']
43
4.930
44
4.950
45
4.870
46
4.890
47
4.890
48
5,206,303
49
Apr 01, 2019
['2019-04-01', '4.840', '4.950', '4.830', '4.930', '4.930', '4,508,087']
50
4.840
51
4.950
52
4.830
53
4.930
54
4.930
55
4,508,087
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0175.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '17.740', '17.900', '17.380', '17.620', '17.620', '123,588,925']
1
17.740
2
17.900
3
17.380
4
17.620
5
17.620
6
123,588,925
7
Apr 10, 2019
['2019-04-10', '17.180', '17.880', '16.720', '17.700', '17.700', '109,220,168']
8
17.180
9
17.880
10
16.720
11
17.700
12
17.700
13
109,220,168
14
Apr 09, 2019
['2019-04-09', '17.980', '18.000', '17.240', '17.320', '17.320', '139,808,937']
15
17.980
16
18.000
17
17.240
18
17.320
19
17.320
20
139,808,937
21
Apr 08, 2019
['2019-04-08', '17.020', '17.180', '16.780', '17.160', '17.160', '115,842,913']
22
17.020
23
17.180
24
16.780
25
17.160
26
17.160
27
115,842,913
28
Apr 04, 2019
['2019-04-04', '16.540', '16.880', '16.140', '16.760', '16.760', '122,079,136']
29
16.540
30
16.880
31
16.140
32
16.760
33
16.760
34
122,079,136
35
Apr 03, 2019
['2019-04-03', '16.000', '16.400', '15.760', '16.360', '16.360', '109,089,226']
36
16.000
37
16.400
38
15.760
39
16.360
40
16.360
41
109,089,226
42
Apr 02, 2019
['2019-04-02', '15.760', '15.900', '15.540', '15.820', '15.820', '71,095,295']
43
15.760
44
15.900
45
15.540
46
15.820
47
15.820
48
71,095,295
49
Apr 01, 2019
['2019-04-01', '15.200', '15.800', '15.120', '15.560', '15.560', '89,836,396']
50
15.200
51
15.800
52
15.120
53
15.560
54
15.560
55
89,836,396
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0176.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.300', '0.300', '0.300', '0.300', '0.300', '-']
1
0.300
2
0.300
3
0.300
4
0.300
5
0.300
6
-
7
Apr 10, 2019
['2019-04-10', '0.280', '0.315', '0.280', '0.315', '0.315', '272,000']
8
0.280
9
0.315
10
0.280
11
0.315
12
0.315
13
272,000
14
Apr 09, 2019
['2019-04-09', '0.325', '0.325', '0.325', '0.325', '0.325', '-']
15
0.325
16
0.325
17
0.325
18
0.325
19
0.325
20
-
21
Apr 08, 2019
['2019-04-08', '0.320', '0.320', '0.320', '0.320', '0.320', '6,000']
22
0.320
23
0.320
24
0.320
25
0.320
26
0.320
27
6,000
28
Apr 04, 2019
['2019-04-04', '0.305', '0.305', '0.305', '0.305', '0.305', '-']
29
0.305
30
0.305
31
0.305
32
0.305
33
0.305
34
-
35
Apr 03, 2019
['2019-04-03', '0.290', '0.305', '0.290', '0.305', '0.305', '154,000']
36
0.290
37
0.305
38
0.290
39
0.305
40
0.305
41
154,000
42
Apr 02, 2019
['2019-04-02', '0.300', '0.305', '0.280', '0.305', '0.305', '106,000']
43
0.300
44
0.305
45
0.280
46
0.305
47
0.305
48
106,000
49
Apr 01, 2019
['2019-04-01', '0.300', '0.300', '0.300', '0.300', '0.300', '180,000']
50
0.300
51
0.300
52
0.300
53
0.300
54
0.300
55
180,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0177.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '11.000', '11.120', '10.980', '11.040', '11.040', '1,704,981']
1
11.000
2
11.120
3
10.980
4
11.040
5
11.040
6
1,704,981
7
Apr 10, 2019
['2019-04-10', '10.940', '11.120', '10.860', '11.080', '11.080', '2,815,441']
8
10.940
9
11.120
10
10.860
11
11.080
12
11.080
13
2,815,441
14
Apr 09, 2019
['2019-04-09', '11.000', '11.080', '10.860', '10.880', '10.880', '2,619,837']
15
11.000
16
11.080
17
10.860
18
10.880
19
10.880
20
2,619,837
21
Apr 08, 2019
['2019-04-08', '11.080', '11.220', '10.960', '11.020', '11.020', '3,796,486']
22
11.080
23
11.220
24
10.960
25
11.020
26
11.020
27
3,796,486
28
Apr 04, 2019
['2019-04-04', '10.940', '11.140', '10.920', '11.080', '11.080', '2,672,000']
29
10.940
30
11.140
31
10.920
32
11.080
33
11.080
34
2,672,000
35
Apr 03, 2019
['2019-04-03', '11.100', '11.160', '10.860', '10.940', '10.940', '4,205,274']
36
11.100
37
11.160
38
10.860
39
10.940
40
10.940
41
4,205,274
42
Apr 02, 2019
['2019-04-02', '11.220', '11.220', '11.060', '11.060', '11.060', '2,444,000']
43
11.220
44
11.220
45
11.060
46
11.060
47
11.060
48
2,444,000
49
Apr 01, 2019
['2019-04-01', '11.200', '11.320', '11.200', '11.220', '11.220', '2,813,194']
50
11.200
51
11.320
52
11.200
53
11.220
54
11.220
55
2,813,194
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0179.HKneeds update

[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '19.700', '19.700', '19.000', '19.100', '19.100', '338,765']
1
19.700
2
19.700
3
19.000
4
19.100
5
19.100
6
338,765
7
Apr 10, 2019
['2019-04-10', '19.040', '19.640', '18.900', '19.600', '19.600', '901,000']
8
19.040
9
19.640
10
18.900
11
19.600
12
19.600
13
901,000
14
Apr 09, 2019
['2019-04-09', '19.120', '19.160', '18.880', '19.100', '19.100', '707,500']
15
19.120
16
19.160
17
18.880
18
19.100
19
19.100
20
707,500
21
Apr 08, 2019
['2019-04-08', '19.020', '19.300', '18.960', '19.100', '19.100', '1,102,982']
22
19.020
23
19.300
24
18.960
25
19.100
26
19.100
27
1,102,982
28
Apr 04, 2019
['2019-04-04', '19.120', '19.260', '18.680', '18.980', '18.980', '672,000']
29
19.120
30
19.260
31
18.680
32
18.980
33
18.980
34
672,000
35
Apr 03, 2019
['2019-04-03', '18.920', '19.120', '18.760', '19.120', '19.120', '581,520']
36
18.920
37
19.120
38
18.760
39
19.120
40
19.120
41
581,520
42
Apr 02, 2019
['2019-04-02', '18.600', '18.900', '18.600', '18.780', '18.780', '473,625']
43
18.600
44
18.900
45
18.600
46
18.780
47
18.780
48
473,625
49
Apr 01, 2019
['2019-04-01', '18.300', '18.660', '18.300', '18.560', '18.560', '514,000']
50
18.300
51
18.660
52
18.300
53
18.560
54
18.560
55
514,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0180.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.920', '0.920', '0.890', '0.890', '0.890', '94,000']
1
0.920
2
0.920
3
0.890
4
0.890
5
0.890
6
94,000
7
Apr 10, 2019
['2019-04-10', '0.910', '0.920', '0.900', '0.920', '0.920', '82,000']
8
0.910
9
0.920
10
0.900
11
0.920
12
0.920
13
82,000
14
Apr 09, 2019
['2019-04-09', '0.970', '0.970', '0.970', '0.970', '0.970', '-']
15
0.970
16
0.970
17
0.970
18
0.970
19
0.970
20
-
21
Apr 08, 2019
['2019-04-08', '0.970', '0.970', '0.970', '0.970', '0.970', '-']
22
0.970
23
0.970
24
0.970
25
0.970
26
0.970
27
-
28
Apr 04, 2019
['2019-04-04', '0.950', '0.950', '0.950', '0.950', '0.950', '-']
29
0.950
30
0.950
31
0.950
32
0.950
33
0.950
34
-
35
Apr 03, 2019
['2019-04-03', '0.900', '0.980', '0.900', '0.970', '0.970', '86,000']
36
0.900
37
0.980
38
0.900
39
0.970
40
0.970
41
86,000
42
Apr 02, 2019
['2019-04-02', '0.900', '0.930', '0.890', '0.920', '0.920', '56,000']
43
0.900
44
0.930
45
0.890
46
0.920
47
0.920
48
56,000
49
Apr 01, 2019
['2019-04-01', '0.900', '0.900', '0.880', '0.900', '0.900', '188,000']
50
0.900
51
0.900
52
0.880
53
0.900
54
0.900
55
188,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0182.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.405', '0.405', '0.395', '0.400', '0.400', '6,610,000']
1
0.405
2
0.405
3
0.395
4
0.400
5
0.400
6
6,610,000
7
Apr 10, 2019
['2019-04-10', '0.400', '0.405', '0.395', '0.405', '0.405', '4,220,000']
8
0.400
9
0.405
10
0.395
11
0.405
12
0.405
13
4,220,000
14
Apr 09, 2019
['2019-04-09', '0.405', '0.405', '0.395', '0.400', '0.400', '7,210,000']
15
0.405
16
0.405
17
0.395
18
0.400
19
0.400
20
7,210,000
21
Apr 08, 2019
['2019-04-08', '0.405', '0.405', '0.395', '0.400', '0.400', '8,482,913']
22
0.405
23
0.405
24
0.395
25
0.400
26
0.400
27
8,482,913
28
Apr 04, 2019
['2019-04-04', '0.400', '0.405', '0.395', '0.405', '0.405', '12,910,000']
29
0.400
30
0.405
31
0.395
32
0.405
33
0.405
34
12,910,000
35
Apr 03, 2019
['2019-04-03', '0.410', '0.410', '0.395', '0.400', '0.400', '8,880,000']
36
0.410
37
0.410
38
0.395
39
0.400
40
0.400
41
8,880,000
42
Apr 02, 2019
['2019-04-02', '0.405', '0.410', '0.400', '0.405', '0.405', '3,570,000']
43
0.405
44
0.410
45
0.400
46
0.405
47
0.405
48
3,570,000
49
Apr 01, 2019
['2019-04-01', '0.415', '0.420', '0.400', '0.400', '0.400', '6,310,000']
50
0.415
51
0.420
52
0.400
53
0.400
54
0.400
55
6,310,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0183.HKneeds update
[]
[]
57
[]
[]
0
Apr 11, 2019
['2019-04-11', '0.105', '0.106', '0.105', '0.105', '0.105', '416,000']
1
0.105
2
0.106
3
0.105
4
0.105
5
0.105
6
416,000
7
Apr 10, 2019
['2019-04-10', '0.106', '0.107', '0.104', '0.105', '0.105', '2,112,000']
8
0.106
9
0.107
10
0.104
11
0.105
12
0.105
13
2,112,000
14
Apr 09, 2019
['2019-04-09', '0.104', '0.106', '0.103', '0.106', '0.106', '384,000']
15
0.104
16
0.106
17
0.103
18
0.106
19
0.106
20
384,000
21
Apr 08, 2019
['2019-04-08', '0.106', '0.108', '0.104', '0.106', '0.106', '280,000']
22
0.106
23
0.108
24
0.104
25
0.106
26
0.106
27
280,000
28
Apr 04, 2019
['2019-04-04', '0.105', '0.109', '0.105', '0.107', '0.107', '576,000']
29
0.105
30
0.109
31
0.105
32
0.107
33
0.107
34
576,000
35
Apr 03, 2019
['2019-04-03', '0.105', '0.106', '0.104', '0.106', '0.106', '776,000']
36
0.105
37
0.106
38
0.104
39
0.106
40
0.106
41
776,000
42
Apr 02, 2019
['2019-04-02', '0.108', '0.108', '0.106', '0.106', '0.106', '728,000']
43
0.108
44
0.108
45
0.106
46
0.106
47
0.106
48
728,000
49
Apr 01, 2019
['2019-04-01', '0.107', '0.107', '0.105', '0.107', '0.107', '1,848,000']
50
0.107
51
0.107
52
0.105
53
0.107
54
0.107
55
1,848,000
56
8
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks
0
0184.HKneeds update

ProxyError: HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/0184.HK/history?period1=1554048000&period2=1554998400&interval=1d&filter=history&frequency=1d (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 504 Proxy Timeout ( The connection timed out.  )',)))

plot a random record

In [ ]:

x = [1,2,3,4]
y = [10,20,25,30]
fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(x, y, color='lightblue', linewidth=3)
ax.scatter([2,4,6],[5,15,25],color='darkgreen',marker='^')
ax.set_xlim(1,7.5)

plot a stock record with 233 and 610 average line

In [4]:
import pandas as pd
import numpy as np
from StockObj import StockObj
import matplotlib.pyplot as plt
import sqlite3




abc = StockObj("abc", "%5EHSI")
# conn = abc.create_connection("/Users/chenyanyang/tst.db")
conn = abc.create_connection("D:\\stks\\tst.db")
abc.manual_update("2010-02-02", "2017-09-01")
abc.manual_update("2010-02-02", "2017-04-01")
abc.manual_update("2010-02-02", "2016-12-01")
abc.manual_update("2010-02-02", "2016-07-01")
abc.manual_update("2010-02-02", "2016-02-01")
abc.manual_update("2010-02-02", "2015-10-01")
# abc = StockObj("abc", "1888.HK")
# conn = sqlite3.connect("D:\\stks\\tst.db")
# cur = conn.cursor()
# cur.execute(
#     "SELECT close, stkdate FROM STOCKS where idx = " + "'" + "1888.HK" + 
#     "'" + "and stkdate between " + "'" + "2016-01-01" + "'" + "and" + "'" + "2019-04-08" + "'")
# num = cur.fetchall()
# indlist=[]
# for t in num:
#     indlist.append(t[0])
# y=indlist

# x=np.arange(start = 0, stop = len(indlist), step = 1)

# g610x=[]
# g610y=[]

# g233x=[]
# g233y=[]

# for t in x:
#     if t > 610:
#         g610x.append(t)
#         g610y.append(np.average(indlist[t-610:t]))
        
# for t in x:
#     if t > 233:
#         g233x.append(t)
#         g233y.append(np.average(indlist[t-233:t]))

# fig = plt.figure()
# ax = fig.add_subplot(111)
# ax.plot(x, y, color='lightblue', linewidth=3)
# ax.scatter(g610x, g610y, color='green', linewidth=2)
# ax.scatter(g233x, g233y, color='red', linewidth=2)
# plt.savefig('foo.png')
# #plt.xticks(range(1, 30))
# plt.show()

[]
[]
701
[]
[]
0
Sep 01, 2017
['2017-09-01', '28,015.22', '28,116.70', '27,915.44', '27,953.16', '27,953.16', '1,754,523,000']
1
28,015.22
2
28,116.70
3
27,915.44
4
27,953.16
5
27,953.16
6
1,754,523,000
7
Aug 31, 2017
['2017-08-31', '27,934.45', '27,994.06', '27,861.48', '27,970.30', '27,970.30', '2,795,558,800']
8
27,934.45
9
27,994.06
10
27,861.48
11
27,970.30
12
27,970.30
13
2,795,558,800
14
Aug 30, 2017
['2017-08-30', '27,957.74', '28,127.90', '27,912.82', '28,094.61', '28,094.61', '2,142,434,100']
15
27,957.74
16
28,127.90
17
27,912.82
18
28,094.61
19
28,094.61
20
2,142,434,100
21
Aug 29, 2017
['2017-08-29', '27,744.58', '27,839.83', '27,638.73', '27,765.01', '27,765.01', '1,717,761,500']
22
27,744.58
23
27,839.83
24
27,638.73
25
27,765.01
26
27,765.01
27
1,717,761,500
28
Aug 28, 2017
['2017-08-28', '27,905.59', '28,071.59', '27,806.05', '27,863.29', '27,863.29', '3,019,391,000']
29
27,905.59
30
28,071.59
31
27,806.05
32
27,863.29
33
27,863.29
34
3,019,391,000
35
Aug 25, 2017
['2017-08-25', '27,539.11', '27,878.37', '27,480.11', '27,848.16', '27,848.16', '3,791,271,400']
36
27,539.11
37
27,878.37
38
27,480.11
39
27,848.16
40
27,848.16
41
3,791,271,400
42
Aug 24, 2017
['2017-08-24', '27,642.23', '27,642.23', '27,485.87', '27,518.60', '27,518.60', '2,691,510,500']
43
27,642.23
44
27,642.23
45
27,485.87
46
27,518.60
47
27,518.60
48
2,691,510,500
49
Aug 23, 2017
['2017-08-23', '-', '-', '-', '-', '-', '-']
50
-
51
-
52
-
53
-
54
-
55
-
56
Aug 22, 2017
['2017-08-22', '27,322.20', '27,509.06', '27,316.08', '27,401.67', '27,401.67', '2,049,708,500']
57
27,322.20
58
27,509.06
59
27,316.08
60
27,401.67
61
27,401.67
62
2,049,708,500
63
Aug 21, 2017
['2017-08-21', '27,100.63', '27,221.31', '27,086.43', '27,154.68', '27,154.68', '1,770,623,000']
64
27,100.63
65
27,221.31
66
27,086.43
67
27,154.68
68
27,154.68
69
1,770,623,000
70
Aug 18, 2017
['2017-08-18', '26,999.60', '27,236.32', '26,951.92', '27,047.57', '27,047.57', '1,691,600,400']
71
26,999.60
72
27,236.32
73
26,951.92
74
27,047.57
75
27,047.57
76
1,691,600,400
77
Aug 17, 2017
['2017-08-17', '27,610.29', '27,624.52', '27,302.48', '27,344.22', '27,344.22', '1,795,330,700']
78
27,610.29
79
27,624.52
80
27,302.48
81
27,344.22
82
27,344.22
83
1,795,330,700
84
Aug 16, 2017
['2017-08-16', '27,238.81', '27,422.30', '27,238.81', '27,409.07', '27,409.07', '1,771,056,700']
85
27,238.81
86
27,422.30
87
27,238.81
88
27,409.07
89
27,409.07
90
1,771,056,700
91
Aug 15, 2017
['2017-08-15', '27,371.25', '27,438.42', '27,174.96', '27,174.96', '27,174.96', '2,735,953,400']
92
27,371.25
93
27,438.42
94
27,174.96
95
27,174.96
96
27,174.96
97
2,735,953,400
98
Aug 14, 2017
['2017-08-14', '27,091.77', '27,268.23', '27,032.40', '27,250.23', '27,250.23', '1,416,372,000']
99
27,091.77
100
27,268.23
101
27,032.40
102
27,250.23
103
27,250.23
104
1,416,372,000
105
Aug 11, 2017
['2017-08-11', '27,000.43', '27,184.21', '26,863.71', '26,883.51', '26,883.51', '3,133,494,700']
106
27,000.43
107
27,184.21
108
26,863.71
109
26,883.51
110
26,883.51
111
3,133,494,700
112
Aug 10, 2017
['2017-08-10', '27,791.36', '27,791.36', '27,267.03', '27,444.00', '27,444.00', '2,175,962,000']
113
27,791.36
114
27,791.36
115
27,267.03
116
27,444.00
117
27,444.00
118
2,175,962,000
119
Aug 09, 2017
['2017-08-09', '27,760.08', '27,876.12', '27,602.66', '27,757.09', '27,757.09', '1,650,670,500']
120
27,760.08
121
27,876.12
122
27,602.66
123
27,757.09
124
27,757.09
125
1,650,670,500
126
Aug 08, 2017
['2017-08-08', '27,684.60', '27,867.56', '27,626.19', '27,854.91', '27,854.91', '1,726,572,600']
127
27,684.60
128
27,867.56
129
27,626.19
130
27,854.91
131
27,854.91
132
1,726,572,600
133
Aug 07, 2017
['2017-08-07', '27,665.71', '27,731.92', '27,629.20', '27,690.36', '27,690.36', '1,484,632,800']
134
27,665.71
135
27,731.92
136
27,629.20
137
27,690.36
138
27,690.36
139
1,484,632,800
140
Aug 04, 2017
['2017-08-04', '27,564.71', '27,615.03', '27,508.11', '27,562.68', '27,562.68', '1,464,939,100']
141
27,564.71
142
27,615.03
143
27,508.11
144
27,562.68
145
27,562.68
146
1,464,939,100
147
Aug 03, 2017
['2017-08-03', '27,533.51', '27,601.05', '27,399.58', '27,531.01', '27,531.01', '1,682,624,400']
148
27,533.51
149
27,601.05
150
27,399.58
151
27,531.01
152
27,531.01
153
1,682,624,400
154
Aug 02, 2017
['2017-08-02', '27,645.28', '27,747.35', '27,570.50', '27,607.38', '27,607.38', '2,052,633,600']
155
27,645.28
156
27,747.35
157
27,570.50
158
27,607.38
159
27,607.38
160
2,052,633,600
161
Aug 01, 2017
['2017-08-01', '27,326.04', '27,558.00', '27,326.04', '27,540.23', '27,540.23', '2,392,422,600']
162
27,326.04
163
27,558.00
164
27,326.04
165
27,540.23
166
27,540.23
167
2,392,422,600
168
Jul 31, 2017
['2017-07-31', '27,048.45', '27,324.38', '27,045.41', '27,323.99', '27,323.99', '1,693,214,100']
169
27,048.45
170
27,324.38
171
27,045.41
172
27,323.99
173
27,323.99
174
1,693,214,100
175
Jul 28, 2017
['2017-07-28', '27,007.97', '27,047.88', '26,928.44', '26,979.39', '26,979.39', '1,456,040,200']
176
27,007.97
177
27,047.88
178
26,928.44
179
26,979.39
180
26,979.39
181
1,456,040,200
182
Jul 27, 2017
['2017-07-27', '27,002.70', '27,169.15', '26,962.03', '27,131.17', '27,131.17', '1,763,945,900']
183
27,002.70
184
27,169.15
185
26,962.03
186
27,131.17
187
27,131.17
188
1,763,945,900
189
Jul 26, 2017
['2017-07-26', '26,960.81', '27,007.27', '26,786.63', '26,941.02', '26,941.02', '2,176,480,400']
190
26,960.81
191
27,007.27
192
26,786.63
193
26,941.02
194
26,941.02
195
2,176,480,400
196
Jul 25, 2017
['2017-07-25', '26,847.58', '26,889.70', '26,799.77', '26,852.05', '26,852.05', '1,450,948,000']
197
26,847.58
198
26,889.70
199
26,799.77
200
26,852.05
201
26,852.05
202
1,450,948,000
203
Jul 24, 2017
['2017-07-24', '26,720.04', '26,882.00', '26,674.50', '26,846.83', '26,846.83', '1,532,468,700']
204
26,720.04
205
26,882.00
206
26,674.50
207
26,846.83
208
26,846.83
209
1,532,468,700
210
Jul 21, 2017
['2017-07-21', '26,777.44', '26,778.42', '26,663.25', '26,706.09', '26,706.09', '1,502,400,500']
211
26,777.44
212
26,778.42
213
26,663.25
214
26,706.09
215
26,706.09
216
1,502,400,500
217
Jul 20, 2017
['2017-07-20', '26,770.48', '26,794.18', '26,632.98', '26,740.21', '26,740.21', '1,408,343,500']
218
26,770.48
219
26,794.18
220
26,632.98
221
26,740.21
222
26,740.21
223
1,408,343,500
224
Jul 19, 2017
['2017-07-19', '26,561.81', '26,682.64', '26,541.56', '26,672.16', '26,672.16', '1,346,812,900']
225
26,561.81
226
26,682.64
227
26,541.56
228
26,672.16
229
26,672.16
230
1,346,812,900
231
Jul 18, 2017
['2017-07-18', '26,489.52', '26,540.17', '26,381.14', '26,524.94', '26,524.94', '1,872,330,800']
232
26,489.52
233
26,540.17
234
26,381.14
235
26,524.94
236
26,524.94
237
1,872,330,800
238
Jul 17, 2017
['2017-07-17', '26,572.92', '26,618.66', '26,353.83', '26,470.58', '26,470.58', '1,837,446,700']
239
26,572.92
240
26,618.66
241
26,353.83
242
26,470.58
243
26,470.58
244
1,837,446,700
245
Jul 14, 2017
['2017-07-14', '26,416.68', '26,416.68', '26,295.99', '26,389.23', '26,389.23', '1,744,841,800']
246
26,416.68
247
26,416.68
248
26,295.99
249
26,389.23
250
26,389.23
251
1,744,841,800
252
Jul 13, 2017
['2017-07-13', '26,340.29', '26,383.76', '26,255.31', '26,346.17', '26,346.17', '1,971,724,000']
253
26,340.29
254
26,383.76
255
26,255.31
256
26,346.17
257
26,346.17
258
1,971,724,000
259
Jul 12, 2017
['2017-07-12', '25,991.35', '26,147.30', '25,991.35', '26,043.64', '26,043.64', '2,695,389,200']
260
25,991.35
261
26,147.30
262
25,991.35
263
26,043.64
264
26,043.64
265
2,695,389,200
266
Jul 11, 2017
['2017-07-11', '25,605.19', '25,941.47', '25,596.21', '25,877.64', '25,877.64', '2,230,926,300']
267
25,605.19
268
25,941.47
269
25,596.21
270
25,877.64
271
25,877.64
272
2,230,926,300
273
Jul 10, 2017
['2017-07-10', '25,392.03', '25,622.75', '25,331.95', '25,500.06', '25,500.06', '1,743,504,600']
274
25,392.03
275
25,622.75
276
25,331.95
277
25,500.06
278
25,500.06
279
1,743,504,600
280
Jul 07, 2017
['2017-07-07', '25,377.21', '25,409.90', '25,315.91', '25,340.85', '25,340.85', '1,480,481,500']
281
25,377.21
282
25,409.90
283
25,315.91
284
25,340.85
285
25,340.85
286
1,480,481,500
287
Jul 06, 2017
['2017-07-06', '25,574.57', '25,599.70', '25,436.83', '25,465.22', '25,465.22', '1,494,486,100']
288
25,574.57
289
25,599.70
290
25,436.83
291
25,465.22
292
25,465.22
293
1,494,486,100
294
Jul 05, 2017
['2017-07-05', '25,354.38', '25,559.18', '25,199.86', '25,521.97', '25,521.97', '1,868,195,300']
295
25,354.38
296
25,559.18
297
25,199.86
298
25,521.97
299
25,521.97
300
1,868,195,300
301
Jul 04, 2017
['2017-07-04', '25,782.85', '25,838.27', '25,251.72', '25,389.01', '25,389.01', '2,402,054,600']
302
25,782.85
303
25,838.27
304
25,251.72
305
25,389.01
306
25,389.01
307
2,402,054,600
308
Jul 03, 2017
['2017-07-03', '25,654.77', '25,821.39', '25,654.77', '25,784.17', '25,784.17', '1,505,017,700']
309
25,654.77
310
25,821.39
311
25,654.77
312
25,784.17
313
25,784.17
314
1,505,017,700
315
Jun 30, 2017
['2017-06-30', '25,679.64', '25,816.25', '25,661.43', '25,764.58', '25,764.58', '1,616,948,900']
316
25,679.64
317
25,816.25
318
25,661.43
319
25,764.58
320
25,764.58
321
1,616,948,900
322
Jun 29, 2017
['2017-06-29', '25,872.93', '25,965.42', '25,814.80', '25,965.42', '25,965.42', '1,748,405,000']
323
25,872.93
324
25,965.42
325
25,814.80
326
25,965.42
327
25,965.42
328
1,748,405,000
329
Jun 28, 2017
['2017-06-28', '25,735.21', '25,821.36', '25,625.71', '25,683.50', '25,683.50', '1,652,872,300']
330
25,735.21
331
25,821.36
332
25,625.71
333
25,683.50
334
25,683.50
335
1,652,872,300
336
Jun 27, 2017
['2017-06-27', '25,911.20', '25,929.61', '25,780.69', '25,839.99', '25,839.99', '1,182,985,800']
337
25,911.20
338
25,929.61
339
25,780.69
340
25,839.99
341
25,839.99
342
1,182,985,800
343
Jun 26, 2017
['2017-06-26', '25,727.93', '25,875.48', '25,720.38', '25,871.89', '25,871.89', '1,206,191,500']
344
25,727.93
345
25,875.48
346
25,720.38
347
25,871.89
348
25,871.89
349
1,206,191,500
350
Jun 23, 2017
['2017-06-23', '25,724.28', '25,770.37', '25,648.77', '25,670.05', '25,670.05', '1,302,570,300']
351
25,724.28
352
25,770.37
353
25,648.77
354
25,670.05
355
25,670.05
356
1,302,570,300
357
Jun 22, 2017
['2017-06-22', '25,597.46', '25,867.94', '25,597.46', '25,674.53', '25,674.53', '1,553,964,400']
358
25,597.46
359
25,867.94
360
25,597.46
361
25,674.53
362
25,674.53
363
1,553,964,400
364
Jun 21, 2017
['2017-06-21', '25,752.27', '25,846.52', '25,575.98', '25,694.58', '25,694.58', '1,699,891,000']
365
25,752.27
366
25,846.52
367
25,575.98
368
25,694.58
369
25,694.58
370
1,699,891,000
371
Jun 20, 2017
['2017-06-20', '26,028.43', '26,043.10', '25,833.93', '25,843.04', '25,843.04', '1,251,563,600']
372
26,028.43
373
26,043.10
374
25,833.93
375
25,843.04
376
25,843.04
377
1,251,563,600
378
Jun 19, 2017
['2017-06-19', '25,736.20', '25,939.72', '25,735.07', '25,924.55', '25,924.55', '1,116,125,500']
379
25,736.20
380
25,939.72
381
25,735.07
382
25,924.55
383
25,924.55
384
1,116,125,500
385
Jun 16, 2017
['2017-06-16', '25,601.81', '25,719.97', '25,557.80', '25,626.49', '25,626.49', '1,699,429,200']
386
25,601.81
387
25,719.97
388
25,557.80
389
25,626.49
390
25,626.49
391
1,699,429,200
392
Jun 15, 2017
['2017-06-15', '25,772.28', '25,772.28', '25,565.34', '25,565.34', '25,565.34', '1,658,076,900']
393
25,772.28
394
25,772.28
395
25,565.34
396
25,565.34
397
25,565.34
398
1,658,076,900
399
Jun 14, 2017
['2017-06-14', '25,915.46', '25,915.46', '25,713.02', '25,875.90', '25,875.90', '1,449,845,600']
400
25,915.46
401
25,915.46
402
25,713.02
403
25,875.90
404
25,875.90
405
1,449,845,600
406
Jun 13, 2017
['2017-06-13', '25,826.52', '25,883.22', '25,722.63', '25,852.10', '25,852.10', '1,316,444,700']
407
25,826.52
408
25,883.22
409
25,722.63
410
25,852.10
411
25,852.10
412
1,316,444,700
413
Jun 12, 2017
['2017-06-12', '25,925.45', '25,957.78', '25,689.23', '25,708.04', '25,708.04', '1,614,682,000']
414
25,925.45
415
25,957.78
416
25,689.23
417
25,708.04
418
25,708.04
419
1,614,682,000
420
Jun 09, 2017
['2017-06-09', '26,090.33', '26,090.33', '25,922.68', '26,030.29', '26,030.29', '2,889,395,400']
421
26,090.33
422
26,090.33
423
25,922.68
424
26,030.29
425
26,030.29
426
2,889,395,400
427
Jun 08, 2017
['2017-06-08', '25,974.00', '26,069.98', '25,923.21', '26,063.06', '26,063.06', '1,633,520,700']
428
25,974.00
429
26,069.98
430
25,923.21
431
26,063.06
432
26,063.06
433
1,633,520,700
434
Jun 07, 2017
['2017-06-07', '26,025.21', '26,073.44', '25,898.82', '25,974.16', '25,974.16', '1,999,503,900']
435
26,025.21
436
26,073.44
437
25,898.82
438
25,974.16
439
25,974.16
440
1,999,503,900
441
Jun 06, 2017
['2017-06-06', '25,819.53', '26,019.01', '25,805.02', '25,997.14', '25,997.14', '1,540,428,000']
442
25,819.53
443
26,019.01
444
25,805.02
445
25,997.14
446
25,997.14
447
1,540,428,000
448
Jun 05, 2017
['2017-06-05', '25,976.36', '25,998.66', '25,801.84', '25,862.99', '25,862.99', '1,766,176,100']
449
25,976.36
450
25,998.66
451
25,801.84
452
25,862.99
453
25,862.99
454
1,766,176,100
455
Jun 02, 2017
['2017-06-02', '25,926.06', '25,973.00', '25,851.85', '25,924.05', '25,924.05', '1,990,193,800']
456
25,926.06
457
25,973.00
458
25,851.85
459
25,924.05
460
25,924.05
461
1,990,193,800
462
Jun 01, 2017
['2017-06-01', '25,736.35', '25,834.75', '25,614.61', '25,809.22', '25,809.22', '2,017,055,200']
463
25,736.35
464
25,834.75
465
25,614.61
466
25,809.22
467
25,809.22
468
2,017,055,200
469
May 31, 2017
['2017-05-31', '25,706.45', '25,817.95', '25,650.06', '25,660.65', '25,660.65', '2,997,857,600']
470
25,706.45
471
25,817.95
472
25,650.06
473
25,660.65
474
25,660.65
475
2,997,857,600
476
May 29, 2017
['2017-05-29', '25,672.40', '25,744.72', '25,579.15', '25,701.63', '25,701.63', '1,077,784,400']
477
25,672.40
478
25,744.72
479
25,579.15
480
25,701.63
481
25,701.63
482
1,077,784,400
483
May 26, 2017
['2017-05-26', '25,670.98', '25,724.40', '25,588.70', '25,639.27', '25,639.27', '1,453,713,000']
484
25,670.98
485
25,724.40
486
25,588.70
487
25,639.27
488
25,639.27
489
1,453,713,000
490
May 25, 2017
['2017-05-25', '25,511.46', '25,680.67', '25,491.78', '25,630.78', '25,630.78', '1,890,794,600']
491
25,511.46
492
25,680.67
493
25,491.78
494
25,630.78
495
25,630.78
496
1,890,794,600
497
May 24, 2017
['2017-05-24', '25,382.26', '25,428.50', '25,296.66', '25,428.50', '25,428.50', '1,409,941,800']
498
25,382.26
499
25,428.50
500
25,296.66
501
25,428.50
502
25,428.50
503
1,409,941,800
504
May 23, 2017
['2017-05-23', '25,415.57', '25,486.98', '25,307.27', '25,403.15', '25,403.15', '1,758,690,200']
505
25,415.57
506
25,486.98
507
25,307.27
508
25,403.15
509
25,403.15
510
1,758,690,200
511
May 22, 2017
['2017-05-22', '25,318.29', '25,450.04', '25,201.34', '25,391.34', '25,391.34', '1,410,586,000']
512
25,318.29
513
25,450.04
514
25,201.34
515
25,391.34
516
25,391.34
517
1,410,586,000
518
May 19, 2017
['2017-05-19', '25,171.66', '25,266.22', '25,124.06', '25,174.87', '25,174.87', '1,312,777,700']
519
25,171.66
520
25,266.22
521
25,124.06
522
25,174.87
523
25,174.87
524
1,312,777,700
525
May 18, 2017
['2017-05-18', '25,034.19', '25,263.81', '25,025.05', '25,136.52', '25,136.52', '1,677,298,400']
526
25,034.19
527
25,263.81
528
25,025.05
529
25,136.52
530
25,136.52
531
1,677,298,400
532
May 17, 2017
['2017-05-17', '25,355.76', '25,374.95', '25,245.44', '25,293.63', '25,293.63', '1,512,406,100']
533
25,355.76
534
25,374.95
535
25,245.44
536
25,293.63
537
25,293.63
538
1,512,406,100
539
May 16, 2017
['2017-05-16', '25,413.35', '25,413.35', '25,228.46', '25,335.94', '25,335.94', '1,797,601,700']
540
25,413.35
541
25,413.35
542
25,228.46
543
25,335.94
544
25,335.94
545
1,797,601,700
546
May 15, 2017
['2017-05-15', '25,233.31', '25,385.72', '25,213.47', '25,371.59', '25,371.59', '2,212,734,400']
547
25,233.31
548
25,385.72
549
25,213.47
550
25,371.59
551
25,371.59
552
2,212,734,400
553
May 12, 2017
['2017-05-12', '25,126.48', '25,211.28', '25,087.32', '25,156.34', '25,156.34', '1,417,408,900']
554
25,126.48
555
25,211.28
556
25,087.32
557
25,156.34
558
25,156.34
559
1,417,408,900
560
May 11, 2017
['2017-05-11', '25,101.53', '25,203.54', '25,024.76', '25,125.55', '25,125.55', '1,642,633,800']
561
25,101.53
562
25,203.54
563
25,024.76
564
25,125.55
565
25,125.55
566
1,642,633,800
567
May 10, 2017
['2017-05-10', '24,931.82', '25,164.97', '24,931.82', '25,015.42', '25,015.42', '2,297,649,800']
568
24,931.82
569
25,164.97
570
24,931.82
571
25,015.42
572
25,015.42
573
2,297,649,800
574
May 09, 2017
['2017-05-09', '24,656.95', '24,889.83', '24,548.97', '24,889.03', '24,889.03', '1,381,056,000']
575
24,656.95
576
24,889.83
577
24,548.97
578
24,889.03
579
24,889.03
580
1,381,056,000
581
May 08, 2017
['2017-05-08', '24,604.29', '24,624.21', '24,476.20', '24,577.91', '24,577.91', '1,357,855,500']
582
24,604.29
583
24,624.21
584
24,476.20
585
24,577.91
586
24,577.91
587
1,357,855,500
588
May 05, 2017
['2017-05-05', '24,625.35', '24,634.28', '24,358.72', '24,476.35', '24,476.35', '2,024,201,800']
589
24,625.35
590
24,634.28
591
24,358.72
592
24,476.35
593
24,476.35
594
2,024,201,800
595
May 04, 2017
['2017-05-04', '24,680.45', '24,683.88', '24,530.93', '24,683.88', '24,683.88', '1,760,179,900']
596
24,680.45
597
24,683.88
598
24,530.93
599
24,683.88
600
24,683.88
601
1,760,179,900
602
May 02, 2017
['2017-05-02', '24,773.80', '24,773.80', '24,577.33', '24,696.13', '24,696.13', '1,605,780,100']
603
24,773.80
604
24,773.80
605
24,577.33
606
24,696.13
607
24,696.13
608
1,605,780,100
609
Apr 28, 2017
['2017-04-28', '24,691.29', '24,697.03', '24,563.77', '24,615.13', '24,615.13', '1,181,584,600']
610
24,691.29
611
24,697.03
612
24,563.77
613
24,615.13
614
24,615.13
615
1,181,584,600
616
Apr 27, 2017
['2017-04-27', '24,663.10', '24,717.44', '24,455.12', '24,698.48', '24,698.48', '1,567,031,000']
617
24,663.10
618
24,717.44
619
24,455.12
620
24,698.48
621
24,698.48
622
1,567,031,000
623
Apr 26, 2017
['2017-04-26', '24,563.25', '24,637.85', '24,515.23', '24,578.43', '24,578.43', '1,668,740,700']
624
24,563.25
625
24,637.85
626
24,515.23
627
24,578.43
628
24,578.43
629
1,668,740,700
630
Apr 25, 2017
['2017-04-25', '24,204.78', '24,455.94', '24,201.91', '24,455.94', '24,455.94', '1,880,693,800']
631
24,204.78
632
24,455.94
633
24,201.91
634
24,455.94
635
24,455.94
636
1,880,693,800
637
Apr 24, 2017
['2017-04-24', '24,185.76', '24,206.44', '23,958.18', '24,139.48', '24,139.48', '1,338,069,100']
638
24,185.76
639
24,206.44
640
23,958.18
641
24,139.48
642
24,139.48
643
1,338,069,100
644
Apr 21, 2017
['2017-04-21', '24,143.04', '24,190.14', '23,991.87', '24,042.02', '24,042.02', '1,345,955,400']
645
24,143.04
646
24,190.14
647
23,991.87
648
24,042.02
649
24,042.02
650
1,345,955,400
651
Apr 20, 2017
['2017-04-20', '23,851.02', '24,058.87', '23,827.07', '24,056.98', '24,056.98', '1,512,891,800']
652
23,851.02
653
24,058.87
654
23,827.07
655
24,056.98
656
24,056.98
657
1,512,891,800
658
Apr 19, 2017
['2017-04-19', '23,875.98', '23,893.14', '23,723.87', '23,825.88', '23,825.88', '1,568,253,100']
659
23,875.98
660
23,893.14
661
23,723.87
662
23,825.88
663
23,825.88
664
1,568,253,100
665
Apr 18, 2017
['2017-04-18', '24,268.17', '24,276.31', '23,892.59', '23,924.54', '23,924.54', '1,552,809,600']
666
24,268.17
667
24,276.31
668
23,892.59
669
23,924.54
670
23,924.54
671
1,552,809,600
672
Apr 13, 2017
['2017-04-13', '24,173.42', '24,378.38', '24,158.16', '24,261.66', '24,261.66', '1,334,077,800']
673
24,173.42
674
24,378.38
675
24,158.16
676
24,261.66
677
24,261.66
678
1,334,077,800
679
Apr 12, 2017
['2017-04-12', '24,068.91', '24,313.50', '23,994.13', '24,313.50', '24,313.50', '1,534,864,800']
680
24,068.91
681
24,313.50
682
23,994.13
683
24,313.50
684
24,313.50
685
1,534,864,800
686
Apr 11, 2017
['2017-04-11', '24,280.87', '24,318.15', '24,007.85', '24,088.46', '24,088.46', '1,803,272,800']
687
24,280.87
688
24,318.15
689
24,007.85
690
24,088.46
691
24,088.46
692
1,803,272,800
693
Apr 10, 2017
['2017-04-10', '24,302.01', '24,314.66', '24,215.54', '24,262.18', '24,262.18', '1,193,963,800']
694
24,302.01
695
24,314.66
696
24,215.54
697
24,262.18
698
24,262.18
699

[]
[]
701
[]
[]
0
Mar 31, 2017
['2017-03-31', '24,305.53', '24,329.98', '24,105.38', '24,111.59', '24,111.59', '1,733,165,500']
1
24,305.53
2
24,329.98
3
24,105.38
4
24,111.59
5
24,111.59
6
1,733,165,500
7
Mar 30, 2017
['2017-03-30', '24,429.12', '24,431.12', '24,250.40', '24,301.09', '24,301.09', '1,768,917,100']
8
24,429.12
9
24,431.12
10
24,250.40
11
24,301.09
12
24,301.09
13
1,768,917,100
14
Mar 29, 2017
['2017-03-29', '24,470.66', '24,470.66', '24,330.70', '24,392.05', '24,392.05', '1,834,977,400']
15
24,470.66
16
24,470.66
17
24,330.70
18
24,392.05
19
24,392.05
20
1,834,977,400
21
Mar 28, 2017
['2017-03-28', '24,329.17', '24,360.00', '24,274.52', '24,345.87', '24,345.87', '1,506,216,800']
22
24,329.17
23
24,360.00
24
24,274.52
25
24,345.87
26
24,345.87
27
1,506,216,800
28
Mar 27, 2017
['2017-03-27', '24,235.69', '24,434.90', '24,138.78', '24,193.70', '24,193.70', '1,730,336,000']
29
24,235.69
30
24,434.90
31
24,138.78
32
24,193.70
33
24,193.70
34
1,730,336,000
35
Mar 24, 2017
['2017-03-24', '24,396.41', '24,420.77', '24,263.17', '24,358.27', '24,358.27', '1,784,280,200']
36
24,396.41
37
24,420.77
38
24,263.17
39
24,358.27
40
24,358.27
41
1,784,280,200
42
Mar 23, 2017
['2017-03-23', '24,381.04', '24,466.73', '24,271.26', '24,327.70', '24,327.70', '1,795,481,600']
43
24,381.04
44
24,466.73
45
24,271.26
46
24,327.70
47
24,327.70
48
1,795,481,600
49
Mar 22, 2017
['2017-03-22', '24,336.33', '24,380.42', '24,207.10', '24,320.41', '24,320.41', '2,136,581,500']
50
24,336.33
51
24,380.42
52
24,207.10
53
24,320.41
54
24,320.41
55
2,136,581,500
56
Mar 21, 2017
['2017-03-21', '24,565.73', '24,656.65', '24,500.35', '24,593.12', '24,593.12', '2,055,170,800']
57
24,565.73
58
24,656.65
59
24,500.35
60
24,593.12
61
24,593.12
62
2,055,170,800
63
Mar 20, 2017
['2017-03-20', '24,312.57', '24,501.99', '24,312.57', '24,501.99', '24,501.99', '1,716,660,600']
64
24,312.57
65
24,501.99
66
24,312.57
67
24,501.99
68
24,501.99
69
1,716,660,600
70
Mar 17, 2017
['2017-03-17', '24,376.13', '24,385.81', '24,237.97', '24,309.93', '24,309.93', '2,512,650,300']
71
24,376.13
72
24,385.81
73
24,237.97
74
24,309.93
75
24,309.93
76
2,512,650,300
77
Mar 16, 2017
['2017-03-16', '24,101.98', '24,288.28', '24,003.75', '24,288.28', '24,288.28', '2,576,719,000']
78
24,101.98
79
24,288.28
80
24,003.75
81
24,288.28
82
24,288.28
83
2,576,719,000
84
Mar 15, 2017
['2017-03-15', '23,705.07', '23,842.81', '23,645.51', '23,792.85', '23,792.85', '1,352,441,800']
85
23,705.07
86
23,842.81
87
23,645.51
88
23,792.85
89
23,792.85
90
1,352,441,800
91
Mar 14, 2017
['2017-03-14', '23,871.00', '23,918.12', '23,768.34', '23,827.95', '23,827.95', '1,857,167,800']
92
23,871.00
93
23,918.12
94
23,768.34
95
23,827.95
96
23,827.95
97
1,857,167,800
98
Mar 13, 2017
['2017-03-13', '23,643.30', '23,877.59', '23,567.93', '23,829.67', '23,829.67', '2,016,201,800']
99
23,643.30
100
23,877.59
101
23,567.93
102
23,829.67
103
23,829.67
104
2,016,201,800
105
Mar 10, 2017
['2017-03-10', '23,534.98', '23,603.77', '23,438.86', '23,568.67', '23,568.67', '1,534,086,200']
106
23,534.98
107
23,603.77
108
23,438.86
109
23,568.67
110
23,568.67
111
1,534,086,200
112
Mar 09, 2017
['2017-03-09', '23,667.77', '23,673.58', '23,456.06', '23,501.56', '23,501.56', '1,781,279,500']
113
23,667.77
114
23,673.58
115
23,456.06
116
23,501.56
117
23,501.56
118
1,781,279,500
119
Mar 08, 2017
['2017-03-08', '23,627.28', '23,816.23', '23,563.14', '23,782.27', '23,782.27', '1,823,218,000']
120
23,627.28
121
23,816.23
122
23,563.14
123
23,782.27
124
23,782.27
125
1,823,218,000
126
Mar 07, 2017
['2017-03-07', '23,630.35', '23,728.00', '23,585.77', '23,681.07', '23,681.07', '1,282,674,500']
127
23,630.35
128
23,728.00
129
23,585.77
130
23,681.07
131
23,681.07
132
1,282,674,500
133
Mar 06, 2017
['2017-03-06', '23,600.49', '23,691.05', '23,574.28', '23,596.28', '23,596.28', '1,442,731,400']
134
23,600.49
135
23,691.05
136
23,574.28
137
23,596.28
138
23,596.28
139
1,442,731,400
140
Mar 03, 2017
['2017-03-03', '23,618.36', '23,635.24', '23,511.60', '23,552.72', '23,552.72', '2,387,983,900']
141
23,618.36
142
23,635.24
143
23,511.60
144
23,552.72
145
23,552.72
146
2,387,983,900
147
Mar 02, 2017
['2017-03-02', '24,044.48', '24,080.87', '23,694.33', '23,728.07', '23,728.07', '2,111,361,200']
148
24,044.48
149
24,080.87
150
23,694.33
151
23,728.07
152
23,728.07
153
2,111,361,200
154
Mar 01, 2017
['2017-03-01', '23,849.22', '23,857.28', '23,730.05', '23,776.49', '23,776.49', '1,648,831,300']
155
23,849.22
156
23,857.28
157
23,730.05
158
23,776.49
159
23,776.49
160
1,648,831,300
161
Feb 28, 2017
['2017-02-28', '23,952.64', '24,007.81', '23,740.73', '23,740.73', '23,740.73', '1,666,247,300']
162
23,952.64
163
24,007.81
164
23,740.73
165
23,740.73
166
23,740.73
167
1,666,247,300
168
Feb 27, 2017
['2017-02-27', '23,941.81', '24,067.68', '23,822.88', '23,925.05', '23,925.05', '1,727,456,200']
169
23,941.81
170
24,067.68
171
23,822.88
172
23,925.05
173
23,925.05
174
1,727,456,200
175
Feb 24, 2017
['2017-02-24', '24,115.61', '24,121.91', '23,958.13', '23,965.70', '23,965.70', '1,750,717,000']
176
24,115.61
177
24,121.91
178
23,958.13
179
23,965.70
180
23,965.70
181
1,750,717,000
182
Feb 23, 2017
['2017-02-23', '24,122.18', '24,216.53', '24,046.91', '24,114.86', '24,114.86', '1,880,958,700']
183
24,122.18
184
24,216.53
185
24,046.91
186
24,114.86
187
24,114.86
188
1,880,958,700
189
Feb 22, 2017
['2017-02-22', '24,059.09', '24,201.96', '23,999.55', '24,201.96', '24,201.96', '2,230,148,000']
190
24,059.09
191
24,201.96
192
23,999.55
193
24,201.96
194
24,201.96
195
2,230,148,000
196
Feb 21, 2017
['2017-02-21', '24,174.11', '24,213.64', '23,909.15', '23,963.63', '23,963.63', '1,839,886,700']
197
24,174.11
198
24,213.64
199
23,909.15
200
23,963.63
201
23,963.63
202
1,839,886,700
203
Feb 20, 2017
['2017-02-20', '24,066.00', '24,202.34', '24,022.15', '24,146.08', '24,146.08', '1,936,955,000']
204
24,066.00
205
24,202.34
206
24,022.15
207
24,146.08
208
24,146.08
209
1,936,955,000
210
Feb 17, 2017
['2017-02-17', '24,077.87', '24,106.34', '23,944.68', '24,033.74', '24,033.74', '2,302,691,000']
211
24,077.87
212
24,106.34
213
23,944.68
214
24,033.74
215
24,033.74
216
2,302,691,000
217
Feb 16, 2017
['2017-02-16', '24,139.31', '24,161.39', '23,969.57', '24,107.70', '24,107.70', '3,806,666,400']
218
24,139.31
219
24,161.39
220
23,969.57
221
24,107.70
222
24,107.70
223
3,806,666,400
224
Feb 15, 2017
['2017-02-15', '23,771.95', '24,067.62', '23,771.95', '23,994.87', '23,994.87', '3,843,901,700']
225
23,771.95
226
24,067.62
227
23,771.95
228
23,994.87
229
23,994.87
230
3,843,901,700
231
Feb 14, 2017
['2017-02-14', '23,695.29', '23,735.11', '23,614.47', '23,703.01', '23,703.01', '1,957,113,500']
232
23,695.29
233
23,735.11
234
23,614.47
235
23,703.01
236
23,703.01
237
1,957,113,500
238
Feb 13, 2017
['2017-02-13', '23,664.53', '23,751.92', '23,615.39', '23,710.98', '23,710.98', '1,990,274,600']
239
23,664.53
240
23,751.92
241
23,615.39
242
23,710.98
243
23,710.98
244
1,990,274,600
245
Feb 10, 2017
['2017-02-10', '23,645.90', '23,718.47', '23,573.85', '23,574.98', '23,574.98', '2,143,167,300']
246
23,645.90
247
23,718.47
248
23,573.85
249
23,574.98
250
23,574.98
251
2,143,167,300
252
Feb 09, 2017
['2017-02-09', '23,533.52', '23,644.63', '23,489.65', '23,525.14', '23,525.14', '2,741,007,400']
253
23,533.52
254
23,644.63
255
23,489.65
256
23,525.14
257
23,525.14
258
2,741,007,400
259
Feb 08, 2017
['2017-02-08', '23,284.76', '23,520.77', '23,160.99', '23,485.13', '23,485.13', '2,601,105,500']
260
23,284.76
261
23,520.77
262
23,160.99
263
23,485.13
264
23,485.13
265
2,601,105,500
266
Feb 07, 2017
['2017-02-07', '23,287.89', '23,403.60', '23,256.69', '23,331.57', '23,331.57', '1,523,355,600']
267
23,287.89
268
23,403.60
269
23,256.69
270
23,331.57
271
23,331.57
272
1,523,355,600
273
Feb 06, 2017
['2017-02-06', '23,239.29', '23,348.24', '23,149.70', '23,348.24', '23,348.24', '1,439,947,300']
274
23,239.29
275
23,348.24
276
23,149.70
277
23,348.24
278
23,348.24
279
1,439,947,300
280
Feb 03, 2017
['2017-02-03', '23,216.97', '23,226.92', '22,997.46', '23,129.21', '23,129.21', '1,339,282,100']
281
23,216.97
282
23,226.92
283
22,997.46
284
23,129.21
285
23,129.21
286
1,339,282,100
287
Feb 02, 2017
['2017-02-02', '23,309.46', '23,439.02', '23,131.37', '23,184.52', '23,184.52', '987,795,900']
288
23,309.46
289
23,439.02
290
23,131.37
291
23,184.52
292
23,184.52
293
987,795,900
294
Feb 01, 2017
['2017-02-01', '23,211.88', '23,318.39', '23,082.62', '23,318.39', '23,318.39', '1,515,037,600']
295
23,211.88
296
23,318.39
297
23,082.62
298
23,318.39
299
23,318.39
300
1,515,037,600
301
Jan 27, 2017
['2017-01-27', '23,339.15', '23,397.09', '23,307.05', '23,360.78', '23,360.78', '777,897,700']
302
23,339.15
303
23,397.09
304
23,307.05
305
23,360.78
306
23,360.78
307
777,897,700
308
Jan 26, 2017
['2017-01-26', '23,173.46', '23,386.41', '23,145.31', '23,374.17', '23,374.17', '1,856,554,500']
309
23,173.46
310
23,386.41
311
23,145.31
312
23,374.17
313
23,374.17
314
1,856,554,500
315
Jan 25, 2017
['2017-01-25', '23,066.40', '23,066.40', '22,961.38', '23,049.12', '23,049.12', '1,185,813,200']
316
23,066.40
317
23,066.40
318
22,961.38
319
23,049.12
320
23,049.12
321
1,185,813,200
322
Jan 24, 2017
['2017-01-24', '22,965.25', '22,986.45', '22,907.78', '22,949.86', '22,949.86', '1,462,887,100']
323
22,965.25
324
22,986.45
325
22,907.78
326
22,949.86
327
22,949.86
328
1,462,887,100
329
Jan 23, 2017
['2017-01-23', '22,926.30', '23,068.08', '22,861.29', '22,898.52', '22,898.52', '1,068,403,800']
330
22,926.30
331
23,068.08
332
22,861.29
333
22,898.52
334
22,898.52
335
1,068,403,800
336
Jan 20, 2017
['2017-01-20', '22,966.53', '22,987.68', '22,858.25', '22,885.91', '22,885.91', '1,207,476,100']
337
22,966.53
338
22,987.68
339
22,858.25
340
22,885.91
341
22,885.91
342
1,207,476,100
343
Jan 19, 2017
['2017-01-19', '23,104.35', '23,104.35', '22,941.96', '23,049.96', '23,049.96', '1,174,126,300']
344
23,104.35
345
23,104.35
346
22,941.96
347
23,049.96
348
23,049.96
349
1,174,126,300
350
Jan 18, 2017
['2017-01-18', '22,889.33', '23,151.75', '22,882.02', '23,098.26', '23,098.26', '1,689,344,500']
351
22,889.33
352
23,151.75
353
22,882.02
354
23,098.26
355
23,098.26
356
1,689,344,500
357
Jan 17, 2017
['2017-01-17', '22,819.87', '22,867.84', '22,710.93', '22,840.97', '22,840.97', '1,019,618,000']
358
22,819.87
359
22,867.84
360
22,710.93
361
22,840.97
362
22,840.97
363
1,019,618,000
364
Jan 16, 2017
['2017-01-16', '22,895.36', '22,908.86', '22,657.35', '22,718.15', '22,718.15', '1,313,357,700']
365
22,895.36
366
22,908.86
367
22,657.35
368
22,718.15
369
22,718.15
370
1,313,357,700
371
Jan 13, 2017
['2017-01-13', '22,879.57', '22,971.45', '22,859.28', '22,937.38', '22,937.38', '1,371,840,300']
372
22,879.57
373
22,971.45
374
22,859.28
375
22,937.38
376
22,937.38
377
1,371,840,300
378
Jan 12, 2017
['2017-01-12', '22,956.44', '22,971.49', '22,751.67', '22,829.02', '22,829.02', '1,454,667,000']
379
22,956.44
380
22,971.49
381
22,751.67
382
22,829.02
383
22,829.02
384
1,454,667,000
385
Jan 11, 2017
['2017-01-11', '22,816.01', '22,944.58', '22,767.37', '22,935.35', '22,935.35', '1,554,104,200']
386
22,816.01
387
22,944.58
388
22,767.37
389
22,935.35
390
22,935.35
391
1,554,104,200
392
Jan 10, 2017
['2017-01-10', '22,561.17', '22,744.85', '22,549.86', '22,744.85', '22,744.85', '1,422,515,900']
393
22,561.17
394
22,744.85
395
22,549.86
396
22,744.85
397
22,744.85
398
1,422,515,900
399
Jan 09, 2017
['2017-01-09', '22,561.11', '22,626.43', '22,476.35', '22,558.69', '22,558.69', '1,303,532,900']
400
22,561.11
401
22,626.43
402
22,476.35
403
22,558.69
404
22,558.69
405
1,303,532,900
406
Jan 06, 2017
['2017-01-06', '22,583.29', '22,605.66', '22,445.78', '22,503.01', '22,503.01', '1,389,973,700']
407
22,583.29
408
22,605.66
409
22,445.78
410
22,503.01
411
22,503.01
412
1,389,973,700
413
Jan 05, 2017
['2017-01-05', '22,302.64', '22,483.01', '22,230.31', '22,456.69', '22,456.69', '1,830,652,300']
414
22,302.64
415
22,483.01
416
22,230.31
417
22,456.69
418
22,456.69
419
1,830,652,300
420
Jan 04, 2017
['2017-01-04', '22,201.08', '22,228.06', '22,076.63', '22,134.47', '22,134.47', '1,437,672,200']
421
22,201.08
422
22,228.06
423
22,076.63
424
22,134.47
425
22,134.47
426
1,437,672,200
427
Jan 03, 2017
['2017-01-03', '21,993.36', '22,189.31', '21,883.82', '22,150.40', '22,150.40', '1,302,378,400']
428
21,993.36
429
22,189.31
430
21,883.82
431
22,150.40
432
22,150.40
433
1,302,378,400
434
Dec 30, 2016
['2016-12-30', '21,818.91', '22,069.62', '21,818.91', '22,000.56', '22,000.56', '2,396,676,500']
435
21,818.91
436
22,069.62
437
21,818.91
438
22,000.56
439
22,000.56
440
2,396,676,500
441
Dec 29, 2016
['2016-12-29', '21,591.04', '21,810.40', '21,587.07', '21,790.91', '21,790.91', '1,875,142,100']
442
21,591.04
443
21,810.40
444
21,587.07
445
21,790.91
446
21,790.91
447
1,875,142,100
448
Dec 28, 2016
['2016-12-28', '21,562.70', '21,811.96', '21,488.82', '21,754.74', '21,754.74', '2,173,239,900']
449
21,562.70
450
21,811.96
451
21,488.82
452
21,754.74
453
21,754.74
454
2,173,239,900
455
Dec 23, 2016
['2016-12-23', '21,553.78', '21,601.07', '21,491.83', '21,574.76', '21,574.76', '1,775,512,200']
456
21,553.78
457
21,601.07
458
21,491.83
459
21,574.76
460
21,574.76
461
1,775,512,200
462
Dec 22, 2016
['2016-12-22', '21,800.22', '21,822.18', '21,594.58', '21,636.20', '21,636.20', '1,434,735,500']
463
21,800.22
464
21,822.18
465
21,594.58
466
21,636.20
467
21,636.20
468
1,434,735,500
469
Dec 21, 2016
['2016-12-21', '21,770.89', '21,910.39', '21,755.85', '21,809.80', '21,809.80', '1,206,759,600']
470
21,770.89
471
21,910.39
472
21,755.85
473
21,809.80
474
21,809.80
475
1,206,759,600
476
Dec 20, 2016
['2016-12-20', '21,767.61', '21,873.56', '21,667.19', '21,729.06', '21,729.06', '1,297,152,100']
477
21,767.61
478
21,873.56
479
21,667.19
480
21,729.06
481
21,729.06
482
1,297,152,100
483
Dec 19, 2016
['2016-12-19', '21,945.84', '21,955.94', '21,786.56', '21,832.68', '21,832.68', '1,328,500,400']
484
21,945.84
485
21,955.94
486
21,786.56
487
21,832.68
488
21,832.68
489
1,328,500,400
490
Dec 16, 2016
['2016-12-16', '21,996.38', '22,155.14', '21,965.68', '22,020.75', '22,020.75', '1,899,711,800']
491
21,996.38
492
22,155.14
493
21,965.68
494
22,020.75
495
22,020.75
496
1,899,711,800
497
Dec 15, 2016
['2016-12-15', '22,257.71', '22,305.07', '21,999.30', '22,059.40', '22,059.40', '2,505,720,900']
498
22,257.71
499
22,305.07
500
21,999.30
501
22,059.40
502
22,059.40
503
2,505,720,900
504
Dec 14, 2016
['2016-12-14', '22,596.71', '22,627.60', '22,456.62', '22,456.62', '22,456.62', '1,821,093,300']
505
22,596.71
506
22,627.60
507
22,456.62
508
22,456.62
509
22,456.62
510
1,821,093,300
511
Dec 13, 2016
['2016-12-13', '22,407.62', '22,458.42', '22,292.65', '22,446.70', '22,446.70', '1,723,223,600']
512
22,407.62
513
22,458.42
514
22,292.65
515
22,446.70
516
22,446.70
517
1,723,223,600
518
Dec 12, 2016
['2016-12-12', '22,860.27', '22,863.61', '22,375.58', '22,433.02', '22,433.02', '2,014,527,900']
519
22,860.27
520
22,863.61
521
22,375.58
522
22,433.02
523
22,433.02
524
2,014,527,900
525
Dec 09, 2016
['2016-12-09', '22,765.84', '22,813.85', '22,660.22', '22,760.98', '22,760.98', '1,576,021,700']
526
22,765.84
527
22,813.85
528
22,660.22
529
22,760.98
530
22,760.98
531
1,576,021,700
532
Dec 08, 2016
['2016-12-08', '23,027.38', '23,076.24', '22,817.32', '22,861.84', '22,861.84', '1,711,745,400']
533
23,027.38
534
23,076.24
535
22,817.32
536
22,861.84
537
22,861.84
538
1,711,745,400
539
Dec 07, 2016
['2016-12-07', '22,805.13', '22,843.01', '22,708.88', '22,800.92', '22,800.92', '1,110,472,700']
540
22,805.13
541
22,843.01
542
22,708.88
543
22,800.92
544
22,800.92
545
1,110,472,700
546
Dec 06, 2016
['2016-12-06', '22,694.27', '22,746.67', '22,625.32', '22,675.15', '22,675.15', '1,261,679,800']
547
22,694.27
548
22,746.67
549
22,625.32
550
22,675.15
551
22,675.15
552
1,261,679,800
553
Dec 05, 2016
['2016-12-05', '22,580.75', '22,628.13', '22,375.28', '22,505.55', '22,505.55', '1,626,049,800']
554
22,580.75
555
22,628.13
556
22,375.28
557
22,505.55
558
22,505.55
559
1,626,049,800
560
Dec 02, 2016
['2016-12-02', '22,736.84', '22,756.01', '22,559.20', '22,564.82', '22,564.82', '2,479,074,200']
561
22,736.84
562
22,756.01
563
22,559.20
564
22,564.82
565
22,564.82
566
2,479,074,200
567
Dec 01, 2016
['2016-12-01', '22,948.65', '23,012.28', '22,837.53', '22,878.23', '22,878.23', '2,119,590,600']
568
22,948.65
569
23,012.28
570
22,837.53
571
22,878.23
572
22,878.23
573
2,119,590,600
574
Nov 30, 2016
['2016-11-30', '22,842.36', '22,889.47', '22,755.00', '22,789.77', '22,789.77', '2,062,930,000']
575
22,842.36
576
22,889.47
577
22,755.00
578
22,789.77
579
22,789.77
580
2,062,930,000
581
Nov 29, 2016
['2016-11-29', '22,739.51', '22,868.14', '22,724.59', '22,737.07', '22,737.07', '1,695,023,200']
582
22,739.51
583
22,868.14
584
22,724.59
585
22,737.07
586
22,737.07
587
1,695,023,200
588
Nov 28, 2016
['2016-11-28', '22,738.94', '22,964.02', '22,738.94', '22,830.57', '22,830.57', '1,816,314,100']
589
22,738.94
590
22,964.02
591
22,738.94
592
22,830.57
593
22,830.57
594
1,816,314,100
595
Nov 25, 2016
['2016-11-25', '22,609.22', '22,764.34', '22,589.53', '22,723.45', '22,723.45', '1,385,320,300']
596
22,609.22
597
22,764.34
598
22,589.53
599
22,723.45
600
22,723.45
601
1,385,320,300
602
Nov 24, 2016
['2016-11-24', '22,574.82', '22,647.38', '22,487.54', '22,608.49', '22,608.49', '1,138,055,700']
603
22,574.82
604
22,647.38
605
22,487.54
606
22,608.49
607
22,608.49
608
1,138,055,700
609
Nov 23, 2016
['2016-11-23', '22,702.41', '22,804.26', '22,640.95', '22,676.69', '22,676.69', '1,764,207,800']
610
22,702.41
611
22,804.26
612
22,640.95
613
22,676.69
614
22,676.69
615
1,764,207,800
616
Nov 22, 2016
['2016-11-22', '22,491.71', '22,719.42', '22,484.60', '22,678.07', '22,678.07', '1,851,269,200']
617
22,491.71
618
22,719.42
619
22,484.60
620
22,678.07
621
22,678.07
622
1,851,269,200
623
Nov 21, 2016
['2016-11-21', '22,313.04', '22,480.75', '22,227.80', '22,357.78', '22,357.78', '1,370,598,600']
624
22,313.04
625
22,480.75
626
22,227.80
627
22,357.78
628
22,357.78
629
1,370,598,600
630
Nov 18, 2016
['2016-11-18', '22,239.23', '22,374.36', '22,146.88', '22,344.21', '22,344.21', '1,128,764,800']
631
22,239.23
632
22,374.36
633
22,146.88
634
22,344.21
635
22,344.21
636
1,128,764,800
637
Nov 17, 2016
['2016-11-17', '22,170.07', '22,367.47', '22,114.02', '22,262.88', '22,262.88', '1,355,418,500']
638
22,170.07
639
22,367.47
640
22,114.02
641
22,262.88
642
22,262.88
643
1,355,418,500
644
Nov 16, 2016
['2016-11-16', '22,439.98', '22,499.39', '22,280.53', '22,280.53', '22,280.53', '1,609,770,500']
645
22,439.98
646
22,499.39
647
22,280.53
648
22,280.53
649
22,280.53
650
1,609,770,500
651
Nov 15, 2016
['2016-11-15', '22,270.90', '22,411.12', '22,254.09', '22,323.91', '22,323.91', '1,461,449,900']
652
22,270.90
653
22,411.12
654
22,254.09
655
22,323.91
656
22,323.91
657
1,461,449,900
658
Nov 14, 2016
['2016-11-14', '22,344.23', '22,359.01', '22,118.87', '22,222.22', '22,222.22', '1,910,149,300']
659
22,344.23
660
22,359.01
661
22,118.87
662
22,222.22
663
22,222.22
664
1,910,149,300
665
Nov 11, 2016
['2016-11-11', '22,622.46', '22,673.31', '22,442.75', '22,531.09', '22,531.09', '2,105,351,100']
666
22,622.46
667
22,673.31
668
22,442.75
669
22,531.09
670
22,531.09
671
2,105,351,100
672
Nov 10, 2016
['2016-11-10', '22,848.74', '22,918.34', '22,777.51', '22,839.11', '22,839.11', '1,594,983,400']
673
22,848.74
674
22,918.34
675
22,777.51
676
22,839.11
677
22,839.11
678
1,594,983,400
679
Nov 09, 2016
['2016-11-09', '23,048.32', '23,048.32', '21,957.71', '22,415.19', '22,415.19', '3,548,427,000']
680
23,048.32
681
23,048.32
682
21,957.71
683
22,415.19
684
22,415.19
685
3,548,427,000
686
Nov 08, 2016
['2016-11-08', '22,981.91', '22,996.97', '22,820.39', '22,909.47', '22,909.47', '1,015,231,100']
687
22,981.91
688
22,996.97
689
22,820.39
690
22,909.47
691
22,909.47
692
1,015,231,100
693
Nov 07, 2016

[]
[]
701
[]
[]
0
Dec 02, 2016
['2016-12-02', '22,736.84', '22,756.01', '22,559.20', '22,564.82', '22,564.82', '2,479,074,200']
1
22,736.84
2
22,756.01
3
22,559.20
4
22,564.82
5
22,564.82
6
2,479,074,200
7
Dec 01, 2016
['2016-12-01', '22,948.65', '23,012.28', '22,837.53', '22,878.23', '22,878.23', '2,119,590,600']
8
22,948.65
9
23,012.28
10
22,837.53
11
22,878.23
12
22,878.23
13
2,119,590,600
14
Nov 30, 2016
['2016-11-30', '22,842.36', '22,889.47', '22,755.00', '22,789.77', '22,789.77', '2,062,930,000']
15
22,842.36
16
22,889.47
17
22,755.00
18
22,789.77
19
22,789.77
20
2,062,930,000
21
Nov 29, 2016
['2016-11-29', '22,739.51', '22,868.14', '22,724.59', '22,737.07', '22,737.07', '1,695,023,200']
22
22,739.51
23
22,868.14
24
22,724.59
25
22,737.07
26
22,737.07
27
1,695,023,200
28
Nov 28, 2016
['2016-11-28', '22,738.94', '22,964.02', '22,738.94', '22,830.57', '22,830.57', '1,816,314,100']
29
22,738.94
30
22,964.02
31
22,738.94
32
22,830.57
33
22,830.57
34
1,816,314,100
35
Nov 25, 2016
['2016-11-25', '22,609.22', '22,764.34', '22,589.53', '22,723.45', '22,723.45', '1,385,320,300']
36
22,609.22
37
22,764.34
38
22,589.53
39
22,723.45
40
22,723.45
41
1,385,320,300
42
Nov 24, 2016
['2016-11-24', '22,574.82', '22,647.38', '22,487.54', '22,608.49', '22,608.49', '1,138,055,700']
43
22,574.82
44
22,647.38
45
22,487.54
46
22,608.49
47
22,608.49
48
1,138,055,700
49
Nov 23, 2016
['2016-11-23', '22,702.41', '22,804.26', '22,640.95', '22,676.69', '22,676.69', '1,764,207,800']
50
22,702.41
51
22,804.26
52
22,640.95
53
22,676.69
54
22,676.69
55
1,764,207,800
56
Nov 22, 2016
['2016-11-22', '22,491.71', '22,719.42', '22,484.60', '22,678.07', '22,678.07', '1,851,269,200']
57
22,491.71
58
22,719.42
59
22,484.60
60
22,678.07
61
22,678.07
62
1,851,269,200
63
Nov 21, 2016
['2016-11-21', '22,313.04', '22,480.75', '22,227.80', '22,357.78', '22,357.78', '1,370,598,600']
64
22,313.04
65
22,480.75
66
22,227.80
67
22,357.78
68
22,357.78
69
1,370,598,600
70
Nov 18, 2016
['2016-11-18', '22,239.23', '22,374.36', '22,146.88', '22,344.21', '22,344.21', '1,128,764,800']
71
22,239.23
72
22,374.36
73
22,146.88
74
22,344.21
75
22,344.21
76
1,128,764,800
77
Nov 17, 2016
['2016-11-17', '22,170.07', '22,367.47', '22,114.02', '22,262.88', '22,262.88', '1,355,418,500']
78
22,170.07
79
22,367.47
80
22,114.02
81
22,262.88
82
22,262.88
83
1,355,418,500
84
Nov 16, 2016
['2016-11-16', '22,439.98', '22,499.39', '22,280.53', '22,280.53', '22,280.53', '1,609,770,500']
85
22,439.98
86
22,499.39
87
22,280.53
88
22,280.53
89
22,280.53
90
1,609,770,500
91
Nov 15, 2016
['2016-11-15', '22,270.90', '22,411.12', '22,254.09', '22,323.91', '22,323.91', '1,461,449,900']
92
22,270.90
93
22,411.12
94
22,254.09
95
22,323.91
96
22,323.91
97
1,461,449,900
98
Nov 14, 2016
['2016-11-14', '22,344.23', '22,359.01', '22,118.87', '22,222.22', '22,222.22', '1,910,149,300']
99
22,344.23
100
22,359.01
101
22,118.87
102
22,222.22
103
22,222.22
104
1,910,149,300
105
Nov 11, 2016
['2016-11-11', '22,622.46', '22,673.31', '22,442.75', '22,531.09', '22,531.09', '2,105,351,100']
106
22,622.46
107
22,673.31
108
22,442.75
109
22,531.09
110
22,531.09
111
2,105,351,100
112
Nov 10, 2016
['2016-11-10', '22,848.74', '22,918.34', '22,777.51', '22,839.11', '22,839.11', '1,594,983,400']
113
22,848.74
114
22,918.34
115
22,777.51
116
22,839.11
117
22,839.11
118
1,594,983,400
119
Nov 09, 2016
['2016-11-09', '23,048.32', '23,048.32', '21,957.71', '22,415.19', '22,415.19', '3,548,427,000']
120
23,048.32
121
23,048.32
122
21,957.71
123
22,415.19
124
22,415.19
125
3,548,427,000
126
Nov 08, 2016
['2016-11-08', '22,981.91', '22,996.97', '22,820.39', '22,909.47', '22,909.47', '1,015,231,100']
127
22,981.91
128
22,996.97
129
22,820.39
130
22,909.47
131
22,909.47
132
1,015,231,100
133
Nov 07, 2016
['2016-11-07', '22,682.71', '22,867.24', '22,623.84', '22,801.40', '22,801.40', '1,376,889,500']
134
22,682.71
135
22,867.24
136
22,623.84
137
22,801.40
138
22,801.40
139
1,376,889,500
140
Nov 04, 2016
['2016-11-04', '22,611.54', '22,771.61', '22,587.59', '22,642.62', '22,642.62', '1,014,413,400']
141
22,611.54
142
22,771.61
143
22,587.59
144
22,642.62
145
22,642.62
146
1,014,413,400
147
Nov 03, 2016
['2016-11-03', '22,708.55', '22,855.01', '22,683.51', '22,683.51', '22,683.51', '1,132,688,600']
148
22,708.55
149
22,855.01
150
22,683.51
151
22,683.51
152
22,683.51
153
1,132,688,600
154
Nov 02, 2016
['2016-11-02', '22,946.06', '22,956.85', '22,785.35', '22,810.50', '22,810.50', '1,054,518,000']
155
22,946.06
156
22,956.85
157
22,785.35
158
22,810.50
159
22,810.50
160
1,054,518,000
161
Nov 01, 2016
['2016-11-01', '23,015.06', '23,268.05', '23,015.06', '23,147.07', '23,147.07', '1,537,970,700']
162
23,015.06
163
23,268.05
164
23,015.06
165
23,147.07
166
23,147.07
167
1,537,970,700
168
Oct 31, 2016
['2016-10-31', '22,845.82', '23,045.53', '22,775.29', '22,934.54', '22,934.54', '1,297,925,200']
169
22,845.82
170
23,045.53
171
22,775.29
172
22,934.54
173
22,934.54
174
1,297,925,200
175
Oct 28, 2016
['2016-10-28', '23,088.83', '23,157.73', '22,847.73', '22,954.81', '22,954.81', '1,215,041,700']
176
23,088.83
177
23,157.73
178
22,847.73
179
22,954.81
180
22,954.81
181
1,215,041,700
182
Oct 27, 2016
['2016-10-27', '23,347.19', '23,352.62', '23,002.53', '23,132.35', '23,132.35', '1,551,943,100']
183
23,347.19
184
23,352.62
185
23,002.53
186
23,132.35
187
23,132.35
188
1,551,943,100
189
Oct 26, 2016
['2016-10-26', '23,396.14', '23,464.03', '23,310.23', '23,325.43', '23,325.43', '1,029,317,700']
190
23,396.14
191
23,464.03
192
23,310.23
193
23,325.43
194
23,325.43
195
1,029,317,700
196
Oct 25, 2016
['2016-10-25', '23,581.69', '23,631.34', '23,506.64', '23,565.11', '23,565.11', '1,182,922,100']
197
23,581.69
198
23,631.34
199
23,506.64
200
23,565.11
201
23,565.11
202
1,182,922,100
203
Oct 24, 2016
['2016-10-24', '23,431.63', '23,620.09', '23,235.61', '23,604.08', '23,604.08', '1,804,798,700']
204
23,431.63
205
23,620.09
206
23,235.61
207
23,604.08
208
23,604.08
209
1,804,798,700
210
Oct 21, 2016
['2016-10-21', '-', '-', '-', '-', '-', '-']
211
-
212
-
213
-
214
-
215
-
216
-
217
Oct 20, 2016
['2016-10-20', '23,412.68', '23,500.82', '23,360.55', '23,374.40', '23,374.40', '1,091,055,700']
218
23,412.68
219
23,500.82
220
23,360.55
221
23,374.40
222
23,374.40
223
1,091,055,700
224
Oct 19, 2016
['2016-10-19', '23,393.80', '23,445.56', '23,234.67', '23,304.97', '23,304.97', '1,009,919,700']
225
23,393.80
226
23,445.56
227
23,234.67
228
23,304.97
229
23,304.97
230
1,009,919,700
231
Oct 18, 2016
['2016-10-18', '23,130.20', '23,402.89', '23,130.20', '23,394.39', '23,394.39', '1,423,480,700']
232
23,130.20
233
23,402.89
234
23,130.20
235
23,394.39
236
23,394.39
237
1,423,480,700
238
Oct 17, 2016
['2016-10-17', '23,164.54', '23,177.19', '22,978.01', '23,037.54', '23,037.54', '1,121,480,100']
239
23,164.54
240
23,177.19
241
22,978.01
242
23,037.54
243
23,037.54
244
1,121,480,100
245
Oct 14, 2016
['2016-10-14', '23,119.96', '23,318.36', '23,087.14', '23,233.31', '23,233.31', '1,500,768,600']
246
23,119.96
247
23,318.36
248
23,087.14
249
23,233.31
250
23,233.31
251
1,500,768,600
252
Oct 13, 2016
['2016-10-13', '23,300.38', '23,347.97', '23,006.12', '23,031.30', '23,031.30', '1,957,428,300']
253
23,300.38
254
23,347.97
255
23,006.12
256
23,031.30
257
23,031.30
258
1,957,428,300
259
Oct 12, 2016
['2016-10-12', '23,386.92', '23,444.67', '23,267.63', '23,407.05', '23,407.05', '1,839,710,900']
260
23,386.92
261
23,444.67
262
23,267.63
263
23,407.05
264
23,407.05
265
1,839,710,900
266
Oct 11, 2016
['2016-10-11', '24,013.84', '24,064.50', '23,441.07', '23,549.52', '23,549.52', '2,157,326,400']
267
24,013.84
268
24,064.50
269
23,441.07
270
23,549.52
271
23,549.52
272
2,157,326,400
273
Oct 07, 2016
['2016-10-07', '23,948.95', '23,948.95', '23,770.14', '23,851.82', '23,851.82', '1,137,835,500']
274
23,948.95
275
23,948.95
276
23,770.14
277
23,851.82
278
23,851.82
279
1,137,835,500
280
Oct 06, 2016
['2016-10-06', '23,859.41', '24,004.09', '23,826.45', '23,952.50', '23,952.50', '1,721,487,000']
281
23,859.41
282
24,004.09
283
23,826.45
284
23,952.50
285
23,952.50
286
1,721,487,000
287
Oct 05, 2016
['2016-10-05', '23,619.91', '23,847.46', '23,566.22', '23,788.31', '23,788.31', '1,304,619,300']
288
23,619.91
289
23,847.46
290
23,566.22
291
23,788.31
292
23,788.31
293
1,304,619,300
294
Oct 04, 2016
['2016-10-04', '23,665.35', '23,689.44', '23,518.56', '23,689.44', '23,689.44', '1,008,151,200']
295
23,665.35
296
23,689.44
297
23,518.56
298
23,689.44
299
23,689.44
300
1,008,151,200
301
Oct 03, 2016
['2016-10-03', '23,652.83', '23,698.30', '23,500.71', '23,584.43', '23,584.43', '953,365,300']
302
23,652.83
303
23,698.30
304
23,500.71
305
23,584.43
306
23,584.43
307
953,365,300
308
Sep 30, 2016
['2016-09-30', '23,435.29', '23,484.37', '23,239.36', '23,297.15', '23,297.15', '1,674,842,700']
309
23,435.29
310
23,484.37
311
23,239.36
312
23,297.15
313
23,297.15
314
1,674,842,700
315
Sep 29, 2016
['2016-09-29', '23,828.60', '23,828.60', '23,607.99', '23,739.47', '23,739.47', '1,606,079,200']
316
23,828.60
317
23,828.60
318
23,607.99
319
23,739.47
320
23,739.47
321
1,606,079,200
322
Sep 28, 2016
['2016-09-28', '23,455.73', '23,619.65', '23,370.44', '23,619.65', '23,619.65', '1,524,350,900']
323
23,455.73
324
23,619.65
325
23,370.44
326
23,619.65
327
23,619.65
328
1,524,350,900
329
Sep 27, 2016
['2016-09-27', '23,356.03', '23,646.03', '23,295.05', '23,571.90', '23,571.90', '1,816,391,200']
330
23,356.03
331
23,646.03
332
23,295.05
333
23,571.90
334
23,571.90
335
1,816,391,200
336
Sep 26, 2016
['2016-09-26', '23,554.83', '23,563.50', '23,276.13', '23,317.92', '23,317.92', '1,652,771,300']
337
23,554.83
338
23,563.50
339
23,276.13
340
23,317.92
341
23,317.92
342
1,652,771,300
343
Sep 23, 2016
['2016-09-23', '23,836.60', '23,846.71', '23,628.64', '23,686.48', '23,686.48', '1,872,873,700']
344
23,836.60
345
23,846.71
346
23,628.64
347
23,686.48
348
23,686.48
349
1,872,873,700
350
Sep 22, 2016
['2016-09-22', '23,920.18', '24,058.65', '23,683.58', '23,759.80', '23,759.80', '2,332,001,400']
351
23,920.18
352
24,058.65
353
23,683.58
354
23,759.80
355
23,759.80
356
2,332,001,400
357
Sep 21, 2016
['2016-09-21', '23,522.86', '23,729.02', '23,436.23', '23,669.90', '23,669.90', '1,627,369,300']
358
23,522.86
359
23,729.02
360
23,436.23
361
23,669.90
362
23,669.90
363
1,627,369,300
364
Sep 20, 2016
['2016-09-20', '23,494.01', '23,556.06', '23,397.13', '23,530.86', '23,530.86', '1,483,540,700']
365
23,494.01
366
23,556.06
367
23,397.13
368
23,530.86
369
23,530.86
370
1,483,540,700
371
Sep 19, 2016
['2016-09-19', '23,486.62', '23,625.92', '23,394.95', '23,550.45', '23,550.45', '2,052,783,800']
372
23,486.62
373
23,625.92
374
23,394.95
375
23,550.45
376
23,550.45
377
2,052,783,800
378
Sep 15, 2016
['2016-09-15', '23,237.20', '23,471.48', '23,194.37', '23,335.59', '23,335.59', '1,699,911,500']
379
23,237.20
380
23,471.48
381
23,194.37
382
23,335.59
383
23,335.59
384
1,699,911,500
385
Sep 14, 2016
['2016-09-14', '23,225.58', '23,371.53', '23,155.73', '23,190.64', '23,190.64', '1,473,727,100']
386
23,225.58
387
23,371.53
388
23,155.73
389
23,190.64
390
23,190.64
391
1,473,727,100
392
Sep 13, 2016
['2016-09-13', '23,564.13', '23,652.41', '23,196.49', '23,215.76', '23,215.76', '1,616,669,300']
393
23,564.13
394
23,652.41
395
23,196.49
396
23,215.76
397
23,215.76
398
1,616,669,300
399
Sep 12, 2016
['2016-09-12', '23,596.03', '23,625.37', '23,290.60', '23,290.60', '23,290.60', '2,533,454,700']
400
23,596.03
401
23,625.37
402
23,290.60
403
23,290.60
404
23,290.60
405
2,533,454,700
406
Sep 09, 2016
['2016-09-09', '23,924.77', '24,364.00', '23,914.73', '24,099.70', '24,099.70', '2,771,690,800']
407
23,924.77
408
24,364.00
409
23,914.73
410
24,099.70
411
24,099.70
412
2,771,690,800
413
Sep 08, 2016
['2016-09-08', '23,704.36', '23,928.93', '23,663.59', '23,919.34', '23,919.34', '1,686,733,500']
414
23,704.36
415
23,928.93
416
23,663.59
417
23,919.34
418
23,919.34
419
1,686,733,500
420
Sep 07, 2016
['2016-09-07', '23,785.23', '23,830.75', '23,695.68', '23,741.81', '23,741.81', '1,939,676,800']
421
23,785.23
422
23,830.75
423
23,695.68
424
23,741.81
425
23,741.81
426
1,939,676,800
427
Sep 06, 2016
['2016-09-06', '23,683.28', '23,787.68', '23,548.55', '23,787.68', '23,787.68', '1,830,882,300']
428
23,683.28
429
23,787.68
430
23,548.55
431
23,787.68
432
23,787.68
433
1,830,882,300
434
Sep 05, 2016
['2016-09-05', '23,576.31', '23,688.41', '23,530.36', '23,649.55', '23,649.55', '1,915,393,300']
435
23,576.31
436
23,688.41
437
23,530.36
438
23,649.55
439
23,649.55
440
1,915,393,300
441
Sep 02, 2016
['2016-09-02', '23,157.01', '23,306.48', '23,152.79', '23,266.70', '23,266.70', '2,510,528,100']
442
23,157.01
443
23,306.48
444
23,152.79
445
23,266.70
446
23,266.70
447
2,510,528,100
448
Sep 01, 2016
['2016-09-01', '22,897.16', '23,193.03', '22,843.42', '23,162.34', '23,162.34', '2,106,535,800']
449
22,897.16
450
23,193.03
451
22,843.42
452
23,162.34
453
23,162.34
454
2,106,535,800
455
Aug 31, 2016
['2016-08-31', '23,043.08', '23,063.15', '22,939.87', '22,976.88', '22,976.88', '1,874,216,100']
456
23,043.08
457
23,063.15
458
22,939.87
459
22,976.88
460
22,976.88
461
1,874,216,100
462
Aug 30, 2016
['2016-08-30', '22,945.08', '23,073.52', '22,898.78', '23,016.11', '23,016.11', '1,586,826,100']
463
22,945.08
464
23,073.52
465
22,898.78
466
23,016.11
467
23,016.11
468
1,586,826,100
469
Aug 29, 2016
['2016-08-29', '22,904.20', '22,922.68', '22,762.73', '22,821.34', '22,821.34', '1,262,573,400']
470
22,904.20
471
22,922.68
472
22,762.73
473
22,821.34
474
22,821.34
475
1,262,573,400
476
Aug 26, 2016
['2016-08-26', '22,827.22', '22,997.40', '22,827.22', '22,909.54', '22,909.54', '1,600,056,800']
477
22,827.22
478
22,997.40
479
22,827.22
480
22,909.54
481
22,909.54
482
1,600,056,800
483
Aug 25, 2016
['2016-08-25', '22,814.37', '22,898.12', '22,735.03', '22,814.95', '22,814.95', '1,580,787,200']
484
22,814.37
485
22,898.12
486
22,735.03
487
22,814.95
488
22,814.95
489
1,580,787,200
490
Aug 24, 2016
['2016-08-24', '23,010.63', '23,036.07', '22,702.61', '22,820.78', '22,820.78', '1,770,177,700']
491
23,010.63
492
23,036.07
493
22,702.61
494
22,820.78
495
22,820.78
496
1,770,177,700
497
Aug 23, 2016
['2016-08-23', '22,927.47', '22,998.93', '22,854.35', '22,998.93', '22,998.93', '1,521,237,200']
498
22,927.47
499
22,998.93
500
22,854.35
501
22,998.93
502
22,998.93
503
1,521,237,200
504
Aug 22, 2016
['2016-08-22', '22,941.53', '23,005.16', '22,792.42', '22,997.91', '22,997.91', '1,720,666,500']
505
22,941.53
506
23,005.16
507
22,792.42
508
22,997.91
509
22,997.91
510
1,720,666,500
511
Aug 19, 2016
['2016-08-19', '23,153.74', '23,153.74', '22,875.56', '22,937.22', '22,937.22', '2,095,546,700']
512
23,153.74
513
23,153.74
514
22,875.56
515
22,937.22
516
22,937.22
517
2,095,546,700
518
Aug 18, 2016
['2016-08-18', '23,046.69', '23,193.90', '22,976.11', '23,023.16', '23,023.16', '2,328,376,500']
519
23,046.69
520
23,193.90
521
22,976.11
522
23,023.16
523
23,023.16
524
2,328,376,500
525
Aug 17, 2016
['2016-08-17', '22,995.51', '23,029.48', '22,775.87', '22,799.78', '22,799.78', '2,081,311,500']
526
22,995.51
527
23,029.48
528
22,775.87
529
22,799.78
530
22,799.78
531
2,081,311,500
532
Aug 16, 2016
['2016-08-16', '23,008.09', '23,084.52', '22,841.66', '22,910.84', '22,910.84', '2,005,620,700']
533
23,008.09
534
23,084.52
535
22,841.66
536
22,910.84
537
22,910.84
538
2,005,620,700
539
Aug 15, 2016
['2016-08-15', '22,765.23', '22,975.74', '22,765.23', '22,932.51', '22,932.51', '2,496,263,600']
540
22,765.23
541
22,975.74
542
22,765.23
543
22,932.51
544
22,932.51
545
2,496,263,600
546
Aug 12, 2016
['2016-08-12', '22,788.88', '22,816.75', '22,704.05', '22,766.91', '22,766.91', '2,316,030,200']
547
22,788.88
548
22,816.75
549
22,704.05
550
22,766.91
551
22,766.91
552
2,316,030,200
553
Aug 11, 2016
['2016-08-11', '22,412.31', '22,689.94', '22,359.92', '22,580.55', '22,580.55', '2,356,829,800']
554
22,412.31
555
22,689.94
556
22,359.92
557
22,580.55
558
22,580.55
559
2,356,829,800
560
Aug 10, 2016
['2016-08-10', '22,511.10', '22,618.04', '22,399.29', '22,492.43', '22,492.43', '1,564,549,200']
561
22,511.10
562
22,618.04
563
22,399.29
564
22,492.43
565
22,492.43
566
1,564,549,200
567
Aug 09, 2016
['2016-08-09', '22,464.10', '22,496.75', '22,402.91', '22,465.61', '22,465.61', '1,306,253,700']
568
22,464.10
569
22,496.75
570
22,402.91
571
22,465.61
572
22,465.61
573
1,306,253,700
574
Aug 08, 2016
['2016-08-08', '22,324.18', '22,503.28', '22,260.07', '22,494.76', '22,494.76', '1,409,047,300']
575
22,324.18
576
22,503.28
577
22,260.07
578
22,494.76
579
22,494.76
580
1,409,047,300
581
Aug 05, 2016
['2016-08-05', '21,961.05', '22,193.29', '21,961.05', '22,146.09', '22,146.09', '1,163,973,600']
582
21,961.05
583
22,193.29
584
21,961.05
585
22,146.09
586
22,146.09
587
1,163,973,600
588
Aug 04, 2016
['2016-08-04', '21,873.36', '21,922.42', '21,788.31', '21,832.23', '21,832.23', '1,019,501,800']
589
21,873.36
590
21,922.42
591
21,788.31
592
21,832.23
593
21,832.23
594
1,019,501,800
595
Aug 03, 2016
['2016-08-03', '21,743.32', '21,822.22', '21,725.38', '21,739.12', '21,739.12', '1,685,374,700']
596
21,743.32
597
21,822.22
598
21,725.38
599
21,739.12
600
21,739.12
601
1,685,374,700
602
Aug 02, 2016
['2016-08-02', '-', '-', '-', '-', '-', '-']
603
-
604
-
605
-
606
-
607
-
608
-
609
Aug 01, 2016
['2016-08-01', '22,027.65', '22,260.95', '22,027.65', '22,129.14', '22,129.14', '1,815,980,500']
610
22,027.65
611
22,260.95
612
22,027.65
613
22,129.14
614
22,129.14
615
1,815,980,500
616
Jul 29, 2016
['2016-07-29', '22,055.95', '22,152.75', '21,830.46', '21,891.37', '21,891.37', '1,745,509,100']
617
22,055.95
618
22,152.75
619
21,830.46
620
21,891.37
621
21,891.37
622
1,745,509,100
623
Jul 28, 2016
['2016-07-28', '22,134.12', '22,214.72', '22,053.51', '22,174.34', '22,174.34', '1,611,124,800']
624
22,134.12
625
22,214.72
626
22,053.51
627
22,174.34
628
22,174.34
629
1,611,124,800
630
Jul 27, 2016
['2016-07-27', '22,193.31', '22,277.24', '21,997.88', '22,218.99', '22,218.99', '1,958,434,400']
631
22,193.31
632
22,277.24
633
21,997.88
634
22,218.99
635
22,218.99
636
1,958,434,400
637
Jul 26, 2016
['2016-07-26', '21,890.89', '22,300.51', '21,890.89', '22,129.73', '22,129.73', '1,938,257,900']
638
21,890.89
639
22,300.51
640
21,890.89
641
22,129.73
642
22,129.73
643
1,938,257,900
644
Jul 25, 2016
['2016-07-25', '22,071.77', '22,071.77', '21,878.88', '21,993.44', '21,993.44', '1,189,962,100']
645
22,071.77
646
22,071.77
647
21,878.88
648
21,993.44
649
21,993.44
650
1,189,962,100
651
Jul 22, 2016
['2016-07-22', '21,913.04', '21,972.87', '21,832.43', '21,964.27', '21,964.27', '1,120,997,900']
652
21,913.04
653
21,972.87
654
21,832.43
655
21,964.27
656
21,964.27
657
1,120,997,900
658
Jul 21, 2016
['2016-07-21', '21,971.97', '22,118.22', '21,913.16', '22,000.49', '22,000.49', '1,569,756,600']
659
21,971.97
660
22,118.22
661
21,913.16
662
22,000.49
663
22,000.49
664
1,569,756,600
665
Jul 20, 2016
['2016-07-20', '21,646.39', '21,895.23', '21,632.51', '21,882.48', '21,882.48', '1,417,286,000']
666
21,646.39
667
21,895.23
668
21,632.51
669
21,882.48
670
21,882.48
671
1,417,286,000
672
Jul 19, 2016
['2016-07-19', '21,734.34', '21,767.88', '21,612.60', '21,673.20', '21,673.20', '1,257,334,500']
673
21,734.34
674
21,767.88
675
21,612.60
676
21,673.20
677
21,673.20
678
1,257,334,500
679
Jul 18, 2016
['2016-07-18', '21,656.88', '21,822.00', '21,616.16', '21,803.18', '21,803.18', '1,368,767,600']
680
21,656.88
681
21,822.00
682
21,616.16
683
21,803.18
684
21,803.18
685
1,368,767,600
686
Jul 15, 2016
['2016-07-15', '21,589.08', '21,739.21', '21,515.35', '21,659.25', '21,659.25', '1,784,843,200']
687
21,589.08
688
21,739.21
689
21,515.35
690
21,659.25
691
21,659.25
692
1,784,843,200
693
Jul 14, 2016
['2016-07-14', '21,297.54', '21,581.42', '21,242.93', '21,561.06', '21,561.06', '1,939,969,500']
694
21,297.54
695
21,581.42
696
21,242.93
697
21,561.06
698
21,561.06
699
1,939,969,500
700
100
duplicate data
2. Query all tasks
2. Query all tasks
2. Query all tasks
2. Query all tasks

[]
[]
701
[]
[]
0
Jun 30, 2016
['2016-06-30', '20,736.85', '20,828.03', '20,614.65', '20,794.37', '20,794.37', '2,032,778,200']
1
20,736.85
2
20,828.03
3
20,614.65
4
20,794.37
5
20,794.37
6
2,032,778,200
7
Jun 29, 2016
['2016-06-29', '20,217.07', '20,456.58', '20,217.07', '20,436.12', '20,436.12', '1,566,228,200']
8
20,217.07
9
20,456.58
10
20,217.07
11
20,436.12
12
20,436.12
13
1,566,228,200
14
Jun 28, 2016
['2016-06-28', '19,898.75', '20,196.20', '19,898.75', '20,172.46', '20,172.46', '1,919,983,900']
15
19,898.75
16
20,196.20
17
19,898.75
18
20,172.46
19
20,172.46
20
1,919,983,900
21
Jun 27, 2016
['2016-06-27', '19,982.66', '20,329.16', '19,969.47', '20,227.30', '20,227.30', '1,789,673,800']
22
19,982.66
23
20,329.16
24
19,969.47
25
20,227.30
26
20,227.30
27
1,789,673,800
28
Jun 24, 2016
['2016-06-24', '20,483.51', '21,034.18', '19,662.70', '20,259.13', '20,259.13', '3,953,268,600']
29
20,483.51
30
21,034.18
31
19,662.70
32
20,259.13
33
20,259.13
34
3,953,268,600
35
Jun 23, 2016
['2016-06-23', '20,862.59', '20,889.05', '20,753.94', '20,868.34', '20,868.34', '1,663,934,000']
36
20,862.59
37
20,889.05
38
20,753.94
39
20,868.34
40
20,868.34
41
1,663,934,000
42
Jun 22, 2016
['2016-06-22', '20,553.94', '20,841.51', '20,515.25', '20,795.12', '20,795.12', '1,835,867,700']
43
20,553.94
44
20,841.51
45
20,515.25
46
20,795.12
47
20,795.12
48
1,835,867,700
49
Jun 21, 2016
['2016-06-21', '20,522.36', '20,681.79', '20,516.73', '20,668.44', '20,668.44', '1,608,985,100']
50
20,522.36
51
20,681.79
52
20,516.73
53
20,668.44
54
20,668.44
55
1,608,985,100
56
Jun 20, 2016
['2016-06-20', '20,425.06', '20,551.02', '20,288.49', '20,510.20', '20,510.20', '1,565,765,000']
57
20,425.06
58
20,551.02
59
20,288.49
60
20,510.20
61
20,510.20
62
1,565,765,000
63
Jun 17, 2016
['2016-06-17', '20,244.23', '20,282.04', '20,090.80', '20,169.98', '20,169.98', '2,193,634,100']
64
20,244.23
65
20,282.04
66
20,090.80
67
20,169.98
68
20,169.98
69
2,193,634,100
70
Jun 16, 2016
['2016-06-16', '20,284.91', '20,297.40', '19,964.37', '20,038.42', '20,038.42', '1,901,944,200']
71
20,284.91
72
20,297.40
73
19,964.37
74
20,038.42
75
20,038.42
76
1,901,944,200
77
Jun 15, 2016
['2016-06-15', '20,161.01', '20,553.58', '20,161.01', '20,467.52', '20,467.52', '1,729,131,100']
78
20,161.01
79
20,553.58
80
20,161.01
81
20,467.52
82
20,467.52
83
1,729,131,100
84
Jun 14, 2016
['2016-06-14', '20,476.75', '20,537.92', '20,358.94', '20,387.53', '20,387.53', '1,498,720,500']
85
20,476.75
86
20,537.92
87
20,358.94
88
20,387.53
89
20,387.53
90
1,498,720,500
91
Jun 13, 2016
['2016-06-13', '20,647.51', '20,664.59', '20,430.81', '20,512.99', '20,512.99', '2,083,433,200']
92
20,647.51
93
20,664.59
94
20,430.81
95
20,512.99
96
20,512.99
97
2,083,433,200
98
Jun 10, 2016
['2016-06-10', '21,240.08', '21,270.62', '21,017.98', '21,042.64', '21,042.64', '1,640,607,200']
99
21,240.08
100
21,270.62
101
21,017.98
102
21,042.64
103
21,042.64
104
1,640,607,200
105
Jun 08, 2016
['2016-06-08', '21,294.27', '21,352.37', '21,179.95', '21,297.88', '21,297.88', '1,506,480,000']
106
21,294.27
107
21,352.37
108
21,179.95
109
21,297.88
110
21,297.88
111
1,506,480,000
112
Jun 07, 2016
['2016-06-07', '21,218.96', '21,351.33', '21,153.68', '21,328.24', '21,328.24', '1,820,198,000']
113
21,218.96
114
21,351.33
115
21,153.68
116
21,328.24
117
21,328.24
118
1,820,198,000
119
Jun 06, 2016
['2016-06-06', '20,971.13', '21,039.87', '20,840.95', '21,030.22', '21,030.22', '1,431,229,200']
120
20,971.13
121
21,039.87
122
20,840.95
123
21,030.22
124
21,030.22
125
1,431,229,200
126
Jun 03, 2016
['2016-06-03', '20,956.08', '21,049.20', '20,887.79', '20,947.24', '20,947.24', '1,869,294,300']
127
20,956.08
128
21,049.20
129
20,887.79
130
20,947.24
131
20,947.24
132
1,869,294,300
133
Jun 02, 2016
['2016-06-02', '20,769.81', '20,878.21', '20,680.65', '20,859.22', '20,859.22', '1,988,238,300']
134
20,769.81
135
20,878.21
136
20,680.65
137
20,859.22
138
20,859.22
139
1,988,238,300
140
Jun 01, 2016
['2016-06-01', '20,726.53', '20,898.45', '20,713.29', '20,760.98', '20,760.98', '1,422,260,700']
141
20,726.53
142
20,898.45
143
20,713.29
144
20,760.98
145
20,760.98
146
1,422,260,700
147
May 31, 2016
['2016-05-31', '20,617.33', '20,974.71', '20,617.33', '20,815.09', '20,815.09', '3,129,577,700']
148
20,617.33
149
20,974.71
150
20,617.33
151
20,815.09
152
20,815.09
153
3,129,577,700
154
May 30, 2016
['2016-05-30', '20,523.67', '20,765.61', '20,465.84', '20,629.39', '20,629.39', '1,793,022,100']
155
20,523.67
156
20,765.61
157
20,465.84
158
20,629.39
159
20,629.39
160
1,793,022,100
161
May 27, 2016
['2016-05-27', '20,425.00', '20,620.15', '20,290.84', '20,576.77', '20,576.77', '1,611,353,900']
162
20,425.00
163
20,620.15
164
20,290.84
165
20,576.77
166
20,576.77
167
1,611,353,900
168
May 26, 2016
['2016-05-26', '20,373.48', '20,404.73', '20,249.96', '20,397.11', '20,397.11', '1,347,013,200']
169
20,373.48
170
20,404.73
171
20,249.96
172
20,397.11
173
20,397.11
174
1,347,013,200
175
May 25, 2016
['2016-05-25', '20,156.76', '20,379.66', '20,156.76', '20,368.05', '20,368.05', '2,040,761,100']
176
20,156.76
177
20,379.66
178
20,156.76
179
20,368.05
180
20,368.05
181
2,040,761,100
182
May 24, 2016
['2016-05-24', '19,828.02', '19,870.16', '19,712.67', '19,830.43', '19,830.43', '1,174,095,900']
183
19,828.02
184
19,870.16
185
19,712.67
186
19,830.43
187
19,830.43
188
1,174,095,900
189
May 23, 2016
['2016-05-23', '19,788.13', '19,955.03', '19,750.62', '19,809.03', '19,809.03', '1,086,593,700']
190
19,788.13
191
19,955.03
192
19,750.62
193
19,809.03
194
19,809.03
195
1,086,593,700
196
May 20, 2016
['2016-05-20', '19,631.71', '19,954.33', '19,631.71', '19,852.20', '19,852.20', '1,247,729,300']
197
19,631.71
198
19,954.33
199
19,631.71
200
19,852.20
201
19,852.20
202
1,247,729,300
203
May 19, 2016
['2016-05-19', '19,729.63', '19,793.46', '19,646.35', '19,694.33', '19,694.33', '1,148,089,000']
204
19,729.63
205
19,793.46
206
19,646.35
207
19,694.33
208
19,694.33
209
1,148,089,000
210
May 18, 2016
['2016-05-18', '19,862.42', '19,923.83', '19,749.29', '19,826.41', '19,826.41', '1,351,584,400']
211
19,862.42
212
19,923.83
213
19,749.29
214
19,826.41
215
19,826.41
216
1,351,584,400
217
May 17, 2016
['2016-05-17', '19,987.24', '20,145.77', '19,847.70', '20,118.80', '20,118.80', '1,568,659,300']
218
19,987.24
219
20,145.77
220
19,847.70
221
20,118.80
222
20,118.80
223
1,568,659,300
224
May 16, 2016
['2016-05-16', '19,711.77', '19,998.76', '19,705.91', '19,883.95', '19,883.95', '1,486,067,400']
225
19,711.77
226
19,998.76
227
19,705.91
228
19,883.95
229
19,883.95
230
1,486,067,400
231
May 13, 2016
['2016-05-13', '19,843.49', '19,881.91', '19,594.61', '19,719.29', '19,719.29', '1,758,498,600']
232
19,843.49
233
19,881.91
234
19,594.61
235
19,719.29
236
19,719.29
237
1,758,498,600
238
May 12, 2016
['2016-05-12', '20,100.50', '20,100.50', '19,863.62', '19,915.46', '19,915.46', '1,150,409,200']
239
20,100.50
240
20,100.50
241
19,863.62
242
19,915.46
243
19,915.46
244
1,150,409,200
245
May 11, 2016
['2016-05-11', '20,347.76', '20,347.76', '20,008.92', '20,055.29', '20,055.29', '1,337,926,500']
246
20,347.76
247
20,347.76
248
20,008.92
249
20,055.29
250
20,055.29
251
1,337,926,500
252
May 10, 2016
['2016-05-10', '19,962.43', '20,294.46', '19,962.43', '20,242.68', '20,242.68', '1,446,925,800']
253
19,962.43
254
20,294.46
255
19,962.43
256
20,242.68
257
20,242.68
258
1,446,925,800
259
May 09, 2016
['2016-05-09', '20,279.90', '20,303.19', '20,125.78', '20,156.81', '20,156.81', '1,323,285,400']
260
20,279.90
261
20,303.19
262
20,125.78
263
20,156.81
264
20,156.81
265
1,323,285,400
266
May 06, 2016
['2016-05-06', '20,357.45', '20,377.94', '20,058.77', '20,109.87', '20,109.87', '1,725,801,800']
267
20,357.45
268
20,377.94
269
20,058.77
270
20,109.87
271
20,109.87
272
1,725,801,800
273
May 05, 2016
['2016-05-05', '20,363.86', '20,534.76', '20,342.75', '20,449.82', '20,449.82', '1,354,977,100']
274
20,363.86
275
20,534.76
276
20,342.75
277
20,449.82
278
20,449.82
279
1,354,977,100
280
May 04, 2016
['2016-05-04', '20,556.50', '20,580.38', '20,411.41', '20,525.83', '20,525.83', '1,555,895,400']
281
20,556.50
282
20,580.38
283
20,411.41
284
20,525.83
285
20,525.83
286
1,555,895,400
287
May 03, 2016
['2016-05-03', '21,061.77', '21,061.77', '20,668.37', '20,676.94', '20,676.94', '1,707,676,300']
288
21,061.77
289
21,061.77
290
20,668.37
291
20,676.94
292
20,676.94
293
1,707,676,300
294
Apr 29, 2016
['2016-04-29', '21,215.20', '21,235.39', '21,023.77', '21,067.05', '21,067.05', '1,603,138,400']
295
21,215.20
296
21,235.39
297
21,023.77
298
21,067.05
299
21,067.05
300
1,603,138,400
301
Apr 28, 2016
['2016-04-28', '21,488.96', '21,654.07', '21,255.42', '21,388.03', '21,388.03', '1,684,154,400']
302
21,488.96
303
21,654.07
304
21,255.42
305
21,388.03
306
21,388.03
307
1,684,154,400
308
Apr 27, 2016
['2016-04-27', '21,372.33', '21,442.51', '21,277.04', '21,361.60', '21,361.60', '1,247,249,600']
309
21,372.33
310
21,442.51
311
21,277.04
312
21,361.60
313
21,361.60
314
1,247,249,600
315
Apr 26, 2016
['2016-04-26', '21,380.02', '21,419.92', '21,080.88', '21,407.27', '21,407.27', '1,346,786,700']
316
21,380.02
317
21,419.92
318
21,080.88
319
21,407.27
320
21,407.27
321
1,346,786,700
322
Apr 25, 2016
['2016-04-25', '21,408.56', '21,430.57', '21,254.46', '21,304.44', '21,304.44', '1,199,972,500']
323
21,408.56
324
21,430.57
325
21,254.46
326
21,304.44
327
21,304.44
328
1,199,972,500
329
Apr 22, 2016
['2016-04-22', '21,448.15', '21,495.79', '21,358.53', '21,467.04', '21,467.04', '1,282,700,700']
330
21,448.15
331
21,495.79
332
21,358.53
333
21,467.04
334
21,467.04
335
1,282,700,700
336
Apr 21, 2016
['2016-04-21', '21,406.40', '21,634.74', '21,331.59', '21,622.25', '21,622.25', '1,709,117,500']
337
21,406.40
338
21,634.74
339
21,331.59
340
21,622.25
341
21,622.25
342
1,709,117,500
343
Apr 20, 2016
['2016-04-20', '21,452.82', '21,452.82', '21,103.34', '21,236.31', '21,236.31', '1,716,745,500']
344
21,452.82
345
21,452.82
346
21,103.34
347
21,236.31
348
21,236.31
349
1,716,745,500
350
Apr 19, 2016
['2016-04-19', '21,438.13', '21,459.04', '21,259.17', '21,436.21', '21,436.21', '1,462,091,100']
351
21,438.13
352
21,459.04
353
21,259.17
354
21,436.21
355
21,436.21
356
1,462,091,100
357
Apr 18, 2016
['2016-04-18', '21,129.68', '21,172.00', '21,002.77', '21,161.50', '21,161.50', '1,426,843,200']
358
21,129.68
359
21,172.00
360
21,002.77
361
21,161.50
362
21,161.50
363
1,426,843,200
364
Apr 15, 2016
['2016-04-15', '21,374.65', '21,423.06', '21,234.12', '21,316.47', '21,316.47', '1,413,648,900']
365
21,374.65
366
21,423.06
367
21,234.12
368
21,316.47
369
21,316.47
370
1,413,648,900
371
Apr 14, 2016
['2016-04-14', '21,456.61', '21,511.08', '21,266.21', '21,337.81', '21,337.81', '2,054,279,800']
372
21,456.61
373
21,511.08
374
21,266.21
375
21,337.81
376
21,337.81
377
2,054,279,800
378
Apr 13, 2016
['2016-04-13', '20,739.34', '21,171.29', '20,716.91', '21,158.71', '21,158.71', '2,500,342,000']
379
20,739.34
380
21,171.29
381
20,716.91
382
21,158.71
383
21,158.71
384
2,500,342,000
385
Apr 12, 2016
['2016-04-12', '20,440.72', '20,546.43', '20,407.82', '20,504.44', '20,504.44', '997,121,600']
386
20,440.72
387
20,546.43
388
20,407.82
389
20,504.44
390
20,504.44
391
997,121,600
392
Apr 11, 2016
['2016-04-11', '20,255.84', '20,550.95', '20,240.69', '20,440.81', '20,440.81', '1,234,203,400']
393
20,255.84
394
20,550.95
395
20,240.69
396
20,440.81
397
20,440.81
398
1,234,203,400
399
Apr 08, 2016
['2016-04-08', '20,061.60', '20,370.44', '20,045.47', '20,370.40', '20,370.40', '1,435,612,200']
400
20,061.60
401
20,370.44
402
20,045.47
403
20,370.40
404
20,370.40
405
1,435,612,200
406
Apr 07, 2016
['2016-04-07', '20,297.82', '20,370.52', '20,165.76', '20,266.05', '20,266.05', '1,493,940,300']
407
20,297.82
408
20,370.52
409
20,165.76
410
20,266.05
411
20,266.05
412
1,493,940,300
413
Apr 06, 2016
['2016-04-06', '20,100.00', '20,249.84', '20,100.00', '20,206.67', '20,206.67', '1,338,272,400']
414
20,100.00
415
20,249.84
416
20,100.00
417
20,206.67
418
20,206.67
419
1,338,272,400
420
Apr 05, 2016
['2016-04-05', '20,311.86', '20,311.86', '20,116.87', '20,177.00', '20,177.00', '1,876,707,600']
421
20,311.86
422
20,311.86
423
20,116.87
424
20,177.00
425
20,177.00
426
1,876,707,600
427
Apr 01, 2016
['2016-04-01', '20,786.18', '20,786.18', '20,455.41', '20,498.92', '20,498.92', '1,633,594,800']
428
20,786.18
429
20,786.18
430
20,455.41
431
20,498.92
432
20,498.92
433
1,633,594,800
434
Mar 31, 2016
['2016-03-31', '20,811.46', '20,872.55', '20,689.22', '20,776.70', '20,776.70', '1,781,006,800']
435
20,811.46
436
20,872.55
437
20,689.22
438
20,776.70
439
20,776.70
440
1,781,006,800
441
Mar 30, 2016
['2016-03-30', '20,545.44', '20,820.73', '20,541.07', '20,803.39', '20,803.39', '2,058,668,600']
442
20,545.44
443
20,820.73
444
20,541.07
445
20,803.39
446
20,803.39
447
2,058,668,600
448
Mar 29, 2016
['2016-03-29', '20,386.32', '20,386.32', '20,250.15', '20,366.30', '20,366.30', '1,303,869,800']
449
20,386.32
450
20,386.32
451
20,250.15
452
20,366.30
453
20,366.30
454
1,303,869,800
455
Mar 24, 2016
['2016-03-24', '20,450.69', '20,499.40', '20,268.53', '20,345.61', '20,345.61', '1,460,918,200']
456
20,450.69
457
20,499.40
458
20,268.53
459
20,345.61
460
20,345.61
461
1,460,918,200
462
Mar 23, 2016
['2016-03-23', '20,629.40', '20,693.48', '20,513.61', '20,615.23', '20,615.23', '1,185,399,100']
463
20,629.40
464
20,693.48
465
20,513.61
466
20,615.23
467
20,615.23
468
1,185,399,100
469
Mar 22, 2016
['2016-03-22', '20,765.07', '20,765.07', '20,576.80', '20,666.75', '20,666.75', '1,303,372,700']
470
20,765.07
471
20,765.07
472
20,576.80
473
20,666.75
474
20,666.75
475
1,303,372,700
476
Mar 21, 2016
['2016-03-21', '20,738.25', '20,772.46', '20,618.56', '20,684.15', '20,684.15', '1,520,109,900']
477
20,738.25
478
20,772.46
479
20,618.56
480
20,684.15
481
20,684.15
482
1,520,109,900
483
Mar 18, 2016
['2016-03-18', '20,599.19', '20,687.97', '20,514.97', '20,671.63', '20,671.63', '2,091,585,400']
484
20,599.19
485
20,687.97
486
20,514.97
487
20,671.63
488
20,671.63
489
2,091,585,400
490
Mar 17, 2016
['2016-03-17', '20,580.06', '20,619.34', '20,435.65', '20,503.81', '20,503.81', '1,696,007,800']
491
20,580.06
492
20,619.34
493
20,435.65
494
20,503.81
495
20,503.81
496
1,696,007,800
497
Mar 16, 2016
['2016-03-16', '20,339.90', '20,383.20', '20,168.74', '20,257.70', '20,257.70', '1,213,704,800']
498
20,339.90
499
20,383.20
500
20,168.74
501
20,257.70
502
20,257.70
503
1,213,704,800
504
Mar 15, 2016
['2016-03-15', '20,298.15', '20,366.56', '20,254.59', '20,288.77', '20,288.77', '1,193,143,900']
505
20,298.15
506
20,366.56
507
20,254.59
508
20,288.77
509
20,288.77
510
1,193,143,900
511
Mar 14, 2016
['2016-03-14', '20,371.59', '20,512.03', '20,328.88', '20,435.34', '20,435.34', '1,722,861,700']
512
20,371.59
513
20,512.03
514
20,328.88
515
20,435.34
516
20,435.34
517
1,722,861,700
518
Mar 11, 2016
['2016-03-11', '19,900.67', '20,238.72', '19,853.63', '20,199.60', '20,199.60', '1,970,725,700']
519
19,900.67
520
20,238.72
521
19,853.63
522
20,199.60
523
20,199.60
524
1,970,725,700
525
Mar 10, 2016
['2016-03-10', '20,055.42', '20,184.23', '19,923.54', '19,984.42', '19,984.42', '1,384,555,000']
526
20,055.42
527
20,184.23
528
19,923.54
529
19,984.42
530
19,984.42
531
1,384,555,000
532
Mar 09, 2016
['2016-03-09', '19,898.74', '20,005.41', '19,818.42', '19,996.26', '19,996.26', '1,202,836,200']
533
19,898.74
534
20,005.41
535
19,818.42
536
19,996.26
537
19,996.26
538
1,202,836,200
539
Mar 08, 2016
['2016-03-08', '20,132.10', '20,137.73', '19,902.75', '20,011.58', '20,011.58', '1,449,306,300']
540
20,132.10
541
20,137.73
542
19,902.75
543
20,011.58
544
20,011.58
545
1,449,306,300
546
Mar 07, 2016
['2016-03-07', '20,306.09', '20,331.69', '20,095.63', '20,159.72', '20,159.72', '1,930,240,900']
547
20,306.09
548
20,331.69
549
20,095.63
550
20,159.72
551
20,159.72
552
1,930,240,900
553
Mar 04, 2016
['2016-03-04', '20,052.10', '20,200.38', '19,977.43', '20,176.70', '20,176.70', '1,907,805,100']
554
20,052.10
555
20,200.38
556
19,977.43
557
20,176.70
558
20,176.70
559
1,907,805,100
560
Mar 03, 2016
['2016-03-03', '20,082.01', '20,082.01', '19,791.60', '19,941.76', '19,941.76', '1,761,676,100']
561
20,082.01
562
20,082.01
563
19,791.60
564
19,941.76
565
19,941.76
566
1,761,676,100
567
Mar 02, 2016
['2016-03-02', '19,788.17', '20,058.12', '19,783.92', '20,003.49', '20,003.49', '2,455,833,600']
568
19,788.17
569
20,058.12
570
19,783.92
571
20,003.49
572
20,003.49
573
2,455,833,600
574
Mar 01, 2016
['2016-03-01', '19,259.99', '19,420.00', '19,108.30', '19,407.46', '19,407.46', '1,473,881,700']
575
19,259.99
576
19,420.00
577
19,108.30
578
19,407.46
579
19,407.46
580
1,473,881,700
581
Feb 29, 2016
['2016-02-29', '19,366.17', '19,377.72', '19,053.78', '19,111.93', '19,111.93', '1,270,443,900']
582
19,366.17
583
19,377.72
584
19,053.78
585
19,111.93
586
19,111.93
587
1,270,443,900
588
Feb 26, 2016
['2016-02-26', '19,179.95', '19,436.71', '19,122.56', '19,364.15', '19,364.15', '1,633,549,100']
589
19,179.95
590
19,436.71
591
19,122.56
592
19,364.15
593
19,364.15
594
1,633,549,100
595
Feb 25, 2016
['2016-02-25', '19,215.49', '19,215.49', '18,867.70', '18,888.75', '18,888.75', '1,395,869,600']
596
19,215.49
597
19,215.49
598
18,867.70
599
18,888.75
600
18,888.75
601
1,395,869,600
602
Feb 24, 2016
['2016-02-24', '19,282.34', '19,360.80', '19,060.16', '19,192.45', '19,192.45', '1,302,717,300']
603
19,282.34
604
19,360.80
605
19,060.16
606
19,192.45
607
19,192.45
608
1,302,717,300
609
Feb 23, 2016
['2016-02-23', '19,506.94', '19,519.85', '19,328.26', '19,414.78', '19,414.78', '1,225,027,600']
610
19,506.94
611
19,519.85
612
19,328.26
613
19,414.78
614
19,414.78
615
1,225,027,600
616
Feb 22, 2016
['2016-02-22', '19,374.24', '19,524.97', '19,374.24', '19,464.09', '19,464.09', '1,207,462,000']
617
19,374.24
618
19,524.97
619
19,374.24
620
19,464.09
621
19,464.09
622
1,207,462,000
623
Feb 19, 2016
['2016-02-19', '19,238.43', '19,342.03', '19,210.65', '19,285.50', '19,285.50', '1,268,689,800']
624
19,238.43
625
19,342.03
626
19,210.65
627
19,285.50
628
19,285.50
629
1,268,689,800
630
Feb 18, 2016
['2016-02-18', '19,409.21', '19,436.39', '19,266.22', '19,363.08', '19,363.08', '1,843,924,000']
631
19,409.21
632
19,436.39
633
19,266.22
634
19,363.08
635
19,363.08
636
1,843,924,000
637
Feb 17, 2016
['2016-02-17', '19,198.18', '19,308.54', '18,909.06', '18,924.57', '18,924.57', '1,689,473,500']
638
19,198.18
639
19,308.54
640
18,909.06
641
18,924.57
642
18,924.57
643
1,689,473,500
644
Feb 16, 2016
['2016-02-16', '19,013.74', '19,260.67', '18,974.60', '19,122.08', '19,122.08', '1,869,161,100']
645
19,013.74
646
19,260.67
647
18,974.60
648
19,122.08
649
19,122.08
650
1,869,161,100
651
Feb 15, 2016
['2016-02-15', '18,668.87', '18,937.06', '18,668.87', '18,918.14', '18,918.14', '1,729,340,100']
652
18,668.87
653
18,937.06
654
18,668.87
655
18,918.14
656
18,918.14
657
1,729,340,100
658
Feb 12, 2016
['2016-02-12', '18,278.80', '18,482.33', '18,278.80', '18,319.58', '18,319.58', '2,019,813,200']
659
18,278.80
660
18,482.33
661
18,278.80
662
18,319.58
663
18,319.58
664
2,019,813,200
665
Feb 11, 2016
['2016-02-11', '18,486.93', '18,627.51', '18,446.56', '18,545.80', '18,545.80', '1,868,442,400']
666
18,486.93
667
18,627.51
668
18,446.56
669
18,545.80
670
18,545.80
671
1,868,442,400
672
Feb 05, 2016
['2016-02-05', '19,287.36', '19,397.88', '19,230.00', '19,288.17', '19,288.17', '1,264,808,100']
673
19,287.36
674
19,397.88
675
19,230.00
676
19,288.17
677
19,288.17
678
1,264,808,100
679
Feb 04, 2016
['2016-02-04', '19,190.36', '19,338.37', '19,166.18', '19,183.09', '19,183.09', '1,556,986,500']
680
19,190.36
681
19,338.37
682
19,166.18
683
19,183.09
684
19,183.09
685
1,556,986,500
686
Feb 03, 2016
['2016-02-03', '18,910.88', '19,032.71', '18,764.82', '18,991.59', '18,991.59', '2,126,513,100']
687
18,910.88
688
19,032.71
689
18,764.82
690
18,991.59
691
18,991.59
692
2,126,513,100
693
Feb 02, 2016

[]
[]
701
[]
[]
0
Feb 02, 2016
['2016-02-02', '19,474.87', '19,628.57', '19,403.49', '19,446.84', '19,446.84', '1,783,516,300']
1
19,474.87
2
19,628.57
3
19,403.49
4
19,446.84
5
19,446.84
6
1,783,516,300
7
Feb 01, 2016
['2016-02-01', '19,770.96', '19,770.96', '19,444.26', '19,595.50', '19,595.50', '1,596,458,400']
8
19,770.96
9
19,770.96
10
19,444.26
11
19,595.50
12
19,595.50
13
1,596,458,400
14
Jan 29, 2016
['2016-01-29', '19,138.42', '19,709.99', '19,130.59', '19,683.11', '19,683.11', '2,350,176,600']
15
19,138.42
16
19,709.99
17
19,130.59
18
19,683.11
19
19,683.11
20
2,350,176,600
21
Jan 28, 2016
['2016-01-28', '19,093.77', '19,223.59', '18,982.22', '19,195.83', '19,195.83', '1,941,781,800']
22
19,093.77
23
19,223.59
24
18,982.22
25
19,195.83
26
19,195.83
27
1,941,781,800
28
Jan 27, 2016
['2016-01-27', '19,211.86', '19,216.99', '18,931.34', '19,052.45', '19,052.45', '1,929,850,700']
29
19,211.86
30
19,216.99
31
18,931.34
32
19,052.45
33
19,052.45
34
1,929,850,700
35
Jan 26, 2016
['2016-01-26', '19,068.84', '19,098.07', '18,811.83', '18,860.80', '18,860.80', '1,873,245,100']
36
19,068.84
37
19,098.07
38
18,811.83
39
18,860.80
40
18,860.80
41
1,873,245,100
42
Jan 25, 2016
['2016-01-25', '19,341.41', '19,490.27', '19,291.91', '19,340.14', '19,340.14', '1,776,766,600']
43
19,341.41
44
19,490.27
45
19,291.91
46
19,340.14
47
19,340.14
48
1,776,766,600
49
Jan 22, 2016
['2016-01-22', '19,000.79', '19,152.80', '18,769.61', '19,080.51', '19,080.51', '2,388,446,600']
50
19,000.79
51
19,152.80
52
18,769.61
53
19,080.51
54
19,080.51
55
2,388,446,600
56
Jan 21, 2016
['2016-01-21', '19,079.13', '19,238.27', '18,534.30', '18,542.15', '18,542.15', '2,608,444,800']
57
19,079.13
58
19,238.27
59
18,534.30
60
18,542.15
61
18,542.15
62
2,608,444,800
63
Jan 20, 2016
['2016-01-20', '19,332.22', '19,332.22', '18,833.88', '18,886.30', '18,886.30', '2,459,536,700']
64
19,332.22
65
19,332.22
66
18,833.88
67
18,886.30
68
18,886.30
69
2,459,536,700
70
Jan 19, 2016
['2016-01-19', '19,283.57', '19,647.75', '19,204.22', '19,635.81', '19,635.81', '1,825,359,900']
71
19,283.57
72
19,647.75
73
19,204.22
74
19,635.81
75
19,635.81
76
1,825,359,900
77
Jan 18, 2016
['2016-01-18', '19,287.38', '19,439.49', '19,195.56', '19,237.45', '19,237.45', '2,038,630,500']
78
19,287.38
79
19,439.49
80
19,195.56
81
19,237.45
82
19,237.45
83
2,038,630,500
84
Jan 15, 2016
['2016-01-15', '19,781.46', '19,828.93', '19,500.38', '19,520.77', '19,520.77', '1,932,607,600']
85
19,781.46
86
19,828.93
87
19,500.38
88
19,520.77
89
19,520.77
90
1,932,607,600
91
Jan 14, 2016
['2016-01-14', '19,578.92', '19,893.88', '19,509.08', '19,817.41', '19,817.41', '1,783,215,300']
92
19,578.92
93
19,893.88
94
19,509.08
95
19,817.41
96
19,817.41
97
1,783,215,300
98
Jan 13, 2016
['2016-01-13', '20,028.86', '20,234.78', '19,850.73', '19,934.88', '19,934.88', '1,787,070,400']
99
20,028.86
100
20,234.78
101
19,850.73
102
19,934.88
103
19,934.88
104
1,787,070,400
105
Jan 12, 2016
['2016-01-12', '20,030.03', '20,130.80', '19,694.99', '19,711.76', '19,711.76', '1,834,357,100']
106
20,030.03
107
20,130.80
108
19,694.99
109
19,711.76
110
19,711.76
111
1,834,357,100
112
Jan 11, 2016
['2016-01-11', '19,997.42', '20,068.78', '19,865.18', '19,888.50', '19,888.50', '2,127,840,400']
113
19,997.42
114
20,068.78
115
19,865.18
116
19,888.50
117
19,888.50
118
2,127,840,400
119
Jan 08, 2016
['2016-01-08', '20,491.88', '20,596.42', '20,324.62', '20,453.71', '20,453.71', '2,078,133,200']
120
20,491.88
121
20,596.42
122
20,324.62
123
20,453.71
124
20,453.71
125
2,078,133,200
126
Jan 07, 2016
['2016-01-07', '20,772.60', '20,826.44', '20,323.97', '20,333.34', '20,333.34', '2,982,003,800']
127
20,772.60
128
20,826.44
129
20,323.97
130
20,333.34
131
20,333.34
132
2,982,003,800
133
Jan 06, 2016
['2016-01-06', '21,142.63', '21,199.62', '20,947.30', '20,980.81', '20,980.81', '1,651,083,400']
134
21,142.63
135
21,199.62
136
20,947.30
137
20,980.81
138
20,980.81
139
1,651,083,400
140
Jan 05, 2016
['2016-01-05', '21,318.69', '21,452.74', '21,095.90', '21,188.72', '21,188.72', '1,484,745,100']
141
21,318.69
142
21,452.74
143
21,095.90
144
21,188.72
145
21,188.72
146
1,484,745,100
147
Jan 04, 2016
['2016-01-04', '21,782.62', '21,794.84', '21,227.61', '21,327.12', '21,327.12', '1,712,094,800']
148
21,782.62
149
21,794.84
150
21,227.61
151
21,327.12
152
21,327.12
153
1,712,094,800
154
Dec 31, 2015
['2015-12-31', '21,892.25', '21,970.33', '21,864.12', '21,914.40', '21,914.40', '510,189,800']
155
21,892.25
156
21,970.33
157
21,864.12
158
21,914.40
159
21,914.40
160
510,189,800
161
Dec 30, 2015
['2015-12-30', '22,094.59', '22,114.56', '21,868.03', '21,882.15', '21,882.15', '1,058,882,700']
162
22,094.59
163
22,114.56
164
21,868.03
165
21,882.15
166
21,882.15
167
1,058,882,700
168
Dec 29, 2015
['2015-12-29', '21,923.27', '22,024.28', '21,881.71', '21,999.62', '21,999.62', '766,776,200']
169
21,923.27
170
22,024.28
171
21,881.71
172
21,999.62
173
21,999.62
174
766,776,200
175
Dec 28, 2015
['2015-12-28', '22,151.73', '22,151.73', '21,880.51', '21,919.62', '21,919.62', '874,126,000']
176
22,151.73
177
22,151.73
178
21,880.51
179
21,919.62
180
21,919.62
181
874,126,000
182
Dec 24, 2015
['2015-12-24', '22,207.82', '22,217.45', '22,128.72', '22,138.13', '22,138.13', '712,784,400']
183
22,207.82
184
22,217.45
185
22,128.72
186
22,138.13
187
22,138.13
188
712,784,400
189
Dec 23, 2015
['2015-12-23', '21,869.40', '22,103.63', '21,846.48', '22,040.59', '22,040.59', '1,053,086,500']
190
21,869.40
191
22,103.63
192
21,846.48
193
22,040.59
194
22,040.59
195
1,053,086,500
196
Dec 22, 2015
['2015-12-22', '21,846.90', '21,870.31', '21,750.74', '21,830.02', '21,830.02', '916,724,900']
197
21,846.90
198
21,870.31
199
21,750.74
200
21,830.02
201
21,830.02
202
916,724,900
203
Dec 21, 2015
['2015-12-21', '21,641.17', '21,871.22', '21,641.17', '21,791.68', '21,791.68', '1,302,760,700']
204
21,641.17
205
21,871.22
206
21,641.17
207
21,791.68
208
21,791.68
209
1,302,760,700
210
Dec 18, 2015
['2015-12-18', '21,656.56', '21,956.49', '21,625.82', '21,755.56', '21,755.56', '1,774,171,000']
211
21,656.56
212
21,956.49
213
21,625.82
214
21,755.56
215
21,755.56
216
1,774,171,000
217
Dec 17, 2015
['2015-12-17', '21,841.09', '22,005.19', '21,763.76', '21,872.06', '21,872.06', '1,604,958,700']
218
21,841.09
219
22,005.19
220
21,763.76
221
21,872.06
222
21,872.06
223
1,604,958,700
224
Dec 16, 2015
['2015-12-16', '21,557.73', '21,772.79', '21,557.73', '21,701.21', '21,701.21', '1,645,623,800']
225
21,557.73
226
21,772.79
227
21,557.73
228
21,701.21
229
21,701.21
230
1,645,623,800
231
Dec 15, 2015
['2015-12-15', '21,215.54', '21,442.21', '21,215.54', '21,274.37', '21,274.37', '1,575,316,200']
232
21,215.54
233
21,442.21
234
21,215.54
235
21,274.37
236
21,274.37
237
1,575,316,200
238
Dec 14, 2015
['2015-12-14', '21,063.28', '21,378.19', '21,010.26', '21,309.85', '21,309.85', '1,716,020,200']
239
21,063.28
240
21,378.19
241
21,010.26
242
21,309.85
243
21,309.85
244
1,716,020,200
245
Dec 11, 2015
['2015-12-11', '21,719.17', '21,731.39', '21,440.70', '21,464.05', '21,464.05', '1,399,114,000']
246
21,719.17
247
21,731.39
248
21,440.70
249
21,464.05
250
21,464.05
251
1,399,114,000
252
Dec 10, 2015
['2015-12-10', '21,714.23', '21,880.19', '21,668.12', '21,704.61', '21,704.61', '1,589,431,100']
253
21,714.23
254
21,880.19
255
21,668.12
256
21,704.61
257
21,704.61
258
1,589,431,100
259
Dec 09, 2015
['2015-12-09', '21,773.77', '21,872.33', '21,755.69', '21,803.76', '21,803.76', '1,365,939,700']
260
21,773.77
261
21,872.33
262
21,755.69
263
21,803.76
264
21,803.76
265
1,365,939,700
266
Dec 08, 2015
['2015-12-08', '22,058.55', '22,058.55', '21,765.62', '21,905.13', '21,905.13', '1,812,299,200']
267
22,058.55
268
22,058.55
269
21,765.62
270
21,905.13
271
21,905.13
272
1,812,299,200
273
Dec 07, 2015
['2015-12-07', '22,336.32', '22,352.25', '22,200.55', '22,203.22', '22,203.22', '1,290,311,100']
274
22,336.32
275
22,352.25
276
22,200.55
277
22,203.22
278
22,203.22
279
1,290,311,100
280
Dec 04, 2015
['2015-12-04', '22,142.11', '22,242.49', '22,108.46', '22,235.89', '22,235.89', '1,607,921,200']
281
22,142.11
282
22,242.49
283
22,108.46
284
22,235.89
285
22,235.89
286
1,607,921,200
287
Dec 03, 2015
['2015-12-03', '22,327.04', '22,485.25', '22,327.04', '22,417.01', '22,417.01', '1,271,068,600']
288
22,327.04
289
22,485.25
290
22,327.04
291
22,417.01
292
22,417.01
293
1,271,068,600
294
Dec 02, 2015
['2015-12-02', '22,471.35', '22,563.47', '22,368.66', '22,479.69', '22,479.69', '1,671,129,200']
295
22,471.35
296
22,563.47
297
22,368.66
298
22,479.69
299
22,479.69
300
1,671,129,200
301
Dec 01, 2015
['2015-12-01', '22,197.81', '22,477.51', '22,143.57', '22,381.35', '22,381.35', '1,984,283,400']
302
22,197.81
303
22,477.51
304
22,143.57
305
22,381.35
306
22,381.35
307
1,984,283,400
308
Nov 30, 2015
['2015-11-30', '21,974.85', '22,195.35', '21,907.45', '21,996.42', '21,996.42', '-']
309
21,974.85
310
22,195.35
311
21,907.45
312
21,996.42
313
21,996.42
314
-
315
Nov 27, 2015
['2015-11-27', '22,555.42', '22,555.42', '22,051.01', '22,068.32', '22,068.32', '2,044,748,700']
316
22,555.42
317
22,555.42
318
22,051.01
319
22,068.32
320
22,068.32
321
2,044,748,700
322
Nov 26, 2015
['2015-11-26', '22,749.60', '22,787.50', '22,453.69', '22,488.94', '22,488.94', '1,128,427,600']
323
22,749.60
324
22,787.50
325
22,453.69
326
22,488.94
327
22,488.94
328
1,128,427,600
329
Nov 25, 2015
['2015-11-25', '22,533.53', '22,617.21', '22,436.01', '22,498.00', '22,498.00', '1,513,214,100']
330
22,533.53
331
22,617.21
332
22,436.01
333
22,498.00
334
22,498.00
335
1,513,214,100
336
Nov 24, 2015
['2015-11-24', '22,593.09', '22,629.75', '22,433.51', '22,587.63', '22,587.63', '1,194,757,000']
337
22,593.09
338
22,629.75
339
22,433.51
340
22,587.63
341
22,587.63
342
1,194,757,000
343
Nov 23, 2015
['2015-11-23', '22,760.05', '22,802.71', '22,619.68', '22,665.90', '22,665.90', '1,075,994,800']
344
22,760.05
345
22,802.71
346
22,619.68
347
22,665.90
348
22,665.90
349
1,075,994,800
350
Nov 20, 2015
['2015-11-20', '22,510.45', '22,790.07', '22,412.03', '22,754.72', '22,754.72', '1,230,928,400']
351
22,510.45
352
22,790.07
353
22,412.03
354
22,754.72
355
22,754.72
356
1,230,928,400
357
Nov 19, 2015
['2015-11-19', '22,423.88', '22,559.06', '22,416.00', '22,500.22', '22,500.22', '1,381,484,300']
358
22,423.88
359
22,559.06
360
22,416.00
361
22,500.22
362
22,500.22
363
1,381,484,300
364
Nov 18, 2015
['2015-11-18', '22,331.77', '22,349.73', '22,163.28', '22,188.26', '22,188.26', '1,211,467,800']
365
22,331.77
366
22,349.73
367
22,163.28
368
22,188.26
369
22,188.26
370
1,211,467,800
371
Nov 17, 2015
['2015-11-17', '22,315.18', '22,497.33', '22,243.96', '22,264.25', '22,264.25', '1,627,705,000']
372
22,315.18
373
22,497.33
374
22,243.96
375
22,264.25
376
22,264.25
377
1,627,705,000
378
Nov 16, 2015
['2015-11-16', '21,958.28', '22,127.38', '21,958.28', '22,010.82', '22,010.82', '1,816,444,100']
379
21,958.28
380
22,127.38
381
21,958.28
382
22,010.82
383
22,010.82
384
1,816,444,100
385
Nov 13, 2015
['2015-11-13', '22,494.09', '22,519.33', '22,318.62', '22,396.14', '22,396.14', '2,002,495,500']
386
22,494.09
387
22,519.33
388
22,318.62
389
22,396.14
390
22,396.14
391
2,002,495,500
392
Nov 12, 2015
['2015-11-12', '22,477.60', '22,980.97', '22,454.96', '22,888.92', '22,888.92', '1,844,259,100']
393
22,477.60
394
22,980.97
395
22,454.96
396
22,888.92
397
22,888.92
398
1,844,259,100
399
Nov 11, 2015
['2015-11-11', '22,394.15', '22,479.46', '22,324.41', '22,352.17', '22,352.17', '1,419,265,500']
400
22,394.15
401
22,479.46
402
22,324.41
403
22,352.17
404
22,352.17
405
1,419,265,500
406
Nov 10, 2015
['2015-11-10', '22,505.70', '22,534.92', '22,339.69', '22,401.70', '22,401.70', '1,796,811,200']
407
22,505.70
408
22,534.92
409
22,339.69
410
22,401.70
411
22,401.70
412
1,796,811,200
413
Nov 09, 2015
['2015-11-09', '22,753.51', '22,970.83', '22,689.26', '22,726.77', '22,726.77', '1,544,945,200']
414
22,753.51
415
22,970.83
416
22,689.26
417
22,726.77
418
22,726.77
419
1,544,945,200
420
Nov 06, 2015
['2015-11-06', '22,914.20', '22,922.79', '22,791.91', '22,867.33', '22,867.33', '1,394,990,300']
421
22,914.20
422
22,922.79
423
22,791.91
424
22,867.33
425
22,867.33
426
1,394,990,300
427
Nov 05, 2015
['2015-11-05', '23,045.10', '23,180.27', '22,960.62', '23,051.04', '23,051.04', '1,502,715,700']
428
23,045.10
429
23,180.27
430
22,960.62
431
23,051.04
432
23,051.04
433
1,502,715,700
434
Nov 04, 2015
['2015-11-04', '22,737.44', '23,342.07', '22,737.44', '23,053.57', '23,053.57', '2,604,074,100']
435
22,737.44
436
23,342.07
437
22,737.44
438
23,053.57
439
23,053.57
440
2,604,074,100
441
Nov 03, 2015
['2015-11-03', '22,603.15', '22,697.00', '22,560.17', '22,568.43', '22,568.43', '1,469,567,800']
442
22,603.15
443
22,697.00
444
22,560.17
445
22,568.43
446
22,568.43
447
1,469,567,800
448
Nov 02, 2015
['2015-11-02', '22,502.28', '22,605.80', '22,332.71', '22,370.04', '22,370.04', '-']
449
22,502.28
450
22,605.80
451
22,332.71
452
22,370.04
453
22,370.04
454
-
455
Oct 30, 2015
['2015-10-30', '22,785.86', '22,847.16', '22,612.56', '22,640.04', '22,640.04', '1,537,138,400']
456
22,785.86
457
22,847.16
458
22,612.56
459
22,640.04
460
22,640.04
461
1,537,138,400
462
Oct 29, 2015
['2015-10-29', '23,054.53', '23,054.53', '22,811.32', '22,819.94', '22,819.94', '1,759,025,000']
463
23,054.53
464
23,054.53
465
22,811.32
466
22,819.94
467
22,819.94
468
1,759,025,000
469
Oct 28, 2015
['2015-10-28', '23,070.70', '23,120.25', '22,923.66', '22,956.57', '22,956.57', '1,377,130,700']
470
23,070.70
471
23,120.25
472
22,923.66
473
22,956.57
474
22,956.57
475
1,377,130,700
476
Oct 27, 2015
['2015-10-27', '23,053.12', '23,143.88', '22,885.22', '23,142.73', '23,142.73', '1,532,532,100']
477
23,053.12
478
23,143.88
479
22,885.22
480
23,142.73
481
23,142.73
482
1,532,532,100
483
Oct 26, 2015
['2015-10-26', '23,423.64', '23,423.64', '23,066.94', '23,116.25', '23,116.25', '1,465,182,800']
484
23,423.64
485
23,423.64
486
23,066.94
487
23,116.25
488
23,116.25
489
1,465,182,800
490
Oct 23, 2015
['2015-10-23', '23,220.38', '23,220.38', '23,088.03', '23,151.94', '23,151.94', '1,495,348,200']
491
23,220.38
492
23,220.38
493
23,088.03
494
23,151.94
495
23,151.94
496
1,495,348,200
497
Oct 22, 2015
['2015-10-22', '22,795.58', '22,869.59', '22,727.59', '22,845.37', '22,845.37', '1,374,140,600']
498
22,795.58
499
22,869.59
500
22,727.59
501
22,845.37
502
22,845.37
503
1,374,140,600
504
Oct 20, 2015
['2015-10-20', '22,991.60', '23,057.93', '22,843.04', '22,989.22', '22,989.22', '1,217,365,400']
505
22,991.60
506
23,057.93
507
22,843.04
508
22,989.22
509
22,989.22
510
1,217,365,400
511
Oct 19, 2015
['2015-10-19', '23,085.61', '23,100.66', '22,913.60', '23,075.61', '23,075.61', '1,259,219,800']
512
23,085.61
513
23,100.66
514
22,913.60
515
23,075.61
516
23,075.61
517
1,259,219,800
518
Oct 16, 2015
['2015-10-16', '23,133.59', '23,178.14', '22,953.56', '23,067.37', '23,067.37', '1,922,580,500']
519
23,133.59
520
23,178.14
521
22,953.56
522
23,067.37
523
23,067.37
524
1,922,580,500
525
Oct 15, 2015
['2015-10-15', '22,667.42', '22,940.25', '22,567.65', '22,888.17', '22,888.17', '1,920,825,800']
526
22,667.42
527
22,940.25
528
22,567.65
529
22,888.17
530
22,888.17
531
1,920,825,800
532
Oct 14, 2015
['2015-10-14', '22,398.82', '22,576.50', '22,356.56', '22,439.91', '22,439.91', '1,352,740,800']
533
22,398.82
534
22,576.50
535
22,356.56
536
22,439.91
537
22,439.91
538
1,352,740,800
539
Oct 13, 2015
['2015-10-13', '22,677.60', '22,798.90', '22,515.73', '22,600.46', '22,600.46', '1,710,895,100']
540
22,677.60
541
22,798.90
542
22,515.73
543
22,600.46
544
22,600.46
545
1,710,895,100
546
Oct 12, 2015
['2015-10-12', '22,614.33', '22,779.50', '22,562.26', '22,730.93', '22,730.93', '1,871,862,800']
547
22,614.33
548
22,779.50
549
22,562.26
550
22,730.93
551
22,730.93
552
1,871,862,800
553
Oct 09, 2015
['2015-10-09', '22,615.94', '22,807.86', '22,440.88', '22,458.80', '22,458.80', '2,403,310,800']
554
22,615.94
555
22,807.86
556
22,440.88
557
22,458.80
558
22,458.80
559
2,403,310,800
560
Oct 08, 2015
['2015-10-08', '22,588.69', '22,588.69', '22,201.11', '22,354.91', '22,354.91', '1,931,209,500']
561
22,588.69
562
22,588.69
563
22,201.11
564
22,354.91
565
22,354.91
566
1,931,209,500
567
Oct 07, 2015
['2015-10-07', '21,884.73', '22,527.79', '21,817.42', '22,515.76', '22,515.76', '2,932,824,400']
568
21,884.73
569
22,527.79
570
21,817.42
571
22,515.76
572
22,515.76
573
2,932,824,400
574
Oct 06, 2015
['2015-10-06', '22,169.10', '22,169.10', '21,719.29', '21,831.62', '21,831.62', '1,622,570,500']
575
22,169.10
576
22,169.10
577
21,719.29
578
21,831.62
579
21,831.62
580
1,622,570,500
581
Oct 05, 2015
['2015-10-05', '21,930.97', '21,980.84', '21,739.90', '21,854.50', '21,854.50', '1,468,789,300']
582
21,930.97
583
21,980.84
584
21,739.90
585
21,854.50
586
21,854.50
587
1,468,789,300
588
Oct 02, 2015
['2015-10-02', '21,172.94', '21,530.80', '21,130.11', '21,506.09', '21,506.09', '2,161,215,700']
589
21,172.94
590
21,530.80
591
21,130.11
592
21,506.09
593
21,506.09
594
2,161,215,700
595
Sep 30, 2015
['2015-09-30', '20,795.93', '20,939.39', '20,683.11', '20,846.30', '20,846.30', '2,134,506,700']
596
20,795.93
597
20,939.39
598
20,683.11
599
20,846.30
600
20,846.30
601
2,134,506,700
602
Sep 29, 2015
['2015-09-29', '20,579.22', '20,579.22', '20,368.12', '20,556.60', '20,556.60', '2,536,957,700']
603
20,579.22
604
20,579.22
605
20,368.12
606
20,556.60
607
20,556.60
608
2,536,957,700
609
Sep 25, 2015
['2015-09-25', '21,070.39', '21,318.33', '20,957.99', '21,186.32', '21,186.32', '1,728,956,700']
610
21,070.39
611
21,318.33
612
20,957.99
613
21,186.32
614
21,186.32
615
1,728,956,700
616
Sep 24, 2015
['2015-09-24', '21,304.90', '21,363.21', '21,053.50', '21,095.98', '21,095.98', '1,596,740,300']
617
21,304.90
618
21,363.21
619
21,053.50
620
21,095.98
621
21,095.98
622
1,596,740,300
623
Sep 23, 2015
['2015-09-23', '21,529.47', '21,577.45', '21,008.61', '21,302.91', '21,302.91', '2,304,513,300']
624
21,529.47
625
21,577.45
626
21,008.61
627
21,302.91
628
21,302.91
629
2,304,513,300
630
Sep 22, 2015
['2015-09-22', '21,794.34', '22,111.67', '21,768.98', '21,796.58', '21,796.58', '1,438,158,500']
631
21,794.34
632
22,111.67
633
21,768.98
634
21,796.58
635
21,796.58
636
1,438,158,500
637
Sep 21, 2015
['2015-09-21', '21,614.43', '21,778.06', '21,590.70', '21,756.93', '21,756.93', '1,372,777,800']
638
21,614.43
639
21,778.06
640
21,590.70
641
21,756.93
642
21,756.93
643
1,372,777,800
644
Sep 18, 2015
['2015-09-18', '21,807.25', '22,052.11', '21,807.25', '21,920.83', '21,920.83', '2,054,752,700']
645
21,807.25
646
22,052.11
647
21,807.25
648
21,920.83
649
21,920.83
650
2,054,752,700
651
Sep 17, 2015
['2015-09-17', '22,172.68', '22,203.36', '21,718.71', '21,854.63', '21,854.63', '2,118,628,500']
652
22,172.68
653
22,203.36
654
21,718.71
655
21,854.63
656
21,854.63
657
2,118,628,500
658
Sep 16, 2015
['2015-09-16', '21,731.34', '22,103.06', '21,608.50', '21,966.66', '21,966.66', '2,077,633,300']
659
21,731.34
660
22,103.06
661
21,608.50
662
21,966.66
663
21,966.66
664
2,077,633,300
665
Sep 15, 2015
['2015-09-15', '21,527.53', '21,634.48', '21,411.17', '21,455.23', '21,455.23', '1,352,205,800']
666
21,527.53
667
21,634.48
668
21,411.17
669
21,455.23
670
21,455.23
671
1,352,205,800
672
Sep 14, 2015
['2015-09-14', '21,678.88', '21,762.15', '21,441.71', '21,561.90', '21,561.90', '1,472,113,700']
673
21,678.88
674
21,762.15
675
21,441.71
676
21,561.90
677
21,561.90
678
1,472,113,700
679
Sep 11, 2015
['2015-09-11', '21,710.13', '21,909.82', '21,472.16', '21,504.37', '21,504.37', '2,371,639,300']
680
21,710.13
681
21,909.82
682
21,472.16
683
21,504.37
684
21,504.37
685
2,371,639,300
686
Sep 10, 2015
['2015-09-10', '21,667.86', '21,771.57', '21,492.09', '21,562.50', '21,562.50', '2,092,595,900']
687
21,667.86
688
21,771.57
689
21,492.09
690
21,562.50
691
21,562.50
692
2,092,595,900
693
Sep 09, 2015
['2015-09-09', '21,632.69', '22,228.59', '21,529.81', '22,131.31', '22,131.31', '2,945,626,500']
694
21,632.69
695
22,228.59
696
21,529.81
697

[]
[]
701
[]
[]
0
Oct 02, 2015
['2015-10-02', '21,172.94', '21,530.80', '21,130.11', '21,506.09', '21,506.09', '2,161,215,700']
1
21,172.94
2
21,530.80
3
21,130.11
4
21,506.09
5
21,506.09
6
2,161,215,700
7
Sep 30, 2015
['2015-09-30', '20,795.93', '20,939.39', '20,683.11', '20,846.30', '20,846.30', '2,134,506,700']
8
20,795.93
9
20,939.39
10
20,683.11
11
20,846.30
12
20,846.30
13
2,134,506,700
14
Sep 29, 2015
['2015-09-29', '20,579.22', '20,579.22', '20,368.12', '20,556.60', '20,556.60', '2,536,957,700']
15
20,579.22
16
20,579.22
17
20,368.12
18
20,556.60
19
20,556.60
20
2,536,957,700
21
Sep 25, 2015
['2015-09-25', '21,070.39', '21,318.33', '20,957.99', '21,186.32', '21,186.32', '1,728,956,700']
22
21,070.39
23
21,318.33
24
20,957.99
25
21,186.32
26
21,186.32
27
1,728,956,700
28
Sep 24, 2015
['2015-09-24', '21,304.90', '21,363.21', '21,053.50', '21,095.98', '21,095.98', '1,596,740,300']
29
21,304.90
30
21,363.21
31
21,053.50
32
21,095.98
33
21,095.98
34
1,596,740,300
35
Sep 23, 2015
['2015-09-23', '21,529.47', '21,577.45', '21,008.61', '21,302.91', '21,302.91', '2,304,513,300']
36
21,529.47
37
21,577.45
38
21,008.61
39
21,302.91
40
21,302.91
41
2,304,513,300
42
Sep 22, 2015
['2015-09-22', '21,794.34', '22,111.67', '21,768.98', '21,796.58', '21,796.58', '1,438,158,500']
43
21,794.34
44
22,111.67
45
21,768.98
46
21,796.58
47
21,796.58
48
1,438,158,500
49
Sep 21, 2015
['2015-09-21', '21,614.43', '21,778.06', '21,590.70', '21,756.93', '21,756.93', '1,372,777,800']
50
21,614.43
51
21,778.06
52
21,590.70
53
21,756.93
54
21,756.93
55
1,372,777,800
56
Sep 18, 2015
['2015-09-18', '21,807.25', '22,052.11', '21,807.25', '21,920.83', '21,920.83', '2,054,752,700']
57
21,807.25
58
22,052.11
59
21,807.25
60
21,920.83
61
21,920.83
62
2,054,752,700
63
Sep 17, 2015
['2015-09-17', '22,172.68', '22,203.36', '21,718.71', '21,854.63', '21,854.63', '2,118,628,500']
64
22,172.68
65
22,203.36
66
21,718.71
67
21,854.63
68
21,854.63
69
2,118,628,500
70
Sep 16, 2015
['2015-09-16', '21,731.34', '22,103.06', '21,608.50', '21,966.66', '21,966.66', '2,077,633,300']
71
21,731.34
72
22,103.06
73
21,608.50
74
21,966.66
75
21,966.66
76
2,077,633,300
77
Sep 15, 2015
['2015-09-15', '21,527.53', '21,634.48', '21,411.17', '21,455.23', '21,455.23', '1,352,205,800']
78
21,527.53
79
21,634.48
80
21,411.17
81
21,455.23
82
21,455.23
83
1,352,205,800
84
Sep 14, 2015
['2015-09-14', '21,678.88', '21,762.15', '21,441.71', '21,561.90', '21,561.90', '1,472,113,700']
85
21,678.88
86
21,762.15
87
21,441.71
88
21,561.90
89
21,561.90
90
1,472,113,700
91
Sep 11, 2015
['2015-09-11', '21,710.13', '21,909.82', '21,472.16', '21,504.37', '21,504.37', '2,371,639,300']
92
21,710.13
93
21,909.82
94
21,472.16
95
21,504.37
96
21,504.37
97
2,371,639,300
98
Sep 10, 2015
['2015-09-10', '21,667.86', '21,771.57', '21,492.09', '21,562.50', '21,562.50', '2,092,595,900']
99
21,667.86
100
21,771.57
101
21,492.09
102
21,562.50
103
21,562.50
104
2,092,595,900
105
Sep 09, 2015
['2015-09-09', '21,632.69', '22,228.59', '21,529.81', '22,131.31', '22,131.31', '2,945,626,500']
106
21,632.69
107
22,228.59
108
21,529.81
109
22,131.31
110
22,131.31
111
2,945,626,500
112
Sep 08, 2015
['2015-09-08', '20,636.83', '21,431.99', '20,524.88', '21,259.04', '21,259.04', '2,266,169,400']
113
20,636.83
114
21,431.99
115
20,524.88
116
21,259.04
117
21,259.04
118
2,266,169,400
119
Sep 07, 2015
['2015-09-07', '20,683.31', '21,056.39', '20,579.93', '20,583.52', '20,583.52', '1,656,172,300']
120
20,683.31
121
21,056.39
122
20,579.93
123
20,583.52
124
20,583.52
125
1,656,172,300
126
Sep 04, 2015
['2015-09-04', '21,158.93', '21,174.86', '20,715.02', '20,840.61', '20,840.61', '2,120,922,200']
127
21,158.93
128
21,174.86
129
20,715.02
130
20,840.61
131
20,840.61
132
2,120,922,200
133
Sep 02, 2015
['2015-09-02', '21,101.42', '21,288.53', '20,771.77', '20,934.94', '20,934.94', '2,512,620,100']
134
21,101.42
135
21,288.53
136
20,771.77
137
20,934.94
138
20,934.94
139
2,512,620,100
140
Sep 01, 2015
['2015-09-01', '21,692.78', '21,692.78', '21,170.86', '21,185.43', '21,185.43', '2,155,988,500']
141
21,692.78
142
21,692.78
143
21,170.86
144
21,185.43
145
21,185.43
146
2,155,988,500
147
Aug 31, 2015
['2015-08-31', '21,793.02', '21,793.02', '21,399.62', '21,670.58', '21,670.58', '2,686,630,600']
148
21,793.02
149
21,793.02
150
21,399.62
151
21,670.58
152
21,670.58
153
2,686,630,600
154
Aug 28, 2015
['2015-08-28', '22,424.40', '22,424.40', '21,585.33', '21,612.39', '21,612.39', '3,009,422,400']
155
22,424.40
156
22,424.40
157
21,585.33
158
21,612.39
159
21,612.39
160
3,009,422,400
161
Aug 27, 2015
['2015-08-27', '21,758.62', '21,963.43', '21,407.59', '21,838.54', '21,838.54', '3,192,968,200']
162
21,758.62
163
21,963.43
164
21,407.59
165
21,838.54
166
21,838.54
167
3,192,968,200
168
Aug 26, 2015
['2015-08-26', '21,434.25', '21,686.45', '21,060.09', '21,080.39', '21,080.39', '2,956,076,900']
169
21,434.25
170
21,686.45
171
21,060.09
172
21,080.39
173
21,080.39
174
2,956,076,900
175
Aug 25, 2015
['2015-08-25', '21,119.53', '21,871.40', '20,865.26', '21,404.96', '21,404.96', '3,588,835,100']
176
21,119.53
177
21,871.40
178
20,865.26
179
21,404.96
180
21,404.96
181
3,588,835,100
182
Aug 24, 2015
['2015-08-24', '21,605.97', '21,679.45', '21,136.48', '21,251.57', '21,251.57', '3,579,922,600']
183
21,605.97
184
21,679.45
185
21,136.48
186
21,251.57
187
21,251.57
188
3,579,922,600
189
Aug 21, 2015
['2015-08-21', '22,343.25', '22,492.79', '22,185.85', '22,409.62', '22,409.62', '2,490,613,900']
190
22,343.25
191
22,492.79
192
22,185.85
193
22,409.62
194
22,409.62
195
2,490,613,900
196
Aug 20, 2015
['2015-08-20', '22,973.87', '23,033.97', '22,610.53', '22,757.47', '22,757.47', '2,339,044,200']
197
22,973.87
198
23,033.97
199
22,610.53
200
22,757.47
201
22,757.47
202
2,339,044,200
203
Aug 19, 2015
['2015-08-19', '23,555.02', '23,586.79', '23,138.73', '23,167.85', '23,167.85', '1,914,775,100']
204
23,555.02
205
23,586.79
206
23,138.73
207
23,167.85
208
23,167.85
209
1,914,775,100
210
Aug 18, 2015
['2015-08-18', '23,956.86', '24,024.37', '23,464.35', '23,474.97', '23,474.97', '1,454,347,800']
211
23,956.86
212
24,024.37
213
23,464.35
214
23,474.97
215
23,474.97
216
1,454,347,800
217
Aug 17, 2015
['2015-08-17', '23,945.60', '23,950.57', '23,699.84', '23,814.65', '23,814.65', '1,197,838,600']
218
23,945.60
219
23,950.57
220
23,699.84
221
23,814.65
222
23,814.65
223
1,197,838,600
224
Aug 14, 2015
['2015-08-14', '24,055.02', '24,126.30', '23,957.36', '23,991.03', '23,991.03', '1,198,083,100']
225
24,055.02
226
24,126.30
227
23,957.36
228
23,991.03
229
23,991.03
230
1,198,083,100
231
Aug 13, 2015
['2015-08-13', '23,935.48', '24,133.87', '23,860.82', '24,018.80', '24,018.80', '1,716,745,000']
232
23,935.48
233
24,133.87
234
23,860.82
235
24,018.80
236
24,018.80
237
1,716,745,000
238
Aug 12, 2015
['2015-08-12', '24,269.11', '24,324.19', '23,826.96', '23,916.02', '23,916.02', '1,851,647,500']
239
24,269.11
240
24,324.19
241
23,826.96
242
23,916.02
243
23,916.02
244
1,851,647,500
245
Aug 11, 2015
['2015-08-11', '24,694.78', '24,924.07', '24,420.71', '24,498.21', '24,498.21', '1,608,447,800']
246
24,694.78
247
24,924.07
248
24,420.71
249
24,498.21
250
24,498.21
251
1,608,447,800
252
Aug 10, 2015
['2015-08-10', '24,433.66', '24,602.67', '24,135.64', '24,521.12', '24,521.12', '1,211,647,200']
253
24,433.66
254
24,602.67
255
24,135.64
256
24,521.12
257
24,521.12
258
1,211,647,200
259
Aug 07, 2015
['2015-08-07', '24,327.56', '24,641.93', '24,327.56', '24,552.47', '24,552.47', '1,106,892,000']
260
24,327.56
261
24,641.93
262
24,327.56
263
24,552.47
264
24,552.47
265
1,106,892,000
266
Aug 06, 2015
['2015-08-06', '24,527.74', '24,527.74', '24,320.75', '24,375.28', '24,375.28', '977,477,100']
267
24,527.74
268
24,527.74
269
24,320.75
270
24,375.28
271
24,375.28
272
977,477,100
273
Aug 05, 2015
['2015-08-05', '24,466.30', '24,582.19', '24,420.95', '24,514.16', '24,514.16', '1,105,419,800']
274
24,466.30
275
24,582.19
276
24,420.95
277
24,514.16
278
24,514.16
279
1,105,419,800
280
Aug 04, 2015
['2015-08-04', '24,364.41', '24,519.35', '24,217.78', '24,406.12', '24,406.12', '1,225,548,200']
281
24,364.41
282
24,519.35
283
24,217.78
284
24,406.12
285
24,406.12
286
1,225,548,200
287
Aug 03, 2015
['2015-08-03', '24,533.14', '24,533.14', '24,232.60', '24,411.42', '24,411.42', '1,466,970,000']
288
24,533.14
289
24,533.14
290
24,232.60
291
24,411.42
292
24,411.42
293
1,466,970,000
294
Jul 31, 2015
['2015-07-31', '24,650.93', '24,661.19', '24,467.83', '24,636.28', '24,636.28', '1,363,737,600']
295
24,650.93
296
24,661.19
297
24,467.83
298
24,636.28
299
24,636.28
300
1,363,737,600
301
Jul 30, 2015
['2015-07-30', '24,822.42', '24,872.70', '24,478.07', '24,497.98', '24,497.98', '1,488,228,200']
302
24,822.42
303
24,872.70
304
24,478.07
305
24,497.98
306
24,497.98
307
1,488,228,200
308
Jul 29, 2015
['2015-07-29', '24,630.44', '24,718.64', '24,444.47', '24,619.45', '24,619.45', '1,350,559,500']
309
24,630.44
310
24,718.64
311
24,444.47
312
24,619.45
313
24,619.45
314
1,350,559,500
315
Jul 28, 2015
['2015-07-28', '24,269.90', '24,947.35', '24,140.62', '24,503.94', '24,503.94', '2,134,225,400']
316
24,269.90
317
24,947.35
318
24,140.62
319
24,503.94
320
24,503.94
321
2,134,225,400
322
Jul 27, 2015
['2015-07-27', '24,906.78', '24,908.58', '24,282.21', '24,351.96', '24,351.96', '2,317,678,800']
323
24,906.78
324
24,908.58
325
24,282.21
326
24,351.96
327
24,351.96
328
2,317,678,800
329
Jul 24, 2015
['2015-07-24', '25,279.95', '25,279.95', '25,073.20', '25,128.51', '25,128.51', '1,134,624,200']
330
25,279.95
331
25,279.95
332
25,073.20
333
25,128.51
334
25,128.51
335
1,134,624,200
336
Jul 23, 2015
['2015-07-23', '25,308.55', '25,500.99', '25,250.36', '25,398.85', '25,398.85', '1,130,615,300']
337
25,308.55
338
25,500.99
339
25,250.36
340
25,398.85
341
25,398.85
342
1,130,615,300
343
Jul 22, 2015
['2015-07-22', '25,401.79', '25,401.79', '25,177.60', '25,282.62', '25,282.62', '1,298,894,500']
344
25,401.79
345
25,401.79
346
25,177.60
347
25,282.62
348
25,282.62
349
1,298,894,500
350
Jul 21, 2015
['2015-07-21', '25,428.88', '25,634.32', '25,342.69', '25,536.43', '25,536.43', '1,125,389,100']
351
25,428.88
352
25,634.32
353
25,342.69
354
25,536.43
355
25,536.43
356
1,125,389,100
357
Jul 20, 2015
['2015-07-20', '25,540.31', '25,540.31', '25,298.96', '25,404.81', '25,404.81', '1,088,244,600']
358
25,540.31
359
25,540.31
360
25,298.96
361
25,404.81
362
25,404.81
363
1,088,244,600
364
Jul 17, 2015
['2015-07-17', '25,246.64', '25,517.45', '25,183.86', '25,415.27', '25,415.27', '1,279,509,000']
365
25,246.64
366
25,517.45
367
25,183.86
368
25,415.27
369
25,415.27
370
1,279,509,000
371
Jul 16, 2015
['2015-07-16', '24,976.08', '25,170.35', '24,841.14', '25,162.78', '25,162.78', '1,386,159,700']
372
24,976.08
373
25,170.35
374
24,841.14
375
25,162.78
376
25,162.78
377
1,386,159,700
378
Jul 15, 2015
['2015-07-15', '25,219.45', '25,219.45', '24,862.65', '25,055.76', '25,055.76', '1,603,476,600']
379
25,219.45
380
25,219.45
381
24,862.65
382
25,055.76
383
25,055.76
384
1,603,476,600
385
Jul 14, 2015
['2015-07-14', '25,184.06', '25,250.95', '24,906.47', '25,120.91', '25,120.91', '2,129,805,300']
386
25,184.06
387
25,250.95
388
24,906.47
389
25,120.91
390
25,120.91
391
2,129,805,300
392
Jul 13, 2015
['2015-07-13', '24,709.58', '25,275.76', '24,596.44', '25,224.01', '25,224.01', '2,124,810,600']
393
24,709.58
394
25,275.76
395
24,596.44
396
25,224.01
397
25,224.01
398
2,124,810,600
399
Jul 10, 2015
['2015-07-10', '24,567.92', '25,015.17', '24,567.92', '24,901.28', '24,901.28', '3,230,873,300']
400
24,567.92
401
25,015.17
402
24,567.92
403
24,901.28
404
24,901.28
405
3,230,873,300
406
Jul 09, 2015
['2015-07-09', '23,435.50', '24,695.75', '23,332.90', '24,392.79', '24,392.79', '4,266,946,400']
407
23,435.50
408
24,695.75
409
23,332.90
410
24,392.79
411
24,392.79
412
4,266,946,400
413
Jul 08, 2015
['2015-07-08', '24,411.30', '24,411.30', '22,836.82', '23,516.56', '23,516.56', '5,441,410,900']
414
24,411.30
415
24,411.30
416
22,836.82
417
23,516.56
418
23,516.56
419
5,441,410,900
420
Jul 07, 2015
['2015-07-07', '25,391.76', '25,439.34', '24,819.26', '24,975.31', '24,975.31', '3,020,385,200']
421
25,391.76
422
25,439.34
423
24,819.26
424
24,975.31
425
24,975.31
426
3,020,385,200
427
Jul 06, 2015
['2015-07-06', '26,083.99', '26,261.53', '24,750.31', '25,236.28', '25,236.28', '3,514,118,700']
428
26,083.99
429
26,261.53
430
24,750.31
431
25,236.28
432
25,236.28
433
3,514,118,700
434
Jul 03, 2015
['2015-07-03', '26,349.84', '26,402.85', '25,933.12', '26,064.11', '26,064.11', '1,888,925,900']
435
26,349.84
436
26,402.85
437
25,933.12
438
26,064.11
439
26,064.11
440
1,888,925,900
441
Jul 02, 2015
['2015-07-02', '26,459.43', '26,459.43', '26,135.62', '26,282.32', '26,282.32', '2,185,444,300']
442
26,459.43
443
26,459.43
444
26,135.62
445
26,282.32
446
26,282.32
447
2,185,444,300
448
Jun 30, 2015
['2015-06-30', '25,944.03', '26,470.44', '25,885.66', '26,250.03', '26,250.03', '2,480,821,500']
449
25,944.03
450
26,470.44
451
25,885.66
452
26,250.03
453
26,250.03
454
2,480,821,500
455
Jun 29, 2015
['2015-06-29', '26,560.13', '26,631.51', '25,617.78', '25,966.98', '25,966.98', '3,023,218,900']
456
26,560.13
457
26,631.51
458
25,617.78
459
25,966.98
460
25,966.98
461
3,023,218,900
462
Jun 26, 2015
['2015-06-26', '27,016.09', '27,016.09', '26,522.45', '26,663.87', '26,663.87', '2,473,398,200']
463
27,016.09
464
27,016.09
465
26,522.45
466
26,663.87
467
26,663.87
468
2,473,398,200
469
Jun 25, 2015
['2015-06-25', '27,329.17', '27,350.49', '27,120.72', '27,145.75', '27,145.75', '1,908,078,300']
470
27,329.17
471
27,350.49
472
27,120.72
473
27,145.75
474
27,145.75
475
1,908,078,300
476
Jun 24, 2015
['2015-06-24', '27,397.37', '27,470.50', '27,292.85', '27,404.97', '27,404.97', '1,659,067,500']
477
27,397.37
478
27,470.50
479
27,292.85
480
27,404.97
481
27,404.97
482
1,659,067,500
483
Jun 23, 2015
['2015-06-23', '27,126.47', '27,406.41', '27,008.51', '27,333.46', '27,333.46', '2,138,105,800']
484
27,126.47
485
27,406.41
486
27,008.51
487
27,333.46
488
27,333.46
489
2,138,105,800
490
Jun 22, 2015
['2015-06-22', '26,854.32', '27,166.52', '26,811.66', '27,080.85', '27,080.85', '1,429,174,800']
491
26,854.32
492
27,166.52
493
26,811.66
494
27,080.85
495
27,080.85
496
1,429,174,800
497
Jun 19, 2015
['2015-06-19', '26,885.73', '27,011.95', '26,701.72', '26,760.53', '26,760.53', '2,497,578,900']
498
26,885.73
499
27,011.95
500
26,701.72
501
26,760.53
502
26,760.53
503
2,497,578,900
504
Jun 18, 2015
['2015-06-18', '26,786.53', '26,873.67', '26,595.96', '26,694.66', '26,694.66', '1,469,953,200']
505
26,786.53
506
26,873.67
507
26,595.96
508
26,694.66
509
26,694.66
510
1,469,953,200
511
Jun 17, 2015
['2015-06-17', '26,671.20', '26,880.79', '26,555.96', '26,753.79', '26,753.79', '1,819,404,400']
512
26,671.20
513
26,880.79
514
26,555.96
515
26,753.79
516
26,753.79
517
1,819,404,400
518
Jun 16, 2015
['2015-06-16', '26,807.67', '26,892.88', '26,553.04', '26,566.70', '26,566.70', '1,761,927,200']
519
26,807.67
520
26,892.88
521
26,553.04
522
26,566.70
523
26,566.70
524
1,761,927,200
525
Jun 15, 2015
['2015-06-15', '27,095.18', '27,131.36', '26,841.52', '26,861.81', '26,861.81', '1,324,712,200']
526
27,095.18
527
27,131.36
528
26,841.52
529
26,861.81
530
26,861.81
531
1,324,712,200
532
Jun 12, 2015
['2015-06-12', '27,082.60', '27,356.51', '26,987.52', '27,280.54', '27,280.54', '1,734,157,900']
533
27,082.60
534
27,356.51
535
26,987.52
536
27,280.54
537
27,280.54
538
1,734,157,900
539
Jun 11, 2015
['2015-06-11', '26,938.15', '26,991.51', '26,839.43', '26,907.85', '26,907.85', '1,670,581,300']
540
26,938.15
541
26,991.51
542
26,839.43
543
26,907.85
544
26,907.85
545
1,670,581,300
546
Jun 10, 2015
['2015-06-10', '27,052.79', '27,116.92', '26,573.96', '26,687.64', '26,687.64', '1,977,373,500']
547
27,052.79
548
27,116.92
549
26,573.96
550
26,687.64
551
26,687.64
552
1,977,373,500
553
Jun 09, 2015
['2015-06-09', '27,295.88', '27,322.14', '26,971.57', '26,989.52', '26,989.52', '2,384,116,300']
554
27,295.88
555
27,322.14
556
26,971.57
557
26,989.52
558
26,989.52
559
2,384,116,300
560
Jun 08, 2015
['2015-06-08', '27,147.24', '27,428.59', '27,060.24', '27,316.28', '27,316.28', '2,391,660,200']
561
27,147.24
562
27,428.59
563
27,060.24
564
27,316.28
565
27,316.28
566
2,391,660,200
567
Jun 05, 2015
['2015-06-05', '27,538.06', '27,646.72', '27,211.36', '27,260.16', '27,260.16', '2,228,885,200']
568
27,538.06
569
27,646.72
570
27,211.36
571
27,260.16
572
27,260.16
573
2,228,885,200
574
Jun 04, 2015
['2015-06-04', '27,645.36', '27,854.74', '27,094.50', '27,551.89', '27,551.89', '3,066,127,000']
575
27,645.36
576
27,854.74
577
27,094.50
578
27,551.89
579
27,551.89
580
3,066,127,000
581
Jun 03, 2015
['2015-06-03', '27,716.34', '27,767.23', '27,508.84', '27,657.47', '27,657.47', '1,735,744,700']
582
27,716.34
583
27,767.23
584
27,508.84
585
27,657.47
586
27,657.47
587
1,735,744,700
588
Jun 02, 2015
['2015-06-02', '27,473.45', '27,602.88', '27,348.13', '27,466.72', '27,466.72', '1,502,001,000']
589
27,473.45
590
27,602.88
591
27,348.13
592
27,466.72
593
27,466.72
594
1,502,001,000
595
Jun 01, 2015
['2015-06-01', '27,373.06', '27,766.32', '27,241.95', '27,597.16', '27,597.16', '1,972,936,000']
596
27,373.06
597
27,766.32
598
27,241.95
599
27,597.16
600
27,597.16
601
1,972,936,000
602
May 29, 2015
['2015-05-29', '27,398.28', '27,604.27', '27,255.89', '27,424.19', '27,424.19', '3,050,185,700']
603
27,398.28
604
27,604.27
605
27,255.89
606
27,424.19
607
27,424.19
608
3,050,185,700
609
May 28, 2015
['2015-05-28', '28,162.25', '28,162.25', '27,242.11', '27,454.31', '27,454.31', '3,066,678,800']
610
28,162.25
611
28,162.25
612
27,242.11
613
27,454.31
614
27,454.31
615
3,066,678,800
616
May 27, 2015
['2015-05-27', '28,214.66', '28,214.66', '27,982.14', '28,081.21', '28,081.21', '1,863,591,500']
617
28,214.66
618
28,214.66
619
27,982.14
620
28,081.21
621
28,081.21
622
1,863,591,500
623
May 26, 2015
['2015-05-26', '28,462.32', '28,524.60', '28,237.49', '28,249.86', '28,249.86', '2,672,054,500']
624
28,462.32
625
28,524.60
626
28,237.49
627
28,249.86
628
28,249.86
629
2,672,054,500
630
May 22, 2015
['2015-05-22', '27,723.67', '28,041.32', '27,696.97', '27,992.83', '27,992.83', '1,899,363,800']
631
27,723.67
632
28,041.32
633
27,696.97
634
27,992.83
635
27,992.83
636
1,899,363,800
637
May 21, 2015
['2015-05-21', '27,507.32', '27,611.72', '27,393.31', '27,523.72', '27,523.72', '1,221,508,500']
638
27,507.32
639
27,611.72
640
27,393.31
641
27,523.72
642
27,523.72
643
1,221,508,500
644
May 20, 2015
['2015-05-20', '27,751.44', '27,751.44', '27,490.33', '27,585.05', '27,585.05', '1,470,372,800']
645
27,751.44
646
27,751.44
647
27,490.33
648
27,585.05
649
27,585.05
650
1,470,372,800
651
May 19, 2015
['2015-05-19', '27,597.07', '27,765.55', '27,500.76', '27,693.54', '27,693.54', '1,559,455,500']
652
27,597.07
653
27,765.55
654
27,500.76
655
27,693.54
656
27,693.54
657
1,559,455,500
658
May 18, 2015
['2015-05-18', '27,792.44', '27,792.44', '27,435.57', '27,591.25', '27,591.25', '1,378,791,400']
659
27,792.44
660
27,792.44
661
27,435.57
662
27,591.25
663
27,591.25
664
1,378,791,400
665
May 15, 2015
['2015-05-15', '27,459.58', '27,928.60', '27,315.10', '27,822.28', '27,822.28', '1,754,137,700']
666
27,459.58
667
27,928.60
668
27,315.10
669
27,822.28
670
27,822.28
671
1,754,137,700
672
May 14, 2015
['2015-05-14', '27,395.92', '27,397.67', '27,192.93', '27,286.55', '27,286.55', '1,522,212,900']
673
27,395.92
674
27,397.67
675
27,192.93
676
27,286.55
677
27,286.55
678
1,522,212,900
679
May 13, 2015
['2015-05-13', '27,473.50', '27,524.82', '27,191.03', '27,249.28', '27,249.28', '2,088,818,800']
680
27,473.50
681
27,524.82
682
27,191.03
683
27,249.28
684
27,249.28
685
2,088,818,800
686
May 12, 2015
['2015-05-12', '27,664.18', '27,693.63', '27,395.91', '27,407.18', '27,407.18', '1,530,000,900']
687
27,664.18
688
27,693.63
689
27,395.91
690
27,407.18
691
27,407.18
692
1,530,000,900
693
May 11, 2015

Find ratio

0
0
[]
[]
15
[]
[]
0
Oct 13, 2017
['2017-10-13', '11,312.27', '11,400.05', '11,308.04', '11,399.09', '11,399.09', '93,900']
1
11,312.27
2
11,400.05
3
11,308.04
4
11,399.09
5
11,399.09
6
93,900
7
Oct 12, 2017
['2017-10-12', '-', '-', '-', '-', '-', '-']
8
-
9
-
10
-
11
-
12
-
13
-
14
2
duplicate data
2. Query all tasks
duplicate data
2. Query all tasks

HSI index update and show

In [3]:
import pandas as pd
import numpy as np
from StockObj import StockObj
import matplotlib.pyplot as plt
import sqlite3
abc = StockObj("abc", "%5EHSI")
conn = sqlite3.connect("D:\\stks\\tst.db")
cur = conn.cursor()
cur.execute(
    "SELECT close, stkdate FROM STOCKS where idx = " + "'" + "0700.HK" + 
    "'" + "and stkdate between " + "'" + "2016-01-01" + "'" + "and" + "'" + "2019-04-08" + "'")
num = cur.fetchall()
indlist=[]
for t in num:
    if t[0] == '-':
        continue
    #indlist.append(float(t[0].replace(',', '')))
    indlist.append(t[0])
y=indlist

x=np.arange(start = 0, stop = len(indlist), step = 1)

g610x=[]
g610y=[]

g233x=[]
g233y=[]

for t in x:
    if t > 610:
        g610x.append(t)
        g610y.append(np.average(indlist[t-610:t]))
        
for t in x:
    if t > 233:
        g233x.append(t)
        g233y.append(np.average(indlist[t-233:t]))

fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(x, y, color='lightblue', linewidth=3)
ax.scatter(g610x, g610y, color='green', linewidth=1)
ax.scatter(g233x, g233y, color='red', linewidth=1)
plt.savefig('foo.png')
#plt.xticks(range(1, 30))
plt.show()

AttributeError: 'float' object has no attribute 'replace'